import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createGameServer } from './server/app.mjs';
import { seedWorlds } from './src/worlds.js';
import { readRuntimeConfig } from './server/runtime-config.mjs';
import {readIceRelayConfig} from './server/media-ice.mjs';
const root=dirname(fileURLToPath(import.meta.url));
const runtimeConfig=readRuntimeConfig(process.env,{root});
process.umask(0o077);
const app=createGameServer({database:runtimeConfig.database,dist:resolve(root,'dist'),seeds:seedWorlds,runtimeConfig,iceRelayConfig:readIceRelayConfig(process.env)});
const address=await app.listen(runtimeConfig.port);
const displayHost=runtimeConfig.host.includes(':')?`[${runtimeConfig.host}]`:runtimeConfig.host;
console.log(runtimeConfig.mode==='public'?`Universe private preview listening on ${displayHost}:${address.port}; external TLS and operator provisioning required`:`Universe standalone is ready at http://${displayHost}:${address.port}`);
process.send?.({type:'ready',port:address.port});
let shuttingDown=false;
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,async()=>{if(shuttingDown)return;shuttingDown=true;await app.close();process.exit(0);});
