import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createGameServer} from '../server/app.mjs';import {seedWorlds} from '../src/worlds.js';import {createAction} from '../src/action-schema.js';
async function fixture(database){const app=createGameServer({database,seeds:seedWorlds}),{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;const client=(cookie='')=>({cookie,async call(path,method='GET',body){const r=await fetch(base+path,{method,headers:{Cookie:this.cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};}});const guest=async name=>{const c=client();assert.equal((await c.call('/api/session','POST',{name,woka:0})).status,201);return c;};return {app,client,guest};}
test('ordered item/area actions and stable IDs survive authoritative save, late join and SQLite restart',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'universe-actions-')),database=join(dir,'actions.sqlite');let f=await fixture(database);t.after(async()=>{await f.app.close();await rm(dir,{recursive:true,force:true});});const owner=await f.guest('Action editor');let room=(await owner.call('/api/rooms/commons/join','POST',{})).data.room;
 const actions=['audio','link','message','teleport'].map((type,i)=>({...createAction(type,'stable-'+i),description:'Choice '+i}));actions[0].label='Ambient track';actions[0].volume=0;actions[0].loop=false;actions[1].mode='embed';actions[1].width=35;actions[1].closable=false;
 room.scene.objects[0].actions=actions;room.scene.areas[0].actions=structuredClone(actions).reverse();const saved=await owner.call('/api/rooms/commons/scene','PUT',{revision:room.revision,scene:room.scene});assert.equal(saved.status,200,JSON.stringify(saved.data));const expected=structuredClone(saved.data.room.scene);
 const late=await f.guest('Late visitor');const joined=(await late.call('/api/rooms/commons/join','POST',{})).data.room;assert.deepEqual(joined.scene.objects[0].actions,actions);assert.deepEqual(joined.scene.areas[0].actions,actions.toReversed());assert.equal((await late.call('/api/rooms/commons/scene','PUT',{revision:joined.revision,scene:joined.scene})).status,403);
 const invalid=structuredClone(expected);invalid.objects[0].actions[0].canEditScene=true;assert.equal((await owner.call('/api/rooms/commons/scene','PUT',{revision:saved.data.room.revision,scene:invalid})).status,400);assert.equal((await owner.call('/api/rooms/commons')).data.room.revision,saved.data.room.revision);
 const cookie=owner.cookie;await f.app.close();f=await fixture(database);room=(await f.client(cookie).call('/api/rooms/commons')).data.room;assert.deepEqual(room.scene,expected);assert.deepEqual(room.scene.objects[0].actions.map(a=>a.id),['stable-0','stable-1','stable-2','stable-3']);
});
