/** Real app, HTTP and SSE reconnect with native form/editor/device controls.
 * Local inert audio tracks only; no real devices, media peers or providers. */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createGameServer} from '../server/app.mjs';
import {launch} from '../scripts/browser.mjs';
const scene={version:1,theme:'garden',bounds:{width:24,depth:20},spawn:{x:0,z:5},areas:[],objects:[{id:'form-board',type:'board',name:'Saved board name',x:0,z:3.2,rotation:0,actions:[{id:'form',type:'link',name:'Open retained form',url:'https://arrival-reconnect.invalid/form',mode:'embed',width:30,closable:true}]}]};
const app=createGameServer({database:':memory:',seeds:[{id:'world',name:'Reconnect world',rooms:[{id:'room',name:'Reconnect room',scene}]}],dist:new URL('../dist',import.meta.url).pathname,questsEnabled:false});
const streams=new Set();app.server.on('request',(req,res)=>{if(new URL(req.url,'http://127.0.0.1').pathname==='/api/events'){streams.add(res);res.once('close',()=>streams.delete(res));}});
const {port}=await app.listen(0),base='http://127.0.0.1:'+port,browser=await launch(),context=await browser.newContext({viewport:{width:1600,height:1000},reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(60000);
const checks=[],errors=[],requests=[];let holdResume=false,held=[],frameLoads=0;
page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.url().includes('/api/rooms/room/join'))requests.push(request.postDataJSON());});
await page.addInitScript(()=>{
 window.fixtureTracks=[];window.captureAttempts=0;
 Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async options=>{
  if(!options.audio||options.video)throw Error('Only inert audio fixture allowed');window.captureAttempts++;
  const track={kind:'audio',readyState:'live',enabled:true,stop(){this.readyState='ended';},getSettings(){return{};}};window.fixtureTracks.push(track);return {getTracks:()=>[track],getAudioTracks:()=>[track],getVideoTracks:()=>[]};
 }});
 Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{configurable:true,value:()=>{throw Error('Screen capture prohibited');}});
});
await context.route('https://arrival-reconnect.invalid/form',route=>{frameLoads++;return route.fulfill({contentType:'text/html',body:'<!doctype html><meta charset="utf-8"><label>Unsubmitted note<input aria-label="Unsubmitted note"></label>'});});
await context.route('**/api/rooms/room/join',async route=>{if(!holdResume||route.request().postDataJSON()?.mode!=='resume')return route.continue();const response=await route.fetch();held.push({route,response});});
const state=()=>page.evaluate(()=>window.__universe.getState());
const input=()=>page.frameLocator('iframe.embedded-frame').getByRole('textbox',{name:'Unsubmitted note'});
const check=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
async function disconnect(){assert(streams.size>0);for(const stream of [...streams])stream.end();for(let i=0;!held.length&&i<300;i++)await page.waitForTimeout(20);assert(held.length,'Reconnect starts a held resume request');}
async function release(){holdResume=false;for(const item of held.splice(0))await item.route.fulfill({response:item.response});await page.waitForFunction(()=>!document.querySelector('#editor').inert&&window.__universe.getState().ready);}
try{
 await context.request.post(base+'/api/session',{data:{name:'Reconnect owner'}});await page.goto(base+'/?room=room');await page.waitForFunction(()=>window.__universe?.getState().ready);
 await page.locator('#dock-media').click();await page.locator('.media-join').click();await page.waitForFunction(()=>document.querySelector('.media-join')?.textContent==='Leave audio');await page.locator('[data-media="microphone"]').click();await page.waitForFunction(()=>document.querySelector('[data-media="microphone"]')?.getAttribute('aria-pressed')==='true');await page.locator('#dock-media').click();
 await page.locator('#interact').click();await page.locator('#dialog-actions').getByRole('button',{name:'Open retained form',exact:true}).click();await input().fill('Keep this unsubmitted form');const frame=await page.locator('iframe.embedded-frame').elementHandle();
 await page.locator('#dock-build').click();const point=await page.evaluate(()=>window.__universe.getScreenPoint(0,3.2,1));assert(point?.visible);await page.mouse.click(point.x,point.y);await page.waitForFunction(()=>window.__universe.getEditor().selected==='form-board');
 const section=page.locator('[data-section="item-properties"]');if(!await section.evaluate(node=>node.open))await section.locator('summary').click();const name=page.locator('[data-focus-key="Name"]');await name.fill('My unsaved board draft');await name.press('Tab');await page.waitForFunction(()=>window.__universe.getEditor().dirty);const before=await state(),beforeHistory=await page.evaluate(()=>({state:history.state,url:location.href,length:history.length}));
 await name.focus();await name.press('ArrowLeft');const focusBefore=await name.evaluate(node=>({start:node.selectionStart,end:node.selectionEnd}));assert.equal(await page.evaluate(()=>fixtureTracks[0]?.readyState),'live');holdResume=true;await disconnect();assert.equal(await page.locator('#editor').isVisible(),true);assert.equal(await page.evaluate(()=>window.__universe.getEditor().dirty),true);assert.equal(await input().inputValue(),'Keep this unsubmitted form');assert.equal(await page.evaluate(()=>fixtureTracks[0].readyState),'live');await release();
 let current=await state();assert.equal(current.scene.objects[0].name,'My unsaved board draft');assert.equal(current.room.scene.objects[0].name,'Saved board name');assert.equal(await page.evaluate(()=>window.__universe.getEditor().dirty),true);assert.equal(await page.locator('#editor').isVisible(),true);assert.equal(current.admissionId,before.admissionId);assert.deepEqual(current.position,before.position);assert.deepEqual(await page.evaluate(()=>({state:history.state,url:location.href,length:history.length})),beforeHistory);assert(await frame.evaluate(node=>node.isConnected&&node===document.querySelector('iframe.embedded-frame')));assert.equal(await input().inputValue(),'Keep this unsubmitted form');assert.equal(frameLoads,1);assert.equal(await name.evaluate(node=>document.activeElement===node),true);assert.deepEqual(await name.evaluate(node=>({start:node.selectionStart,end:node.selectionEnd})),focusBefore);assert.equal(await page.evaluate(()=>fixtureTracks[0].readyState),'live');check('Ordinary SSE reconnect retains dirty Build, accepted pose, exact iframe/form/history and deliberate audio intent');
 holdResume=true;await disconnect();const disabled=await context.request.post(base+'/api/media/state',{data:{enabled:false}});assert.equal(disabled.status(),200);await page.waitForFunction(()=>fixtureTracks[0].readyState==='ended');assert(held.length>0);assert.equal(await page.evaluate(()=>captureAttempts),1);await release();assert.equal(await page.evaluate(()=>fixtureTracks[0].readyState),'ended');check('Current-room media disabled push retires capture immediately during held same-admission resume');
 await page.locator('#dock-media').click();await page.locator('.media-join').click();await page.waitForFunction(()=>document.querySelector('.media-join')?.textContent==='Leave audio');await page.locator('[data-media="microphone"]').click();await page.waitForFunction(()=>fixtureTracks.length===2&&fixtureTracks[1].readyState==='live');await page.locator('#dock-media').click();
 holdResume=true;await disconnect();const saved=(await(await context.request.get(base+'/api/rooms/room')).json()).room,nextScene=structuredClone(saved.scene);nextScene.areas.push({id:'new-silent',name:'New committed quiet zone',action:'silent',x:0,z:5,width:4,depth:4});const save=await context.request.put(base+'/api/rooms/room/scene',{data:{revision:saved.revision,scene:nextScene}});assert.equal(save.status(),200);await page.waitForFunction(()=>fixtureTracks[1].readyState==='ended');assert(held.length>0);assert.equal((await state()).scene.objects[0].name,'My unsaved board draft');assert.equal((await state()).room.scene.areas.length,0);assert.equal(await page.evaluate(()=>window.__universe.getEditor().dirty),true);check('Fresh committed Silent SSE stops inert capture while resume HTTP is held and the dirty saved base still lacks Silent');
 await release();current=await state();assert.equal(current.scene.objects[0].name,'My unsaved board draft');assert.equal(current.scene.areas.length,0);assert.equal(current.room.revision,saved.revision);assert.equal(await page.evaluate(()=>window.__universe.getEditor().dirty),true);await page.getByText('A newer room version needs your attention',{exact:true}).waitFor();assert.equal(await page.locator('#editor').isVisible(),true);assert(await frame.evaluate(node=>node.isConnected&&node===document.querySelector('iframe.embedded-frame')));assert.equal(await input().inputValue(),'Keep this unsubmitted form');assert.equal(await page.locator('[data-media="microphone"]').isDisabled(),true);assert.equal(await page.evaluate(()=>captureAttempts),2);assert.equal(current.admissionId,before.admissionId);assert.deepEqual(current.position,before.position);check('Held reconnect commit records editor conflict without replacing draft or form, and newly saved Silent remains denied');
 await mkdir('evidence',{recursive:true});await page.screenshot({path:'evidence/arrival-reconnect-dirty-silent.png'});assert.deepEqual(errors,[]);assert(requests.slice(1).every(value=>value.mode==='resume'));assert.equal(frameLoads,1);
}catch(error){console.error(error);checks.push({name:'failure',status:'failed',error:error.stack});await mkdir('evidence',{recursive:true});await page.screenshot({path:'evidence/arrival-reconnect-failure.png'}).catch(()=>{});process.exitCode=1;}finally{await release().catch(()=>{});await writeFile('evidence/arrival-reconnect-full.json',JSON.stringify({checks,errors,requests,frameLoads,bundleSha256:createHash('sha256').update(await readFile('dist/main.js')).digest('hex'),limits:['Actual app, HTTP, SSE reconnect and native editor/form/device controls','Only inert JavaScript audio tracks; no real devices, external provider or media packets']},null,2));await context.close();await browser.close();await app.close();}
