/** Controlled native DOM/API fixture; combined authenticated game travel is separate. */
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {build} from 'esbuild';
import {chromium} from 'playwright-core';
import embedded from '@sparticuz/chromium';
const out='evidence/arrival-surfaces';await mkdir(out,{recursive:true});
const setup=`
import {mountActionRuntime} from './src/action-runtime.js';
import {createArrivalShare} from './src/arrival-share.js';
import {itemActions} from './src/action-schema.js';
import './src/action-runtime.css';import './src/arrival-share.css';
window.state={user:{id:'actor'},room:{id:'room',revision:4},ready:true,position:{x:0,z:0},scene:{bounds:{width:20,depth:20},spawn:{x:0,z:0},objects:[{id:'portal',type:'portal',x:0,z:0,target:'garden',entry:'cafe'}],areas:[{id:'entry',name:'Café entrance',x:0,z:0,width:3,depth:3,start:{key:'cafe'},actions:[{id:'door',type:'teleport',name:'Visit the garden',target:'garden',entry:'cafe',trigger:'enter'},{id:'welcome',type:'message',name:'Welcome',message:'Welcome here',trigger:'enter'}]}]}};
window.nav=[];window.calls=[];window.messages=[];window.toasts=[];window.copied=[];window.hold=false;window.pending=[];window.mismatch=false;window.catalogError=false;window.noClipboard=false;
const catalog={room:[{key:'cafe',areaId:'entry',name:'Café entrance',isDefault:false}],garden:[{key:'stage',areaId:'stage',name:'Stage entrance',isDefault:true}]};
const api=async(path,options={})=>{calls.push({path,...options});let value;
 if(path.endsWith('/entries')){if(catalogError)throw Error('Arrival list is unavailable');const roomId=path.split('/')[3];value={roomId,revision:4,entries:catalog[roomId]||[]};}
 else{const ref=options.body,entity=(ref.entityType==='item'?state.scene.objects:state.scene.areas).find(e=>e.id===ref.entityId);const list=ref.entityType==='item'?itemActions(entity):(entity.actions||[]);const action=list.find(a=>a.id===ref.actionId);value={revision:state.room.revision,entity:{name:entity.name||entity.type},action:{...action,...(mismatch?{entry:'wrong'}:{})}};}
 const copy=structuredClone(value);if(hold)await new Promise(resolve=>pending.push(resolve));return copy;};
const runtime=mountActionRuntime({root:document.querySelector('#content'),controlsRoot:document.querySelector('#action-controls'),api,getState:()=>state,onDialog:data=>{messages.push(data.text);const root=document.querySelector('#item-actions');root.replaceChildren();for(const action of data.actions||[]){const b=document.createElement('button');b.textContent=action.label;b.onclick=action.run;root.append(b)}},onNavigate:(target,options)=>nav.push({target,options}),toast:text=>toasts.push(text)});
window.runtime=runtime;window.reset=()=>{runtime.clear();nav=[];calls=[];messages=[];toasts=[];state.room={id:'room',revision:4};state.ready=true;state.position={x:0,z:0};};
const dialog=document.querySelector('#dialog'),root=document.querySelector('#dialog-content');
const share=createArrivalShare({root,api,getState:()=>state,openDialog:data=>{dialog.hidden=false;document.querySelector('#dialog-title').textContent=data.title;root.textContent=data.text;document.querySelector('#dialog-close').focus()},isOpen:()=>!dialog.hidden,toast:text=>toasts.push(text),getUrl:()=>'https://game.invalid/play?room='+state.room.id+'&invite=discard-me&token=discard-me#discard-me',clipboard:()=>noClipboard?undefined:{writeText:async text=>copied.push(text)}});
document.querySelector('#open-share').onclick=()=>share.open();document.querySelector('#dialog-close').onclick=()=>{dialog.hidden=true;share.cancel()};document.querySelector('#open-item').onclick=()=>runtime.openItem('portal');
window.ready=true;
`;
await build({stdin:{contents:setup,resolveDir:process.cwd()},bundle:true,format:'esm',outfile:out+'/fixture.js'});
const html=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/universe-tokens.css"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/fixture.css"><style>body{overflow:auto;background:#242333;padding:16px}#action-controls{position:relative}#dialog-content{overflow-wrap:anywhere}</style><button id="open-item">Inspect portal</button><div id="item-actions"></div><div id="action-controls"></div><div id="content"></div><button id="open-share">Share a destination</button><div id="dialog" class="modal-backdrop" hidden><section class="dialog-card" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button id="dialog-close" class="icon-btn" aria-label="Close share dialog">×</button><p class="eyebrow">SHARE</p><h2 id="dialog-title"></h2><div id="dialog-content"></div></section></div><script type="module" src="/fixture.js"></script>`;
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local');if(url.pathname==='/'){res.setHeader('Content-Type','text/html');return res.end(html)}const path=url.pathname.startsWith('/fixture.')?out+url.pathname:'public'+url.pathname;res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'application/octet-stream');res.end(await readFile(path));}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;const checks=[],errors=[];const check=async(name,run)=>{await run();checks.push(name);console.log('PASS '+name)};
try{
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||await embedded.executablePath(),headless:true,args:['--no-sandbox','--no-zygote','--disable-gpu']});const page=await browser.newPage({viewport:{width:1000,height:800},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>ready);
 await check('landing suppresses automatic exits while welcome remains active; leaving and re-entering triggers exactly once',async()=>{await page.evaluate(()=>{runtime.arrive('room',state.scene,state.position);runtime.update()});await page.waitForFunction(()=>messages.includes('Welcome here'));assert.equal(await page.evaluate(()=>nav.length),0);await page.evaluate(()=>{state.position={x:5,z:0};runtime.update();state.position={x:0,z:0};runtime.update()});await page.waitForFunction(()=>nav.length===1);assert.deepEqual(await page.evaluate(()=>nav[0]),{target:'garden',options:{entry:'cafe',sourceAction:{roomId:'room',entityType:'area',entityId:'entry',actionId:'door',revision:4}}});await page.evaluate(()=>runtime.update());assert.equal(await page.evaluate(()=>nav.length),1)});
 await check('a landing still offers deliberate native doorway activation',async()=>{await page.evaluate(()=>{reset();runtime.arrive('room',state.scene,state.position);runtime.update()});await page.getByRole('button',{name:'Visit the garden',exact:true}).click();await page.waitForFunction(()=>nav.length===1)});
 await check('legacy item entry survives canonical resolution and native interaction',async()=>{await page.evaluate(()=>reset());await page.getByRole('button',{name:'Inspect portal',exact:true}).click();await page.getByRole('button',{name:'Travel to room',exact:true}).click();await page.waitForFunction(()=>nav.length===1);assert.equal(await page.evaluate(()=>nav[0].options.entry),'cafe');assert.equal(await page.evaluate(()=>nav[0].options.sourceAction.actionId),'legacy-target')});
 await check('changed entry and late old-room action responses cannot navigate',async()=>{await page.evaluate(()=>{reset();mismatch=true});await page.getByRole('button',{name:'Inspect portal',exact:true}).click();await page.getByRole('button',{name:'Travel to room',exact:true}).click();await page.waitForFunction(()=>toasts.some(t=>t.includes('changed')));assert.equal(await page.evaluate(()=>nav.length),0);await page.evaluate(()=>{mismatch=false;hold=true});await page.getByRole('button',{name:'Inspect portal',exact:true}).click();await page.getByRole('button',{name:'Travel to room',exact:true}).click();await page.waitForFunction(()=>pending.length===1);await page.evaluate(()=>{runtime.clear();state.room={id:'garden',revision:4};hold=false;pending.shift()()});await page.waitForTimeout(30);assert.equal(await page.evaluate(()=>nav.length),0)});
 await check('named and default share links discard invitation/query capabilities and use native keyboard copy',async()=>{await page.evaluate(()=>reset());await page.getByRole('button',{name:'Share a destination',exact:true}).click();const select=page.getByLabel('Arrival for shared link');await select.waitFor();await page.waitForFunction(()=>!document.querySelector('select').disabled);await select.selectOption('cafe');const copy=page.getByRole('button',{name:'Copy link',exact:true});await copy.focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>copied.length===1);assert.equal(await page.evaluate(()=>copied[0]),'https://game.invalid/play?room=room&entry=cafe');await select.selectOption('');await copy.click();await page.waitForFunction(()=>copied.length===2);assert.equal(await page.evaluate(()=>copied[1]),'https://game.invalid/play?room=room')});
 await check('unavailable clipboard exposes a selected usable URL without a false copied status',async()=>{await page.evaluate(()=>noClipboard=true);await page.getByRole('button',{name:'Copy link',exact:true}).click();const field=page.getByLabel('Room destination link');assert.deepEqual(await field.evaluate(n=>({focus:document.activeElement===n,start:n.selectionStart,end:n.selectionEnd,length:n.value.length})),{focus:true,start:0,end:field?await field.inputValue().then(v=>v.length):0,length:await field.inputValue().then(v=>v.length)});assert.equal(await page.evaluate(()=>copied.length),2);assert.match(await page.locator('.arrival-share-form [role=status]').textContent(),/Copy this selected link/)});
 await check('denied and stale entry lists never populate a replaced dialog',async()=>{await page.getByRole('button',{name:'Close share dialog'}).click();await page.evaluate(()=>catalogError=true);await page.getByRole('button',{name:'Share a destination'}).click();await page.getByText('Arrival list is unavailable',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Copy link',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Close share dialog'}).click();await page.evaluate(()=>{catalogError=false;hold=true});await page.getByRole('button',{name:'Share a destination'}).click();await page.waitForFunction(()=>pending.length===1);await page.getByRole('button',{name:'Close share dialog'}).click();await page.evaluate(()=>{state.room={id:'garden',revision:4};hold=false});await page.getByRole('button',{name:'Share a destination'}).click();await page.getByRole('option',{name:'Stage entrance · default'}).waitFor({state:'attached'});await page.evaluate(()=>pending.shift()());await page.waitForTimeout(30);assert.equal(await page.getByRole('option',{name:'Café entrance',exact:true}).count(),0)});
 await check('320px share controls remain reachable by native touch and preserve copy fallback',async()=>{await page.setViewportSize({width:320,height:568});const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});const button=page.getByRole('button',{name:'Copy link',exact:true});await button.scrollIntoViewIfNeeded();const box=await button.boundingBox();assert(box&&box.width>=48&&box.height>=48&&box.x>=0&&box.x+box.width<=320);for(const selector of ['.dialog-card','#dialog-close','.arrival-share-form select','.arrival-share-form input']){const bounds=await page.locator(selector).boundingBox();assert(bounds&&bounds.x>=0&&bounds.x+bounds.width<=320,selector+' stays inside the viewport');}await button.tap();assert.match(await page.locator('.arrival-share-form [role=status]').textContent(),/Copy this selected link/);await page.screenshot({path:out+'/share-320.png'});await page.getByRole('button',{name:'Close share dialog'}).tap();assert.equal(await page.locator('#dialog').isHidden(),true)});
 assert.deepEqual(errors,[]);await writeFile(out+'/results.json',JSON.stringify({scope:'Controlled native DOM/API fixture; no authenticated admission or full-game proof',checks,errors},null,2));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
