import {build} from 'esbuild';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {launch} from '../scripts/browser.mjs';
import {seedWorlds} from '../src/worlds.js';
import {createGameServer} from '../server/app.mjs';
await mkdir('evidence',{recursive:true});
const bundle=await build({stdin:{contents:`import{EngineStore}from'@babylonjs/core/Engines/engineStore.js';import{createRenderer}from'./src/renderer.js';import{emptyScene}from'./src/worlds.js';const r=await createRenderer(document.querySelector('canvas'),document.querySelector('#labels'));const world=emptyScene();world.objects=[{id:'table',type:'table',name:'Café table',x:4,z:0}];world.areas=[{id:'cafe',name:'Café entrance',x:-4,z:0,width:4,depth:4,action:'welcome',start:{key:'cafe',isDefault:true}},{id:'stage',name:'Stage entrance',x:4,z:0,width:4,depth:4,action:'teleport',target:'commons',start:{key:'stage',isDefault:false}}];window.world=world;r.sync(world);r.setFollow(false);r.setTarget(0,0);window.settle=async()=>{await EngineStore.LastCreatedScene.whenReadyAsync();r.render(.016);r.render(.016);};window.snapshot=()=>{const scene=EngineStore.LastCreatedScene;return{meshes:scene.meshes.length,nodes:scene.transformNodes.length,geometries:scene.geometries.length,areas:scene.meshes.filter(m=>m.metadata?.type==='area'||m.metadata?.ranges?.some(range=>range.metadata?.type==='area')).map(m=>({name:m.name,pickable:m.isPickable}))};};await r.ready;window.r=r;`,resolveDir:process.cwd()},bundle:true,format:'esm',minify:true,write:false});
const app=createGameServer({seeds:seedWorlds,dist:new URL('../dist',import.meta.url).pathname}),address=await app.listen(0),browser=await launch(),page=await browser.newPage({viewport:{width:1280,height:900}}),checks=[],errors=[];page.on('pageerror',error=>errors.push(error.message));
const check=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
await page.route('**/arrival-renderer.js',route=>route.fulfill({contentType:'text/javascript',body:bundle.outputFiles[0].text}));const styles=(await Promise.all(['public/style.css','src/editor.css'].map(path=>readFile(path,'utf8')))).join('\n');
await page.route('**/arrival-renderer',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><style>'+styles+' html,body{margin:0;width:100%;height:100%;overflow:hidden}canvas{width:100%;height:100%;display:block}#labels{position:absolute;inset:0;pointer-events:none}</style></head><body><canvas></canvas><div id="labels"></div><script type="module" src="/arrival-renderer.js"></script></body></html>'}));
try{
 await page.goto('http://127.0.0.1:'+address.port+'/arrival-renderer');await page.waitForFunction(()=>!!window.r);await page.evaluate(()=>settle());const baseline=await page.evaluate(()=>snapshot()),original=await page.evaluate(()=>structuredClone(world));assert.equal(await page.locator('.arrival-label').count(),0);
 await page.evaluate(()=>r.setBuild(true));await page.evaluate(()=>settle());assert.equal(await page.locator('.arrival-label').count(),2);assert.equal(await page.locator('[data-arrival-key="cafe"]').getAttribute('data-arrival-default'),'true');assert.equal(await page.locator('[data-arrival-key="stage"]').getAttribute('data-arrival-default'),'false');const building=await page.evaluate(()=>snapshot());assert(building.areas.length>0);assert(building.areas.every(mesh=>!mesh.pickable));check('Saved start regions render distinct named/default markers only in build mode');
 const picks=await page.evaluate(()=>{const ground=r.screenPoint(-4,0),table=r.screenPoint(4,0,1);return{ground:r.pick(ground.x,ground.y),table:r.pick(table.x,table.y)};});assert(Math.abs(picks.ground.point.x+4)<.03);assert(Math.abs(picks.ground.point.z)<.03);assert.equal(picks.table.id,'table');assert.deepEqual(await page.evaluate(()=>world),original);check('Arrival rings do not intercept ground/table picking or alter collision geometry');await page.screenshot({path:'evidence/arrival-markers-desktop.png'});
 await page.evaluate(()=>{for(let i=0;i<8;i++)r.sync(world);});assert.deepEqual(await page.evaluate(()=>snapshot()),building);assert.equal(await page.locator('.arrival-label').count(),2);await page.evaluate(()=>r.setBuild(false));await page.evaluate(()=>settle());assert.deepEqual(await page.evaluate(()=>snapshot()),baseline);assert.equal(await page.locator('.arrival-label').count(),0);check('Repeated draft rendering does not leak labels/meshes and gameplay removes authoring markers');assert.deepEqual(errors,[]);
}catch(error){console.error(error);checks.push({name:'failure',status:'failed',error:error.stack});await page.screenshot({path:'evidence/arrival-renderer-failure.png'}).catch(()=>{});process.exitCode=1;}finally{await writeFile('evidence/arrival-renderer-checks.json',JSON.stringify({checks,errors},null,2));await browser.close();await app.close();}
