import{test}from'node:test';import assert from'node:assert/strict';import{createAudioActions}from'../src/audio-actions.js';
class FakeAudio{constructor(url){this.src=url;this.pauses=0;this.loads=0;this.plays=0;}play(){this.plays++;return this.next??Promise.resolve();}pause(){this.pauses++;}load(){this.loads++;}removeAttribute(){}}
function setup(){const sounds=[],errors=[],saved=[];const controller=createAudioActions({createAudio:url=>{const a=new FakeAudio(url);sounds.push(a);return a;},onError:e=>errors.push(e),saveVolume:v=>saved.push(v),initialVolume:.4});return{controller,sounds,errors,saved};}
const config={key:'r:a:s',url:'/assets/chime.wav',label:'Garden music',volume:.8,loop:true};
test('EDIT-17: volume cap preserves zero, remembered user volume, mute and optional voice duck',async()=>{const {controller:c,sounds,saved}=setup();await c.play(config);assert.equal(sounds[0].volume,.4);assert.equal(sounds[0].loop,true);c.setVolume(.9);assert.equal(sounds[0].volume,.8);c.setDucked(true);assert.equal(sounds[0].volume,.4);c.setMuted(true);assert.equal(sounds[0].volume,0);c.setMuted(false);c.ensure({...config,volume:0});assert.equal(sounds[1].volume,0);assert.deepEqual(saved,[.9]);});
test('EDIT-17: repeated pending/playing activation never overlaps; source change unloads old audio',async()=>{const {controller:c,sounds}=setup();c.ensure(config);let resolve;sounds[0].next=new Promise(r=>resolve=r);const a=c.play(config),b=c.play(config);assert.equal(sounds.length,1);assert.equal(sounds[0].plays,1);resolve();await Promise.all([a,b]);await c.play(config);assert.equal(sounds[0].plays,1);await c.play({...config,url:'/assets/changed.wav'});assert.equal(sounds.length,2);assert.equal(sounds[0].src,'');assert(sounds[0].loads>0);});
test('EDIT-17: rejected autoplay has no retries until user Play; leave/revoke kills late play',async()=>{const {controller:c,sounds,errors}=setup();c.ensure(config);sounds[0].next=Promise.reject(Object.assign(new Error('blocked'),{name:'NotAllowedError'}));assert.equal(await c.play(config),false);assert.equal(sounds[0].plays,1);assert.match(errors[0],/blocked/);sounds[0].next=Promise.resolve();assert.equal(await c.play(config),true);c.pause(config.key);let resolve;sounds[0].next=new Promise(r=>resolve=r);const pending=c.play(config.key);c.clear();resolve();assert.equal(await pending,false);assert.equal(c.snapshot().entries.length,0);assert.equal(sounds[0].src,'');});
test('EDIT-17: late superseded play cannot pause a newer user retry; ended playback restarts at zero',async()=>{const {controller:c,sounds}=setup();c.ensure(config);let resolve;sounds[0].next=new Promise(r=>resolve=r);const first=c.play(config.key);c.pause(config.key);sounds[0].next=Promise.resolve();await c.play(config.key);const pauses=sounds[0].pauses;resolve();await first;assert.equal(sounds[0].pauses,pauses);sounds[0].currentTime=12;sounds[0].onended();await c.play(config.key);assert.equal(sounds[0].currentTime,0);});
test('EDIT-17: synchronous media failure can be retried by the user',async()=>{const {controller:c,sounds}=setup();c.ensure(config);sounds[0].play=()=>{throw Error('unsupported')};assert.equal(await c.play(config.key),false);sounds[0].play=()=>Promise.resolve();assert.equal(await c.play(config.key),true);});
test('EDIT-17: explicit retry reloads failed native source before playing again',async()=>{const {controller:c,sounds}=setup();c.ensure(config);sounds[0].play=()=>sounds[0].loads?Promise.resolve():Promise.reject(Error('source failed'));assert.equal(await c.play(config.key),false);assert.equal(sounds[0].loads,0);assert.equal(await c.play(config.key),true);assert.equal(sounds[0].loads,1);});
