import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{createGameServer}from'../server/app.mjs';import{seedWorlds}from'../src/worlds.js';import{AVATAR_PRESETS,DEFAULT_APPEARANCE}from'../src/avatar-spec.js';
async function fixture(database=':memory:'){const app=createGameServer({database,seeds:seedWorlds}),{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;const client=()=>({cookie:'',async call(path,method='GET',body){const r=await fetch(base+path,{method,headers:{...(this.cookie?{Cookie:this.cookie}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,data:await r.json()};}});return{app,base,client};}
async function guest(f,name,appearance=DEFAULT_APPEARANCE){const c=f.client(),r=await c.call('/api/session','POST',{name,appearance});assert.equal(r.status,201);c.user=r.data.user;return c;}
async function stream(f,c){const abort=new AbortController(),r=await fetch(f.base+'/api/events',{headers:{Cookie:c.cookie},signal:abort.signal}),reader=r.body.getReader(),events=[];let raw='';const pending=(async()=>{try{while(true){const{value,done}=await reader.read();if(done)break;raw+=new TextDecoder().decode(value);let pos;while((pos=raw.indexOf('\n\n'))>=0){const part=raw.slice(0,pos);raw=raw.slice(pos+2);const event=part.match(/^event: (.+)$/m)?.[1],data=part.match(/^data: (.+)$/m)?.[1];if(event&&data)events.push({event,data:JSON.parse(data)});}}}catch{}})();return{events,close:async()=>{abort.abort();await pending;},async wait(predicate){for(let i=0;i<200;i++){const match=events.find(predicate);if(match)return match;await new Promise(r=>setTimeout(r,10));}assert.fail('Appearance SSE update did not reach authorized peer');}};}
test('appearance saves propagate to room peer; invalid catalog/style/color/entitlements leave prior state intact',async t=>{
 const f=await fixture();t.after(()=>f.app.close());const a=await guest(f,'Avatar owner'),b=await guest(f,'Room peer',AVATAR_PRESETS[1].appearance);await a.call('/api/rooms/commons/join','POST',{});await b.call('/api/rooms/commons/join','POST',{});const live=await stream(f,b);t.after(()=>live.close());await live.wait(e=>e.event==='hello');const appearance={...structuredClone(AVATAR_PRESETS[4].appearance),hat:'beanie',glasses:'square',body:{height:'tall',build:'soft'}};
 const save=await a.call('/api/me','PATCH',{appearance});assert.equal(save.status,200);assert.deepEqual(save.data.user.appearance,appearance);assert.deepEqual(save.data.user.woka,appearance);
 const event=await live.wait(e=>e.event==='presence'&&e.data.presence.some(p=>p.id===a.user.id&&p.appearance?.hat==='beanie'));assert.deepEqual(event.data.presence.find(p=>p.id===a.user.id).appearance,appearance);
 for(const bad of[{...appearance,catalog:'someone-elses-catalog'},{...appearance,hat:'exclusive-paid-crown'},{...appearance,skin:'#000000'},{...appearance,entitlements:['owner']},{...appearance,body:{height:99,build:'soft'}}]){const rejected=await a.call('/api/me','PATCH',{appearance:bad});assert.equal(rejected.status,400);assert.equal(rejected.data.code,'INVALID_APPEARANCE');assert.deepEqual((await a.call('/api/session')).data.user.appearance,appearance);}
 const aliasReject=await a.call('/api/me','PATCH',{woka:{...appearance,catalog:'unknown-catalog'}});assert.equal(aliasReject.status,400);assert.equal(aliasReject.data.code,'INVALID_APPEARANCE');const otherBefore=(await b.call('/api/session')).data.user.appearance;await a.call('/api/me','PATCH',{userId:b.user.id,appearance:AVATAR_PRESETS[2].appearance});assert.deepEqual((await b.call('/api/session')).data.user.appearance,otherBefore);assert.equal((await f.client().call('/api/me','PATCH',{appearance})).status,401);
});
test('appearance survives reload/session, world and room changes, database restart and independent login',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'avatar-persistence-'));t.after(()=>rm(dir,{recursive:true,force:true}));const db=join(dir,'test.sqlite');let f=await fixture(db);const a=await guest(f,'Persistent avatar',AVATAR_PRESETS[3].appearance);await a.call('/api/account','POST',{username:'avatar_test_owner',password:'only a local test fixture password'});const appearance={...structuredClone(AVATAR_PRESETS[2].appearance),hairStyle:'curls',bag:'satchel',eyeColor:'#35675e'};assert.equal((await a.call('/api/me','PATCH',{appearance})).status,200);
 assert.deepEqual((await a.call('/api/session')).data.user.appearance,appearance);for(const room of['commons','studio','terrace']){const res=await a.call(`/api/rooms/${room}/join`,'POST',{});if(res.status===200)assert.deepEqual((await a.call('/api/session')).data.user.appearance,appearance);}
 const world=(await a.call('/api/worlds','POST',{name:'Avatar second world',public:true})).data.world;const room=(await a.call('/api/rooms','POST',{name:'Avatar second room',worldId:world.id,public:true})).data.room;assert.equal((await a.call(`/api/rooms/${room.id}/join`,'POST',{})).status,200);assert.deepEqual((await a.call('/api/session')).data.user.appearance,appearance);
 const cookie=a.cookie;await f.app.close();f=await fixture(db);t.after(()=>f.app.close());const restored=f.client();restored.cookie=cookie;assert.deepEqual((await restored.call('/api/session')).data.user.appearance,appearance);const login=f.client(),result=await login.call('/api/login','POST',{username:'avatar_test_owner',password:'only a local test fixture password'});assert.equal(result.status,200);assert.deepEqual(result.data.user.appearance,appearance);assert.equal(result.data.user.id,a.user.id);
});
