/** Integrated proof: run only after the coordinator's current npm run build. */
import{launch}from'../scripts/browser.mjs';import{seedWorlds}from'../src/worlds.js';import{createGameServer}from'../server/app.mjs';import{writeFile}from'node:fs/promises';import assert from'node:assert/strict';
const app=createGameServer({seeds:seedWorlds,dist:process.env.UNIVERSE_AVATAR_DIST||new URL('../dist',import.meta.url).pathname}),{port}=await app.listen(0),base='http://127.0.0.1:'+port,browser=await launch(),context=await browser.newContext({viewport:{width:1365,height:900}}),page=await context.newPage(),peerContext=await browser.newContext({viewport:{width:1024,height:800}}),peer=await peerContext.newPage(),checks=[],errors=[],legacyRequests=[];for(const p of[page,peer]){p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/\/assets\/woka-\d+\.png/.test(r.url()))legacyRequests.push(r.url());});}const check=name=>{checks.push(name);console.log('PASS',name);};
try{
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.locator('#customize-character').click();await page.getByRole('tab',{name:'Hair',exact:true}).click();await page.getByRole('button',{name:'Hairstyle: High bun',exact:true}).click();await page.getByRole('button',{name:'Save character',exact:true}).click();await page.locator('#avatar-creator').waitFor({state:'hidden'});await page.getByPlaceholder('Your name').fill('Character owner');await page.getByRole('button',{name:'Enter Universe'}).click();await page.waitForFunction(()=>window.__universe?.getState().ready);assert.equal(await page.evaluate(()=>__universe.getState().user.appearance.hairStyle),'bun');check('Welcome native3D customization becomes the authenticated profile');
 await peer.goto(base,{waitUntil:'domcontentloaded'});await peer.getByPlaceholder('Your name').fill('Character peer');await peer.getByRole('button',{name:'Enter Universe'}).click();await peer.waitForFunction(()=>window.__universe?.getState().ready);const userId=await page.evaluate(()=>__universe.getState().user.id);await peer.waitForFunction(id=>__universe.getState().people.some(p=>p.id===id),userId);
 await page.locator('#dock-settings').click();await page.getByRole('button',{name:'Edit your 3D character',exact:true}).click();assert.equal(await page.locator('.avatar-preview').evaluate(canvas=>(canvas.getContext('webgl2')||canvas.getContext('webgl')).isContextLost()),false);await page.getByRole('tab',{name:'Extras',exact:true}).click();await page.getByRole('button',{name:'Headwear: Soft cap',exact:true}).click();await page.getByRole('button',{name:'Bag: Day backpack',exact:true}).click();await page.getByRole('button',{name:'Eyewear: Round frames',exact:true}).click();await page.screenshot({path:'evidence/avatar-live-desktop.png'});await page.getByRole('button',{name:'Save character',exact:true}).click();await page.locator('#avatar-creator').waitFor({state:'hidden'});await peer.waitForFunction(id=>__universe.getState().people.some(p=>p.id===id&&p.appearance?.hat==='cap'&&p.appearance?.bag==='backpack'),userId);check('Saving3D profile updates local state and the second browser in real time');await peerContext.close();
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__universe?.getState().ready);assert.equal(await page.evaluate(()=>__universe.getState().user.appearance.glasses),'round');await page.goto(base+'/?room=studio',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__universe?.getState().room?.id==='studio');assert.equal(await page.evaluate(()=>__universe.getState().user.appearance.hat),'cap');check('Appearance survives browser reload and actual room navigation');
 await page.locator('#dock-settings').click();await page.getByRole('button',{name:'Edit your 3D character',exact:true}).click();await page.getByRole('tab',{name:'Hair',exact:true}).click();await page.getByRole('button',{name:'Hairstyle: Clean shaven',exact:true}).click();await page.keyboard.press('Escape');await page.locator('#avatar-creator').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>__universe.getState().user.appearance.hairStyle),'bun');const session=await page.evaluate(async()=>await(await fetch('/api/session')).json());assert.equal(session.user.appearance.hairStyle,'bun');check('Cancel/Escape preserves both live and stored appearance after a shape edit');
 await page.setViewportSize({width:390,height:844});await page.locator('#dock-settings').click();if(!(await page.getByRole('button',{name:'Edit your 3D character',exact:true}).isVisible()))await page.locator('#dock-settings').click();await page.getByRole('button',{name:'Edit your 3D character',exact:true}).click();await page.getByRole('tab',{name:'Outfit',exact:true}).click();await page.getByRole('button',{name:'Top: Cozy hoodie',exact:true}).click();await page.screenshot({path:'evidence/avatar-live-mobile.png'});const position=await page.evaluate(()=>__universe.getState().position);await page.locator('.avatar-preview').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('w');await page.keyboard.press('Space');await page.waitForTimeout(250);assert.deepEqual(await page.evaluate(()=>__universe.getState().position),position);assert(await page.locator('#avatar-creator').isVisible());check('Mobile creator remains operable and focused keyboard input never moves the world avatar');
 await page.setViewportSize({width:320,height:700});await page.waitForTimeout(250);const compact=await page.locator('.avatar-presets .avatar-preset').first().boundingBox(),saveBox=await page.getByRole('button',{name:'Save character',exact:true}).boundingBox();assert(compact.height<=44);assert(saveBox.x>=0&&saveBox.x+saveBox.width<=320&&saveBox.y+saveBox.height<=700);assert.equal(await page.locator('.avatar-stage-label').isVisible(),false);await page.screenshot({path:'evidence/avatar-live-320-final.png'});check('Final320px named preset chips remain compact and Save stays inside viewport');
 assert.deepEqual(errors,[]);assert.deepEqual(legacyRequests,[]);check('Integrated flow has no page errors or legacy sprite asset requests');
}catch(e){console.error(e);errors.push(e.stack);await page.screenshot({path:'evidence/avatar-live-failure.png'}).catch(()=>{});process.exitCode=1;}finally{await writeFile('evidence/avatar-live-results.json',JSON.stringify({checks,errors},null,2));await browser.close();await app.close();}
