/** Bounded final layout and keyboard-entry regression against the actual built shell. */
import{launch}from'../scripts/browser.mjs';import{createGameServer}from'../server/app.mjs';import{seedWorlds}from'../src/worlds.js';import{writeFile}from'node:fs/promises';import assert from'node:assert/strict';
const app=createGameServer({seeds:seedWorlds,dist:new URL('../dist',import.meta.url).pathname}),{port}=await app.listen(0),browser=await launch(),context=await browser.newContext({viewport:{width:320,height:700},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await context.newPage(),errors=[],checks=[];p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));
try{
 await p.goto('http://127.0.0.1:'+port,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!!window.__universe);
 for(let i=0;i<18;i++){await p.keyboard.press('Tab');assert(await p.locator('#welcome').evaluate(root=>root.contains(document.activeElement)));}await p.keyboard.press('Control+k');assert(await p.locator('#command-palette').isHidden());checks.push('Onboarding Tab stays in dialog and Cmd/CtrlK cannot reach unauthenticated actions');
 await p.locator('#customize-character').tap();await p.getByRole('tab',{name:'Hair',exact:true}).click();await p.getByRole('button',{name:'Hairstyle: High bun',exact:true}).click();await p.waitForTimeout(700);
 const preset=await p.locator('.avatar-presets .avatar-preset').first().boundingBox(),save=await p.getByRole('button',{name:'Save character',exact:true}).boundingBox();assert(preset.height<=44);assert(save.x>=0&&save.x+save.width<=320&&save.y+save.height<=700);assert(await p.locator('.avatar-stage-label').isHidden());assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),320);checks.push('320px ink creator has compact named chips, uncluttered silhouette and visible Save');
 await p.screenshot({path:'evidence/avatar-live-320-final.png'});await p.getByRole('button',{name:'Save character',exact:true}).tap();await p.locator('#avatar-creator').waitFor({state:'hidden'});await p.getByPlaceholder('Your name').fill('Final mobile look');await p.getByRole('button',{name:'Enter Universe'}).tap();await p.waitForFunction(()=>window.__universe.getState().ready);assert.equal(await p.evaluate(()=>__universe.getState().user.appearance.hairStyle),'bun');checks.push('Actual touch Save applies the final320px draft to the authenticated profile');assert.deepEqual(errors,[]);
}catch(e){errors.push(e.stack);console.error(e);process.exitCode=1;await p.screenshot({path:'evidence/avatar-layout-final-failure.png'}).catch(()=>{});}finally{await writeFile('evidence/avatar-layout-final-results.json',JSON.stringify({checks,errors,scope:'Actual browser touch emulation and keyboard against frozen application code; not physical-phone certification'},null,2));await browser.close();await app.close();}
