import {build}from'esbuild';import{mkdtemp,readFile,writeFile,rm,mkdir}from'node:fs/promises';import{createServer}from'node:http';import{tmpdir}from'node:os';import{join}from'node:path';import assert from'node:assert/strict';import{launch}from'../scripts/browser.mjs';
const dir=await mkdtemp(join(tmpdir(),'universe-avatar-'));await mkdir('evidence',{recursive:true});
await build({stdin:{contents:`import {mountAvatarCreator,createAvatarPortrait} from './src/avatar-creator.js';import {AVATAR_PRESETS,normalizeAppearance}from'./src/avatar-spec.js';let user={id:'fixture',appearance:normalizeAppearance(0)},writes=[],events=[];const creator=mountAvatarCreator({root:document.querySelector('#wardrobe'),getState:()=>({user}),api:async(path,options)=>{writes.push({path,...options});user={...user,appearance:options.body.appearance};return{user};},onSaved:u=>{user=u},onOpenChange:o=>events.push(o)});document.querySelector('#open').onclick=()=>creator.open();window.avatar={creator,getUser:()=>user,writes,events,presets:AVATAR_PRESETS,portrait:createAvatarPortrait};window.worldKeys=[];window.addEventListener('keydown',e=>window.worldKeys.push(e.key));`,resolveDir:process.cwd(),sourcefile:'avatar-fixture.js'},outfile:join(dir,'fixture.js'),bundle:true,format:'esm',target:'es2022'});
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/fixture.css"><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#262339}button{font-family:inherit}#open{margin:30px;padding:15px}</style></head><body><button id="open">Customize character</button><div id="wardrobe"></div><script type="module" src="/fixture.js"></script></body></html>`;
const server=createServer(async(req,res)=>{try{if(req.url==='/'){res.setHeader('content-type','text/html');res.end(html);}else{res.setHeader('content-type',req.url.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(join(dir,req.url.slice(1))));}}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await launch(),page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const check=name=>{checks.push(name);console.log('PASS',name);};
try{
 await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#open').click();await page.waitForTimeout(900);assert(await page.locator('.avatar-preview-error').isHidden());await page.screenshot({path:'evidence/avatar-creator-front.png'});check('Native preview initializes without WebGL or merge errors');
 await page.getByRole('button',{name:'Rotate character preview right'}).click();await page.getByRole('button',{name:'Rotate character preview right'}).click();await page.waitForTimeout(150);await page.screenshot({path:'evidence/avatar-creator-side.png'});
 await page.getByRole('button',{name:'Show character back',exact:true}).click();await page.waitForTimeout(150);await page.screenshot({path:'evidence/avatar-creator-back.png'});await page.getByRole('button',{name:'Show character front',exact:true}).click();check('Front, side and back geometry inspected from actual orbit controls');
 await page.getByRole('tab',{name:'Hair',exact:true}).click();await page.getByRole('button',{name:'Hairstyle: Soft curls',exact:true}).click();assert.equal(await page.evaluate(()=>avatar.creator.getDraft().hairStyle),'curls');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>avatar.writes.length),0);assert.equal(await page.evaluate(()=>avatar.getUser().appearance.hairStyle),'sweep');assert.equal(await page.evaluate(()=>document.activeElement.id),'open');check('Cancel discards a shape edit, writes nothing, and restores focus');
 await page.locator('#open').click();await page.getByRole('tab',{name:'Extras',exact:true}).click();await page.getByRole('button',{name:'Bag: Day backpack',exact:true}).click();await page.getByRole('button',{name:'Eyewear: Round frames',exact:true}).click();await page.getByRole('button',{name:'Save character',exact:true}).click();await page.waitForFunction(()=>!avatar.creator.isOpen());assert.equal(await page.evaluate(()=>avatar.writes.length),1);assert.equal(await page.evaluate(()=>avatar.writes[0].path),'/api/me');assert.equal(await page.evaluate(()=>avatar.getUser().appearance.bag),'backpack');check('Save emits one canonical /api/me appearance and updates the profile');
 await page.locator('#open').click();assert.equal(await page.evaluate(()=>avatar.creator.getDraft().glasses),'round');assert.equal(await page.locator('.avatar-preview').evaluate(canvas=>(canvas.getContext('webgl2')||canvas.getContext('webgl')).isContextLost()),false);await page.locator('.avatar-preview').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('w');assert(!(await page.evaluate(()=>worldKeys)).includes('w'));await page.getByRole('button',{name:'Save character',exact:true}).focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Close character creator');check('Reopen uses saved profile; canvas keyboard and focus trap keep game input isolated');
 const portrait=await page.evaluate(async()=>{const [a,b,c]=await Promise.all([avatar.portrait(0),avatar.portrait(1),avatar.portrait(0)]);return{length:a.length,different:a!==b,cached:a===c};});assert(portrait.length>1000);assert(portrait.different&&portrait.cached);check('Three queued portrait requests render genuine3D; distinct appearances and cache match');
 await page.evaluate(async()=>{const proof=document.createElement('section');proof.id='portrait-proof';proof.style='position:fixed;inset:0;z-index:9999;background:#f5f0fa;display:flex;align-items:center;justify-content:center;gap:15px';for(const p of avatar.presets){const item=document.createElement('div');item.style='text-align:center;font:12px sans-serif;color:#584168';const img=document.createElement('img');img.src=await avatar.portrait(p.appearance);img.style='display:block;width:160px;height:160px';item.append(img,p.name);proof.append(item);}document.body.append(proof);});await page.screenshot({path:'evidence/avatar-native-presets.png'});await page.locator('#portrait-proof').evaluate(node=>node.remove());

 await page.getByRole('button',{name:'Show character back',exact:true}).click();await page.waitForTimeout(100);await page.screenshot({path:'evidence/avatar-creator-accessories-back.png'});
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);await page.getByRole('tab',{name:'Outfit',exact:true}).click();await page.getByRole('button',{name:'Top: Cozy hoodie',exact:true}).click();await page.getByRole('button',{name:'Bottoms: Weekend shorts',exact:true}).click();await page.getByRole('button',{name:'Show character front',exact:true}).click();await page.waitForTimeout(200);await page.screenshot({path:'evidence/avatar-creator-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);const save=await page.getByRole('button',{name:'Save character',exact:true}).boundingBox();assert(save.y+save.height<=844);check('390px portrait layout retains visible preview, choices, and Save without page overflow');
 await page.setViewportSize({width:844,height:390});await page.waitForTimeout(200);await page.screenshot({path:'evidence/avatar-creator-landscape.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),844);check('Landscape layout remains bounded');
 await page.keyboard.press('Escape');await page.locator('#open').click();await page.getByRole('tab',{name:'Hair',exact:true}).click();for(const id of ['crop','curls','bob','bun','spikes','bald','sweep']){const option=await page.evaluate(id=>({crop:'Cropped',curls:'Soft curls',bob:'Rounded bob',bun:'High bun',spikes:'Tousled',bald:'Clean shaven',sweep:'Side sweep'})[id],id);await page.getByRole('button',{name:'Hairstyle: '+option,exact:true}).click();}assert.deepEqual(errors,[]);check('Repeated live mesh rebuilds are free of browser errors');
 const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}),touchPage=await touchContext.newPage();touchPage.on('pageerror',e=>errors.push(e.message));await touchPage.goto('http://127.0.0.1:'+server.address().port);await touchPage.locator('#open').tap();await touchPage.waitForTimeout(250);const before=await touchPage.evaluate(()=>avatar.creator.getPreviewState().camera.alpha),box=await touchPage.locator('.avatar-preview').boundingBox(),cdp=await touchContext.newCDPSession(touchPage);const point={x:box.x+box.width*.4,y:box.y+box.height*.5};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point]});for(let i=1;i<=5;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:point.x+i*15,y:point.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touchPage.waitForTimeout(150);const after=await touchPage.evaluate(()=>avatar.creator.getPreviewState().camera.alpha);assert(Math.abs(after-before)>.1);await touchPage.getByRole('tab',{name:'Extras',exact:true}).tap();await touchPage.getByRole('button',{name:'Headwear: Ribbed beanie',exact:true}).tap();assert.equal(await touchPage.evaluate(()=>avatar.creator.getDraft().hat),'beanie');await touchPage.screenshot({path:'evidence/avatar-creator-touch.png'});await touchPage.getByRole('button',{name:'Cancel',exact:true}).tap();assert.equal(await touchPage.evaluate(()=>avatar.writes.length),0);await touchContext.close();check('Mobile emulated touch drag orbits native preview; touch edits and Cancel work');assert.deepEqual(errors,[]);

}catch(e){console.error(e);errors.push(e.stack);await page.screenshot({path:'evidence/avatar-creator-failure.png'}).catch(()=>{});process.exitCode=1;}finally{await writeFile('evidence/avatar-browser-results.json',JSON.stringify({checks,errors},null,2));await browser.close();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}
