/** Isolated resident editor DOM + protocol fixture. No game renderer, WebGL,
 * shared dist build or production account is used by this test. */
import { build } from 'esbuild';
import { launch } from '../scripts/browser.mjs';
import assert from 'node:assert/strict';
import { writeFile, mkdir } from 'node:fs/promises';

import {source} from './bot-editor-fixture.mjs';
const result = await build({ stdin: { contents: source, resolveDir: process.cwd(), sourcefile: 'resident-editor-fixture.js' }, bundle: true, format: 'iife', write: false, outfile: '/tmp/universe-resident-editor-fixture.js' });
const browser = await launch(), page = await browser.newPage({ viewport: { width: 1280, height: 920 } });
const errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
const check = name => { checks.push({ name, status: 'passed' }); console.log('PASS', name); };
const field = path => { const control = page.locator(`[data-bot-field="${path}"]`); return new Proxy(control, { get(target, key) { const value = target[key]; if (['fill', 'selectOption', 'check', 'uncheck', 'focus', 'press'].includes(key)) return async (...args) => { await target.evaluate(node => { for (let parent = node.parentElement; parent; parent = parent.parentElement) if (parent.tagName === 'DETAILS') parent.open = true; }); return value.apply(target, args); }; return typeof value === 'function' ? value.bind(target) : value; } }); };
const saved = () => page.waitForFunction(() => !editor.isSaving());
const mutations = () => page.evaluate(() => logs.requests.filter(r => r.args.method));
async function listView() {
  if (await page.getByRole('button', { name: 'Back to residents', exact: true }).isVisible()) {
    await page.getByRole('button', { name: 'Back to residents', exact: true }).click();
    if (await page.getByTestId('bot-confirm-save').isVisible()) { await page.getByTestId('bot-confirm-save').click(); await saved(); }
  }
}
async function chooseResident(id) { await listView(); await page.locator(`[data-bot-id="${id}"]`).click(); }
async function createDraft() { await listView(); await page.getByTestId('bot-create').click(); }

await mkdir('evidence', { recursive: true });
try {
  await page.route('https://resident-editor.test/', route => route.fulfill({ status: 200, contentType: 'text/html', body: '<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:linear-gradient(140deg,#564967,#2e443e);height:100vh}button,input{font-family:Arial}</style><button id="launch">Open residents</button>' }));
  await page.goto('https://resident-editor.test/');
  await page.addStyleTag({ content: result.outputFiles.find(file => file.path.endsWith('.css')).text });
  await page.addScriptTag({ content: result.outputFiles.find(file => file.path.endsWith('.js')).text });
  await page.waitForFunction(() => document.querySelectorAll('[data-bot-id]').length === 2);
  assert.match(await page.locator('[data-bot-id="rose"]').innerText(), /Disabled/);
  await chooseResident('rose');
  assert.equal(await field('enabled').isChecked(), false);
  assert.equal(await field('privateInstructions').inputValue(), 'Only managers see these instructions');
  assert.deepEqual(await page.evaluate(() => editor.getIdentity()), { roomId: 'alpha', botId: 'rose' });
  assert.equal(await page.evaluate(() => logs.preview.at(-1).botId), 'rose');
  assert.equal(await page.evaluate(() => editor.updateMap({ roomId: 'beta', botId: 'rose', radius: 99 })), false);
  assert.equal(await page.evaluate(() => editor.updateMap({ roomId: 'alpha', botId: 'moss', radius: 99 })), false);
  assert.equal(await field('radius').inputValue(), '6');
  check('Disabled residents remain editable; identity-tagged preview and map updates reject wrong-room or wrong-resident drags');

  await page.evaluate(() => editor.updateMap({ spawn: { x: 3, z: 2 }, radius: 4 }));
  await field('name').fill('Rose renamed without blur');
  await page.keyboard.press('Control+s'); await saved();
  const first = (await mutations()).at(-1);
  assert.deepEqual(first.args.body.patch.spawn, { x: 3, z: 2 });
  assert.equal(first.args.body.patch.radius, 4);
  assert.equal(first.args.body.patch.name, 'Rose renamed without blur');
  assert.equal(first.args.body.revision, 0);
  assert.equal(first.args.body.patch.privateInstructions, undefined);
  assert.equal(await page.evaluate(() => editor.isDirty()), false);
  check('Unblurred text and map edits share one canonical draft, with a minimal CAS patch');

  await field('name').fill('Saved by Back');
  await page.getByRole('button', { name: 'Back to residents', exact: true }).click();
  assert.equal(await page.evaluate(() => database.alpha[1].name), 'Rose renamed without blur');
  await page.getByTestId('bot-confirm-save').click();
  await page.waitForFunction(() => editor.getDraft() === null);
  assert.equal(await page.evaluate(() => database.alpha[1].name), 'Saved by Back');
  await chooseResident('rose');
  await field('name').fill('Kept after close failure');
  await page.evaluate(() => { manual = true; window.closing1 = editor.close(); window.closing2 = editor.close(); });
  assert.equal(await page.evaluate(() => pending.length), 0);
  await page.getByTestId('bot-confirm-save').click();
  assert.equal(await page.evaluate(() => pending.length), 1);
  assert.equal(await page.evaluate(() => closing1 === closing2), true);
  await page.evaluate(() => reject('Connection unavailable'));
  await saved();
  assert.equal(await page.evaluate(() => editor.isOpen()), true);
  assert.equal(await field('name').inputValue(), 'Kept after close failure');
  assert.match(await page.locator('.resident-error:not([hidden])').innerText(), /Connection unavailable/);
  const failedId = (await mutations()).at(-1).args.body.clientOperationId;
  await page.evaluate(() => { manual = false; });
  await page.getByRole('button', { name: 'Close residents' }).click();
  await page.getByTestId('bot-confirm-save').click();
  await page.waitForFunction(() => !editor.isOpen());
  assert.equal((await mutations()).at(-1).args.body.clientOperationId, failedId);
  assert.equal(await page.evaluate(() => logs.closed), 1);
  check('Back and Close require explicit Save; repeated saves serialize, preserve failure and retry the same operation');

  await page.evaluate(() => setup());
  await createDraft();
  await field('name').fill('Uncommitted Alpha');
  await field('privateInstructions').fill('Private draft, not a room record');
  await field('radius').fill('');
  assert.match(await page.locator('.resident-save-status').innerText(), /Not created yet.*Reloading or signing out clears it/);
  assert.equal(await page.getByRole('button', { name: 'Close residents', exact: true }).count(), 1);
  await page.getByRole('button', { name: 'Back to residents', exact: true }).click();
  await page.waitForFunction(() => editor.getDraft() === null);
  assert.deepEqual(await mutations(), []);
  assert.equal(await page.locator('[data-bot-id]').count(), 2);
  assert.match(await page.getByTestId('bot-create').innerText(), /Resume/);
  await createDraft();
  assert.equal(await field('name').inputValue(), 'Uncommitted Alpha');
  assert.equal(await field('radius').inputValue(), '');
  await field('radius').fill('7');
  await chooseResident('moss');
  assert.equal(await field('name').inputValue(), 'Moss');
  assert.deepEqual(await mutations(), []);
  await createDraft();
  assert.equal(await field('name').inputValue(), 'Uncommitted Alpha');
  assert.equal(await page.evaluate(() => editor.setRoom(room('beta'))), true);
  await createDraft();
  await field('name').fill('Uncommitted Beta');
  assert.equal(await page.evaluate(() => editor.setRoom(room('alpha'))), true);
  assert.equal(await field('name').inputValue(), 'Uncommitted Alpha');
  await page.getByRole('button', { name: 'Close residents', exact: true }).click();
  await page.waitForFunction(() => !editor.isOpen());
  assert.deepEqual(await mutations(), []);
  assert.equal(await page.evaluate(() => { const event = new Event('beforeunload', { cancelable: true }); window.dispatchEvent(event); return event.defaultPrevented; }), true);
  const readsBeforeReopen = await page.evaluate(() => logs.requests.length);
  await page.evaluate(() => editor.open(room('alpha')));
  assert.equal(await page.evaluate(() => logs.requests.length), readsBeforeReopen + 1);
  assert.equal(await field('name').inputValue(), 'Uncommitted Alpha');
  assert.equal(await field('privateInstructions').inputValue(), 'Private draft, not a room record');
  assert.equal(await field('radius').inputValue(), '7');
  assert.equal(await page.evaluate(() => created), 0);
  await page.getByTestId('bot-save').click(); await saved();
  assert.equal(await page.evaluate(() => created), 1);
  assert.equal((await mutations()).length, 1);
  assert.equal((await mutations())[0].args.method, 'POST');
  assert.equal((await mutations())[0].args.body.config.name, 'Uncommitted Alpha');
  await page.evaluate(() => editor.setRoom(room('beta')));
  assert.equal(await field('name').inputValue(), 'Uncommitted Beta');
  assert.equal(await page.evaluate(() => created), 1);
  check('New drafts survive Back, selection, Close and room switches with zero mutation requests; reopening rechecks access and only explicit Create commits');

  await page.evaluate(() => setup());
  await createDraft();
  await field('name').fill('Discard this draft');
  await page.getByRole('button', { name: 'Discard draft', exact: true }).click();
  assert.equal(await page.evaluate(() => editor.getDraft()), null);
  await page.evaluate(() => editor.close());
  assert.equal(await page.evaluate(() => { const event = new Event('beforeunload', { cancelable: true }); window.dispatchEvent(event); return event.defaultPrevented; }), false);
  await page.evaluate(() => editor.open());
  assert.equal(await page.evaluate(() => editor.getDraft()), null);
  await createDraft();
  assert.equal(await field('name').inputValue(), 'New resident');
  assert.deepEqual(await mutations(), []);
  check('Deliberate Discard removes the retained new draft and reload warning without creating a resident');

  await page.evaluate(() => setup());
  await createDraft();
  await field('name').fill('Keep while editing Moss');
  await chooseResident('moss');
  await field('name').fill('Updated Moss');
  await page.getByTestId('bot-save').click(); await saved();
  assert.equal((await mutations()).length, 1);
  assert.equal((await mutations())[0].args.method, 'PATCH');
  await createDraft();
  assert.equal(await field('name').inputValue(), 'Keep while editing Moss');
  await page.evaluate(() => { editor.save(); editor.updateAuthority(false); });
  await saved();
  assert.equal((await mutations()).length, 1);
  assert.equal(await page.evaluate(() => created), 0);
  assert.equal(await page.evaluate(() => editor.close()), true);
  check('Saving a different persisted resident preserves the retained new draft; authority revocation before dispatch prevents Create');


  await page.evaluate(() => setup());
  await createDraft();
  await field('name').fill('Owner A private draft');
  await field('privateInstructions').fill('Never show to a different account');
  await page.evaluate(() => editor.close());
  await page.evaluate(() => { denied = true; });
  assert.equal(await page.evaluate(() => editor.open()), false);
  assert.equal(await page.evaluate(() => editor.getDraft()), null);
  assert.equal(await field('privateInstructions').count(), 0);
  assert.equal(await page.getByTestId('bot-create').isDisabled(), true);
  await page.evaluate(() => editor.close());
  await page.evaluate(() => { denied = false; });
  await page.evaluate(() => editor.open());
  assert.equal(await field('name').inputValue(), 'Owner A private draft');
  await page.evaluate(() => { actorId = 'owner-b'; editor.updateAuthority(true); });
  assert.equal(await page.evaluate(() => editor.getDraft()), null);
  assert.equal(await field('privateInstructions').count(), 0);
  await page.evaluate(() => editor.setRoom(room()));
  assert.equal(await page.evaluate(() => editor.getDraft()), null);
  await createDraft();
  assert.equal(await field('privateInstructions').inputValue(), '');
  await page.evaluate(() => editor.close());
  await page.evaluate(() => { actorId = 'owner-a'; });
  await page.evaluate(() => editor.open());
  assert.equal(await page.evaluate(() => editor.getDraft()), null);
  assert.deepEqual(await mutations(), []);
  check('Restoration requires fresh management permission; account changes clear both active and retained private drafts');

  await page.evaluate(() => setup());
  await createDraft();
  await field('name').fill('Explicit Create in flight');
  await page.evaluate(() => { manual = true; window.creating = editor.save(); window.dismissCreating = editor.close(); });
  await page.waitForFunction(() => pending.length === 1);
  assert.equal((await mutations()).length, 1);
  await page.evaluate(() => { const next = pending.shift(); response(next.url, next.args); next.reject(new Error('Connection lost after create')); });
  assert.equal(await page.evaluate(() => dismissCreating), true);
  assert.equal(await page.evaluate(() => created), 1);
  assert.equal((await mutations()).length, 1);
  await page.evaluate(() => { manual = false; });
  await page.evaluate(() => editor.open());
  assert.equal(await field('name').inputValue(), 'Explicit Create in flight');
  await page.getByRole('button', { name: 'Discard draft', exact: true }).click();
  assert.match(await page.locator('.resident-error:not([hidden])').innerText(), /not been acknowledged/);
  assert.equal(await field('name').inputValue(), 'Explicit Create in flight');
  await page.getByTestId('bot-save').click(); await saved();
  const inFlightRequests = await mutations();
  assert.equal(inFlightRequests.length, 2);
  assert.deepEqual(inFlightRequests[1], inFlightRequests[0]);
  assert.equal(await page.evaluate(() => created), 1);
  check('Close waits for an explicitly started Create without posting again; ambiguous results survive reopen and retry the identical receipt');

  await page.evaluate(() => setup());
  await createDraft();
  assert.deepEqual(await page.evaluate(() => editor.getIdentity()), { roomId: 'alpha', botId: null });
  assert.equal(await page.evaluate(() => editor.updateMap({ roomId: 'alpha', botId: null, radius: 7 })), true);
  await field('name').fill('New uncertain resident');
  await page.evaluate(() => { uncertainNext = true; });
  await page.getByTestId('bot-save').click(); await saved();
  assert.equal(await page.evaluate(() => created), 1);
  const uncertain = (await mutations()).at(-1);
  await page.getByRole('button', { name: 'Back to residents', exact: true }).click();
  await page.waitForFunction(() => editor.getDraft() === null);
  assert.equal((await mutations()).length, 1);
  await createDraft();
  await chooseResident('moss');
  assert.equal((await mutations()).length, 1);
  await createDraft();
  await page.evaluate(() => editor.close());
  assert.equal((await mutations()).length, 1);
  await page.evaluate(() => editor.open());
  assert.equal(await field('name').inputValue(), 'New uncertain resident');
  assert.equal((await mutations()).length, 1);
  await field('name').fill('Edited after uncertainty');
  await page.getByTestId('bot-save').click(); await saved();
  const retried = await mutations();
  assert.equal(retried[1].args.body.clientOperationId, uncertain.args.body.clientOperationId);
  assert.deepEqual(retried[1].args.body.config, uncertain.args.body.config);
  assert.equal(retried[2].args.method, 'PATCH');
  assert.equal(retried[2].args.body.revision, 0);
  assert.equal(retried[2].args.body.patch.name, 'Edited after uncertainty');
  assert.equal(await page.evaluate(() => created), 1);
  assert.equal(await page.getByTestId('bot-delete').isVisible(), true);
  check('Uncertain create retry reuses exact body and operation ID, then serially saves later edits without duplication');

  await page.evaluate(() => setup());
  await chooseResident('moss');
  await field('name').fill('Snapshot one');
  await page.evaluate(() => { manual = true; editor.save(); editor.save(); });
  await page.waitForFunction(() => pending.length === 1);
  await field('privateInstructions').fill('Typed while the first save was pending');
  await page.evaluate(() => editor.updateMap({ spawn: { x: 2, z: 1 } }));
  await page.evaluate(() => accept());
  await page.waitForFunction(() => pending.length === 1);
  assert.equal(await page.evaluate(() => pending[0].args.body.revision), 1);
  assert.deepEqual(await page.evaluate(() => pending[0].args.body.patch.spawn), { x: 2, z: 1 });
  await page.evaluate(() => accept()); await saved();
  assert.equal(await page.evaluate(() => database.alpha[0].privateInstructions), 'Typed while the first save was pending');
  assert.equal(await page.evaluate(() => logs.requests.filter(r => r.args.method).length), 2);
  check('In-flight edits are preserved and drained as a second serialized CAS revision, without duplicate submits');

  await page.evaluate(() => setup());
  await page.evaluate(() => { holdGets = true; window.roomA = editor.setRoom(room('slow')); window.roomB = editor.setRoom(room('beta')); });
  assert.equal(await page.evaluate(() => pending.length), 2);
  await page.evaluate(() => { const newer = pending.pop(); newer.resolve(response(newer.url, newer.args)); });
  await page.waitForFunction(() => document.querySelector('.resident-room').textContent === 'Moon Studio');
  await page.evaluate(() => accept());
  assert.equal(await page.locator('[data-bot-id="ocean"]').count(), 1);
  assert.equal(await page.locator('[data-bot-id="moss"]').count(), 0);
  await createDraft();
  assert.equal(await page.locator('[data-appearance-id]').count(), 1);
  assert.equal(await page.locator('[data-appearance-id="ocean"]').count(), 1);
  check('An old room response resolving last cannot replace the current resident list or appearance catalog');

  await page.evaluate(() => setup());
  await chooseResident('moss');
  await field('name').fill('Stay here until saved');
  await page.evaluate(() => { failNext = { message: 'Room save failed' }; });
  assert.equal(await page.evaluate(() => editor.setRoom(room('beta'))), false);
  await page.getByTestId('bot-confirm-save').click(); await saved();
  assert.equal(await page.locator('.resident-room').innerText(), 'The Commons');
  assert.equal(await field('name').inputValue(), 'Stay here until saved');
  assert.match(await page.locator('.resident-error:not([hidden])').innerText(), /Room save failed/);
  await page.evaluate(() => { window.staleInput = document.querySelector('[data-bot-field="name"]'); });
  assert.equal(await page.evaluate(() => editor.setRoom(room('beta'))), false);
  await page.getByTestId('bot-confirm-save').click(); await saved();
  await page.waitForFunction(() => document.querySelector('.resident-room').textContent === 'Moon Studio');
  await chooseResident('ocean');
  await page.evaluate(() => { staleInput.value = 'Old detached write'; staleInput.dispatchEvent(new Event('input', { bubbles: true })); });
  assert.equal(await field('name').inputValue(), 'Ocean');
  check('Failed room-change save keeps the old draft visible; detached old fields cannot mutate a new room');

  await page.evaluate(() => setup());
  await chooseResident('moss');
  await field('behavior').selectOption('patrol');
  await page.getByTestId('bot-add-waypoint').click();
  await field('waypoints.0.x').fill('1'); await field('waypoints.0.z').fill('2');
  await page.getByTestId('bot-add-waypoint').click();
  await field('waypoints.1.x').fill('3'); await field('waypoints.1.z').fill('4');
  await page.getByRole('button', { name: 'Insert after waypoint 1', exact: true }).click();
  assert.deepEqual(await page.evaluate(() => editor.getDraft().waypoints), [{ x: 1, z: 2 }, { x: 2, z: 3 }, { x: 3, z: 4 }]);
  await page.getByRole('button', { name: 'Move waypoint 3 earlier', exact: true }).click();
  await page.getByRole('button', { name: 'Remove waypoint 1', exact: true }).click();
  assert.deepEqual(await page.evaluate(() => editor.getDraft().waypoints), [{ x: 3, z: 4 }, { x: 2, z: 3 }]);
  assert.equal(await page.locator('[data-plan-handle="waypoint"]').count(), 2);
  await page.getByText('Room plan & exact coordinates', { exact: true }).click();
  await page.locator('[data-plan-handle="waypoint"][data-index="0"]').focus();
  await page.keyboard.press('ArrowLeft');
  assert.equal(await field('waypoints.0.x').inputValue(), '3.4');
  assert.equal(await field('waypoints.0.z').inputValue(), '3.6');
  await page.locator('[data-plan-handle="radius"]').focus(); await page.keyboard.press('ArrowRight');
  assert.equal(await field('radius').inputValue(), '6.5');
  await page.getByTestId('bot-save').click(); await saved();
  assert.deepEqual(await page.evaluate(() => database.alpha[0].waypoints), [{ x: 3.4, z: 3.6 }, { x: 2, z: 3 }]);
  check('Ordered waypoint add, insertion, reordering, removal and keyboard plan handles persist in matching route order');

  await page.locator('[data-plan-handle="spawn"]').scrollIntoViewIfNeeded();
  const mark = await page.locator('[data-plan-handle="spawn"]').boundingBox();
  await page.mouse.move(mark.x + mark.width / 2, mark.y + mark.height / 2);
  await page.mouse.down(); await page.mouse.move(mark.x + mark.width / 2 + 12, mark.y + mark.height / 2 + 8, { steps: 4 }); await page.mouse.up();
  assert.notEqual(await field('spawn.x').inputValue(), '0');
  assert.equal(await page.evaluate(() => editor.getDraft().spawn.x), Number(await field('spawn.x').inputValue()));
  check('Pointer map dragging updates the same sidebar coordinates through SVG redraws');

  await field('behavior').selectOption('social');
  assert.match(await page.locator('.resident-detail').innerText(), /Public resident conversation is not connected/);
  assert.match(await page.locator('.resident-detail').innerText(), /No provider is attached[\s\S]*not executed/);
  assert.match(await page.locator('.resident-detail').innerText(), /Do not enter passwords or API keys/);
  await field('permissions.pause').uncheck();
  assert.equal(await page.locator('[data-live-command="pause"]').isDisabled(), true);
  await page.locator('[data-live-command="return"]').click(); await saved();
  await page.waitForFunction(() => logs.requests.at(-1).url.endsWith('/commands'));
  assert.equal((await mutations()).at(-1).args.body.command, 'return');
  assert.equal(await page.evaluate(() => database.alpha[0].permissions.pause), false);
  check('Unconnected social behavior is explicit and silent; local command permissions save before server-authorized commands');

  await page.evaluate(() => setup());
  await chooseResident('moss');
  await page.evaluate(() => { failNext = { status: 409, code: 'BOT_INACTIVE', message: 'A person must be in the room' }; });
  await page.locator('[data-live-command="pause"]').click();
  await page.waitForFunction(() => document.querySelector('.resident-error:not([hidden])')?.textContent.includes('A person'));
  assert.equal(await page.locator('.resident-recovery').isHidden(), true);
  await field('name').fill('Still editable after inactive command');
  assert.equal(await page.getByTestId('bot-save').isEnabled(), true);
  await page.getByTestId('bot-save').click(); await saved();
  await page.evaluate(() => { uncertainNext = true; });
  await page.locator('[data-live-command="pause"]').click();
  await page.waitForFunction(() => document.querySelector('.resident-error:not([hidden])')?.textContent.includes('Connection lost'));
  const firstCommand = (await mutations()).at(-1);
  await chooseResident('rose');
  await field('enabled').check();
  await page.locator('[data-live-command="pause"]').click();
  await page.waitForFunction(() => logs.requests.at(-1).url.includes('/rose/commands'));
  const otherCommand = (await mutations()).at(-1);
  assert.notEqual(firstCommand.args.body.clientOperationId, otherCommand.args.body.clientOperationId);
  check('Inactive command errors do not lock editing; an uncertain command receipt cannot leak across resident targets');

  await page.evaluate(() => setup());
  await chooseResident('moss'); await field('name').fill('My conflicting draft');
  await page.evaluate(() => { database.alpha[0].revision = 3; database.alpha[0].name = 'Other editor'; });
  await page.getByTestId('bot-save').click(); await saved();
  assert.equal(await field('name').inputValue(), 'My conflicting draft');
  assert.equal(await page.getByTestId('bot-save').isDisabled(), true);
  assert.equal(await page.evaluate(() => editor.close()), false);
  await page.getByRole('button', { name: 'Reload saved version', exact: true }).click();
  await page.getByRole('button', { name: 'Replace draft', exact: true }).click();
  await page.waitForFunction(() => editor.getDraft()?.name === 'Other editor');
  assert.equal(await page.evaluate(() => editor.isDirty()), false);
  check('Revision conflicts retain the draft, block Close and require an explicit reviewable reload');

  await page.getByTestId('bot-delete').click();
  await page.getByRole('button', { name: 'Keep resident', exact: true }).click();
  assert.equal((await mutations()).filter(r => r.args.method === 'DELETE').length, 0);
  await page.getByTestId('bot-delete').click();
  await page.getByRole('button', { name: 'Confirm delete', exact: true }).click();
  await page.waitForFunction(() => editor.getDraft() === null);
  assert.equal(await page.locator('[data-bot-id="moss"]').count(), 0);
  assert.equal((await mutations()).at(-1).args.body.revision, 3);
  check('Deletion requires an explicit confirmation and uses the selected immutable ID and current revision');

  await page.evaluate(() => setup());
  await chooseResident('moss');
  await field('name').fill('Keyboard-safe name');
  await page.evaluate(() => { window.keysLeaked = 0; document.addEventListener('keydown', () => keysLeaked++); });
  await page.keyboard.press('w'); await page.keyboard.press('ArrowLeft');
  assert.equal(await page.evaluate(() => keysLeaked), 0);
  await page.getByTestId('bot-reset').click();
  assert.equal(await field('name').inputValue(), 'Moss');
  await page.locator('summary', { hasText: 'Customize this look' }).click();
  await field('appearance.hairStyle').selectOption('curls');
  await field('appearance.topColor').selectOption('#e3b852');
  await page.screenshot({ path: 'evidence/bot-editor-desktop.png' });
  check('Focused text never reaches movement shortcuts; reset restores accepted state and native wardrobe selectors edit appearance');

  await page.setViewportSize({ width: 320, height: 700 });
  await field('behavior').selectOption('patrol');
  await page.getByTestId('bot-add-waypoint').click();
  const overflow = await page.evaluate(() => ({ page: document.documentElement.scrollWidth > innerWidth, panel: document.querySelector('.resident-panel').getBoundingClientRect().width > innerWidth, field: [...document.querySelectorAll('.resident-detail input')].some(e => e.getBoundingClientRect().right > innerWidth) }));
  assert.deepEqual(overflow, { page: false, panel: false, field: false });
  assert.equal(await field('name').evaluate(el => getComputedStyle(el).fontSize), '16px');
  await page.screenshot({ path: 'evidence/bot-editor-mobile.png' });
  await page.getByRole('button', { name: 'Back to residents', exact: true }).click();
  await page.getByTestId('bot-confirm-save').click();
  await page.waitForFunction(() => editor.getDraft() === null);
  assert.equal(await page.getByTestId('bot-create').isVisible(), true);
  check('320px layout has no horizontal overflow, touch-sized controls, readable inputs and equivalent list navigation');

  await page.evaluate(() => { denied = true; });
  await page.evaluate(() => editor.setRoom(room('forbidden')));
  assert.equal(await page.getByTestId('bot-create').isDisabled(), true);
  assert.equal(await page.locator('[data-bot-id]').count(), 0);
  assert.match(await page.locator('.resident-error:not([hidden])').innerText(), /cannot manage/);
  assert.equal(await page.evaluate(() => editor.select(null)), false);
  check('Server-denied room capability clears prior catalog and blocks creation and selection');
  assert.deepEqual(errors, []);
} catch (error) {
  checks.push({ name: 'failure', status: 'failed', error: error.stack }); console.error(error); process.exitCode = 1;
  await page.screenshot({ path: 'evidence/bot-editor-failure.png' }).catch(() => {});
} finally {
  await writeFile('evidence/bot-editor-checks.json', JSON.stringify({ checks, errors, limits: ['Isolated DOM/protocol fixture with controlled requests; no full renderer, WebGL or integrated production server used'] }, null, 2));
  await browser.close();
}
