/** Isolated CSS/DOM contract tests. No shared dist build, live DB or WebGL. */
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
import {icon,ICON_NAMES} from '../src/universe-icons.js';
const css=['places','social','express','editor','avatar-creator','command-palette','action-runtime','bot-editor','media','quests','personal-areas'];
const shell=(await readFile(new URL('../public/index.html',import.meta.url),'utf8')).replace(/<script[^>]+src="\/main.js"[^>]*><\/script>/,'').replace('<link rel="stylesheet" href="/main.css">',css.map(n=>`<link rel="stylesheet" href="/src/${n}.css">`).join(''));
const sample=`<section class="places-shell" id="brand-places"><header class="places-header"><div class="places-grow"><p class="places-eyebrow">YOUR UNIVERSE</p><h2 class="places-title">Places to belong</h2><p class="places-subtitle">A whole universe. A world for your people. A room of your own.</p></div><button class="places-btn places-close" aria-label="Close places">${icon('Close')}</button></header><nav class="places-tabs"><button class="places-tab" aria-selected="true">Explore</button><button class="places-tab">Memberships</button><button class="places-tab">Starred</button></nav><div class="places-body"><div class="places-catalog">${[['universe','Planet','Our Universe'],['world','Earth','Moon Garden'],['room','DoorOpen','The Commons']].map(([kind,glyph,name])=>`<button class="places-tree-item places-tree-${kind}" data-kind="${kind}" aria-current="${kind==='room'}"><span class="places-tree-icon">${icon(glyph)}</span><span class="places-tree-text"><span class="places-tree-kind">${kind}</span>${name}</span></button>`).join('')}<button class="places-btn" style="margin-top:20px">${icon('Plus','u-icon-sm')} New universe</button></div><div class="places-detail"><div class="places-breadcrumb"><button class="places-btn places-btn-quiet" data-kind="universe">${icon('Planet','u-icon-sm')} Our Universe</button><span>/</span><button class="places-btn places-btn-quiet" data-kind="world">${icon('Earth','u-icon-sm')} Moon Garden</button></div><h2 class="places-detail-title">The Commons</h2><div class="places-tags"><span class="places-badge" data-kind="room">Room</span><span class="places-badge places-badge-public">Public</span></div><article class="places-card" data-kind="room"><h3 class="places-card-title">Make room for possibility</h3><p class="places-muted">A quiet corner for friendly hellos, shared ideas, and a little creativity.</p><div class="places-actions"><button class="places-btn places-btn-primary">Enter The Commons ${icon('ArrowRight','u-icon-sm')}</button><button class="places-btn">${icon('Star','u-icon-sm')} Star room</button></div></article><p class="places-muted">Your permission: Owner</p><button class="places-btn">Edit details</button></div></div><footer class="places-local-note">Universe → World → Room · Local standalone places</footer></section>`;

const mediaSample=`<div class="universe-media" style="position:absolute;bottom:110px;left:11px;max-width:calc(100% - 22px)"><section class="media-dock"><div class="media-context"><span class="media-dot" data-state="connected"></span><div><strong class="media-context-label">Nearby conversation</strong><span class="media-context-detail">Devices stay off until you choose</span></div></div><div class="media-actions"><button class="media-join">Join audio</button><span class="media-divider"></span><button class="media-device" data-media="microphone" aria-pressed="false" aria-label="Microphone off">${icon('MicOff')}<span>Mic</span></button><button class="media-device" data-media="camera" aria-pressed="true" aria-label="Camera on">${icon('CamOn')}<span>Camera</span></button><button class="media-device" data-media="screen" aria-pressed="false" aria-label="Screen sharing off">${icon('Share')}<span>Share</span></button><button class="media-details-toggle" aria-label="Media details">${icon('Help')}</button></div></section></div>`;
const expressSample=`<div class="express-root"><div class="express-bubbles"><div class="express-bubble express-bubble-say express-self" style="left:50%;top:300px"><div class="express-bubble-card"><span class="express-bubble-name">Duplicate name</span><span class="express-bubble-text">Make room for possibility</span></div></div></div><section class="express-tray"><header class="express-header"><div class="express-heading"><span class="express-eyebrow">IN THE MOMENT</span><strong>Express yourself</strong></div><button class="express-close" aria-label="Close Express">${icon('Close')}</button></header><div class="express-mode-row"><div class="express-modes"><button class="express-mode" aria-pressed="true">Say</button><button class="express-mode" aria-pressed="false">Think</button></div><span class="express-intent">Visible to people nearby</span></div><div class="express-form"><input class="express-input" aria-label="Your expression" placeholder="Say something…"><button class="express-send ready" aria-label="Send expression">${icon('Send')}</button></div><div class="express-helper"><span>A little hello goes a long way</span><span>140</span></div><div class="express-emotes">${['👋','💜','🎉','👏','💡','👍'].map(x=>`<button class="express-emote" aria-label="React ${x}"><span>${x}</span></button>`).join('')}</div><div class="express-phrases"><button class="express-phrase">Hi!</button><button class="express-phrase">Be right back</button><button class="express-phrase">Nice work!</button></div><footer class="express-footer"><span>Enter to send · Escape to close</span><button class="express-customize">Make it yours</button></footer></section></div>`;
const fixture=kind=>shell.replace('</body>',`<div id="fixture-extra">${kind==='places'?sample:kind==='media'?mediaSample:kind==='express'?expressSample:''}</div><div id="state-fixture" style="position:absolute;top:160px;left:50%;display:flex;gap:20px"><button id="state-active" class="u-control active" aria-label="Active control">${icon('MicOn')}</button><button id="state-muted" class="u-control is-muted" aria-label="Muted control">${icon('MicOff')}</button><button id="state-disabled" class="u-control" disabled>${icon('CamOn')}</button></div><script type="module">import {icon} from '/src/universe-icons.js';document.querySelector('#welcome').hidden=true;document.querySelector('#state-fixture').hidden=${kind!=='states'};document.body.style.background='linear-gradient(130deg,#334c49,#243b36 45%,#1b2b29)';for(const [id,name]of Object.entries({'dock-explore':'Planet','dock-chat':'MessageCircle','dock-people':'Users','dock-media':'MicOn','dock-emote':'Emoji','dock-build':'Tools','dock-settings':'Settings','zoom-in':'Plus','zoom-out':'Minus','rotate-camera':'RotateLeft','camera-right':'RotateRight','camera-tilt-up':'ChevronUp','camera-tilt-down':'ChevronDown','camera-pan':'Move','camera-follow':'Focus','home-camera':'Home','shortcuts-help':'Help'})){const b=document.getElementById(id);if(b)b.querySelector('span')?b.querySelector('span').innerHTML=icon(name):b.innerHTML=icon(name)}document.querySelector('#dock-chat').classList.add('active');window.ready=true;</script></body>`);
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path==='/'){res.setHeader('content-type','text/html');res.end(fixture(new URL(req.url,'http://localhost').searchParams.get('view')));return}const file=path.startsWith('/src/')?'..'+path:'../public'+path;res.setHeader('content-type',path.endsWith('.css')?'text/css':path.endsWith('.js')?'text/javascript':path.endsWith('.ttf')?'font/ttf':path.endsWith('.woff2')?'font/woff2':path.endsWith('.png')?'image/png':'image/svg+xml');res.end(await readFile(new URL(file,import.meta.url)))}catch{res.statusCode=404;res.end('Not found')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const browser=await launch(),checks=[],errors=[];
await mkdir('evidence',{recursive:true});
try{
 const context=await browser.newContext({viewport:{width:1280,height:860},reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/?view=states');await page.waitForFunction(()=>window.ready);await page.evaluate(()=>document.fonts.ready);
 for(const id of ['state-active','state-muted']){await page.locator('#'+id).focus();const c=await page.locator('#'+id).evaluate(e=>({outline:getComputedStyle(e).outlineColor,width:getComputedStyle(e).outlineWidth,offset:getComputedStyle(e).outlineOffset,bg:getComputedStyle(e).backgroundImage,color:getComputedStyle(e).backgroundColor}));assert.equal(c.outline,'rgb(255, 255, 255)');assert.equal(c.width,'2px');assert.equal(c.offset,'-3px');checks.push({name:id+' keeps separate white focus ring',computed:c})}
 const stable=await page.locator('#state-active').boundingBox();await page.locator('#state-active').evaluate(e=>e.classList.remove('active'));assert.deepEqual(await page.locator('#state-active').boundingBox(),stable);checks.push({name:'state changes do not move control bounds'});
 await page.locator('#state-disabled').evaluate(e=>{e.addEventListener('click',()=>window.disabledActivated=true);e.click()});assert.equal(await page.evaluate(()=>!!window.disabledActivated),false);checks.push({name:'native disabled target cannot activate'});
 const font=await page.evaluate(async()=>{await document.fonts.load('700 24px Space');return [...document.fonts].filter(f=>f.family==='Space').map(f=>({weight:f.weight,status:f.status}))});assert.deepEqual(font,[{weight:'700',status:'loaded'}]);checks.push({name:'static Space Grotesk loads as700',font});
 const shadow=await page.locator('#dock').evaluate(e=>getComputedStyle(e).boxShadow);assert(!shadow.includes('48px'));checks.push({name:'persistent dock has no popup elevation/glow',shadow});
 await page.goto(base);await page.waitForFunction(()=>window.ready);await page.screenshot({path:'evidence/brand-port-shell-desktop.png'});
 await page.goto(base+'/?view=places');await page.waitForFunction(()=>window.ready);await page.evaluate(()=>document.fonts.ready);assert.match(await page.locator('.places-shell').evaluate(e=>getComputedStyle(e).fontFamily),/^Inter/);await page.screenshot({path:'evidence/brand-port-places-desktop.png'});const kinds=await page.locator('.places-tree-icon').evaluateAll(es=>es.map(e=>getComputedStyle(e).color));assert.deepEqual(kinds,['rgb(167, 139, 250)','rgb(45, 212, 191)','rgb(251, 191, 36)']);checks.push({name:'Orbit kinds have source colors and Inter is scoped',kinds});
 for(const size of [{width:320,height:700},{width:360,height:760},{width:640,height:360}]){const c=await browser.newContext({viewport:size,isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await c.newPage();await p.goto(base);await p.waitForFunction(()=>window.ready);const dims=await p.locator('#dock button,#view-controls button,#shortcuts-help').evaluateAll(es=>es.filter(e=>getComputedStyle(e).display!=='none'&&e.getClientRects().length).map(e=>({id:e.id,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));for(const x of dims){assert(x.w>=48,`${size.width} ${x.id} width ${x.w}`);assert(x.h>=48,`${size.width} ${x.id} height ${x.h}`)}assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),size.width);const logo=await p.locator('.brand-logo').boundingBox();assert.equal(logo.width/logo.height,2);assert.equal(await p.evaluate(()=>matchMedia('(hover: hover)').matches),false);await p.screenshot({path:`evidence/brand-port-shell-${size.width}x${size.height}.png`});await p.goto(base+'/?view=places');await p.waitForFunction(()=>window.ready);const placeDims=await p.locator('.places-shell button').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({text:e.textContent,h:e.getBoundingClientRect().height})));for(const x of placeDims)assert(x.h>=48,`${x.text}: ${x.h}`);await p.screenshot({path:`evidence/brand-port-places-${size.width}x${size.height}.png`});checks.push({name:`${size.width}x${size.height} coarse targets, no viewport overflow, 2:1 logo`,targets:dims.length});await c.close()}
 for(const view of ['media','express']){for(const size of [{width:1280,height:860},{width:320,height:700},{width:640,height:360}]){const c=await browser.newContext({viewport:size,isMobile:size.width<700,hasTouch:true,reducedMotion:'reduce'}),p=await c.newPage();await p.goto(base+'/?view='+view);await p.waitForFunction(()=>window.ready);const target=view==='media'?'.media-dock':'.express-tray';const b=await p.locator(target).boundingBox();assert(b.x>=0&&b.x+b.width<=size.width,`${view} ${size.width} overflow`);const dims=await p.locator(target+' button').evaluateAll(es=>es.map(e=>({name:e.getAttribute('aria-label')||e.textContent,h:e.getBoundingClientRect().height})));for(const x of dims)assert(x.h>=48,`${view} ${x.name}: ${x.h}`);if(view==='media'){await p.locator('[data-media=camera]').focus();assert.equal(await p.locator('[data-media=camera]').evaluate(e=>getComputedStyle(e).outlineColor),'rgb(255, 255, 255)')}else{assert.equal(await p.locator('.express-bubble-name').isVisible(),false);assert.equal(await p.locator('.express-bubble-text').evaluate(e=>getComputedStyle(e).fontSize),'11px')}await p.screenshot({path:`evidence/brand-port-${view}-${size.width}x${size.height}.png`});checks.push({name:`${view} ${size.width} coarse controls and source states`});await c.close()}}
 assert.equal(ICON_NAMES.length,47);assert.deepEqual(errors,[]);console.log(JSON.stringify(checks,null,2));
}catch(e){errors.push(e.stack);process.exitCode=1;console.error(e)}finally{await writeFile('evidence/brand-port-results.json',JSON.stringify({checks,errors,scope:'Isolated real CSS and source-shell DOM; no WebGL or full app behavior certification'},null,2));await browser.close();await new Promise(r=>server.close(r))}
