import {launch} from '../scripts/browser.mjs';import {createGameServer} from '../server/app.mjs';import {seedWorlds} from '../src/worlds.js';import assert from 'node:assert/strict';import {writeFile,mkdir} from 'node:fs/promises';
const app=createGameServer({seeds:seedWorlds,dist:new URL('../dist',import.meta.url).pathname});const address=await app.listen(0),base='http://127.0.0.1:'+address.port;const browser=await launch();const checks=[],errors=[],requests=[];let ctxA,ctxB,primary;
const check=(name,detail={})=>{checks.push({name,status:'passed',...detail});console.log('PASS',name);};
const state=p=>p.evaluate(()=>window.__universe.getState());
async function guest(name,opts={}){const ctx=await browser.newContext({viewport:{width:1440,height:960},...opts});const page=await ctx.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.status()!==401)requests.push({url:r.url(),status:r.status()});});await page.goto(base+'/?room=commons');await page.getByPlaceholder('Your name').fill(name);await page.getByRole('button',{name:'Enter Universe'}).click();await page.waitForFunction(()=>window.__universe?.getState().ready);return {ctx,page};}
try{const a=await guest('Avery');ctxA=a.ctx;const p=a.page;primary=p;assert.equal((await state(p)).room.id,'commons');assert.equal((await state(p)).room.role,'owner');check('Desktop onboarding creates authenticated owner session and intended room');
const before=(await state(p)).position;await p.keyboard.down('w');await p.waitForFunction(before=>{const p=window.__universe.getState().position;return Math.hypot(p.x-before.x,p.z-before.z)>1;},before);await p.keyboard.up('w');const after=(await state(p)).position;assert(Math.hypot(after.x-before.x,after.z-before.z)>1);check('WASD moves the actual Woka');
await p.locator('#dock-chat').click();await p.getByRole('textbox',{name:'Message the room'}).fill('wasd stays in chat');const typingBefore=(await state(p)).position;await p.keyboard.type('wasd');await p.waitForTimeout(250);assert.deepEqual((await state(p)).position,typingBefore);check('Typing in chat suppresses movement');
const b=await guest('Robin');ctxB=b.ctx;const q=b.page;await p.waitForFunction(()=>window.__universe.getState().people.length===2);assert.equal((await state(q)).room.role,'guest');assert(await q.locator('#dock-build').isDisabled());check('Second independent session appears live; public guest cannot build or gain membership');
await q.locator('#dock-chat').click();await p.getByRole('textbox',{name:'Message the room'}).fill('Hello from the Commons');await p.getByRole('button',{name:'Send message',exact:true}).click();await q.getByText('Hello from the Commons',{exact:true}).waitFor();check('Persistent room chat reaches another authenticated client live');
await p.getByRole('button',{name:'Close social panel'}).click();await p.locator('#dock-build').click();const original=(await state(p)).scene.objects.length;await p.locator('[data-tool="plant"]').click();await p.locator('#game').click({position:{x:680,y:500}});assert.equal((await state(p)).scene.objects.length,original+1);await p.locator('#editor').getByRole('button',{name:'Save room',exact:true}).click();await p.waitForFunction(()=>!window.__universe.getEditor().dirty);await q.waitForFunction(n=>window.__universe.getState().scene.objects.length===n,original+1);check('In-game placement saves durably and synchronizes to another client');
await p.locator('[data-tool="lamp"]').click();await p.locator('#game').click({position:{x:650,y:600}});assert.equal((await state(p)).scene.objects.length,original+2);await p.locator('#editor').getByRole('button',{name:'↶',exact:true}).click();assert.equal((await state(p)).scene.objects.length,original+1);await p.locator('#editor').getByRole('button',{name:'↷',exact:true}).click();assert.equal((await state(p)).scene.objects.length,original+2);await p.locator('#editor').getByRole('button',{name:'Save room',exact:true}).click();await p.waitForFunction(()=>!window.__universe.getEditor().dirty);check('Editor undo, redo and repeat save work');
await p.screenshot({path:'evidence/build-desktop.png'});await p.reload();await p.waitForFunction(()=>window.__universe?.getState().ready);assert.equal((await state(p)).scene.objects.length,original+2);check('Reload restores server-saved scene and guest identity');
await p.locator('#dock-explore').click();await p.getByRole('button',{name:'Enter The Studio',exact:true}).click();await p.waitForFunction(()=>window.__universe.getState().room.id==='studio');await p.waitForTimeout(200);assert.equal((await state(q)).people.length,1);check('Room explorer travels; old-room presence removes departed user');await p.screenshot({path:'evidence/studio-desktop.png'});
await p.locator('#dock-settings').click();await p.getByRole('textbox',{name:'Display name',exact:true}).fill('Avery updated');await p.getByRole('button',{name:'Choose Woka 4',exact:true}).click();await p.getByRole('button',{name:'Save profile',exact:true}).click();await p.waitForFunction(()=>window.__universe.getState().user.name==='Avery updated');assert.equal((await state(p)).user.woka,3);check('Profile and Woka update persist through server');
await p.getByRole('button',{name:'Close social panel'}).click();await p.locator('#dock-media').click();assert(await p.getByRole('button',{name:/microphone|mic/i}).count()>0);check('Real media controls mount without implicit device capture');await p.screenshot({path:'evidence/media-desktop.png'});
await ctxB.close();ctxB=null;const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});ctxB=mobile;const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto(base);await m.getByPlaceholder('Your name').fill('Mobile Robin');await m.getByRole('button',{name:'Enter Universe'}).click();await m.waitForFunction(()=>window.__universe?.getState().ready);assert(await m.locator('#joystick').isVisible());const box=await m.locator('#joystick').boundingBox();const mobileBefore=(await state(m)).position;const cdp=await mobile.newCDPSession(m);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2+27,y:box.y+box.height/2,id:1}]});await m.waitForFunction(before=>{const p=window.__universe.getState().position;return Math.hypot(p.x-before.x,p.z-before.z)>.5;},mobileBefore);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const mobileAfter=(await state(m)).position;assert(Math.hypot(mobileAfter.x-mobileBefore.x,mobileAfter.z-mobileBefore.z)>0.5);check('390px touch joystick moves and releases');
await m.locator('#dock-chat').tap();await m.getByRole('textbox',{name:'Message the room'}).fill('Hello from touch');await m.getByRole('button',{name:'Send message',exact:true}).tap();await m.getByText('Hello from touch',{exact:true}).waitFor();assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth),390);await m.screenshot({path:'evidence/chat-mobile.png'});check('Mobile chat fits viewport and sends');await m.getByRole('button',{name:'Close social panel'}).tap();await m.screenshot({path:'evidence/commons-mobile.png'});
assert.deepEqual(errors,[]);check('No page runtime exceptions in tested desktop/touch flows');
}catch(e){if(primary)await primary.screenshot({path:'evidence/failure.png'}).catch(()=>{});console.error(e);checks.push({name:'run failure',status:'failed',error:e.stack});process.exitCode=1;}finally{await writeFile('evidence/browser-checks.json',JSON.stringify({checks,errors,requests,limits:['Cloud Chromium SwiftShader; no physical phones','No successful real media transport assertion','Local standalone services, not Matrix or production Universe']},null,2));await ctxA?.close();await ctxB?.close();await browser.close();await app.close();}
