import {build}from'esbuild';import{mkdtemp,cp,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import assert from'node:assert/strict';import{launch}from'../scripts/browser.mjs';import{seedWorlds}from'../src/worlds.js';import{createGameServer}from'../server/app.mjs';
const dir=await mkdtemp(join(tmpdir(),'universe-camera-walk-'));await cp('public',dir,{recursive:true});await build({entryPoints:['src/main.js'],outdir:dir,bundle:true,format:'esm',splitting:true,minify:true,target:'es2022'});
const app=createGameServer({seeds:seedWorlds,dist:dir}),address=await app.listen(0),browser=await launch(),page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(60000);const check=name=>{checks.push({name,status:'passed'});console.log('PASS',name)};
try{await page.goto('http://127.0.0.1:'+address.port,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!window.__universe,{},{timeout:60000});await page.getByPlaceholder('Your name').fill('Garden explorer');await page.getByRole('button',{name:'Enter Universe'}).click();await page.waitForFunction(()=>window.__universe?.getState().ready);await page.waitForTimeout(400);const no=page.getByRole('button',{name:'Not now',exact:true});if(await no.isVisible())await no.click();await page.locator('#game').focus();
async function assertLabelsClear(){const data=await page.evaluate(()=>{const boxes=[...document.querySelectorAll('#hud > .brand, #hud > .room-heading, #hud > .hud-right, #quest-open, #area-banner, #view-controls, #dock, #quick-actions, #shortcuts-help')].filter(e=>!e.hidden&&e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').map(e=>e.getBoundingClientRect());const all=[...document.querySelectorAll('.world-label')],visible=all.filter(e=>getComputedStyle(e).visibility==='visible'&&getComputedStyle(e).display!=='none');return{visible:visible.length,hidden:all.length-visible.length,overlaps:visible.filter(e=>{const r=e.getBoundingClientRect();return boxes.some(b=>r.left<b.right+8&&r.right>b.left-8&&r.top<b.bottom+8&&r.bottom>b.top-8)}).map(e=>e.textContent)}});assert.deepEqual(data.overlaps,[]);return data;}
let suppressed=0;for(const size of[{width:1280,height:800},{width:390,height:844}]){await page.setViewportSize(size);await page.waitForTimeout(200);for(let i=0;i<8;i++){await page.getByRole('button',{name:'Orbit camera right',exact:true}).click();if(i===3)await page.getByRole('button',{name:'Tilt camera down',exact:true}).click();await page.waitForTimeout(120);const result=await assertLabelsClear();suppressed+=result.hidden;}await page.screenshot({path:`evidence/finishing-hud-labels-${size.width<700?'mobile':'desktop'}.png`});}assert(suppressed>0);check('measured label bounds avoid actual HUD rectangles across desktop/mobile camera orbits');await page.setViewportSize({width:1280,height:800});await page.getByRole('button',{name:'Reset camera',exact:true}).click();await page.waitForTimeout(250);await page.screenshot({path:'evidence/finishing-integrated-arrival.png'});

const before=await page.evaluate(()=>window.__universe.getState().position);await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.up('w');await page.screenshot({path:'evidence/textured-native-walking-desktop.png'});await page.waitForTimeout(500);const after=await page.evaluate(()=>window.__universe.getState().position);assert(Math.hypot(after.x-before.x,after.z-before.z)>1);check('actual WASD walk moves native character through textured Commons');
const oldCamera=await page.evaluate(()=>window.__universe.getCamera());await page.mouse.move(780,320);await page.mouse.down({button:'right'});await page.mouse.move(980,360,{steps:10});await page.mouse.up({button:'right'});await page.waitForTimeout(250);const orbit=await page.evaluate(()=>({camera:window.__universe.getCamera(),position:window.__universe.getState().position}));assert(Math.abs(orbit.camera.yaw-oldCamera.yaw)>.4);assert(Math.hypot(orbit.position.x-after.x,orbit.position.z-after.z)<.01);check('right-drag orbit changes 3D view without walking');await page.screenshot({path:'evidence/textured-native-orbit-desktop.png'});
await page.locator('#dock-build').click();const pose=await page.evaluate(()=>window.__universe.getCamera());assert(Math.abs(pose.yaw-orbit.camera.yaw)<.01);check('actual Build entry retains the current orbit');await page.locator('#editor [data-tool="chair"]').click();const count=await page.evaluate(()=>window.__universe.getState().scene.objects.length);await page.mouse.move(790,310);await page.mouse.down({button:'right'});await page.mouse.move(630,350,{steps:8});await page.mouse.up({button:'right'});await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.__universe.getState().scene.objects.length),count);check('camera orbit with armed furniture tool never drops an object');await page.screenshot({path:'evidence/textured-native-builder-orbit.png'});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);const touchBefore=await page.evaluate(()=>window.__universe.getCamera().distance);const touch=await page.context().newCDPSession(page);await touch.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:11,x:120,y:330},{id:12,x:240,y:330}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:11,x:85,y:300},{id:12,x:280,y:300}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(150);const touchAfter=await page.evaluate(()=>({distance:window.__universe.getCamera().distance,count:window.__universe.getState().scene.objects.length}));assert(touchAfter.distance<touchBefore);assert.equal(touchAfter.count,count);check('two-finger mobile pinch/orbit changes camera without placing armed furniture');await page.screenshot({path:'evidence/textured-native-touch-camera.png'});

assert.deepEqual(errors,[]);await writeFile('evidence/camera-walkthrough-results.json',JSON.stringify({checks,errors,start:before,end:after},null,2));}catch(error){console.error(error);await page.screenshot({path:'evidence/camera-walkthrough-failure.png'}).catch(()=>{});await writeFile('evidence/camera-walkthrough-results.json',JSON.stringify({checks,errors,failure:error.stack},null,2));process.exitCode=1;}finally{await browser.close();await app.close();await rm(dir,{recursive:true,force:true});}
