import {CAMERA_LIMITS} from '../src/camera-rig.js';
import {build} from 'esbuild';
import {readFile,writeFile,rm} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {launch} from '../scripts/browser.mjs';
import {seedWorlds} from '../src/worlds.js';
const {createGameServer}=await import('../server/app.mjs');
await build({stdin:{contents:`import{EngineStore}from'@babylonjs/core/Engines/engineStore.js';import{createRenderer}from'./src/renderer.js';import{seedWorlds}from'./src/worlds.js';const r=await createRenderer(document.querySelector('canvas'),document.querySelector('#labels'));r.sync(seedWorlds[0].rooms[0].scene);r.syncPeople([{id:'self',name:'Camera explorer',woka:0,x:0,z:7,self:true,direction:0}]);r.setTarget(0,7);let last=0;function loop(t){const dt=Math.min(.05,(t-last)/1000||.016);last=t;r.render(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);await r.ready;window.r=r;window.peerHeading=id=>EngineStore.LastCreatedScene.getTransformNodeByName('avatar-'+id)?.rotation.y;window.areaOverlayCount=()=>EngineStore.LastCreatedScene.meshes.reduce((n,m)=>n+(m.metadata?.type==='area'?1:m.metadata?.ranges?.filter(r=>r.metadata?.type==='area').length||0),0);`,resolveDir:process.cwd()},bundle:true,format:'esm',minify:true,outfile:'evidence/camera-harness.js'});
const app=createGameServer({seeds:seedWorlds,dist:new URL('../dist',import.meta.url).pathname}),address=await app.listen(0),browser=await launch(),page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[],checks=[];
page.on('pageerror',e=>{errors.push(e.message);page.evaluate(message=>{window.__renderError=message},e.message).catch(()=>{});});const check=name=>{checks.push({name,status:'passed'});console.log('PASS',name)};
await page.route('**/camera-harness.js',async r=>r.fulfill({contentType:'text/javascript',body:await readFile('evidence/camera-harness.js')}));
await page.route('**/camera-harness',r=>r.fulfill({contentType:'text/html',body:'<html><head><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#14121e}canvas{width:100%;height:100%;display:block;touch-action:none}#labels{position:absolute;inset:0;pointer-events:none}.world-label{position:absolute;left:0;top:0;color:#ede8f3;font:12px sans-serif;white-space:nowrap;text-shadow:0 1px 4px #14121e}</style></head><body><canvas></canvas><div id="labels"></div><script type="module" src="/camera-harness.js"></script></body></html>'}));
try{
 await page.goto(`http://127.0.0.1:${address.port}/camera-harness`);await page.waitForFunction(()=>!!window.r||window.__renderError);const startup=await page.evaluate(()=>window.__renderError);if(startup)throw new Error(startup);await page.waitForTimeout(1800);await page.screenshot({path:'evidence/camera-textured-desktop.png'});
 assert.equal(await page.evaluate(()=>areaOverlayCount()),0);check('normal play contains no area-debug overlay geometry');const initial=await page.evaluate(()=>r.getCameraState());await page.evaluate(()=>r.setBuild(true));const built=await page.evaluate(()=>r.getCameraState());assert((await page.evaluate(()=>areaOverlayCount()))>0);assert.equal(initial.yaw,built.yaw);assert.equal(initial.tilt,built.tilt);assert.equal(initial.distance,built.distance);assert(Math.abs(initial.target.z-built.target.z)<.05);check('enter Build preserves camera pose');
 await page.evaluate(()=>r.setFollow(false));
 for(const angle of [0,.55,-1.1]){await page.evaluate(a=>r.rotate(a),angle);await page.waitForTimeout(100);const picked=await page.evaluate(()=>{const p=r.screenPoint(-6,-2,1);return {p,hit:r.pick(p.x,p.y)}});assert.equal(picked.hit.id,'commons-table');check('camera-relative merged face pick at orbit '+angle);}
 const ray=await page.evaluate(()=>{const p=r.screenPoint(19,15,0);return r.pick(p.x,p.y)});assert(ray.point);assert(Math.abs(ray.point.x-19)<.015);assert(Math.abs(ray.point.z-15)<.015);check('ground ray projection persists outside floor bounds');
 await page.evaluate(()=>r.orbit(70,35));const a=await page.evaluate(()=>r.getCameraState());assert.notEqual(a.yaw,initial.yaw);assert.notEqual(a.tilt,initial.tilt);await page.evaluate(()=>r.pan(80,-40));assert.equal((await page.evaluate(()=>r.getCameraState())).follow,false);check('orbit, tilt and pan change pose without follow snapping');
 await page.evaluate(()=>{r.zoom(-999);r.render(.01)});assert.equal((await page.evaluate(()=>r.getCameraState())).distance,CAMERA_LIMITS.minDistance);await page.evaluate(()=>r.zoom(999));assert.equal((await page.evaluate(()=>r.getCameraState())).distance,CAMERA_LIMITS.maxDistance);check('zoom clamps safely');
 await page.evaluate(()=>{r.resetCamera();r.setGhost({type:'table',x:-2,z:5,rotation:45,valid:true});r.setDestination({x:4,z:6});});await page.waitForTimeout(350);await page.screenshot({path:'evidence/camera-ghost-valid.png'});
 const ghostPick=await page.evaluate(()=>{const p=r.screenPoint(-2,5,1);return r.pick(p.x,p.y)});assert.notEqual(ghostPick.id,'ghost-preview');check('ghost cannot steal placement or selection ray');
 await page.evaluate(()=>r.setGhost({type:'table',x:-2,z:5,rotation:45,valid:false}));await page.waitForTimeout(250);await page.screenshot({path:'evidence/camera-ghost-invalid.png'});
 await page.evaluate(()=>{r.setGhost(null);r.setBuild(false);r.resetCamera();});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(600);await page.screenshot({path:'evidence/camera-textured-mobile.png'});const point=await page.evaluate(()=>r.screenPoint(0,7,1));assert(point.visible);assert(Math.abs(point.x-195)<5);check('mobile resize preserves player framing and projection');
 await page.evaluate(()=>{r.orbit(190,-80);r.zoom(-7)});await page.waitForTimeout(300);await page.screenshot({path:'evidence/camera-low-angle-mobile.png'});
 await page.evaluate(()=>r.syncPeople([{id:'self',name:'Camera explorer',woka:0,x:0,z:7,self:true},{id:'peer-test',name:'Heading fixture',woka:1,x:2,z:6,rotation:Math.PI/4,direction:1,moving:true,running:true}]));await page.waitForTimeout(800);const peerAngle=await page.evaluate(()=>peerHeading('peer-test'));assert(Math.abs(Math.atan2(Math.sin(peerAngle-Math.PI/4),Math.cos(peerAngle-Math.PI/4)))<.025);check('legacy remote peer preserves exact diagonal rotation despite coarse direction');await page.evaluate(()=>r.syncPeople([{id:'self',name:'Camera explorer',woka:0,x:0,z:7,self:true}]));
 const stats=await page.evaluate(()=>r.getStats());assert(stats.meshes<100);assert(stats.drawCalls>0&&stats.drawCalls<150);assert(stats.textures>=6);assert.deepEqual(errors,[]);check('textured room stays below100 meshes with clean runtime');
 await writeFile('evidence/camera-renderer-results.json',JSON.stringify({checks,errors,stats},null,2));
}catch(e){console.error(e);await page.screenshot({path:'evidence/camera-test-failure.png'}).catch(()=>{});await writeFile('evidence/camera-renderer-results.json',JSON.stringify({checks,errors,failure:e.stack},null,2));process.exitCode=1;}finally{await browser.close();await app.close();await rm('evidence/camera-harness.js',{force:true});}
