import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
const html=`<meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}#social{position:fixed;left:8px;right:8px;top:var(--social-sheet-top);height:var(--social-sheet-height);background:#eee}#handle{height:48px;touch-action:none;background:#ccc}</style><section id="social"><div id="handle" tabindex="0" role="separator">Resize conversation</div></section><script type="module">import {mountSocialSheet} from '/sheet.js';window.sheet=mountSocialSheet(document.querySelector('#social'),document.querySelector('#handle'));window.ready=true;</script>`;
const server=http.createServer(async(req,res)=>{res.setHeader('Content-Type',req.url==='/sheet.js'?'text/javascript':'text/html');res.end(req.url==='/sheet.js'?await readFile(new URL('../src/social-sheet-layout.js',import.meta.url)):html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await launch(),context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),checks=[];
const check=async(name,fn)=>{await fn();checks.push(name);console.log('PASS',name);};
try{
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.ready);const cdp=await context.newCDPSession(page);
 const height=()=>page.locator('#social').evaluate(n=>n.getBoundingClientRect().height);
 async function drag(){const box=await page.locator('#handle').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:50,y:box.y+24}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:50,y:box.y-20}]});}
 await check('native touch cancellation restores height and releases capture',async()=>{const before=await height();await drag();assert((await height())>before);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(await height(),before);assert.equal(await page.locator('#social').getAttribute('data-sheet-resizing'),null);});
 await check('external hidden/inert cancels an in-progress gesture',async()=>{const before=await height();await drag();await page.locator('#social').evaluate(n=>n.inert=true);await page.waitForFunction(()=>!document.querySelector('#social').hasAttribute('data-sheet-resizing'));await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await height(),before);await page.locator('#social').evaluate(n=>n.inert=false);});
 await check('viewport shrink clamps and restores the preferred height without remounting',async()=>{await page.locator('#handle').press('Home');const before=await height();await page.setViewportSize({width:390,height:620});await page.waitForFunction(()=>document.querySelector('#social').getBoundingClientRect().bottom<=innerHeight);assert((await height())<=620);await page.setViewportSize({width:390,height:844});await page.waitForFunction(h=>Math.abs(document.querySelector('#social').getBoundingClientRect().height-h)<1,before);});
 await check('destroy during native drag removes capture, CSS state and all resize behavior',async()=>{await drag();await page.evaluate(()=>sheet.destroy());await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.setViewportSize({width:320,height:568});await page.locator('#handle').press('ArrowUp');assert.equal(await page.locator('#social').getAttribute('style'),'');assert.equal(await page.locator('#social').getAttribute('data-sheet-resizing'),null);});
 await mkdir('evidence/compact-conversations',{recursive:true});await writeFile('evidence/compact-conversations/sheet-results.json',JSON.stringify({checks,scope:'Native Chromium CDP touch events, emulated viewport, no physical device.'},null,2));
}finally{await context.close();await browser.close();await new Promise(r=>server.close(r));}
