import test from 'node:test';
import assert from 'node:assert/strict';
import {createContentWindowModality} from '../src/content-window-modality.js';
function node(inert=false){return{value:inert,writes:0,get inert(){return this.value;},set inert(v){this.value=v;this.writes++;}};}
function fixture(){let state={open:false,maximized:false},higher=false,elements=[];const foreground=[];const control=createContentWindowModality({getWindow:()=>state,hasHigherSurface:()=>higher,getCoveredElements:()=>elements,setForeground:v=>foreground.push(v)});return{control,foreground,state:v=>state=v,higher:v=>higher=v,elements:v=>elements=v};}
test('maximized content covers only supplied lower surfaces and restores their prior inert state',()=>{const f=fixture(),canvas=node(),disabled=node(true),dialog=node();f.elements([canvas,disabled]);f.control.sync();assert.equal(canvas.inert,false);f.state({open:true,maximized:true});f.control.sync();assert.equal(canvas.inert,true);assert.equal(dialog.inert,false);f.state({open:true,maximized:false});f.control.sync();assert.equal(canvas.inert,false);assert.equal(disabled.inert,true);});
test('a higher dialog owns content foreground while lower surfaces remain covered',()=>{const f=fixture(),canvas=node();f.elements([canvas]);f.state({open:true,maximized:true});f.control.sync();f.higher(true);f.control.sync();assert.equal(f.foreground.at(-1),false);assert.equal(canvas.inert,true);f.higher(false);f.control.sync();assert.equal(f.foreground.at(-1),true);f.state({open:false,maximized:false});f.control.sync();assert.equal(canvas.inert,false);});
test('repeated synchronization is inert-write-free and handles replaced lower surfaces',()=>{const f=fixture(),old=node(),next=node();f.elements([old]);f.state({open:true,maximized:true});f.control.sync();for(let i=0;i<600;i++)f.control.sync();assert.equal(old.writes,1);f.elements([next]);f.control.sync();assert.equal(old.inert,false);assert.equal(next.inert,true);f.control.destroy();assert.equal(next.inert,false);});
test('foreground callbacks cannot recursively synchronize the cover ledger',()=>{const canvas=node();let control,calls=0;control=createContentWindowModality({getWindow:()=>({open:true,maximized:true}),getCoveredElements:()=>[canvas],setForeground:()=>{calls++;control.sync();}});control.sync();assert.equal(calls,1);assert.equal(canvas.writes,1);control.destroy();assert.equal(canvas.inert,false);});
