/** GPU-free product controls with a synthetic membership projection. */
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
const server=http.createServer(async(req,res)=>{if(req.url==='/controls.js'){res.setHeader('content-type','text/javascript');return res.end(await readFile('src/proximity-controls-ui.js'));}if(req.url==='/controls.css'){res.setHeader('content-type','text/css');return res.end(await readFile('src/proximity-controls.css'));}res.end('<!doctype html><link rel="stylesheet" href="/controls.css"><body style="background:#333"><div id="root"></div><script type="module" src="/fixture.js"></script>');});
server.prependListener('request',(req,res)=>{if(req.url!=='/fixture.js')return;res.setHeader('content-type','text/javascript');res.end(`import {mountProximityControls} from '/controls.js';window.calls=[];const c={accountId:'guest',memberId:'m1',roomId:'r',connectionId:'c1',bubbleId:'b1',membershipRevision:1,participants:[{accountId:'guest',name:'Guest'},{accountId:'peer',name:'Nearby person'}],locked:false,canLock:true,canInvite:true,followers:[]};const s={available:true,canAct:true,context:c,invitations:[],ignoreRequests:false};const controller={snapshot:()=>s,subscribe:()=>()=>{},lock:()=>calls.push('lock'),invite:()=>{},setIgnoreRequests:()=>{},refresh:()=>{}};window.ui=mountProximityControls({root:document.querySelector('#root'),controller,onChat:()=>calls.push('chat'),onMedia:()=>calls.push('media')});window.ready=true;`);});
// The main listener must leave the script response untouched.
const listeners=server.listeners('request');server.removeAllListeners('request');server.on('request',(req,res)=>{if(req.url==='/fixture.js')return listeners[0](req,res);return listeners[1](req,res);});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await launch(),page=await browser.newPage();let checks=0;
try{for(const viewport of[{width:1280,height:900},{width:320,height:568},{width:667,height:375}]){await page.setViewportSize(viewport);await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.ready);const primary=page.locator('[data-control=chat]');await primary.click();await page.locator('[data-control=call]').click();assert.deepEqual(await page.evaluate(()=>calls),['chat','media']);assert.equal(await page.locator('[data-control=lock]').isVisible(),false);await page.getByLabel('More bubble controls').click();const lock=page.locator('[data-control=lock]');await lock.click();assert.equal(await page.evaluate(()=>calls.at(-1)),'lock');const box=await lock.boundingBox();assert(box.x>=0&&box.x+box.width<=viewport.width);await page.getByLabel('More bubble controls').click();assert.equal(await lock.isVisible(),false);checks++;console.log('PASS compact conversation controls',viewport.width,viewport.height);}}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}assert.equal(checks,3);
