/** Actual bundled game, authenticated local saves, native pointer/touch input.
 * Diagnostics only read state, projection and layout; no editor helper calls. */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds,emptyScene} from '../src/worlds.js';
import {validatePlacement,validateTerrainEdit} from '../src/editor-geometry.js';
import {applyTerrainRect} from '../src/terrain.js';
import {launch} from '../scripts/browser.mjs';
const out=process.env.EDITOR_COMPACT_EVIDENCE||'evidence/editor-compact';await mkdir(out,{recursive:true});
const seeds=structuredClone(seedWorlds);seeds[0].rooms[0].scene={...emptyScene(),bounds:{width:30,depth:24},spawn:{x:0,z:5},objects:[],areas:[]};
const app=createGameServer({database:':memory:',seeds,dist:new URL('../dist',import.meta.url).pathname,questsEnabled:false}),{port}=await app.listen(0),browser=await launch();
const checks=[],errors=[],saveEvidence=[],responseTasks=[];const saveRequests=new Map();let page,context,touch,storageState,cdp,phase;
const scene=()=>page.evaluate(()=>__universe.getState().scene),editor=()=>page.evaluate(()=>__universe.getEditor());
const measure=locator=>locator.evaluate(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{tag:el.tagName,rect:r.toJSON(),clientHeight:el.clientHeight,scrollHeight:el.scrollHeight,hit:el===hit||el.contains(hit),target:hit?.outerHTML.slice(0,160),width:innerWidth,height:innerHeight};});
async function hit(locator){const m=await measure(locator);assert(m.rect.x>=0&&m.rect.y>=0&&m.rect.right<=m.width+.5&&m.rect.bottom<=m.height+.5,JSON.stringify(m));assert(m.hit,JSON.stringify(m));return m;}
async function press(locator){const m=await hit(locator);if(m.tag==='BUTTON')assert(m.rect.width>=44&&m.rect.height>=44,'Preserve full-size editing targets: '+JSON.stringify(m));await locator[touch?'tap':'click']();}
async function scroll(locator,amount){const m=await hit(locator);if(!touch){await page.mouse.move(m.rect.x+m.rect.width/2,m.rect.y+m.rect.height/2);await page.mouse.wheel(0,amount);}else{const x=m.rect.right-18,start=m.rect.bottom-20,end=Math.max(m.rect.top+20,start-amount);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x,y:start}]});for(let i=1;i<=6;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x,y:start+(end-start)*i/6}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}await page.waitForFunction(el=>el.scrollTop>0,await locator.elementHandle());}
async function pointFor(type='chair'){
 await page.waitForFunction(()=>{const f=__universe.getCamera().framing;return f.status==='manual'||!f.targetOffset||Math.hypot(f.offset.x-f.targetOffset.x,f.offset.y-f.targetOffset.y)<1;});
 const state=await page.evaluate(()=>__universe.getState());
 // Terrain uses lower-corner cells. Aim inside the intended cell on the ground
 // plane, not at a furniture center projected above a shared grid boundary.
 const points=await page.evaluate(type=>{const points=[];for(let cx=-10;cx<=10;cx++)for(let cz=-8;cz<=8;cz++){const x=cx+(type==='terrain'?.5:0),z=cz+(type==='terrain'?.5:0),p=__universe.getScreenPoint(x,z,type==='terrain'?0:.1);if(p?.visible&&p.x>18&&p.x<innerWidth-18&&p.y>100&&p.y<innerHeight-85&&[-18,0,18].every(dx=>[-18,0,18].every(dy=>document.elementFromPoint(p.x+dx,p.y+dy)?.id==='game')))points.push({x,z,p});}return points;},type);
 const chosen=points.find(({x,z})=>{
  if(Math.hypot(x-state.position.x,z-state.position.z)<=3)return false;
  if(type!=='terrain')return validatePlacement(state.scene,{type,x,z,rotation:0},{position:state.position}).valid;
  const cx=Math.floor(x),cz=Math.floor(z);if(state.scene.terrain?.cells.some(cell=>cell[0]===cx&&cell[1]===cz))return false;
  return validateTerrainEdit(state.scene,{minX:cx,minZ:cz,maxX:cx,maxZ:cz},{material:'water',blocked:true},{position:state.position}).valid;
 });
 assert(chosen,'An unobscured valid '+type+' point must remain available');return chosen;
}
async function worldPress(p){assert.equal(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id,p),'game');if(touch)await page.touchscreen.tap(p.x,p.y);else await page.mouse.click(p.x,p.y);}
async function save(){
 const evidence={phase,before:await page.evaluate(()=>({state:__universe.getState(),editor:__universe.getEditor()})),requests:[]};saveEvidence.push(evidence);
 await press(page.getByRole('button',{name:'Save room',exact:true}));await page.waitForFunction(()=>!__universe.getEditor().saving);await Promise.all(responseTasks);
 evidence.after=await page.evaluate(()=>({state:__universe.getState(),editor:__universe.getEditor(),status:document.querySelector('.editor-status')?.textContent,recovery:document.querySelector('.builder-recovery')?.textContent}));
 assert.equal(evidence.after.editor.dirty,false,JSON.stringify(evidence));assert.equal(evidence.requests.length,1,'Native Save sends exactly one request');assert.equal(evidence.requests[0].status,200,JSON.stringify(evidence.requests));
 const saved=await scene();assert.deepEqual(saved,evidence.before.state.scene,'Save preserves the exact native draft');
 const response=await page.request.get(`http://127.0.0.1:${port}/api/rooms/${evidence.before.state.room.id}`);assert.equal(response.status(),200);evidence.persisted=(await response.json()).room;assert.deepEqual(evidence.persisted.scene,saved,'Authenticated read confirms exact persistence');return saved;
}
async function pass(name,fn){phase=name;const detail=await fn();checks.push({name,status:'passed',...detail});console.log('PASS',name);}
try{
 for(const scenario of[{name:'landscape-pointer',width:568,height:320,touch:false},{name:'landscape-touch',width:568,height:320,touch:true},{name:'portrait-touch',width:320,height:568,touch:true}]){
  touch=scenario.touch;context=await browser.newContext({viewport:{width:scenario.width,height:scenario.height},deviceScaleFactor:touch?2:1,hasTouch:touch,isMobile:touch,...(storageState?{storageState}:{})});page=await context.newPage();page.on('request',r=>{if(/\/scene(?:\/operations)?$/.test(new URL(r.url()).pathname)&&['PUT','POST'].includes(r.method())){const entry={url:r.url(),method:r.method(),body:r.postDataJSON()};saveRequests.set(r,entry);saveEvidence.at(-1)?.requests.push(entry);}});page.on('response',r=>{const entry=saveRequests.get(r.request());if(entry){entry.status=r.status();responseTasks.push(r.text().then(body=>{entry.responseBody=body;try{entry.response=JSON.parse(body);}catch{entry.response=null;}}));}});page.on('requestfailed',r=>{const entry=saveRequests.get(r);if(entry)entry.failure=r.failure();});page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));if(touch)cdp=await context.newCDPSession(page);
  await page.goto(`http://127.0.0.1:${port}`,{waitUntil:'domcontentloaded'});if(!storageState){await page.locator('#display-name').fill('Compact editor owner');await page.locator('#join-button').click();}await page.waitForFunction(()=>window.__universe?.getState().ready,null,{timeout:60000});await press(page.locator('#dock-build'));await page.waitForFunction(()=>document.querySelector('#editor').dataset.compact==='true');
  await pass(scenario.name+': Room replaces Furniture with a substantial inspector; native scroll keeps close and Save stable',async()=>{
   await page.screenshot({path:out+'/'+scenario.name+'-furniture.png'});await press(page.locator('.builder-room-settings'));assert.equal(await page.locator('.builder-tray').isVisible(),false);const body=await measure(page.locator('.inspector'));assert(body.clientHeight>=140,JSON.stringify(body));const env=page.locator('select[data-focus-key=Environment]');await press(env);await page.keyboard.press((await scene()).theme==='garden'?'End':'Home');await page.keyboard.press('Enter');await page.locator('.builder-inspector-heading').click();assert((await editor()).dirty,'Native environment change creates a draft');await scroll(page.locator('.inspector'),160);await hit(page.getByRole('button',{name:'Close item details',exact:true}));await hit(page.getByRole('button',{name:'Save room',exact:true}));await page.screenshot({path:out+'/'+scenario.name+'-room-scrolled.png'});await save();await press(page.getByRole('button',{name:'Close item details',exact:true}));return{body};
  });
  await pass(scenario.name+': Water receives the initial native input and terrain saves without closing the editor',async()=>{
   await press(page.getByRole('button',{name:'Terrain',exact:true}));const water=page.getByRole('button',{name:'Paint water',exact:true}),waterLayout=await hit(water);await press(water);assert.equal(await water.getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#editor').isVisible(),true);await page.screenshot({path:out+'/'+scenario.name+'-terrain.png'});await press(page.getByRole('button',{name:'Close terrain palette',exact:true}));const target=await pointFor('terrain'),before=await scene(),cell={x:Math.floor(target.x),z:Math.floor(target.z)};await worldPress(target.p);await page.waitForFunction(n=>(__universe.getState().scene.terrain?.cells.length||0)===n+1,before.terrain?.cells.length||0);const expected=applyTerrainRect(before.terrain,{minX:cell.x,minZ:cell.z,maxX:cell.x,maxZ:cell.z},{material:'water',blocked:true});assert.deepEqual((await scene()).terrain,expected,'Native input paints exactly the chosen ground cell');const saved=await save();assert.deepEqual(saved.terrain,expected);return{waterLayout,paintPoint:target,cell};
  });
  await pass(scenario.name+': native chair placement, visible Rotate, explicit More Undo/Redo, Save and reload preserve the draft',async()=>{
   await press(page.getByRole('button',{name:'＋ Furniture',exact:true}));await press(page.getByRole('button',{name:/^Place Chair$/}));const rotate=page.locator('.builder-toolbelt .builder-rotate');await hit(rotate);await press(rotate);const rotation=(await editor()).rotation,target=await pointFor(),before=(await scene()).objects.length;await worldPress(target.p);await page.waitForFunction(n=>__universe.getState().scene.objects.length===n+1,before);const chair=(await scene()).objects.at(-1);assert.equal(chair.rotation,rotation);await page.screenshot({path:out+'/'+scenario.name+'-placed.png'});
   await press(page.getByRole('button',{name:'More build tools',exact:true}));await press(page.getByRole('button',{name:'Undo',exact:true}));assert.equal((await scene()).objects.length,before);await press(page.getByRole('button',{name:'Redo',exact:true}));assert.equal((await scene()).objects.length,before+1);await press(page.getByRole('button',{name:'Close more build tools',exact:true}));await press(page.getByRole('button',{name:'↖ Select',exact:true}));const q=await page.evaluate(o=>__universe.getScreenPoint(o.x,o.z,.5),chair);await worldPress(q);await page.waitForFunction(id=>__universe.getEditor().selected===id,chair.id);assert.equal(await page.locator('.builder-inspector').isVisible(),true);await press(page.locator('.inspector .editor-actions button').filter({hasText:'Rotate'}));assert.equal((await scene()).objects.at(-1).rotation,(rotation+90)%360);
   const validDraft=await scene(),validHistory=(await editor()).undo;await press(page.getByRole('button',{name:'Close item details',exact:true}));await press(page.getByRole('button',{name:'Terrain',exact:true}));await press(page.getByRole('button',{name:'Paint water',exact:true}));await press(page.getByRole('button',{name:'Close terrain palette',exact:true}));const blockedPoint=await page.evaluate(o=>__universe.getScreenPoint(o.x+.15,o.z+.15,0),chair);await worldPress(blockedPoint);const rejected=await editor();assert.equal(rejected.preview.valid,false);assert.match(rejected.preview.reason,/Overlaps Chair/);assert.deepEqual(await scene(),validDraft,'Rejected terrain preserves the exact unsaved chair draft');assert.equal(rejected.undo,validHistory);assert.equal(rejected.dirty,true);await page.screenshot({path:out+'/'+scenario.name+'-blocked-terrain.png'});
   const saved=await save();await press(page.getByRole('button',{name:'Close editor',exact:true}));await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__universe?.getState().ready);assert.deepEqual(await scene(),saved);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),scenario.width);return{chairId:chair.id,placement:target,rotation:(rotation+90)%360,rejectedTerrain:rejected.preview};
  });
  storageState=await context.storageState();await context.close();context=null;
 }
 assert.deepEqual(errors,[]);
}catch(error){checks.push({name:phase,status:'failed',error:error.stack});console.error(error);if(page&&!page.isClosed()){console.log(await page.evaluate(()=>({editor:window.__universe?.getEditor(),root:document.querySelector('#editor')?.outerHTML.slice(0,1500)})));await page.screenshot({path:out+'/failure.png'}).catch(()=>{});}process.exitCode=1;
}finally{const hash=async path=>createHash('sha256').update(await readFile(path)).digest('hex');await writeFile(out+'/results.json',JSON.stringify({checks,errors,saveEvidence,bundle:{js:await hash('dist/main.js'),css:await hash('dist/main.css')},limits:['Native Chromium mouse, keyboard and CDP touch; software WebGL','Touch emulation at DPR2, not physical phones','Synthetic local account and scene, real authenticated local save/reload, no external service']},null,2));await context?.close();await browser.close();await app.close();}
