import {build} from 'esbuild';
import {launch} from '../scripts/browser.mjs';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const source=`import {mountEditor} from './src/editor.js';import {emptyScene} from './src/worlds.js';
window.emptyScene=emptyScene;const scene=emptyScene();scene.objects=[{id:'board',type:'board',name:'Welcome board',x:4,z:3,url:'https://example.org/old',text:'An old description',document:{id:'doc',name:'Old guide.pdf',size:12}}];scene.areas=[{id:'area',name:'Reading zone',x:-4,z:0,width:4,depth:4,action:'welcome',message:'Original primary message'}];
window.state={scene,room:{id:'first',role:'owner',revision:1,scene:structuredClone(scene)},position:{x:0,z:7}};window.logs={requests:[],toasts:[]};window.pending=[];window.limited=false;
window.editor=mountEditor({root:document.querySelector('#editor'),getState:()=>state,onScene:scene=>state.scene=scene,onSelect:()=>{},toast:t=>logs.toasts.push(t),editPolicy:()=>limited?{canEdit:true,canEditItem:o=>o.id==='board',validateChange:(before,after)=>window.blockScopedHistory?'Ownership changed':before.theme!==after.theme?'Room settings are restricted':after.objects.some(o=>o.x>8)?'Outside owned area':null}:null,api:(url,args)=>{logs.requests.push({url,args});return new Promise((resolve,reject)=>pending.push({resolve,reject,args,url}));}});editor.attachRoom();editor.setBuild(true);editor.select('board');
window.accept=()=>{const p=pending.shift();p.resolve({room:{id:p.url.split('/')[3],revision:2,scene:structuredClone(p.args.body.scene)}})};window.newRoom=()=>{state.scene=emptyScene();state.room={id:'second',role:'owner',revision:1,scene:structuredClone(state.scene)};editor.attachRoom()};`;
const bundle=await build({stdin:{contents:source,resolveDir:process.cwd(),sourcefile:'editor-actions-fixture.js'},bundle:true,format:'iife',write:false});
const browser=await launch(),page=await browser.newPage();const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const check=name=>{checks.push({name,status:'passed'});console.log('PASS',name)};
const key=k=>page.locator('[data-focus-key="'+k+'"]');
try{
 // Give the editor a viewport-height lane before its ResizeObserver measures it.
 await page.route('https://editor.test/',route=>route.fulfill({status:200,contentType:'text/html',body:'<style>#editor{min-height:100vh}</style><canvas id="game" tabindex="0"></canvas><aside id="editor"></aside>'}));await page.goto('https://editor.test/');await page.addScriptTag({content:bundle.outputFiles[0].text});
 await page.locator('[data-section="item-actions"] summary').click();assert.equal(await page.locator('.action-card').count(),1);assert.equal(await page.evaluate(()=>state.scene.objects[0].actions),undefined);check('Legacy interactions render without mutating a saved scene');
 await key('add:link').click();await key('add:audio').click();await key('add:message').click();await key('add:teleport').click();const ids=await page.evaluate(()=>state.scene.objects[0].actions.map(a=>a.id));assert.equal(ids.length,5);assert.equal(ids[0],'legacy-url');assert.equal(await page.evaluate(()=>state.scene.objects[0].url),'https://example.org/old');assert.equal(await page.evaluate(()=>state.scene.objects[0].document.name),'Old guide.pdf');check('Item supports ordered message, link, audio and travel alongside normalized legacy link');
 await key(ids[1]+':name').fill('Research link');await key(ids[1]+':name').press('Tab');await key(ids[1]+':url').fill('https://example.org/research');await key(ids[1]+':url').press('Tab');assert.equal(await page.evaluate(()=>state.scene.objects[0].actions[0].url),'https://example.org/old');assert.equal(await page.evaluate(()=>state.scene.objects[0].actions[1].url),'https://example.org/research');check('Repeated field names target the correct stable action ID');
 await key(ids[1]+':mode').selectOption('embed');await key(ids[1]+':width').fill('45');await key(ids[1]+':width').press('Tab');await key(ids[1]+':closable').selectOption('false');await key(ids[2]+':label').fill('Gentle ambience');await key(ids[2]+':label').press('Tab');await key(ids[2]+':volume').fill('0');await key(ids[2]+':volume').press('Tab');await key(ids[2]+':loop').selectOption('false');check('Link mode, panel size, closability and sound label, zero volume, loop are editable');
 await key(ids[1]+':name').fill('Research link after typing');await key(ids[1]+':move:-1').click();assert.equal(await page.evaluate(()=>state.scene.objects[0].actions[0].id),ids[1]);await page.getByRole('button',{name:'Undo',exact:true}).click();check('Clicking an action control flushes focused text without swallowing the click');
 await key(ids[1]+':move:-1').focus();await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>state.scene.objects[0].actions[0].id),ids[1]);assert.equal(await page.evaluate(()=>document.activeElement.dataset.focusKey),ids[1]+':move:-1');await page.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual(await page.evaluate(()=>state.scene.objects[0].actions.map(a=>a.id)),ids);await page.getByRole('button',{name:'Redo',exact:true}).click();assert.equal(await page.evaluate(()=>state.scene.objects[0].actions[0].id),ids[1]);check('Move up/down is undoable and retains keyboard focus on the same action');
 await key(ids[3]+':message').fill('Typing r d Delete must stay text');const count=await page.evaluate(()=>state.scene.objects.length);await page.keyboard.press('r');assert.equal(await page.evaluate(()=>state.scene.objects.length),count);await page.keyboard.press('Control+s');assert.equal(await page.evaluate(()=>editor.isSaving()),true);assert.equal(await page.evaluate(()=>logs.requests.at(-1).args.body.scene.objects[0].actions.find(a=>a.type==='message').message),'Typing r d Delete must stay textr');await page.evaluate(()=>accept());await page.waitForFunction(()=>!editor.isSaving());assert.equal(await page.evaluate(()=>editor.isDirty()),false);check('Ctrl+S from focused text flushes unblurred fields into the exact save snapshot');
 await key(ids[1]+':description').fill('Unblurred click-save description');assert.equal(await page.getByRole('button',{name:'Save room',exact:true}).isEnabled(),true);await page.getByRole('button',{name:'Save room',exact:true}).click();assert.equal(await page.evaluate(()=>logs.requests.at(-1).args.body.scene.objects[0].actions[0].description),'Unblurred click-save description');await page.evaluate(()=>accept());await page.waitForFunction(()=>!editor.isSaving());check('Pending text enables Save and click-save flushes field changes');
 await key(ids[4]+':delete').click();assert.equal(await page.evaluate(()=>state.scene.objects[0].actions.length),4);await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await page.evaluate(()=>state.scene.objects[0].actions.length),5);check('Delete action is recoverable with Undo');
 await key(ids[1]+':url').fill('javascript:alert(1)');const beforeRequests=await page.evaluate(()=>logs.requests.length);await page.keyboard.press('Control+s');assert.equal(await page.evaluate(()=>logs.requests.length),beforeRequests);assert.equal(await page.evaluate(()=>editor.isDirty()),true);assert.match(await page.locator('.builder-recovery').innerText(),/safe HTTP/);await key(ids[1]+':url').fill('https://example.org/research');await key(ids[1]+':url').press('Tab');check('Unsafe URL stops before network save and preserves recoverable draft');
 await page.evaluate(()=>editor.select('area'));await page.locator('[data-section="area-actions"] summary').click();await key('add:link').click();await key('add:link').click();await key('add:audio').click();await key('add:audio').click();const areaIds=await page.evaluate(()=>state.scene.areas[0].actions.map(a=>a.id));await key(areaIds[0]+':trigger').selectOption('enter');await key(areaIds[3]+':move:-1').click();assert.equal(await page.evaluate(()=>state.scene.areas[0].actions[2].id),areaIds[3]);assert.equal(await page.evaluate(()=>state.scene.areas[0].message),'Original primary message');assert.equal(await page.evaluate(()=>state.scene.areas[0].actions[0].trigger),'enter');check('Area supports two links and two sounds in saved order without changing primary semantics');
 await page.evaluate(()=>editor.select('board'));await page.locator('[data-section="item-actions"] summary').click();await page.evaluate(()=>{window.staleInput=document.querySelector('[data-focus-key="'+state.scene.objects[0].actions[0].id+':name"]');window.staleInput.value='Late wrong-room update';window.staleChange=window.staleInput.onchange;});await page.evaluate(()=>newRoom());await page.evaluate(()=>staleChange());assert.equal(await page.evaluate(()=>state.scene.objects.length),0);assert.equal(await page.evaluate(()=>editor.isDirty()),false);check('Detached field callback cannot mutate a newly attached room');
 await page.evaluate(()=>{state.scene.objects=[{id:'board',type:'board',name:'Fresh board',x:4,z:3,actions:[]}];state.room.scene=structuredClone(state.scene);editor.attachRoom();editor.select('board');});await page.locator('[data-section="item-actions"] summary').click();await key('add:message').click();await page.evaluate(()=>{editor.save();});assert.equal(await page.evaluate(()=>editor.isSaving()),true);await page.evaluate(()=>{state.scene=emptyScene();state.room={id:'third',role:'owner',revision:8,scene:structuredClone(state.scene)};editor.attachRoom();});assert.equal(await page.evaluate(()=>editor.isSaving()),false);await page.evaluate(()=>accept());await page.waitForTimeout(20);assert.equal(await page.evaluate(()=>state.room.id),'third');assert.equal(await page.evaluate(()=>state.room.revision),8);assert.equal(await page.evaluate(()=>state.scene.objects.length),0);check('Late save completion cannot overwrite or keep a newer room locked');
 await page.evaluate(()=>{state.scene.objects=[{id:'board',type:'board',name:'Owned board',x:4,z:3,actions:[]}];state.room={id:'scoped',role:'member',revision:1,scene:structuredClone(state.scene)};limited=true;editor.attachRoom();editor.select('board');});assert.equal(await page.getByRole('button',{name:'⚙ Room',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'▱ Area',exact:true}).isDisabled(),true);await page.locator('[data-section="item-actions"] summary').click();await key('add:message').click();assert.equal(await page.evaluate(()=>state.scene.objects[0].actions.length),1);await key('X').fill('12');await key('X').press('Tab');assert.equal(await page.evaluate(()=>state.scene.objects[0].x),4);assert.equal(await page.evaluate(()=>logs.toasts.at(-1)),'Outside owned area');check('Optional limited policy allows owned-object actions while guarding room settings and every mutation');
 await page.evaluate(()=>{window.blockScopedHistory=true;editor.undo();});assert.equal(await page.evaluate(()=>state.scene.objects[0].actions.length),1);assert.equal(await page.evaluate(()=>logs.toasts.at(-1)),'Ownership changed');await page.evaluate(()=>{window.blockScopedHistory=false;editor.undo();window.blockScopedHistory=true;editor.redo();});assert.equal(await page.evaluate(()=>state.scene.objects[0].actions.length),0);check('Undo and redo recheck current scoped authority rather than reviving stale edit rights');
 assert.deepEqual(errors,[]);
}catch(e){checks.push({name:'failure',status:'failed',error:e.stack});console.error(e);process.exitCode=1;}finally{await writeFile('evidence/editor-actions-checks.json',JSON.stringify({checks,errors,limits:['Isolated editor browser fixture; full renderer/provider/network behavior tested separately']},null,2));await browser.close();}
