import {build} from 'esbuild';
import {launch} from '../scripts/browser.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const out='evidence/editor-polish-feedback';await mkdir(out,{recursive:true});
const bundle=await build({stdin:{contents:`import {mountEditor} from './src/editor.js';import {emptyScene} from './src/worlds.js';window.state={user:{id:'editor'},room:{id:'r',role:'editor',revision:1},scene:{...emptyScene(),objects:[{id:'a',name:'Chair',type:'chair',x:4,z:3,rotation:0},{id:'b',name:'Other chair',type:'chair',x:6,z:3,rotation:0}]},position:{x:0,z:0}};state.room.scene=structuredClone(state.scene);window.editor=mountEditor({root:document.querySelector('#editor'),getState:()=>state,onScene:s=>state.scene=s,onSelect:()=>{},api:async()=>{},toast:()=>{},getCameraAngle:()=>-Math.PI/2});editor.attachRoom();editor.setBuild(true);`,resolveDir:process.cwd()},bundle:true,write:false,format:'iife'});
const browser=await launch(),p=await browser.newPage(),checks=[];
const pass=name=>{checks.push(name);console.log('PASS',name);};
try{
 await p.route('https://editor.test/',r=>r.fulfill({contentType:'text/html',body:'<style>#editor{height:960px}</style><canvas id="game" tabindex="0"></canvas><aside id="editor"></aside>'}));await p.goto('https://editor.test/');await p.addScriptTag({content:bundle.outputFiles[0].text});await p.evaluate(()=>editor.select('a'));
 const snapshot=()=>p.evaluate(()=>JSON.stringify(state.scene));const original=await snapshot();await p.locator('.editor-actions button').first().focus();for(const key of ['ArrowRight','Delete','r','d'])await p.keyboard.press(key);assert.equal(await snapshot(),original);await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>state.scene.objects[0].rotation),90);pass('Focused controls own arrows/delete/letter keys; native Space still rotates');
 await p.locator('#game').focus();await p.keyboard.press('d');assert.equal(await p.evaluate(()=>editor.getInteractionState().preview.valid),false);assert.match(await p.locator('.builder-hint').innerText(),/Overlaps/);pass('Duplicate starts with honest overlap rejection, not a success instruction');
 await p.keyboard.press('Escape');await p.evaluate(()=>editor.select('a'));await p.locator('#game').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>state.scene.objects[0].x),5);await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>state.scene.objects[0].x),5);assert.match(await p.locator('.builder-hint').innerText(),/Overlaps/);pass('Rejected keyboard nudge retains geometry and its actual rejection reason');
 await p.evaluate(()=>{editor.pointerDown({id:'a',point:{x:5,z:3}},{pointerId:1,clientX:0,clientY:0});editor.pointerMove({point:{x:8,z:5}},{pointerId:1,clientX:40,clientY:40});});assert.equal(await p.locator('#editor').getAttribute('data-dragging'),'true');await p.getByRole('button',{name:'Grid 1m',exact:true}).click();assert.equal(await p.locator('#editor').getAttribute('data-dragging'),'false');await p.evaluate(()=>editor.pointerUp({point:{x:8,z:5}},{pointerId:1}));assert.equal(await p.evaluate(()=>state.scene.objects[0].x),5);pass('Changing grid cancels the complete pending drag without committing it');
 await p.evaluate(()=>editor.undo());assert.match(await p.locator('button[aria-label=Redo]').getAttribute('title'),/Move Chair/);pass('History intent follows the actual undo/redo snapshots');
 await p.locator('.builder-room-settings').click();assert.equal(await p.locator('.builder-inspector .editor-polish-feedback').getAttribute('hidden'),'');pass('Room settings removes obsolete selection feedback and keeps its scroll area');
}finally{await browser.close();await writeFile(out+'/results.json',JSON.stringify({checks,scope:'Isolated real editor DOM; synthetic input hits and scene; no renderer/server claims'},null,2));}
