/** Editor DOM lifecycle checks with controlled receipts/events. The companion
 * editor-save-ack-ordering.browser.mjs uses real SQLite/HTTP/native SSE. */
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
const source=`import {mountEditor} from './src/editor.js';
import {emptyScene,clone} from './src/worlds.js';
import {personalEditPolicy} from './src/personal-editor-policy.js';
import {imageDefinitions,resolvedImage} from './src/image-asset-context.js';
import {normalizeImageAssetDraft,validateImageDefinition} from './src/image-asset-schema.js';
window.install=()=>{
 const scene=emptyScene();window.state={scene,room:{id:'r',name:'Receipt room',role:'editor',revision:1,capabilities:{canEditScene:true,canBuild:true,canEditObjects:true},personalAreas:[],imageDefinitions:{},scene:clone(scene)},user:{id:'actor'},position:{x:0,z:7}};
 window.logs={scenes:[],toasts:[],requests:[]};window.pending=[];
 window.editor=mountEditor({root:document.querySelector('#editor'),getState:()=>state,onScene:s=>{state.scene=s;logs.scenes.push(JSON.stringify(s));},onSelect:()=>{},toast:t=>logs.toasts.push(t),editPolicy:personalEditPolicy,api:(url,args)=>{logs.requests.push({url,args});return new Promise((resolve,reject)=>pending.push({resolve,reject}));}});
 editor.attachRoom();editor.setBuild(true);
};
window.room=(revision,patch={})=>({...clone(state.room),revision,scene:{...emptyScene(),objects:[{id:'server-'+revision,name:'Server '+revision,type:'chair',x:-4,z:-3,rotation:0}]},...patch});
window.draft=()=>{editor.setTool('chair');editor.pick({point:{x:4,z:3}});window.exactDraft=JSON.stringify(state.scene);};
window.start=()=>{draft();window.settled=editor.save();};
window.receipt=()=>({...clone(state.room),revision:2,scene:JSON.parse(exactDraft)});
window.accept=async value=>{pending.shift().resolve({room:value||receipt()});await settled;};
window.fail=async ({status=500,room,code}={})=>{pending.shift().reject(Object.assign(Error('Controlled failure'),{status,data:{room,code}}));await settled;};
window.entry=(revision=1,status='active')=>{const stamp='2026-10-02T00:00:00.000Z',definition={schemaVersion:1,assetId:'image',roomId:'r',createdBy:'actor',createdAt:stamp,originKind:'upload'},version={...normalizeImageAssetDraft({name:'Image revision '+revision,floating:true},{width:64,height:64,byteLength:100,mediaType:'image/png'}),schemaVersion:1,assetId:'image',roomId:'r',versionId:'v1',sequence:1,sha256:'a'.repeat(64),createdBy:'actor',createdAt:stamp};return {...validateImageDefinition(definition,version),status,revision};};
window.definition=()=>imageDefinitions(state.scene)['image:v1'];
window.resolveImage=()=>resolvedImage(state.scene,state.scene.objects.find(o=>o.type==='image'));
install();`;
const bundle=await build({stdin:{contents:source,resolveDir:process.cwd(),sourcefile:'receipt-lifecycle-fixture.js'},bundle:true,format:'iife',write:false});
const browser=await launch(),checks=[],errors=[],out='evidence/editor-save-reconciliation';await mkdir(out,{recursive:true});
async function check(name,fn){let context;try{context=await browser.newContext({acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(60000);page.setDefaultNavigationTimeout(60000);page.on('pageerror',e=>errors.push(e.message));await page.bringToFront();await page.route('https://receipt.test/',r=>r.fulfill({contentType:'text/html',body:'<canvas id="game" tabindex="0"></canvas><aside id="editor"></aside>'}));await page.goto('https://receipt.test/');await page.addScriptTag({content:bundle.outputFiles[0].text});await fn(page);checks.push({name,status:'passed'});console.log('PASS',name);}catch(error){checks.push({name,status:'failed',error:error.stack});console.error('FAIL',name,error);process.exitCode=1;}finally{await context?.close();}}
const read=page=>page.evaluate(()=>({scene:JSON.stringify(state.scene),room:state.room,dirty:editor.isDirty(),saving:editor.isSaving(),scenes:logs.scenes,toasts:logs.toasts,history:editor.getInteractionState().undo}));
try{
 await check('Ordinary save applies the canonical receipt and preserves valid local undo',async p=>{
  await p.evaluate(()=>{start();window.accepted=receipt();accepted.scene.objects[0].name='Canonical name';});await p.evaluate(()=>accept(accepted));const s=await read(p);assert.equal(s.room.revision,2);assert.equal(JSON.parse(s.scene).objects[0].name,'Canonical name');assert.equal(s.dirty,false);assert.equal(s.history,1);assert.equal(await p.evaluate(()=>logs.requests[0].args.deferRoomPreparation),true);
 });
 await check('Highest scene wins independently of later lower-revision live metadata',async p=>{
  await p.evaluate(()=>{start();window.accepted=receipt();editor.receiveScene(room(4));editor.receiveScene(room(3));editor.receiveScene(room(2,{role:'member',capabilities:{canBuild:false,canEditScene:false,canEditObjects:false},personalAreas:[{areaId:'desk',ownerId:'other',revision:8}]}));});assert.equal((await read(p)).scenes.length,1);
  await p.evaluate(()=>accept(accepted));const s=await read(p);assert.equal(s.room.revision,4);assert.equal(JSON.parse(s.scene).objects[0].id,'server-4');assert.equal(s.room.role,'member');assert.equal(s.room.personalAreas[0].revision,8);assert.equal(s.history,0);assert.equal(s.dirty,false);assert.equal(await p.locator('button[data-tool=chair]').isDisabled(),true);
 });
 for(const status of [409,500])await check('Failure '+status+' preserves the exact draft and exports it before loading the highest observed server revision',async p=>{
  await p.evaluate(()=>{start();editor.receiveScene(room(4));editor.receiveScene(room(3));});await p.evaluate(status=>fail({status,code:status===409?'REVISION_CONFLICT':undefined,room:room(2)}),status);
  let s=await read(p);assert.equal(s.scene,await p.evaluate(()=>exactDraft));assert.equal(s.room.revision,1);assert.equal(s.dirty,true);assert.equal(s.saving,false);assert.equal(s.scenes.length,1);
  const downloadPromise=p.waitForEvent('download');await p.getByRole('button',{name:'Export my draft',exact:true}).click();const download=await downloadPromise;const file=out+'/draft-'+status+'.json';await download.saveAs(file);assert.equal(JSON.stringify(JSON.parse(await readFile(file,'utf8')).scene),s.scene);
  await p.evaluate(()=>editor.receiveScene(room(2,{role:'member',capabilities:{canBuild:false,canEditScene:false,canEditObjects:false}})));await p.getByRole('button',{name:'Load server version',exact:true}).click();s=await read(p);assert.equal(s.room.revision,4);assert.equal(JSON.parse(s.scene).objects[0].id,'server-4');assert.equal(s.room.role,'member');assert.equal(s.dirty,false);assert.equal(await p.locator('button[data-tool=chair]').isDisabled(),true);
 });
 await check('A conflict receipt newer than observed events remains an explicit whole-scene recovery',async p=>{await p.evaluate(()=>{start();editor.receiveScene(room(3));});await p.evaluate(()=>fail({status:409,code:'REVISION_CONFLICT',room:room(5)}));assert.equal((await read(p)).scene,await p.evaluate(()=>exactDraft));await p.evaluate(()=>editor.revert());assert.equal((await read(p)).room.revision,5);assert.equal(JSON.parse((await read(p)).scene).objects.length,1);});
 await check('Network failure without events keeps the base and can retry normally',async p=>{await p.evaluate(()=>start());await p.evaluate(()=>fail());assert.equal((await read(p)).dirty,true);await p.evaluate(()=>{window.settled=editor.save();});await p.evaluate(()=>accept());assert.equal((await read(p)).dirty,false);assert.equal((await read(p)).room.revision,2);});
 await check('Receipt cannot revive an archived image or replace a higher asset metadata revision',async p=>{
  await p.evaluate(()=>{state.room.imageDefinitions={'image:v1':entry()};editor.attachRoom();editor.setImageAsset({assetId:'image',versionId:'v1'});editor.pick({point:{x:4,z:3}});window.exactDraft=JSON.stringify(state.scene);window.settled=editor.save();window.accepted=receipt();editor.receiveScene({...room(2),imageDefinitions:{'image:v1':entry(3,'archived')}});editor.receiveScene({...room(2),imageDefinitions:{'image:v1':entry(2)}});});await p.evaluate(()=>accept(accepted));
  assert.equal(await p.evaluate(()=>definition().revision),3);assert.equal(await p.evaluate(()=>definition().status),'archived');assert.equal(await p.evaluate(()=>resolveImage().status),'archived');assert.equal(await p.evaluate(()=>state.room.imageDefinitions['image:v1'].revision),3);assert.equal(await p.evaluate(()=>state.scene.imageDefinitions),undefined);assert.equal(await p.evaluate(()=>editor.setImageAsset({assetId:'image',versionId:'v1'})),false);
 });
 await check('Personal-area removal at the same scene revision survives the receipt and disables scoped authoring',async p=>{
  await p.evaluate(()=>{state.room.role='member';state.room.capabilities={canBuild:true,canEditScene:false,canEditObjects:true};state.room.personalAreas=[{areaId:'desk',ownerId:'actor',canEditObjects:true,x:4,z:3,width:6,depth:6,revision:1}];editor.attachRoom();start();window.accepted=receipt();editor.receiveScene({...room(2),personalAreas:[],capabilities:{canBuild:false,canEditScene:false,canEditObjects:false}});});await p.evaluate(()=>accept(accepted));const s=await read(p);assert.equal(s.dirty,false);assert.deepEqual(s.room.personalAreas,[]);assert.equal(s.room.capabilities.canBuild,false);assert.equal(await p.locator('button[data-tool=chair]').isDisabled(),true);assert.deepEqual(await p.evaluate(()=>logs.requests[0].args.body.personalAreaRevisions),{desk:1});
 });
 await check('Authority updated by the shell without a scene event survives the receipt',async p=>{await p.evaluate(()=>{start();window.accepted=receipt();state.room.role='member';state.room.capabilities={canBuild:false,canEditScene:false};});await p.evaluate(()=>accept(accepted));assert.equal((await read(p)).room.role,'member');assert.equal(await p.locator('button[data-tool=chair]').isDisabled(),true);});
 await check('A live authority round trip back to its initial value remains the latest observation',async p=>{
  await p.evaluate(()=>{start();window.accepted=receipt();const initial=structuredClone(state.room);editor.receiveScene({...room(2),role:'member',capabilities:{canBuild:false,canEditScene:false,canEditObjects:false}});state.room.role=initial.role;state.room.capabilities=initial.capabilities;});await p.evaluate(()=>accept(accepted));const s=await read(p);assert.equal(s.room.role,'editor');assert.equal(s.room.capabilities.canEditScene,true);assert.equal(await p.locator('button[data-tool=chair]').isDisabled(),false);
 });
 for(const revision of [undefined,0,1,'2',1.5,Number.MAX_SAFE_INTEGER+1])await check('Invalid receipt revision '+String(revision)+' keeps the exact draft dirty',async p=>{
  await p.evaluate(()=>start());await p.evaluate(revision=>accept({...receipt(),revision}),revision);const s=await read(p);assert.equal(s.scene,await p.evaluate(()=>exactDraft));assert.equal(s.room.revision,1);assert.equal(s.dirty,true);assert.equal(s.saving,false);assert.equal(s.scenes.length,1);assert.deepEqual(s.toasts,['The save response has an invalid revision. Your draft is unchanged.']);assert.equal(await p.locator('.editor-status').textContent(),'Save failed · your draft is safe');
 });
 for(const outcome of ['success','failure'])for(const change of ['null-room','different-room','different-actor'])await check(outcome+' receipt is inert after '+change+' without attachRoom',async p=>{
  await p.evaluate(change=>{start();window.accepted=receipt();editor.receiveScene(room(4));if(change==='null-room')state.room=null;else if(change==='different-room')state.room={...room(1),id:'elsewhere'};else state.user={id:'other'};window.retiredScene=JSON.stringify(state.scene);window.retiredRoom=JSON.stringify(state.room);},change);
  assert.equal(await p.evaluate(()=>editor.isSaving()),false);await p.evaluate(()=>editor.receiveScene({...accepted,revision:9}));await p.evaluate(outcome=>outcome==='success'?accept(accepted):fail({status:409,room:{...accepted,revision:9}}),outcome);assert.equal(await p.evaluate(()=>JSON.stringify(state.room)),await p.evaluate(()=>retiredRoom));assert.equal((await read(p)).scene,await p.evaluate(()=>retiredScene));assert.equal((await read(p)).scenes.length,1);assert.deepEqual((await read(p)).toasts,[]);
 });
 await check('Leaving and reattaching the same room fences an older receipt while a new save is pending',async p=>{
  await p.evaluate(()=>{start();window.oldSettled=settled;window.oldReceipt=receipt();editor.receiveScene(room(8));state.room={...room(1),id:'elsewhere'};state.scene=cloneForTest(state.room.scene);function cloneForTest(v){return structuredClone(v)}editor.attachRoom();state.room={...room(1),id:'r'};state.scene=structuredClone(state.room.scene);editor.attachRoom();start();window.newSettled=settled;window.newReceipt=receipt();pending.shift().resolve({room:oldReceipt});});await p.evaluate(()=>oldSettled);assert.equal((await read(p)).saving,true);await p.evaluate(async()=>{pending.shift().resolve({room:newReceipt});await newSettled;});assert.equal((await read(p)).room.revision,2);assert.equal((await read(p)).dirty,false);
 });
 await check('Same-room actor replacement via attachRoom retires prior save and its observations',async p=>{await p.evaluate(()=>{start();window.accepted=receipt();editor.receiveScene(room(8));state.user={id:'new-actor'};state.room=room(6);state.scene=structuredClone(state.room.scene);editor.attachRoom();});await p.evaluate(()=>accept(accepted));assert.equal((await read(p)).room.revision,6);assert.equal(JSON.parse((await read(p)).scene).objects[0].id,'server-6');assert.equal((await read(p)).dirty,false);});
 for(const attach of [false,true])await check('A new admission in the same room fences an old receipt '+(attach?'with reattachment':'without observing the null interval'),async p=>{
  await p.evaluate(()=>{Object.assign(state,{admissionId:'first',admissionEpoch:'process',admissionRevision:1});editor.attachRoom();start();window.accepted=receipt();editor.receiveScene(room(8));});
  await p.evaluate(attach=>{state.room=null;state.admissionId=null;state.room={...accepted,revision:6,scene:{...accepted.scene,theme:'studio'}};state.scene=structuredClone(state.room.scene);Object.assign(state,{admissionId:'second',admissionEpoch:'process',admissionRevision:2});if(attach)editor.attachRoom();window.retained=JSON.stringify(state.scene);},attach);
  await p.evaluate(()=>accept(accepted));assert.equal((await read(p)).room.revision,6);assert.equal((await read(p)).scene,await p.evaluate(()=>retained));assert.equal((await read(p)).saving,false);assert.deepEqual((await read(p)).toasts,[]);
 });
 await check('Same-admission reconnect preserves the pending save and ordinary receipt',async p=>{await p.evaluate(()=>{Object.assign(state,{admissionId:'same',admissionEpoch:'process',admissionRevision:7});editor.attachRoom();start();window.accepted=receipt();state.ready=false;state.room={...state.room};state.ready=true;editor.attachRoom();});assert.equal((await read(p)).saving,true);await p.evaluate(()=>accept(accepted));assert.equal((await read(p)).room.revision,2);assert.equal((await read(p)).dirty,false);});
 await check('Destroy retires pending receipt with no scene or authority side effects',async p=>{await p.evaluate(()=>{start();window.accepted=receipt();editor.receiveScene(room(8));editor.destroy();});await p.evaluate(()=>accept(accepted));assert.equal((await read(p)).room.revision,1);assert.equal((await read(p)).scenes.length,1);assert.equal((await read(p)).saving,false);});
 assert.deepEqual(errors,[]);
}finally{await browser.close();await writeFile(out+'/results.json',JSON.stringify({checks,errors,limits:['Isolated real editor DOM with controlled promises and event snapshots; no server or renderer in this suite','Actual SQLite HTTP/native SSE and actual-shell coverage are separate suites','Whole-scene CAS and explicit draft export/recovery; no operation or collaborative merge']},null,2));}
