/** Native two-editor flow, local SQLite/HTTP/SSE, bundled game, software WebGL.
 * Serialize with flock ../.universe-gpu-test.lock node tests/editor-collaboration.full.mjs */
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createGameServer} from '../server/app.mjs';
import {emptyScene} from '../src/worlds.js';
import {launch} from '../scripts/browser.mjs';
const out='evidence/editor-collaboration-full';await mkdir(out,{recursive:true});
const initial={...emptyScene(),objects:[{id:'a',type:'chair',name:'Chair A',x:4,z:3,rotation:0},{id:'b',type:'chair',name:'Chair B',x:-4,z:-3,rotation:0}]};
const app=createGameServer({database:':memory:',seeds:[{id:'world',name:'Shared world',rooms:[{id:'r',name:'Shared room',scene:initial}]}],dist:new URL('../dist',import.meta.url).pathname,questsEnabled:false});
const {port}=await app.listen(0),base='http://127.0.0.1:'+port,browser=await launch(),contexts=[],checks=[],errors=[],requests=[];let alice,bob,phase='startup';
const state=p=>p.evaluate(()=>__universe.getState()),edit=p=>p.evaluate(()=>__universe.getEditor());
async function call(context,path,method='GET',data){const r=await context.request.fetch(base+path,{method,...(data===undefined?{}:{data})});const body=await r.json();assert(r.ok(),JSON.stringify(body));return body;}
async function enter(context){const p=await context.newPage();p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().endsWith('/scene/operations')&&r.method()==='POST')requests.push({actor:p===alice?'alice':'bob',body:r.postDataJSON()});});await p.goto(base+'/?room=r',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe?.getState().ready,undefined,{timeout:90000});await p.locator('#dock-build').click();return p;}
async function select(p,id){await p.bringToFront();await p.locator('#game').focus();await p.keyboard.press('v');for(let i=0;i<20&&(await edit(p)).selected!==id;i++)await p.keyboard.press(']');assert.equal((await edit(p)).selected,id);}
async function rename(p,id,name){await select(p,id);await p.getByRole('textbox',{name:'Name',exact:true}).fill(name);await p.getByRole('textbox',{name:'Name',exact:true}).press('Tab');assert.equal((await edit(p)).dirty,true);}
async function save(p){await p.bringToFront();await p.getByRole('button',{name:'Save room',exact:true}).click();await p.waitForFunction(()=>!__universe.getEditor().saving&&!__universe.getEditor().dirty);}
async function point(p,x,z){await p.bringToFront();await p.waitForFunction(()=>{const c=__universe.getCamera().framing;return c.status==='manual'||!c.targetOffset||Math.hypot(c.offset.x-c.targetOffset.x,c.offset.y-c.targetOffset.y)<1;});const q=await p.evaluate(({x,z})=>__universe.getScreenPoint(x,z,0),{x,z});assert(q.visible,'Point visible '+JSON.stringify({x,z,q}));assert.equal(await p.evaluate(q=>document.elementFromPoint(q.x,q.y)?.id,q),'game','Native canvas point unobscured');return q;}
async function add(p,x,z){await p.bringToFront();if(!await p.locator('.builder-tray').isVisible())await p.getByRole('button',{name:'＋ Furniture',exact:true}).click();await p.getByRole('button',{name:'Place Chair',exact:true}).click();const q=await point(p,x,z);await p.mouse.click(q.x,q.y);assert.equal((await edit(p)).dirty,true);return (await state(p)).scene.objects.at(-1).id;}
async function paint(p,x,z,material){await p.bringToFront();await p.getByRole('button',{name:'Terrain',exact:true}).click();await p.getByRole('button',{name:'Paint '+material,exact:true}).click();await p.getByRole('button',{name:'Close terrain palette',exact:true}).click();const q=await point(p,x+.2,z+.2);await p.mouse.click(q.x,q.y);assert.equal((await edit(p)).dirty,true);}
async function check(name,fn){phase=name;const started=performance.now();try{await fn();checks.push({name,status:'passed',durationMs:Math.round(performance.now()-started)});console.log('PASS',name,Math.round(performance.now()-started)+'ms');}catch(error){checks.push({name,status:'failed',durationMs:Math.round(performance.now()-started),error:error.stack});throw error;}}
try{
 const a=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),b=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});contexts.push(a,b);
 await call(a,'/api/session','POST',{name:'Alice builder'});await call(a,'/api/rooms/r/scene','PUT',{revision:0,scene:initial});const {user}=await call(b,'/api/session','POST',{name:'Bob builder'});await call(a,'/api/worlds/world/members/'+user.id,'PUT',{role:'editor'});
 alice=await enter(a);bob=await enter(b);assert.equal((await state(alice)).room.sceneOperations.version,1);
 await check('two native editors save independent object edits in both orders',async()=>{
  await rename(alice,'a','Alice A');await rename(bob,'b','Bob B');await save(alice);await bob.waitForFunction(()=>__universe.getState().scene.objects.find(o=>o.id==='a').name==='Alice A');assert.equal((await edit(bob)).dirty,true);await save(bob);await alice.waitForFunction(()=>__universe.getState().scene.objects.find(o=>o.id==='b').name==='Bob B');
  await rename(alice,'a','Alice A2');await rename(bob,'b','Bob B2');await save(bob);await alice.waitForFunction(()=>__universe.getState().scene.objects.find(o=>o.id==='b').name==='Bob B2');await save(alice);const room=(await call(a,'/api/rooms/r')).room;assert.deepEqual(room.scene.objects.map(o=>o.name),['Alice A2','Bob B2']);
 });
 await check('two native additions survive a peer commit and local undo/redo',async()=>{
  const mine=await add(alice,8,2),peer=await add(bob,-8,2);await save(alice);await bob.waitForFunction(id=>__universe.getState().scene.objects.some(o=>o.id===id),mine);await bob.getByRole('button',{name:'Undo',exact:true}).click();assert((await state(bob)).scene.objects.some(o=>o.id===mine));assert(!(await state(bob)).scene.objects.some(o=>o.id===peer));await bob.getByRole('button',{name:'Redo',exact:true}).click();await save(bob);await alice.waitForFunction(id=>__universe.getState().scene.objects.some(o=>o.id===id),peer);const room=(await call(a,'/api/rooms/r')).room;assert(room.scene.objects.some(o=>o.id===mine)&&room.scene.objects.some(o=>o.id===peer));
 });
 await check('two native terrain cells reconcile without replacing other authored ground',async()=>{
  await paint(alice,6,-5,'wood');await paint(bob,-6,-5,'stone');await save(bob);await alice.waitForFunction(()=>__universe.getState().scene.terrain?.cells.some(c=>c[0]===-6&&c[1]===-5));await save(alice);const cells=(await call(a,'/api/rooms/r')).room.scene.terrain.cells;assert(cells.some(c=>c[0]===6&&c[1]===-5&&c[2]==='wood'));assert(cells.some(c=>c[0]===-6&&c[1]===-5&&c[2]==='stone'));
 });
 await check('same item conflict supports native cancel, exact export and reviewed mine save',async()=>{
  await rename(alice,'a','Alice competing');await rename(bob,'a','Bob competing');const exact=(await state(bob)).scene;await save(alice);await bob.locator('.builder-recovery').getByRole('button',{name:'Review changes',exact:true}).waitFor();await bob.locator('.builder-recovery').getByRole('button',{name:'Review changes',exact:true}).click();assert.match(await bob.locator('.builder-conflict-review').innerText(),/Alice competing/);assert.match(await bob.locator('.builder-conflict-review').innerText(),/Bob competing/);await bob.goBack();await bob.locator('.builder-conflict-review').waitFor({state:'hidden'});assert.equal(await bob.locator('#editor').isVisible(),true);await bob.goForward();await bob.locator('.builder-conflict-review').waitFor({state:'visible'});await bob.keyboard.press('Escape');assert.equal(await bob.locator('#editor').isVisible(),true);assert.deepEqual((await state(bob)).scene,exact);
  const promised=bob.waitForEvent('download');await bob.locator('.builder-recovery').getByRole('button',{name:'Export my draft',exact:true}).click();const dl=await promised;await dl.saveAs(out+'/native-conflict-draft.json');assert.deepEqual(JSON.parse(await readFile(out+'/native-conflict-draft.json','utf8')).scene,exact);
  await bob.locator('.builder-recovery').getByRole('button',{name:'Review changes',exact:true}).click();await bob.getByLabel('Keep mine',{exact:true}).check();await bob.getByRole('button',{name:'Use reviewed choices',exact:true}).click();await bob.waitForFunction(()=>history.state?.surface==='build');await save(bob);await alice.waitForFunction(()=>__universe.getState().scene.objects.find(o=>o.id==='a').name==='Bob competing');assert.equal((await call(a,'/api/rooms/r')).room.scene.objects.find(o=>o.id==='a').name,'Bob competing');await bob.screenshot({path:out+'/reviewed-room.png'});
 });
 await check('lost successful response retries exact ID and retains a later edit plus peer commit',async()=>{
  let dropped=false,first;await alice.route(base+'/api/rooms/r/scene/operations',async route=>{if(!dropped){dropped=true;first=route.request().postDataJSON();const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');}else await route.continue();});
  await rename(alice,'a','Committed before loss');await alice.getByRole('button',{name:'Save room',exact:true}).click();await alice.getByRole('button',{name:'Retry save',exact:true}).waitFor();await alice.waitForFunction(()=>!__universe.getEditor().saving);await rename(alice,'a','Later local edit');await rename(bob,'b','Peer during retry');await save(bob);await alice.getByRole('button',{name:'Retry save',exact:true}).click();await alice.waitForFunction(()=>!__universe.getEditor().saving);assert.equal((await edit(alice)).dirty,true);const r=await state(alice);assert.equal(r.scene.objects.find(o=>o.id==='a').name,'Later local edit');assert.equal(r.scene.objects.find(o=>o.id==='b').name,'Peer during retry');const same=requests.filter(x=>x.body.operationId===first.operationId);assert.equal(same.length,2);assert.deepEqual(same[0].body,same[1].body);await save(alice);const room=(await call(a,'/api/rooms/r')).room;assert.equal(room.scene.objects.find(o=>o.id==='a').name,'Later local edit');assert.equal(room.scene.objects.find(o=>o.id==='b').name,'Peer during retry');await alice.unroute(base+'/api/rooms/r/scene/operations');
 });
 assert.deepEqual(errors,[]);
}catch(error){if(!checks.some(c=>c.name===phase&&c.status==='failed'))checks.push({name:phase,status:'failed',error:error.stack});console.error(error);await alice?.screenshot({path:out+'/failure-alice.png'}).catch(()=>{});await bob?.screenshot({path:out+'/failure-bob.png'}).catch(()=>{});process.exitCode=1;}
finally{await writeFile(out+'/results.json',JSON.stringify({checks,errors,requestIds:requests.map(x=>({actor:x.actor,operationId:x.body.operationId,baseRevision:x.body.baseRevision})),bundleSha256:createHash('sha256').update(await readFile('dist/main.js')).digest('hex'),limits:['Native DOM/pointer/keyboard edits in two actual bundled game clients with local SQLite/HTTP/native SSE','One response deliberately dropped after authentic server commit to verify idempotent retry','Software WebGL Chromium only; no hosted service or physical-device claim']},null,2));for(const c of contexts)await c.close();await browser.close();await app.close();}
