import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds,clone} from '../src/worlds.js';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const app=createGameServer({seeds:seedWorlds,dist:process.env.UNIVERSE_EDITOR_DIST||new URL('../dist',import.meta.url).pathname});
const address=await app.listen(0),base='http://127.0.0.1:'+address.port,browser=await launch();
const ctx=await browser.newContext({viewport:{width:1440,height:960}}),p=await ctx.newPage();p.setDefaultTimeout(20000);
const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const report=(name,details={})=>{checks.push({name,status:'passed',...details});console.log('PASS',name,JSON.stringify(details));};
const state=()=>p.evaluate(()=>window.__universe.getState());
const editor=()=>p.evaluate(()=>window.__universe.getEditor());
const point=(x,z,y=0)=>p.evaluate(({x,z,y})=>window.__universe.getScreenPoint(x,z,y),{x,z,y});
const clickWorld=async(x,z,y=0)=>{const q=await point(x,z,y);await p.mouse.click(q.x,q.y);};
const moveWorld=async(x,z,y=0)=>{const q=await point(x,z,y);await p.mouse.move(q.x,q.y);return q;};
async function choose(type){if(!await p.locator('.builder-tray').isVisible())await p.getByRole('button',{name:'＋ Furniture',exact:true}).click();await p.locator('[data-tool="'+type+'"]').click();}
try{
 await p.goto(base,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>!!window.__universe,{},{timeout:60000});await p.getByPlaceholder('Your name').fill('Builder proof');await p.getByRole('button',{name:'Enter Universe'}).click();await p.waitForFunction(()=>window.__universe?.getState().ready);await p.locator('#dock-build').click();await p.waitForTimeout(250);await p.screenshot({path:'evidence/builder-toolbelt-desktop.png'});
 const original=(await state()).scene.objects.length;
 await choose('chair');await moveWorld(4,3);assert.match(await p.locator('.builder-hint').innerText(),/Click to place/);await clickWorld(4,3);assert.equal((await state()).scene.objects.length,original+1);const chair=(await state()).scene.objects.at(-1);assert.equal(chair.x,4);assert.equal(chair.z,3);report('Direct single click places exactly one snapped chair',{id:chair.id,x:chair.x,z:chair.z});
 await moveWorld(4,3);assert.match(await p.locator('.builder-hint').innerText(),/Overlaps/);await clickWorld(4,3);assert.equal((await state()).scene.objects.length,original+1);report('Overlap is previewed and rejected before mutation');
 await p.getByRole('button',{name:'↖ Select',exact:true}).click();const start=await point(chair.x,chair.z,.48);await p.mouse.move(start.x,start.y);await p.mouse.down();const beforeDrag=clone((await state()).scene);const end=await point(7,4);await p.mouse.move(end.x,end.y,{steps:8});assert.deepEqual((await state()).scene,beforeDrag);assert.match(await p.locator('.builder-hint').innerText(),/Release to move/);await p.screenshot({path:'evidence/builder-live-drag-desktop.png'});await p.mouse.up();const moved=(await state()).scene.objects.find(i=>i.id===chair.id);assert.notDeepEqual({x:moved.x,z:moved.z},{x:chair.x,z:chair.z});assert(Number.isInteger(moved.x)&&Number.isInteger(moved.z));report('Drag previews without scene mutation and commits once on release',{from:[chair.x,chair.z],to:[moved.x,moved.z]});
 await p.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual((await state()).scene,beforeDrag);await p.getByRole('button',{name:'Redo',exact:true}).click();assert.deepEqual((await state()).scene.objects.find(i=>i.id===chair.id),moved);report('One Undo reverses the complete drag and one Redo restores it');
 const current=await point(moved.x,moved.z,.48);await p.mouse.move(current.x,current.y);await p.mouse.down();await moveWorld(8,6);await p.keyboard.press('Escape');await p.mouse.up();assert.deepEqual((await state()).scene.objects.find(i=>i.id===chair.id),moved);assert(await p.locator('#editor').isVisible());report('Escape rolls back active drag without closing Build');
 await choose('table');const orbitCount=(await state()).scene.objects.length;const orbitStart=await point(0,1);await p.mouse.move(orbitStart.x,orbitStart.y);await p.mouse.down({button:'right'});await p.mouse.move(orbitStart.x+100,orbitStart.y+25,{steps:10});await p.mouse.up({button:'right'});assert.equal((await state()).scene.objects.length,orbitCount);report('Orbit gesture while holding a placement tool never drops an item');
 await p.locator('#game').focus();await p.keyboard.press('Home');await p.waitForTimeout(100);await choose('chair');await p.keyboard.press('ArrowRight');await p.keyboard.press('r');const beforeSpace=(await state()).scene.objects.length;await p.keyboard.press('Space');assert.equal((await state()).scene.objects.length,beforeSpace+1);assert.equal((await state()).scene.objects.at(-1).rotation,90);report('Keyboard arrow preview + R + Space places a rotated item without mouse');
 await p.keyboard.press('v');await p.keyboard.press(']');const keySelection=(await editor()).selected;assert(keySelection);await p.keyboard.press('d');assert.equal((await editor()).tool,'duplicate');await p.keyboard.press('ArrowRight');await p.keyboard.press('ArrowRight');const copies=(await state()).scene.objects.length;await p.keyboard.press('Space');assert.equal((await state()).scene.objects.length,copies+1);report('Keyboard selection cycle + duplicate preview + Space creates a copy');
 await p.keyboard.press('Control+z');assert.equal((await state()).scene.objects.length,copies);await p.keyboard.press('Control+Shift+z');assert.equal((await state()).scene.objects.length,copies+1);report('Ctrl+Z and Ctrl+Shift+Z preserve editor history');
 await p.keyboard.press('Control+s');await p.waitForFunction(()=>!window.__universe.getEditor().dirty);const saved=clone((await state()).scene);report('Keyboard Save commits the exact scene through authenticated server API');
 await p.reload();await p.waitForFunction(()=>window.__universe?.getState().ready);assert.deepEqual((await state()).scene,saved);report('Reload recovers the server-saved scene');
 await p.locator('#dock-build').click();await p.keyboard.press(']');const name=p.getByRole('textbox',{name:'Name',exact:true});await name.fill('rdvx typing is safe');await name.press('Tab');const typed=(await state()).scene;assert.equal(typed.objects[0].name,'rdvx typing is safe');report('Typing editor shortcuts into item Name does not rotate/delete/place');
 // A committed server settings change proactively opens recovery for the local draft.
 const draft=clone((await state()).scene);assert.equal((await editor()).dirty,true);const room=await p.request.get(base+'/api/rooms/commons');const remote=(await room.json()).room;remote.scene.theme='studio';const newer=await p.request.put(base+'/api/rooms/commons/scene',{data:{revision:remote.revision,scene:remote.scene}});assert.equal(newer.status(),200);const committed=(await newer.json()).room;assert.equal(committed.scene.theme,'studio');assert(committed.revision>remote.revision);
 await p.locator('.builder-recovery').getByRole('button',{name:'Review changes',exact:true}).waitFor({state:'visible'});assert.deepEqual((await state()).scene,draft);assert.equal((await editor()).dirty,true);
 await p.getByRole('toolbar',{name:'Build tools',exact:true}).getByRole('button',{name:'Review changes',exact:true}).click();const review=p.getByRole('dialog',{name:'Review conflicting room changes',exact:true});await review.waitFor({state:'visible'});await review.getByRole('group',{name:'Room settings and areas',exact:true}).waitFor({state:'visible'});assert.deepEqual((await state()).scene,draft);assert.equal((await editor()).dirty,true);assert.equal(await p.locator('.builder-recovery').evaluate(el=>el.inert),true,'Recovery stays inert behind the review modal');
 await review.getByRole('button',{name:'Cancel',exact:true}).click();await review.waitFor({state:'hidden'});assert.deepEqual((await state()).scene,draft);assert.equal((await editor()).dirty,true);assert.equal(await p.locator('.builder-recovery').evaluate(el=>el.inert),false);assert(await p.getByRole('button',{name:'Load server version',exact:true}).isVisible());report('Committed settings event preserves the exact draft through native review and cancel');
 await p.getByRole('button',{name:'Load server version',exact:true}).click();assert.equal((await state()).scene.theme,'studio');assert.deepEqual((await state()).scene,committed.scene);assert.equal((await state()).room.revision,committed.revision);assert.equal((await editor()).dirty,false);report('Conflict recovery loads the verified server scene');
 await p.getByRole('button',{name:'▱ Area',exact:true}).click();await clickWorld(-3,5);const areaId=(await editor()).selected;assert(areaId);await p.getByRole('textbox',{name:'Name',exact:true}).fill('Builder proof area');await p.getByRole('textbox',{name:'Name',exact:true}).press('Tab');await p.locator('.builder-details summary').filter({hasText:'More actions'}).click();await p.getByRole('button',{name:'+ Message',exact:true}).click();await p.getByRole('textbox',{name:'Message text',exact:true}).fill('Area behavior remains real');await p.getByRole('textbox',{name:'Message text',exact:true}).press('Tab');assert.equal((await state()).scene.areas.find(a=>a.id===areaId).actions[0].message,'Area behavior remains real');report('Direct area placement retains editable multiple-action behavior');
 await p.locator('#game').focus();await p.keyboard.press('v');await p.keyboard.press(']');const documentItem=(await editor()).selected;await p.locator('.builder-details summary').filter({hasText:'Attach a room document'}).click();await p.locator('.builder-details input[type=file]').setInputFiles({name:'builder-proof.txt',mimeType:'text/plain',buffer:Buffer.from('A real authenticated room attachment')});await p.waitForFunction(id=>window.__universe.getState().scene.objects.find(o=>o.id===id)?.document?.name==='builder-proof.txt',documentItem);const attachment=(await state()).scene.objects.find(o=>o.id===documentItem);const downloaded=await p.request.get(base+attachment.url);assert.equal(downloaded.status(),200);assert.equal(await downloaded.text(),'A real authenticated room attachment');await p.locator('#game').focus();await p.keyboard.press('Control+s');await p.waitForFunction(()=>!window.__universe.getEditor().dirty);await p.reload();await p.waitForFunction(()=>window.__universe?.getState().ready);assert.equal((await state()).scene.objects.find(o=>o.id===documentItem).document.name,'builder-proof.txt');assert.equal((await state()).scene.areas.find(a=>a.id===areaId).actions[0].message,'Area behavior remains real');report('Authenticated document upload/download, attachment and area actions survive save/reload');await p.locator('#dock-build').click();
 await p.screenshot({path:'evidence/builder-finished-desktop.png'});
 const storageState=await ctx.storageState();await p.close();const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,storageState});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto(base,{waitUntil:'domcontentloaded',timeout:60000});await m.waitForFunction(()=>window.__universe?.getState().ready,{},{timeout:60000});await m.locator('#dock-build').tap();await m.screenshot({path:'evidence/builder-toolbelt-mobile.png'});assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth),390);await m.locator('[data-tool="plant"]').tap();const mp=await m.evaluate(()=>window.__universe.getScreenPoint(-4,4));const beforeTouch=await m.evaluate(()=>window.__universe.getState().scene.objects.length);const cdp=await mobile.newCDPSession(m);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:mp.x,y:mp.y,id:1},{x:mp.x+45,y:mp.y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:mp.x+25,y:mp.y-10,id:1},{x:mp.x+90,y:mp.y+10,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await m.evaluate(()=>window.__universe.getState().scene.objects.length),beforeTouch);report('390px touch toolbelt fits and two-finger camera gesture creates no item');await mobile.close();
 assert.deepEqual(errors,[]);report('No runtime exceptions in direct desktop/touch authoring');
}catch(e){checks.push({name:'failure',status:'failed',error:e.stack});console.error(e);await p.screenshot({path:'evidence/builder-direct-failure.png'}).catch(()=>{});process.exitCode=1;}
finally{await writeFile('evidence/builder-direct-checks.json',JSON.stringify({checks,errors,limits:['Headless Chromium / SwiftShader, not a physical phone','No production/provider parity claim']},null,2));await ctx.close();await browser.close();await app.close();}
