/** Controlled real editor DOM; no renderer, transport, or server claims. */
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright-core';
import embedded from '@sparticuz/chromium';
const source=`import {mountEditor} from './src/editor.js';
import {emptyScene} from './src/worlds.js';
import {applySceneOperations} from './src/scene-operations.js';
import {sceneRequestHash} from './src/editor-collaboration.js';
import {personalEditPolicy} from './src/personal-editor-policy.js';
import {imageDefinitions,resolvedImage} from './src/image-asset-context.js';
import {normalizeImageAssetDraft,validateImageDefinition} from './src/image-asset-schema.js';
window.install=(initial=emptyScene())=>{
 window.state={scene:structuredClone(initial),room:{id:'r',name:'Shared room',role:'editor',revision:1,sceneOperations:{version:1},capabilities:{canEditScene:true,canBuild:true,canEditObjects:true},personalAreas:[],imageDefinitions:{},scene:structuredClone(initial)},user:{id:'actor'},position:{x:0,z:7},admissionId:'joined',admissionEpoch:'process',admissionRevision:1};
 window.logs={scenes:[],toasts:[],requests:[]};window.pending=[];
 window.editor=mountEditor({root:document.querySelector('#editor'),getState:()=>state,onScene:s=>{state.scene=s;logs.scenes.push(JSON.stringify(s));},onSelect:()=>{},toast:t=>logs.toasts.push(t),editPolicy:personalEditPolicy,api:(url,args)=>{logs.requests.push({url,args:structuredClone(args)});return new Promise((resolve,reject)=>pending.push({resolve,reject}));}});editor.attachRoom();editor.setBuild(true);
};
window.entry=(revision=1,status='active')=>{const stamp='2026-10-02T00:00:00.000Z',definition={schemaVersion:1,assetId:'image',roomId:'r',createdBy:'actor',createdAt:stamp,originKind:'upload'},version={...normalizeImageAssetDraft({name:'Image revision '+revision,floating:true},{width:64,height:64,byteLength:100,mediaType:'image/png'}),schemaVersion:1,assetId:'image',roomId:'r',versionId:'v1',sequence:1,sha256:'a'.repeat(64),createdBy:'actor',createdAt:stamp};return {...validateImageDefinition(definition,version),status,revision};};
window.imageMetadata=()=>({entry:imageDefinitions(state.scene)['image:v1'],resolved:resolvedImage(state.scene,state.scene.objects.find(o=>o.type==='image'))});
window.item=(id,x=-4,z=-3)=>({id,type:'chair',name:id,x,z,rotation:0});
window.peer=(objects,revision=2,patch={})=>({...structuredClone(state.room),revision,scene:{...structuredClone(state.room.scene),objects},...patch});
window.add=(x=4,z=3)=>{editor.setTool('chair');editor.pick({point:{x,z}});return state.scene.objects.at(-1).id;};
window.start=()=>{window.settled=editor.save();};
window.succeed=async({room,receipt={}}={})=>{const request=logs.requests.at(-1),body=request.args.body;const committed=room||{...structuredClone(state.room),revision:body.baseRevision+1,scene:applySceneOperations(state.room.scene,body.operations)};const result={room:committed,receipt:{version:1,operationId:body.operationId,actorId:'actor',roomId:'r',appliedRevision:body.baseRevision+1,requestHash:await sceneRequestHash('r',body),...receipt}};pending.shift().resolve(result);await settled;};
window.fail=async(status=500,room,code='SCENE_OPERATION_CONFLICT')=>{pending.shift().reject(Object.assign(Error('Controlled failure'),{status,data:{room,code}}));await settled;};
window.rename=(id,name)=>{editor.select(id);const input=[...document.querySelectorAll('.inspector input')].find(x=>x.dataset.focusKey==='Name');input.value=name;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));};
install();`;
const bundle=await build({stdin:{contents:source,resolveDir:process.cwd(),sourcefile:'collaborative-client-fixture.js'},bundle:true,format:'iife',write:false});
const browser=await chromium.launch({executablePath:await embedded.executablePath(),headless:true,args:['--no-sandbox','--no-zygote','--disable-gpu']}),checks=[],errors=[],out='evidence/editor-collaboration';await mkdir(out,{recursive:true});
async function check(name,fn){const context=await browser.newContext({acceptDownloads:true,viewport:{width:1100,height:900}});try{const p=await context.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));await p.route('https://collaboration.test/',r=>r.fulfill({contentType:'text/html',body:'<canvas id="game" tabindex="0"></canvas><aside id="editor"></aside>'}));await p.goto('https://collaboration.test/');await p.addScriptTag({content:bundle.outputFiles[0].text});await fn(p);checks.push({name,status:'passed'});console.log('PASS',name);}catch(error){checks.push({name,status:'failed',error:error.stack});console.error('FAIL',name,error);process.exitCode=1;}finally{await context.close();}}
const start=async p=>{await p.evaluate(()=>start());await p.waitForFunction(()=>pending.length===1);};
const read=p=>p.evaluate(()=>({scene:state.scene,room:state.room,dirty:editor.isDirty(),saving:editor.isSaving(),history:editor.getInteractionState().undo,toasts:logs.toasts,requests:logs.requests}));
try{
 await check('disjoint committed snapshot rebases draft and undo keeps peer addition',async p=>{
  await p.evaluate(()=>{add();editor.receiveScene(peer([item('peer')]));});let r=await read(p);assert.equal(r.scene.objects.length,2);assert.equal(r.room.revision,2);assert.equal(r.dirty,true);assert.equal(r.history,1);await p.evaluate(()=>editor.undo());r=await read(p);assert.deepEqual(r.scene.objects.map(o=>o.id),['peer']);assert.equal(r.dirty,false);await p.evaluate(()=>editor.redo());assert.equal((await read(p)).scene.objects.length,2);
 });
 await check('operation save sends only target changes and verifies its receipt',async p=>{
  await p.evaluate(()=>add());await start(p);const request=(await read(p)).requests[0];assert.equal(request.url,'/api/rooms/r/scene/operations');assert.equal(request.args.method,'POST');assert.equal(request.args.deferRoomPreparation,true);assert.equal(request.args.body.operations.length,1);assert.equal(request.args.body.scene,undefined);assert.equal(request.args.body.admission.admissionId,'joined');await p.evaluate(()=>succeed());assert.equal((await read(p)).dirty,false);assert.equal((await read(p)).room.revision,2);
 });
 await check('delayed acknowledgement adopts newer geometry and live authority separately',async p=>{
  await p.evaluate(()=>add());await start(p);await p.evaluate(()=>{const accepted=structuredClone(state.scene);window.receiptRoom={...peer(accepted.objects),revision:2};editor.receiveScene({...peer([...accepted.objects,item('peer')],4),role:'member',capabilities:{canEditScene:false,canBuild:false}});editor.receiveScene({...peer([],3),role:'member',capabilities:{canEditScene:false,canBuild:false}});});await p.evaluate(()=>succeed({room:receiptRoom}));const r=await read(p);assert.equal(r.room.revision,4);assert.equal(r.scene.objects.length,2);assert.equal(r.room.capabilities.canEditScene,false);assert.equal(r.dirty,false);
 });
 await check('unknown outcome keeps exact original request during further draft edits',async p=>{
  await p.evaluate(()=>add());await start(p);const original=(await read(p)).requests[0];await p.evaluate(()=>fail());await p.evaluate(()=>{add(7,3);const accepted=structuredClone(state.room.scene);accepted.objects.push(structuredClone(logs.requests[0].args.body.operations[0].after),item('peer'));editor.receiveScene({...peer(accepted.objects,3)});});await start(p);assert.deepEqual((await read(p)).requests[1],original);await p.evaluate(()=>succeed());const r=await read(p);assert.equal(r.scene.objects.length,3);assert.equal(r.room.scene.objects.length,2);assert.equal(r.room.revision,3);assert.equal(r.dirty,true);await start(p);assert.notEqual((await read(p)).requests[2].args.body.operationId,original.args.body.operationId);await p.evaluate(()=>succeed());assert.equal((await read(p)).dirty,false);
 });
 await check('malformed receipt hash retains same-ID retry and exact draft',async p=>{
  await p.evaluate(()=>add());await start(p);const before=await read(p);await p.evaluate(()=>succeed({receipt:{requestHash:'0'.repeat(64)}}));assert.equal((await read(p)).dirty,true);assert.deepEqual((await read(p)).scene,before.scene);await start(p);assert.deepEqual((await read(p)).requests[1],before.requests[0]);await p.evaluate(()=>succeed());assert.equal((await read(p)).dirty,false);
 });
 await check('same-object conflict shows Base Mine Server; cancel and export preserve exact draft',async p=>{
  await p.evaluate(()=>{editor.receiveScene(peer([item('a')]));rename('a','My chair');window.exact=JSON.stringify(state.scene);editor.receiveScene(peer([{...item('a'),name:'Their chair'}],3));});assert.equal(JSON.stringify((await read(p)).scene),await p.evaluate(()=>exact));await p.getByRole('button',{name:'Review changes',exact:true}).first().click();assert.equal(await p.locator('.builder-conflict-values strong').allTextContents().then(x=>x.join(',')),'Base,Mine,Server');assert.match(await p.locator('.builder-conflict-review').innerText(),/My chair/);assert.match(await p.locator('.builder-conflict-review').innerText(),/Their chair/);await p.keyboard.press('Escape');assert.equal(await p.locator('.builder-conflict-review').isVisible(),false);const promised=p.waitForEvent('download');await p.locator('.builder-recovery').getByRole('button',{name:'Export my draft',exact:true}).click();const dl=await promised;const path=out+'/exact-draft.json';await dl.saveAs(path);assert.equal(JSON.stringify(JSON.parse(await readFile(path,'utf8')).scene),await p.evaluate(()=>exact));
 });
 await check('mine resolution sends a new batch against current server object and preserves peer work',async p=>{
  await p.evaluate(()=>{editor.receiveScene(peer([item('a')]));rename('a','Mine');});await start(p);const original=(await read(p)).requests[0].args.body;await p.evaluate(()=>fail(409,peer([{...item('a'),name:'Server'},item('peer',-7)],3)));await p.getByRole('button',{name:'Review changes',exact:true}).first().click();await p.getByLabel('Keep mine',{exact:true}).check();await p.getByRole('button',{name:'Use reviewed choices',exact:true}).click();assert.equal((await read(p)).scene.objects.length,2);await start(p);const next=(await read(p)).requests[1].args.body;assert.notEqual(next.operationId,original.operationId);assert.equal(next.baseRevision,3);assert.notEqual(next.operations[0].before,original.operations[0].before);assert.equal(next.operations.length,1);await p.evaluate(()=>succeed());assert.deepEqual((await read(p)).scene.objects.map(o=>o.name),['Mine','peer']);
 });
 await check('using server version keeps independent local addition',async p=>{
  await p.evaluate(()=>{window.resolutionEvents=[];addEventListener('editor-review',e=>resolutionEvents.push(e.detail));editor.receiveScene(peer([item('a')]));rename('a','Mine');add();editor.receiveScene(peer([{...item('a'),name:'Server'}],3));});await p.getByRole('button',{name:'Review changes',exact:true}).first().click();await p.getByLabel('Use server',{exact:true}).check();await p.getByRole('button',{name:'Use reviewed choices',exact:true}).click();const r=await read(p);assert.equal(r.scene.objects.length,2);assert.equal(r.scene.objects[0].name,'Server');assert.equal(r.dirty,true);assert.equal(r.history,0);assert.deepEqual(await p.evaluate(()=>resolutionEvents.at(-1)),{open:false,record:true});
 });
 await check('combined geometry preserves exact draft and mine cannot bypass collision check',async p=>{
  await p.evaluate(()=>{add();window.exact=JSON.stringify(state.scene);editor.receiveScene(peer([item('peer',4,3)]));});assert.equal(JSON.stringify((await read(p)).scene),await p.evaluate(()=>exact));await p.getByRole('button',{name:'Review changes',exact:true}).first().click();await p.getByLabel('Keep my changes (must fit safely)',{exact:true}).check();await p.getByRole('button',{name:'Use reviewed choices',exact:true}).click();assert.equal(await p.locator('.builder-conflict-review').isVisible(),true);assert.match((await read(p)).toasts.at(-1),/Overlaps/);assert.equal((await read(p)).requests.length,0);await p.getByLabel('Use server (discard my draft changes)',{exact:true}).check();await p.getByRole('button',{name:'Use reviewed choices',exact:true}).click();assert.deepEqual((await read(p)).scene.objects.map(o=>o.id),['peer']);assert.equal((await read(p)).dirty,false);
 });
 await check('reconnect snapshot uses same reconciliation and ignores older scene with newer denial',async p=>{
  await p.evaluate(()=>{add();editor.receiveScene(peer([item('reconnected')],6));editor.receiveScene({...peer([],3),role:'member',capabilities:{canEditScene:false,canBuild:false}});});const r=await read(p);assert.equal(r.room.revision,6);assert.equal(r.scene.objects.length,2);assert.equal(r.room.role,'member');assert.equal(await p.getByRole('button',{name:'Save room',exact:true}).isDisabled(),true);
 });
 for(const retire of ['actor','room','admission'])await check('old in-flight result is inert after '+retire+' replacement',async p=>{
  await p.evaluate(()=>add());await start(p);await p.evaluate(retire=>{if(retire==='actor')state.user.id='other';else if(retire==='room')state.room.id='other';else state.admissionId='other';window.exact=JSON.stringify(state.scene);},retire);await p.evaluate(()=>succeed({room:{...peer(state.scene.objects),id:'r'}}));assert.equal(JSON.stringify((await read(p)).scene),await p.evaluate(()=>exact));assert.equal((await read(p)).saving,false);assert.equal((await read(p)).dirty,true);
 });
 await check('authority removal while review is open disables committing its choices',async p=>{
  await p.evaluate(()=>{editor.receiveScene(peer([item('a')]));rename('a','Mine');editor.receiveScene(peer([{...item('a'),name:'Server'}],3));});await p.getByRole('button',{name:'Review changes',exact:true}).first().click();await p.evaluate(()=>editor.receiveScene({...peer(state.room.scene.objects,3),role:'member',capabilities:{canEditScene:false,canBuild:false}}));await p.getByLabel('Keep mine',{exact:true}).check();assert.equal(await p.getByRole('button',{name:'Use reviewed choices',exact:true}).isDisabled(),true);assert.equal((await read(p)).requests.length,0);
 });
 await check('operation receipt preserves newest archived image metadata through cloned rebases',async p=>{
  await p.evaluate(()=>{state.room.imageDefinitions={'image:v1':entry()};editor.attachRoom();editor.setImageAsset({assetId:'image',versionId:'v1'});editor.pick({point:{x:4,z:3}});window.acceptedRoom={...structuredClone(state.room),revision:2,scene:structuredClone(state.scene)};});await start(p);await p.evaluate(()=>{editor.receiveScene({...acceptedRoom,imageDefinitions:{'image:v1':entry(3,'archived')}});editor.receiveScene({...acceptedRoom,imageDefinitions:{'image:v1':entry(2)}});});await p.evaluate(()=>succeed({room:acceptedRoom}));const metadata=await p.evaluate(()=>imageMetadata());assert.equal(metadata.entry.revision,3);assert.equal(metadata.entry.status,'archived');assert.equal(metadata.resolved.status,'archived');assert.equal((await read(p)).scene.imageDefinitions,undefined);assert.equal(await p.evaluate(()=>editor.setImageAsset({assetId:'image',versionId:'v1'})),false);
 });
 await check('saved local undo is honestly invalidated after peer edits the same target',async p=>{
  await p.evaluate(()=>add());await start(p);await p.evaluate(()=>succeed());assert.equal((await read(p)).history,1);await p.evaluate(()=>editor.receiveScene(peer([{...state.scene.objects[0],name:'Peer name'}],3)));assert.equal((await read(p)).history,0);assert.match(await p.locator('.builder-recovery').innerText(),/undo history was cleared/);assert.equal((await read(p)).scene.objects[0].name,'Peer name');
 });
 await check('rename on grandfathered overlapping furniture rebases over unrelated peer work and saves',async p=>{
  await p.evaluate(()=>{editor.receiveScene(peer([item('a'),item('b')],2));rename('a','Renamed overlap');editor.receiveScene(peer([item('a'),item('b'),item('peer',-8,-3)],3));});const before=await read(p);assert.equal(before.scene.objects[0].name,'Renamed overlap');assert.equal(before.scene.objects.length,3);assert.equal(await p.locator('.builder-conflict-review').isVisible(),false);await start(p);assert.equal((await read(p)).requests[0].args.body.operations.length,1);await p.evaluate(()=>succeed());assert.equal((await read(p)).dirty,false);assert.equal((await read(p)).scene.objects[0].name,'Renamed overlap');assert.equal((await read(p)).scene.objects.length,3);
 });
 for(const committed of [false,true])await check('fresh same-room admission preserves '+(committed?'committed':'uncommitted')+' old batch and independent peer changes',async p=>{
  await p.evaluate(()=>add());await start(p);const original=(await read(p)).requests[0].args.body;await p.evaluate(committed=>{window.oldRoom={...structuredClone(state.room),revision:2,scene:structuredClone(state.scene)};const remote=peer(committed?[...state.scene.objects,item('peer')]:[item('peer')],3);Object.assign(state,{ready:true,admissionId:'rejoined',admissionEpoch:'restarted',admissionRevision:2});window.resumed=editor.resumeAdmission(remote);window.afterResume=JSON.stringify(state.scene);},committed);assert.equal(await p.evaluate(()=>resumed),true);assert.equal((await read(p)).scene.objects.length,2);assert.equal((await read(p)).dirty,!committed);await p.evaluate(()=>succeed({room:oldRoom}));assert.equal(JSON.stringify((await read(p)).scene),await p.evaluate(()=>afterResume));assert.equal((await read(p)).room.revision,3);assert.equal((await read(p)).requests.length,1);if(!committed){await start(p);const next=(await read(p)).requests[1].args.body;assert.notEqual(next.operationId,original.operationId);assert.equal(next.admission.admissionId,'rejoined');assert.equal(next.admission.admissionEpoch,'restarted');assert.equal(next.baseRevision,3);await p.evaluate(()=>succeed());assert.equal((await read(p)).dirty,false);}
 });
 await check('new admission retires an unknown retry without resubmission and retains later local work',async p=>{
  await p.evaluate(()=>add());await start(p);const original=(await read(p)).requests[0].args.body;await p.evaluate(()=>fail());await p.evaluate(()=>{add(7,3);const remote=peer([logs.requests[0].args.body.operations[0].after,item('peer')],3);Object.assign(state,{ready:true,admissionId:'rejoined',admissionEpoch:'restarted',admissionRevision:2});editor.resumeAdmission(remote);});assert.equal((await read(p)).scene.objects.length,3);assert.equal((await read(p)).dirty,true);assert.equal((await read(p)).requests.length,1);await start(p);const next=(await read(p)).requests[1].args.body;assert.notEqual(next.operationId,original.operationId);assert.equal(next.operations.length,1);assert.equal(next.admission.admissionId,'rejoined');await p.evaluate(()=>succeed());assert.equal((await read(p)).dirty,false);
 });
 await check('admission resume refuses a different actor or room and unavailable authority context',async p=>{
  await p.evaluate(()=>{state.ready=true;add();});for(const change of ['actor','room','not-ready']){const result=await p.evaluate(change=>{const old={user:structuredClone(state.user),room:structuredClone(state.room),ready:state.ready};const exact=JSON.stringify(state.scene);if(change==='actor')state.user.id='other';else if(change==='room')state.room.id='elsewhere';else state.ready=false;const accepted=editor.resumeAdmission(peer([item('peer')],3));const retained=exact===JSON.stringify(state.scene);Object.assign(state,old);return {accepted,retained};},change);assert.deepEqual(result,{accepted:false,retained:true});}
 });
 for(const committed of [false,true])await check('unknown result plus undo-to-base stays dirty and survives '+(committed?'committed':'uncommitted')+' fresh admission',async p=>{
  await p.evaluate(()=>{window.dirtyEvents=[];addEventListener('editor-status',e=>dirtyEvents.push(e.detail.dirty));add();});await start(p);const original=(await read(p)).requests[0].args.body;await p.evaluate(()=>fail());await p.evaluate(()=>editor.undo());assert.equal((await read(p)).scene.objects.length,0);assert.equal((await read(p)).dirty,true);assert.equal(await p.evaluate(()=>dirtyEvents.at(-1)),true);await p.evaluate(committed=>{const mine=logs.requests[0].args.body.operations[0].after,remote=peer(committed?[mine,item('peer')]:[item('peer')],3);Object.assign(state,{ready:true,admissionId:'rejoined',admissionEpoch:'restarted',admissionRevision:2});editor.resumeAdmission(remote);},committed);assert.deepEqual((await read(p)).scene.objects.map(o=>o.id),['peer']);assert.equal((await read(p)).dirty,committed);assert.equal((await read(p)).requests.length,1);if(committed){await start(p);const request=(await read(p)).requests[1].args.body;assert.notEqual(request.operationId,original.operationId);assert.equal(request.operations.length,1);assert.equal(request.operations[0].after,null);await p.evaluate(()=>succeed());assert.deepEqual((await read(p)).scene.objects.map(o=>o.id),['peer']);assert.equal((await read(p)).dirty,false);}
 });
 await check('ambiguous post-request undo keeps its review reference across later peer snapshots',async p=>{
  await p.evaluate(()=>add());await start(p);await p.evaluate(()=>fail());await p.evaluate(()=>{editor.undo();const mine=logs.requests[0].args.body.operations[0].after,remote=peer([{...mine,name:'Peer changed pending item'},item('peer')],3);Object.assign(state,{ready:true,admissionId:'rejoined',admissionEpoch:'restarted',admissionRevision:2});editor.resumeAdmission(remote);editor.receiveScene({...remote,revision:4,scene:{...remote.scene,objects:[...remote.scene.objects,item('later-peer',-8,-3)]}});});assert.equal((await read(p)).dirty,true);assert.equal((await read(p)).scene.objects.length,0);await p.getByRole('button',{name:'Review changes',exact:true}).first().click();assert.match(await p.locator('.builder-conflict-review').innerText(),/Peer changed pending item/);assert.equal((await read(p)).requests.length,1);
 });
 await check('context conflict is reviewed before a new target batch and keeps latest room settings',async p=>{
  await p.evaluate(()=>{add();const remote=peer([],2);remote.scene.bounds.width=30;editor.receiveScene(remote);});await p.getByRole('button',{name:'Review changes',exact:true}).first().click();assert.match(await p.locator('.builder-conflict-row').innerText(),/Room settings and areas/);await p.getByLabel('Keep my settings and recheck on this room',{exact:true}).check();await p.getByRole('button',{name:'Use reviewed choices',exact:true}).click();assert.equal((await read(p)).scene.bounds.width,30);assert.equal((await read(p)).scene.objects.length,1);await start(p);assert.equal((await read(p)).requests[0].args.body.baseRevision,2);await p.evaluate(()=>succeed());assert.equal((await read(p)).dirty,false);
 });
 await check('room settings retain explicit whole-scene CAS transport',async p=>{
  await p.getByRole('button',{name:'⚙ Room',exact:true}).click();await p.locator('[data-focus-key=Environment]').selectOption('studio');await start(p);const request=(await read(p)).requests[0];assert.equal(request.url,'/api/rooms/r/scene');assert.equal(request.args.method,'PUT');assert.equal(request.args.body.scene.theme,'studio');await p.evaluate(async()=>{pending.shift().resolve({room:{...peer([],2),scene:structuredClone(state.scene)}});await settled;});assert.equal((await read(p)).dirty,false);
 });
 await check('new admission retires unknown save identity before any retry can send',async p=>{
  await p.evaluate(()=>add());await start(p);await p.evaluate(()=>fail());await p.evaluate(()=>{state.admissionId='rejoined';return editor.save();});assert.equal((await read(p)).requests.length,1);assert.equal((await read(p)).dirty,true);
 });
 await check('review traps keyboard focus and emits visibility events without scene history',async p=>{
  await p.evaluate(()=>{window.reviewEvents=[];addEventListener('editor-review',e=>reviewEvents.push(e.detail));editor.receiveScene(peer([item('a')]));rename('a','Mine');editor.receiveScene(peer([{...item('a'),name:'Server'}],3));});await p.getByRole('button',{name:'Review changes',exact:true}).first().click();await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Export my draft');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Cancel');await p.evaluate(()=>document.querySelector('#game').focus());await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Cancel');await p.evaluate(()=>document.querySelector('#game').focus());await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Export my draft');await p.keyboard.press('Escape');assert.deepEqual(await p.evaluate(()=>reviewEvents),[{open:true,record:true},{open:false,record:true}]);assert.equal(await p.locator('#editor').isVisible(),true);assert.equal((await read(p)).dirty,true);
 });
 await check('repeated authorized review opening preserves native radio choices and a single open event',async p=>{
  await p.evaluate(()=>{window.openEvents=[];addEventListener('editor-review',e=>openEvents.push(e.detail));editor.receiveScene(peer([item('a')]));rename('a','Mine');editor.receiveScene(peer([{...item('a'),name:'Server'}],3));});await p.getByRole('button',{name:'Review changes',exact:true}).first().click();await p.getByLabel('Keep mine',{exact:true}).check();assert.equal(await p.evaluate(()=>editor.openReview({record:false})),true);assert.equal(await p.evaluate(()=>editor.openReview()),true);assert.equal(await p.getByLabel('Keep mine',{exact:true}).isChecked(),true);assert.equal(await p.getByRole('button',{name:'Use reviewed choices',exact:true}).isEnabled(),true);assert.deepEqual(await p.evaluate(()=>openEvents),[{open:true,record:true}]);assert.equal((await read(p)).requests.length,0);
 });
 await check('native Ctrl and Cmd Save shortcuts stay inside review and prevent browser Save Page',async p=>{
  await p.evaluate(()=>{window.saveKeys=[];addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s')saveKeys.push({prevented:e.defaultPrevented,trusted:e.isTrusted,ctrl:e.ctrlKey,meta:e.metaKey});});editor.receiveScene(peer([item('a')]));rename('a','Mine');editor.receiveScene(peer([{...item('a'),name:'Server'}],3));});await p.getByRole('button',{name:'Review changes',exact:true}).first().click();await p.keyboard.press('Control+s');assert.equal(await p.locator('.builder-conflict-review').isVisible(),true);assert.equal(await p.getByLabel('Keep mine',{exact:true}).evaluate(e=>document.activeElement===e),true);await p.getByLabel('Keep mine',{exact:true}).check();await p.keyboard.press('Meta+s');assert.equal(await p.getByRole('button',{name:'Use reviewed choices',exact:true}).evaluate(e=>document.activeElement===e),true);assert.equal(await p.getByLabel('Keep mine',{exact:true}).isChecked(),true);assert.deepEqual(await p.evaluate(()=>saveKeys),[{prevented:true,trusted:true,ctrl:true,meta:false},{prevented:true,trusted:true,ctrl:false,meta:true}]);assert.equal((await read(p)).requests.length,0);assert.equal((await read(p)).dirty,true);assert.match((await read(p)).toasts.at(-1),/use reviewed choices before saving/);
 });
 await check('compact review has touch choices and contained scrolling at 393px',async p=>{
  await p.addStyleTag({content:await readFile('public/universe-tokens.css','utf8')});await p.addStyleTag({content:(await readFile('public/style.css','utf8')).replace('@import "/universe-tokens.css";','')});await p.addStyleTag({content:await readFile('src/editor.css','utf8')});await p.setViewportSize({width:393,height:852});await p.evaluate(()=>{editor.receiveScene(peer([item('a')]));rename('a','My chair');editor.receiveScene(peer([{...item('a'),name:'Their chair'}],3));});await p.getByRole('button',{name:'Review changes',exact:true}).first().click();const dims=await p.locator('.builder-conflict-review').evaluate(e=>({x:e.getBoundingClientRect().x,right:e.getBoundingClientRect().right,height:e.getBoundingClientRect().height,choices:[...e.querySelectorAll('.builder-conflict-choices label')].map(x=>x.getBoundingClientRect().height)}));assert.ok(dims.x>=0&&dims.right<=393);assert.ok(dims.choices.every(h=>h>=48));await p.screenshot({path:out+'/compact-review.png'});
 });
 assert.deepEqual(errors,[]);
}finally{await browser.close();await writeFile(out+'/results.json',JSON.stringify({checks,errors,limits:['Controlled editor DOM with synthetic promise/event snapshots; no renderer or real HTTP/SSE','Operation service and native two-client checks are separate suites']},null,2));}
