import {build} from 'esbuild';
import {launch} from '../scripts/browser.mjs';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';

// Production editor and native world-input; deterministic ground projection and API response.
const source=`import {mountEditor} from './src/editor.js';import {mountWorldInput} from './src/world-input.js';import {emptyScene} from './src/worlds.js';
const scene=emptyScene();window.state={scene,room:{id:'toolbar',role:'owner',revision:1,scene:structuredClone(scene)},position:{x:0,z:7}};window.logs={custom:0,saves:[],commits:0};
const renderer={pick:(x,y)=>({point:{x:(x-innerWidth/2)/20,z:(y-280)/20}}),setGhost:()=>{},getCameraState:()=>({distance:25}),orbit:()=>{},pan:()=>{},zoom:()=>{}};
window.editor=mountEditor({root:document.querySelector('#editor'),getState:()=>state,onScene:s=>{state.scene=s;logs.commits++},onSelect:()=>{},onOpenImageLibrary:()=>logs.custom++,toast:()=>{},api:async(url,args)=>{logs.saves.push(args.body);return {room:{...state.room,revision:state.room.revision+1,scene:structuredClone(args.body.scene)}}}});editor.attachRoom();editor.setBuild(true);
mountWorldInput({canvas:document.querySelector('#game'),joystickRoot:document.querySelector('#joystick'),joystickThumb:document.querySelector('#thumb'),getContext:()=>({ready:true,building:true,modalOpen:false}),getRenderer:()=>renderer,getEditor:()=>editor,onWalkTo:()=>{},onInteract:()=>{},onJoystick:()=>{}});`;
const bundle=await build({stdin:{contents:source,resolveDir:process.cwd(),sourcefile:'toolbar-fixture.js'},bundle:true,format:'iife',write:false});
const css=(await Promise.all(['public/universe-tokens.css','public/style.css','src/editor.css'].map(path=>readFile(path,'utf8')))).join('\n');
const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}\nhtml,body{margin:0;width:100%;height:100%;overflow:hidden}#game{position:absolute;inset:0;width:100%;height:100%;touch-action:none;background:#537263}#joystick{display:none}[hidden]{display:none!important}</style><canvas id="game" tabindex="0"></canvas><aside id="editor"></aside><div id="joystick"><div id="thumb"></div></div>`;
const browser=await launch(),context=await browser.newContext({viewport:{width:320,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const report=(name,details={})=>{checks.push({name,...details});console.log('PASS',name,JSON.stringify(details));};
const rects=()=>page.evaluate(()=>{const belt=document.querySelector('.builder-toolbelt'),box=node=>{const r=node.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};return {width:document.documentElement.scrollWidth,belt:box(belt),buttons:[...belt.querySelectorAll('button')].map(node=>({name:node.getAttribute('aria-label')||node.textContent,rect:box(node),fits:node.scrollWidth<=node.clientWidth+1})),room:box(document.querySelector('.builder-room-settings')),done:box(document.querySelector('.builder-done'))}});
try{
 await mkdir('evidence',{recursive:true});await page.route('https://toolbar.test/',route=>route.fulfill({status:200,contentType:'text/html',body:html}));await page.goto('https://toolbar.test/');await page.addScriptTag({content:bundle.outputFiles[0].text});
 // Preserve twelve full-size direct tools by grouping Room beside Done.
 for(const width of [320,393,700,800,1024,1440]){
  await page.setViewportSize({width,height:844});const layout=await rects();assert.equal(layout.width,width);assert.equal(layout.buttons.length,12);for(const button of layout.buttons){assert(button.rect.x>=0&&button.rect.right<=width,`${width}: ${button.name} stays visible`);assert(button.rect.width>=44&&button.rect.height>=44,`${width}: ${button.name} touch target`);assert(button.fits,`${width}: ${button.name} label fits`);}for(let i=0;i<layout.buttons.length;i++)for(let j=i+1;j<layout.buttons.length;j++){const a=layout.buttons[i].rect,b=layout.buttons[j].rect;assert(!(a.x<b.right&&a.right>b.x&&a.y<b.bottom&&a.bottom>b.y),`${width}: tools do not overlap`);}if(width<=700)assert.equal(new Set(layout.buttons.map(b=>Math.round(b.rect.y+b.rect.height/2))).size,2);assert(layout.room.right<=layout.done.x);report('Touch toolbar stays reachable at '+width+'px',{minWidth:Math.min(...layout.buttons.map(b=>b.rect.width)),rows:new Set(layout.buttons.map(b=>Math.round(b.rect.y+b.rect.height/2))).size});
 }
 await page.setViewportSize({width:320,height:844});await page.getByRole('button',{name:'Terrain',exact:true}).tap();assert.equal(await page.evaluate(()=>editor.getTool()),'terrain');await page.getByRole('button',{name:'Paint stone',exact:true}).tap();const palette=await page.getByRole('region',{name:'Terrain tools'}).boundingBox(),belt=(await rects()).belt;assert(palette.y+palette.height<=belt.y);const hint=await page.locator('.builder-hint').boundingBox();assert(hint.y+hint.height<=palette.y+1,'Terrain hint does not cover its palette');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),320);
 const visibleControls=await page.evaluate(()=>[...document.querySelectorAll('.builder-terrain button,.builder-terrain input')].filter(node=>!node.disabled).map(node=>{const r=node.getBoundingClientRect();return {name:node.getAttribute('aria-label')||node.textContent,x:r.x,y:r.y,width:r.width,height:r.height,hit:node.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))}}));for(const control of visibleControls){assert(control.x>=0&&control.x+control.width<=320);assert(control.hit,control.name+' center remains reachable');if(control.name!=='Blocks walking')assert(control.width>=44&&control.height>=44,control.name+' touch target');}
 await page.screenshot({path:'evidence/editor-toolbar-terrain-320.png'});await page.touchscreen.tap(205,280);assert.equal(await page.evaluate(()=>state.scene.terrain.cells.length),1);const draft=await page.evaluate(()=>structuredClone(state.scene));await page.getByRole('button',{name:'Custom images',exact:true}).tap();assert.equal(await page.evaluate(()=>logs.custom),1);assert.deepEqual(await page.evaluate(()=>state.scene),draft);await page.getByRole('button',{name:'Save room',exact:true}).tap();await page.waitForFunction(()=>!editor.isSaving());assert.equal(await page.evaluate(()=>logs.saves.length),1);assert.deepEqual(await page.evaluate(()=>logs.saves[0].scene),draft);assert.equal(await page.evaluate(()=>editor.isDirty()),false);report('320px native touch reaches Terrain, paints one cell, opens Custom and saves the exact draft');
 await page.getByRole('button',{name:'⚙ Room',exact:true}).tap();assert.equal(await page.locator('.builder-inspector').isVisible(),true);await page.getByRole('button',{name:'Close item details',exact:true}).tap();await page.locator('#game').focus();for(let i=0;i<30&&await page.evaluate(()=>document.activeElement.getAttribute('aria-label'))!=='Terrain';i++)await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Terrain');await page.keyboard.press('Enter');await page.screenshot({path:'evidence/editor-toolbar-320.png'});report('Room settings and Terrain remain natively reachable after relocation');assert.deepEqual(errors,[]);
}catch(error){console.error(error);process.exitCode=1;await page.screenshot({path:'evidence/editor-toolbar-failure.png'}).catch(()=>{});}
finally{await writeFile('evidence/editor-toolbar-checks.json',JSON.stringify({checks,errors,limits:['Production editor/world-input fixture with native Chromium touch and keyboard','Custom library opening is verified through its production callback; full library behavior is covered by existing image suite']},null,2));await context.close();await browser.close();}
