import {build} from 'esbuild';
import {launch} from '../scripts/browser.mjs';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const source=`import {mountEditor} from './src/editor.js';import {emptyScene} from './src/worlds.js';
let scene=emptyScene();const state={scene,room:{id:'test',role:'owner',revision:1,scene:structuredClone(scene)},position:{x:0,z:7}};
window.logs={ghosts:[],toasts:[],commits:0,requests:[],closed:0};window.state=state;let savingResolve;window.resolveSave=()=>savingResolve?.({room:{...state.room,revision:state.room.revision+1,scene:structuredClone(state.scene)}});
window.rejectSave=()=>savingResolve?.(Promise.reject(Object.assign(new Error('Save conflict'),{status:409,data:{room:{...state.room,revision:9,scene:{...emptyScene(),theme:'studio'}}}})));
window.editor=mountEditor({root:document.querySelector('#editor'),getState:()=>state,onScene:s=>{state.scene=s;logs.commits++},onSelect:()=>{},toast:t=>logs.toasts.push(t),onGhost:g=>logs.ghosts.push(g),onClose:()=>logs.closed++,getCameraAngle:()=>Math.PI/4,api:(url,args)=>{logs.requests.push({url,args});return new Promise(r=>savingResolve=r)}});window.editor.attachRoom();window.editor.setBuild(true);`;
const bundle=await build({stdin:{contents:source,resolveDir:process.cwd(),sourcefile:'editor-fixture.js'},bundle:true,format:'iife',write:false});
const browser=await launch(),page=await browser.newPage();const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const check=name=>{checks.push({name,status:'passed'});console.log('PASS',name)};
try{
 // Give the editor a viewport-height lane before its ResizeObserver measures it.
 await page.route('https://editor.test/',route=>route.fulfill({status:200,contentType:'text/html',body:'<style>#editor{min-height:100vh}</style><canvas id="game" tabindex="0"></canvas><aside id="editor"></aside>'}));await page.goto('https://editor.test/');await page.addScriptTag({content:bundle.outputFiles[0].text});
 await page.locator('[data-tool=chair]').click();await page.evaluate(()=>{editor.pointerDown({point:{x:4,z:3}},{clientX:100,clientY:100,pointerId:1,button:0});editor.pointerUp({point:{x:4,z:3}},{clientX:100,clientY:100,pointerId:1,button:0});});assert.equal(await page.evaluate(()=>state.scene.objects.length),1);check('Single click commits one object');
 await page.evaluate(()=>{editor.select(state.scene.objects[0].id);editor.pointerDown({id:state.scene.objects[0].id,point:{x:4,z:3}},{clientX:100,clientY:100,pointerId:2,button:0});editor.pointerMove({point:{x:6.24,z:3.9}},{clientX:140,clientY:140,pointerId:2,button:0});});assert.equal(await page.evaluate(()=>state.scene.objects[0].x),4);assert.equal(await page.evaluate(()=>editor.getInteractionState().preview.x),6);await page.evaluate(()=>editor.pointerUp({point:{x:6.24,z:3.9}},{clientX:140,clientY:140,pointerId:2,button:0}));assert.equal(await page.evaluate(()=>state.scene.objects[0].x),6);assert.equal(await page.evaluate(()=>editor.getInteractionState().undo),2);check('Live drag is transactional and adds exactly one history entry');
 await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await page.evaluate(()=>state.scene.objects[0].x),4);await page.getByRole('button',{name:'Redo',exact:true}).click();assert.equal(await page.evaluate(()=>state.scene.objects[0].x),6);check('Undo/redo restores complete drag');
 await page.evaluate(()=>{const i=state.scene.objects[0];editor.pointerDown({id:i.id,point:{x:i.x,z:i.z}},{clientX:100,clientY:100,button:0});editor.pointerMove({point:{x:10,z:8}},{clientX:140,clientY:140,button:0});editor.cancelGesture();editor.pointerUp({point:{x:10,z:8}},{clientX:140,clientY:140,button:0});});assert.equal(await page.evaluate(()=>state.scene.objects[0].x),6);check('Camera cancellation cannot commit pending drag');
 // At yaw PI/4, screen-right is world -X/+Z in the shared left-handed camera basis.
 await page.locator('#game').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>state.scene.objects[0].x),5);assert.equal(await page.evaluate(()=>state.scene.objects[0].z),5);await page.keyboard.press('r');assert.equal(await page.evaluate(()=>state.scene.objects[0].rotation),90);await page.keyboard.press('d');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>state.scene.objects.length),2);check('Camera-relative keyboard nudge, rotate, duplicate and Space work');
 await page.locator('.inspector').getByRole('button',{name:'↻ Rotate',exact:true}).focus();await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'↻ Rotate');check('Native Space activates a focused inspector control and keeps its focus after editing');await page.locator('#game').focus();await page.keyboard.press('Control+s');assert.equal(await page.evaluate(()=>editor.isSaving()),true);const snapshot=await page.evaluate(()=>structuredClone(state.scene));await page.keyboard.press('Delete');await page.keyboard.press('ArrowRight');assert.deepEqual(await page.evaluate(()=>state.scene),snapshot);await page.evaluate(()=>resolveSave());await page.waitForFunction(()=>!editor.isSaving());assert.equal(await page.evaluate(()=>editor.isDirty()),false);check('Saving locks draft mutations and acknowledges exact accepted snapshot');
 await page.locator('#game').focus();await page.keyboard.press('r');const freshDraft=await page.evaluate(()=>structuredClone(state.scene));await page.evaluate(()=>editor.receiveScene({...state.room,scene:structuredClone(state.room.scene)}));assert.deepEqual(await page.evaluate(()=>state.scene),freshDraft);assert(await page.locator('.builder-recovery').isHidden());check('Late same-revision server event cannot replace or falsely conflict with a new draft');await page.keyboard.press('Control+s');await page.evaluate(()=>rejectSave());await page.waitForFunction(()=>!editor.isSaving());assert.equal(await page.evaluate(()=>editor.isDirty()),true);assert(await page.getByRole('button',{name:'Load server version',exact:true}).isVisible());await page.getByRole('button',{name:'Load server version',exact:true}).click();assert.equal(await page.evaluate(()=>state.scene.theme),'studio');assert.equal(await page.evaluate(()=>editor.isDirty()),false);check('Rejected save retains draft and explicit server recovery works');
 await page.locator('#game').focus();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>logs.closed),1);check('Escape at neutral closes build');assert.deepEqual(errors,[]);
}catch(e){checks.push({name:'failure',status:'failed',error:e.stack});console.error(e);process.exitCode=1;}finally{await writeFile('evidence/editor-transaction-checks.json',JSON.stringify({checks,errors,limits:['Isolated editor model with controlled save response; full renderer and real server tested separately']},null,2));await browser.close();}
