/** Isolated browser acceptance for the Express and command menu modules. */
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
const fixture=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/express.css"><link rel="stylesheet" href="/command-palette.css"><style>html,body{width:100%;height:100%;margin:0}body{margin:0;background:radial-gradient(ellipse at 50% 50%,#897394,#261e36);font:14px Arial;color:white}#game{position:absolute;inset:0;width:100%;height:100%;border:0;outline:0;background:transparent}.test-controls{position:absolute;top:18px;left:18px;z-index:30;display:flex;gap:12px}.test-controls button{padding:12px;background:#30233c;color:white;border:1px solid #8e65ae;border-radius:9px}#outside{position:absolute;right:20px;top:20px;z-index:30}#express{position:absolute;inset:0}button,input{font:inherit}[hidden]{display:none!important}</style></head><body><canvas id="game" tabindex="0"></canvas><div class="test-controls"><button id="open">Express</button><button id="quick">Quick menu</button></div><input id="outside" value="A preserved draft"><div id="express"></div><div id="palette"></div><script type="module">
import{mountExpress}from'/express.js';import{mountPalette}from'/command-palette.js';
const self={id:'me',name:'Mira',woka:0,status:'online'},peer={id:'ari',name:'Ari <b>unsafe</b>',woka:1,x:3,z:0};
window.state={ready:true,user:self,room:{id:'r1',name:'Moon garden',role:'owner'},position:{x:0,z:0},moving:false,people:[self,peer],scene:{areas:[]},worlds:[{id:'w',name:'Our world',rooms:[{id:'r1',name:'Moon garden'},{id:'r2',name:'Art studio'}]}]};
window.portraitCalls=[];window.holdPortrait=false;window.pendingPortraits=[];window.holdFlush=false;window.flushes=[];window.calls=[];window.runs=[];window.toasts=[];window.hold=false;window.reject=false;window.pending=[];window.clock=Date.now();window.gameKeys=[];window.projection={x:450,y:400,visible:true};
window.snapshotThoughts=[];window.holdSnapshot=false;window.pendingSnapshots=[];window.api=async(path,options={})=>{if(path.endsWith('/expressions')){const thoughts=structuredClone(window.snapshotThoughts);if(window.holdSnapshot)await new Promise(resolve=>window.pendingSnapshots.push(resolve));return{thoughts}};window.calls.push({path,...options});if(window.hold)await new Promise(resolve=>window.pending.push(resolve));if(window.reject){window.reject=false;throw Error('Network interrupted. Your draft is safe.')}if(path.endsWith('/expression'))return{expression:{id:options.body.clientOperationId,roomId:path.split('/')[3],author:self,kind:options.body.kind,text:options.body.text,origin:{x:0,z:0}}};return{ok:true}};
window.express=mountExpress({root:document.querySelector('#express'),api:window.api,getState:()=>window.state,beforeSend:async()=>{if(window.holdFlush)await new Promise(resolve=>window.flushes.push(resolve))},project:()=>window.projection,onReturnFocus:()=>document.querySelector('#game').focus(),now:()=>window.clock,onEmote:emoji=>window.runs.push('emote:'+emoji),toast:message=>window.toasts.push(message)});
window.palette=mountPalette({root:document.querySelector('#palette'),portrait:async person=>{window.portraitCalls.push({id:person.id,appearance:person.appearance});if(window.holdPortrait)await new Promise(resolve=>window.pendingPortraits.push(resolve));return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZlWQAAAAASUVORK5CYII='},getState:()=>window.state,getActions:()=>[{id:'express',label:'Express yourself',description:'Say, think, react',icon:'☻',run:()=>window.express.open()},{id:'build',label:'Build the room',description:'Create something',enabled:state=>state.room.role==='owner',run:()=>window.runs.push('build')},{id:'camera',label:'Reset camera',description:'Find your view',run:()=>window.runs.push('camera')}],onPerson:person=>window.runs.push('person:'+person.id),onNavigate:room=>window.runs.push('room:'+room),toast:message=>window.toasts.push(message)});
window.addEventListener('keydown',e=>{if(window.palette.handleKey(e)||window.express.handleKey(e))return},true);window.addEventListener('keyup',e=>window.express.handleKey(e),true);
window.addEventListener('keydown',e=>window.gameKeys.push(e.key));document.querySelector('#open').onclick=()=>window.express.open();document.querySelector('#quick').onclick=()=>window.palette.open();
window.frame=setInterval(()=>window.express.update(),30);window.ready=true;
</script></body></html>`;
const server=http.createServer(async(req,res)=>{try{if(/^\/(express|command-palette)\.(js|css)$/.test(req.url)){res.setHeader('Content-Type',req.url.endsWith('css')?'text/css':'text/javascript');res.end(await readFile(new URL('../src'+req.url,import.meta.url)));}else{res.setHeader('Content-Type','text/html');res.end(fixture)}}catch(e){res.statusCode=500;res.end(e.message)}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await launch();const page=await browser.newPage({viewport:{width:900,height:820}});const errors=[],checks=[];page.on('pageerror',error=>errors.push(error.message));
const check=async(name,fn)=>{await fn();checks.push({name,status:'passed'});console.log('PASS',name)};
try{
 await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>window.ready);
 await check('Enter keyup opens Express, typing is isolated, authenticated Say and screen-attached bubble',async()=>{
  await page.locator('#game').focus();await page.keyboard.press('Enter');await page.getByRole('textbox',{name:'Your expression',exact:true}).fill('Hello <img src=x>');await page.keyboard.press('Enter');
  await page.waitForFunction(()=>window.calls.length===1);assert.equal(await page.locator('.express-tray').isHidden(),true);assert.equal(await page.locator('.express-bubble-text').textContent(),'Hello <img src=x>');assert.equal(await page.locator('.express-bubble img').count(),0);
  assert.equal(await page.evaluate(()=>window.calls[0].path),'/api/rooms/r1/expression');assert.equal(await page.evaluate(()=>window.calls[0].body.kind),'say');assert.equal(await page.locator('.express-bubble').getAttribute('data-user-id'),'me');
  const x=await page.locator('.express-bubble').evaluate(el=>el.style.left);await page.evaluate(()=>window.projection.x=520);await page.waitForFunction(()=>document.querySelector('.express-bubble').style.left==='520px');assert.notEqual(x,'520px');
 });
 await check('close debounce blocks released Enter and Ctrl Enter opens visible Think',async()=>{
  await page.keyboard.press('Enter');assert.equal(await page.locator('.express-tray').isHidden(),true);await page.evaluate(()=>window.clock+=600);await page.keyboard.press('Control+Enter');
  assert.equal(await page.locator('[data-mode=think]').count(),1);await page.getByRole('textbox',{name:'Your expression',exact:true}).fill('Sketching ideas');await page.keyboard.press('Enter');await page.locator('.express-bubble-think').waitFor();assert.equal(await page.evaluate(()=>window.calls.at(-1).body.kind),'think');
  await page.evaluate(()=>{window.state.position.x=1;window.express.update()});assert.equal(await page.locator('.express-bubble-think').count(),0);assert.equal(await page.locator('.express-bubble-say').count(),1);
 });
 await check('Say expires independently and hidden projection suppresses offscreen expression',async()=>{
  await page.evaluate(()=>{window.projection.visible=false;window.express.update()});assert.equal(await page.locator('.express-bubble').isHidden(),true);await page.evaluate(()=>{window.projection.visible=true;window.clock+=6000;window.express.update()});assert.equal(await page.locator('.express-bubble').count(),0);
 });
 await check('IME Enter does not submit, failed sends retain drafts, duplicate retry uses same operation',async()=>{
  await page.getByRole('button',{name:'Express',exact:true}).click();const input=page.getByRole('textbox',{name:'Your expression',exact:true});await input.fill('こんにちは');const count=await page.evaluate(()=>window.calls.length);
  await input.evaluate(el=>el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,isComposing:true})));assert.equal(await page.evaluate(()=>window.calls.length),count);
  await page.evaluate(()=>window.reject=true);await input.press('Enter');await page.getByRole('alert').waitFor();assert.equal(await input.inputValue(),'こんにちは');const id=await page.evaluate(()=>window.calls.at(-1).body.clientOperationId);await input.press('Enter');await page.waitForFunction(()=>document.querySelector('.express-tray').hidden);assert.equal(await page.evaluate(()=>window.calls.at(-1).body.clientOperationId),id);
 });
 await check('in-flight room changes never show an old-room bubble or erase a new draft',async()=>{
  await page.getByRole('button',{name:'Express',exact:true}).click();await page.getByRole('textbox',{name:'Your expression',exact:true}).fill('Old room message');await page.evaluate(()=>window.hold=true);await page.getByRole('button',{name:'Send expression',exact:true}).click();
  await page.evaluate(()=>{window.state.room={id:'r2',name:'Studio',role:'owner'};window.express.update();window.express.open()});assert.equal(await page.getByRole('textbox',{name:'Your expression',exact:true}).inputValue(),'');await page.getByRole('textbox',{name:'Your expression',exact:true}).fill('New room draft');
  await page.evaluate(()=>{window.hold=false;window.pending.shift()()});await page.waitForTimeout(70);assert.equal(await page.locator('.express-bubble').count(),0);assert.equal(await page.getByRole('textbox',{name:'Your expression',exact:true}).inputValue(),'New room draft');
  await page.getByRole('button',{name:'Close Express',exact:true}).click();await page.evaluate(()=>{window.state.room={id:'r1',role:'owner'};window.express.update()});
 });
 await check('room change during awaited presence flush cancels POST and retains original draft',async()=>{
  await page.getByRole('button',{name:'Express',exact:true}).click();await page.getByRole('textbox',{name:'Your expression',exact:true}).fill('Before leaving');const before=await page.evaluate(()=>window.calls.length);await page.evaluate(()=>window.holdFlush=true);await page.getByRole('button',{name:'Send expression',exact:true}).click();await page.waitForFunction(()=>window.flushes.length===1);
  await page.evaluate(()=>{window.state.room={id:'r2',role:'owner'};window.express.update();window.flushes.shift()();window.holdFlush=false});await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>window.calls.length),before);
  await page.evaluate(()=>{window.state.room={id:'r1',role:'owner'};window.express.update();window.express.open()});assert.equal(await page.getByRole('textbox',{name:'Your expression',exact:true}).inputValue(),'Before leaving');await page.getByRole('button',{name:'Close Express',exact:true}).click();
 });
 await check('Tab-focused tray controls retain native Enter and Space activation',async()=>{
  await page.getByRole('button',{name:'Express',exact:true}).click();await page.getByRole('textbox',{name:'Your expression',exact:true}).fill('A composer draft');
  await page.getByRole('button',{name:'Think',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.express-tray').isVisible(),true);assert.equal(await page.locator('.express-tray').getAttribute('data-mode'),'think');assert.equal(await page.getByRole('textbox',{name:'Your expression',exact:true}).inputValue(),'A composer draft');
  await page.getByRole('button',{name:'Say',exact:true}).focus();await page.keyboard.press('Space');assert.equal(await page.locator('.express-tray').getAttribute('data-mode'),'say');assert.equal(await page.getByRole('textbox',{name:'Your expression',exact:true}).inputValue(),'A composer draft');
  await page.getByRole('button',{name:'Make it yours',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.express-preferences').isVisible(),true);await page.getByRole('button',{name:'Cancel',exact:true}).focus();await page.keyboard.press('Space');assert.equal(await page.locator('.express-preferences').isHidden(),true);
  await page.getByRole('button',{name:'Hi!',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('.express-tray').hidden);assert.equal(await page.evaluate(()=>window.calls.at(-1).body.text),'Hi!');
  await page.getByRole('button',{name:'Express',exact:true}).click();await page.getByRole('button',{name:'Express 👍',exact:true}).focus();await page.keyboard.press('Space');await page.waitForFunction(()=>document.querySelector('.express-tray').hidden);assert.equal(await page.evaluate(()=>window.calls.at(-1).body.emoji),'👍');
 });
 await check('custom favorites persist and real emote endpoint is invoked',async()=>{
  await page.getByRole('button',{name:'Express',exact:true}).click();await page.getByRole('button',{name:'Make it yours',exact:true}).click();await page.getByRole('textbox',{name:'Favorite emote 1',exact:true}).fill('🚀');await page.getByRole('textbox',{name:'Quick phrase 1',exact:true}).fill('Ready to create');await page.getByRole('button',{name:'Save favorites',exact:true}).click();await page.getByRole('button',{name:'Express 🚀',exact:true}).click();await page.waitForFunction(()=>window.runs.includes('emote:🚀'));assert.equal(await page.evaluate(()=>window.calls.at(-1).path),'/api/rooms/r1/emote');
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('universe:express:v1:me')).phrases[0]),'Ready to create');
 });
 await check('away status forces Think and persistent room or DM messages never become avatar bubbles',async()=>{
  await page.evaluate(()=>{window.state.user.status='away';window.express.clear();window.express.open();window.express.onEvent({type:'message',data:{roomId:'r1',message:{id:'persistent',author:window.state.people[1],text:'Private history'}}});window.express.onEvent({type:'dm',data:{message:{id:'dm',text:'Secret'}}})});
  assert.equal(await page.getByRole('button',{name:'Say',exact:true}).isDisabled(),true);assert.equal(await page.locator('.express-bubble').count(),0);await page.getByRole('textbox',{name:'Your expression',exact:true}).fill('Quietly thinking');await page.keyboard.press('Enter');await page.waitForFunction(()=>window.calls.at(-1).body.kind==='think');
 });
 await check('reconnect snapshot retains the same thought and cannot override newer live thought or clear',async()=>{
  await page.evaluate(()=>{window.express.clear();window.state.position={x:0,z:0};window.snapshotThoughts=[{id:'reconnect-think',roomId:'r1',author:window.state.people[1],kind:'think',text:'Still sketching',origin:{x:3,z:0}}];window.express.onEvent({type:'hello',data:{}})});await page.locator('[data-expression-id="reconnect-think"]').waitFor();
  await page.evaluate(()=>window.express.onEvent({type:'hello',data:{}}));await page.waitForTimeout(60);assert.equal(await page.locator('[data-expression-id="reconnect-think"]').count(),1);
  await page.evaluate(()=>{window.holdSnapshot=true;window.express.onEvent({type:'hello',data:{}});window.express.onEvent({type:'expression',data:{roomId:'r1',expression:{id:'live-new',roomId:'r1',author:window.state.people[1],kind:'think',text:'New idea',origin:{x:3,z:0}}}});window.pendingSnapshots.shift()();window.holdSnapshot=false});await page.waitForTimeout(60);assert.equal(await page.locator('[data-expression-id="live-new"]').count(),1);assert.equal(await page.locator('[data-expression-id="reconnect-think"]').count(),0);
  await page.evaluate(()=>{window.holdSnapshot=true;window.express.onEvent({type:'hello',data:{}});window.express.onEvent({type:'expression-clear',data:{roomId:'r1',userId:'ari',kind:'think'}});window.pendingSnapshots.shift()();window.holdSnapshot=false;window.snapshotThoughts=[]});await page.waitForTimeout(60);assert.equal(await page.locator('.express-bubble-think').count(),0);
 });
 await check('Cmd K preserves another text field and Escape restores exact selection',async()=>{
  await page.locator('#outside').focus();await page.locator('#outside').evaluate(el=>el.setSelectionRange(2,7));await page.keyboard.press('Meta+k');await page.getByRole('combobox').waitFor();await page.getByRole('combobox').fill('cam');await page.keyboard.press('Escape');assert.equal(await page.locator('#outside').inputValue(),'A preserved draft');assert.deepEqual(await page.locator('#outside').evaluate(el=>[document.activeElement===el,el.selectionStart,el.selectionEnd]),[true,2,7]);
 });
 await check('command arrows/Enter execute real callback after closing and omit unauthorized build',async()=>{
  await page.keyboard.press('Control+k');await page.getByRole('combobox').fill('Reset camera');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.equal(await page.locator('#palette').isHidden(),true);assert(await page.evaluate(()=>window.runs.includes('camera')));
  await page.evaluate(()=>window.state.room.role='member');await page.keyboard.press('Control+k');await page.getByRole('combobox').fill('build');assert.equal(await page.getByRole('option').count(),0);await page.keyboard.press('Escape');
 });
 await check('people/place command results use live actual state and hostile names stay literal',async()=>{
  await page.getByRole('button',{name:'Quick menu',exact:true}).click();await page.getByRole('combobox').fill('Ari');assert.equal(await page.locator('.command-result script').count(),0);assert.match(await page.getByRole('option').textContent(),/Ari <b>unsafe<\/b>/);await page.keyboard.press('Enter');assert(await page.evaluate(()=>window.runs.includes('person:ari')));
  await page.getByRole('button',{name:'Quick menu',exact:true}).click();await page.getByRole('combobox').fill('Art studio');await page.keyboard.press('Enter');assert(await page.evaluate(()=>window.runs.includes('room:r2')));
 });
 await check('people keep actual appearance, render async native portraits and never request legacy sprites',async()=>{
  await page.evaluate(()=>{window.state.people[1].appearance={palette:'plum',hair:'crop'};window.holdPortrait=true});await page.getByRole('button',{name:'Quick menu',exact:true}).click();await page.getByRole('combobox').fill('Ari');await page.waitForFunction(()=>window.pendingPortraits.length===1);assert.equal(await page.locator('.command-person-initials').count(),1);assert.equal(await page.locator('.command-person-portrait').count(),0);
  await page.evaluate(()=>{window.pendingPortraits.shift()();window.holdPortrait=false});await page.locator('.command-person-portrait').waitFor();assert.deepEqual(await page.evaluate(()=>window.portraitCalls.at(-1)),{id:'ari',appearance:{palette:'plum',hair:'crop'}});assert.match(await page.locator('.command-person-portrait').getAttribute('src'),/^data:image\/png;base64,/);assert.equal(await page.locator('[style*="woka-"]').count(),0);
  await page.getByRole('combobox').fill('Camera');assert.equal(await page.locator('.command-person-portrait').count(),0);await page.keyboard.press('Escape');
 });
 await check('presence-only refresh keeps the actual clickable option and portrait DOM stable',async()=>{
  await page.getByRole('button',{name:'Quick menu',exact:true}).click();await page.getByRole('combobox').fill('Ari');await page.locator('.command-person-portrait').waitFor();
  await page.evaluate(()=>{window.stableOption=document.querySelector('[role=option]');window.stablePortrait=document.querySelector('.command-person-portrait');for(let i=0;i<80;i++){window.state.people[1]={...window.state.people[1],x:i/10,z:i/20,lastSeen:i};window.palette.refresh();}});
  assert.equal(await page.evaluate(()=>window.stableOption===document.querySelector('[role=option]')&&window.stableOption.isConnected&&window.stablePortrait===document.querySelector('.command-person-portrait')),true);
  await page.getByRole('option').click();assert.equal(await page.locator('#palette').isHidden(),true);assert(await page.evaluate(()=>window.runs.includes('person:ari')));
 });
 await check('open-menu role revocation is revalidated at execution',async()=>{
  await page.evaluate(()=>window.state.room.role='owner');await page.getByRole('button',{name:'Quick menu',exact:true}).click();await page.getByRole('combobox').fill('Build');assert.equal(await page.getByRole('option').count(),1);await page.evaluate(()=>window.state.room.role='member');await page.keyboard.press('Enter');assert.equal(await page.getByRole('option').count(),0);assert.equal(await page.evaluate(()=>window.runs.includes('build')),false);await page.keyboard.press('Escape');
 });
 await check('room revocation immediately clears avatar speech and closes Express',async()=>{
  await page.getByRole('button',{name:'Express',exact:true}).click();await page.evaluate(()=>window.express.onEvent({type:'access-revoked',data:{roomId:'r1'}}));assert.equal(await page.locator('.express-bubble').count(),0);assert.equal(await page.locator('.express-tray').isHidden(),true);
 });
 await page.evaluate(()=>{window.state.user.status='online';window.express.open();window.express.onEvent({type:'expression',data:{roomId:'r1',expression:{id:'photo',roomId:'r1',author:window.state.people[1],kind:'say',text:'Make a little room for magic ✨'}}})});await page.waitForTimeout(260);await page.screenshot({path:'evidence/express-desktop.png'});
 await check('mobile tray and quick menu fit narrow screens',async()=>{
  await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.screenshot({path:'evidence/express-mobile.png'});
  const tray=await page.locator('.express-tray').boundingBox();assert(tray.x>=0&&tray.x+tray.width<=390);await page.getByRole('button',{name:'Close Express',exact:true}).click();await page.getByRole('button',{name:'Quick menu',exact:true}).click();const panel=await page.locator('.command-panel').boundingBox();assert(panel.x>=0&&panel.x+panel.width<=390);await page.screenshot({path:'evidence/command-mobile.png'});
 });
 await check('touch entry does not summon keyboard, printable keys focus composer, and swipe dismisses',async()=>{
  const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const touch=await touchContext.newPage();touch.on('pageerror',e=>errors.push(e.message));await touch.goto(`http://127.0.0.1:${server.address().port}`);await touch.waitForFunction(()=>window.ready);await touch.getByRole('button',{name:'Express',exact:true}).tap();
  assert.equal(await touch.evaluate(()=>matchMedia('(pointer: fine)').matches),false);assert.notEqual(await touch.evaluate(()=>document.activeElement.className),'express-input');
  await touch.keyboard.type('hi');assert.equal(await touch.getByRole('textbox',{name:'Your expression',exact:true}).inputValue(),'hi');assert.equal(await touch.evaluate(()=>document.activeElement.className),'express-input');
  await touch.locator('.express-heading').evaluate(el=>{el.dispatchEvent(new TouchEvent('touchstart',{bubbles:true,touches:[new Touch({identifier:1,target:el,clientX:80,clientY:430})]}));el.dispatchEvent(new TouchEvent('touchend',{bubbles:true,changedTouches:[new Touch({identifier:1,target:el,clientX:84,clientY:510})]}))});assert.equal(await touch.locator('.express-tray').isHidden(),true);await touchContext.close();
 });
 assert.deepEqual(errors,[]);await writeFile('evidence/express-browser-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
