import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds} from '../src/worlds.js';
async function fixture(database=':memory:',clock=Date.now){const app=createGameServer({database,seeds:seedWorlds,clock});const{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;const client=()=>({cookie:'',async call(path,method='GET',body){const r=await fetch(base+path,{method,headers:{Cookie:this.cookie,...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,data:await r.json()};}});let seq=0;async function guest(name='Guest',account=false){const c=client();const r=await c.call('/api/session','POST',{name});c.user=r.data.user;if(account)assert.equal((await c.call('/api/account','POST',{username:`account_${++seq}`,password:'strong local password'})).status,201);return c;}return{app,base,client,guest};}
async function create(c,path,data){const r=await c.call(path,'POST',data);assert.equal(r.status,201,JSON.stringify(r));return r.data;}
async function setup(t,opts={}){const f=await fixture(opts.database,opts.clock);t.after(()=>f.app.close());const owner=await f.guest('Owner',true),member=await f.guest('Member',true),other=await f.guest('Other',true);return{...f,owner,member,other};}

test('WORLD-02/03 create identity, retry, forbidden fields, slug scopes and metadata CAS',async t=>{const{owner,other}=await setup(t);const b={name:'My universe',slug:'my-universe',description:'First',clientOperationId:'universe-op'};const u=(await create(owner,'/api/universes',b)).universe;assert.equal(u.ownerId,owner.user.id);assert.equal((await owner.call('/api/universes','POST',b)).data.universe.id,u.id);assert.equal((await owner.call('/api/universes','POST',{...b,name:'Changed'})).status,409);assert.equal((await owner.call('/api/universes','POST',{name:'Dup',slug:u.slug})).status,409);assert.equal((await owner.call('/api/universes','POST',{name:'Forgery',ownerId:other.user.id})).status,400);assert.equal((await owner.call(`/api/universes/${u.id}`,'PATCH',{featured:true})).status,400);const w=(await create(owner,'/api/worlds',{universeId:u.id,name:'World',slug:'same'})).world;const u2=(await create(owner,'/api/universes',{name:'Second'})).universe;assert.equal((await create(owner,'/api/worlds',{universeId:u2.id,name:'World',slug:'same'})).world.slug,'same');assert.equal((await owner.call('/api/worlds','POST',{universeId:u.id,name:'Dup',slug:'same'})).status,409);assert.equal((await other.call('/api/worlds','POST',{universeId:u.id,name:'No'})).status,403);const changed=await owner.call(`/api/universes/${u.id}`,'PATCH',{slug:'renamed',metadataRevision:0});assert.equal(changed.data.universe.id,u.id);assert.equal((await owner.call(`/api/universes/${u.id}`,'PATCH',{name:'stale',metadataRevision:0})).status,409);assert.equal(w.capabilities.canEdit,true);});

test('ACCESS-06 public guest visits persist no membership and private ancestors block every route',async t=>{const{app,owner,member}=await setup(t);await member.call('/api/rooms/commons/join','POST',{});assert.equal(app.store.get('SELECT COUNT(*) AS n FROM world_members WHERE user_id=?',member.user.id).n,0);assert.equal(app.store.get('SELECT COUNT(*) AS n FROM members WHERE user_id=?',member.user.id).n,0);assert.equal((await member.call('/api/rooms/commons')).data.room.role,'guest');const u=(await create(owner,'/api/universes',{name:'Secret parent',public:false})).universe;const w=(await create(owner,'/api/worlds',{universeId:u.id,name:'Public child',public:true})).world;const r=(await create(owner,'/api/rooms',{worldId:w.id,name:'Secret room',public:true})).room;for(const path of [`/api/universes/${u.id}`,`/api/worlds/${w.id}`,`/api/rooms/${r.id}`,`/api/rooms/${r.id}/files`])assert.equal((await member.call(path)).status,404,path);assert.equal((await member.call(`/api/rooms/${r.id}/join`,'POST',{})).status,404);assert.equal((await member.call('/api/discover?q=Secret')).data.rooms.length,0);assert.equal((await member.call(`/api/rooms/${r.id}/star`,'PUT',{})).status,404);});

test('WORLD-04/05 scoped admins/editors, last manager, tags, cross-world isolation',async t=>{const{owner,member,other}=await setup(t);const u=(await create(owner,'/api/universes',{name:'Roles'})).universe;const w=(await create(owner,'/api/worlds',{universeId:u.id,name:'One'})).world;const w2=(await create(owner,'/api/worlds',{universeId:u.id,name:'Two'})).world;let m=await owner.call(`/api/worlds/${w.id}/members/${member.user.id}`,'PUT',{role:'editor',tags:['artist']});assert.equal(m.status,200);assert.equal((await member.call(`/api/worlds/${w.id}`)).data.world.capabilities.canEdit,false);assert.equal((await member.call('/api/rooms','POST',{worldId:w.id,name:'Not allowed'})).status,403);assert.equal((await member.call(`/api/worlds/${w.id}/members/${member.user.id}`,'PUT',{role:'admin'})).status,403);assert.equal((await owner.call(`/api/worlds/${w2.id}/members/${member.user.id}`,'DELETE')).status,404);const room=(await create(owner,'/api/rooms',{worldId:w.id,name:'Room'})).room;assert.equal((await member.call(`/api/rooms/${room.id}`,'PATCH',{name:'Editor changed'})).status,200);assert.equal((await member.call(`/api/rooms/${room.id}`,'DELETE')).status,200);assert.equal((await member.call(`/api/rooms/${room.id}/restore`,'POST',{})).status,200);await owner.call(`/api/worlds/${w.id}/members/${member.user.id}`,'PUT',{role:'admin',tags:['artist']});assert.equal((await create(member,'/api/rooms',{worldId:w.id,name:'Admin room'})).room.role,'admin');assert.equal((await owner.call(`/api/worlds/${w.id}/members/${owner.user.id}`,'DELETE')).status,409);assert.equal((await owner.call(`/api/worlds/${w.id}/leave`,'POST',{userId:other.user.id})).status,400);assert.equal((await member.call(`/api/worlds/${w.id}/members`)).data.members.find(m=>m.userId===member.user.id).tags.includes('artist'),true);});

test('WORLD-06 ACCESS-04 targeted pending invitations accept/cancel race, preserve member and reject/expire',async t=>{let time=Date.now();const{owner,member,other}=await setup(t,{clock:()=>time});const w=(await create(owner,'/api/worlds',{name:'Invites',public:false})).world;const b={userId:member.user.id,role:'editor',tags:['maker'],clientOperationId:'invite-once'};const invitation=(await create(owner,`/api/worlds/${w.id}/invitations`,b)).invitation;assert.equal((await member.call('/api/memberships')).data.memberships.length,0);assert.equal((await owner.call(`/api/worlds/${w.id}/invitations`,'POST',b)).data.invitation.id,invitation.id);assert.equal((await other.call(`/api/invitations/${invitation.id}/accept`,'POST',{})).status,404);const result=await Promise.all([member.call(`/api/invitations/${invitation.id}/accept`,'POST',{}),owner.call(`/api/invitations/${invitation.id}/cancel`,'POST',{})]);assert.deepEqual(result.map(r=>r.status).sort(),[200,409]);const status=(await owner.call(`/api/worlds/${w.id}/invitations`)).data.invitations.find(i=>i.id===invitation.id).status;assert.equal((await member.call('/api/memberships')).data.memberships.some(m=>m.worldId===w.id),status==='accepted');await owner.call(`/api/worlds/${w.id}/members/${member.user.id}`,'PUT',{role:'member',tags:['keep']});const second=(await create(owner,`/api/worlds/${w.id}/invitations`,{userId:member.user.id,role:'admin',tags:['overwrite']})).invitation;assert.equal((await member.call(`/api/invitations/${second.id}/accept`,'POST',{})).status,200);assert.deepEqual((await member.call('/api/memberships')).data.memberships.find(m=>m.worldId===w.id).tags,['keep']);const third=(await create(owner,`/api/worlds/${w.id}/invitations`,{userId:other.user.id,role:'member'})).invitation;assert.equal((await other.call(`/api/invitations/${third.id}/reject`,'POST',{})).status,200);const fourth=(await create(owner,`/api/worlds/${w.id}/invitations`,{userId:other.user.id,expiresInDays:1})).invitation;time+=2*86400000;assert.equal((await other.call(`/api/invitations/${fourth.id}/accept`,'POST',{})).status,409);assert.equal((await other.call('/api/invitations')).data.invitations.find(i=>i.id===fourth.id).status,'expired');});

test('WORLD-07 NAV-03 scoped discovery, stable stars, archive/recover preserves scene and stale grants',async t=>{const{app,owner,member}=await setup(t);const w=(await create(owner,'/api/worlds',{name:'Discovery'})).world;const r=(await create(owner,'/api/rooms',{worldId:w.id,name:'Needle'})).room;await member.call(`/api/rooms/${r.id}/star`,'PUT',{});await member.call(`/api/rooms/${r.id}/star`,'PUT',{});assert.equal((await member.call('/api/stars')).data.rooms.length,1);assert.equal((await member.call(`/api/discover?universeId=${w.universeId}&q=Needle`)).data.rooms[0].id,r.id);await owner.call(`/api/worlds/${w.id}`,'PATCH',{public:false});assert.equal((await member.call('/api/stars')).data.rooms.length,0);await owner.call(`/api/worlds/${w.id}`,'DELETE');assert.equal((await owner.call(`/api/rooms/${r.id}`)).status,404);assert.equal(app.store.get('SELECT id FROM rooms WHERE id=?',r.id).id,r.id);await owner.call(`/api/worlds/${w.id}/restore`,'POST',{});assert.equal((await owner.call(`/api/rooms/${r.id}`)).data.room.scene.version,1);});

test('ACCESS-06 membership revoke disconnects old SSE, media and file access immediately',async t=>{const{app,base,owner,member}=await setup(t);const w=(await create(owner,'/api/worlds',{name:'Private revoke',public:false})).world;const r=(await create(owner,'/api/rooms',{worldId:w.id,name:'Private',public:false})).room;await owner.call(`/api/worlds/${w.id}/members/${member.user.id}`,'PUT',{role:'editor'});await member.call(`/api/rooms/${r.id}/join`,'POST',{});await member.call('/api/media/state','POST',{enabled:true});const abort=new AbortController(),response=await fetch(base+'/api/events',{headers:{Cookie:member.cookie},signal:abort.signal});let content='';const reading=(async()=>{try{for await(const chunk of response.body)content+=new TextDecoder().decode(chunk);}catch{}})();t.after(async()=>{abort.abort();await reading;});assert.equal((await owner.call(`/api/worlds/${w.id}/members/${member.user.id}`,'DELETE')).status,200);await new Promise(r=>setTimeout(r,30));assert.match(content,/event: access-revoked/);assert.match(content,/recoverDraft/);assert.match(content,/event: media-policy/);assert.equal((await member.call('/api/session')).data.currentRoomId,null);assert.equal((await member.call(`/api/rooms/${r.id}/files`)).status,404);assert.equal((await member.call(`/api/rooms/${r.id}/scene`,'PUT',{revision:0,scene:r.scene})).status,404);assert.equal(app.presence.has(`${r.id}:${member.user.id}`),false);await owner.call(`/api/rooms/${r.id}/messages`,'POST',{text:'secret-after-revocation'});await new Promise(r=>setTimeout(r,20));assert.equal(content.includes('secret-after-revocation'),false);assert.equal((await member.call('/api/media/signal','POST',{roomId:r.id,to:owner.user.id,connectionId:'stale',request:'offer'})).status,403);});

test('SQLite hierarchy restart preserves metadata, memberships, invitations, archives and existing scene',async t=>{const dir=await mkdtemp(join(tmpdir(),'hierarchy-'));t.after(()=>rm(dir,{recursive:true,force:true}));const database=join(dir,'game.sqlite');let f=await fixture(database),a=await f.guest('Owner',true),b=await f.guest('Member',true);const u=(await create(a,'/api/universes',{name:'Durable'})).universe,w=(await create(a,'/api/worlds',{universeId:u.id,name:'Saved'})).world,r=(await create(a,'/api/rooms',{worldId:w.id,name:'Saved room'})).room;await a.call(`/api/worlds/${w.id}/members/${b.user.id}`,'PUT',{role:'editor',tags:['durable']});await a.call(`/api/rooms/${r.id}`,'DELETE');const cookie=a.cookie;await f.app.close();f=await fixture(database);t.after(()=>f.app.close());a=f.client();a.cookie=cookie;assert.equal((await a.call(`/api/universes/${u.id}`)).data.universe.name,'Durable');assert.deepEqual((await a.call(`/api/worlds/${w.id}/members`)).data.members.find(m=>m.userId===b.user.id).tags,['durable']);assert.equal((await a.call('/api/universes?includeArchived=1')).data.universes.find(x=>x.id===u.id).worlds[0].rooms[0].archivedAt>0,true);assert.equal((await a.call(`/api/rooms/${r.id}/restore`,'POST',{})).status,200);assert.equal((await a.call(`/api/rooms/${r.id}`)).data.room.scene.version,1);});

test('Scoped account lookup cannot enumerate registered identities without management authority',async t=>{const{owner,member}=await setup(t);const w=(await owner.call('/api/worlds')).data.worlds[0];assert.equal((await member.call(`/api/accounts?worldId=${w.id}&query=account`)).status,403);assert.equal((await owner.call('/api/accounts?query=account')).status,400);assert.equal((await owner.call(`/api/accounts?worldId=${w.id}`)).status,400);const result=await owner.call(`/api/accounts?worldId=${w.id}&query=account`);assert.equal(result.status,200);assert.equal(result.data.users.length,3);});

test('Participant DM history remains readable after public room leave, new send needs shared scope',async t=>{const{owner,member,other}=await setup(t);await owner.call('/api/rooms/commons/join','POST',{});await member.call('/api/rooms/commons/join','POST',{});assert.equal((await owner.call(`/api/dm/${member.user.id}/messages`,'POST',{text:'Keep our conversation'})).status,201);await member.call('/api/rooms/commons/leave','POST',{});const history=await member.call(`/api/dm/${owner.user.id}/messages`);assert.equal(history.status,200);assert.equal(history.data.messages[0].text,'Keep our conversation');assert.equal((await member.call(`/api/dm/${owner.user.id}/messages`,'POST',{text:'No current scope'})).status,403);assert.equal((await other.call(`/api/dm/${owner.user.id}/messages`)).status,403);});

test('Room grant cannot restore or leak private ancestor data after parent privacy changes',async t=>{const{owner,member}=await setup(t);const w=(await create(owner,'/api/worlds',{name:'Grant restore'})).world;const r=(await create(owner,'/api/rooms',{worldId:w.id,name:'Grant room'})).room;await owner.call(`/api/rooms/${r.id}/members/${member.user.id}`,'PUT',{role:'editor'});await owner.call(`/api/rooms/${r.id}`,'DELETE');await owner.call(`/api/worlds/${w.id}`,'PATCH',{public:false});assert.equal((await member.call(`/api/rooms/${r.id}/restore`,'POST',{})).status,404);assert.equal((await member.call('/api/universes?includeArchived=1')).data.universes.flatMap(u=>u.worlds).some(x=>x.id===w.id),false);});
