import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds} from '../src/worlds.js';
async function fixture(t){const app=createGameServer({seeds:seedWorlds});const{port}=await app.listen(0);t.after(()=>app.close());const client=()=>({cookie:'',async call(path,method='GET',body){const r=await fetch(`http://127.0.0.1:${port}${path}`,{method,headers:{Cookie:this.cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,data:await r.json()};}});const owner=client(),editor=client();owner.user=(await owner.call('/api/session','POST',{name:'Owner'})).data.user;editor.user=(await editor.call('/api/session','POST',{name:'Editor'})).data.user;const world=(await owner.call('/api/worlds','POST',{name:'Pending upload',public:false})).data.world;const room=(await owner.call('/api/rooms','POST',{worldId:world.id,name:'Room',public:false})).data.room;await owner.call(`/api/worlds/${world.id}/members/${editor.user.id}`,'PUT',{role:'editor'});return{app,port,owner,editor,world,room};}
function pendingUpload(port,cookie,roomId){let request;const result=new Promise((resolve,reject)=>{request=http.request({host:'127.0.0.1',port,path:`/api/rooms/${roomId}/files`,method:'POST',headers:{Cookie:cookie,'Content-Type':'application/octet-stream','X-File-Name':'pending.txt','X-File-Type':'text/plain','Transfer-Encoding':'chunked'}},res=>{let raw='';res.on('data',b=>raw+=b);res.on('end',()=>resolve({status:res.statusCode,data:JSON.parse(raw)}));});request.on('error',reject);request.write('pending ');});return{request,result};}

for(const action of ['member-revoke','ancestor-archive'])test(`In-flight upload cannot commit after ${action}`,async t=>{const f=await fixture(t);let observed;const admitted=new Promise(resolve=>observed=resolve),authorize=f.app.store.authorize.bind(f.app.store);f.app.store.authorize=(roomId,userId,roles)=>{const r=authorize(roomId,userId,roles);if(userId===f.editor.user.id&&roles?.includes('editor'))observed();return r;};const upload=pendingUpload(f.port,f.editor.cookie,f.room.id);await admitted;const r=action==='member-revoke'?await f.owner.call(`/api/worlds/${f.world.id}/members/${f.editor.user.id}`,'DELETE'):await f.owner.call(`/api/worlds/${f.world.id}`,'DELETE',{metadataRevision:0});assert.equal(r.status,200);upload.request.end('bytes');assert.equal((await upload.result).status,404);assert.equal(f.app.store.get('SELECT COUNT(*) AS n FROM room_files WHERE room_id=?',f.room.id).n,0);});

test('Stale archive retry cannot rearchive a newly restored stable ID when using metadata CAS',async t=>{const{owner,world}=await fixture(t);assert.equal((await owner.call(`/api/worlds/${world.id}`,'DELETE',{metadataRevision:0})).status,200);assert.equal((await owner.call(`/api/worlds/${world.id}/restore`,'POST',{metadataRevision:1})).status,200);assert.equal((await owner.call(`/api/worlds/${world.id}`,'DELETE',{metadataRevision:0})).status,409);const latest=(await owner.call(`/api/worlds/${world.id}`)).data.world;assert.equal(latest.id,world.id);assert.equal(latest.archivedAt,null);assert.equal(latest.metadataRevision,2);});
