/** Actual-game image setup acceptance. Run serially under the shared GPU flock.
 * All claimed UI flows use native mouse/keyboard/file chooser/CDP touch input.
 * evaluate() only reads state, projections, DOM and rendered-frame diagnostics.
 * The separate local owner is an HTTP fixture for peer commits and role changes.
 */
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {inflateSync} from 'node:zlib';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds,emptyScene} from '../src/worlds.js';
import {resolveImagePlacement} from '../src/image-asset-geometry.js';
import {makePng} from '../fixtures/png-fixtures.mjs';

const out=process.env.UNIVERSE_IMAGE_SETUP_EVIDENCE||'evidence/image-setup-version-full';
const dist=process.env.UNIVERSE_IMAGE_SETUP_DIST||new URL('../dist',import.meta.url).pathname;
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
await mkdir(out,{recursive:true});
const app=createGameServer({seeds:structuredClone(seedWorlds),dist}),address=await app.listen(0),base=`http://127.0.0.1:${address.port}`;
const browser=await launch();
let context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage(),roomId,assetId,ownerCookie='',cdp;
const checks=[],errors=[],mutations=[],events=[],fixtures=[];
const results={startedAt:new Date().toISOString(),sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sourceTree:execFileSync('git',['rev-parse','HEAD^{tree}'],{encoding:'utf8'}).trim(),testSha256:sha(await readFile(new URL(import.meta.url))),bundleSha256:sha(await readFile(dist+'/main.js')),checks,errors,mutations,events,fixtures,limits:[
 'Disposable loopback server, local accounts and synthetic 128×64 PNG; no external media, real provider, credentials or deployment',
 'Native browser mouse, keyboard, file chooser and CDP touch; browser evaluation is read-only diagnostic access',
 'A separately authenticated owner arranges room, membership and concurrent version fixtures through HTTP',
 'SQLite and pure geometry checks are model evidence; separate screenshot pixels, native picking and keyboard walking establish actual renderer/input behavior',
 'Headless Chromium SwiftShader and emulated 320px touch are not physical-device performance evidence'
]};
const state=()=>page.evaluate(()=>window.__universe.getState());
const editor=()=>page.evaluate(()=>window.__universe.getEditor());
const root=()=>page.locator('#image-library');
const setup=()=>root().locator('.uil-setup');
const button=(name,scope=root())=>scope.getByRole('button',{name,exact:true});
const assetPath=()=>`/api/rooms/${roomId}/assets/${assetId}`;
const ref=entry=>({assetId:entry.definition.assetId,versionId:entry.version.versionId});
const persist=()=>writeFile(out+'/results.json',JSON.stringify(results,null,2));
const report=async(name,details={})=>{checks.push({name,status:'passed',...details});console.log('PASS',name);await persist();};
const near=(actual,expected,tolerance=.08)=>assert(Math.abs(actual-expected)<tolerance,`${actual} should be within ${tolerance} of ${expected}`);
async function owner(path,method='GET',body){
 const response=await fetch(base+path,{method,headers:{Cookie:ownerCookie,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 if(response.headers.get('set-cookie'))ownerCookie=response.headers.get('set-cookie').split(';')[0];
 const result=await response.json();fixtures.push({path,method,status:response.status});
 assert(response.ok,JSON.stringify({path,status:response.status,result}));return result;
}
async function observe(){
 page.setDefaultTimeout(20000);
 page.on('pageerror',error=>errors.push(error.message));
 page.on('request',request=>{const path=new URL(request.url()).pathname;if(['POST','PATCH'].includes(request.method())&&path.includes('/assets'))mutations.push({method:request.method(),path,body:JSON.parse(request.postData())});});
 cdp=await context.newCDPSession(page);await cdp.send('Network.enable');
 cdp.on('Network.eventSourceMessageReceived',event=>{if(event.eventName==='image-assets')events.push(JSON.parse(event.data));});
}
async function frames(count=3){const start=await page.evaluate(()=>window.__universe.getStats().presentation.drawnFrames);await page.waitForFunction(n=>window.__universe.getStats().presentation.drawnFrames>=n,start+count,{timeout:30000});}
async function ready(){await page.waitForFunction(()=>window.__universe?.getState().ready,{},{timeout:60000});await frames();}
async function build(){if(!await page.locator('#editor').isVisible())await page.locator('#dock-build').click();}
async function openLibrary(){if(!await root().isVisible()){await build();await page.getByRole('button',{name:'Custom images',exact:true}).click();}await root().waitFor({state:'visible'});await libraryReady();}
async function libraryReady(){await page.waitForFunction(()=>document.querySelector('#image-library .uil-cards')?.getAttribute('aria-busy')!=='true');}
async function closeLibrary(){await button('Close Custom image library').click();await root().waitFor({state:'hidden'});await frames();}
async function openSetup(name){await openLibrary();await button('Edit setup for '+name).click();await setup().waitFor({state:'visible'});}
async function list(status='active'){const response=await page.request.get(base+`/api/rooms/${roomId}/assets?status=${status}`);assert.equal(response.status(),200);return(await response.json()).entries;}
async function current(status='active'){const entry=(await list(status)).find(e=>e.definition.assetId===assetId);assert(entry,'fixture asset remains discoverable');return entry;}
async function room(){const response=await page.request.get(base+`/api/rooms/${roomId}`);assert.equal(response.status(),200);return(await response.json()).room;}
async function choose(name,version){await openLibrary();const place=root().getByRole('button',{name:`Place ${name} (${assetId})`,exact:true});assert.equal(await place.innerText(),`Place ${name} · version ${version}`);await place.click();await root().waitFor({state:'hidden'});await page.waitForFunction(()=>window.__universe.getEditor().tool==='image');}
async function projected(x,z,y=0){
 await page.waitForFunction(()=>{const f=window.__universe.getCamera().framing;return f.status==='manual'||!f.targetOffset||Math.hypot(f.offset.x-f.targetOffset.x,f.offset.y-f.targetOffset.y)<1;});
 const point=await page.evaluate(p=>window.__universe.getScreenPoint(p.x,p.z,p.y),{x,z,y});assert(point?.visible,`visible world point ${x},${z},${y}`);
 assert.equal(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id,point),'game','world point reaches the actual canvas');return point;
}
async function clickWorld(x,z,y=0){const point=await projected(x,z,y);await page.mouse.click(point.x,point.y);return point;}
async function preview(x,z){const point=await projected(x,z);await page.mouse.move(point.x,point.y);await frames();const value=(await editor()).preview;assert.equal(value?.type,'image');assert.equal(value.valid,true,value.reason);return{point,value};}
async function place(x,z,expectedRef){const before=(await state()).scene.objects.length,{point,value}=await preview(x,z);assert.deepEqual(value.assetRef,expectedRef);await page.mouse.click(point.x,point.y);await page.waitForFunction(n=>window.__universe.getState().scene.objects.length===n,before+1);const valuePlaced=(await state()).scene.objects.at(-1);assert.deepEqual(valuePlaced.assetRef,expectedRef);return valuePlaced;}
async function select(){await page.getByRole('button',{name:'↖ Select',exact:true}).click();}
async function save(){await page.getByRole('button',{name:'Save room',exact:true}).click();await page.waitForFunction(()=>!window.__universe.getEditor().dirty&&!window.__universe.getEditor().saving);return(await state()).scene;}
async function untouched(scene,revision){assert.deepEqual((await state()).scene,scene);assert.equal((await room()).revision,revision);assert.equal((await editor()).dirty,false);}
async function bytesFor(entry,bytes){const response=await page.request.get(base+assetPath()+`/versions/${entry.version.versionId}/image`);assert.equal(response.status(),200);assert.deepEqual(await response.body(),bytes);assert.equal(entry.version.sha256,sha(bytes));}
function rows(){return app.store.all('SELECT version_id,sequence,version_json,sha256,byte_length,bytes FROM room_image_asset_versions WHERE room_id=? AND asset_id=? ORDER BY sequence',roomId,assetId);}
function snapshotRows(){return rows().map(row=>({...row,bytes:Buffer.from(row.bytes).toString('base64')}));}
function decodeScreenshot(bytes){
 let off=8,width,height,channels,parts=[];
 while(off<bytes.length){const length=bytes.readUInt32BE(off),type=bytes.toString('ascii',off+4,off+8),data=bytes.subarray(off+8,off+8+length);if(type==='IHDR'){width=data.readUInt32BE(0);height=data.readUInt32BE(4);channels=data[9]===6?4:data[9]===2?3:0;assert(channels&&data[8]===8);}if(type==='IDAT')parts.push(data);off+=length+12;}
 const raw=inflateSync(Buffer.concat(parts)),pixels=Buffer.alloc(width*height*channels),paeth=(a,b,c)=>{const p=a+b-c;return Math.abs(p-a)<=Math.abs(p-b)&&Math.abs(p-a)<=Math.abs(p-c)?a:Math.abs(p-b)<=Math.abs(p-c)?b:c;};
 for(let y=0;y<height;y++){const filter=raw[y*(width*channels+1)];for(let x=0;x<width*channels;x++){const i=y*width*channels+x,a=x>=channels?pixels[i-channels]:0,b=y?pixels[i-width*channels]:0,c=y&&x>=channels?pixels[i-width*channels-channels]:0;pixels[i]=(raw[y*(width*channels+1)+1+x]+[0,a,b,Math.floor((a+b)/2),paeth(a,b,c)][filter])&255;}}
 return{rgb(x,y){const i=(Math.round(y)*width+Math.round(x))*channels;return[...pixels.subarray(i,i+3)];}};
}
async function pink(name,x,z,y=.05){
 await page.locator('#image-render-status').waitFor({state:'hidden'});await frames(4);const point=await projected(x,z,y),pixels=decodeScreenshot(await page.screenshot({path:out+'/'+name+'.png'})),rgb=pixels.rgb(point.x,point.y);
 assert(rgb[0]>180&&rgb[1]<110&&rgb[2]>150,`actual rendered pink pixel at ${JSON.stringify(point)}: ${rgb}`);return{point,rgb};
}
async function configure(preset,pivotValue,grid){
 await setup().getByRole('combobox',{name:'Representation and depth',exact:true}).selectOption(preset);
 if(preset==='custom')await setup().getByRole('spinbutton',{name:'Custom ground pivot',exact:true}).fill(String(pivotValue));
 const checkbox=setup().getByRole('checkbox',{name:'Paint collision cells',exact:true});await checkbox.setChecked(!!grid);
 if(grid)for(let row=0;row<grid.length;row++)for(let col=0;col<grid[row].length;col++){const cell=button(`Collision row ${row+1}, column ${col+1}`,setup());if((await cell.getAttribute('aria-pressed'))!==String(!!grid[row][col]))await cell.click();}
}
async function setupValues(){return{depth:await setup().getByRole('combobox',{name:'Representation and depth',exact:true}).inputValue(),pivot:await setup().getByRole('spinbutton',{name:'Custom ground pivot',exact:true}).inputValue(),grid:await setup().getByRole('group',{name:'Setup collision cells',exact:true}).getByRole('button').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('aria-pressed')))};}
async function saveVersion(sequence){const count=mutations.length;await button('Save new version',setup()).click();await setup().waitFor({state:'hidden'});await libraryReady();const entry=await current();assert.equal(entry.version.sequence,sequence);assert.equal(mutations.length,count+1);return entry;}
async function peerVersion(baseEntry,setupValue){return owner(assetPath()+'/versions','POST',{operationId:'peer-'+randomUUID(),expectedRevision:baseEntry.revision,expectedVersionId:baseEntry.version.versionId,setup:setupValue});}
async function mobileLibrary(){const custom=page.getByRole('button',{name:'Custom images',exact:true});if(!await custom.isVisible())await touch(page.getByRole('button',{name:'More build tools',exact:true}));await touch(custom);}
async function touch(locator){await locator.scrollIntoViewIfNeeded();const box=await locator.boundingBox();assert(box&&box.x>=0&&box.x+box.width<=320.5&&box.y>=0&&box.y+box.height<=760.5,`touch target in viewport: ${JSON.stringify(box)}`);const point={x:box.x+box.width/2,y:box.y+box.height/2};assert(await locator.evaluate((node,p)=>node===document.elementFromPoint(p.x,p.y)||node.contains(document.elementFromPoint(p.x,p.y)),point));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...point,id:1,radiusX:2,radiusY:2,force:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}

try{
 await observe();
 await owner('/api/session','POST',{name:'Setup version peer owner'});
 const universe=(await owner('/api/universes','POST',{name:'Local setup version acceptance'})).universe;
 const world=(await owner('/api/worlds','POST',{universeId:universe.id,name:'Setup version world'})).world;
 const roomName='Setup version court';
 const created=(await owner('/api/rooms','POST',{worldId:world.id,name:roomName,scene:{...emptyScene(),bounds:{width:12,depth:18},spawn:{x:0,z:4}}})).room;roomId=created.id;
 await owner(`/api/rooms/${roomId}/join`,'POST',{});
 await page.goto(base,{waitUntil:'domcontentloaded',timeout:60000});await page.getByPlaceholder('Your name').fill('Setup native editor');await page.locator('#join-button').click();await ready();
 const userId=(await state()).user.id;await owner(`/api/rooms/${roomId}/members/${userId}`,'PUT',{role:'editor'});
 await page.locator('#dock-explore').click();await page.getByRole('button',{name:'View room '+roomName,exact:true}).click();await page.getByRole('button',{name:'Enter '+roomName,exact:true}).click();await page.waitForFunction(id=>window.__universe.getState().room.id===id,roomId);await page.locator('#places').waitFor({state:'hidden'});
 await openLibrary();const name='Setup pink panel',bytes=makePng({width:128,height:64,pixel:(x,y)=>[245,35,225,x<32&&y>=32?0:255]});
 await button('Add PNG').click();await button('Cancel draft').click();assert.equal(mutations.length,0,'Cancel never uploads');
 await button('Add PNG').click();const chooser=page.waitForEvent('filechooser');await button('Choose PNG').click();await(await chooser).setFiles({name:name+'.png',mimeType:'image/png',buffer:bytes});await root().getByAltText('Local image preview').waitFor();
 await root().getByRole('textbox',{name:'Name',exact:true}).fill(name);await root().getByRole('combobox',{name:'Representation and depth',exact:true}).selectOption('floor');await root().getByRole('checkbox',{name:'Floating placement',exact:true}).uncheck();await root().getByRole('checkbox',{name:'Paint collision cells',exact:true}).check();for(let col=1;col<=4;col++)await button(`Collision row 1, column ${col}`).click();
 const sceneBefore=(await state()).scene;await button('Upload').click();await root().getByRole('button',{name:/^Place Setup pink panel/}).waitFor();const v1=(await list())[0];assetId=v1.definition.assetId;
 assert.deepEqual((await state()).scene,sceneBefore);assert.equal(v1.version.sequence,1);assert.deepEqual(v1.version.collisionGrid,[[1,1,1,1],[0,0,0,0]]);await bytesFor(v1,bytes);
 await choose(name,1);const old=await place(0,0,ref(v1));await select();const pinned=await save(),revision=(await room()).revision,immutableV1=snapshotRows()[0];
 const oldPixels=await pink('01-v1-floor',0,-.5);await clickWorld(0,-.5,.05);assert.equal((await editor()).selected,old.id);await clickWorld(-1.5,.5,.05);assert.equal((await editor()).selected,null,'transparent floor quadrant passes through to ground');
 await report('Native PNG chooser, Cancel, upload, painted floor collision, placement, rendered pixel, alpha picking and Save establish immutable v1',{assetId,versionId:v1.version.versionId,oldPixels});

 await choose(name,1);assert.deepEqual((await preview(0,-4)).value.assetRef,ref(v1));await openSetup(name);assert.equal(await button('Save new version',setup()).isDisabled(),true,'unchanged source setup cannot publish');assert.match(await setup().innerText(),/Source version 1/);assert.match(await setup().innerText(),/Existing objects and an already selected placement keep their original setup/);
 await configure('custom',.25,[[0,0,0,0],[1,1,1,1]]);assert.equal(await button('Save new version',setup()).isEnabled(),true);const draft=await setupValues(),beforeDraft=mutations.length;
 const pivot=setup().getByRole('spinbutton',{name:'Custom ground pivot',exact:true});await pivot.press('r');await pivot.press('d');assert.equal((await editor()).tool,'image');assert.equal((await editor()).rotation,0,'typing R cannot rotate the queued image');await untouched(pinned,revision);
 const firstCell=button('Collision row 1, column 1',setup());await firstCell.focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Collision row 1, column 2');await page.keyboard.press('Space');await page.keyboard.press('Space');assert.deepEqual(await setupValues(),draft);
 await button('Back to library',setup()).click();await setup().waitFor({state:'hidden'});await openSetup(name);assert.deepEqual(await setupValues(),draft);await closeLibrary();await openLibrary();assert(await setup().isVisible());assert.deepEqual(await setupValues(),draft);await page.goBack();await root().waitFor({state:'hidden'});await openLibrary();assert(await setup().isVisible());assert.deepEqual(await setupValues(),draft);assert.equal(mutations.length,beforeDraft);
 const v2=await saveVersion(2);await untouched(pinned,revision);assert.deepEqual(snapshotRows()[0],immutableV1);assert.equal(v2.version.depthPreset,'custom');assert.equal(v2.version.depthPivot,.25);assert.deepEqual(v2.version.collisionGrid,[[0,0,0,0],[1,1,1,1]]);assert.equal(v2.version.floating,v1.version.floating);await bytesFor(v2,bytes);
 await closeLibrary();assert.deepEqual((await preview(0,-4)).value.assetRef,ref(v1),'queued placement still targets v1 after v2 publication');await untouched(pinned,revision);
 await choose(name,2);const fresh=await place(0,-4,ref(v2));await select();const paired=await save(),pairedRevision=(await room()).revision;
 const newPixels=await pink('02-v2-upright',0,-4.5,1.2);await clickWorld(0,-4.5,1.2);assert.equal((await editor()).selected,fresh.id);await clickWorld(-1.5,-4.5,.5);assert.equal((await editor()).selected,null,'transparent upright quadrant passes through to ground');const oldStillPixels=await pink('03-v1-stays-floor',0,-.5);await clickWorld(0,-.5,.05);assert.equal((await editor()).selected,old.id);
 const oldGeometry=resolveImagePlacement(v1,old),newGeometry=resolveImagePlacement(v2,fresh);assert.equal(oldGeometry.render.representation,'floor');assert.equal(newGeometry.render.representation,'upright');assert(oldGeometry.render.worldCorners.every(p=>p.y===.05));assert(newGeometry.render.worldCorners.every(p=>p.z===-4.5));assert.deepEqual(oldGeometry.collisionCells.map(c=>[c.row,c.col,c.minZ,c.maxZ]),[0,1,2,3].map(col=>[0,col,-1,0]));assert.deepEqual(newGeometry.collisionCells.map(c=>[c.row,c.col,c.minZ,c.maxZ]),[0,1,2,3].map(col=>[1,col,-4,-3]));
 await report('Explicit version-labelled Place is required: saving v2 leaves the scene/revision/ref and queued v1 ghost unchanged; old floor and new upright both render and pick their pinned PNG',{newPixels,oldStillPixels,modelGeometry:{old:oldGeometry,new:newGeometry}});

 await page.getByRole('button',{name:'Close editor',exact:true}).click();await page.locator('#editor').waitFor({state:'hidden'});await frames();await page.locator('#game').focus();const beforeWalk=(await state()).position,cameraYaw=await page.evaluate(()=>window.__universe.getCamera().yaw);near(cameraYaw,Math.PI/4,.001);await page.keyboard.down('Shift');await page.keyboard.down('w');await page.keyboard.down('a');await page.waitForFunction(()=>window.__universe.getState().position.z<.4);await frames(12);const stoppedOld=(await state()).position;await frames(12);const stoppedOldAgain=(await state()).position;await page.keyboard.up('w');await page.keyboard.up('a');await page.keyboard.up('Shift');assert(stoppedOld.z>.28&&stoppedOld.z<.4);near(stoppedOldAgain.z,stoppedOld.z,.04);assert(beforeWalk.z-stoppedOld.z>2,'native W+A demonstrably advances world -Z');near(stoppedOld.x,beforeWalk.x,.15);
 await clickWorld(3,-2);await page.waitForFunction(()=>{const p=window.__universe.getState().position;return Math.hypot(p.x-3,p.z+2)<.2;});await clickWorld(0,-2);await page.waitForFunction(()=>{const p=window.__universe.getState().position;return Math.hypot(p.x,p.z+2)<.2;});await page.locator('#game').focus();await page.keyboard.down('Shift');await page.keyboard.down('w');await page.keyboard.down('a');await page.waitForFunction(()=>window.__universe.getState().position.z<-2.6);await frames(12);const stoppedNew=(await state()).position;await frames(12);const stoppedNewAgain=(await state()).position;await page.keyboard.up('w');await page.keyboard.up('a');await page.keyboard.up('Shift');assert(stoppedNew.z>-2.72&&stoppedNew.z<-2.6);near(stoppedNewAgain.z,stoppedNew.z,.04);await page.screenshot({path:out+'/04-actual-collision-stops.png'});await report('Actual native W+A walking crosses clear cells and stops at each version’s different painted row',{cameraYaw,input:'Shift+W+A',beforeWalk,stoppedOld,stoppedOldAgain,stoppedNew,stoppedNewAgain});await clickWorld(0,4);await page.waitForFunction(()=>{const p=window.__universe.getState().position;return Math.hypot(p.x,p.z-4)<.2;});
 await page.reload();await ready();assert.deepEqual((await state()).scene,paired);await build();await select();await pink('05-reloaded-floor',0,-.5);await pink('06-reloaded-upright',0,-4.5,1.2);await bytesFor(v1,bytes);await bytesFor(v2,bytes);
 await report('Save/reload retains both exact refs, rendered planes and authenticated PNG bytes');

 await openSetup(name);await configure('custom',.6,[[1,0,0,0],[0,0,0,0]]);const staleDraft=await setupValues(),beforePeer=mutations.length;
 let releaseStale,seenStale;const staleGate=new Promise(resolve=>{releaseStale=resolve;}),staleReady=new Promise(resolve=>{seenStale=resolve;});await page.route('**'+assetPath()+'/versions',async route=>{seenStale();await staleGate;await route.continue();},{times:1});const staleResponse=page.waitForResponse(response=>new URL(response.url()).pathname===assetPath()+'/versions'&&response.request().method()==='POST');await button('Save new version',setup()).click();await staleReady;const v3=(await peerVersion(v2,{depthPreset:'standing',depthPivot:1,collisionGrid:[[0,1,0,0],[0,0,0,0]]})).entry;releaseStale();assert.equal((await staleResponse).status(),409);
 await button('Review latest version',setup()).waitFor();assert.equal(await button('Save new version',setup()).isDisabled(),true);assert.match(await setup().innerText(),/changed[\s\S]*draft[\s\S]*preserved[\s\S]*Review/i);assert.deepEqual(await setupValues(),staleDraft);assert.equal(mutations.length,beforePeer+1);assert.equal(mutations.at(-1).body.expectedVersionId,v2.version.versionId);
 await pivot.press('Enter');await frames();assert.equal(mutations.length,beforePeer+1,'stale Enter cannot silently resubmit');await button('Review latest version',setup()).click();await page.waitForFunction(()=>document.querySelector('.uil-setup')?.textContent.includes('Reviewed version 3'));assert.deepEqual(await setupValues(),staleDraft);await configure('standing',1,v3.version.collisionGrid);assert.equal(await button('Save new version',setup()).isDisabled(),true,'normalizing to the reviewed current version cannot publish a duplicate');await configure('custom',.6,[[1,0,0,0],[0,0,0,0]]);assert.deepEqual(await setupValues(),staleDraft);assert.equal(await button('Save new version',setup()).isEnabled(),true);const v4=await saveVersion(4);await untouched(paired,pairedRevision);assert.equal(v4.version.depthPivot,.6);await report('A separately authenticated peer v3 makes a held native Save stale; its real409 preserves the draft and explicit Review latest version preserves input and permits deliberate v4 publication without changing placements');

 await openSetup(name);await configure('custom',.75,[[0,0,1,0],[0,0,0,0]]);let receipt,releaseLost;
 const lostReady=new Promise(resolve=>{releaseLost=resolve;});const postPath=assetPath()+'/versions';
 await page.route('**'+postPath,async route=>{if(route.request().method()!=='POST')return route.continue();const response=await route.fetch();assert.equal(response.status(),201);receipt=await response.json();await route.abort('failed');releaseLost();},{times:1});
 const beforeLost=mutations.length;await button('Save new version',setup()).click();await lostReady;await button('Check version save status',setup()).waitFor();assert.equal(receipt.published.sequence,5);const publishedV5=receipt.entry,submitted=mutations.at(-1);assert.equal(mutations.length,beforeLost+1);assert.equal(await button('Save new version',setup()).isDisabled(),true);const pendingDraft=await setupValues();
 await button('Back to library',setup()).click();await openSetup(name);assert.deepEqual(await setupValues(),pendingDraft);await closeLibrary();await openLibrary();assert.deepEqual(await setupValues(),pendingDraft);assert(await button('Check version save status',setup()).isVisible());
 const v6=(await peerVersion(publishedV5,{depthPreset:'standing',depthPivot:1,collisionGrid:[[0,0,0,1],[0,0,0,0]]})).entry;const sixRows=snapshotRows();await button('Check version save status',setup()).click();await setup().waitFor({state:'hidden'});await libraryReady();assert.match(await root().innerText(),/Saved version 5/);assert.match(await root().innerText(),/library now displays version 6/);assert.match(await root().innerText(),/Version 6 · library revision 6/);assert.equal((await current()).version.versionId,v6.version.versionId);assert.equal(mutations.length,beforeLost+1);assert.deepEqual(snapshotRows(),sixRows);await untouched(paired,pairedRevision);
 const reconciled=await page.request.get(base+assetPath()+'/versions/operations/'+submitted.body.operationId);assert.equal(reconciled.status(),200);const reconciledBody=await reconciled.json();assert.deepEqual(reconciledBody.published,receipt.published);assert.equal(reconciledBody.entry.version.versionId,v6.version.versionId);assert.equal(events.filter(event=>event.versionId===publishedV5.version.versionId).length,1,'lost response publishes exactly one version event');for(const row of rows())assert.deepEqual(Buffer.from(row.bytes),bytes);
 await page.screenshot({path:out+'/07-reconciled-v5-current-v6.png'});await report('Lost successful v5 response survives Back/Close/reopen; reconciliation names published v5 while displaying newer peer v6, with no duplicate request/version/bytes/event or auto-placement',{published:receipt.published,current:ref(v6),versions:rows().length});

 await openSetup(name);await configure('custom',.4,[[0,1,0,0],[1,0,0,0]]);const roleDraft=await setupValues(),beforeRole=snapshotRows(),roleMutations=mutations.length;
 await owner(`/api/rooms/${roomId}/members/${userId}`,'PUT',{role:'member'});await page.waitForFunction(()=>window.__universe.getState().room.role==='member');assert.deepEqual(snapshotRows(),beforeRole);assert.equal(mutations.length,roleMutations);
 if(await setup().isVisible()){assert.equal(await button('Save new version',setup()).isDisabled(),true);assert.deepEqual(await setupValues(),roleDraft);}
 await owner(`/api/rooms/${roomId}/members/${userId}`,'PUT',{role:'editor'});await page.waitForFunction(()=>window.__universe.getState().room.role==='editor');await openLibrary();if(!await setup().isVisible())await openSetup(name);assert.deepEqual(await setupValues(),roleDraft);assert.equal(await button('Save new version',setup()).isDisabled(),true);await button('Review latest version',setup()).click();await page.waitForFunction(()=>!document.querySelector('.uil-setup button[type=submit]').disabled);assert.deepEqual(await setupValues(),roleDraft);await button('Back to library',setup()).click();assert.deepEqual(snapshotRows(),beforeRole);await report('Role downgrade prevents publication; restored editor recovers the original draft and must explicitly review current authority before Save');

 await button('Archive '+name).click();await button('Cancel archive').click();assert.equal((await current()).status,'active');await button('Archive '+name).click();await button('Confirm archive').click();await page.waitForFunction(()=>!document.querySelector('#image-library .uil-card'));await root().getByRole('combobox',{name:'Library status',exact:true}).selectOption('archived');await libraryReady();const archived=await current('archived');assert.equal(await root().getByRole('button',{name:/^Place /}).count(),0);await button('Edit setup for '+name).click();await setup().waitFor({state:'visible'});assert.equal(await button('Save new version',setup()).isDisabled(),true);await button('Review latest version',setup()).click();await page.waitForFunction(()=>document.querySelector('.uil-setup')?.textContent.includes('This image is archived'));assert.equal(await button('Save new version',setup()).isDisabled(),true);assert.equal(rows().length,6);await button('Back to library',setup()).click();await closeLibrary();await pink('08-archived-floor',0,-.5);await pink('09-archived-upright',0,-4.5,1.2);await bytesFor(v1,bytes);await bytesFor(v2,bytes);await untouched(paired,pairedRevision);await openLibrary();await button('Restore '+name).click();await root().getByRole('combobox',{name:'Library status',exact:true}).selectOption('active');await libraryReady();assert.equal((await current()).version.versionId,v6.version.versionId);await closeLibrary();
 await report('Archive Cancel does not publish; archive blocks setup publication and removes new-placement controls while pinned floor/upright visuals and exact bytes remain, and restore keeps current v6',{archivedRevision:archived.revision});

 const desktopContext=context,storage=await context.storageState();await desktopContext.close();context=await browser.newContext({viewport:{width:320,height:760},isMobile:true,hasTouch:true,deviceScaleFactor:1,storageState:storage});page=await context.newPage();await observe();await page.goto(base,{waitUntil:'domcontentloaded',timeout:60000});await ready();assert.deepEqual((await state()).scene,paired);
 await touch(page.locator('#dock-build'));await mobileLibrary();await root().waitFor({state:'visible'});await libraryReady();await touch(button('Edit setup for '+name));await setup().waitFor({state:'visible'});
 const metrics=await setup().evaluate(node=>{const r=node.getBoundingClientRect();return{width:innerWidth,document:document.documentElement.scrollWidth,client:node.clientWidth,scroll:node.scrollWidth,left:r.left,right:r.right,controls:[...node.querySelectorAll('button,input,select')].filter(n=>n.getClientRects().length).map(n=>{const target=n.matches('input[type=checkbox]')?n.closest('label'):n,b=target.getBoundingClientRect();return{label:n.getAttribute('aria-label')||n.textContent,target:n.matches('input[type=checkbox]')?'associated native label':'control',width:b.width,height:b.height,left:b.left,right:b.right};})};});assert.equal(metrics.width,320);assert.equal(metrics.document,320);assert.equal(metrics.scroll,metrics.client);for(const control of metrics.controls){assert(control.height>=44,control.label+' target at least44px');assert(control.left>=metrics.left-.5&&control.right<=metrics.right+.5,control.label+' stays in setup bounds');}
 await setup().getByRole('combobox',{name:'Representation and depth',exact:true}).selectOption('custom');const mobilePivot=setup().getByRole('spinbutton',{name:'Custom ground pivot',exact:true});await mobilePivot.fill('.35');await mobilePivot.press('r');await mobilePivot.press('d');await mobilePivot.press('Tab');assert.equal(await root().evaluate(node=>node.contains(document.activeElement)),true,'Tab stays in setup controls instead of moving focus into world input');assert.deepEqual((await state()).scene,paired);assert.equal((await editor()).tool,'select');assert.equal((await editor()).rotation,0,'typing R cannot rotate placement');
 const mobileCell=button('Collision row 1, column 1',setup());await touch(mobileCell);const mobileDraft=await setupValues(),mobileMutationCount=mutations.length;await touch(button('Back to library',setup()));await touch(button('Edit setup for '+name));assert.deepEqual(await setupValues(),mobileDraft);await touch(button('Close Custom image library'));await root().waitFor({state:'hidden'});await mobileLibrary();await setup().waitFor({state:'visible'});assert.deepEqual(await setupValues(),mobileDraft);assert.equal(mutations.length,mobileMutationCount);await page.screenshot({path:out+'/10-mobile320-setup.png'});
 await touch(button('Save new version',setup()));await setup().waitFor({state:'hidden'});await libraryReady();const v7=await current();assert.equal(v7.version.sequence,7);assert.equal(v7.version.depthPivot,.35);await untouched(paired,pairedRevision);const mobilePlace=button(`Place ${name} (${assetId})`);assert.equal(await mobilePlace.innerText(),`Place ${name} · version 7`);await touch(mobilePlace);await root().waitFor({state:'hidden'});
 let mobilePoint,mobileTarget;for(const target of [{x:0,z:4},{x:0,z:6},{x:-3,z:4},{x:3,z:5},{x:0,z:7},{x:3,z:6}]){const point=await page.evaluate(p=>window.__universe.getScreenPoint(p.x,p.z,0),target);if(point?.visible&&await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id==='game',point)){mobileTarget=target;mobilePoint=await projected(target.x,target.z);break;}}assert(mobilePoint,'a valid image placement must be visible on unobscured mobile canvas');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:mobilePoint.x,y:mobilePoint.y,id:1,radiusX:2,radiusY:2,force:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>window.__universe.getState().scene.objects.length===3);const mobilePlaced=(await state()).scene.objects.at(-1);assert.deepEqual(mobilePlaced.assetRef,ref(v7));near(mobilePlaced.x,mobileTarget.x,.6);near(mobilePlaced.z,mobileTarget.z,.6);for(const oldItem of paired.objects)assert.deepEqual((await state()).scene.objects.find(item=>item.id===oldItem.id),oldItem);
 await touch(page.getByRole('button',{name:'Save room',exact:true}));await page.waitForFunction(()=>!window.__universe.getEditor().dirty&&!window.__universe.getEditor().saving);const finalScene=(await state()).scene;await page.reload();await ready();assert.deepEqual((await state()).scene,finalScene);await bytesFor(v1,bytes);await bytesFor(v2,bytes);await bytesFor(v7,bytes);await page.screenshot({path:out+'/11-mobile320-reloaded.png'});await report('After retiring desktop WebGL, actual 320px CDP touch edits/reopens/saves setup v7, explicitly places/saves/reloads it; bounded controls, collision grid, keyboard isolation and both old pins are preserved',{metrics,placed:mobilePlaced});
 assert.deepEqual(errors,[]);await report('No unhandled runtime exceptions during the complete bounded native acceptance');
}catch(error){console.error(error);checks.push({name:'Actual-game setup acceptance failure',status:'failed',error:error.stack});await page.screenshot({path:out+'/failure.png'}).catch(()=>{});await writeFile(out+'/failure-state.json',JSON.stringify({state:await state().catch(()=>null),editor:await editor().catch(()=>null),text:await page.locator('body').innerText().catch(()=>null),mutations,events},null,2));process.exitCode=1;
}finally{await persist();await context.close();await browser.close();await app.close();}
