import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {createRequire} from 'node:module';
const base = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'), require = createRequire(path.join(base, 'package.json'));
const {build} = require('esbuild'), {chromium} = require('playwright-core'), executable = (await import(require.resolve('@sparticuz/chromium'))).default;
const source = `
import {mountImageLibraryShell} from './src/image-library-shell.js';
import {normalizeImageAssetDraft} from './src/image-asset-schema.js';
const date='2026-10-02T00:00:00.000Z';
window.makeEntry=(sequence=1,revision=sequence,status='active')=>({schemaVersion:1,status,revision,metadata:{name:'Fern',description:'Library details',tags:['plant']},definition:{schemaVersion:1,assetId:'asset_a',roomId:'room_a',createdBy:'alice',createdAt:date,originKind:'upload'},version:{...normalizeImageAssetDraft({name:'Fern',floating:false,collisionGrid:[[1,0],[0,0]]},{width:64,height:64,byteLength:200,mediaType:'image/png'}),schemaVersion:1,assetId:'asset_a',roomId:'room_a',versionId:'version_'+sequence,sequence,sha256:'a'.repeat(64),createdBy:'alice',createdAt:date}});
window.sample=async()=>{const c=document.createElement('canvas');c.width=c.height=64;c.getContext('2d').fillRect(0,0,64,64);return new Uint8Array(await(await new Promise(r=>c.toBlob(r,'image/png'))).arrayBuffer())};
window.currentEntry=makeEntry();window.log={create:[],choose:[],reconcile:[],listReads:0,imageReads:0};window.mode='normal';window.receipts=new Map();
window.selected={assetId:'asset_a',versionId:'version_1'};
window.state={user:{id:'alice'},ready:true,room:{id:'room_a',role:'owner',capabilities:{canRead:true,canEditScene:true,canBuild:true},imageDefinitions:{}},scene:{objects:[{id:'old',type:'image',assetRef:{assetId:'asset_a',versionId:'version_1'}}]}};
state.room.scene=state.scene;
const transport={list:async({roomId,status='active'})=>{log.listReads++;return{entries:roomId==='room_a'&&currentEntry.status===status?[structuredClone(currentEntry)]:[]}},readImage:async()=>{log.imageReads++;return{bytes:await sample(),mediaType:'image/png'}},create:async()=>currentEntry,reconcileCreate:async()=>({status:'not-found'}),
createVersion:async args=>{log.create.push({...structuredClone({...args,signal:undefined})});
 const commit=()=>{if(args.expectedRevision!==currentEntry.revision||args.expectedVersionId!==currentEntry.version.versionId)throw Object.assign(new Error('The image changed.'),{code:'IMAGE_REVISION_CONFLICT',status:409});const e=makeEntry(currentEntry.version.sequence+1,currentEntry.revision+1);e.version={...e.version,...args.setup,representation:args.setup.depthPreset==='floor'?'floor':'upright'};currentEntry=e;const result={status:'committed',entry:structuredClone(e),published:{assetId:'asset_a',versionId:e.version.versionId,sequence:e.version.sequence}};receipts.set(args.operationId,result.published);return result;};
 if(mode==='hold')return new Promise(resolve=>window.finishSave=()=>resolve(commit()));
 if(mode==='conflict')throw Object.assign(new Error('The image changed.'),{code:'IMAGE_REVISION_CONFLICT',status:409});
 if(mode==='lost'){commit();throw new Error('Response lost');}
 if(mode==='not-sent')throw new Error('Connection interrupted');
 if(receipts.has(args.operationId))return{status:'committed',entry:structuredClone(currentEntry),published:receipts.get(args.operationId)};
 return commit();},reconcileVersion:async args=>{log.reconcile.push(args);return receipts.has(args.operationId)?{status:'committed',entry:structuredClone(currentEntry),published:receipts.get(args.operationId)}:{status:'not-found'}}};
window.shell=mountImageLibraryShell({root:document.querySelector('#library'),getState:()=>state,getRenderer:()=>({setImageContext(){},setImageStateListener(){},getImageStates:()=>[]}),transport,onChoose:ref=>{selected=ref;log.choose.push(ref);return true},onOpenChange:open=>{if(open)history.pushState({surface:'images'},'',location.href);else if(history.state?.surface==='images')history.back();}});
shell.acceptRoom();document.querySelector('#open').onclick=()=>shell.setOpen(true,{trigger:document.querySelector('#open')});window.addEventListener('popstate',()=>shell.setOpen(history.state?.surface==='images',{record:false}));
`;
const bundle = await build({stdin: {contents: source, resolveDir: base}, bundle: true, format: 'iife', write: false});
const browser = await chromium.launch({executablePath: await executable.executablePath(), headless: true, args: ['--no-sandbox', '--no-zygote', '--disable-gpu']});
const page = await browser.newPage({viewport: {width: 900, height: 800}}), errors = [];
page.on('pageerror', error => errors.push(error.message));
const html = '<!doctype html><html><body><button id="open">Open images</button><canvas id="game" tabindex="0"></canvas><section id="library"></section></body></html>';
await page.route('**/*', route => new URL(route.request().url()).hostname === 'image-setup.test' ? route.fulfill({contentType: 'text/html', body: html}) : route.abort());
const setup = page.locator('.uil-setup'), save = setup.getByRole('button', {name: 'Save new version', exact: true});
async function openSetup() {
  if (await page.locator('#library').isHidden()) await page.getByRole('button', {name: 'Open images', exact: true}).click();
  if (await setup.isHidden()) await page.getByRole('button', {name: 'Edit setup for Fern', exact: true}).click();
  await setup.getByRole('heading', {name: 'Edit image setup'}).waitFor();
}
async function chooseDepth(value) { await setup.getByLabel('Representation and depth', {exact: true}).selectOption(value); }
const pass = name => console.log('PASS', name);
try {
  await page.goto('https://image-setup.test/');
  await page.addStyleTag({content: (await Promise.all(['public/universe-tokens.css', 'src/image-library-panel.css', 'src/image-library-shell.css'].map(file => readFile(path.join(base, file), 'utf8')))).join('\n')});
  await page.addScriptTag({content: bundle.outputFiles[0].text});
  await openSetup(); assert.equal(await save.isDisabled(), true);
  await chooseDepth('floor'); assert.equal(await save.isEnabled(), true); await chooseDepth('standing'); assert.equal(await save.isDisabled(), true);
  const originalCell = setup.getByRole('button', {name: 'Collision row 1, column 1', exact: true});
  await originalCell.click(); assert.equal(await save.isEnabled(), true); await originalCell.click(); assert.equal(await save.isDisabled(), true);
  await setup.getByLabel('Paint collision cells', {exact: true}).uncheck(); assert.equal(await save.isEnabled(), true); await setup.getByLabel('Paint collision cells', {exact: true}).check(); assert.equal(await save.isDisabled(), true);
  await setup.evaluate(form => form.requestSubmit()); assert.equal(await page.evaluate(() => log.create.length), 0);
  await chooseDepth('custom'); await setup.getByLabel('Custom ground pivot', {exact: true}).fill(''); await save.click(); await setup.getByText(/must be a finite number/).waitFor(); assert.equal(await page.evaluate(() => log.create.length), 0);
  await setup.getByLabel('Custom ground pivot', {exact: true}).fill('.3'); assert.equal(await save.isEnabled(), true);
  pass('Unchanged depth and collision setup disables Save, reverting disables it again, and invalid pivots explain validation');
  const beforeDiscard = await page.evaluate(() => JSON.parse(JSON.stringify(log)));
  await setup.getByRole('button', {name: 'Discard setup draft', exact: true}).click(); await page.getByText('Setup draft discarded. Saved versions are unchanged.', {exact: true}).waitFor();
  assert.deepEqual(await page.evaluate(() => JSON.parse(JSON.stringify(log))), beforeDiscard); await openSetup();
  assert.equal(await setup.getByLabel('Representation and depth', {exact: true}).inputValue(), 'standing'); assert.equal(await save.isDisabled(), true);
  await chooseDepth('custom'); await setup.getByLabel('Custom ground pivot', {exact: true}).fill('.3');
  pass('Discard deletes only the unsent local draft without any request and reopen starts from the saved version');
  const first = setup.getByRole('button', {name: 'Collision row 1, column 1', exact: true}); await first.focus(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Space');
  assert.equal(await setup.getByRole('button', {name: 'Collision row 1, column 2'}).getAttribute('aria-pressed'), 'true');
  await page.getByRole('button', {name: 'Close Custom image library'}).click(); await page.waitForFunction(() => history.state?.surface !== 'images');
  await page.goForward(); await setup.waitFor({state: 'visible'}); assert.equal(await setup.getByLabel('Custom ground pivot', {exact: true}).inputValue(), '.3');
  await page.goBack(); await page.waitForFunction(() => document.querySelector('#library').hidden); await openSetup();
  assert.equal(await page.evaluate(() => log.create.length), 0); assert.equal(await setup.getByLabel('Representation and depth', {exact: true}).inputValue(), 'custom');
  pass('Close, history Back/Forward and reopen preserve the setup draft without a create');
  await save.click(); await page.getByText('Version 2 · library revision 2', {exact: true}).waitFor();
  assert.deepEqual(await page.evaluate(() => selected), {assetId: 'asset_a', versionId: 'version_1'}); assert.equal(await page.evaluate(() => state.scene.objects[0].assetRef.versionId), 'version_1');
  assert.deepEqual(await page.evaluate(() => log.create[0].setup), {depthPreset: 'custom', depthPivot: .3, collisionGrid: [[1, 1], [0, 0]]});
  assert.equal(await page.evaluate(() => log.choose.length), 0);
  await page.getByRole('button', {name: 'Place Fern (asset_a)', exact: true}).click(); assert.equal(await page.evaluate(() => selected.versionId), 'version_2');
  pass('Saving preserves scene and queued pins; explicit displayed-version Place is the only selection change');
  await openSetup(); await setup.getByLabel('Custom ground pivot', {exact: true}).fill('.30'); assert.equal(await save.isDisabled(), true);
  await setup.getByLabel('Custom ground pivot', {exact: true}).fill('.31'); assert.equal(await save.isEnabled(), true); await setup.getByLabel('Custom ground pivot', {exact: true}).fill('.3'); assert.equal(await save.isDisabled(), true);
  await chooseDepth('floor'); await page.evaluate(() => { currentEntry = makeEntry(3, 3); mode = 'conflict'; }); await save.click();
  await setup.getByText(/Your setup draft is preserved/).waitFor(); assert.equal(await save.isDisabled(), true); assert.equal(await setup.getByLabel('Representation and depth', {exact: true}).inputValue(), 'floor');
  await page.evaluate(() => { currentEntry.version = {...currentEntry.version, depthPreset: 'floor', depthPivot: .5, representation: 'floor', collisionGrid: [[1, 1], [0, 0]]}; });
  await setup.getByRole('button', {name: 'Review latest version', exact: true}).click(); await setup.getByText(/Reviewed version 3, revision 3/).waitFor();
  assert.equal(await setup.getByLabel('Representation and depth', {exact: true}).inputValue(), 'floor'); assert.equal(await save.isDisabled(), true); await setup.evaluate(form => form.requestSubmit()); assert.equal(await page.evaluate(() => log.create.length), 2);
  await chooseDepth('custom'); await setup.getByLabel('Custom ground pivot', {exact: true}).fill('.4'); assert.equal(await save.isEnabled(), true);
  await page.evaluate(() => { mode = 'normal'; }); await save.click(); await page.getByText('Version 4 · library revision 4', {exact: true}).waitFor();
  const calls = await page.evaluate(() => log.create); assert.equal(calls[1].expectedVersionId, 'version_2'); assert.equal(calls[2].expectedVersionId, 'version_3'); assert.notEqual(calls[1].operationId, calls[2].operationId);
  pass('CAS conflict keeps all draft values and requires an explicit latest-base review before a new operation');
  await openSetup(); await chooseDepth('standing'); await page.evaluate(() => { mode = 'not-sent'; }); await save.click();
  assert.equal(await setup.getByRole('button', {name: 'Discard setup draft', exact: true}).isDisabled(), true);
  await setup.getByRole('button', {name: 'Check version save status', exact: true}).click(); await setup.getByRole('button', {name: 'Retry same version save', exact: true}).waitFor();
  assert.equal(await setup.getByLabel('Representation and depth', {exact: true}).isDisabled(), true);
  await setup.getByRole('button', {name: 'Back to library', exact: true}).click(); await openSetup();
  assert.equal(await setup.getByRole('button', {name: 'Discard setup draft', exact: true}).isDisabled(), true);
  await setup.getByRole('button', {name: 'Check version save status', exact: true}).click(); await page.evaluate(() => { mode = 'lost'; }); await setup.getByRole('button', {name: 'Retry same version save', exact: true}).click();
  await setup.getByText(/response was interrupted/).waitFor();
  const retries = await page.evaluate(() => log.create.slice(-2)); assert.deepEqual(retries[0], retries[1]);
  await page.evaluate(() => { currentEntry = makeEntry(6, 6); }); await setup.getByRole('button', {name: 'Check version save status', exact: true}).click();
  await page.getByText('Version 6 · library revision 6', {exact: true}).waitFor(); await page.getByText(/Saved version 5/).waitFor(); assert.equal(await page.evaluate(() => selected.versionId), 'version_2');
  pass('Unknown outcomes lock the draft, retry exact identity, and reconcile an older receipt without regressing current version');
  await openSetup(); await chooseDepth('custom'); await setup.getByLabel('Custom ground pivot', {exact: true}).fill('.6');
  await page.evaluate(() => { state.room.capabilities.canEditScene = false; shell.syncAuthority(); }); assert.equal(await save.isDisabled(), true);
  assert.equal(await setup.getByRole('button', {name: 'Discard setup draft', exact: true}).isEnabled(), true);
  const beforeRoleDiscard = await page.evaluate(() => JSON.parse(JSON.stringify(log))); await setup.getByRole('button', {name: 'Discard setup draft', exact: true}).click(); assert.deepEqual(await page.evaluate(() => JSON.parse(JSON.stringify(log))), beforeRoleDiscard);
  await page.evaluate(() => { state.room.capabilities.canEditScene = true; shell.syncAuthority(); }); await openSetup();
  assert.equal(await setup.getByLabel('Representation and depth', {exact: true}).inputValue(), 'standing');
  await chooseDepth('custom'); await setup.getByLabel('Custom ground pivot', {exact: true}).fill('.6');
  await page.evaluate(() => { state.room.capabilities.canEditScene = false; shell.syncAuthority(); });
  await page.evaluate(() => { state.room.capabilities.canEditScene = true; shell.syncAuthority(); }); await setup.getByRole('button', {name: 'Review latest version', exact: true}).click(); await setup.getByText(/Reviewed version 6/).waitFor();
  assert.equal(await setup.getByLabel('Custom ground pivot', {exact: true}).inputValue(), '.6');
  await page.evaluate(() => { currentEntry = {...currentEntry, status: 'archived', revision: 7}; shell.refresh({assetId:'asset_a', status:'archived',revision:7}); });
  await setup.getByText(/Your setup draft is preserved/).waitFor(); assert.equal(await save.isDisabled(), true);
  await setup.getByRole('button', {name: 'Review latest version', exact: true}).click(); await setup.getByText(/This image is archived/).waitFor(); assert.equal(await save.isDisabled(), true);
  assert.equal(await setup.getByLabel('Custom ground pivot', {exact: true}).inputValue(), '.6');
  pass('Manage loss and archive preserve the draft and block version saves until authority and latest base are reviewed');
  await page.evaluate(() => { currentEntry = {...currentEntry, status: 'active', revision: 8}; }); await setup.getByRole('button', {name: 'Review latest version', exact: true}).click(); await setup.getByText(/Reviewed version 6, revision 8/).waitFor();
  await page.setViewportSize({width: 320, height: 700});
  for (const locator of [save, setup.getByRole('button', {name:'Back to library', exact:true}), setup.getByRole('button', {name:'Discard setup draft', exact:true})]) { const box = await locator.boundingBox(); assert(box.width >= 44 && box.height >= 44 && box.x >= 0 && box.x + box.width <= 321); }
  await setup.getByRole('button', {name:'Back to library', exact:true}).click(); await openSetup(); assert.equal(await setup.getByLabel('Custom ground pivot', {exact: true}).inputValue(), '.6');
  await page.evaluate(() => { mode = 'hold'; }); await save.click(); await page.waitForFunction(() => !!window.finishSave); await setup.evaluate(form => form.requestSubmit());
  assert.equal(await setup.getByRole('button', {name: 'Discard setup draft', exact: true}).isDisabled(), true);
  const count = await page.evaluate(() => log.create.length); await page.evaluate(() => { state.user = {id:'bob'}; state.room = {...state.room, id:'room_b', imageDefinitions:{}}; shell.acceptRoom(); finishSave(); });
  await page.waitForTimeout(50); assert.equal(await page.evaluate(() => log.create.length), count); assert.equal(await setup.isHidden(), true); assert.deepEqual(await page.evaluate(() => Object.keys(state.room.imageDefinitions)), []);
  pass('320px controls remain reachable; repeated save and stale account completion cannot create or reveal another version');
  assert.deepEqual(errors, []);
} finally { await browser.close(); }
