import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {createRequire} from 'node:module';
const base=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),require=createRequire(path.join(base,'package.json'));
const {build}=require('esbuild'),{chromium}=require('playwright-core'),executable=(await import(require.resolve('@sparticuz/chromium'))).default;
const source=`
import {mountImageLibraryShell} from './src/image-library-shell.js';
import {normalizeImageAssetDraft} from './src/image-asset-schema.js';
window.state={user:{id:'alice'},ready:true,room:{id:'room_a',role:'owner',capabilities:{canEditScene:true,canBuild:true},imageDefinitions:{},scene:{objects:[]}},scene:{objects:[]}};
window.log={choose:[],open:[],retry:[],create:[],reconcile:[]};let listener,states=[];
window.renderer={setImageContext(ctx){if(!ctx.canRead){states=[];listener?.(states)}},setImageStateListener(fn){listener=fn},getImageStates:()=>states,retryImage:id=>{log.retry.push(id);return Promise.resolve(true)}};
window.setStatuses=value=>{states=value;listener?.(states)};
window.sample=async()=>{const canvas=document.createElement('canvas');canvas.width=64;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle='green';ctx.fillRect(0,0,64,64);return new Uint8Array(await (await new Promise(r=>canvas.toBlob(r,'image/png'))).arrayBuffer())};
const date='2026-10-02T00:00:00.000Z';window.makeEntry=(roomId='room_a')=>({schemaVersion:1,status:'active',definition:{schemaVersion:1,assetId:'asset_a',roomId,createdBy:'alice',createdAt:date,originKind:'upload'},version:{...normalizeImageAssetDraft({name:'Fern'},{width:64,height:64,byteLength:200,mediaType:'image/png'}),schemaVersion:1,assetId:'asset_a',roomId,versionId:'version_a',sequence:1,sha256:'a'.repeat(64),createdBy:'alice',createdAt:date}});
window.entries=[makeEntry()];window.holdCreate=false;window.receipt=null;
const transport={list:async({roomId})=>({entries:entries.filter(e=>e.definition.roomId===roomId)}),readImage:async()=>({bytes:await sample(),mediaType:'image/png'}),create:async args=>{log.create.push({...args,signal:undefined,bytes:[...args.bytes]});if(holdCreate)return new Promise((resolve,reject)=>window.finishCreate=()=>{receipt=makeEntry(args.roomId);entries=[receipt];reject(new Error('Lost upload response'));});return makeEntry(args.roomId)},reconcileCreate:async args=>{log.reconcile.push(args.operationId);return receipt?{status:'committed',entry:receipt}:{status:'not-found'}}};
window.shell=mountImageLibraryShell({root:document.querySelector('#image-library'),statusRoot:document.querySelector('#image-render-status'),getState:()=>state,getRenderer:()=>renderer,transport,onChoose:ref=>{log.choose.push(ref);return true},onOpenChange:open=>{log.open.push(open);if(open)history.pushState({surface:'images'},'',location.href);else if(history.state?.surface==='images')history.back();}});
shell.acceptRoom();document.querySelector('#open').onclick=()=>shell.setOpen(true,{trigger:document.querySelector('#open')});window.addEventListener('popstate',()=>shell.setOpen(history.state?.surface==='images',{record:false}));
window.switchRoom=roomId=>{shell.suspend();state.room={...state.room,id:roomId,imageDefinitions:{},scene:{objects:[]}};state.scene={objects:[]};shell.acceptRoom()};
`;
const bundle=await build({stdin:{contents:source,resolveDir:base,sourcefile:'image-shell-fixture.js'},bundle:true,format:'iife',write:false});
const browser=await chromium.launch({executablePath:await executable.executablePath(),headless:true,args:['--no-sandbox','--no-zygote','--disable-gpu']});
const page=await browser.newPage({viewport:{width:900,height:700}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
const html='<!doctype html><html><body><button id="open">Open images</button><canvas id="game" tabindex="0"></canvas><section id="image-library"></section><section id="image-render-status" hidden role="status"></section></body></html>';
await page.route('**/*',route=>new URL(route.request().url()).hostname==='image-shell.test'?route.fulfill({contentType:'text/html',body:html}):route.abort());
const passed=[];const check=name=>{passed.push(name);console.log('PASS',name)};
try{
 await page.goto('https://image-shell.test/');await page.addStyleTag({content:(await Promise.all(['public/universe-tokens.css','src/image-library-panel.css','src/image-library-shell.css'].map(file=>readFile(path.join(base,file),'utf8')))).join('\n')});await page.addScriptTag({content:bundle.outputFiles[0].text});
 await page.getByRole('button',{name:'Open images',exact:true}).click();await page.locator('.uil-card img:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>!!state.room.imageDefinitions['asset_a:version_a']),true);check('Open loads a real decoded thumbnail and caches validated scene metadata');
 await page.getByRole('button',{name:'Close Custom image library',exact:true}).click();await page.waitForFunction(()=>history.state?.surface!=='images');assert.equal(await page.locator('#open').evaluate(node=>node===document.activeElement),true);await page.goForward();await page.locator('.uil-card').waitFor();assert.equal(await page.locator('#image-library').isVisible(),true);await page.goBack();await page.waitForFunction(()=>document.querySelector('#image-library').hidden);check('Native close and Back/Forward keep visibility and trigger focus synchronized');
 await page.getByRole('button',{name:'Open images',exact:true}).click();await page.locator('.uil-card button').click();assert.deepEqual(await page.evaluate(()=>log.choose),[{assetId:'asset_a',versionId:'version_a'}]);assert.equal(await page.locator('#game').evaluate(node=>node===document.activeElement),true);assert.equal(await page.locator('#image-library').isHidden(),true);check('Choose passes only the pinned reference and returns focus to the world');
 await page.evaluate(()=>setStatuses([{id:'a',status:'ready',name:'Ready'},{id:'b',status:'loading',name:'Loading fern'},{id:'c',status:'error',name:'Error fern'},{id:'d',status:'revoked',name:'Revoked'}]));assert.equal(await page.locator('#image-render-status>div').count(),2);await page.getByRole('button',{name:'Retry Error fern'}).click();assert.deepEqual(await page.evaluate(()=>log.retry),['c']);await page.evaluate(()=>shell.suspend());assert.equal(await page.locator('#image-render-status').isHidden(),true);check('Status/retry reflects only actual loading/errors and clears immediately on revoke');
 await page.evaluate(()=>shell.resume());await page.getByRole('button',{name:'Open images',exact:true}).click();await page.getByRole('button',{name:'Add PNG',exact:true}).click();const bytes=await page.evaluate(async()=>[...await sample()]);await page.locator('input[type=file]').setInputFiles({name:'fern.png',mimeType:'image/png',buffer:Buffer.from(bytes)});await page.getByText('Local preview ready. Configure it before uploading.',{exact:true}).waitFor();await page.getByLabel('Tags',{exact:true}).focus();await page.keyboard.press('Escape');assert.equal(await page.locator('.uil-draft').isHidden(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#image-library').isHidden(),true);check('Escape steps out of the local draft before closing the nonmodal library');
 await page.waitForFunction(()=>history.state?.surface!=='images');await page.getByRole('button',{name:'Open images',exact:true}).click();await page.getByRole('button',{name:'Add PNG',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'fern.png',mimeType:'image/png',buffer:Buffer.from(bytes)});await page.getByText('Local preview ready. Configure it before uploading.',{exact:true}).waitFor();await page.evaluate(()=>holdCreate=true);await page.getByRole('button',{name:'Upload',exact:true}).click();await page.waitForFunction(()=>!!window.finishCreate);await page.getByRole('button',{name:'Close Custom image library',exact:true}).click();await page.evaluate(()=>finishCreate());await page.waitForFunction(()=>document.querySelector('.uil-recovery').hidden===false);await page.getByRole('button',{name:'Open images',exact:true}).click();await page.waitForFunction(()=>log.reconcile.length>0);await page.getByText('Uploaded Fern. It is ready in Custom; no world object has been placed.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>log.create.length),1);check('Closing an in-flight upload retains uncertainty and reopening reconciles the original receipt');
 await page.evaluate(()=>{state.room.capabilities.canBuild=false;state.room.capabilities.canEditScene=false;shell.syncAuthority()});assert.equal(await page.getByRole('button',{name:'Add PNG',exact:true}).isDisabled(),true);await page.locator('.uil-card').waitFor();assert.equal(await page.locator('.uil-card button').isDisabled(),true);await page.evaluate(()=>{state.ready=false;shell.syncAuthority()});assert.equal(await page.locator('#image-library').isHidden(),true);assert.equal(await page.locator('.uil-card').count(),0);check('Current place/manage/read changes cancel stale authority and clear protected cards');
 assert.deepEqual(errors,[]);console.log(passed.length+' focused bridge browser checks passed');
}finally{await browser.close()}
