/** Actual local game acceptance. No application actions are invoked through evaluate.
 * Browser JS reads documented state/projection or DOM only. Fixtures and fault
 * injection are confined to the fresh loopback server. Run serially on the GPU.
 */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {inflateSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds,emptyScene} from '../src/worlds.js';
import {makePng} from '../fixtures/png-fixtures.mjs';
const scope=process.env.UNIVERSE_IMAGE_SCOPE||'full',out=process.env.UNIVERSE_IMAGE_EVIDENCE||'evidence/image-library-full';await mkdir(out,{recursive:true});
const seeds=structuredClone(seedWorlds);seeds[0].rooms.push({id:'image-court',name:'Image acceptance court',scene:{...emptyScene(),bounds:{width:8,depth:12},spawn:{x:0,z:4},objects:[{id:'depth-chair',name:'Alpha depth chair',type:'chair',x:0,z:-3,rotation:0}]}});
const dist=process.env.UNIVERSE_IMAGE_DIST||new URL('../dist',import.meta.url).pathname,testedBundleSha256=createHash('sha256').update(await readFile(dist+'/main.js')).digest('hex'),startedAt=new Date().toISOString();
const app=createGameServer({seeds,dist}),address=await app.listen(0),base=`http://127.0.0.1:${address.port}`;
const browser=await launch(),context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage();page.setDefaultTimeout(15000);
const checks=[],errors=[],requests=[],limits=['Local generated PNG fixtures and isolated loopback server only','Headless Chromium / SwiftShader; 320px touch emulation is not a physical phone','Read-only application state/projection diagnostics; no invoked app actions or forged DOM events','No production, external-provider, credential or security probing','File chooser exercised; native OS file drag/drop not exercised'];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST'&&/\/assets$/.test(new URL(r.url()).pathname))requests.push(JSON.parse(r.postData()));});
const state=()=>page.evaluate(()=>window.__universe.getState()),editor=()=>page.evaluate(()=>window.__universe.getEditor());
const report=async(name,details={})=>{checks.push({name,status:'passed',...details});console.log('PASS',name,JSON.stringify(details));await persist();};
const persist=()=>writeFile(out+'/results.json',JSON.stringify({scope,startedAt,testedBundleSha256,checks,errors,limits},null,2));
const near=(a,b,t=.08)=>assert(Math.abs(a-b)<t,`${a} should be within ${t} of ${b}`);
async function projected(x,z,y=0,p=page){const q=await p.evaluate(a=>window.__universe.getScreenPoint(a.x,a.z,a.y),{x,z,y});assert(q?.visible,`projected point ${x},${z},${y} is on canvas`);return q;}
async function clickWorld(x,z,y=0){const q=await projected(x,z,y);await page.mouse.click(q.x,q.y);return q;}
async function moveWorld(x,z,y=0){const q=await projected(x,z,y);await page.mouse.move(q.x,q.y);return q;}
async function ready(p=page){await p.waitForFunction(()=>window.__universe?.getState().ready,{},{timeout:60000});}
async function build(){if(!await page.locator('#editor').isVisible())await page.locator('#dock-build').click();}
async function openLibrary(){await build();if(!await page.locator('#image-library').isVisible())await page.getByRole('button',{name:'Custom images',exact:true}).click();await page.locator('#image-library').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#image-library .uil-cards')?.getAttribute('aria-busy')!=='true');}
async function prepare({bytes,name,tags='proof, local',depth='floor',pivot,collision=false,cols=0}){
 await openLibrary();await page.getByPlaceholder('Search Custom').fill('');await page.getByRole('button',{name:'Add PNG',exact:true}).click();
 const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose PNG',exact:true}).click();await (await chooser).setFiles({name:name+'.png',mimeType:'image/png',buffer:bytes});
 const root=page.locator('#image-library');await root.getByAltText('Local image preview').waitFor();await root.getByRole('textbox',{name:'Name',exact:true}).fill(name);await root.getByRole('textbox',{name:'Tags',exact:true}).fill(tags);await root.getByRole('combobox',{name:'Representation and depth',exact:true}).selectOption(depth);
 if(pivot!==undefined)await root.getByRole('spinbutton',{name:'Custom ground pivot',exact:true}).fill(String(pivot));
 if(collision){await root.getByRole('checkbox',{name:'Floating placement',exact:true}).uncheck();await root.getByRole('checkbox',{name:'Paint collision cells',exact:true}).check();for(let c=1;c<=cols;c++)await root.getByRole('button',{name:`Collision row 1, column ${c}`,exact:true}).click();}
 await root.getByRole('button',{name:'Upload',exact:true}).waitFor();
}
async function upload(draft){const before=requests.length;await prepare(draft);assert.equal(requests.length,before,'choosing/configuring a local file must not upload');const scene=(await state()).scene;await page.locator('#image-library').getByRole('button',{name:'Upload',exact:true}).click();await page.getByRole('button',{name:new RegExp('^Place '+draft.name+' \\(')}).waitFor();assert.equal(requests.length,before+1);assert.deepEqual((await state()).scene,scene,'upload must not place a world object');const room=(await state()).room.id,response=await page.request.get(base+`/api/rooms/${room}/assets`),entry=(await response.json()).entries.find(e=>e.version.name===draft.name);assert(entry);assert.equal(entry.version.sha256,createHash('sha256').update(draft.bytes).digest('hex'));return entry;}
async function choose(name){await openLibrary();await page.getByPlaceholder('Search Custom').fill(name);await page.getByRole('button',{name:new RegExp('^Place '+name+' \\(')}).click();await page.locator('#image-library').waitFor({state:'hidden'});await page.waitForFunction(()=>window.__universe.getEditor().tool==='image');}
async function place(x,z){const before=(await state()).scene.objects.length;await moveWorld(x,z);const preview=(await editor()).preview;assert.equal(preview.type,'image');assert.equal(preview.valid,true,preview.reason);assert.equal((await state()).scene.objects.length,before);await clickWorld(x,z);await page.waitForFunction(n=>window.__universe.getState().scene.objects.length===n,before+1);return (await state()).scene.objects.at(-1);}
async function select(){await page.getByRole('button',{name:'↖ Select',exact:true}).click();}
async function save(){await page.getByRole('button',{name:'Save room',exact:true}).click();await page.waitForFunction(()=>!window.__universe.getEditor().dirty&&!window.__universe.getEditor().saving);return (await state()).scene;}
async function visit(name,id){await page.locator('#dock-explore').click();await page.getByRole('button',{name:'View room '+name,exact:true}).click();await page.getByRole('button',{name:'Enter '+name,exact:true}).click();await page.waitForFunction(id=>window.__universe.getState().room.id===id,id);await page.locator('#places').waitFor({state:'hidden'}).catch(()=>{});}
// Decode screenshots independently so visibility assertions inspect rendered pixels.
function decodeScreenshot(bytes){let off=8,w,h,n,parts=[];while(off<bytes.length){const len=bytes.readUInt32BE(off),type=bytes.toString('ascii',off+4,off+8),data=bytes.subarray(off+8,off+8+len);if(type==='IHDR'){w=data.readUInt32BE(0);h=data.readUInt32BE(4);n=data[9]===6?4:data[9]===2?3:0;assert(n&&data[8]===8);}if(type==='IDAT')parts.push(data);off+=len+12;}const raw=inflateSync(Buffer.concat(parts)),pixels=Buffer.alloc(w*h*n),paeth=(a,b,c)=>{const p=a+b-c;return Math.abs(p-a)<=Math.abs(p-b)&&Math.abs(p-a)<=Math.abs(p-c)?a:Math.abs(p-b)<=Math.abs(p-c)?b:c;};for(let y=0;y<h;y++){const f=raw[y*(w*n+1)];for(let x=0;x<w*n;x++){const i=y*w*n+x,a=x>=n?pixels[i-n]:0,b=y?pixels[i-w*n]:0,c=y&&x>=n?pixels[i-w*n-n]:0;pixels[i]=(raw[y*(w*n+1)+1+x]+[0,a,b,Math.floor((a+b)/2),paeth(a,b,c)][f])&255;}}return{w,h,rgb(x,y){const at=(Math.round(y)*w+Math.round(x))*n;return [...pixels.subarray(at,at+3)];}};}
const pink=rgb=>rgb[0]>180&&rgb[1]<110&&rgb[2]>150;
// Software-WebGL captures can outlast a locator's15s action timeout on shared CI.
// Keep the actual screenshot/pixel assertions, but foreground its sole live game page.
async function capturePage(target,path){
 await target.bringToFront();
 await target.waitForFunction(()=>document.visibilityState==='visible',{},{timeout:60000});
 return target.screenshot({path,timeout:60000});
}
async function screenshot(name){const bytes=await capturePage(page,out+'/'+name+'.png');return decodeScreenshot(bytes);}
async function visiblePink(name,x,z,y=.05){await page.waitForTimeout(700);const q=await projected(x,z,y),shot=await screenshot(name);const rgb=shot.rgb(q.x,q.y);assert(pink(rgb),`Custom image rendered above paving at ${x},${z}: ${rgb}`);return{point:q,rgb};}
async function commonsFlow(){
 await page.goto(base,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>!!window.__universe,{},{timeout:60000});await page.getByPlaceholder('Your name').fill('Image acceptance');await page.locator('#join-button').click();await ready();await build();
 const bytes=makePng({width:64,height:64,pixel:(x,y)=>[245,35,225,x<24&&y<24?0:255]});const entry=await upload({bytes,name:'Acceptance floor',tags:'Paving, Alpha, paving'});
 assert.deepEqual(entry.version.tags,['Paving','Alpha']);assert.equal(entry.version.representation,'floor');assert.equal(entry.version.floating,true);await report('Real chooser, local preview, metadata and explicit Upload create one canonical asset without placement',{assetId:entry.definition.assetId,versionId:entry.version.versionId});
 await page.getByPlaceholder('Search Custom').fill('alpha');assert.equal(await page.locator('#image-library .uil-card').count(),1);await page.getByPlaceholder('Search Custom').fill('nothing-matches');assert.equal(await page.locator('#image-library .uil-card').count(),0);await choose('Acceptance floor');
 const item=await place(0,3);assert.deepEqual(item.assetRef,{assetId:entry.definition.assetId,versionId:entry.version.versionId});await select();const rendered=await visiblePink('commons-floor-on-paving',.5,3.5);await report('Custom tag/name search, real projected ghost and pointer placement render a floor PNG on Commons paving',rendered);
 await clickWorld(-.6,2.4,.05);assert.equal((await editor()).selected,null,'transparent floor pixel picks the ground');await clickWorld(.5,3.5,.05);assert.equal((await editor()).selected,item.id,'opaque floor pixel picks exact image instance');await report('Real pointer alpha picking passes through transparent floor pixel and selects opaque pixel');
 const start=await projected(.5,3.5,.05),end=await projected(5.5,3.5);await page.mouse.move(start.x,start.y);await page.mouse.down();const before=(await state()).scene;await page.mouse.move(end.x,end.y,{steps:12});assert.deepEqual((await state()).scene,before,'drag preview cannot mutate scene before release');assert.equal((await editor()).preview?.kind,'move');await screenshot('pointer-drag-preview');await page.mouse.up();const moved=(await state()).scene.objects.find(o=>o.id===item.id);assert(moved.x>4.8&&moved.x<5.2);assert.deepEqual(moved.assetRef,item.assetRef);
 await page.locator('#game').focus();await page.keyboard.press('r');assert.equal((await state()).scene.objects.find(o=>o.id===item.id).rotation,90);await page.keyboard.press('d');assert.equal((await editor()).tool,'duplicate');await moveWorld(-6,-2);assert.equal((await editor()).preview.valid,true);await clickWorld(-6,-2);const copy=(await state()).scene.objects.at(-1);assert.notEqual(copy.id,item.id);assert.deepEqual(copy.assetRef,item.assetRef);assert.equal(copy.rotation,90);await select();await clickWorld(-6,-2,1);assert.equal((await editor()).selected,'commons-table');const tq=await projected(-6,-2,1),depthShot=await screenshot('native-table-depth-over-floor');assert(!pink(depthShot.rgb(tq.x,tq.y)),'native table is visible above floor image');await report('Pointer drag commits once; real R/D and pointer duplicate retain pinned ref; native table remains visible and pickable above image');
 const saved=await save();await page.reload();await ready();assert.deepEqual((await state()).scene,saved);const imageURL=`/api/rooms/commons/assets/${entry.definition.assetId}/versions/${entry.version.versionId}/image`,response=await page.request.get(base+imageURL);assert.equal(response.status(),200);assert.equal(response.headers()['content-type'],'image/png');assert.equal(response.headers()['cache-control'],'private, no-store');assert.deepEqual(await response.body(),bytes);await report('Save and reload recover exact scene/pinned refs and real authenticated no-store PNG bytes');
 await openLibrary();await page.getByRole('button',{name:'Close Custom image library',exact:true}).click();await page.locator('#image-library').waitFor({state:'hidden'});await page.waitForTimeout(150);assert(await page.locator('#editor').isVisible());await report('Close library returns to live Build');
 return{saved,entry};
}
async function retryFlow(){
 const bytes=makePng({width:32,height:32,pixel:()=>[40,210,170,255]});await prepare({bytes,name:'Retry proof'});const before=requests.length;let blocked=false;
 const matcher='**/api/rooms/commons/assets';const interrupt=route=>{if(route.request().method()==='POST'&&!blocked){blocked=true;return route.abort('failed');}return route.continue();};await page.route(matcher,interrupt);await page.locator('#image-library').getByRole('button',{name:'Upload',exact:true}).click();await page.getByRole('button',{name:'Check upload status',exact:true}).waitFor();assert.equal(await page.locator('#image-library .uil-card').filter({hasText:'Retry proof'}).count(),0);const list=await page.request.get(base+'/api/rooms/commons/assets');assert(!(await list.json()).entries.some(e=>e.version.name==='Retry proof'));await page.unroute(matcher,interrupt);
 await page.getByRole('button',{name:'Check upload status',exact:true}).click();await page.getByRole('button',{name:'Retry same upload',exact:true}).click();await page.getByRole('button',{name:/^Place Retry proof \(/}).waitFor();assert.equal(requests.length,before+2);assert.deepEqual(requests.at(-1),requests.at(-2));await report('Interrupted actual upload creates no fake card; status reconciliation and explicit retry preserve exact bytes/draft/operation ID');
 await page.getByRole('button',{name:'Close Custom image library',exact:true}).click();
}
async function compactFlow(){
 await visit('Image acceptance court','image-court');await build();assert.equal((await editor()).tool,'select');assert.equal((await editor()).preview,null);await openLibrary();assert.equal(await page.locator('#image-library .uil-card').count(),0);await report('UI room exit clears library cards and old placement context');
 const bytes=makePng({width:256,height:64,pixel:(x,y)=>y<32?[245,35,225,255]:[25,230,240,255]});const entry=await upload({bytes,name:'Painted wall',depth:'floor',collision:true,cols:8});assert.equal(entry.version.floating,false);assert.deepEqual(entry.version.collisionGrid,[Array(8).fill(1),Array(8).fill(0)]);await choose('Painted wall');const wall=await place(0,0);await select();await visiblePink('compact-paving-painted-wall',0,-.5);await report('Collision UI paints only first row of an eight-cell-wide PNG; image remains visible on compact paving');await save();
 await page.getByRole('button',{name:'Close editor',exact:true}).click();await page.waitForTimeout(350);if(await page.locator('#editor').isVisible()){checks.push({name:'First Done closes Build after image library workflows',status:'failed',error:'The editor reopens after its first Done click; a second explicit click is required',history:await page.evaluate(()=>history.state)});await persist();await screenshot('done-reopens-build');await page.getByRole('button',{name:'Close editor',exact:true}).click();}else await report('First Done closes Build after image-library placement');await page.locator('#editor').waitFor({state:'hidden'});await page.locator('#game').focus();const before=(await state()).position;await page.keyboard.down('Shift');await page.keyboard.down('w');await page.waitForFunction(p=>{const q=window.__universe.getState().position;return p.z-q.z>.45&&Math.hypot(q.x-p.x,q.z-p.z)>.6;},before);const moving=(await state()).position;assert(moving.z<before.z-.45,'W movement precondition is demonstrated');await page.waitForTimeout(1100);await page.keyboard.up('w');await page.keyboard.up('Shift');await page.waitForTimeout(150);const blocked=(await state()).position;assert(blocked.z>.28&&blocked.z<.4,`painted cells stop near z=.3: ${JSON.stringify(blocked)}`);assert(blocked.z<1.1,'player passed the unpainted row, disproving full-image-rectangle collision');const stopped={...blocked};await page.locator('#game').focus();await page.keyboard.down('Shift');await page.keyboard.down('w');await page.waitForTimeout(600);await page.keyboard.up('w');await page.keyboard.up('Shift');const again=(await state()).position;near(again.z,stopped.z,.04);await screenshot('actual-player-painted-cell-stop');await report('Actual Shift/W player moves through clear row and stops at painted cells, not full image rectangle',{before,moving,blocked,again,wallId:wall.id});
 await build();const ringBytes=makePng({width:128,height:96,pixel:(x,y)=>[245,35,225,x<7||x>120||y<7||y>88?255:0]});
 const ringEntry=await upload({bytes:ringBytes,name:'Upright alpha frame',depth:'custom',pivot:.5});assert.equal(ringEntry.version.representation,'upright');assert.equal(ringEntry.version.depthPreset,'custom');assert.equal(ringEntry.version.depthPivot,.5);await choose('Upright alpha frame');const ring=await place(0,-2);await select();await page.waitForTimeout(600);
 await clickWorld(-1.9,-2,1.5);assert.equal((await editor()).selected,ring.id,'opaque upright border selects image');await clickWorld(0,-3,.48);assert.equal((await editor()).selected,'depth-chair','transparent upright centre allows native chair selection');await clickWorld(1.1,-2,.45);assert.equal((await editor()).selected,null,'transparent upright pixel allows native ground selection');await screenshot('upright-alpha-and-native-chair');await report('Custom depth pivot renders upright PNG; true pointer hits opaque border and passes transparent pixels to native chair and ground');await save();
 // Return via room navigation for the independent mobile scope.
 await visit('The Commons','commons');
}

async function checkMobileChrome(m,mobile){
 const metrics=await m.evaluate(()=>{const e=document.querySelector('.brand-logo'),r=e.getBoundingClientRect(),share=document.querySelector('#invite').getBoundingClientRect(),dock=document.querySelector('#dock');return{client:document.documentElement.clientWidth,document:document.documentElement.scrollWidth,inner:innerWidth,brand:{width:r.width,height:r.height,naturalWidth:e.naturalWidth,naturalHeight:e.naturalHeight},share:{x:share.x,y:share.y,width:share.width,height:share.height,right:share.right},dock:{scrollLeft:dock.scrollLeft,scrollWidth:dock.scrollWidth,clientWidth:dock.clientWidth},hint:!document.querySelector('#dock-more').hidden};});
 assert.equal(metrics.client,320);assert.equal(metrics.document,320);assert.equal(metrics.inner,320);assert.equal(metrics.brand.width,124);assert.equal(metrics.brand.height,62);near(metrics.brand.width/metrics.brand.height,metrics.brand.naturalWidth/metrics.brand.naturalHeight,.001);assert(metrics.share.x>=0&&metrics.share.right<=320&&metrics.share.width>=48&&metrics.share.height>=48);assert(metrics.hint,'native horizontal dock chevron is visible while more controls are offscreen');
 await m.locator('#invite').tap();await m.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('Room link copied')||!document.querySelector('#dialog').hidden);if(await m.locator('#dialog').isVisible()){await m.locator('#dialog-close').tap();await m.locator('#dialog').waitFor({state:'hidden'});await m.waitForTimeout(150);}await capturePage(m,out+'/mobile-header-brand-share.png');await report('320px document fits; original 124×62 brand ratio and complete 48px Share action are verified',{metrics});
 const dock=await m.locator('#dock').boundingBox(),cdp=await mobile.newCDPSession(m),y=dock.y+dock.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:dock.x+dock.width-35,y,id:1}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:dock.x+dock.width-35-i*22,y,id:1}]});await m.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await m.waitForFunction(()=>document.querySelector('#dock').scrollLeft>0);await m.waitForTimeout(250);let you=await m.locator('#dock-settings').boundingBox();assert(you.x>=dock.x&&you.x+you.width<=dock.x+dock.width+.5);await m.locator('#dock-settings').tap();await m.waitForFunction(()=>!document.querySelector('#social').hidden&&document.querySelector('#social').dataset.tab==='settings');await m.keyboard.press('Escape');await m.locator('#social').waitFor({state:'hidden'});await m.waitForTimeout(150);
 await m.locator('#dock-explore').focus();for(let i=0;i<6;i++)await m.keyboard.press('Tab');assert.equal(await m.evaluate(()=>document.activeElement.id),'dock-settings');you=await m.locator('#dock-settings').boundingBox();assert(you.x>=dock.x&&you.x+you.width<=dock.x+dock.width+.5);await m.keyboard.press('Enter');await m.waitForFunction(()=>!document.querySelector('#social').hidden&&document.querySelector('#social').dataset.tab==='settings');await m.keyboard.press('Escape');await m.locator('#social').waitFor({state:'hidden'});await m.waitForTimeout(150);await capturePage(m,out+'/mobile-dock-swipe-tab-you.png');await report('Native horizontal dock swipe reaches You; real Tab navigation scrolls it into view and Enter opens settings');
}
async function checkMobileLibrary(m){
 const design=await m.locator('#image-library').evaluate(root=>{const r=root.getBoundingClientRect();return{clientWidth:root.clientWidth,scrollWidth:root.scrollWidth,font:getComputedStyle(root).fontFamily,controls:[...root.querySelectorAll('button,input:not([type=file]),select')].filter(e=>e.getClientRects().length).map(e=>{const b=e.getBoundingClientRect(),s=getComputedStyle(e);return{label:e.getAttribute('aria-label')||e.textContent,width:b.width,height:b.height,x:b.x,right:b.right,radius:s.borderRadius};}),left:r.left,right:r.right};});assert.equal(design.scrollWidth,design.clientWidth);assert.match(design.font,/^Roboto/);for(const c of design.controls){assert(c.height>=48,`${c.label} has a 48px coarse target`);assert(c.x>=design.left&&c.right<=design.right,`${c.label} stays inside library`);}await report('Custom library uses native Roboto, pill controls and unclipped 48px coarse targets',{design});
 await m.getByRole('button',{name:'Add PNG',exact:true}).tap();const chooser=m.waitForEvent('filechooser');await m.getByRole('button',{name:'Choose PNG',exact:true}).tap();await(await chooser).setFiles({name:'Mobile local grid.png',mimeType:'image/png',buffer:makePng({width:256,height:64,pixel:()=>[245,35,225,255]})});await m.getByAltText('Local image preview').waitFor();await m.getByRole('checkbox',{name:'Floating placement',exact:true}).uncheck();await m.getByRole('checkbox',{name:'Paint collision cells',exact:true}).check();const first=m.getByRole('button',{name:'Collision row 1, column 1',exact:true});await first.tap();const cell=await first.boundingBox();assert.equal(cell.width,48);assert.equal(cell.height,48);const draft=await m.locator('#image-library').evaluate(root=>({client:root.clientWidth,scroll:root.scrollWidth,gridClient:root.querySelector('.uil-grid').clientWidth,gridScroll:root.querySelector('.uil-grid').scrollWidth}));assert.equal(draft.client,draft.scroll);assert(draft.gridScroll>draft.gridClient,'wide grid scrolls inside its own bounded region');await m.getByRole('button',{name:'Cancel draft',exact:true}).tap();await m.getByRole('button',{name:/^Place Acceptance floor \(/}).waitFor();await report('320px local draft and 48px collision cells fit; wide grid scroll stays internal and Cancel returns to Custom',{draft,cell});
}

async function mobileFlow(){
 const storageState=await context.storageState();
 // Desktop acceptance is complete. Retire its draw loop, SSE and WebGL context
 // before starting the independent mobile flow; never keep two game renderers alive.
 await page.close();assert.equal(page.isClosed(),true);
 const mobile=await browser.newContext({viewport:{width:320,height:740},isMobile:true,hasTouch:true,deviceScaleFactor:1,storageState}),m=await mobile.newPage();m.setDefaultTimeout(15000);m.on('pageerror',e=>errors.push(e.message));try{
 await m.bringToFront();await m.goto(base+'/?room=commons',{waitUntil:'domcontentloaded',timeout:60000});await ready(m);const welcome=m.getByRole('button',{name:'Not now',exact:true});await welcome.waitFor({state:'visible',timeout:3000}).catch(()=>{});if(await welcome.isVisible())await welcome.tap();await checkMobileChrome(m,mobile);await m.locator('#dock-build').tap();await m.getByRole('button',{name:'More build tools',exact:true}).tap();await m.getByRole('button',{name:'Custom images',exact:true}).tap();await m.getByRole('button',{name:/^Place Acceptance floor \(/}).waitFor();const layout=await m.evaluate(()=>({width:innerWidth,clientWidth:document.documentElement.clientWidth,visualViewport:{width:visualViewport.width,scale:visualViewport.scale},documentWidth:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&(r.right>320.5||r.left<-.5)&&getComputedStyle(e).display!=='none'&&getComputedStyle(e).visibility!=='hidden';}).map(e=>{const r=e.getBoundingClientRect();return{tag:e.tagName,id:e.id,className:typeof e.className==='string'?e.className:'',text:e.textContent?.slice(0,90),x:r.x,right:r.right,width:r.width,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth};})}));if(layout.documentWidth!==320){checks.push({name:'Document fits 320px viewport',status:'failed',layout});await persist();}const bounds=await m.locator('#image-library').boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=320);await capturePage(m,out+'/library-320px.png');await checkMobileLibrary(m);
 await m.getByRole('button',{name:'Close Custom image library',exact:true}).tap();await m.locator('#image-library').waitFor({state:'hidden'});await m.waitForTimeout(150);await m.getByRole('button',{name:'More build tools',exact:true}).tap();await m.getByRole('button',{name:'Custom images',exact:true}).tap();await m.getByPlaceholder('Search Custom').fill('Acceptance floor');await m.getByRole('button',{name:/^Place Acceptance floor \(/}).tap();await m.locator('#image-library').waitFor({state:'hidden'});await m.waitForTimeout(150);const before=await m.evaluate(()=>window.__universe.getState().scene.objects.length);let q;for(const [x,z] of [[-3,7],[-4,7],[-2,8],[0,9],[2,9]]){const candidate=await projected(x,z,0,m);const target=await m.evaluate(p=>({tag:document.elementFromPoint(p.x,p.y)?.tagName,id:document.elementFromPoint(p.x,p.y)?.id}),candidate);if(target.id==='game'){q=candidate;break;}}assert(q,'a projected point must be visibly on unobscured game canvas');const cdp=await mobile.newCDPSession(m);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:q.x,y:q.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await m.waitForFunction(n=>window.__universe.getState().scene.objects.length===n,before+1);await m.getByRole('button',{name:'↖ Select',exact:true}).tap();const headerLayout=await m.locator('.builder-heading').evaluate(root=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom};};return{title:rect(root.querySelector('.builder-title')),status:rect(root.querySelector('.editor-status')),done:rect(root.querySelector('.builder-done')),save:rect(root.querySelector('.builder-save')),room:rect(root.querySelector('.builder-room-settings')),header:rect(root)};});assert(headerLayout.status.y>=headerLayout.title.bottom,'dirty status must not overlap Build mode heading');for(const control of [headerLayout.room,headerLayout.save,headerLayout.done])assert(headerLayout.status.y>=control.bottom,'separate status row must not overlap Room, Save or Done');assert(headerLayout.status.x>=headerLayout.header.x&&headerLayout.status.right<=headerLayout.header.right,'status stays inside the header');await capturePage(m,out+'/placement-320px.png');await report('320px Custom library fits, close/reopen works, and real CDP touch places an image',{headerLayout});
 }catch(error){await capturePage(m,out+'/mobile-failure.png').catch(()=>{});await writeFile(out+'/mobile-failure-state.json',JSON.stringify({text:await m.locator('body').innerText().catch(()=>null),state:await m.evaluate(()=>window.__universe?.getState()).catch(()=>null),editor:await m.evaluate(()=>window.__universe?.getEditor()).catch(()=>null)},null,2));throw error;}finally{await mobile.close();}
}
try{if(scope==='mobile'){const session=await context.request.post(base+'/api/session',{data:{name:'Mobile image fixture'}});assert.equal(session.status(),201);const joined=await context.request.post(base+'/api/rooms/commons/join',{data:{}});assert.equal(joined.status(),200);const bytes=makePng({width:64,height:64,pixel:()=>[245,35,225,255]});const fixture=await context.request.post(base+'/api/rooms/commons/assets',{data:{draft:{name:'Acceptance floor',tags:'Mobile fixture',depthPreset:'floor',floating:true},operationId:'mobile-fixture',mediaType:'image/png',pngBase64:bytes.toString('base64')}});assert.equal(fixture.status(),201);limits.push('Mobile-only mode arranges its committed asset through local fixture API; full mode exercises the real file chooser/upload first');}else{await commonsFlow();await retryFlow();await compactFlow();}await mobileFlow();assert.deepEqual(errors,[]);await report('No unhandled runtime exceptions in bounded full-game acceptance');}
catch(error){console.error(error);checks.push({name:'Acceptance failure',status:'failed',error:error.stack});if(!page.isClosed())await capturePage(page,out+'/failure.png').catch(()=>{});await writeFile(out+'/failure-state.json',JSON.stringify({state:await state().catch(()=>null),editor:await editor().catch(()=>null),html:await page.locator('body').innerText().catch(()=>null)},null,2));process.exitCode=1;}
finally{if(checks.some(c=>c.status==='failed'))process.exitCode=1;await persist();await context.close();await browser.close();await app.close();}
