import test from 'node:test';import assert from 'node:assert/strict';
import{normalizeImageAssetDraft,validateImageDefinition}from'../src/image-asset-schema.js';
import{bindImageDefinitions,imageDefinitions,inheritImageDefinitions,imageGeometry}from'../src/image-asset-context.js';
import{clone,canStand,collisionBoxes,findPath}from'../src/worlds.js';
import{validatePlacement}from'../src/editor-geometry.js';
import{objectFootprint,editablePersonalArea}from'../src/personal-area-policy.js';
const stamp='2026-10-02T00:00:00.000Z';
function fixture(){const definition={schemaVersion:1,assetId:'asset1',roomId:'room1',createdBy:'user1',createdAt:stamp,originKind:'upload'},version={...normalizeImageAssetDraft({name:'Panel',floating:false,collisionGrid:[[0,0],[1,0]]},{width:64,height:64,byteLength:200,mediaType:'image/png'}),schemaVersion:1,assetId:'asset1',roomId:'room1',versionId:'v1',sequence:1,sha256:'f'.repeat(64),createdBy:'user1',createdAt:stamp},entry={...validateImageDefinition(definition,version),status:'active'},item={id:'image1',type:'image',assetRef:{assetId:'asset1',versionId:'v1'},x:0,z:0,rotation:0},scene={bounds:{width:20,depth:20},spawn:{x:0,z:7},objects:[item],areas:[]};return{entry,item,scene,definitions:{'asset1:v1':entry}};}
test('read projection is immutable and never serializes into a scene; clone retains its context',()=>{const f=fixture(),json=JSON.stringify(f.scene);bindImageDefinitions(f.scene,f.definitions,'room1');assert.equal(JSON.stringify(f.scene),json);assert(Object.isFrozen(imageDefinitions(f.scene)['asset1:v1'].version));const copy=clone(f.scene);assert.deepEqual(imageGeometry(copy,copy.objects[0]),imageGeometry(f.scene,f.item));assert.equal(JSON.stringify(copy),json);assert.deepEqual(imageDefinitions(clone({scene:f.scene}).scene),imageDefinitions(f.scene));});
test('definitions reject wrong room/key; scene-supplied metadata never resolves a reference',()=>{const f=fixture();assert.throws(()=>bindImageDefinitions(f.scene,f.definitions,'other'));assert.throws(()=>bindImageDefinitions(f.scene,{wrong:f.entry},'room1'));f.scene.imageDefinitions=f.definitions;assert.throws(()=>imageGeometry(f.scene,f.item));assert.equal(canStand(f.scene,8,8),false);});
test('manual and path movement use only authored occupied image cells, not full transparent extent',()=>{const f=fixture();bindImageDefinitions(f.scene,f.definitions,'room1');assert.equal(collisionBoxes(f.scene,f.item).length,1);assert.equal(canStand(f.scene,-.5,-.5),true);assert.equal(canStand(f.scene,-.5,.5),false);assert.equal(canStand(f.scene,.5,.5),true);assert(findPath(f.scene,{x:0,z:5},{x:.5,z:.5}).length);const copy=clone(f.scene);copy.objects[0].rotation=90;assert.equal(canStand(copy,-.5,-.5),false);assert.equal(canStand(copy,.5,-.5),true);});
test('placement distinguishes solid cells from image extent and rejects unresolved neighbors without throwing',()=>{const f=fixture();bindImageDefinitions(f.scene,f.definitions,'room1');const chair={id:'c',type:'chair',x:.5,z:-.5,width:.2,depth:.2};assert.equal(validatePlacement(f.scene,chair).valid,true);chair.x=-.5;chair.z=.5;assert.equal(validatePlacement(f.scene,chair).valid,false);f.scene.objects.push({...f.item,id:'unknown',assetRef:{assetId:'missing',versionId:'v1'}});assert.equal(validatePlacement(f.scene,{...chair,x:5,z:5}).valid,false);});
test('personal containment uses the whole image despite sparse collision; missing metadata denies',()=>{const f=fixture(),small={x:-.5,z:.5,width:1,depth:1,ownerId:'user1',canEditObjects:true},large={...small,x:0,z:0,width:2,depth:2};assert.equal(objectFootprint(f.item),null);assert.equal(editablePersonalArea([small],f.item,'user1',f.definitions),null);assert.equal(editablePersonalArea([large],f.item,'user1',f.definitions),large);assert.equal(objectFootprint({...f.item,scale:.1},f.definitions),null);});
test('scene derivations deliberately inherit context; geometry cache tracks changed pose and references',()=>{const f=fixture();bindImageDefinitions(f.scene,f.definitions,'room1');const before=imageGeometry(f.scene,f.item);f.item.x=3;assert.notEqual(imageGeometry(f.scene,f.item),before);const next=inheritImageDefinitions(f.scene,{...f.scene,objects:[]});assert.equal(imageDefinitions(next),imageDefinitions(f.scene));f.item.assetRef.versionId='missing';assert.throws(()=>imageGeometry(f.scene,f.item));});
