import {build} from 'esbuild';
import {mkdtemp,cp,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
import {launch} from '../scripts/browser.mjs';
import {seedWorlds,emptyScene} from '../src/worlds.js';
import {createGameServer} from '../server/app.mjs';
const dir=await mkdtemp(join(tmpdir(),'live-feedback-motion-')),out='evidence/live-feedback-motion';await mkdir(out,{recursive:true});await cp('public',dir,{recursive:true});await build({entryPoints:['src/main.js'],outdir:dir,bundle:true,format:'esm',splitting:true,minify:true,target:'es2022'});
const seeds=structuredClone(seedWorlds);seeds[0].rooms[0].scene={...emptyScene(),spawn:{x:0,z:4},objects:[{id:'jump-platform',type:'table',name:'Jump platform',x:0,z:0,width:3,depth:3},{id:'test-chair',type:'chair',name:'Chair',x:4,z:4,rotation:0}],areas:[]};
const app=createGameServer({seeds,dist:dir}),{port}=await app.listen(0),base='http://127.0.0.1:'+port,browser=await launch(),errors=[],checks=[];let alice,bob;
const check=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
const pos=p=>p.evaluate(()=>__universe.getState().position);
async function enter(name){const context=await browser.newContext({viewport:{width:1280,height:800}}),p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(60000);await p.goto(base,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe);await p.getByPlaceholder('Your name').fill(name);await p.locator('#join-button').click();await p.waitForFunction(()=>__universe.getState().ready);const no=p.getByRole('button',{name:'Not now',exact:true});if(await no.isVisible())await no.click();return p;}
async function point(p,x,z,y=0){return p.evaluate(({x,z,y})=>__universe.getScreenPoint(x,z,y),{x,z,y});}
async function walk(p,x,z){await p.locator('#game').focus();const q=await point(p,x,z);await p.mouse.click(q.x,q.y);await p.waitForFunction(({x,z})=>Math.hypot(__universe.getState().position.x-x,__universe.getState().position.z-z)<.35,{x,z});await p.waitForTimeout(200);}
async function yaw(p,target){const before=await p.evaluate(()=>__universe.getCamera().yaw);await p.mouse.move(750,330);await p.mouse.down({button:'right'});await p.mouse.move(750-(target-before)/.006,330,{steps:3});await p.mouse.up({button:'right'});await p.locator('#game').focus();}
try{
 alice=await enter('Physics builder');bob=await enter('Physics peer');await alice.bringToFront();await yaw(alice,Math.PI/2);await alice.keyboard.down('w');await alice.waitForFunction(()=>__universe.getState().position.z<1.9&&__universe.getMotion().speed<.01);await alice.keyboard.up('w');await alice.waitForTimeout(100);let p=await pos(alice);assert(p.z>=1.79&&p.z<1.9);assert.equal(p.y,0);check('native keyboard cannot walk through the visible solid furniture');
 await alice.keyboard.down('w');await alice.keyboard.press('Space');await alice.waitForFunction(()=>__universe.getState().position.y>1&&__universe.getState().position.z<1.3);await alice.keyboard.up('w');await alice.waitForFunction(()=>__universe.getMotion().grounded&&__universe.getState().position.y===1.01);p=await pos(alice);assert(Math.abs(p.z)<1.5);const actorId=await alice.evaluate(()=>__universe.getState().user.id);await bob.waitForFunction(id=>__universe.getState().people.some(p=>p.id===id&&p.y===1.01),actorId);await alice.screenshot({path:out+'/landed-on-furniture.png'});check('Space jumps with gravity and lands on furniture top; peer receives elevated presence');
 await alice.keyboard.down('s');await alice.waitForFunction(()=>__universe.getState().position.z>2.3);await alice.keyboard.up('s');await alice.waitForFunction(()=>__universe.getMotion().grounded&&__universe.getState().position.y===0);check('walking off obstacle falls to the floor');
 await walk(alice,4,5.5);await alice.keyboard.press('t');await alice.waitForFunction(()=>__universe.getMotion().seatId==='test-chair');await bob.waitForFunction(id=>__universe.getState().people.some(p=>p.id===id&&p.seatId==='test-chair'&&p.seatHeight===.61),actorId);await alice.screenshot({path:out+'/seated-on-chair.png'});check('T sits on a nearby chair and server broadcasts canonical seated pose');
 await alice.locator('#dock-emote').click();await alice.getByRole('button',{name:'👋 Wave',exact:true}).click();await bob.waitForFunction(id=>__universe.getStats().presentation.actors.some(p=>p.id===id&&p.waving),actorId);check('visible Wave action animates the remote 3D avatar');await alice.locator('.express-tray').waitFor({state:'hidden'});await alice.locator('#game').focus();await alice.keyboard.press('Space');await alice.waitForFunction(()=>__universe.getMotion().seatId===null&&__universe.getState().position.y>0);await alice.waitForFunction(()=>__universe.getMotion().grounded);check('Space stands safely and jumps from a seat');
 await yaw(alice,Math.PI/2);await alice.mouse.move(700,370);await alice.mouse.down({button:'right'});await alice.mouse.move(700,110,{steps:5});await alice.mouse.up({button:'right'});await alice.locator('#game').focus();for(let i=0;i<20;i++)await alice.keyboard.press('+');const camera=await alice.evaluate(()=>__universe.getCamera());assert(camera.tilt<.02);assert.equal(camera.distance,6);await alice.screenshot({path:out+'/low-front-camera.png'});check('camera reaches near-horizontal close front view');await alice.getByRole('button',{name:'Reset camera',exact:true}).click();
 // Author real terrain through the native palette, save it, then verify a reload
 // and independent peer both use the committed collision mask.
 await alice.locator('#dock-build').click();await alice.getByRole('button',{name:'Terrain',exact:true}).click();await alice.getByRole('button',{name:'Paint stone',exact:true}).click();await alice.getByRole('checkbox',{name:'Blocks walking',exact:true}).check();const close=alice.getByRole('button',{name:'Close terrain palette',exact:true});if(await close.isVisible())await close.click();const a=await point(alice,-4.5,4.5),b=await point(alice,-2.5,4.5);await alice.mouse.move(a.x,a.y);await alice.mouse.down();await alice.mouse.move(b.x,b.y,{steps:5});await alice.mouse.up();await alice.waitForFunction(()=>__universe.getState().scene.terrain?.cells.some(c=>c[3]));await alice.getByRole('button',{name:'Save room',exact:true}).click();await alice.waitForFunction(()=>!__universe.getEditor().dirty);await alice.locator('#dock-build').click();const terrain=await alice.evaluate(()=>__universe.getState().scene.terrain);await alice.reload({waitUntil:'domcontentloaded'});await alice.waitForFunction(()=>window.__universe?.getState().ready);assert.deepEqual(await alice.evaluate(()=>__universe.getState().scene.terrain),terrain);await walk(alice,-3.5,6);await yaw(alice,Math.PI/2);await alice.keyboard.down('w');await alice.waitForFunction(()=>__universe.getState().position.z<5.6&&__universe.getMotion().speed<.01);await alice.keyboard.up('w');p=await pos(alice);assert(p.z>=5.29&&p.z<5.6);check('native painted Blocks walking terrain survives save/reload and stops manual movement');
 await alice.setViewportSize({width:390,height:844});await alice.locator('#jump-button').waitFor({state:'visible'});const jumpRect=await alice.locator('#jump-button').boundingBox();await alice.mouse.move(jumpRect.x+jumpRect.width/2,jumpRect.y+jumpRect.height/2);await alice.mouse.down();await alice.waitForFunction(()=>__universe.getState().position.y>0);await alice.waitForFunction(()=>__universe.getMotion().grounded);await alice.mouse.up();await alice.waitForTimeout(150);assert.equal((await pos(alice)).y,0);check('holding mobile Jump through landing does not jump again on pointer release');await alice.screenshot({path:out+'/mobile-jump-controls.png'});
 assert.deepEqual(errors,[]);
}catch(error){console.error(error);checks.push({name:'failure',status:'failed',error:error.stack});if(alice&&!alice.isClosed()){console.error(await alice.evaluate(()=>({position:__universe.getState().position,motion:__universe.getMotion(),camera:__universe.getCamera(),editor:__universe.getEditor(),toast:document.querySelector('#toast').textContent})).catch(()=>{}));await alice.screenshot({path:out+'/failure.png'}).catch(()=>{});}process.exitCode=1;}finally{await writeFile(out+'/results.json',JSON.stringify({checks,errors,limits:['Isolated local synthetic accounts and temporary scene; no live service changes','Native keyboard and pointer interaction, read-only app diagnostics','Software WebGL; physical-phone acceptance remains unverified']},null,2));await browser.close();await app.close();await rm(dir,{recursive:true,force:true});}
