// Full game + local server, real layout/touch. Capture is prohibited by injected
// failing functions; this test never accesses a camera, microphone or live account.
import assert from 'node:assert/strict';
import {mkdtemp,cp,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {build} from 'esbuild';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds} from '../src/worlds.js';
const dir=await mkdtemp(join(tmpdir(),'universe-live-layout-'));await cp('public',dir,{recursive:true});await build({entryPoints:['src/main.js'],outdir:dir,bundle:true,format:'esm',splitting:true,minify:true,target:'es2022'});
const app=createGameServer({seeds:structuredClone(seedWorlds),dist:dir}),address=await app.listen(0),browser=await launch(),context=await browser.newContext({viewport:{width:1280,height:800},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage(),checks=[],errors=[];page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.captureAttempts=0;Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:()=>{captureAttempts++;throw Error('Physical capture is forbidden in this layout test');}});Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{value:()=>{captureAttempts++;throw Error('Physical capture is forbidden in this layout test');}});});
const check=async(name,fn)=>{await fn();checks.push({name,status:'passed'});console.log('PASS',name)};
const reachable=async locator=>{await locator.scrollIntoViewIfNeeded();const detail=await locator.evaluate(n=>{const b=n.getBoundingClientRect(),hit=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2);return{label:n.getAttribute('aria-label')||n.textContent,rect:{x:b.x,y:b.y,width:b.width,height:b.height},hit:hit?.id||hit?.className,ok:b.x>=0&&b.right<=innerWidth+1&&b.y>=0&&b.bottom<=innerHeight+1&&n.contains(hit)};});assert(detail.ok,JSON.stringify(detail));assert(detail.rect.width>=44&&detail.rect.height>=44,JSON.stringify(detail));};
const more=()=>page.locator('#dock-more');
try{
 await mkdir('evidence',{recursive:true});await page.goto('http://127.0.0.1:'+address.port,{waitUntil:'domcontentloaded'});await page.getByPlaceholder('Your name').fill('Layout reviewer');await page.locator('#join-button').click();await page.waitForFunction(()=>window.__universe?.getState().ready);await page.waitForTimeout(300);
 await check('welcome prompt and real save toast cannot intercept joystick or Jump',async()=>{
  await page.setViewportSize({width:390,height:844});await page.locator('.quest-invitation').waitFor({state:'visible'});
  await page.locator('#dock-build').click();await page.getByRole('button',{name:'Terrain',exact:true}).click();await page.getByRole('button',{name:'Paint soil',exact:true}).click();await page.getByRole('button',{name:'Close terrain palette',exact:true}).click();await page.locator('#game').focus();await page.keyboard.press('Space');await page.keyboard.press('Control+s');await page.waitForFunction(()=>!__universe.getEditor().dirty);await page.locator('#dock-build').click();await page.locator('.quest-invitation').waitFor({state:'visible'});await page.locator('#toast').waitFor({state:'visible'});
  assert.equal(await page.locator('#toast').evaluate(n=>getComputedStyle(n).pointerEvents),'none');
  for(const side of ['right','left']){if(await page.locator('#app').getAttribute('data-movement-side')!==side)await page.locator('#movement-side-toggle').click();for(const id of ['joystick','jump-button','movement-side-toggle','dock-more'])await reachable(page.locator('#'+id));await reachable(page.locator('.quest-invitation').getByRole('button',{name:'Not now',exact:true}));}
  await page.locator('#movement-side-toggle').click();assert.equal(await page.locator('#app').getAttribute('data-movement-side'),'right');
  const stick=await page.locator('#joystick').boundingBox(),jump=await page.locator('#jump-button').boundingBox(),cdp=await context.newCDPSession(page),finger={id:1,x:stick.x+stick.width/2+5,y:stick.y+stick.height/2},jumpFinger={id:2,x:jump.x+jump.width/2,y:jump.y+jump.height/2};
  await page.screenshot({path:'evidence/live-layout-welcome-toast-controls.png'});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[finger]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[finger,jumpFinger]});await page.waitForFunction(()=>__universe.getState().position.y>0);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>__universe.getMotion().grounded);assert(await page.locator('.quest-invitation').isVisible());await cdp.detach();await page.setViewportSize({width:1280,height:800});
 });const later=page.getByRole('button',{name:'Not now',exact:true});if(await later.isVisible())await later.click();
 await check('real desktop media dock leaves all world camera controls reachable',async()=>{await page.locator('#dock-media').click();for(const id of['zoom-in','zoom-out','camera-follow'])await reachable(page.locator('#'+id));await reachable(page.locator('.media-join'));await page.screenshot({path:'evidence/live-layout-desktop-media.png'});await page.locator('#dock-media').click();});
 await check('phone control geometry, mirrored movement controls and More remain reachable',async()=>{for(const [width,height]of[[390,844],[320,568],[844,390]]){await page.setViewportSize({width,height});await page.waitForTimeout(120);for(const id of['zoom-in','zoom-out','camera-follow','jump-button','movement-side-toggle','dock-more'])await reachable(page.locator('#'+id));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const banner=await page.locator('#area-banner').boundingBox();if(banner)for(const id of['zoom-in','movement-side-toggle','jump-button']){const control=await page.locator('#'+id).boundingBox();assert(banner.x+banner.width<=control.x||control.x+control.width<=banner.x||banner.y+banner.height<=control.y||control.y+control.height<=banner.y,JSON.stringify({width,banner,control,id}));}await page.locator('#movement-side-toggle').click();assert.equal(await page.locator('#app').getAttribute('data-movement-side'),'left');const stick=await page.locator('#joystick').boundingBox();assert(stick.x<100);for(const id of['zoom-in','zoom-out','camera-follow','jump-button','movement-side-toggle','dock-more'])await reachable(page.locator('#'+id));await reachable(page.locator('#joystick'));await page.locator('#movement-side-toggle').click();assert.equal(await page.locator('#app').getAttribute('data-movement-side'),'right');await more().click();await reachable(page.getByRole('button',{name:'Close More',exact:true}));for(const label of['Connect','Express','Quests','Zoom in','Orbit right'])await reachable(page.locator('#shell-more').getByRole('button',{name:label,exact:true}));assert.equal(await page.locator('#jump-button').isVisible(),false);await page.screenshot({path:'evidence/live-layout-more-'+width+'.png'});await page.getByRole('button',{name:'Close More',exact:true}).click();await page.screenshot({path:'evidence/live-layout-world-'+width+'.png'});}});
 await check('phone Connect and scrolling media settings keep close/choices onscreen with no capture',async()=>{await page.setViewportSize({width:390,height:844});await more().click();await page.locator('#shell-more').getByRole('button',{name:'Connect',exact:true}).click();await reachable(page.locator('.media-join'));await reachable(page.locator('#zoom-in'));await page.locator('.media-details-toggle').click();await reachable(page.getByRole('button',{name:'Close media settings'}));await page.locator('.media-keep-microphone').scrollIntoViewIfNeeded();await reachable(page.getByRole('button',{name:'Close media settings'}));await page.screenshot({path:'evidence/live-layout-settings-phone.png'});await page.getByRole('button',{name:'Close media settings'}).click();assert.equal(await page.evaluate(()=>captureAttempts),0);await more().click();await page.locator('#shell-more').getByRole('button',{name:'Connect',exact:true}).click();});
 await check('Explore detail uses an inset scrollable sheet with reachable controls',async()=>{for(const [width,height]of[[390,844],[320,568],[844,390]]){await page.setViewportSize({width,height});await page.locator('#dock-explore').click();await page.locator('#places').waitFor({state:'visible'});await reachable(page.locator('.places-close'));if(await page.locator('.places-tree-world').first().isVisible())await page.locator('.places-tree-world').first().click();await page.locator('.places-detail-title').waitFor();for(const text of['Edit details','New room','Members & invitations']){const target=page.locator('.places-detail').getByRole('button',{name:new RegExp(text)});if(await target.count())await reachable(target.first());}const box=await page.locator('#places').boundingBox();assert(box.x>=8&&box.x+box.width<=width-8);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'evidence/live-layout-explore-'+width+'.png'});await page.locator('.places-close').click();}});
 await check('full-sheet Chat owns touch layer and dismiss restores movement controls',async()=>{await page.setViewportSize({width:390,height:844});await page.locator('#dock-chat').click();assert.equal(await page.locator('#jump-button').isVisible(),false);assert.equal(await page.locator('#movement-side-toggle').isVisible(),false);assert.equal(await page.locator('#joystick').isVisible(),false);await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('#social').hidden);await reachable(page.locator('#jump-button'));});
 await check('small fine-pointer viewport at 200% text has no hidden keyboard-strip overflow',async()=>{const fine=await browser.newContext({viewport:{width:320,height:680},storageState:await context.storageState(),reducedMotion:'reduce'});try{const p=await fine.newPage();await p.addInitScript(()=>{Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:()=>{throw Error('Capture forbidden in layout test');}});});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+address.port,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe?.getState().ready);await p.evaluate(()=>document.documentElement.style.fontSize='200%');await p.waitForTimeout(300);assert(await p.evaluate(()=>matchMedia('(pointer:fine)').matches));assert.equal(await p.locator('#controls-hint').isVisible(),false);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),320);}finally{await fine.close();}});
 assert.deepEqual(errors,[]);
}catch(error){console.error(error);checks.push({name:'failure',error:error.stack});process.exitCode=1;await page.screenshot({path:'evidence/live-layout-full-failure.png'}).catch(()=>{});}
finally{await writeFile('evidence/live-layout-full-results.json',JSON.stringify({checks,errors,limits:['Local isolated game server and ephemeral reviewer profile','Software WebGL plus native browser input and viewport emulation; no physical iOS Safari certification','No device capture, external service, live account change or deployment']},null,2));await browser.close();await app.close();await rm(dir,{recursive:true,force:true});}
