// Native DOM/input/layout and native synthetic canvas video. Real device APIs
// are replaced, and Permissions-Policy denies physical capture in this fixture.
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {build} from 'esbuild';
import {launch} from '../scripts/browser.mjs';
const source=`import {mountMedia} from './src/media.js';import {mountActionRuntime} from './src/action-runtime.js';
window.captures=[];window.fixtureTracks=[];let enabled=false;window.kind='meeting';
window.fixtureState={user:{id:'fixture-user'},ready:true,room:{id:'r',revision:1},scene:{objects:[],areas:[{id:'a',name:'Welcome corner',x:0,z:0,width:4,depth:4,message:'Welcome to the studio. Take a seat and turn on your microphone when you are ready to talk.',actions:[{id:'note',type:'message',name:'A readable welcome',message:'This automatically triggered message remains readable until you leave this area or dismiss it. You can keep walking, use touch controls, and read at your own pace.',trigger:'enter'}]}]},position:{x:0,z:0}};
const devices=new EventTarget();devices.enumerateDevices=async()=>[{kind:'videoinput',deviceId:'camera-a',label:'Fixture camera A'},{kind:'videoinput',deviceId:'camera-b',label:'Fixture camera B'},{kind:'audioinput',deviceId:'mic-a',label:'Fixture microphone'}];
devices.getUserMedia=async options=>{captures.push(options);if(!options.video)throw Object.assign(Error('Denied test microphone'),{name:'NotAllowedError'});const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const context=canvas.getContext('2d');context.fillStyle='#7d4eff';context.fillRect(0,0,320,180);context.fillStyle='#fff';context.fillRect(20,20,60,60);const stream=canvas.captureStream(5);fixtureTracks.push(...stream.getTracks());return stream;};
Object.defineProperty(navigator,'mediaDevices',{value:devices});
const policy=()=>({selfId:'fixture-user',roomId:'r',enabled,context:{kind,group:kind==='meeting'?'studio':null,canPublish:kind!=='silent',label:'Studio meeting'},peers:[]});
const api=async(path,options={})=>{if(path.endsWith('/actions/resolve'))return{revision:1,entity:{name:'Welcome corner'},action:fixtureState.scene.areas[0].actions[0]};if(path==='/api/media/state')enabled=options.body.enabled;return policy();};
window.media=mountMedia({root:document.querySelector('#media'),api,getState:()=>fixtureState});
window.dialogs=[];window.actionRuntime=mountActionRuntime({root:document.querySelector('#embedded-content'),controlsRoot:document.querySelector('#area-sounds'),api,getState:()=>fixtureState,onDialog:dialog=>dialogs.push(dialog)});
window.pushSilent=()=>{kind='silent';media.onEvent({type:'media-policy',data:policy()});};
window.exitArea=()=>{fixtureState.position={x:10,z:10};actionRuntime.update();};
window.enterArea=()=>{fixtureState.position={x:0,z:0};actionRuntime.update();};
window.worldKeys=[];window.addEventListener('keydown',event=>worldKeys.push(event.key));
`;
const bundle=await build({stdin:{contents:source,resolveDir:process.cwd()},bundle:true,format:'iife',write:false});
const css=(await Promise.all(['public/universe-tokens.css','public/style.css','src/media.css','src/action-runtime.css','src/hud-availability.css'].map(path=>readFile(path,'utf8')))).join('\n').replace(/@import[^;]+;/g,'');
const pageMarkup=await readFile('public/index.html','utf8');
const content=pageMarkup.replace(/<head>[\s\S]*?<\/head>/,`<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>${css}</style></head>`).replace('<script type="module" src="/main.js"></script>','').replace('<div id="media" hidden>','<div id="media">').replace('<section id="welcome" class="modal-backdrop"','<section id="welcome" hidden class="modal-backdrop"').replace('</div></body>','<div id="embedded-content"></div></div></body>');
const browser=await launch(),context=await browser.newContext({viewport:{width:1100,height:760},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage(),checks=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));await context.route('https://media-shell.invalid/**',route=>route.fulfill({contentType:'text/html',headers:{'Permissions-Policy':'microphone=(), camera=(), display-capture=()'},body:content}));
const check=async(name,fn)=>{await fn();checks.push({name,status:'passed'});console.log('PASS',name);};
const reachable=async locator=>{const b=await locator.boundingBox();assert(b&&b.width>=44&&b.height>=44);assert(await locator.evaluate(n=>{const b=n.getBoundingClientRect();return b.x>=0&&b.right<=innerWidth+1&&b.y>=0&&b.bottom<=innerHeight+1&&n.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2));}),await locator.getAttribute('id')||await locator.getAttribute('class'));};
try{
 await mkdir('evidence',{recursive:true});await page.goto('https://media-shell.invalid/');await page.addScriptTag({content:bundle.outputFiles[0].text});await page.waitForFunction(()=>media.getStatus().policy);
 await check('camera and audio overlays occupy separate lanes at desktop and compact widths',async()=>{for(const [width,height]of[[1100,760],[1030,595],[768,800],[390,844],[320,568],[844,390]]){await page.setViewportSize({width,height});await page.waitForTimeout(30);await reachable(page.locator('#zoom-in'));await reachable(page.locator('.media-join'));const a=await page.locator('#view-controls').boundingBox(),b=await page.locator('.media-dock').boundingBox();assert(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y,JSON.stringify({width,a,b}));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await page.screenshot({path:'evidence/live-media-landscape.png'});});
 await page.setViewportSize({width:390,height:844});
 await check('settings list and input choices request no devices and preserve touch/keyboard access',async()=>{await page.locator('.media-details-toggle').click();await page.waitForFunction(()=>!media.getStatus().listingDevices);assert.equal(await page.evaluate(()=>captures.length),0);await page.locator('[data-media-setting=camera]').selectOption('camera-b');assert.equal(await page.evaluate(()=>captures.length),0);await reachable(page.locator('.media-settings-close'));await page.locator('[data-media-setting=camera]').focus();await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>worldKeys.includes('ArrowDown')),false);await page.keyboard.press('Escape');assert.equal(await page.locator('.media-details').isHidden(),true);await page.locator('.media-details-toggle').click();});
 await check('explicit camera start displays native synthetic stream in muted inline mirrored preview',async()=>{await page.locator('.media-settings-camera').click();await page.waitForFunction(()=>media.getStatus().devices.camera.status==='on');await page.waitForFunction(()=>document.querySelector('.media-self-preview video').videoWidth>0);const state=await page.locator('.media-self-preview video').evaluate(n=>({muted:n.muted,inline:n.playsInline,width:n.videoWidth,live:n.srcObject.getTracks()[0].readyState,transform:getComputedStyle(n).transform}));assert.equal(state.muted,true);assert.equal(state.inline,true);assert.equal(state.width,320);assert.equal(state.live,'live');assert.match(state.transform,/-1/);await page.locator('[data-media-setting=mirror]').uncheck();assert.equal(await page.locator('.media-self-preview video').evaluate(n=>getComputedStyle(n).transform),'none');await page.screenshot({path:'evidence/live-media-self-preview-phone.png'});});
 await check('switch camera fences old tracks, microphone denial is honest and Silent clears self preview',async()=>{await page.locator('[data-media-setting=camera]').selectOption('camera-a');await page.waitForFunction(()=>captures.length===2&&media.getStatus().devices.camera.status==='on');assert.equal(await page.evaluate(()=>fixtureTracks[0].readyState),'ended');await page.locator('.media-settings-microphone').click();await page.waitForFunction(()=>media.getStatus().devices.microphone.status==='error');assert.match(await page.locator('.media-warning').innerText(),/not allowed/);assert.match(await page.locator('[data-capture-error=microphone]').innerText(),/not allowed/);await page.evaluate(()=>pushSilent());assert.equal(await page.locator('.media-self-preview video').evaluate(n=>n.srcObject),null);assert.equal(await page.evaluate(()=>fixtureTracks.every(t=>t.readyState==='ended')),true);assert.equal(await page.locator('.media-settings-camera').isDisabled(),true);});
 await check('readable entry messages are nonmodal, persistent, dismissible and cleared on exit',async()=>{await page.locator('.media-settings-close').click();await page.evaluate(()=>{document.querySelector('#media').hidden=true;enterArea();});await page.locator('.area-entry-message').waitFor();assert.equal(await page.evaluate(()=>dialogs.length),0);assert(Number(await page.locator('.area-entry-message p').evaluate(n=>parseFloat(getComputedStyle(n).fontSize)))>=14);await page.locator('#game').focus();await page.keyboard.press('w');assert(await page.evaluate(()=>worldKeys.includes('w')));await page.locator('.area-entry-message button').click();assert.equal(await page.locator('.area-entry-messages').isHidden(),true);await page.evaluate(()=>{actionRuntime.update({suppressed:true});actionRuntime.update();});await page.waitForTimeout(30);assert.equal(await page.locator('.area-entry-messages').isHidden(),true);await page.evaluate(()=>exitArea());await page.evaluate(()=>enterArea());await page.locator('.area-entry-message').waitFor();await page.screenshot({path:'evidence/live-area-message-phone.png'});await page.evaluate(()=>exitArea());assert.equal(await page.locator('.area-entry-message').count(),0);});
 await page.evaluate(()=>{media.destroy();actionRuntime.destroy();});assert.deepEqual(errors,[]);
}catch(error){checks.push({name:'failure',error:error.stack});console.error(error);process.exitCode=1;await page.screenshot({path:'evidence/live-media-layout-failure.png'}).catch(()=>{});}
finally{await writeFile('evidence/live-media-layout-results.json',JSON.stringify({checks,errors,limits:['Native synthetic canvas MediaStream; no physical camera or microphone used','Local routed fixture with authoritative policy injection; no live server/account or transport success claimed','Viewport/touch emulation is not physical phone certification']},null,2));await context.close();await browser.close();}
