// Injected devices only. These assertions are ownership/lifecycle proof, not physical capture.
import test from 'node:test';
import assert from 'node:assert/strict';
import {createMediaSession} from '../src/media.js';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{resolve,promise};};
function fixture(){
 const calls=[],tracks=[],events=new Map();let capture,enumerate;const state={user:{id:'a'},room:{id:'r'},ready:true};
 let policy={selfId:'a',roomId:'r',enabled:false,context:{kind:'meeting',group:'meeting1',canPublish:true},peers:[]};
 const list=[{deviceId:'cam1',kind:'videoinput',label:'First camera'},{deviceId:'cam2',kind:'videoinput',label:'Second camera'},{deviceId:'mic1',kind:'audioinput',label:'Microphone'}];
 const device=kind=>{const track={kind,readyState:'live',stop(){this.readyState='ended';}};tracks.push(track);return{getTracks:()=>[track]};};
 const env={isSecureContext:true,RTCPeerConnection:class{},setTimeout,clearTimeout,navigator:{mediaDevices:{enumerateDevices:()=>enumerate?enumerate():Promise.resolve(list),getUserMedia:args=>{calls.push(args);return capture?capture(args):Promise.resolve(device(args.video?'video':'audio'));},addEventListener:(n,fn)=>events.set(n,fn),removeEventListener:(n)=>events.delete(n)}}};
 const session=createMediaSession({env,getState:()=>state,api:async(path,options={})=>{if(path==='/api/media/state')policy={...policy,enabled:options.body.enabled};return structuredClone(policy);}});
 return{session,calls,tracks,list,events,state,device,setCapture:fn=>capture=fn,setEnumerate:fn=>enumerate=fn,push:value=>{policy={...policy,...value};session.acceptPolicy(policy);}};
}
test('listing devices, quality and mirror choice never capture or join',async t=>{const f=fixture();t.after(()=>f.session.destroy());await f.session.refreshDevices();assert.equal(f.calls.length,0);await f.session.setCaptureSetting('camera','cam2');await f.session.setCaptureSetting('cameraQuality','high');await f.session.setCaptureSetting('mirror',false);assert.equal(f.calls.length,0);assert.equal(f.session.snapshot().joined,false);assert.equal(f.session.snapshot().settings.camera,'cam2');assert.equal(await f.session.setCaptureSetting('camera','missing'),false);});
test('active device switch stops old track and uses exact chosen device plus quality',async t=>{const f=fixture();t.after(()=>f.session.destroy());await f.session.refreshDevices();await f.session.toggleDevice('camera');const old=f.tracks[0];await f.session.setCaptureSetting('camera','cam2');assert.equal(old.readyState,'ended');assert.deepEqual(f.calls[1].video.deviceId,{exact:'cam2'});await f.session.setCaptureSetting('cameraQuality','high');assert.equal(f.tracks[1].readyState,'ended');assert.equal(f.calls[2].video.width.ideal,1280);assert.equal(f.calls[2].video.height.ideal,720);});
test('changed microphone noise settings recapture only the already active microphone',async t=>{const f=fixture();t.after(()=>f.session.destroy());await f.session.setCaptureSetting('noiseSuppression',false);assert.equal(f.calls.length,0);await f.session.toggleDevice('microphone');assert.equal(f.calls[0].audio.noiseSuppression,false);await f.session.setCaptureSetting('echoCancellation',false);assert.equal(f.tracks[0].readyState,'ended');assert.equal(f.calls[1].audio.echoCancellation,false);assert.equal(f.session.snapshot().devices.camera.status,'off');});
test('changing settings cancels pending capture without starting another and fences late stream',async t=>{const f=fixture();t.after(()=>f.session.destroy());await f.session.refreshDevices();await f.session.refreshPolicy(true);const wait=deferred();f.setCapture(()=>wait.promise);const pending=f.session.toggleDevice('camera');await f.session.setCaptureSetting('camera','cam2');assert.equal(f.calls.length,1);const late=f.device('video');wait.resolve(late);assert.equal(await pending,false);assert.equal(late.getTracks()[0].readyState,'ended');assert.equal(f.session.snapshot().devices.camera.status,'off');});
test('silent during replacement capture and exit never resumes a device',async t=>{const f=fixture();t.after(()=>f.session.destroy());await f.session.refreshDevices();await f.session.toggleDevice('camera');const wait=deferred();f.setCapture(()=>wait.promise);const pending=f.session.setCaptureSetting('camera','cam2');f.push({context:{kind:'silent',canPublish:false}});f.push({context:{kind:'meeting',group:'meeting1',canPublish:true}});const late=f.device('video');wait.resolve(late);assert.equal(await pending,false);assert.equal(late.getTracks()[0].readyState,'ended');assert.equal(f.session.snapshot().devices.camera.status,'off');assert.equal(f.calls.length,2);});
test('latest enumeration wins, hotplug never captures and destroy removes listener',async()=>{const f=fixture(),old=deferred(),fresh=deferred();let n=0;f.setEnumerate(()=>++n===1?old.promise:fresh.promise);const p=f.session.refreshDevices(),q=f.session.refreshDevices();fresh.resolve(f.list.slice(0,1));await q;old.resolve(f.list);await p;assert.equal(f.session.snapshot().availableDevices.length,1);assert.equal(f.calls.length,0);f.session.destroy();assert.equal(f.events.has('devicechange'),false);});
