// GPU-free DOM behavior only: RTC is a controlled class; capture APIs throw if called.
// This never requests real microphone, camera, screen access or external connections.
import {createServer} from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(process.env.MEDIA_TEST_DEPS || import.meta.url);
const {chromium}=require('playwright-core');const embedded=(await import(require.resolve('@sparticuz/chromium'))).default;
const root=new URL('../',import.meta.url), results=[];
const server=createServer(async(req,res)=>{
 try{const path=new URL(req.url,'http://localhost').pathname;
 if(['/src/media.js','/src/media-ice.js','/src/media-away.js','/src/media.css','/src/media-policy-copy.js'].includes(path)){res.setHeader('Content-Type',path.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(new URL('.'+path,root)));return;}
 res.setHeader('Permissions-Policy','microphone=(), camera=(), display-capture=()');res.setHeader('Content-Type','text/html');res.end(`<!doctype html><html><head><link rel="stylesheet" href="/src/media.css"><style>body{font-family:Arial;color:#eee;background:#18131f}#media{position:absolute;bottom:20px;left:12px;max-width:calc(100vw - 24px)}</style></head><body><div id="media"></div><script type="module">import {mountMedia} from '/src/media.js';window.captureAttempts=0;window.peerAttempts=0;window.stateCalls=[];
 for(const name of ['getUserMedia','getDisplayMedia'])Object.defineProperty(navigator.mediaDevices,name,{configurable:true,value:()=>{captureAttempts++;throw Error('Capture prohibited by controlled fixture');}});
 window.RTCPeerConnection=class{constructor(){peerAttempts++;throw Error('No peer transport expected in this DOM fixture');}};
 window.policy={selfId:'a',roomId:'r',enabled:false,context:{kind:'silent',label:'Garden',canPublish:false,reason:'Legacy proximity-only message'},peers:[]};
 window.api=async(path,options={})=>{if(path==='/api/media/state'){stateCalls.push(options.body.enabled);policy.enabled=options.body.enabled;}return structuredClone(policy);};
 window.media=mountMedia({root:document.querySelector('#media'),api,getState:()=>({user:{id:'a'},room:{id:'r'}})});
 window.push=changes=>{policy={...policy,...changes};media.onEvent({type:'media-policy',data:structuredClone(policy)});};</script></body></html>`);
 }catch(error){res.statusCode=500;res.end(error.message);}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${server.address().port}`;let browser;
try{
 browser=await chromium.launch({executablePath:await embedded.executablePath(),headless:true,args:['--no-sandbox','--no-zygote','--disable-gpu']});
 const page=await browser.newPage({viewport:{width:1280,height:860}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>new URL(route.request().url()).origin===url?route.continue():route.abort());await page.goto(url);await page.waitForFunction(()=>window.media?.getStatus().policy?.context.kind==='silent');
 assert.equal(await page.locator('.media-join').isDisabled(),true);assert.match(await page.locator('.media-context-detail').textContent(),/No calls here.*microphone, camera and screen sharing are off.*incoming calls are blocked/);for(const kind of ['microphone','camera','screen'])assert.equal(await page.locator(`[data-media="${kind}"]`).isDisabled(),true);
 await page.locator('.media-join').dispatchEvent('click');assert.deepEqual(await page.evaluate(()=>stateCalls),[]);await page.locator('.media-details-toggle').click();assert.equal(await page.locator('.media-retry').isDisabled(),true);assert.match(await page.locator('.media-policy-detail').textContent(),/listening can resume if you stayed joined.*Turn devices on again/);results.push({test:'Silent shows full policy before join; join/devices/retry disabled and direct click guarded',pass:true});
 const screenshots=[];for(const viewport of [{width:1280,height:860},{width:640,height:360},{width:320,height:700}]){await page.setViewportSize(viewport);await page.screenshot({path:new URL(`evidence/media-silent-${viewport.width}x${viewport.height}.png`,root).pathname});screenshots.push({viewport,geometry:await page.evaluate(()=>({pageWidth:document.documentElement.scrollWidth,viewport:innerWidth,dock:document.querySelector('.media-dock').getBoundingClientRect().toJSON(),detail:document.querySelector('.media-context-detail').getBoundingClientRect().toJSON()}))});assert(screenshots.at(-1).geometry.pageWidth<=viewport.width,'Silent copy must not cause horizontal page overflow');}results.push({test:'Mandatory copy and controls at desktop, landscape, and narrow mobile widths',pass:true,screenshots});
 await page.evaluate(()=>push({context:{kind:'proximity',label:'Nearby',canPublish:false,reason:'Nearby calls are paused for your current status'}}));assert.equal(await page.locator('.media-join').isDisabled(),false);assert.doesNotMatch(await page.locator('.media-warning').textContent(),/No calls here/);await page.locator('.media-join').click();assert.match(await page.locator('.media-context-detail').textContent(),/current status/);assert.doesNotMatch(await page.locator('.media-context-detail').textContent(),/Audience/);assert.equal(await page.locator('[data-media="camera"]').isDisabled(),true);results.push({test:'Busy proximity keeps join available and displays status reason, not audience copy',pass:true});
 await page.evaluate(()=>push({context:{kind:'silent',label:'Garden',canPublish:false}}));assert.equal(await page.locator('.media-join').textContent(),'Leave audio');assert.equal(await page.locator('.media-join').isDisabled(),false);await page.locator('.media-join').click();assert.equal(await page.locator('.media-join').isDisabled(),true);assert.equal(await page.evaluate(()=>media.getStatus().joined),false);results.push({test:'Retained opt-in can be explicitly left inside Silent',pass:true});
 await page.evaluate(()=>push({context:{kind:'proximity',canPublish:true}}));assert.equal(await page.locator('.media-join').isDisabled(),false);await page.locator('.media-join').click();assert.equal(await page.evaluate(()=>media.getStatus().joined),true);assert.equal(await page.evaluate(()=>captureAttempts),0);assert.equal(await page.evaluate(()=>peerAttempts),0);for(const kind of ['microphone','camera','screen'])assert.equal(await page.evaluate(kind=>media.getStatus().devices[kind].status,kind),'off');results.push({test:'Exit requires deliberate join after leave, and joining does not silently turn devices on',pass:true});
 await page.evaluate(()=>media.destroy());assert.deepEqual(errors,[]);const report={scope:'controlled-dom-no-gpu-no-devices-no-transport',browser:await browser.version(),results,errors,limits:['No 3D renderer or GPU verification.','No native media, screen consent, live packets or external provider contacted.','Synthetic controlled policies; HTTP authority remains covered separately.']};await writeFile(new URL('evidence/media-silent-dom.json',root),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
