import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {createIceCache} from '../src/media-ice.js';
import {createMediaSession} from '../src/media.js';
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
function timers(){let time=100000,id=0;const tasks=new Map();return{env:{AbortController,performance:{now:()=>time},setTimeout(fn,ms){const key=++id;tasks.set(key,{fn,at:time+ms});return key;},clearTimeout(key){tasks.delete(key);}},now:()=>time,async advance(ms){time+=ms;for(const[key,task]of [...tasks])if(task.at<=time){tasks.delete(key);task.fn();}await tick();},tasks};}
const response=(context,requestId,now)=>({scope:context.scope,requestId,selfId:context.selfId,roomId:context.roomId,issuedAt:now,expiresAt:now+60000,renewAt:now+45000,transport:'relay-configured',iceServers:[{urls:['turn:127.0.0.1:9?transport=udp'],username:`${Math.floor(now/1000)+60}:actor`,credential:randomBytes(24).toString('base64'),credentialType:'password'}]});
function cacheFixture(){const timer=timers(),context={scope:'scope',roomId:'r',selfId:'a',generation:1},calls=[],renew=[],failures=[];let serial=0,intercept=null,valid=true,wallOffset=0;const cache=createIceCache({api:async(path,o)=>{calls.push({path,...o});return intercept?intercept(o):response(context,o.body.requestId,timer.now());},env:timer.env,now:()=>timer.now()+wallOffset,nextId:()=>`request-${String(++serial).padStart(16,'0')}`,isCurrent:c=>valid&&c.scope===context.scope&&c.generation===context.generation,onRenew:c=>renew.push(c),onFailure:s=>failures.push(s)});return{...timer,context,calls,renew,failures,cache,wall(value){wallOffset=value;},set intercept(fn){intercept=fn;},invalidate(){valid=false;cache.retire();}};}
test('ICE cache requests exact challenge after authorization, deduplicates in-flight work and caches separately',async t=>{const f=cacheFixture();t.after(f.cache.retire);const wait=deferred();f.intercept=o=>wait.promise;const first=f.cache.ensure(f.context),second=f.cache.ensure(f.context);assert.equal(f.calls.length,1);assert.deepEqual(Object.keys(f.calls[0].body).sort(),['requestId','scope']);assert.equal(f.cache.configuration(f.context),null);wait.resolve(response(f.context,f.calls[0].body.requestId,f.now()));await first;await second;await f.cache.ensure(f.context);assert.equal(f.calls.length,1);assert.equal(f.cache.configuration(f.context).iceServers.length,1);});
test('ICE renewal makes a fresh request rather than reusing the fulfilled promise',async t=>{const f=cacheFixture();t.after(f.cache.retire);await f.cache.ensure(f.context);const initial=f.cache.configuration(f.context).iceServers[0].username;await f.advance(45000);assert.equal(f.calls.length,2);assert.equal(f.renew.length,1);assert.notEqual(f.cache.configuration(f.context).iceServers[0].username,initial);assert.notEqual(f.calls[0].body.requestId,f.calls[1].body.requestId);});
for(const field of ['requestId','scope','roomId','selfId'])test(`ICE response with wrong ${field} never enters cache`,async t=>{const f=cacheFixture();t.after(f.cache.retire);f.intercept=o=>({...response(f.context,o.body.requestId,f.now()),[field]:'wrong'});await assert.rejects(f.cache.ensure(f.context),/Invalid ICE/);assert.equal(f.cache.configuration(f.context),null);});
for(const change of [{expiresAt:100000},{renewAt:160000},{expiresAt:20000000},{iceServers:[{urls:['https://example.invalid']}]},{iceServers:[{urls:['turn:127.0.0.1:9'],username:'u'}]}])test('invalid lifetime or transport schema is rejected',async t=>{const f=cacheFixture();t.after(f.cache.retire);f.intercept=o=>({...response(f.context,o.body.requestId,f.now()),...change});await assert.rejects(f.cache.ensure(f.context));assert.equal(f.cache.configuration(f.context),null);});
test('8s deadline aborts an ignored request and ignores late success',async t=>{const f=cacheFixture();t.after(f.cache.retire);const wait=deferred();f.intercept=()=>wait.promise;const pending=f.cache.ensure(f.context);const rejected=assert.rejects(pending,/timed out/);await f.advance(8000);await rejected;assert.equal(f.calls[0].signal.aborted,true);wait.resolve(response(f.context,f.calls[0].body.requestId,f.now()));await tick();assert.equal(f.cache.configuration(f.context),null);});
test('retirement aborts pending work and a late result cannot revive it',async()=>{const f=cacheFixture(),wait=deferred();f.intercept=()=>wait.promise;const pending=f.cache.ensure(f.context),rejected=assert.rejects(pending,/retired/);f.invalidate();await rejected;wait.resolve(response(f.context,f.calls[0].body.requestId,f.now()));await tick();assert.equal(f.tasks.size,0);assert.equal(f.cache.configuration(f.context),null);});
test('held renewal expires without credentials, and late success cannot revive it',async t=>{const f=cacheFixture();t.after(f.cache.retire);await f.cache.ensure(f.context);const wait=deferred();f.intercept=()=>wait.promise;await f.advance(45000);await f.advance(15000);assert.equal(f.failures.length,1);assert.match(f.failures[0],/expired/);wait.resolve(response(f.context,f.calls.at(-1).body.requestId,f.now()));await tick();assert.equal(f.cache.configuration(f.context),null);});
class Peer{constructor(config){this.config=config;this.transceivers=[];this.connectionState='new';this.iceGatheringState='new';this.signalingState='stable';this.options=[];this.configChanges=0;Peer.instances.push(this);}getTransceivers(){return this.transceivers;}addTransceiver(kind,{direction}){const t={kind,direction,sender:{track:null,async replaceTrack(track){this.track=track;}}};this.transceivers.push(t);return t;}async createOffer(options){this.options.push(options);return{type:'offer',sdp:'fixture'};}async createAnswer(){return{type:'answer',sdp:'fixture'};}async setLocalDescription(d){this.localDescription=d;}async setRemoteDescription(d){this.remoteDescription=d;if(!this.transceivers.length)for(const kind of ['audio','video','video'])this.addTransceiver(kind,{direction:'sendrecv'});}async addIceCandidate(){}setConfiguration(c){this.config=c;this.configChanges++;}close(){this.closed=true;this.connectionState='closed';}}
Peer.instances=[];
class Track{constructor(){this.readyState='live';this.kind='audio';}stop(){this.readyState='ended';}}
class Stream{constructor(tracks){this.tracks=tracks;}getTracks(){return this.tracks;}}
function sessionFixture(self='a'){const timer=timers(),calls=[],capturedTracks=[],state={user:{id:self},room:{id:'r',scene:{areas:[{id:'quiet',action:'silent',x:5,z:0,width:2,depth:2}]}},position:{x:0,z:0},ready:true};let policy={selfId:self,roomId:'r',enabled:false,iceScope:'scope',context:{kind:'proximity',canPublish:true},peers:[{id:self==='a'?'z':'a',canSend:true,canReceive:true}]},intercept=null,signalIntercept=null,capture=0;const env={...timer.env,RTCPeerConnection:Peer,MediaStream:Stream,isSecureContext:true,navigator:{mediaDevices:{async getUserMedia(){capture++;const track=new Track;capturedTracks.push(track);return new Stream([track]);}}}};const api=async(path,o={})=>{calls.push({path,...o});if(path==='/api/media/signal'&&signalIntercept)return signalIntercept(o);if(path==='/api/media/state'){policy.enabled=o.body.enabled;return policy;}if(path==='/api/media')return structuredClone(policy);if(path==='/api/media/ice')return intercept?intercept(o):response({scope:policy.iceScope,roomId:policy.roomId,selfId:self},o.body.requestId,timer.now());return{ok:true};};const session=createMediaSession({api,getState:()=>state,env,now:timer.now});return{...timer,session,state,calls,capturedTracks,get capture(){return capture;},get policy(){return policy;},push(p){policy={...policy,...p};session.acceptPolicy(structuredClone(policy));},set intercept(fn){intercept=fn;},set signalIntercept(fn){signalIntercept=fn;}};}
test('native-shaped peer consumes private authorized config, snapshots omit credentials and capture stays explicit',async t=>{const f=sessionFixture();t.after(()=>f.session.destroy());assert.equal(f.calls.length,0);await f.session.setJoined(true);await tick();const p=Peer.instances.at(-1);assert.equal(p.config.iceServers.length,1);assert.equal(f.session.snapshot().iceTransport,'relay-configured');assert.equal(f.capture,0);assert.equal(JSON.stringify(f.session.snapshot()).includes(p.config.iceServers[0].credential),false);assert.equal(JSON.stringify(f.session.snapshot()).includes(p.config.iceServers[0].username),false);});
test('offerer renewal setsConfiguration and creates an ICE-restart offer on the existing peer',async t=>{const f=sessionFixture();t.after(()=>f.session.destroy());await f.session.setJoined(true);await tick();const p=Peer.instances.at(-1);await f.advance(45000);assert.equal(p.closed,undefined);assert.equal(p.configChanges,1);assert.deepEqual(p.options.at(-1),{iceRestart:true});});
test('answerer renewal requests authorized restart on the existing connection instead of originating an offer',async t=>{const f=sessionFixture('z');t.after(()=>f.session.destroy());await f.session.setJoined(true);await f.session.onSignal({roomId:'r',from:'a',connectionId:'connection',description:{type:'offer',sdp:'fixture'}});const p=Peer.instances.at(-1);await f.advance(45000);assert.equal(p.configChanges,1);assert.equal(p.options.length,0);assert.equal(f.calls.some(c=>c.path==='/api/media/signal'&&c.body.request==='restart'&&c.body.connectionId==='connection'),true);});
for(const mode of ['room','actor','silent','scope','destroy'])test(`late ICE response cannot cross ${mode} retirement`,async t=>{const f=sessionFixture();t.after(()=>f.session.destroy());const wait=deferred();f.intercept=()=>wait.promise;const pending=f.session.setJoined(true);await tick();const call=f.calls.find(c=>c.path==='/api/media/ice');if(mode==='room')f.state.room={id:'other',scene:{areas:[]}};if(mode==='actor')f.state.user={id:'other'};if(mode==='silent')f.state.position={x:5,z:0};if(mode==='scope')f.push({iceScope:'new-scope',context:{kind:'silent',canPublish:false},peers:[]});if(mode==='destroy')f.session.destroy();else f.session.checkLocalPolicy();wait.resolve(response({scope:'scope',roomId:'r',selfId:'a'},call.body.requestId,f.now()));await pending;await tick();assert.equal(f.session.snapshot().peers.length,0);assert.equal(f.capture,0);});
test('renewal failure stops devices and stays latched through healthy policy pushes without recapture',async t=>{const f=sessionFixture();t.after(()=>f.session.destroy());await f.session.toggleDevice('microphone');await tick();const track=f.session.snapshot().devices.microphone.stream.getTracks()[0],p=Peer.instances.at(-1);f.intercept=()=>Promise.reject(Error('network failure'));await f.advance(45000);assert.equal(track.readyState,'ended');assert.equal(p.closed,true);assert.match(f.session.snapshot().iceError,/renewal failed/);const calls=f.calls.filter(c=>c.path==='/api/media/ice').length;f.push({});await f.session.update();await tick();assert.equal(f.calls.filter(c=>c.path==='/api/media/ice').length,calls);assert.equal(f.capture,1);assert.equal(f.session.snapshot().peers.length,0);});

test('mandatory current-server ICE policy never falls back to host-only when its scope is missing',async t=>{const f=sessionFixture();t.after(()=>f.session.destroy());await f.session.toggleDevice('microphone');await tick();const track=f.session.snapshot().devices.microphone.stream.getTracks()[0],p=Peer.instances.at(-1),count=Peer.instances.length;f.push({iceRequired:true,iceScope:undefined});await tick();assert.equal(p.closed,true);assert.equal(f.session.snapshot().peers.length,0);assert.equal(Peer.instances.length,count);assert.equal(track.readyState,'ended');assert.equal(f.capture,1);});

test('server clock offset and browser wall-clock rollback cannot extend elapsed renewal or expiry',async t=>{const f=cacheFixture();t.after(f.cache.retire);const wait=deferred();f.wall(86400000*365);f.intercept=()=>wait.promise;const first=f.cache.ensure(f.context);await f.advance(1500);wait.resolve(response(f.context,f.calls[0].body.requestId,f.now()+86400000*730));await first;f.wall(-86400000*365);assert.ok(f.cache.configuration(f.context));f.intercept=o=>response(f.context,o.body.requestId,f.now()+86400000*730);await f.advance(43499);assert.equal(f.calls.length,1);await f.advance(1);assert.equal(f.calls.length,2);assert.equal(f.renew.length,1);const held=deferred();f.intercept=()=>held.promise;f.wall(86400000*7300);await f.advance(45000);f.wall(-86400000*7300);await f.advance(15000);assert.equal(f.cache.configuration(f.context),null);assert.match(f.failures[0],/expired/);held.resolve(response(f.context,f.calls.at(-1).body.requestId,f.now()+86400000*730));await tick();assert.equal(f.cache.configuration(f.context),null);});


test('retired onSignal ICE request must not poison a later valid scope',async t=>{
 const f=sessionFixture('z');t.after(()=>f.session.destroy());await f.session.setJoined(true);
 const wait=deferred();f.intercept=()=>wait.promise;f.push({iceScope:'scope2'});await tick();
 const pending=f.session.onSignal({roomId:'r',from:'a',connectionId:'old',candidate:{candidate:'fixture'}});await tick();
 f.intercept=null;f.push({iceScope:'scope3'});await pending;await tick();
 assert.equal(f.session.snapshot().iceError,'');assert.equal(f.session.snapshot().iceTransport,'relay-configured');
});
test('retired retry ICE request must not poison a new room join',async t=>{
 const f=sessionFixture();t.after(()=>f.session.destroy());await f.session.setJoined(true);
 const wait=deferred();f.intercept=()=>wait.promise;const pending=f.session.retry();await tick();
 f.state.room={id:'new-room',scene:{areas:[]}};f.intercept=null;f.push({roomId:'new-room',iceScope:'new-scope',enabled:false});
 const joined=f.session.setJoined(true);await pending;const result=await joined;await tick();
 assert.equal(f.session.snapshot().iceError,'');assert.equal(result,true);
});

test('late restart signaling failure must not stop a freshly rejoined session',async t=>{
 const f=sessionFixture('z');t.after(()=>f.session.destroy());await f.session.setJoined(true);
 await f.session.onSignal({roomId:'r',from:'a',connectionId:'old',description:{type:'offer',sdp:'fixture'}});
 const wait=deferred();f.signalIntercept=o=>o.body.request==='restart'?wait.promise:{ok:true};await f.advance(45000);
 assert.equal(f.calls.some(c=>c.body?.request==='restart'),true);
 await f.session.setJoined(false);f.signalIntercept=null;assert.equal(await f.session.setJoined(true),true);
 await f.session.onSignal({roomId:'r',from:'a',connectionId:'new',description:{type:'offer',sdp:'fixture'}});
 const peer=Peer.instances.at(-1);wait.reject(Error('old request failed'));await tick();
 assert.equal(f.session.snapshot().iceError,'');assert.notEqual(peer.closed,true);
});
test('superseded same-scope retry must not fail a newer retry',async t=>{
 const f=sessionFixture();t.after(()=>f.session.destroy());await f.session.setJoined(true);
 const wait=deferred();f.intercept=()=>wait.promise;const first=f.session.retry();await tick();
 f.intercept=null;const second=f.session.retry();await first;await second;await tick();
 assert.equal(f.session.snapshot().iceError,'');assert.equal(f.session.snapshot().iceTransport,'relay-configured');
});

test('current initial ICE failure stops pending capture and requires explicit retry',async t=>{
 const f=sessionFixture();t.after(()=>f.session.destroy());f.intercept=()=>Promise.reject(Error('current ICE failure'));
 assert.equal(await f.session.toggleDevice('microphone'),false);await tick();
 assert.match(f.session.snapshot().iceError,/configuration unavailable/);assert.equal(f.session.snapshot().devices.microphone.status,'off');assert.equal(f.session.snapshot().peers.length,0);assert.equal(f.capturedTracks[0].readyState,'ended');
 const calls=f.calls.filter(c=>c.path==='/api/media/ice').length;f.intercept=null;f.push({});await f.session.update();await tick();
 assert.equal(f.calls.filter(c=>c.path==='/api/media/ice').length,calls);assert.equal(f.capture,1);
 await f.session.retry();await tick();assert.equal(f.session.snapshot().iceError,'');assert.equal(f.session.snapshot().iceTransport,'relay-configured');assert.equal(f.session.snapshot().devices.microphone.status,'off');assert.equal(f.capture,1);
});

test('current retry ICE failure stops live devices and a later retry never recaptures them',async t=>{
 const f=sessionFixture();t.after(()=>f.session.destroy());await f.session.toggleDevice('microphone');await tick();
 const track=f.session.snapshot().devices.microphone.stream.getTracks()[0],peer=Peer.instances.at(-1);f.intercept=()=>Promise.reject(Error('current retry failure'));
 await f.session.retry();assert.match(f.session.snapshot().iceError,/configuration unavailable/);assert.equal(track.readyState,'ended');assert.equal(peer.closed,true);
 f.intercept=null;await f.session.retry();await tick();assert.equal(f.session.snapshot().iceError,'');assert.equal(f.session.snapshot().iceTransport,'relay-configured');assert.equal(f.session.snapshot().devices.microphone.status,'off');assert.equal(f.capture,1);
});

test('current renewal restart signaling failure still stops live devices and peers',async t=>{
 const f=sessionFixture('z');t.after(()=>f.session.destroy());await f.session.toggleDevice('microphone');
 await f.session.onSignal({roomId:'r',from:'a',connectionId:'current',description:{type:'offer',sdp:'fixture'}});
 const track=f.session.snapshot().devices.microphone.stream.getTracks()[0],peer=Peer.instances.at(-1);
 f.signalIntercept=o=>o.body.request==='restart'?Promise.reject(Error('current restart failure')):{ok:true};await f.advance(45000);
 assert.match(f.session.snapshot().iceError,/restart signaling failed/);assert.equal(track.readyState,'ended');assert.equal(peer.closed,true);assert.equal(f.capture,1);
});
