import test from'node:test';import assert from'node:assert/strict';import{emptyScene,findPath}from'../src/worlds.js';import{WALK_SPEED,FAST_WALK_MULTIPLIER,createMotion,advanceMotion,stopMotion,screenDirection}from'../src/motion.js';
const room=()=>({...emptyScene(),bounds:{width:200,depth:200}});
function walk(fps,input,fast=false,seconds=1){const m=createMotion({x:0,z:0});for(let i=0;i<fps*seconds;i++)advanceMotion(m,room(),{input,angle:Math.PI/4,fast},1/fps);return m;}
test('MOVE-FEEL: 10/20/30/60/120fps cover equal distance instead of slow-time frame clamp',()=>{const distances=[10,20,30,60,120].map(fps=>{const p=walk(fps,{x:0,z:-1}).position;return Math.hypot(p.x,p.z)});assert(Math.max(...distances)-Math.min(...distances)<.00001);assert(distances[0]>WALK_SPEED*.95);});
test('MOVE-SHIFT: fast walk is source2.5×, diagonal speed normalized',()=>{const a=walk(60,{x:0,z:-1}),b=walk(60,{x:1,z:-1}),fast=walk(60,{x:0,z:-1},true);const distance=m=>Math.hypot(m.position.x,m.position.z);assert(Math.abs(distance(a)-distance(b))<1e-8);assert(Math.abs(distance(fast)/distance(a)-FAST_WALK_MULTIPLIER)<1e-8);});
test('MOVE-CAMERA: input basis follows all orbit quadrants without skew',()=>{for(let a=0;a<Math.PI*2;a+=Math.PI/4){const forward=screenDirection({x:0,z:-1},a),right=screenDirection({x:1,z:0},a);assert(Math.abs(Math.hypot(forward.x,forward.z)-1)<1e-9);assert(Math.abs(forward.x*right.x+forward.z*right.z)<1e-9);}});
test('MOVE-RELEASE: short responsive stop; blur/modal hard-stop leaves no motion',()=>{const m=walk(60,{x:0,z:-1});const before={...m.position};for(let i=0;i<12;i++)advanceMotion(m,room(),{input:{x:0,z:0}},1/60);assert(Math.hypot(m.position.x-before.x,m.position.z-before.z)<.1);assert(Math.hypot(m.velocity.x,m.velocity.z)<.0001);stopMotion(m);assert.deepEqual(m.velocity,{x:0,z:0});assert.equal(m.moving,false);});
test('MOVE-PATH: Shift alone does not accelerate automatic path or cancel it',()=>{const scene=room(),a=createMotion({x:0,z:0}),b=createMotion({x:0,z:0});const pa=findPath(scene,a.position,{x:0,z:-10}),pb=structuredClone(pa);for(let i=0;i<60;i++){advanceMotion(a,scene,{path:pa,fast:false},1/60);advanceMotion(b,scene,{path:pb,fast:true},1/60);}assert(Math.hypot(a.position.x-b.position.x,a.position.z-b.position.z)<1e-9);assert(pa.length>0);});
test('MOVE-COLLISION: fast walk and low fps cannot cross solid furniture',()=>{const scene=room();scene.objects=[{id:'wall',type:'wall',x:0,z:-3,width:20,depth:.3,rotation:0}];const m=createMotion({x:0,z:0});for(let i=0;i<20;i++)advanceMotion(m,scene,{input:{x:0,z:-1},angle:Math.PI/2,fast:true},.1);assert(m.position.z>-2.56);});
test('MOVE-PAUSE: very long suspended frame is bounded and never teleports across map',()=>{const m=createMotion({x:0,z:0});advanceMotion(m,room(),{input:{x:1,z:0},fast:true},60);assert(Math.hypot(m.position.x,m.position.z)<4);});
test('MOVE-DESK: explicit scripted desk speed is2.5x while ordinary click paths ignore Shift',()=>{const scene={bounds:{width:200,depth:200},objects:[]};const a=createMotion({x:0,z:0}),b=createMotion({x:0,z:0});const pa=[{x:40,z:0}],pb=[{x:40,z:0}];for(let i=0;i<120;i++){advanceMotion(a,scene,{path:pa,fast:true},1/60);advanceMotion(b,scene,{path:pb,pathSpeed:FAST_WALK_MULTIPLIER},1/60);}assert(Math.abs(b.position.x/a.position.x-2.5)<.001);assert.equal(a.running,false);assert.equal(b.running,true);});
