/** Actual shell, native UI actions, read-only diagnostics. CSS-only layout
 * fixtures exercise real panels on either side and during resize/transition. */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
const out='evidence/panel-framing';await mkdir(out,{recursive:true});
const scene={version:1,theme:'garden',bounds:{width:32,depth:26},spawn:{x:0,z:0},objects:[],areas:[{id:'content-area',name:'Content area',action:'welcome',x:0,z:0,width:20,depth:20,actions:[{id:'open',type:'link',label:'Open framing fixture',url:'https://framing-fixture.invalid/',mode:'embed',width:40,closable:true}]}]};
const dist=new URL('../dist',import.meta.url).pathname,app=createGameServer({dist,seeds:[{id:'framing-world',name:'Framing world',rooms:[{id:'framing-room',name:'Framing room',scene}]}],questsEnabled:false}),{port}=await app.listen(0),browser=await launch(),ctx=await browser.newContext({viewport:{width:1440,height:950},deviceScaleFactor:2}),page=await ctx.newPage();page.setDefaultTimeout(30000);
const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const camera=()=>page.evaluate(()=>__universe.getCamera()),position=()=>page.evaluate(()=>__universe.getState().position),wait=()=>page.waitForTimeout(900),shot=n=>page.screenshot({path:out+'/'+n+'.png'}),pass=(name,detail={})=>{checks.push({name,status:'passed',...detail});console.log('PASS',name);};
const pose=c=>({yaw:c.yaw,tilt:c.tilt,distance:c.distance,target:c.target,player:c.player});
async function fit(){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await page.waitForFunction(()=>{const f=__universe.getCamera().framing;return f.status==='framed'&&f.targetOffset&&Math.hypot(f.offset.x-f.targetOffset.x,f.offset.y-f.targetOffset.y)<1;});await page.waitForTimeout(80);const c=await camera();assert.equal(c.viewportWidth,1);assert.equal(c.framing.status,'framed',JSON.stringify(c.framing));const p=await page.evaluate(()=>{const s=__universe.getCamera();return __universe.getScreenPoint(s.target.x,s.target.z,1.2);});const r=c.framing.rect;assert(p.x>r.left&&p.x<r.right&&p.y>r.top&&p.y<r.bottom,JSON.stringify({p,r}));return c;}
async function canvasPoint(x,z,y=0){const p=await page.evaluate(v=>__universe.getScreenPoint(v.x,v.z,v.y),{x,z,y});assert.equal(await page.evaluate(q=>document.elementFromPoint(q.x,q.y)?.id,p),'game',JSON.stringify(p));return p;}
try{
 await page.route('https://framing-fixture.invalid/**',r=>r.fulfill({contentType:'text/html',body:'<h1>Local framing fixture</h1>'}));await page.goto(`http://127.0.0.1:${port}/?room=framing-room`,{waitUntil:'domcontentloaded'});await page.getByPlaceholder('Your name').fill('Framing explorer');await page.locator('#join-button').click();await page.waitForFunction(()=>window.__universe?.getState().ready);await page.locator('#home-camera').click();await wait();const initial=await camera(),player=await position();
 await page.locator('#dock-chat').click();let c=await fit();assert.deepEqual(pose(c),pose(initial));assert.deepEqual(await position(),player);assert(c.framing.offset.x<0);assert.equal(await page.locator('#dialog').isVisible(),false);await shot('right-chat-dpr2');pass('Right chat reframes follow into measured free map without cropping or changing pose/player',{camera:c});
 // Real chat panel remains the same UI; only the test's placement CSS differs.
 const leftStyle=await page.addStyleTag({content:'#social{left:16px!important;right:auto!important;transition:width .25s linear;width:320px!important}'});c=await fit();assert(c.framing.offset.x>0);await shot('left-chat');pass('Measured left side is recognized with no right-only width shortcut',{framing:c.framing});
 await page.getByRole('button',{name:'Close social panel',exact:true}).click();await page.getByRole('button',{name:'Open framing fixture',exact:true}).click();await page.locator('.embedded-panel').waitFor();await page.locator('#dock-chat').click();c=await fit();assert.equal(c.framing.panelCount,2);assert(c.framing.rect.left>300&&c.framing.rect.right<900);await shot('simultaneous-panels');pass('Real chat and embedded content can occlude both sides simultaneously',{framing:c.framing});
 await page.getByRole('button',{name:'Return to world',exact:true}).click();await wait();const beforePan=await camera(),start=await canvasPoint(0,0,1);await page.mouse.move(start.x,start.y);await page.mouse.down({button:'middle'});await page.mouse.move(start.x+70,start.y+30,{steps:8});await page.mouse.up({button:'middle'});await wait();const manual=await camera();assert.equal(manual.framingMode,'manual');assert.notDeepEqual(manual.target,beforePan.target);await page.getByRole('button',{name:'Close social panel',exact:true}).click();await wait();assert.deepEqual(pose(await camera()),pose(manual));assert.deepEqual((await camera()).framing.offset,manual.framing.offset);await page.locator('#dock-chat').click();await wait();assert.deepEqual(pose(await camera()),pose(manual));assert.deepEqual((await camera()).framing.offset,manual.framing.offset);pass('Native middle pan freezes composition through panel close/reopen, without pulling player');
 await page.locator('#game').focus();await page.keyboard.press('f');await page.waitForFunction(()=>{const c=__universe.getCamera();return c.follow&&Math.hypot(c.target.x-c.player.x,c.target.z-c.player.z)<.03;});c=await fit();assert.equal(c.framingMode,'follow');assert(Math.hypot(c.target.x-player.x,c.target.z-player.z)<.05);await page.locator('#game').focus();await page.keyboard.press('Home');await fit();pass('Explicit Follow and Reset resume free-area framing');
 await page.getByRole('button',{name:'Close social panel',exact:true}).click();await leftStyle.evaluate(e=>e.remove());await page.locator('#manage-bots').click();await page.getByTestId('bot-create').click();c=await fit();assert.equal(c.framingMode,'focus');const home=async()=>({x:Number(await page.locator('[data-bot-field="spawn.x"]').inputValue()),z:Number(await page.locator('[data-bot-field="spawn.z"]').inputValue())}),old=await home(),target={x:old.x+1,z:old.z+1},from=await canvasPoint(old.x,old.z,1.1),to=await canvasPoint(target.x,target.z,0);await page.mouse.move(from.x,from.y);const dragCamera=await camera();await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:10});assert.deepEqual(pose(await camera()),pose(dragCamera),'resident drag must not take camera ownership or move its target');assert.deepEqual((await camera()).framing.offset,dragCamera.framing.offset,'resident drag must not automatically reframe');assert.deepEqual(await home(),old);await page.mouse.up();await page.waitForFunction(v=>Number(document.querySelector('[data-bot-field="spawn.x"]').value)===v.x&&Number(document.querySelector('[data-bot-field="spawn.z"]').value)===v.z,target);assert.deepEqual(await position(),player);await shot('resident-drag-dpr2');pass('DPR2 native resident handle pick/drag roundtrip commits exact world coordinates without moving player',{old,target,from,to});
 const focusBefore=await camera();await page.getByTestId('bot-focus').click();c=await fit();assert.deepEqual(c.target,target);for(const k of['yaw','tilt','distance'])assert.equal(c[k],focusBefore[k]);pass('Explicit resident Focus frames its current home and preserves perspective pose');
 const residentPanStart=await canvasPoint(target.x,target.z,1.1);await page.mouse.move(residentPanStart.x,residentPanStart.y);await page.mouse.down({button:'middle'});await page.mouse.move(residentPanStart.x+24,residentPanStart.y-8,{steps:5});await page.mouse.up({button:'middle'});const residentManual=await camera();assert.equal(residentManual.framingMode,'manual');await page.getByRole('button',{name:'Close residents',exact:true}).click();await page.getByTestId('bot-editor').waitFor({state:'hidden'});await page.waitForFunction(()=>history.state?.surface!=='bots');await page.locator('#manage-bots').click();await page.locator('[data-bot-field="name"]').waitFor();await wait();const reopened=await camera();assert.equal(reopened.framingMode,'manual');assert.deepEqual(reopened.target,residentManual.target);assert.deepEqual(reopened.framing.offset,residentManual.framing.offset);await page.getByTestId('bot-focus').click();await fit();pass('Closing and reopening a restored resident draft preserves manual camera until explicit Focus');
 // A CSS transition changes the existing panel, not a synthetic blocker/helper.
 const narrowStyle=await page.addStyleTag({content:'.resident-panel{width:450px!important;transition:width .3s linear}'});await page.waitForFunction(()=>Math.abs(document.querySelector('.resident-panel').getBoundingClientRect().width-450)<.1);await fit();const width1=(await camera()).framing.rect.width;await narrowStyle.evaluate(e=>{e.textContent='.resident-panel{width:600px!important;transition:width .3s linear}';});await page.waitForFunction(()=>Math.abs(document.querySelector('.resident-panel').getBoundingClientRect().width-600)<.1);await fit();assert((await camera()).framing.rect.width<width1,JSON.stringify({width1,framing:(await camera()).framing}));pass('Actual panel width transition is remeasured and settled framing follows resized geometry');await narrowStyle.evaluate(e=>e.remove());
 await page.setViewportSize({width:1000,height:760});await fit();await shot('tablet-resident');pass('Tablet resident reframes at full viewport without desktop-only breakpoint');
 await page.setViewportSize({width:768,height:700});await wait();c=await camera();assert.equal(c.viewportWidth,1);assert.equal(c.framing.status,'insufficient-space');assert.match(await page.locator('#toast').innerText(),/Not enough visible map space/);pass('Tiny blocked layout reports inability rather than cropping or zooming',{framing:c.framing});await shot('blocked-tablet');
 await page.setViewportSize({width:390,height:844});await wait();c=await camera();assert.equal(c.framing.status,'unobstructed');assert.equal(c.viewportWidth,1);assert(Math.abs(c.framing.offset.x)<1);assert.equal(await page.locator('.resident-panel').getAttribute('aria-modal'),'false');await shot('mobile-fullscreen-ignored');pass('Mobile near-fullscreen resident sheet is ignored by side framing and does not broaden modal behavior');
 await page.getByRole('button',{name:'Close residents',exact:true}).click();await page.getByTestId('bot-editor').waitFor({state:'hidden'});await page.setViewportSize({width:1100,height:850});await page.locator('#home-camera').click();await page.locator('#dock-chat').click();await fit();const cdp=await ctx.newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});const beforeTouch=await camera(),p=await canvasPoint(0,0,1);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:p.x-30,y:p.y},{id:2,x:p.x+30,y:p.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:p.x-45,y:p.y-10},{id:2,x:p.x+50,y:p.y-10}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait();assert((await camera()).distance<beforeTouch.distance);assert.deepEqual(await position(),player);pass('DPR2 native touch pinch/orbit remains usable in reframed map without walking');await shot('touch-reframed');
 await page.getByRole('button',{name:'Close social panel',exact:true}).click();await page.locator('#shortcuts-help').click();await wait();assert.equal((await camera()).framing.panelCount,0);assert.equal((await camera()).framing.status,'unobstructed');pass('Centered real modal is outside side-blocker framing');assert.deepEqual(errors,[]);
}catch(error){console.error(error);checks.push({name:'panel framing acceptance',status:'failed',error:error.stack});await shot('failure').catch(()=>{});process.exitCode=1;}finally{await writeFile(out+'/results.json',JSON.stringify({buildSha256:createHash('sha256').update(await readFile(dist+'/main.js')).digest('hex'),checks,errors,limitations:['Local native UI and intercepted local iframe fixture only','CSS-only test placement/transition fixture for left side and width changes; actual production panels are measured','Headless Chromium SwiftShader; no physical-device or deployed claim']},null,2));await ctx.close();await browser.close();await app.close();}
