/** DOM-only personal-area UI with the real local authority API. No renderer/GPU. */
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
const temp=await mkdtemp(join(tmpdir(),'universe-personal-ui-'));
const source=`import {mountPersonalAreas} from './src/personal-areas.js';
window.state={...window.fixture,position:{x:0,z:12},ready:true,scene:structuredClone(window.fixture.room.scene)};
window.logs={posts:[],rooms:[],open:[],toasts:[],build:[],desk:[],register:0};window.hooks={};
window.request=async(url,options={})=>{if(options.method==='POST')logs.posts.push({url,body:structuredClone(options.body)});const r=await fetch(url,{method:options.method||'GET',headers:options.body?{'Content-Type':'application/json'}:{},body:options.body?JSON.stringify(options.body):undefined});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.message),{status:r.status,data});if(hooks.dropNext&&url.endsWith('/'+hooks.dropNext)){hooks.dropNext=null;throw new Error('Simulated lost successful response');}if(hooks.delayNext&&url.endsWith('/'+hooks.delayNext)){hooks.delayNext=null;await new Promise(resolve=>window.releaseResponse=resolve);}return data;};
window.surface=mountPersonalAreas({root:document.getElementById('personal'),getState:()=>state,api:request,onRoom:room=>{logs.rooms.push(structuredClone(room));state.room=room;if(!hooks.dirty)state.scene=structuredClone(room.scene);},beforeOperation:async({action})=>{if(hooks.denyBefore)return false;if(hooks.pauseBefore)await new Promise(resolve=>window.releaseBefore=resolve);if(action==='claim'||action==='decline')await request('/api/presence',{method:'POST',body:{roomId:state.room.id,...state.position}});return true;},onBuild:id=>logs.build.push(id),onDesk:target=>logs.desk.push(target),onRegister:()=>logs.register++,onOpenChange:value=>logs.open.push(value),toast:text=>logs.toasts.push(text)});
window.refreshRoom=async()=>{state.room=(await request('/api/rooms/'+state.room.id)).room;surface.update();};window.move=async(id)=>{const area=state.room.personalAreas.find(a=>a.areaId===id);state.position={x:area.x,z:area.z};await request('/api/presence',{method:'POST',body:{roomId:state.room.id,...state.position}});surface.update();};document.getElementById('open').onclick=()=>surface.open();`;
await build({stdin:{contents:source,resolveDir:process.cwd(),sourcefile:'personal-area-fixture.js'},bundle:true,format:'iife',outdir:temp,entryNames:'fixture'});
await writeFile(join(temp,'index.html'),'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="fixture.css"><style>body{margin:0;background:#30343a;font:14px Arial;color:#fff}button,input{font:inherit}#open,#chat{min-height:44px}#personal{position:relative}</style><button id="open">Open areas</button><input id="chat" aria-label="Chat"><button id="other">Other control</button><div id="personal"></div><script src="fixture.js"></script>');
const app=createGameServer({dist:temp}),{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;
const client=()=>({cookie:'',async call(path,method='GET',body){const r=await fetch(base+path,{method,headers:{Cookie:this.cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];const data=await r.json();assert(r.ok,JSON.stringify({status:r.status,path,data}));return data;}});
async function account(name,registered=true){const c=client();await c.call('/api/session','POST',{name});if(registered)await c.call('/api/account','POST',{username:`test_${randomUUID().replaceAll('-','').slice(0,15)}`,password:'Local browser fixture password'});c.user=(await c.call('/api/session')).user;return c;}
const manager=await account('Manager'),alice=await account('Alice'),bob=await account('Bob'),guest=await account('Guest',false);
const area=(id,x,z=0,mode='dynamic',allowedTags=[])=>({id,name:id,x,z,width:6,depth:6,action:'welcome',personalArea:{mode,allowedTags}});
const world=(await manager.call('/api/worlds','POST',{name:'Personal area UI world'})).world;
const room=(await manager.call('/api/rooms','POST',{worldId:world.id,name:'Personal area browser room',scene:{version:1,theme:'garden',bounds:{width:32,depth:32},spawn:{x:0,z:12},objects:[],areas:[area('desk-a',-8),area('desk-b',0),area('desk-c',8),area('static-desk',-8,8,'static'),area('tagged-desk',8,8,'dynamic',['artist'])]}})).room;
for(const c of [manager,alice,bob,guest])await c.call(`/api/rooms/${room.id}/join`,'POST',{});
const browser=await launch(),checks=[],errors=[];let currentPage;const contexts=[];
const pass=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
async function pageFor(c,viewport={width:1100,height:800}){const context=await browser.newContext({viewport});contexts.push(context);await context.addCookies([{name:'universe_session',value:c.cookie.split('=')[1],url:base}]);const page=await context.newPage();currentPage=page;page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(fixture=>{window.fixture=fixture;},{user:c.user,room:(await c.call(`/api/rooms/${room.id}`)).room});await page.goto(base);await page.waitForFunction(()=>!!window.surface);return page;}
const btn=(page,key)=>page.locator(`[data-personal-key="${key}"]`);
async function open(page,id){await page.evaluate(id=>surface.open(id),id);await page.waitForFunction(()=>!document.querySelector('.personal-area-sheet')?.textContent.includes('Checking current room…'));}
async function settled(page){await page.waitForFunction(()=>!document.querySelector('.personal-area-sheet')?.textContent.includes('Saving change…'));}
async function revoke(c,id,handling='keep'){const r=(await c.call(`/api/rooms/${room.id}`)).room,a=r.personalAreas.find(a=>a.areaId===id);return c.call(`/api/rooms/${room.id}/personal-areas/${id}/revoke`,'POST',{revision:a.revision,roomRevision:r.revision,objectHandling:handling,clientOperationId:randomUUID()});}
async function save(c,transform){const r=(await c.call(`/api/rooms/${room.id}`)).room,s=structuredClone(r.scene);transform(s);return c.call(`/api/rooms/${room.id}/scene`,'PUT',{revision:r.revision,scene:s,personalAreaRevisions:Object.fromEntries(r.personalAreas.map(a=>[a.areaId,a.revision]))});}
try{
 const g=await pageFor(guest);await g.evaluate(()=>move('desk-a'));await g.getByRole('button',{name:'Register or sign in'}).waitFor();assert.equal(await g.getByRole('button',{name:'Claim area',exact:true}).count(),0);await g.getByRole('button',{name:'Register or sign in'}).click();assert.equal(await g.evaluate(()=>logs.register),1);assert.equal(await g.evaluate(()=>logs.posts.some(p=>p.url.endsWith('/claim'))),false);pass('Guest entry has a real registration callback and cannot claim');
 const a=await pageFor(alice);await a.evaluate(()=>move('desk-a'));await a.locator('.personal-area-invitation').waitFor({state:'visible'});await a.locator('#chat').focus();await a.evaluate(()=>surface.update());assert.equal(await a.locator('.personal-area-invitation').isVisible(),false);await a.locator('#open').focus();await a.evaluate(()=>surface.update({suppressed:true}));assert.equal(await a.locator('.personal-area-invitation').isVisible(),false);await a.evaluate(()=>surface.update({suppressed:false}));assert.equal(await a.locator('.personal-area-invitation').isVisible(),true);await a.evaluate(()=>move('tagged-desk'));assert.equal(await a.locator('.personal-area-invitation').isVisible(),false);pass('Entry invitation respects typing, suppression and server eligibility');
 await a.evaluate(()=>move('desk-a'));await btn(a,'invite-decline').click();await a.waitForFunction(()=>state.room.personalAreas.find(x=>x.areaId==='desk-a').declined);assert.equal(await a.locator('.personal-area-invitation').isVisible(),false);await a.reload();await a.evaluate(async()=>{await refreshRoom();await move('desk-a')});assert.equal(await a.locator('.personal-area-invitation').isVisible(),false);await open(a,'desk-a');await btn(a,'claim').waitFor();pass('Decline is durable in the authority projection and manual claim stays available');
 await a.evaluate(()=>{hooks.denyBefore=true;hooks.dirty=true;state.scene.objects.push({id:'draft-kept',type:'chair',x:0,z:0});});const postCount=await a.evaluate(()=>logs.posts.length);await btn(a,'claim').click();await settled(a);assert.equal(await a.evaluate(()=>logs.posts.length),postCount);assert.equal(await a.evaluate(()=>state.scene.objects.at(-1).id),'draft-kept');await a.evaluate(()=>{hooks.denyBefore=false;hooks.dirty=false;});pass('Pending-save gate prevents ownership mutation without discarding a draft');
 await btn(a,'claim').click();await a.waitForFunction(()=>state.room.personalAreas.find(x=>x.areaId==='desk-a').isOwner);assert.equal(await a.evaluate(()=>state.room.capabilities.canEditScene),false);await btn(a,'build').click();assert.deepEqual(await a.evaluate(()=>logs.build),['desk-a']);assert.equal(await a.evaluate(()=>surface.isOpen()),false);pass('Real claim grants only current-area build rights and invokes the real build callback');
 await save(alice,s=>s.objects.push({id:'old-owner-chair',name:'Old owner chair',type:'chair',x:-8,z:0,rotation:0}));await a.evaluate(async()=>{await refreshRoom();await move('desk-b');});await open(a,'desk-b');await btn(a,'claim').click();await btn(a,'confirm-transfer').waitFor();const beforeCancel=await a.evaluate(()=>logs.posts.length);await btn(a,'cancel').click();assert.equal(await a.evaluate(()=>logs.posts.length),beforeCancel);assert.equal((await alice.call(`/api/rooms/${room.id}`)).room.personalAreas.find(x=>x.areaId==='desk-a').isOwner,true);pass('Transfer warning is explicit and Cancel sends no ownership request');
 await btn(a,'claim').click();await btn(a,'confirm-transfer').waitFor();await save(manager,s=>s.objects.push({id:'manager-chair',name:'Manager chair',type:'chair',x:-7,z:0,rotation:0}));await a.evaluate(()=>refreshRoom());assert.equal(await btn(a,'confirm-transfer').count(),0);await a.getByRole('alert').filter({hasText:'changed'}).waitFor();await btn(a,'claim').click();await btn(a,'confirm-transfer').waitFor();const original=await a.evaluate(()=>logs.posts.filter(p=>p.url.endsWith('/claim')).at(-1));await btn(a,'confirm-transfer').click();await a.waitForFunction(()=>state.room.personalAreas.find(x=>x.areaId==='desk-b').isOwner);const confirmed=await a.evaluate(()=>logs.posts.filter(p=>p.url.endsWith('/claim')).at(-1));assert.equal(confirmed.body.clientOperationId,original.body.clientOperationId);assert.equal(confirmed.body.confirmedTransfer,true);assert.equal(await a.evaluate(()=>state.room.personalAreas.find(x=>x.areaId==='desk-a').ownerId),null);assert.equal(await a.evaluate(()=>state.room.scene.objects.some(o=>o.id==='old-owner-chair')),true);pass('Transfer invalidates stale confirmation, uses current room CAS and retains semantic operation identity');
 await btn(a,'desk').click();assert.deepEqual(await a.evaluate(()=>logs.desk),[{roomId:room.id}]);pass('Desk callback is explicitly scoped to the current room');
 const m=await pageFor(manager);await open(m,'static-desk');const beforeSearch=await m.evaluate(()=>logs.posts.length);await btn(m,'account-query').fill('A');await m.waitForTimeout(300);assert.equal(await m.locator('.personal-area-account-results button').count(),0);await btn(m,'account-query').fill('Alice');await m.getByRole('button',{name:new RegExp('^Alice · @')}).click();await btn(m,'assign').click();await m.waitForFunction(()=>state.room.personalAreas.find(x=>x.areaId==='static-desk').owner?.name==='Alice');assert.equal(await m.evaluate(()=>logs.posts.length),beforeSearch+1);pass('Static assignment searches actual scoped accounts and saves the selected registered identity');
 await save(alice,s=>s.objects.push({id:'alice-static',name:'Alice static',type:'chair',x:-8,z:8,rotation:0}));await save(manager,s=>s.objects.push({id:'manager-static',name:'Manager static',type:'chair',x:-7,z:8,rotation:0}));await m.evaluate(()=>refreshRoom());await btn(m,'revoke').click();await btn(m,'revoke-keep').waitFor();await btn(m,'revoke-remove').waitFor();const revokePosts=await m.evaluate(()=>logs.posts.length);await btn(m,'cancel').click();assert.equal(await m.evaluate(()=>logs.posts.length),revokePosts);await btn(m,'revoke').click();await btn(m,'revoke-remove').click();await m.waitForFunction(()=>!state.room.personalAreas.find(x=>x.areaId==='static-desk').ownerId);assert.equal(await m.evaluate(()=>state.room.scene.objects.some(x=>x.id==='alice-static')),false);assert.equal(await m.evaluate(()=>state.room.scene.objects.some(x=>x.id==='manager-static')),true);pass('Revoke exposes keep/remove/cancel and removes only the current grant’s own objects');
 const b=await pageFor(bob);await b.evaluate(()=>move('desk-c'));await open(b,'desk-c');await b.evaluate(()=>{hooks.dropNext='claim'});await btn(b,'claim').click();await btn(b,'retry').waitFor();const originalRetry=await b.evaluate(()=>logs.posts.find(p=>p.url.endsWith('/claim')));await revoke(manager,'desk-c');await btn(b,'retry').click();await settled(b);assert.equal(await btn(b,'retry').count(),0);const retryBodies=await b.evaluate(()=>logs.posts.filter(p=>p.url.endsWith('/claim')).map(p=>p.body));assert.deepEqual(retryBodies,[originalRetry.body,originalRetry.body]);assert.equal(await b.evaluate(()=>state.room.personalAreas.find(x=>x.areaId==='desk-c').ownerId),null);assert.equal(await btn(b,'build').count(),0);assert.equal(await b.evaluate(()=>state.room.capabilities.canBuild),false);pass('Lost successful response retries exact payload; historical duplicate after revoke never resurrects rights');
 await b.evaluate(()=>{window.releaseResponse=undefined;hooks.delayNext='claim'});await btn(b,'claim').click();await b.waitForFunction(()=>typeof releaseResponse==='function');await btn(b,'close').click();await b.evaluate(()=>releaseResponse());await b.waitForTimeout(100);assert.equal(await b.evaluate(()=>surface.isOpen()),false);assert.equal(await b.evaluate(()=>state.room.personalAreas.find(x=>x.areaId==='desk-c').isOwner),true);pass('Closing a pending operation stays closed while its current result reconciles');
 await open(b,'desk-c');await b.evaluate(()=>{hooks.dirty=true;state.scene.objects.push({id:'unsaved-draft',type:'chair',x:8,z:0});});await revoke(manager,'desk-c');await b.evaluate(()=>refreshRoom());assert.equal(await btn(b,'build').count(),0);assert.equal(await b.evaluate(()=>state.scene.objects.at(-1).id),'unsaved-draft');assert.equal(await b.locator('.personal-area-status').count(),0);pass('Revocation removes visible build controls without mutating the editor draft');
 await b.evaluate(()=>surface.close());await b.locator('#open').focus();await b.locator('#open').click();await b.waitForFunction(()=>document.querySelector('[data-personal-key=close]')===document.activeElement);await b.keyboard.press('Shift+Tab');assert.equal(await b.evaluate(()=>document.querySelector('.personal-area-sheet').contains(document.activeElement)),true);await b.keyboard.press('Tab');assert.equal(await b.evaluate(()=>document.querySelector('[data-personal-key=close]')===document.activeElement),true);await b.keyboard.press('Escape');assert.equal(await b.evaluate(()=>surface.isOpen()),false);assert.equal(await b.locator('#open').evaluate(n=>document.activeElement===n),true);await b.evaluate(()=>surface.restore());assert.equal(await b.evaluate(()=>surface.isOpen()),true);pass('Focus containment, Escape, return focus and Forward restore work');
 await b.evaluate(()=>surface.open('desk-c'));await b.setViewportSize({width:320,height:480});await b.evaluate(()=>document.documentElement.style.fontSize='200%');let box=await btn(b,'close').boundingBox();assert(box.width>=44&&box.height>=44&&box.x>=0&&box.y>=0&&box.x+box.width<=320);assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth),320);await b.screenshot({path:'evidence/personal-areas-mobile.png'});await btn(b,'claim').scrollIntoViewIfNeeded();let control=await btn(b,'claim').boundingBox();assert(control.y>=0&&control.y+control.height<=480);await b.screenshot({path:'evidence/personal-areas-mobile-controls.png'});await b.setViewportSize({width:740,height:320});box=await btn(b,'close').boundingBox();assert(box.y>=0&&box.y+box.height<=320);await b.screenshot({path:'evidence/personal-areas-landscape.png'});await btn(b,'claim').scrollIntoViewIfNeeded();control=await btn(b,'claim').boundingBox();assert(control.y>=0&&control.y+control.height<=320);pass('320px and short-height landscape keep a reachable 44px close with no page overflow');
 await b.setViewportSize({width:1100,height:800});await b.evaluate(()=>{document.documentElement.style.fontSize='100%';window.releaseResponse=undefined;hooks.delayNext='claim';});await btn(b,'claim').click();await b.waitForFunction(()=>typeof releaseResponse==='function');await revoke(manager,'desk-c');await b.evaluate(()=>refreshRoom());await b.evaluate(()=>releaseResponse());await settled(b);assert.equal(await b.evaluate(()=>state.room.personalAreas.find(x=>x.areaId==='desk-c').ownerId),null);assert.equal(await btn(b,'build').count(),0);pass('A delayed successful claim cannot roll back a newer authoritative revoke');
 await b.evaluate(()=>{surface.clear();state.room={id:'another-room',revision:0,personalAreas:[],scene:{objects:[]}};surface.update();});assert.equal(await b.evaluate(()=>surface.isOpen()),false);assert.equal(await b.locator('.personal-area-invitation').isVisible(),false);pass('Room changes clear the previous room’s surface and entry offers');
 await m.setViewportSize({width:1100,height:800});await open(m,'desk-b');await m.screenshot({path:'evidence/personal-areas-desktop.png'});assert.deepEqual(errors,[]);pass('No browser runtime errors');
}catch(e){console.error(e);checks.push({name:'failure',status:'failed',error:e.stack});process.exitCode=1;await currentPage?.screenshot({path:'evidence/personal-areas-failure.png'}).catch(()=>{});}
finally{await mkdir('evidence',{recursive:true});await writeFile('evidence/personal-areas-browser-checks.json',JSON.stringify({checks,errors,limitations:['Standalone DOM module and real local server, no full-world renderer integration','Headless Chromium emulation, not physical iOS/Android or Safari/Firefox certification']},null,2));for(const c of contexts)await c.close();await browser.close();await app.close();await rm(temp,{recursive:true,force:true});}
