/** Native input against the actual shell. Fixtures use only a fresh local server. */
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds,emptyScene} from '../src/worlds.js';
import {makePng} from '../fixtures/png-fixtures.mjs';
const out=process.env.DPR_EVIDENCE||new URL('../evidence/dpr-picking',import.meta.url).pathname;await mkdir(out,{recursive:true});
const dist=process.env.DPR_DIST||new URL('../dist',import.meta.url).pathname;
const seeds=structuredClone(seedWorlds);seeds[0].rooms[0].scene={...emptyScene(),bounds:{width:16,depth:16},spawn:{x:0,z:5},objects:[{id:'dpr-chair',name:'DPR chair',type:'chair',x:0,z:-2,rotation:0}]};
const app=createGameServer({seeds,dist}),address=await app.listen(0),base=`http://127.0.0.1:${address.port}`,browser=await launch();
const checks=[],errors=[],contexts=[];let page,ownerStorage;
const results={startedAt:new Date().toISOString(),bundleSha256:createHash('sha256').update(await readFile(dist+'/main.js')).digest('hex'),checks,errors,scope:'Actual local game, native Playwright mouse and CDP touch, read-only state/projection diagnostics. Generated PNG fixture uses authenticated local API; no upload-flow claim, physical phone or external service.'};
const persist=()=>writeFile(out+'/results.json',JSON.stringify(results,null,2));const report=async(name,data={})=>{checks.push({name,status:'passed',...data});console.log('PASS',name);await persist();};
const near=(a,b)=>assert(Math.abs(a-b)<.08,`${a} != ${b}`);
async function screen(x,z,y=0){const p=await page.evaluate(a=>window.__universe.getScreenPoint(a.x,a.z,a.y),{x,z,y});assert(p?.visible);const id=await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id,p);assert.equal(id,'game','actual projected point must be unobscured canvas');return p;}
try{
 for(const touch of [false,true]){
  const context=await browser.newContext({viewport:touch?{width:390,height:844}:{width:1000,height:760},deviceScaleFactor:2,hasTouch:touch,isMobile:touch,...(ownerStorage?{storageState:ownerStorage}:{})});contexts.push(context);page=await context.newPage();page.setDefaultTimeout(60000);page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base,{waitUntil:'domcontentloaded',timeout:60000});if(!ownerStorage){await page.getByPlaceholder('Your name').fill('DPR pointer fixture');await page.locator('#join-button').click();}await page.waitForFunction(()=>window.__universe?.getState().ready);const cdp=touch?await context.newCDPSession(page):null;
  const click=async p=>{if(!touch)return page.mouse.click(p.x,p.y);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});};
  await page.locator('#dock-build').click();if(await page.locator('.builder-tray').isVisible())await page.getByRole('button',{name:'Close furniture tray',exact:true}).click();const chair=await screen(0,-2,.5);await click(chair);assert.equal(await page.evaluate(()=>window.__universe.getEditor().selected),'dpr-chair','real input selects chair at its projected CSS point');await report(`DPR2 native ${touch?'touch':'mouse'} selects the projected native chair`,{chair,metrics:await page.locator('#game').evaluate(e=>({dpr:devicePixelRatio,clientWidth:e.clientWidth,clientHeight:e.clientHeight,renderWidth:e.width,renderHeight:e.height,ratio:e.clientWidth/e.width}))});
  await page.getByRole('button',{name:'Close item details',exact:true}).click();await page.getByRole('button',{name:'↖ Select',exact:true}).click();const yaw=await page.evaluate(()=>window.__universe.getCamera().yaw);await page.locator('#camera-right').click();await page.waitForFunction(y=>Math.abs(window.__universe.getCamera().yaw-y)>.1,yaw);let rotatedChair;for(let attempt=0;attempt<10;attempt++){try{rotatedChair=await screen(0,-2,.5);break;}catch{const previous=await page.evaluate(()=>window.__universe.getCamera().distance);await page.locator('#zoom-out').click();await page.waitForFunction(d=>window.__universe.getCamera().distance>=d,previous);}}assert(rotatedChair,'native zoom can frame chair after orbit');await click(rotatedChair);assert.equal(await page.evaluate(()=>window.__universe.getEditor().selected),'dpr-chair');await page.getByRole('button',{name:'Close item details',exact:true}).click();await report(`DPR2 native ${touch?'touch':'mouse'} picking remains aligned after visible camera orbit`,{rotatedChair});
  const bytes=makePng({width:64,height:64,pixel:(x,y)=>[245,35,225,x<24&&y<24?0:255]});const upload=await page.request.post(base+'/api/rooms/commons/assets',{data:{operationId:'dpr-fixture',draft:{name:'DPR alpha floor',tags:'dpr',depthPreset:'floor',floating:true},mediaType:'image/png',pngBase64:bytes.toString('base64')}});assert([200,201].includes(upload.status()),`fixture upload ${upload.status()}`);
  if(!await page.getByRole('button',{name:'Custom images',exact:true}).isVisible())await page.getByRole('button',{name:'More build tools',exact:true}).click();await page.getByRole('button',{name:'Custom images',exact:true}).click();await page.getByRole('button',{name:/^Place DPR alpha floor \(/}).click();await page.locator('#image-library').waitFor({state:'hidden'});let target,world;for(const [x,z] of [[3,2],[-3,2],[-3,4],[-2,4],[0,2],[2,-1],[-3,-1]]){try{const q=await screen(x,z);await screen(x+.5,z+.5,.05);await screen(x-.6,z-.6,.05);target=q;world={x,z};break;}catch{}}assert(target,'fixture needs three unobscured native canvas points');let preview;if(touch){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:target.x,y:target.y,id:1}]});preview=await page.evaluate(()=>window.__universe.getEditor().preview);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await page.mouse.move(target.x,target.y);preview=await page.evaluate(()=>window.__universe.getEditor().preview);await click(target);}assert(preview?.valid,preview?.reason);near(preview.x,world.x);near(preview.z,world.z);const imageId=await page.evaluate(()=>window.__universe.getState().scene.objects.at(-1).id);await page.getByRole('button',{name:'↖ Select',exact:true}).click();let hit=await screen(world.x+.5,world.z+.5,.05);await click(hit);assert.equal(await page.evaluate(()=>window.__universe.getEditor().selected),imageId);if(touch)await page.getByRole('button',{name:'Close item details',exact:true}).tap();hit=await screen(world.x-.6,world.z-.6,.05);await click(hit);assert.equal(await page.evaluate(()=>window.__universe.getEditor().selected),null);await report(`DPR2 ${touch?'touch':'mouse'} ghost matches world point; opaque pixels select and transparent pixels pass through`,{preview:{x:preview.x,z:preview.z},imageId});
  await page.screenshot({path:out+`/dpr2-${touch?'touch':'mouse'}.png`});if(!ownerStorage)ownerStorage=await context.storageState();await context.close();contexts.pop();
 }
 assert.deepEqual(errors,[]);
}catch(error){console.error(error);checks.push({name:'DPR regression',status:'failed',error:error.stack});await page?.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}finally{await persist();for(const c of contexts)await c.close();await browser.close();await app.close();}
