import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile, mkdir, writeFile} from 'node:fs/promises';
import {chromium} from 'playwright-core';
import embedded from '@sparticuz/chromium';
const fixture = String.raw`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/social.css"><style>:root{--u-text-soft:#eee;--u-text-muted:#bbb;--u-surface-flat:#17131f;--u-card:#24202d;--u-primary:#544d72;--u-secondary:#292435;--u-secondary-border:#555;--u-decision-size:44px;--u-pill:8px}body{margin:0;font:14px Arial}#root{width:min(360px,100vw);height:min(800px,100dvh)}</style></head><body><div id="root"></div><script type="module">
import {mountSocial} from '/social.js';
window.state={user:{id:'a',name:'Ay'},room:{id:'r',name:'Garden',role:'member'},people:[{id:'a',name:'Ay'},{id:'b',name:'Bee'}],ready:true};
window.calls=[];window.unreads=[];window.gameKeys=0;window.seq=0;window.rev=0;window.rows=new Map();window.loseNext=false;window.holdNext=false;window.resolvers=[];
window.addEventListener('keydown',()=>gameKeys++);
window.base=()=>({protocol:'proximity-text-v1',available:true,canSend:true,reason:null,selfId:'a',roomId:'r',connectionEpoch:'epoch',contextRevision:++rev,bubbleId:'bubble',memberId:'member-a',membershipRevision:1,conversationRecipients:[{accountId:'b',memberId:'member-b'}],recipientCount:1,limits:{maxCodePoints:2000,maxBytes:8192,history:200}});
window.push=(change={})=>{window.lastContext={...base(),...change};social.onEvent({type:'proximity-text-context',data:lastContext})};
window.incoming=(change={})=>social.onEvent({type:'proximity-text-message',data:{id:'remote-'+(++seq),requestId:'remote-request-'+seq,createdAt:Date.now(),roomId:'r',bubbleId:lastContext.bubbleId,membershipRevision:1,fromMemberId:'member-b',author:{id:'b',name:'Bee'},text:'message '+seq,recipient:{connectionEpoch:lastContext.connectionEpoch,memberId:lastContext.memberId},ownAccountCopy:false,...change}});
window.api=async(path,options={})=>{calls.push({path,...options});if(path==='/api/proximity-text/messages'){const b=options.body;if(holdNext){holdNext=false;await new Promise(resolve=>resolvers.push(resolve))}let message=rows.get(b.requestId),duplicate=!!message;if(!message){message={...b,id:'accepted-'+b.requestId,createdAt:Date.now(),fromMemberId:b.memberId,author:{id:'a',name:'Ay'},recipient:{connectionEpoch:b.connectionEpoch,memberId:b.memberId},ownAccountCopy:false};rows.set(b.requestId,message)}if(loseNext){loseNext=false;throw Error('Connection interrupted')}return {message,duplicate}}if(path.startsWith('/api/proximity-text?'))return lastContext;if(path==='/api/conversations')return {conversations:[]};return {messages:[]}};
window.social=mountSocial({root:document.querySelector('#root'),api,getState:()=>state,onNearbyUnread:count=>unreads.push(count)});window.ready=true;
</script></body></html>`;
const modules=new Set(['/password-policy.js','/social-sheet-layout.js','/universe-icons.js','/social.css','/social.js','/permissions.js','/proximity-text.js','/proximity-typing.js']);
const server=http.createServer(async(req,res)=>{if(modules.has(req.url)){res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(new URL('../src'+req.url,import.meta.url)))}else{res.setHeader('Content-Type','text/html');res.end(fixture)}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
let browser;const results=[],errors=[];
const check=async(name,fn)=>{await fn();results.push({test:name,status:'pass'});console.log('PASS '+name)};
try{
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||await embedded.executablePath(),headless:true,args:['--no-sandbox','--no-zygote','--disable-gpu']});
 const page=await browser.newPage({viewport:{width:900,height:860}});page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready);
 const composer=()=>page.getByRole('textbox',{name:'Message nearby people'}),send=()=>page.getByRole('button',{name:'Send nearby message'});
 await check('default off adds no controls or Nearby calls; enabled discovery preserves focused Room draft',async()=>{assert.equal(await page.getByRole('button',{name:'Nearby',exact:true}).count(),0);await page.getByRole('textbox',{name:'Message the room'}).fill('room draft');await page.evaluate(()=>push());assert.equal(await page.getByRole('textbox',{name:'Message the room'}).inputValue(),'room draft');assert.equal(await page.getByRole('textbox',{name:'Message the room'}).evaluate(n=>n===document.activeElement),true);assert.equal(await page.evaluate(()=>calls.some(c=>c.path.startsWith('/api/proximity-text'))),false);await page.getByRole('button',{name:'Nearby',exact:true}).click()});
 await check('native Shift+Enter and Enter send one plain-text message without game keys',async()=>{await composer().fill('first');await composer().press('Shift+Enter');await composer().press('End');await composer().type('second');assert.equal(await composer().inputValue(),'first\nsecond');await composer().press('Enter');await page.locator('.social-message-text').waitFor();assert.equal(await page.evaluate(()=>calls.filter(c=>c.path==='/api/proximity-text/messages').length),1);assert.equal(await page.evaluate(()=>gameKeys),0);assert.equal(await composer().inputValue(),'')});
 await check('IME composition Enter never submits; focus and cursor survive incoming inert text',async()=>{await composer().fill('composing');await composer().dispatchEvent('compositionstart');await composer().press('Enter');await composer().dispatchEvent('compositionend');assert.equal(await page.evaluate(()=>calls.filter(c=>c.path==='/api/proximity-text/messages').length),1);await composer().fill('keep focus');await composer().press('ArrowLeft');const cursor=await composer().evaluate(n=>n.selectionStart);await page.evaluate(()=>incoming({text:'<script>window.bad=true</script> https://example.test **plain**'}));assert.equal(await composer().evaluate(n=>n===document.activeElement),true);assert.equal(await composer().evaluate(n=>n.selectionStart),cursor);assert.equal(await page.locator('.social-message-text script,.social-message-text a').count(),0);assert.equal(await page.evaluate(()=>window.bad),undefined)});
 await check('ambiguous retry is explicit, same request ID, one accepted row; newer draft survives',async()=>{await composer().fill('retry me');await page.evaluate(()=>loseNext=true);await send().click();await page.getByRole('button',{name:'Retry nearby message'}).waitFor();assert.equal(await page.getByText('retry me',{exact:true}).count(),0);const count=await page.evaluate(()=>calls.length);await composer().press('Enter');assert.equal(await page.evaluate(()=>calls.length),count);await composer().fill('newer draft');await page.getByRole('button',{name:'Retry nearby message'}).click();await page.getByText('retry me',{exact:true}).waitFor();const pair=await page.evaluate(()=>calls.filter(c=>c.path==='/api/proximity-text/messages').slice(-2).map(c=>c.body));assert.deepEqual(pair[0],pair[1]);assert.equal(await composer().inputValue(),'newer draft');assert.equal(await page.getByText('retry me',{exact:true}).count(),1)});
 await check('incoming while focused DM preserves thread and focus; only validated messages increment unread',async()=>{await page.evaluate(()=>social.openDm({id:'b',name:'Bee'}));const dm=page.getByRole('textbox',{name:'Message Bee',exact:true});await dm.fill('private draft');await page.evaluate(()=>{incoming({recipient:{connectionEpoch:'retired',memberId:'member-a'}});incoming({text:'valid unread'})});assert.equal(await dm.inputValue(),'private draft');assert.equal(await dm.evaluate(n=>n===document.activeElement),true);assert.deepEqual(await page.evaluate(()=>unreads),[1]);await page.getByRole('button',{name:'Nearby',exact:true}).click();assert.deepEqual(await page.evaluate(()=>unreads),[1,0]);await page.getByText('valid unread',{exact:true}).waitFor()});
 await check('epoch refresh keeps visible rows/draft; disconnect cannot send and recovery never auto-sends',async()=>{const before=await page.locator('.social-message').count();await composer().fill('offline draft');await page.evaluate(()=>{social.resetNearbyConnection('error');push({connectionEpoch:'epoch-2'})});assert.equal(await page.locator('.social-message').count(),before);assert.equal(await composer().inputValue(),'offline draft');const sends=await page.evaluate(()=>calls.filter(c=>c.path==='/api/proximity-text/messages').length);await page.evaluate(()=>social.resetNearbyConnection('error'));await composer().press('Enter');assert.equal(await send().isDisabled(),true);await page.evaluate(()=>push({connectionEpoch:'epoch-3'}));assert.equal(await page.evaluate(()=>calls.filter(c=>c.path==='/api/proximity-text/messages').length),sends);assert.equal(await composer().inputValue(),'offline draft')});
 await check('leave makes draft read-only; new stay requires selection and never replays transcript',async()=>{await page.evaluate(()=>push({canSend:false,reason:'no-active-bubble',bubbleId:null,membershipRevision:null,conversationRecipients:[],recipientCount:0,connectionEpoch:'alone'}));assert.equal(await composer().getAttribute('readonly'),'');assert.equal(await composer().inputValue(),'offline draft');await page.evaluate(()=>push({bubbleId:'new-bubble',memberId:'new-member',connectionEpoch:'new-epoch'}));assert.equal(await composer().getAttribute('readonly'),'');await page.getByRole('button',{name:'Open current nearby stay'}).click();assert.equal(await composer().inputValue(),'');assert.equal(await page.locator('.social-message').count(),0);await page.locator('.social-nearby-details > summary').click();await page.getByRole('combobox',{name:'Nearby stays'}).selectOption({index:0});assert.equal(await composer().inputValue(),'offline draft');assert.ok(await page.locator('.social-message').count()>0);await page.getByRole('button',{name:'Open current nearby stay'}).click()});
 await check('Nearby drafts and rows never enter browser durable storage',async()=>{assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage}).includes('offline draft')),false);assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage}).includes('retry me')),false);assert.deepEqual(await page.evaluate(()=>indexedDB.databases()),[])});
 await check('native Tab and Escape reach controls, close cleanly and do not send',async()=>{await composer().fill('escape draft');await composer().press('Tab');assert.equal(await send().evaluate(n=>n===document.activeElement),true);await composer().focus();const sends=await page.evaluate(()=>calls.filter(c=>c.path==='/api/proximity-text/messages').length);await composer().press('Escape');assert.equal(await page.locator('#root').isVisible(),true);await composer().press('Escape');assert.equal(await page.locator('#root').isVisible(),false);await page.evaluate(()=>social.setTab('chat'));assert.equal(await composer().inputValue(),'escape draft');assert.equal(await page.evaluate(()=>calls.filter(c=>c.path==='/api/proximity-text/messages').length),sends)});
 await check('320px and landscape 200% keep composer and actions reachable within viewport',async()=>{for(const spec of [{width:320,height:640,zoom:1},{width:640,height:360,zoom:2}]){await page.setViewportSize({width:spec.width,height:spec.height});await page.evaluate(zoom=>{document.body.style.zoom=zoom;const root=document.querySelector('#root');root.style.width=`min(360px,${100/zoom}vw)`;root.style.height=`${100/zoom}dvh`},spec.zoom);await composer().scrollIntoViewIfNeeded();let box=await composer().boundingBox();assert.ok(box.x>=-1&&box.x+box.width<=spec.width+1);await send().scrollIntoViewIfNeeded();box=await send().boundingBox();if(!(box.y>=-1&&box.y+box.height<=spec.height+1)){console.log(JSON.stringify({spec,box,layout:await page.evaluate(()=>[...document.querySelectorAll('#root,.social-header,.social-tabs,.social-panel,.social-nearby-composer')].map(n=>({cls:n.className,height:n.getBoundingClientRect().height,scroll:n.scrollHeight,client:n.clientHeight,top:n.getBoundingClientRect().top})))}));await page.screenshot({path:'/tmp/nearby-geometry.png'})}assert.ok(box.y>=-1&&box.y+box.height<=spec.height+1);assert.equal(await send().isVisible(),true)}});
 await check('full reload has no transcript or Nearby draft',async()=>{await page.reload();await page.waitForFunction(()=>window.ready);await page.evaluate(()=>push());await page.getByRole('button',{name:'Nearby',exact:true}).click();assert.equal(await composer().inputValue(),'');assert.equal(await page.locator('.social-message').count(),0)});
 assert.deepEqual(errors,[]);await mkdir(new URL('../evidence/',import.meta.url),{recursive:true});await writeFile(new URL('../evidence/proximity-text-client-browser.json',import.meta.url),JSON.stringify({status:'pass',browser:await browser.version(),scope:'Native browser interactions against a social module fixture; live server and 3D shell covered separately',results,pageErrors:errors},null,2)+'\n');console.log(results.length+' Nearby native fixture checks passed');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}
