// Synthetic loopback HTTP/SSE fixtures using real Store/session/ICE paths.
// This is authorization proof, not WebRTC, device, relay, or SFU transport proof.
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {createGameServer} from '../server/app.mjs';
import {proximityFixture} from './fixtures/proximity-config.mjs';
const scene={version:1,theme:'garden',bounds:{width:100,depth:100},spawn:{x:0,z:0},objects:[],areas:[]};
const seeds=[{id:'world',name:'World',rooms:['r','other'].map(id=>({id,name:id,scene}))}];
async function fixture(t,config=proximityFixture){
 let time=1800000000000;const app=createGameServer({database:':memory:',seeds,questsEnabled:false,clock:()=>time,proximityMembershipConfig:config});const{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;t.after(()=>app.close());
 function client(cookie=''){return{cookie,async call(path,method='GET',body){const r=await fetch(base+path,{method,headers:{...(this.cookie?{cookie:this.cookie}:{}),...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,data:await r.json()};}};}
 async function add(name){const c=client();const response=await c.call('/api/session','POST',{name,woka:0});assert.equal(response.status,201);c.user=response.data.user;assert.equal((await c.call('/api/rooms/r/join','POST',{})).status,200);return c;}
 function sameUser(c){const token=randomBytes(32).toString('base64url'),hash=createHash('sha256').update(token).digest('hex');app.store.run('INSERT INTO sessions VALUES(?,?,?,?)',hash,c.user.id,time+1000000,'r');const copy=client(`universe_session=${token}`);copy.user=c.user;return copy;}
 const policy=async c=>{const r=await c.call('/api/media');assert.equal(r.status,200);return r.data;};
 const consent=async(c,enabled=true)=>{const current=await policy(c);const r=await c.call('/api/media/state','POST',{enabled,roomId:current.roomId,...(current.proximityMembership?.memberId?{memberId:current.proximityMembership.memberId}:{})});assert.equal(r.status,200);return r.data;};
 const hash=c=>createHash('sha256').update(c.cookie.split('=')[1]).digest('hex');
 return{app,base,add,sameUser,policy,consent,hash,advance(ms){time+=ms;},get time(){return time;}};
}
const signal=(p,to,extra={})=>({roomId:p.roomId,to:to.user.id,connectionId:'synthetic-connection',bubbleId:p.proximityMembership.bubbleId,fromMemberId:p.proximityMembership.memberId,toMemberId:p.peers.find(peer=>peer.id===to.user.id).memberId,intentGeneration:p.proximityMembership.transport.intentGeneration,mediaScope:p.proximityMembership.mediaScope,request:'offer',...extra});
const iceBody=p=>({scope:p.iceScope,requestId:randomBytes(18).toString('base64url')});
async function stream(t,f,c){
 const controller=new AbortController(),events=[],waiters=new Set();const response=await fetch(f.base+'/api/events',{headers:{cookie:c.cookie},signal:controller.signal});assert.equal(response.status,200);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
 const reading=(async()=>{try{for(;;){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,end);buffer=buffer.slice(end+2);const event=block.match(/^event: (.+)$/m)?.[1],data=block.match(/^data: (.+)$/m)?.[1];if(event&&data){events.push({event,data:JSON.parse(data)});for(const check of waiters)check();}}}}catch(e){if(e.name!=='AbortError')throw e;}})();t.after(async()=>{controller.abort();await reading;});
 return{events,wait(predicate,after=0){const find=()=>events.slice(after).find(predicate);if(find())return Promise.resolve(find());return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{waiters.delete(check);reject(Error('SSE fixture timed out'));},2500);const check=()=>{const found=find();if(found){clearTimeout(timeout);waiters.delete(check);resolve(found);}};waiters.add(check);check();});}};
}
test('explicit undefined option retains legacy response without new protocol',async t=>{
 const app=createGameServer({database:':memory:',seeds,questsEnabled:false});t.after(()=>app.close());const{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;let r=await fetch(base+'/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Legacy',woka:0})});const cookie=r.headers.get('set-cookie').split(';')[0];await fetch(base+'/api/rooms/r/join',{method:'POST',headers:{cookie,'content-type':'application/json'},body:'{}'});const p=await(await fetch(base+'/api/media',{headers:{cookie}})).json();assert.equal('proximityMembership'in p,false);assert.equal(p.limits.proximityParticipants,4);
});
test('HTTP counts six media-off members and blocks large mesh with no SFU or ICE claim',async t=>{
 const f=await fixture(t),members=[];for(let i=0;i<6;i++)members.push(await f.add('Member '+i));const p=await f.policy(members[0]);assert.equal(p.proximityMembership.transport.memberCount,6);assert.equal(p.proximityMembership.conversationRecipients.length,5);assert.deepEqual(p.peers,[]);assert.equal(p.proximityMembership.transport.blockedReason,'sfu-unavailable');assert.equal(p.proximityMembership.transport.connectedTransport,null);assert.equal(p.proximityMembership.transport.handoffComplete,false);const enabled=await f.consent(members[0]);assert.equal(enabled.enabled,true);assert.equal(enabled.iceScope,undefined);assert.equal((await members[0].call('/api/media/ice','POST',{scope:randomBytes(32).toString('base64url'),requestId:randomBytes(18).toString('base64url')})).status,403);
});
test('accepted-session HTTP policy, signaling and ICE cannot inherit another tab consent',async t=>{
 const f=await fixture(t),a=await f.add('A'),b=await f.add('B'),a2=f.sameUser(a);await f.consent(a);await f.consent(b);const p=await f.policy(a),other=await f.policy(a2);assert.equal(p.peers.length,1);assert.equal(other.enabled,false);assert.deepEqual(other.peers,[]);assert.equal(other.iceScope,undefined);assert.equal((await a.call('/api/media/ice','POST',iceBody(p))).status,200);assert.equal((await a2.call('/api/media/ice','POST',iceBody(p))).status,403);assert.equal((await a2.call('/api/media/signal','POST',signal(p,b))).status,403);assert.equal((await a.call('/api/media/signal','POST',signal(p,b))).status,200);
});
test('SSE scope is personalized and signaling reaches only currently consenting target sessions',async t=>{
 const f=await fixture(t),a=await f.add('A'),b=await f.add('B'),a2=f.sameUser(a),sa=await stream(t,f,a),sa2=await stream(t,f,a2);await f.consent(a);await f.consent(b);await sa2.wait(e=>e.event==='media-policy'&&e.data.proximityMembership?.transport?.memberCount===2);const a2Policies=sa2.events.filter(e=>e.event==='media-policy');assert(a2Policies.every(e=>e.data.enabled===false&&e.data.peers.length===0&&!e.data.iceScope));const from=await f.policy(b),offset=sa2.events.length;assert.equal((await b.call('/api/media/signal','POST',signal(from,a))).status,200);const event=await sa.wait(e=>e.event==='media-signal');assert.equal(event.data.mediaScope,from.proximityMembership.mediaScope);assert.equal(event.data.toMemberId,from.peers[0].memberId);await f.consent(b);await sa2.wait(e=>e.event==='media-policy',offset);assert.equal(sa2.events.some(e=>e.event==='media-signal'),false);
});
test('withdraw/reconsent rotates AV+ICE scope while membership identity stays stable',async t=>{
 const f=await fixture(t),a=await f.add('A'),b=await f.add('B');await f.consent(a);await f.consent(b);const old=await f.policy(a),oldSignal=signal(old,b);await f.consent(a,false);await f.consent(a);const next=await f.policy(a);assert.equal(next.proximityMembership.bubbleId,old.proximityMembership.bubbleId);assert.equal(next.proximityMembership.memberId,old.proximityMembership.memberId);assert.notEqual(next.proximityMembership.mediaScope,old.proximityMembership.mediaScope);assert.notEqual(next.iceScope,old.iceScope);assert.equal((await a.call('/api/media/signal','POST',oldSignal)).status,403);assert.equal((await a.call('/api/media/ice','POST',iceBody(old))).status,403);assert.equal((await a.call('/api/media/signal','POST',signal(next,b))).status,200);
});
test('last-session leave/rejoin and expiry cannot reuse scoped signals',async t=>{
 const f=await fixture(t),a=await f.add('A'),b=await f.add('B');await f.consent(a);await f.consent(b);const before=await f.policy(a),old=signal(before,b);assert.equal((await b.call('/api/rooms/other/join','POST',{})).status,200);assert.equal((await b.call('/api/rooms/r/join','POST',{})).status,200);await f.consent(b);const next=await f.policy(a);assert.notEqual(next.proximityMembership.bubbleId,before.proximityMembership.bubbleId);assert.equal((await a.call('/api/media/signal','POST',old)).status,403);f.app.store.run('UPDATE sessions SET expires_at=? WHERE token_hash=?',f.time,f.hash(b));assert.deepEqual((await f.policy(a)).peers,[]);assert.equal((await b.call('/api/media')).status,401);
});
test('unscoped legacy signals are rejected only in opt-in proximity; meeting remains legacy',async t=>{
 const f=await fixture(t),a=await f.add('A'),b=await f.add('B');await f.consent(a);await f.consent(b);assert.equal((await a.call('/api/media/signal','POST',{to:b.user.id,connectionId:'legacy',request:'offer'})).status,403);f.app.store.run('UPDATE rooms SET scene=? WHERE id=?',JSON.stringify({...scene,areas:[{id:'m',action:'meeting',x:0,z:0,width:10,depth:10}]}),'r');const p=await f.policy(a);assert.equal(p.context.kind,'meeting');assert.equal('proximityMembership'in p,false);assert.equal(p.peers.length,1);assert.equal((await a.call('/api/media/signal','POST',{to:b.user.id,connectionId:'legacy-meeting',request:'offer'})).status,200);
});
test('authority failure pushes an empty teardown policy rather than retaining cached SSE peers',async t=>{
 const f=await fixture(t),a=await f.add('A'),b=await f.add('B'),events=await stream(t,f,a);await f.consent(a);await f.consent(b);const offset=events.events.length;f.app.presence.get(`r:${b.user.id}`).x=NaN;const result=await a.call('/api/media');assert.equal(result.status,500);const denied=await events.wait(e=>e.event==='media-policy'&&e.data.proximityAuthorityUnavailable,offset);assert.equal(denied.data.enabled,false);assert.deepEqual(denied.data.peers,[]);assert.equal(denied.data.iceScope,undefined);f.app.presence.get(`r:${b.user.id}`).x=0;const restored=await f.policy(a);assert.equal(restored.enabled,false);assert.deepEqual(restored.peers,[]);
});
test('over-cap session join is rejected before mutating room admission or other members',async t=>{
 const f=await fixture(t,{...proximityFixture,maxSessionsPerMember:1}),a=await f.add('A'),b=await f.add('B');await f.consent(a);await f.consent(b);const a2=f.sameUser(a);f.app.store.run('UPDATE sessions SET current_room_id=NULL WHERE token_hash=?',f.hash(a2));const denied=await a2.call('/api/rooms/r/join','POST',{});assert.equal(denied.status,429);assert.equal(denied.data.code,'PROXIMITY_SESSION_LIMIT');assert.equal(f.app.store.get('SELECT current_room_id FROM sessions WHERE token_hash=?',f.hash(a2)).current_room_id,null);assert.equal((await f.policy(a)).peers.length,1);
});
test('opt-in meeting preserves another consenting tab when one opts out and refuses nonconsenting delivery',async t=>{
 const f=await fixture(t),a=await f.add('A'),b=await f.add('B'),a2=f.sameUser(a);f.app.store.run('UPDATE rooms SET scene=? WHERE id=?',JSON.stringify({...scene,areas:[{id:'m',action:'meeting',x:0,z:0,width:10,depth:10}]}),'r');await f.consent(a);await f.consent(a2);await f.consent(b);await f.consent(a2,false);const p=await f.policy(a),other=await f.policy(a2);assert.equal(p.enabled,true);assert.equal(p.peers.length,1);assert.equal(other.enabled,false);assert.deepEqual(other.peers,[]);
});
test('ordinary chat mute does not remove bubble membership, while moderation ban tears down media',async t=>{
 const f=await fixture(t),a=await f.add('Owner'),b=await f.add('Member');await f.consent(a);await f.consent(b);const before=await f.policy(a),old=signal(before,b);assert.equal((await a.call('/api/rooms/r/moderate','POST',{userId:b.user.id,action:'mute'})).status,200);const muted=await f.policy(a);assert.equal(muted.proximityMembership.transport.memberCount,2);assert.equal(muted.proximityMembership.bubbleId,before.proximityMembership.bubbleId);assert.equal(muted.peers.length,1);assert.equal((await b.call('/api/rooms/r/messages','POST',{text:'muted fixture'})).status,403);assert.equal((await a.call('/api/rooms/r/moderate','POST',{userId:b.user.id,action:'ban'})).status,200);assert.deepEqual((await f.policy(a)).peers,[]);assert.equal((await a.call('/api/media/signal','POST',old)).status,403);
});
test('opt-in meeting drops a target whose last consenting session expires even with another live tab',async t=>{
 const f=await fixture(t),a=await f.add('A'),b=await f.add('B'),b2=f.sameUser(b);f.app.store.run('UPDATE rooms SET scene=? WHERE id=?',JSON.stringify({...scene,areas:[{id:'m',action:'meeting',x:0,z:0,width:10,depth:10}]}),'r');await f.consent(a);await f.consent(b);assert.equal((await f.policy(a)).peers.length,1);f.app.store.run('UPDATE sessions SET expires_at=? WHERE token_hash=?',f.time,f.hash(b));assert.deepEqual((await f.policy(a)).peers,[]);assert.equal((await f.policy(b2)).enabled,false);assert.equal((await a.call('/api/media/signal','POST',{to:b.user.id,connectionId:'expired-meeting',request:'offer'})).status,403);
});
