/** Local controlled protocol fixture only. No server/provider authorization or 3D proof. */
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright-core';
import embedded from '@sparticuz/chromium';
const fixture = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/universe-tokens.css"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/hud-availability.css"><link rel="stylesheet" href="/proximity-controls.css"><style>body{margin:0;background:#302f40}#app{position:relative;width:100vw;height:100dvh}#draft{position:absolute;left:150px;top:70px;width:120px;height:45px;z-index:13}#game{position:absolute;inset:0;width:100%;height:100%;background:linear-gradient(145deg,#465e58,#26243b)}#fixture-label{position:absolute;top:8px;left:10px;color:#fff;font:11px Arial;pointer-events:none}#dock{height:64px}#view-controls{z-index:7}.proximity-controls{z-index:12}#camera{width:48px;height:48px}#shortcuts-help,#quick-actions{z-index:8}</style></head><body><div id="app" data-hud-compact="false" data-hud-constrained="false"><div id="game" tabindex="0"></div><div id="fixture-label">LOCAL CONTROLLED PROTOCOL FIXTURE</div><textarea id="draft" aria-label="Existing chat draft"></textarea><div id="joystick"><div id="joystick-thumb"></div></div><div id="view-controls"><button id="camera" aria-label="Camera">View</button></div><nav id="dock"><button>Chat</button><button>People</button><button>Build</button></nav><div id="controls"></div></div><script type="module">
import {createProximityControls} from '/proximity-controls.js'; import {mountProximityControls} from '/proximity-controls-ui.js';
window.state={user:{id:'a'},room:{id:'r'},ready:true};window.clockOffset=0;window.calls=[];window.rev=0;window.hold=false;window.fail=false;window.resolvers=[];window.gameKeys=0;window.addEventListener('keydown',()=>gameKeys++);
window.base=()=>({protocol:'proximity-controls-v1',available:true,accountId:'a',connectionId:'stream-1',roomId:'r',memberId:'member-a',bubbleId:'bubble',membershipRevision:1,controlRevision:1,stateRevision:1,snapshotRevision:++rev,locked:false,full:false,participants:[{accountId:'a',memberId:'member-a',name:'Ay'},{accountId:'b',memberId:'member-b',name:'Bee'}],canLock:true,canInvite:true,ignoreRequests:false,invitations:[],outgoingInvitations:[],following:null,followers:[],serverTime:Date.now(),limits:{sourceUnitsPerWorldUnit:32,memberTtlMs:60000,invitationTtlMs:30000}});
window.invite=(change={})=>({invitationId:'invite-1',leaderId:'b',leaderMemberId:'member-b',leaderName:'Bee',expiresAt:Date.now()+30000,...change});
window.push=(change={})=>{window.current={...base(),...change};return controller.acceptContext(current)};
window.api=async(path,opts={})=>{calls.push({path,...opts});if(hold)await new Promise(r=>resolvers.push(r));if(fail)throw Error('Fixture network failure');if(!opts.body)return current;const b=opts.body;let value={...current,snapshotRevision:++rev,stateRevision:current.stateRevision+1,serverTime:Date.now()};if(b.action==='lock')value.locked=b.locked;if(b.action==='preferences'){value.ignoreRequests=b.ignoreRequests;if(b.ignoreRequests)value.invitations=[]}if(b.action==='decline')value.invitations=[];if(b.action==='accept'){value.invitations=[];value.following={leaderId:'b',leaderMemberId:'member-b',leaderName:'Bee',leaseId:'lease-1',controlling:true,controllerConnected:true,leaderPresence:{x:2,z:3,lastSeen:Date.now(),moving:true}}}if(b.action==='stop'){value.invitations=[];value.outgoingInvitations=[];value.following=null;value.followers=[]}if(b.action==='invite')value.outgoingInvitations=[{invitationId:'sent',recipientId:'b',recipientMemberId:'member-b',recipientName:'Bee',expiresAt:Date.now()+30000}];current=value;return{ok:true,duplicate:false,state:value}};
window.controller=createProximityControls({api,getState:()=>state,storage:null,monotonicNow:()=>performance.now()+clockOffset});window.ui=mountProximityControls({root:document.querySelector('#controls'),controller,onReturnFocus:()=>document.querySelector('#game').focus()});window.ready=true;
</script></body></html>`;
const src = new Set(['/proximity-controls.js','/proximity-controls-ui.js','/proximity-controls.css','/hud-availability.css']);
const server = http.createServer(async(req,res)=>{try{if(src.has(req.url)){res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'text/javascript');res.end(await readFile(new URL('../src'+req.url,import.meta.url)))}else if(req.url==='/style.css'||req.url==='/universe-tokens.css'||req.url.startsWith('/assets/')){res.setHeader('Content-Type',req.url.endsWith('.css')?'text/css':'application/octet-stream');res.end(await readFile(new URL('../public'+req.url,import.meta.url)))}else{res.setHeader('Content-Type','text/html');res.end(fixture)}}catch{res.statusCode=404;res.end()}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const out='evidence/proximity-controls';await mkdir(out,{recursive:true});let browser;const checks=[],errors=[],layouts=[],visualStates=[];
const check=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name)};
try {
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||await embedded.executablePath(),headless:true,args:['--no-sandbox','--no-zygote','--disable-gpu']});
 const page=await browser.newPage({viewport:{width:1280,height:800}});page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:'+server.address().port;await page.goto(url);await page.waitForFunction(()=>ready);
 await check('disabled controls stay hidden without traffic',async()=>{assert.equal(await page.locator('#controls').isHidden(),true);assert.equal(await page.evaluate(()=>calls.length),0)});
 await check('incoming invitations preserve unrelated composer node, draft, focus, selection and scroll',async()=>{await page.getByRole('textbox').fill('unsent draft');await page.getByRole('textbox').evaluate(n=>{window.savedDraft=n;n.setSelectionRange(2,5)});await page.evaluate(()=>push({full:true,invitations:[invite()]}));assert.deepEqual(await page.getByRole('textbox').evaluate(n=>({same:n===savedDraft,value:n.value,start:n.selectionStart,end:n.selectionEnd,focus:document.activeElement===n})),{same:true,value:'unsent draft',start:2,end:5,focus:true});assert.equal(await page.locator('.proximity-summary').textContent(),'With BeeFull');assert.equal(await page.evaluate(()=>controller.snapshot().motion),null);assert.equal(await page.evaluate(()=>controller.snapshot().followSpeedLimited),false)});
 await check('equivalent live updates retain real Accept node; native Enter accepts without leaking game keys',async()=>{const accept=page.getByRole('button',{name:'Accept Bee’s follow invitation'});await accept.focus();await accept.evaluate(n=>window.savedAccept=n);await page.evaluate(()=>{for(let i=0;i<30;i++)push({invitations:[invite()]})});assert.equal(await accept.evaluate(n=>n===savedAccept&&document.activeElement===n),true);const before=await page.evaluate(()=>gameKeys);await accept.press('Enter');await page.getByRole('button',{name:'Stop following',exact:true}).waitFor();assert.equal(await page.evaluate(()=>gameKeys),before);assert.equal(await page.evaluate(()=>controller.snapshot().motion?.leaseId),'lease-1')});
 await check('Stop immediately retires local motion while acknowledgement fails and remains directly retryable',async()=>{await page.evaluate(()=>{hold=true;fail=true});await page.getByRole('button',{name:'Stop following',exact:true}).click();assert.equal(await page.evaluate(()=>controller.snapshot().motion),null);await page.evaluate(()=>{hold=false;resolvers.shift()()});await page.getByText(/Server stop is unconfirmed/).waitFor();assert.equal(await page.getByRole('button',{name:'Stop following',exact:true}).getAttribute('aria-disabled'),'false');await page.evaluate(()=>fail=false);await page.getByRole('button',{name:'Stop following',exact:true}).click();await page.getByRole('button',{name:'Follow me',exact:true}).waitFor()});
 // Real retained product UI and controller, native input, and a controlled local
 // elapsed clock. Invitation duration remains the production 30,000 ms.
 const preparePending=async()=>page.evaluate(()=>{clockOffset=0;push({outgoingInvitations:[{invitationId:'pending',recipientId:'b',recipientMemberId:'member-b',recipientName:'Bee',expiresAt:Date.now()+30000}]});return calls.length});
 const expirePending=async(render=true)=>page.evaluate(render=>{clockOffset+=30001;if(render)ui.render();},render);
 const follow=page.locator('[data-control=follow]');
 await check('native pointer Stop gesture cannot become Invite when its pending consent expires before release',async()=>{
  const before=await preparePending();await page.getByRole('button',{name:'Stop leading',exact:true}).hover();await page.mouse.down();await expirePending();assert.equal(await follow.getAttribute('aria-label'),'Follow me');const box=await follow.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.up();assert.equal(await page.evaluate(()=>calls.length),before,'An expired Stop gesture must not send a new invitation');assert.equal(await page.evaluate(()=>controller.snapshot().motion),null);await page.evaluate(()=>push());
 });
 await check('native Space Stop gesture cannot become Invite across expiry; a new Space gesture still invites',async()=>{
  const before=await preparePending();await follow.focus();await page.keyboard.down('Space');await expirePending();await page.keyboard.up('Space');assert.equal(await page.evaluate(()=>calls.length),before,'Space release must preserve its original Stop intent');await follow.press('Space');assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'invite');assert.equal(await page.evaluate(()=>calls.length),before+1);await page.evaluate(()=>push());
 });
 await check('held native Enter stops once and cannot invite on auto-repeat after Stop acknowledgement',async()=>{
  const before=await preparePending();await follow.focus();await page.keyboard.down('Enter');await page.waitForFunction(()=>!controller.snapshot().canStop);await page.keyboard.down('Enter');await page.keyboard.down('Enter');await page.keyboard.up('Enter');assert.deepEqual(await page.evaluate(before=>calls.slice(before).map(c=>c.body?.action),before),['stop']);await follow.press('Enter');assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'invite');await page.evaluate(()=>push());
 });
 await check('visible Stop uses current authority even before the expiry render tick',async()=>{
  const before=await preparePending();await follow.evaluate(n=>n.addEventListener('pointerdown',()=>{clockOffset+=30001;window.beforeExpiryRender={label:n.getAttribute('aria-label'),canStop:controller.snapshot().canStop};},{once:true}));await follow.click();assert.deepEqual(await page.evaluate(()=>beforeExpiryRender),{label:'Stop leading',canStop:false});assert.equal(await page.evaluate(()=>calls.length),before);await page.evaluate(()=>push());
 });
 await check('blur retires a held Space intent even if focus returns before release',async()=>{
  const before=await preparePending();await follow.focus();await page.keyboard.down('Space');await page.getByRole('textbox').focus();await expirePending();await follow.focus();await page.keyboard.up('Space');assert.equal(await page.evaluate(()=>calls.length),before);await follow.press('Space');assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'invite');await page.evaluate(()=>push());
 });
 await check('window blur and hidden-document lifecycle notifications cancel held Space while the button keeps focus',async()=>{
  // Controlled lifecycle notifications isolate the window/document path from
  // element blur; the gesture itself still uses native keyboard down/up.
  for(const lifecycle of ['blur','hidden']){
   const before=await preparePending();await follow.focus();await page.keyboard.down('Space');
   await page.evaluate(lifecycle=>{if(lifecycle==='blur')window.dispatchEvent(new Event('blur'));else{Object.defineProperty(document,'hidden',{configurable:true,value:true});try{document.dispatchEvent(new Event('visibilitychange'));}finally{delete document.hidden;}}},lifecycle);
   assert.equal(await follow.evaluate(n=>document.activeElement===n),true);await page.keyboard.up('Space');assert.equal(await page.evaluate(()=>calls.length),before,lifecycle);await follow.press('Space');assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'stop');await page.evaluate(()=>push());
  }
 });
 await check('Escape cancels a held Space gesture; its native Stop cannot become Invite on Space release',async()=>{
  const before=await preparePending();await follow.focus();await page.keyboard.down('Space');await page.keyboard.press('Escape');await page.waitForFunction(()=>!controller.snapshot().canStop);await page.keyboard.up('Space');assert.deepEqual(await page.evaluate(before=>calls.slice(before).map(c=>c.body?.action),before),['stop']);await follow.press('Enter');assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'invite');await page.evaluate(()=>push());
 });
 for(const gesture of ['pointer','Space'])await check(`${gesture} gesture is retired on changed admission or audience, including a return to the original authority`,async()=>{
  for(const change of [{membershipRevision:2},{bubbleId:'another-bubble'},{memberId:'replacement',participants:[{accountId:'a',memberId:'replacement',name:'Ay'},{accountId:'b',memberId:'member-b',name:'Bee'}]}]){
   const before=await preparePending();await follow.evaluate(n=>window.gestureNode=n);
   if(gesture==='pointer'){await follow.hover();await page.mouse.down();}else{await follow.focus();await page.keyboard.down('Space');}
   await page.evaluate(change=>{const original=current;push({...original,...change,snapshotRevision:++rev});push({...original,snapshotRevision:++rev});},change);
   assert.equal(await follow.evaluate(n=>n===gestureNode),true);
   if(gesture==='pointer'){const box=await follow.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.up();}else await page.keyboard.up('Space');
   assert.equal(await page.evaluate(()=>calls.length),before,JSON.stringify({gesture,change}));await follow.click();assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'stop');await page.evaluate(()=>push());
  }
 });
 await check('a fresh Invite gesture rechecks current canInvite permission at activation',async()=>{
  await page.evaluate(()=>push());const before=await page.evaluate(()=>calls.length);await follow.hover();await page.mouse.down();await page.evaluate(()=>push({canInvite:false}));await page.mouse.up();assert.equal(await page.evaluate(()=>calls.length),before);await page.evaluate(()=>push());await follow.click();assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'invite');await page.evaluate(()=>push());
 });
 await check('native touch cancellation retires the pointer gesture and the next deliberate tap still works',async()=>{
  const before=await preparePending(),box=await follow.boundingBox(),cdp=await page.context().newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:box.x+box.width/2,y:box.y+box.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await expirePending();assert.equal(await page.evaluate(()=>calls.length),before);
  const fresh=await follow.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:2,x:fresh.x+fresh.width/2,y:fresh.y+fresh.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'invite');assert.equal(await page.evaluate(()=>calls.length),before+1);await cdp.detach();await page.evaluate(()=>push());
 });
 await check('Ignore native Space, focused node retention, local suppression and durable button semantics',async()=>{const ignore=page.getByRole('button',{name:'Ignore follow invitations'});await ignore.focus();await ignore.evaluate(n=>window.savedIgnore=n);await ignore.press('Space');assert.equal(await ignore.getAttribute('aria-pressed'),'true');await page.evaluate(()=>{for(let i=0;i<20;i++)push({ignoreRequests:true})});assert.equal(await ignore.evaluate(n=>n===savedIgnore&&document.activeElement===n),true);assert.equal(await ignore.evaluate(n=>getComputedStyle(n).outlineWidth),'2px');await ignore.press('Space');assert.equal(await ignore.getAttribute('aria-pressed'),'false')});
 await check('Escape declines a focused invitation; unrelated typing and IME cannot consent',async()=>{await page.evaluate(()=>push({invitations:[invite()]}));const before=await page.evaluate(()=>calls.length);await page.getByRole('textbox').focus();await page.getByRole('textbox').dispatchEvent('keydown',{key:'Enter',isComposing:true,keyCode:229});assert.equal(await page.evaluate(()=>calls.length),before);await page.getByRole('button',{name:'Accept Bee’s follow invitation'}).focus();await page.keyboard.press('Escape');await page.locator('.proximity-invitation').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>calls.at(-1).body.action),'decline')});
 await check('expired invitation is visible, disabled and cannot be accepted',async()=>{await page.evaluate(()=>push({invitations:[invite({expiresAt:Date.now()-1})]}));assert.equal(await page.getByRole('button',{name:'Accept Bee’s follow invitation'}).getAttribute('aria-disabled'),'true');const count=await page.evaluate(()=>calls.length);await page.getByRole('button',{name:'Accept Bee’s follow invitation'}).click({force:true});assert.equal(await page.evaluate(()=>calls.length),count);assert.match(await page.locator('.proximity-invitation-title').textContent(),/expired/)});
 await check('authoritative Stop beats an aborted receipt while the native focused button stays mounted',async()=>{await page.evaluate(()=>push({following:{leaderId:'b',leaderMemberId:'member-b',leaderName:'Bee',leaseId:null,controlling:false,controllerConnected:true,leaderPresence:{x:2,z:3,lastSeen:Date.now(),moving:true}}}));const stop=page.getByRole('button',{name:'Stop following',exact:true});await stop.focus();await stop.evaluate(n=>window.savedStop=n);await page.evaluate(()=>{hold=true;fail=true});await stop.press('Enter');await page.evaluate(()=>push());assert.equal(await page.locator('.proximity-status').textContent(),'Stopped.');assert.equal(await page.getByRole('button',{name:'Follow me',exact:true}).evaluate(n=>n===savedStop&&document.activeElement===n),true);await page.evaluate(()=>{hold=false;resolvers.shift()()});await page.waitForTimeout(30);assert.deepEqual(await page.evaluate(()=>({error:controller.snapshot().error,uncertain:controller.snapshot().stopUnconfirmed,canStop:controller.snapshot().canStop,motion:controller.snapshot().motion})),{error:'',uncertain:false,canStop:false,motion:null});assert.equal(await page.locator('.proximity-status').textContent(),'Stopped.');await page.evaluate(()=>fail=false)});
 await check('current accepted followers and unsolicited relations outrank old notices without new motion or focus',async()=>{await page.getByRole('button',{name:'Follow me',exact:true}).press('Enter');assert.equal(await page.locator('.proximity-status').textContent(),'Waiting for others to accept');await page.evaluate(()=>push({followers:[{accountId:'b',memberId:'member-b',name:'Bee'}]}));assert.equal(await page.locator('.proximity-status').textContent(),'Bee is following you');assert.equal(await page.getByRole('button',{name:'Stop leading',exact:true}).evaluate(n=>n===savedStop&&document.activeElement===n),true);await page.getByRole('button',{name:'Stop leading',exact:true}).press('Space');assert.equal(await page.locator('.proximity-status').textContent(),'Stopped.');await page.getByRole('textbox').focus();await page.evaluate(()=>push({following:{leaderId:'b',leaderMemberId:'member-b',leaderName:'Bee',leaseId:null,controlling:false,controllerConnected:true,leaderPresence:{x:2,z:3,lastSeen:Date.now(),moving:true}}}));assert.equal(await page.locator('.proximity-status').textContent(),'Following Bee in another tab. No automatic movement here.');assert.equal(await page.getByRole('textbox').evaluate(n=>document.activeElement===n),true);assert.equal(await page.evaluate(()=>controller.snapshot().motion),null)});
 await check('disconnected controller reads paused and pending-only cancellation has no F hint',async()=>{await page.evaluate(()=>push({following:{leaderId:'b',leaderMemberId:'member-b',leaderName:'Bee',leaseId:null,controlling:false,controllerConnected:false,leaderPresence:{x:2,z:3,lastSeen:Date.now(),moving:false}}}));assert.equal(await page.locator('.proximity-status').textContent(),'Following Bee is paused. The controlling tab is disconnected.');assert.equal(await page.evaluate(()=>controller.snapshot().motion),null);await page.evaluate(()=>push({invitations:[invite()]}));const pending=page.getByRole('button',{name:'Stop',exact:true});assert.equal(await pending.getAttribute('title'),'Cancel pending follow invitations');assert.doesNotMatch(await pending.getAttribute('title'),/\(F\)/);assert.equal(await page.getByRole('textbox').evaluate(n=>document.activeElement===n),true)});
 await check('Stop retains readable source coral hover/pressed states, native font and keyboard focus',async()=>{
  const initial=await page.evaluate(()=>{push({invitations:[invite()]});const s=getComputedStyle(document.querySelector('[data-control=follow]'));return{background:s.backgroundColor,color:s.color,transition:s.transitionProperty}});assert(['rgb(233, 109, 81)','rgb(212, 85, 58)'].includes(initial.background),JSON.stringify(initial));assert.doesNotMatch(initial.transition,/background/);const stop=page.getByRole('button',{name:'Stop',exact:true});await stop.hover();
  const read=()=>stop.evaluate(n=>{const s=getComputedStyle(n);return{background:s.backgroundColor,color:s.color,font:s.fontFamily,outline:s.outlineWidth}});
  const contrast=s=>{const luminance=c=>{const rgb=c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};const a=luminance(s.background),b=luminance(s.color);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);};
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('[data-control=follow]')).backgroundColor===(matchMedia('(hover:hover)').matches?'rgb(212, 85, 58)':'rgb(233, 109, 81)'));const hover=await read();assert.equal(hover.background,await page.evaluate(()=>matchMedia('(hover:hover)').matches?'rgb(212, 85, 58)':'rgb(233, 109, 81)'));assert(contrast(hover)>=4.5,JSON.stringify(hover));assert.match(hover.font,/^Roboto/);
  await page.mouse.down();await page.waitForFunction(()=>getComputedStyle(document.querySelector('[data-control=follow]')).backgroundColor==='rgb(196, 74, 48)');const pressed=await read();assert.equal(pressed.background,'rgb(196, 74, 48)');assert(contrast(pressed)>=4.5,JSON.stringify(pressed));visualStates.push({hoverCapable:await page.evaluate(()=>matchMedia('(hover:hover)').matches),hover,pressed,hoverContrast:contrast(hover),pressedContrast:contrast(pressed)});await page.mouse.move(5,5);await page.mouse.up();
  await stop.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');assert.equal(await stop.evaluate(n=>document.activeElement===n),true);assert.equal((await read()).outline,'2px');
 });
 for (const viewport of [{width:1280,height:800},{width:390,height:844},{width:320,height:568},{width:844,height:390},{width:568,height:320}]) {
  const context=await browser.newContext({viewport,hasTouch:true,isMobile:viewport.width<700});const touch=await context.newPage();await touch.goto(url);await touch.waitForFunction(()=>ready);await touch.evaluate(()=>{document.querySelector('#draft').hidden=true;push({invitations:[invite()]})});
  const detail=[];
  for(const selector of ['[data-control=lock]','[data-control=follow]','[data-control=ignore]','.proximity-primary','.proximity-invitation-actions button:first-child']) {
   const control=touch.locator(selector);await control.scrollIntoViewIfNeeded();
   const geometry=await control.evaluate(n=>{const r=n.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{selector:n.getAttribute('aria-label'),rect:r.toJSON(),hit:n===hit||n.contains(hit),viewport:{width:innerWidth,height:innerHeight},documentWidth:document.documentElement.scrollWidth}});
   detail.push(geometry);assert.ok(geometry.rect.width>=48&&geometry.rect.height>=48,JSON.stringify(geometry));assert.ok(geometry.hit,JSON.stringify(geometry));assert.ok(geometry.rect.x>=0&&geometry.rect.right<=viewport.width&&geometry.rect.y>=0&&geometry.rect.bottom<=viewport.height,JSON.stringify(geometry));assert.ok(geometry.documentWidth<=viewport.width,JSON.stringify(geometry));
  }
  // The fixture retains the real dock/camera/joystick geometry. None may lose its center hit target.
  for(const selector of ['#dock button:first-child','#camera','#joystick']) {const node=touch.locator(selector);if(await node.isVisible()){const hit=await node.evaluate(n=>{const r=n.getBoundingClientRect(),target=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{hit:n===target||n.contains(target),selector:n.id||n.textContent,rect:r.toJSON(),target:target?.outerHTML.slice(0,120)}});assert.ok(hit.hit,JSON.stringify(hit));}}
  await touch.getByRole('button',{name:'Accept Bee’s follow invitation'}).tap();assert.equal(await touch.evaluate(()=>controller.snapshot().motion?.leaseId),'lease-1');await touch.getByRole('button',{name:'Stop following',exact:true}).tap();assert.equal(await touch.evaluate(()=>controller.snapshot().motion),null);await touch.evaluate(()=>push({invitations:[invite()]}));
  layouts.push({viewport,controls:detail});await touch.screenshot({path:out+`/fixture-${viewport.width}x${viewport.height}.png`});await context.close();console.log('PASS touch '+viewport.width+'x'+viewport.height);
 }
 assert.deepEqual(errors,[]);await writeFile(out+'/results.json',JSON.stringify({scope:'Local controlled protocol module fixture; actual HUD CSS and native input, not integrated game/server or provider proof',status:'pass',browser:await browser.version(),checks,layouts,visualStates,errors},null,2));
} finally {await browser?.close();await new Promise(r=>server.close(r))}
