import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Readable} from 'node:stream';
import {Store} from '../server/store.mjs';
import {createGameServer} from '../server/app.mjs';
import {bootstrapOwner} from '../server/operator-accounts.mjs';
import {createAccessGate} from '../server/access-gate.mjs';
import {createOpenSignup} from '../server/open-signup.mjs';
import {readRuntimeConfig} from '../server/runtime-config.mjs';
import {publicGuestPerson} from '../server/public-guests.mjs';
import {createArrivalState} from '../src/arrival-state.js';
import {sceneOperationGeometryConflicts} from '../server/scene-operation-geometry.mjs';
import {validateTerrainSceneDelta} from '../server/terrain.mjs';
import {proximityFixture} from './fixtures/proximity-config.mjs';
import {makePng} from '../fixtures/png-fixtures.mjs';
const password='synthetic guest transition password';
const scene={version:1,theme:'garden',bounds:{width:24,depth:22},spawn:{x:0,z:6},areas:[{id:'welcome',name:'Welcome',x:5,z:0,width:2,depth:2,action:'welcome',start:{key:'welcome'}}],objects:[{id:'chair',type:'chair',x:2,z:6,rotation:0}]};
const seeds=[{id:'universe',name:'Synthetic',rooms:['commons','studio','private'].map(id=>({id,name:id,scene:structuredClone(scene)}))}];
const env=(database,mode='open',setup=false)=>({UNIVERSE_MODE:'public',UNIVERSE_BIND_ADDRESS:'127.0.0.1',PORT:'4190',UNIVERSE_DB:database,UNIVERSE_ALLOWED_HOSTS:'preview.example.test',UNIVERSE_ALLOWED_ORIGINS:'https://preview.example.test',UNIVERSE_TLS_MODE:'external',UNIVERSE_COOKIE_SECURE:'always',UNIVERSE_REGISTRATION_MODE:mode,UNIVERSE_SETUP_ONLY:setup?'1':'0'});
function request(port,path,{method='GET',body,cookie,headers={}}={}){return new Promise((resolve,reject)=>{const bytes=body===undefined?undefined:JSON.stringify(body);const req=http.request({hostname:'127.0.0.1',port,path,method,headers:{Host:'preview.example.test',...(method==='GET'?{}:{Origin:'https://preview.example.test'}),...(cookie?{Cookie:cookie}:{}),...(bytes===undefined?{}:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(bytes)}),...headers}},res=>{const chunks=[];res.on('data',p=>chunks.push(p));res.on('end',()=>{const text=Buffer.concat(chunks).toString();let data;try{data=JSON.parse(text);}catch{}resolve({status:res.statusCode,data,text,headers:res.headers,cookie:res.headers['set-cookie']?.[0].split(';')[0]});});});req.on('error',reject);req.end(bytes);});}
async function fixture(t,{mode='open',setup=false,proximity=false}={}){const dir=await mkdtemp(join(tmpdir(),'public-guest-')),database=join(dir,'synthetic.sqlite');let time=Date.now(),app,port,owner;if(!setup){const store=new Store(database,seeds);owner=await bootstrapOwner(store,{name:'Synthetic Owner',username:'synthetic_owner',password});store.run('UPDATE rooms SET public=0 WHERE id=?','private');store.close();}const config=readRuntimeConfig(env(database,mode,setup));const start=async()=>{app=createGameServer({database,seeds,runtimeConfig:config,clock:()=>time,...(proximity?{proximityMembershipConfig:proximityFixture}:{})});port=(await app.listen(0)).port;};await start();t.after(async()=>{await app?.close();await rm(dir,{recursive:true,force:true});});return{get app(){return app;},get port(){return port;},owner,config,database,call:(path,options)=>request(port,path,options),advance:ms=>time+=ms,restart:async()=>{await app.close();app=null;await start();}};}
async function guest(f){const r=await f.call('/api/session',{method:'POST',body:{}});assert.equal(r.status,201,r.text);assert.equal(r.data.user.ephemeralGuest,true);assert.equal(r.data.user.account,false);return{...r,user:r.data.user};}
const as=(f,cookie)=>(path,method='GET',body)=>f.call(path,{method,body,cookie});
function unprivileged(f,id){for(const table of['universes','worlds','rooms'])assert.equal(f.app.store.get(`SELECT COUNT(*) n FROM ${table} WHERE owner_id=?`,id).n,0);for(const table of['members','world_members','accounts','users','sessions'])assert.equal(f.app.store.get(`SELECT COUNT(*) n FROM ${table} WHERE ${table==='users'?'id':'user_id'}=?`,id).n,0);}
const movement=(roomId,a,extra={})=>({roomId,admissionId:a.admissionId,admissionEpoch:a.admissionEpoch,admissionRevision:a.admissionRevision,x:a.x,z:a.z,y:0,grounded:true,verticalVelocity:0,moving:false,...extra});
async function owner(f){return f.call('/api/login',{method:'POST',body:{username:'synthetic_owner',password}});}

test('Public guests enter named public destinations with short opaque sessions and no durable identity or rights',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie);unprivileged(f,g.user.id);const cookie=g.headers['set-cookie'][0];for(const value of['HttpOnly','Secure','SameSite=Strict'])assert(cookie.includes(value));assert(!cookie.includes('Max-Age'));assert.equal((await f.call('/api/access')).data.publicGuests,true);assert.equal((await call('/api/setup/me')).status,401);const entered=await call('/api/rooms/studio/join','POST',{mode:'travel',entry:'welcome'});assert.equal(entered.status,200,entered.text);assert(entered.data.arrival.x>4);assert.equal(entered.data.room.role,'guest');assert.equal(entered.data.room.capabilities.canBuild,false);assert.equal((await call('/api/session')).data.currentRoomId,'studio');assert.equal((await call('/api/rooms/private/join','POST',{})).status,404);for(const table of['rooms','worlds','universes']){const condition=table==='rooms'?"id='studio'":table==='worlds'?"id='universe'":'1';f.app.store.run(`UPDATE ${table} SET public=0 WHERE ${condition}`);assert.equal((await call('/api/rooms/studio/join','POST',{})).status,404,table);f.app.store.run(`UPDATE ${table} SET public=1 WHERE ${condition}`);}unprivileged(f,g.user.id);});

test('Server denies persistent guest writes, privilege grants and private bypass',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie);assert.equal((await call('/api/rooms/commons/join','POST',{})).status,200);const denied=[['/api/me','PATCH',{name:'Persist'}],['/api/session','PATCH',{}],['/api/account','POST',{username:'guest_owner',password}],['/api/universes','POST',{name:'mine'}],['/api/worlds','POST',{}],['/api/rooms','POST',{}],['/api/rooms/commons/scene','PUT',{revision:0,scene}],['/api/rooms/commons/scene/operations','POST',{}],['/api/rooms/commons/messages','POST',{text:'Persist'}],['/api/rooms/commons/files','POST',{}],['/api/rooms/commons/assets','POST',{}],['/api/rooms/commons/star','PUT',{}],['/api/quests/preferences','PATCH',{}],['/api/quests/accept','POST',{}],['/api/quests/notices/claim','POST',{}],['/api/rooms/commons/personal-areas/test/claim','POST',{}],['/api/rooms/commons/bots','POST',{}],['/api/invitations/fake/accept','POST',{}],['/api/invites/fake/join','POST',{}],['/api/logout','DELETE',{}],['/api/future-write','POST',{}]];for(const[path,method,body]of denied){const r=await call(path,method,body);assert.equal(r.status,403,`${method} ${path}: ${r.text}`);assert.equal(r.data.code,'GUEST_ACCOUNT_REQUIRED');}const signed=await owner(f),o=as(f,signed.cookie);for(const path of[`/api/rooms/commons/members/${g.user.id}`,`/api/worlds/universe/members/${g.user.id}`])assert.equal((await o(path,'PUT',{role:'editor'})).data.code,'GUEST_ACCOUNT_REQUIRED');assert.equal((await o(`/api/dm/${g.user.id}/messages`,'POST',{text:'Persistent'})).data.code,'GUEST_ACCOUNT_REQUIRED');assert.equal((await call('/api/quests')).data.enabled,false);assert.equal(f.app.store.get('SELECT COUNT(*) n FROM quest_preferences WHERE user_id=?',g.user.id).n,0);unprivileged(f,g.user.id);});

test('Guest presence uses authoritative admission and seat validation',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie),joined=await call('/api/rooms/commons/join','POST',{}),a=joined.data.arrival;assert.equal((await call('/api/presence','POST',movement('commons',a))).status,200);assert.equal((await call('/api/presence','POST',movement('commons',a,{admissionId:'forged'}))).status,409);assert.equal((await call('/api/presence','POST',movement('commons',a,{seatId:'missing',seatHeight:1}))).status,400);});

test('Reload retains guest identity; restart loses leases and preserves ordinary accounts and destination re-entry',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie);await call('/api/rooms/studio/join','POST',{entry:'welcome'});assert.equal((await call('/api/session')).data.user.id,g.user.id);assert.equal((await call('/api/rooms/studio/join','POST',{mode:'resume'})).status,200);await f.restart();assert.equal((await call('/api/session')).status,401);assert.equal(f.app.store.user(g.user.id),undefined);const next=await guest(f),again=await as(f,next.cookie)('/api/rooms/studio/join','POST',{entry:'welcome'});assert.equal(again.status,200);assert(again.data.arrival.x>4);assert.notEqual(next.user.id,g.user.id);assert.equal(f.app.store.user(f.owner.id).account,true);assert.equal((await as(f,next.cookie)('/api/logout','POST',{})).status,200);assert.equal(f.app.store.user(next.user.id),undefined);const expired=await guest(f);f.advance(86400001);assert.equal((await as(f,expired.cookie)('/api/session')).status,401);await guest(f);assert.equal(f.app.store.user(expired.user.id),undefined);});

test('Guest signup creates separate ordinary account and only successful login retires guest presence/cookie',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie);await call('/api/rooms/studio/join','POST',{entry:'welcome'});const input={email:'guest-upgrade@example.test',password,name:'Account visitor'};assert.equal((await call('/api/signup','POST',input)).status,201);assert.equal((await call('/api/setup/me')).status,401);assert.equal((await call('/api/session')).data.user.id,g.user.id);assert.equal((await call('/api/login','POST',{...input,password:'wrong'})).status,401);assert.equal((await call('/api/session')).status,200);const signed=await call('/api/login','POST',input);assert.equal(signed.status,200,signed.text);assert.notEqual(signed.data.user.id,g.user.id);assert.equal(signed.data.user.account,true);assert.equal(f.app.store.user(g.user.id),undefined);assert.equal((await call('/api/session')).status,401);assert.equal(f.app.presence.has('studio:'+g.user.id),false);assert.equal((await as(f,signed.cookie)('/api/setup/me')).data.accountId,signed.data.user.id);assert.equal((await as(f,signed.cookie)('/api/rooms/studio/join','POST',{entry:'welcome'})).status,200);for(const table of['universes','worlds','rooms'])assert.equal(f.app.store.get(`SELECT COUNT(*) n FROM ${table} WHERE owner_id=?`,signed.data.user.id).n,0);});

test('Setup, invite-only and disabled remain closed and legacy unprovisioned profiles are still refused',async t=>{for(const mode of['disabled','invite-only']){const f=await fixture(t,{mode});assert.equal((await f.call('/api/session',{method:'POST',body:{}})).status,403);}const setup=await fixture(t,{setup:true});assert.equal((await setup.call('/api/session',{method:'POST',body:{}})).data.code,'SETUP_ONLY');const f=await fixture(t);f.app.store.run('INSERT INTO users(id,name,woka,created_at) VALUES(?,?,?,?)','legacy','Legacy','0',1);assert.throws(()=>createAccessGate({store:f.app.store,config:f.config}).assertReady(),e=>e.code==='UNPROVISIONED_PROFILES');});

test('Guest entry/read/movement/moderation/logout leave every permanent table and schema unchanged',async t=>{const f=await fixture(t),signed=await owner(f),o=as(f,signed.cookie),persistent=()=>f.app.store.all("SELECT name FROM main.sqlite_master WHERE type='table' ORDER BY name").map(({name})=>({name,rows:f.app.store.all(`SELECT * FROM "${name.replaceAll('"','""')}" ORDER BY rowid`)})),before=persistent(),g=await guest(f),call=as(f,g.cookie),entered=await call('/api/rooms/commons/join','POST',{});assert.equal(entered.status,200);for(const path of['/api/session','/api/worlds','/api/universes','/api/invitations','/api/memberships','/api/stars','/api/quests','/api/media','/api/rooms/commons','/api/rooms/commons/messages'])assert.equal((await call(path)).status,200,path);assert.equal((await call('/api/presence','POST',movement('commons',entered.data.arrival))).status,200);assert.deepEqual(persistent(),before);unprivileged(f,g.user.id);createAccessGate({store:f.app.store,config:f.config}).assertReady();assert.equal((await o('/api/rooms/commons/moderate','POST',{userId:g.user.id,action:'ban'})).status,200);assert.equal((await call('/api/rooms/commons/join','POST',{})).status,404);assert.equal(f.app.presence.has('commons:'+g.user.id),false);assert.deepEqual(persistent(),before);assert.equal((await o('/api/rooms/commons/moderate','POST',{userId:g.user.id,action:'unban'})).status,200);assert.equal((await call('/api/rooms/commons/join','POST',{})).status,200);assert.equal((await call('/api/logout','POST',{})).status,200);assert.deepEqual(persistent(),before);assert.equal(f.app.store.publicGuestModeration.size,0);});

test('Guest cap rejects before allocation and expiry releases memory',async t=>{const f=await fixture(t);for(let i=0;i<512;i++){const g=f.app.store.createPublicGuest('Synthetic cap','0');f.app.store.publicGuestSessions.set('synthetic-'+i,{token_hash:'synthetic-'+i,user_id:g.id,expires_at:Date.now()+86400000,current_room_id:null});}const before=f.app.store.get('SELECT COUNT(*) n FROM users').n,r=await f.call('/api/session',{method:'POST',body:{}});assert.equal(r.status,503);assert.equal(r.data.code,'GUEST_LIMIT_REACHED');assert.equal(f.app.store.get('SELECT COUNT(*) n FROM users').n,before);f.advance(86400001);await guest(f);assert.equal(f.app.store.publicGuestProfiles.size,1);});

test('Configured proximity admits guests without enabling devices or ownership',async t=>{const f=await fixture(t,{proximity:true}),g=await guest(f),call=as(f,g.cookie),joined=await call('/api/rooms/commons/join','POST',{});assert.equal(joined.status,200,joined.text);assert.equal((await call('/api/presence','POST',movement('commons',joined.data.arrival))).status,200);const media=await call('/api/media');assert.equal(media.data.enabled,false);assert.equal(media.data.context.canPublish,true);assert(media.data.proximityMembership.memberId);assert.deepEqual(media.data.peers,[]);assert.equal((await call('/api/proximity-controls')).data.available,true);assert.equal((await call('/api/presence','POST',movement('commons',joined.data.arrival,{followLeaseId:'forged'}))).status,409);});

test('Guest signup rejects a changed session after hashing without a partial account',async t=>{const f=await fixture(t),g=await guest(f);let finishHash,startedHash;const gate=new Promise(resolve=>finishHash=resolve),started=new Promise(resolve=>startedHash=resolve);let current=[...f.app.store.publicGuestSessions.values()].find(s=>s.user_id===g.user.id);const service=createOpenSignup({store:f.app.store,config:{registrationMode:'open',maxAccounts:10000},setup:{active:false,assertPending(){},recordAccount(){}},session:()=>current,send(){assert.fail('Race cannot succeed');},limitSignup(){},derivePassword:async()=>{startedHash();await gate;return Buffer.alloc(64);}}),req=Readable.from([Buffer.from(JSON.stringify({email:'stale@example.test',name:'Synthetic',password}))]);req.headers={'content-type':'application/json'};const pending=service.handle({req,res:{},path:'/api/signup',method:'POST',url:new URL('https://preview.example.test/api/signup')});await started;current=null;finishHash();await assert.rejects(pending,e=>e.code==='SIGNUP_SESSION_CHANGED');assert.equal(f.app.store.get('SELECT 1 FROM accounts WHERE email=?','stale@example.test'),undefined);});

test('Scene/terrain protect guest occupancy and saved private teleports remain denied',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie),joined=await call('/api/rooms/studio/join','POST',{entry:'welcome'}),a=joined.data.arrival,room=f.app.store.roomRow('studio'),before=JSON.parse(room.scene),next=structuredClone(before);next.objects.push({id:'blocked-by-guest',type:'wall',x:a.x,z:a.z,width:1,depth:1,height:2,rotation:0});const options={store:f.app.store,presence:f.app.presence,now:f.app.store.now,room,before,next,beforeImages:{},nextImages:{},userId:f.owner.id};assert(sceneOperationGeometryConflicts(options).some(c=>c.id==='blocked-by-guest'));assert.throws(()=>validateTerrainSceneDelta(options),e=>e.code==='WALL_BLOCKS_PLAYER');const saved=structuredClone(before);saved.objects.push({id:'public-door',type:'board',name:'Door',x:a.x,z:a.z+1,rotation:0,actions:[{id:'private-travel',type:'teleport',target:'private'}]});f.app.store.run('UPDATE rooms SET scene=?,revision=revision+1 WHERE id=?',JSON.stringify(saved),'studio');const result=await call('/api/rooms/studio/actions/resolve','POST',{revision:1,entityType:'item',entityId:'public-door',actionId:'private-travel'});assert.equal(result.status,404,result.text);assert.equal(result.data.code,'DESTINATION_UNAVAILABLE');});

test('Login retires guest SSE and every old cookie capability',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie),joined=await call('/api/rooms/commons/join','POST',{});let ended;const end=new Promise(resolve=>ended=resolve);await new Promise((resolve,reject)=>{const req=http.get({hostname:'127.0.0.1',port:f.port,path:'/api/events',headers:{Host:'preview.example.test',Cookie:g.cookie}},res=>{let text='';res.on('data',chunk=>{text+=chunk;if(text.includes('event: hello'))resolve();});res.on('end',ended);});req.on('error',reject);t.after(()=>req.destroy());});assert.equal((await call('/api/login','POST',{username:'synthetic_owner',password})).status,200);await Promise.race([end,new Promise((_,reject)=>setTimeout(()=>reject(Error('Old SSE did not retire')),2000).unref())]);assert.equal((await call('/api/events')).status,401);assert.equal((await call('/api/presence','POST',movement('commons',joined.data.arrival))).status,401);assert.equal(f.app.store.publicGuestProfiles.size,0);assert.equal(f.app.store.publicGuestSessions.size,0);});

test('Guest projections hide offline directory, usernames, tags and saved chat while preserving self admission',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie),signed=await owner(f),o=as(f,signed.cookie);f.app.store.run('UPDATE world_members SET tags=? WHERE user_id=?',JSON.stringify(['private-role-tag']),f.owner.id);f.app.store.run('INSERT INTO messages(id,room_id,user_id,text,created_at) VALUES(?,?,?,?,?)','synthetic-message','commons',f.owner.id,'private-saved-chat',1);const prior=JSON.parse(f.app.store.roomRow('commons').scene),next=structuredClone(prior);next.areas.push({id:'private-owner-label',name:'Owner corner',x:-6,z:0,width:2,depth:2,action:'welcome',personalArea:{mode:'static',allowedTags:[]}});f.app.store.syncPersonalAreas('commons',prior,next);f.app.store.run('UPDATE rooms SET scene=? WHERE id=?',JSON.stringify(next),'commons');f.app.store.run('UPDATE personal_areas SET owner_id=? WHERE area_id=?',f.owner.id,'private-owner-label');const entered=await call('/api/rooms/commons/join','POST',{});assert.equal(entered.status,200);assert.deepEqual(entered.data.members.map(p=>p.id),[g.user.id]);assert.deepEqual(entered.data.messages,[]);assert.equal(entered.data.presence.find(p=>p.id===g.user.id).admissionId,entered.data.arrival.admissionId);assert.equal(entered.data.room.personalAreas[0].owner.username,undefined);let stream='';await new Promise((resolve,reject)=>{const req=http.get({hostname:'127.0.0.1',port:f.port,path:'/api/events',headers:{Host:'preview.example.test',Cookie:g.cookie}},res=>res.on('data',bytes=>{stream+=bytes;if(stream.includes('event: hello'))resolve();}));req.on('error',reject);t.after(()=>req.destroy());});assert.equal((await o('/api/rooms/commons/join','POST',{})).status,200);const members=(await call('/api/users')).data.users;assert(members.some(p=>p.id===f.owner.id));for(const p of members){assert.equal(p.username,undefined);assert.equal(p.tags,undefined);assert.equal(p.role,undefined);}assert.equal((await o('/api/rooms/commons/messages','POST',{text:'new-private-saved-chat'})).status,201);assert.deepEqual((await call('/api/rooms/commons/messages')).data.messages,[]);await new Promise(resolve=>setTimeout(resolve,30));for(const secret of['synthetic_owner','private-role-tag','private-saved-chat']){assert.equal(JSON.stringify((await call('/api/rooms/commons')).data).includes(secret),false,secret);assert.equal(stream.includes(secret),false,secret);}assert((await o('/api/users')).data.users.some(p=>p.username==='synthetic_owner'&&p.tags.includes('private-role-tag')));assert((await o('/api/rooms/commons/messages')).data.messages.some(m=>m.text==='private-saved-chat'));});

test('Guest asset/document reads require exact pins and saved links, never catalogs or edit journals',async t=>{const f=await fixture(t),g=await guest(f),call=as(f,g.cookie),signed=await owner(f),o=as(f,signed.cookie);await o('/api/rooms/studio/join','POST',{});await call('/api/rooms/studio/join','POST',{entry:'welcome'});const uploaded=await o('/api/rooms/studio/assets','POST',{draft:{name:'Synthetic image',floating:false,collisionGrid:[[1]]},operationId:'synthetic-guest-render',mediaType:'image/png',pngBase64:makePng({width:32,height:32}).toString('base64')});assert.equal(uploaded.status,201,uploaded.text);const image=uploaded.data,assetId=image.definition.assetId,versionId=image.version.versionId,imagePath=`/api/rooms/studio/assets/${assetId}/versions/${versionId}/image`;assert.equal((await call(imagePath)).status,404);assert.equal((await o(imagePath)).status,200);for(const path of['/api/rooms/studio/assets',`/api/rooms/studio/assets/${assetId}`,'/api/rooms/studio/files','/api/rooms/studio/scene/operations'])assert.equal((await call(path)).data.code,'GUEST_ACCOUNT_REQUIRED');const filePath='/api/rooms/studio/files/synthetic-file',bytes=Buffer.from('Synthetic document visible only after saved link');f.app.store.run('INSERT INTO room_files(id,room_id,name,content_type,size,bytes,sha256,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)','synthetic-file','studio','document.txt','text/plain',bytes.length,bytes,'0'.repeat(64),f.owner.id,1);assert.equal((await call(filePath)).status,404);assert.equal((await o(filePath)).status,200);const room=(await o('/api/rooms/studio')).data.room,next=structuredClone(room.scene);next.objects.push({id:'public-image',type:'image',name:'Public image',x:-5,z:0,rotation:0,assetRef:{assetId,versionId}},{id:'public-document',type:'board',name:'Public document',x:-5,z:3,rotation:0,actions:[{id:'download',type:'link',url:filePath,mode:'tab'}]});const saved=await o('/api/rooms/studio/scene','PUT',{revision:room.revision,scene:next});assert.equal(saved.status,200,saved.text);assert.equal((await call(imagePath)).status,200);assert.equal((await call(filePath)).status,200);next.objects=next.objects.filter(o=>!['public-image','public-document'].includes(o.id));assert.equal((await o('/api/rooms/studio/scene','PUT',{revision:saved.data.room.revision,scene:next})).status,200);assert.equal((await call(imagePath)).status,404);assert.equal((await call(filePath)).status,404);});

test('Guest self projection is accepted by the arrival-state model without sharing peer tuples',()=>{const person={id:'self',name:'Visible name',username:'private-name',tags:['private-tag'],role:'owner',admissionId:'own-id',admissionEpoch:'epoch',admissionRevision:7,x:1,z:2},self=publicGuestPerson(person,'self'),other=publicGuestPerson(person,'another');assert.equal(self.admissionId,'own-id');assert.equal(self.admissionEpoch,'epoch');assert.equal(self.admissionRevision,7);for(const field of['username','tags','role']){assert.equal(self[field],undefined);assert.equal(other[field],undefined);}for(const field of['admissionId','admissionEpoch','admissionRevision'])assert.equal(other[field],undefined);const model=createArrivalState({accountId:'self',roomId:'commons',sourceGeneration:1});model.hello({sourceGeneration:1,arrivalEpoch:'epoch'});const ticket=model.beginJoin({roomId:'commons'});assert.equal(model.resolveJoin(ticket,{roomId:'commons',arrival:self}).kind,'adopt');assert.notEqual(model.observeSelf({sourceGeneration:1,roomId:'commons',presence:self}).kind,'refresh-required');assert.equal(model.snapshot().needsAuthority,false);});
