/** Real HTTP/SQLite + native other-site clicks, signup and room entry.
 * Public authority stays active. Only its configured Origin is loopback HTTP
 * in this isolated fixture; production config continues to require HTTPS.
 * No request interception, certificate bypass or synthetic browser headers.
 */
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {Store} from '../server/store.mjs';
import {bootstrapOwner} from '../server/operator-accounts.mjs';
import {createGameServer} from '../server/app.mjs';
import {readRuntimeConfig} from '../server/runtime-config.mjs';
import {launch} from '../scripts/browser.mjs';
const out=process.env.UNIVERSE_PUBLIC_GUEST_EVIDENCE||'evidence/public-guest-entry';await mkdir(out,{recursive:true});
const dist=resolve('dist'),folder=await mkdtemp(join(tmpdir(),'universe-shared-entry-')),database=join(folder,'synthetic.sqlite'),password='synthetic shared entry password';
const scene={version:1,theme:'garden',bounds:{width:24,depth:22},spawn:{x:0,z:6},areas:[{id:'welcome',name:'Welcome point',x:5,z:0,width:2,depth:2,action:'welcome',start:{key:'welcome'}}],objects:[{id:'chair-root',type:'chair',name:'Welcome chair',x:2,z:6,rotation:0},{id:'chair-named',type:'chair',name:'Arrival chair',x:6.4,z:0,rotation:0}]};
const seeds=[{id:'universe',name:'Synthetic Universe',rooms:['commons','studio','private'].map(id=>({id,name:id==='studio'?'Friend Studio':id==='private'?'Private Studio':'Commons',scene:structuredClone(scene)}))}];
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
async function snapshot(){return{head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),tree:execFileSync('git',['rev-parse','HEAD^{tree}'],{encoding:'utf8'}).trim(),trackedChanges:execFileSync('git',['status','--porcelain','--untracked-files=no'],{encoding:'utf8'}).trim(),diffSha256:hash(execFileSync('git',['diff','HEAD'])),guardSha256:hash(await readFile('server/runtime-config.mjs')),bundleSha256:hash(await readFile(join(dist,'main.js'))),signupSha256:hash(await readFile(join(dist,'signup.js')))};}
const sourceBefore=await snapshot(),checks=[],wire=[],errors=[];let browser,context,page,app,driver,base,driverBase,landingViewport;
const pass=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
async function freePort(){const server=http.createServer();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port;await new Promise(resolve=>server.close(resolve));return port;}
async function fresh(mobile=false){await context?.close();context=await browser.newContext({viewport:landingViewport||{width:1280,height:900},hasTouch:mobile,isMobile:mobile,reducedMotion:'reduce'});page=await context.newPage();page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));}
const readJson=async response=>{try{return await response.json();}catch{return null;}};
async function link(target,mobile=false){await page.goto(driverBase+'/?target='+encodeURIComponent(target),{waitUntil:'domcontentloaded'});const start=wire.length;const [response]=await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),mobile?page.locator('#shared').tap():page.locator('#shared').click()]);const request=wire.slice(start).find(r=>r.path===target&&r.headers['sec-fetch-dest']==='document');assert(request,'Server observed native target document');assert.equal(request.headers['sec-fetch-site'],'cross-site');assert.equal(request.headers['sec-fetch-mode'],'navigate');assert.equal(request.headers['sec-fetch-user'],'?1');assert.equal(request.headers.origin,undefined);return{response,request};}
async function signup(email,mobile=false){await page.locator('#open-signup').waitFor();if(mobile)await page.locator('#open-signup').tap();else await page.locator('#open-signup').press('Enter');await page.locator('#signup-view').waitFor();await page.locator('#signup-name').fill('Synthetic shared-link friend');await page.locator('#signup-email').fill(email);await page.locator('#signup-password').fill(password);await page.locator('#signup-confirm').fill(password);if(mobile)await page.locator('#signup-submit').tap();else await page.locator('#signup-confirm').press('Enter');}
async function ready(room){await page.waitForFunction(room=>window.__universe?.getState().ready&&window.__universe.getState().room?.id===room,room);return page.evaluate(()=>__universe.getState());}
function assertOrdinary(id){for(const table of['universes','worlds','rooms'])assert.equal(app.store.get(`SELECT COUNT(*) AS n FROM ${table} WHERE owner_id=?`,id).n,0);assert.equal(app.store.get('SELECT COUNT(*) AS n FROM world_members WHERE user_id=?',id).n,0);assert.equal(app.store.get('SELECT COUNT(*) AS n FROM members WHERE user_id=? AND granted=1',id).n,0);}
try{
 const store=new Store(database,seeds);await bootstrapOwner(store,{name:'Synthetic owner',username:'synthetic_owner',password});store.run('UPDATE rooms SET public=0 WHERE id=?','private');store.close();
 const port=await freePort();base=`http://127.0.0.1:${port}`;
 const productionConfig=readRuntimeConfig({UNIVERSE_MODE:'public',UNIVERSE_BIND_ADDRESS:'127.0.0.1',PORT:String(port),UNIVERSE_DB:database,UNIVERSE_ALLOWED_HOSTS:`127.0.0.1:${port}`,UNIVERSE_ALLOWED_ORIGINS:`https://127.0.0.1:${port}`,UNIVERSE_TLS_MODE:'external',UNIVERSE_COOKIE_SECURE:'always',UNIVERSE_REGISTRATION_MODE:'open'});
 // The sole test-fixture override enables native HTTP Origin on loopback.
 // The guard, public access gate, Secure cookies and real APIs are unmodified.
 const runtimeConfig=Object.freeze({...productionConfig,allowedOrigins:Object.freeze([base])});
 app=createGameServer({database,seeds,dist,runtimeConfig});await app.listen(port);
 const observeRequest=(req,res)=>{const row={method:req.method,path:req.url,headers:Object.fromEntries(['host','origin','referer','sec-fetch-site','sec-fetch-mode','sec-fetch-dest','sec-fetch-user'].filter(key=>req.headers[key]!==undefined).map(key=>[key,req.headers[key]])),cookiePresent:!!req.headers.cookie};wire.push(row);res.on('finish',()=>row.status=res.statusCode);};app.server.on('request',observeRequest);
 driver=http.createServer((req,res)=>{const target=new URL(req.url,'http://localhost').searchParams.get('target')||'/';const escaped=(base+target).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');res.writeHead(200,{'Content-Type':'text/html','Cache-Control':'no-store'});res.end(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><h1>A friend shared a place</h1><a id="shared" href="${escaped}">Open shared Universe</a>${req.url==='/resources'?`<iframe src="${base}/"></iframe><img src="${base}/signup.js"><script src="${base}/signup.js"></script>`:''}${req.url==='/automatic'?`<script>setTimeout(()=>location.href=${JSON.stringify(base+'/')},250)</script>`:''}<form method="post" action="${base}/api/signup"><button id="post">Cross-site form</button></form>`);});await new Promise(resolve=>driver.listen(0,'127.0.0.1',resolve));driverBase=`http://localhost:${driver.address().port}`;browser=await launch();
 async function bounds(){return page.evaluate(()=>{
  const rect=node=>{const r=node.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom};};
  const target=document.getElementById('join-button'),r=rect(target),center={x:r.x+r.width/2,y:r.y+r.height/2},hit=document.elementFromPoint(center.x,center.y);
  return{viewport:{width:innerWidth,height:innerHeight,visualWidth:visualViewport?.width,visualHeight:visualViewport?.height},button:{...r,text:target.textContent,disabled:target.disabled,fullyInViewport:r.x>=0&&r.y>=0&&r.right<=innerWidth&&r.bottom<=innerHeight&&r.y>=document.querySelector('.welcome-card').getBoundingClientRect().top&&r.bottom<=document.querySelector('.welcome-card').getBoundingClientRect().bottom,centerHit:target===hit||target.contains(hit),hit:hit?.outerHTML.slice(0,200)},activeElement:document.activeElement?.id,nameRequired:document.getElementById('display-name').required,scroll:[document.scrollingElement,document.getElementById('welcome'),document.querySelector('.welcome-card')].map(n=>({node:n.id||n.className||n.tagName,top:n.scrollTop,left:n.scrollLeft,clientHeight:n.clientHeight,scrollHeight:n.scrollHeight,rect:rect(n)})),art:rect(document.querySelector('.welcome-art')),name:rect(document.getElementById('display-name')),avatar:rect(document.querySelector('.woka-picker'))};
 });}
 for(const viewport of[{width:667,height:375},{width:320,height:568}]){
  landingViewport=viewport;await fresh(true);await link('/',true);await page.waitForFunction(()=>window.__universe&&document.getElementById('join-button').disabled===false);await page.waitForTimeout(150);const initial=await bounds();
  await writeFile(out+`/${viewport.width}x${viewport.height}-initial.json`,JSON.stringify({initial,actions:'Only the external driver link was tapped; no app-page focus, locator tap, scroll, wheel or activation before these measurements'},null,2));await page.screenshot({path:out+`/${viewport.width}x${viewport.height}-initial.png`});
  assert.equal(initial.button.fullyInViewport,true,'Primary guest entry must fit the clipped viewport');assert.equal(initial.button.centerHit,true,'Primary guest entry must be an actual hit target');assert(initial.scroll.every(n=>n.top===0&&n.left===0),'Initial landing must not rely on autofocus scrolling');assert.equal(initial.nameRequired,false);assert.equal(await page.locator('#display-name').inputValue(),'');assert.equal(await page.locator('#guest-entry-options').getAttribute('open'),null);assert.equal(await page.locator('#open-signup').getAttribute('href'),'/signup.html');
  await page.touchscreen.tap(initial.button.x+initial.button.width/2,initial.button.y+initial.button.height/2);let state=await ready('commons');assert(state.user.ephemeralGuest);assert.match(state.user.name,/^Guest /);assertOrdinary(state.user.id);pass(`${viewport.width}x${viewport.height}: unscrolled no-name guest CTA hit bounds and native default entry`);
  await fresh(true);await link('/',true);await page.waitForFunction(()=>window.__universe&&document.getElementById('join-button').disabled===false);
  const sessionsBefore=wire.filter(r=>r.method==='POST'&&r.path==='/api/session').length;await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement===document.querySelector('#guest-entry-options > summary')),true);
  for(const key of ['Enter','Space']){await page.keyboard.press(key);assert.equal(await page.locator('#guest-entry-options').getAttribute('open'),'');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement?.id),'display-name','Expanded optional choices must stay in the native Tab order');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement===document.querySelector('#guest-entry-options > summary')),true);await page.keyboard.press(key);assert.equal(await page.locator('#guest-entry-options').getAttribute('open'),null);}
  await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement?.id),'show-login');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement?.id),'open-signup');await page.keyboard.press('Shift+Tab');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement===document.querySelector('#guest-entry-options > summary')),true);await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>__universe.getState().user),null);assert.equal(wire.filter(r=>r.method==='POST'&&r.path==='/api/session').length,sessionsBefore,'Disclosure activation must not submit a guest visit');
  pass(`${viewport.width}x${viewport.height}: native Tab/Enter/Space reach optional fields and account controls without submitting`);
  await page.locator('#guest-entry-options > summary').tap();assert.equal(await page.locator('#guest-entry-options').getAttribute('open'),'');await page.locator('#display-name').fill('Synthetic optional guest');await page.locator('#woka-options button').nth(1).tap();assert.equal(await page.locator('#woka-options button').nth(1).getAttribute('aria-pressed'),'true');await page.locator('#guest-entry-options > summary').tap();assert.equal(await page.locator('#guest-entry-options').getAttribute('open'),null);pass(`${viewport.width}x${viewport.height}: optional name/avatar expand, select and collapse with native controls`);
  for(let repeat=0;repeat<2;repeat++){
   await page.locator('#show-login').tap();await page.locator('#login-form').waitFor({state:'visible'});assert.equal(await page.locator('#join-form').isVisible(),false);assert.equal(await page.locator('#login-username').getAttribute('maxlength'),'254');await page.locator('#show-login').tap();await page.locator('#join-form').waitFor({state:'visible'});assert.equal(await page.locator('#login-form').isVisible(),false);assert.equal(await page.locator('#guest-entry-options').count(),1);assert.equal(await page.locator('#display-name').inputValue(),'Synthetic optional guest');assert.equal(await page.locator('#display-name').getAttribute('required'),null);assert.equal(await page.locator('#open-signup').getAttribute('href'),'/signup.html');
  }
  await page.locator('#join-button').tap();state=await ready('commons');assert(state.user.ephemeralGuest);assert.equal(state.user.name,'Synthetic optional guest');pass(`${viewport.width}x${viewport.height}: repeated sign-in switching retains guest choices/account link and returns to native entry`);
 }
 assert.deepEqual(errors,[]);
}catch(error){process.exitCode=1;checks.push({status:'failed',error:error.stack});console.error(error);await page?.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});}
finally{
 await context?.close();await browser?.close();await new Promise(resolve=>driver?driver.close(resolve):resolve());await app?.close();const sourceAfter=await snapshot();if(JSON.stringify(sourceBefore)!==JSON.stringify(sourceAfter)){process.exitCode=1;checks.push({status:'failed',error:'Source or build changed during native test'});}
 await writeFile(out+'/results.json',JSON.stringify({checks,errors,sourceBefore,sourceAfter,wire,fixture:{base,driverBase,mode:'public',registrationMode:'open',setupOnly:false,override:'allowedOrigins=[actual loopback HTTP origin]; production readRuntimeConfig HTTPS validation untouched',cookieSecure:'always'},limits:['Synthetic SQLite and native Chromium on loopback HTTP only','Public-mode guard and all auth/access APIs real; only test fixture Origin matches loopback HTTP','No request interception, certificate warning bypass, browser trust change, hosted TLS or physical-device certification']},null,2));await rm(folder,{recursive:true,force:true});
}
