import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds} from '../src/worlds.js';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
await mkdir('evidence/quests-guidance',{recursive:true});
const app=createGameServer({seeds:seedWorlds,dist:process.env.QUEST_TEST_DIST||new URL('../dist',import.meta.url).pathname});const {port}=await app.listen(0),base=`http://127.0.0.1:${port}`,browser=await launch(),checks=[],errors=[];
const pass=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
async function until(check,label,timeout=60000){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(await check())return;await new Promise(r=>setTimeout(r,150));}assert.fail('Timed out: '+label);}
let context,page,peerContext;
try{
 context=await browser.newContext({viewport:{width:1440,height:960}});page=await context.newPage();page.setDefaultTimeout(60000);page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByPlaceholder('Your name').fill('Quest Explorer');await page.getByRole('button',{name:'Enter Universe'}).click();await page.waitForFunction(()=>window.__universe?.getState().ready);await page.locator('.quest-invitation').waitFor({state:'visible'});assert.equal(await page.locator('.quest-tracker').isVisible(),false);pass('Readiness produces only a nonblocking opt-in invitation');
 await page.locator('.quest-invitation').getByRole('button',{name:'Not now',exact:true}).click();await page.locator('.quest-invitation').waitFor({state:'hidden'});await page.reload();await page.waitForFunction(()=>window.__universe?.getState().ready);await page.waitForTimeout(1200);assert.equal(await page.locator('.quest-invitation').isVisible(),false);pass('Not now remains declined after browser reload');
 await page.locator('#quest-open').click();await page.locator('.quest-sheet').waitFor({state:'visible'});const close=page.getByRole('button',{name:'Close quests'});await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Close quests');assert.equal(await close.evaluate(e=>document.activeElement===e),true);const position=await page.evaluate(()=>window.__universe.getState().position);await page.keyboard.type('wasd');await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>window.__universe.getState().position),position);pass('Quest dialog focuses close first and does not move the avatar while typing');
 const quiet=page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Explore Quiet garden',exact:true})});await quiet.getByRole('button',{name:'Accept quest'}).click();await quiet.getByRole('button',{name:'Show the way'}).waitFor();const beforeGuide=await page.evaluate(()=>window.__universe.getState().position);await quiet.getByRole('button',{name:'Show the way'}).click();await page.waitForTimeout(400);assert.deepEqual(await page.evaluate(()=>window.__universe.getState().position),beforeGuide);assert.equal((await page.evaluate(()=>window.__universe.getPath())).length,0);pass('Show the way marks the actual target without walking or teleporting');
 await page.locator('#quest-open').click();await page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Explore Quiet garden',exact:true})}).getByRole('button',{name:'Walk there'}).click();await page.getByRole('button',{name:'Cancel walk',exact:true}).waitFor();await page.getByRole('button',{name:'Cancel walk',exact:true}).click();assert.equal((await page.evaluate(()=>window.__universe.getPath())).length,0);pass('Player can cancel a quest walk');
 await page.locator('#quest-open').click();await page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Explore Quiet garden',exact:true})}).getByRole('button',{name:'Walk there'}).click();await until(async()=>(await page.evaluate(async()=>(await(await fetch('/api/quests')).json()).stampCount))===1,'real Explore completion');await page.locator('.quest-tracker').waitFor({state:'hidden'});pass('Real collision-aware walking enters the named area and the server awards one private Explorer stamp');
 await page.locator('#quest-open').click();await page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Try building',exact:true})}).getByRole('button',{name:'Accept quest'}).click();await page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Try building',exact:true})}).getByRole('button',{name:'Open Build'}).click();await page.locator('#editor').waitFor({state:'visible'});const oldObjects=await page.evaluate(()=>window.__universe.getState().scene.objects.length);await page.locator('[data-tool="plant"]').click();await page.locator('#game').focus();await page.keyboard.press('Space');await page.waitForFunction(n=>window.__universe.getState().scene.objects.length===n+1,oldObjects);assert.equal((await page.evaluate(async()=>(await (await fetch('/api/quests')).json()).stampCount)),1);await page.locator('#editor').getByRole('button',{name:'Save room',exact:true}).click();await until(async()=>(await page.evaluate(async()=>(await(await fetch('/api/quests')).json()).stampCount))===2,'saved Build completion');assert.equal(await page.locator('.quest-payoff').isVisible(),false);pass('Unsaved object gives no reward; authorized Save grants Builder stamp while payoff stays suppressed in editor');
 await page.locator('#dock-build').click();await page.locator('.quest-payoff').waitFor({state:'visible'});await page.locator('#quest-open').click();await page.getByText('Builder · private stamp',{exact:false}).waitFor();await page.screenshot({path:'evidence/quests-desktop.png'});pass('Deferred payoff appears after editing and both private stamps remain in the log');
 await page.getByRole('button',{name:'Close quests'}).click();await page.locator('#home-camera').click();const spawnPoint=await page.evaluate(()=>{const p=window.__universe.getState().scene.spawn;return window.__universe.getScreenPoint(p.x,p.z);});await page.locator('#game').click({position:{x:spawnPoint.x,y:spawnPoint.y}});await until(async()=>page.evaluate(()=>{const s=window.__universe.getState();return Math.hypot(s.position.x-s.scene.spawn.x,s.position.z-s.scene.spawn.z)<.8;}),'walk out of the silent garden to meet a real player');
 peerContext=await browser.newContext({viewport:{width:1440,height:960}});const peer=await peerContext.newPage();peer.setDefaultTimeout(60000);peer.on('pageerror',e=>errors.push(e.message));await peer.goto(base,{waitUntil:'domcontentloaded',timeout:90000});await peer.getByPlaceholder('Your name').fill('Real Quest Partner');await peer.getByRole('button',{name:'Enter Universe'}).click();await peer.waitForFunction(()=>window.__universe?.getState().ready);
 for(const p of [page,peer]){await p.locator('#dock-media').click();await p.getByRole('button',{name:'Join audio',exact:true}).click();await p.getByRole('button',{name:'Leave audio',exact:true}).waitFor();await p.locator('#dock-media').click();}
 await until(async()=>(await page.evaluate(async()=>(await(await fetch('/api/quests')).json()).available)).some(q=>q.kind==='meet'),'real eligible proximity peer');
 await page.locator('#quest-open').click();await page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Meet someone',exact:true})}).getByRole('button',{name:'Accept quest'}).click();await page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Meet someone',exact:true})}).getByRole('button',{name:'Stop following'}).waitFor();await page.getByRole('button',{name:'Close quests'}).click();
 await page.locator('#dock-emote').click();await page.getByRole('button',{name:'👋 Wave',exact:true}).click();assert.equal(await page.evaluate(async()=>(await(await fetch('/api/quests')).json()).stampCount),2);await until(async()=>/1\/2 waves/.test(await page.locator('.quest-tracker').innerText()),'server-counted partial wave progress');await peer.locator('#dock-emote').click();await peer.getByRole('button',{name:'👋 Wave',exact:true}).click();await until(async()=>(await page.evaluate(async()=>(await(await fetch('/api/quests')).json()).stampCount))===3,'reciprocal actual player waves');pass('Two actual browser users exchange waves in a real opt-in proximity link; one wave alone does not award Meet');
 await page.locator('#quest-open').click();await page.getByText('Connection · private stamp',{exact:false}).waitFor();await page.screenshot({path:'evidence/quests-three-stamps.png'});await peerContext.close();peerContext=null;
 await page.setViewportSize({width:320,height:680});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.locator('.quest-sheet').evaluate(e=>e.scrollTop=0);await page.waitForTimeout(400);await writeFile('evidence/quests-guidance/completed-log-layout.json',JSON.stringify(await page.evaluate(()=>({width:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(n=>{const r=n.getBoundingClientRect();return r.width&&r.height&&(r.right>innerWidth+.5||r.left<-.5)&&getComputedStyle(n).display!=='none';}).map(n=>({tag:n.tagName,id:n.id,cls:typeof n.className==='string'?n.className:'',bounds:n.getBoundingClientRect().toJSON(),text:n.textContent.slice(0,80)}))})),null,2));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),320);const bounds=await close.boundingBox();assert(bounds.width>=44&&bounds.height>=44&&bounds.x>=0&&bounds.x+bounds.width<=320);await page.screenshot({path:'evidence/quests-mobile-320-200pct.png'});pass('320px viewport with 200% root text keeps reachable 44px close and no page overflow');
 await page.keyboard.press('Escape');assert.equal(await page.locator('.quest-sheet').isVisible(),false);assert.equal(await page.locator('#dock-more').evaluate(e=>document.activeElement===e),true);pass('Escape closes only quests and restores focus to visible More after a mobile resize');
 assert.deepEqual(errors,[]);pass('No browser runtime exceptions in quest flows');
}catch(error){console.error(error);checks.push({name:'quest browser failure',status:'failed',error:error.stack});await page?.screenshot({path:'evidence/quests-failure.png'}).catch(()=>{});process.exitCode=1;}
finally{await writeFile('evidence/quests-browser-checks.json',JSON.stringify({checks,errors,limitations:['Cloud Chromium, not physical iOS/Android','Meet is local reciprocal emotes in a real proximity policy link, not original-source proximity chat semantics','Independent local service, not original source-stack quest parity']},null,2));await peerContext?.close();await context?.close();await browser.close();await app.close();}
