// Actual app/server regression for the audited welcome/quest + area overlap.
// All identities and room state are disposable; no hosted service or capture.
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds} from '../src/worlds.js';
const output=process.env.QUEST_AREA_OUTPUT||'evidence/quest-area-layout';
await mkdir(output,{recursive:true});
const app=createGameServer({seeds:structuredClone(seedWorlds),dist:process.env.QUEST_AREA_DIST||new URL('../dist',import.meta.url).pathname});
const {port}=await app.listen(0),browser=await launch(),context=await browser.newContext({viewport:{width:320,height:568},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage();
page.setDefaultTimeout(20000);const checks=[],errors=[],measurements=[];
page.on('pageerror',error=>errors.push(error.message));
await page.addInitScript(()=>{window.captureAttempts=0;if(navigator.mediaDevices)for(const method of ['getUserMedia','getDisplayMedia'])Object.defineProperty(navigator.mediaDevices,method,{value:()=>{window.captureAttempts++;throw Error('Capture forbidden in layout test');}});});
async function check(name,fn){try{await fn();checks.push({name,status:'passed'});console.log('PASS',name);}catch(error){checks.push({name,status:'failed',error:error.stack});console.error('FAIL',name,error.message);process.exitCode=1;}}
const overlap=(a,b)=>a&&b?Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y)):0;
async function reachable(locator){await locator.scrollIntoViewIfNeeded();const result=await locator.evaluate(node=>{const r=node.getBoundingClientRect(),points=node.matches('button,#joystick')?[[.5,.5],[.25,.25],[.75,.25],[.25,.75],[.75,.75]]:[[.5,.5]],hits=points.map(([x,y])=>document.elementFromPoint(r.x+r.width*x,r.y+r.height*y));return {rect:r.toJSON(),hits:hits.map(hit=>hit?.id||hit?.className),ok:r.x>=0&&r.right<=innerWidth+.5&&r.y>=0&&r.bottom<=innerHeight+.5&&hits.every(hit=>node.contains(hit))};});assert(result.ok,JSON.stringify(result));}
async function geometry(stage){for(const [width,height]of[[320,568],[390,844],[667,375],[844,390],[550,375]]){await page.setViewportSize({width,height});await page.waitForTimeout(200);for(const side of ['right','left']){if(await page.locator('#app').getAttribute('data-movement-side')!==side)await page.locator('#movement-side-toggle').click();await page.waitForTimeout(120);const area=await page.locator('#area-banner').boundingBox(),card=await page.locator(stage==='welcome'?'.quest-invitation':'.quest-tracker').boundingBox();const row={stage,width,height,side,area,card,overlapPixels:overlap(area,card)};measurements.push(row);await page.screenshot({path:`${output}/${stage}-${width}x${height}-${side}.png`});await check(`${stage} ${width}x${height} ${side}: area and quest cards do not cover each other`,()=>{assert(area&&card);assert.equal(row.overlapPixels,0,JSON.stringify(row));});await check(`${stage} ${width}x${height} ${side}: world controls remain hit-testable`,async()=>{for(const selector of ['#joystick','#jump-button','#movement-side-toggle','#zoom-in','#zoom-out','#camera-follow','#dock-more'])await reachable(page.locator(selector));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);});}}}
try{
 await page.goto(`http://127.0.0.1:${port}`);await page.getByPlaceholder('Your name').fill('Context layout reviewer');await page.locator('#join-button').click();await page.waitForFunction(()=>window.__universe?.getState().ready);await page.locator('.quest-invitation').waitFor({state:'visible'});await page.locator('#area-banner').waitFor({state:'visible'});
 await geometry('welcome');
 await page.setViewportSize({width:320,height:568});await page.locator('.quest-invitation').getByRole('button',{name:'Show me the options',exact:true}).click();const quest=page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Explore The Commons',exact:true})});await quest.getByRole('button',{name:'Accept quest',exact:true}).click();await quest.getByRole('button',{name:'Show the way',exact:true}).click();await page.locator('.quest-tracker').waitFor({state:'visible'});await geometry('active');
 await check('Both area text and current objective are independently retrievable without covering each other',async()=>{
  await page.setViewportSize({width:320,height:568});const toggle=page.locator('.quest-area-toggle');assert.equal(await toggle.count(),1,'Area info expand/collapse control is available');await reachable(toggle);await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'true');await reachable(page.locator('#area-message'));assert.match(await page.locator('#area-message').innerText(),/Welcome to your Universe/);assert.equal(overlap(await page.locator('#area-banner').boundingBox(),await page.locator('.quest-tracker').boundingBox()),0);await page.screenshot({path:output+'/area-expanded-320.png'});await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'false');await reachable(page.locator('.quest-tracker .quest-next-step'));assert.match(await page.locator('.quest-tracker .quest-next-step').innerText(),/Step outside The Commons first/);
 });
 await check('Short-landscape 200% text keeps area retrieval bounded above every dock icon',async()=>{
  await page.setViewportSize({width:550,height:375});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.waitForTimeout(250);await reachable(page.locator('.quest-area-toggle'));await page.locator('.quest-area-toggle').click();await reachable(page.locator('#area-message'));await page.locator('.quest-area-toggle').click();for(const side of ['right','left']){if(await page.locator('#app').getAttribute('data-movement-side')!==side)await page.locator('#movement-side-toggle').click();for(const selector of ['#joystick','#jump-button','#movement-side-toggle','#dock button:not([hidden])']){const controls=page.locator(selector);for(let i=0;i<await controls.count();i++)if(await controls.nth(i).isVisible())await reachable(controls.nth(i));}const geometry=await page.evaluate(()=>{const clip=node=>{let r=node.getBoundingClientRect();r={x:r.x,y:r.y,width:r.width,height:r.height};for(let p=node.parentElement;p;p=p.parentElement){const css=getComputedStyle(p);if(/auto|scroll|hidden|clip/.test(css.overflow)){const a=p.getBoundingClientRect(),right=Math.min(r.x+r.width,a.right),bottom=Math.min(r.y+r.height,a.bottom);r.x=Math.max(r.x,a.x);r.y=Math.max(r.y,a.y);r.width=Math.max(0,right-r.x);r.height=Math.max(0,bottom-r.y);}}return r;};return{area:clip(document.querySelector('#area-banner')),quest:clip(document.querySelector('.quest-tracker')),dock:document.querySelector('#dock').getBoundingClientRect().toJSON()};});assert.equal(overlap(geometry.area,geometry.dock),0,JSON.stringify(geometry));assert.equal(overlap(geometry.quest,geometry.dock),0,JSON.stringify(geometry));}await page.screenshot({path:output+'/short-landscape-area-200-percent.png'});await page.evaluate(()=>document.documentElement.style.fontSize='');await page.setViewportSize({width:320,height:568});
 });
 await page.evaluate(()=>document.documentElement.style.fontSize='');await page.setViewportSize({width:320,height:568});if(await page.locator('.quest-area-toggle').getAttribute('aria-expanded')==='true')await page.locator('.quest-area-toggle').click();
 await check('Repeated quest-log open/close preserves progress, dismissal and focus',async()=>{
  for(let i=0;i<2;i++){await page.locator('.quest-tracker').getByRole('button',{name:'Quest log',exact:true}).click();await page.getByRole('button',{name:'Close quests',exact:true}).click();await page.locator('.quest-tracker').waitFor({state:'visible'});await reachable(page.locator('.quest-tracker').getByRole('button',{name:'Quest log',exact:true}));}
  assert.equal(await page.evaluate(async()=>(await(await fetch('/api/quests')).json()).stampCount),0);await page.locator('#area-banner').getByRole('button',{name:'Dismiss area message',exact:true}).click();assert.equal(await page.locator('#area-banner').isVisible(),false);await reachable(page.locator('.quest-tracker .quest-next-step'));await page.locator('.quest-tracker').getByRole('button',{name:'Quest log',exact:true}).click();await page.getByRole('button',{name:'Close quests',exact:true}).click();assert.equal(await page.locator('#area-banner').isVisible(),false);
 });
 await check('A real saved-room receipt is readable below the current objective and cannot intercept controls',async()=>{
  await page.locator('#dock-build').click();await page.getByRole('button',{name:'Terrain',exact:true}).click();await page.getByRole('button',{name:'Paint soil',exact:true}).click();await page.getByRole('button',{name:'Close terrain palette',exact:true}).click();await page.locator('#game').focus();await page.keyboard.press('Space');await page.keyboard.press('Control+s');await page.waitForFunction(()=>!__universe.getEditor().dirty);await page.locator('#dock-build').click();await page.locator('.quest-tracker').waitFor({state:'visible'});await page.locator('#toast').waitFor({state:'visible'});await page.waitForTimeout(150);assert.equal(overlap(await page.locator('#toast').boundingBox(),await page.locator('.quest-tracker').boundingBox()),0);assert.equal(await page.locator('#toast').evaluate(n=>getComputedStyle(n).pointerEvents),'none');for(const id of ['joystick','jump-button','dock-more'])await reachable(page.locator('#'+id));await page.screenshot({path:output+'/save-receipt-and-objective.png'});await page.locator('#toast').waitFor({state:'hidden'});
 });
 await check('Root 200% really enlarges quest copy and leaves actions and controls reachable',async()=>{
  const instruction=page.locator('.quest-tracker .quest-next-step'),before=await instruction.evaluate(n=>parseFloat(getComputedStyle(n).fontSize));await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.waitForTimeout(250);assert(await instruction.evaluate(n=>parseFloat(getComputedStyle(n).fontSize))>=before*1.9);await reachable(instruction);for(const selector of ['.quest-tracker [data-quest-key="tracker-walk"]','#joystick','#jump-button','#movement-side-toggle','#dock-more'])await reachable(page.locator(selector));await page.screenshot({path:output+'/quest-text-200-percent.png'});await page.evaluate(()=>document.documentElement.style.fontSize='');
 });
 await check('No browser runtime errors or media capture',async()=>{assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>window.captureAttempts),0);});
}catch(error){console.error(error);checks.push({name:'Actual game journey',status:'failed',error:error.stack});process.exitCode=1;await page.screenshot({path:output+'/failure.png'}).catch(()=>{});}
finally{await writeFile(output+'/results.json',JSON.stringify({checks,measurements,errors,scope:'Actual built application with in-memory local server and synthetic profile; Chromium SwiftShader touch/text emulation, not physical device certification'},null,2));await context.close();await browser.close();await app.close();}
