// Actual app/server regression for the audited welcome/quest + area overlap.
// All identities and room state are disposable; no hosted service or capture.
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds} from '../src/worlds.js';
const output=process.env.QUEST_AREA_OUTPUT||'evidence/quest-area-layout';
await mkdir(output,{recursive:true});
const app=createGameServer({seeds:structuredClone(seedWorlds),dist:process.env.QUEST_AREA_DIST||new URL('../dist',import.meta.url).pathname});
const {port}=await app.listen(0),browser=await launch(),context=await browser.newContext({viewport:{width:320,height:568},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage();
page.setDefaultTimeout(20000);const checks=[],errors=[],measurements=[];
page.on('pageerror',error=>errors.push(error.message));
await page.addInitScript(()=>{window.captureAttempts=0;if(navigator.mediaDevices)for(const method of ['getUserMedia','getDisplayMedia'])Object.defineProperty(navigator.mediaDevices,method,{value:()=>{window.captureAttempts++;throw Error('Capture forbidden in layout test');}});});
async function check(name,fn){try{await fn();checks.push({name,status:'passed'});console.log('PASS',name);}catch(error){checks.push({name,status:'failed',error:error.stack});console.error('FAIL',name,error.message);process.exitCode=1;}}
const painted=locator=>locator.evaluate(n=>{const r=n.getBoundingClientRect();let b={x:Math.max(0,r.x),y:Math.max(0,r.y),right:Math.min(innerWidth,r.right),bottom:Math.min(innerHeight,r.bottom)};for(let p=n.parentElement;p&&p!==document.body&&p!==document.documentElement;p=p.parentElement)if(/auto|scroll|hidden|clip/.test(getComputedStyle(p).overflow)){const a=p.getBoundingClientRect();b.x=Math.max(b.x,a.x);b.y=Math.max(b.y,a.y);b.right=Math.min(b.right,a.right);b.bottom=Math.min(b.bottom,a.bottom);}return{x:b.x,y:b.y,width:Math.max(0,b.right-b.x),height:Math.max(0,b.bottom-b.y)};});
const overlap=(a,b)=>a&&b?Math.max(0,Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.height,b.y+b.height)-Math.max(a.y,b.y)):0;
async function reachable(locator){await locator.scrollIntoViewIfNeeded();const result=await locator.evaluate(node=>{const r=node.getBoundingClientRect(),points=node.matches('button,#joystick')?[[.5,.5],[.25,.25],[.75,.25],[.25,.75],[.75,.75]]:[[.5,.5]],hits=points.map(([x,y])=>document.elementFromPoint(r.x+r.width*x,r.y+r.height*y));return {rect:r.toJSON(),hits:hits.map(hit=>hit?.id||hit?.className),ok:r.x>=0&&r.right<=innerWidth+.5&&r.y>=0&&r.bottom<=innerHeight+.5&&hits.every(hit=>node.contains(hit))};});assert(result.ok,JSON.stringify(result));}
// This regression uses only native touch scrolling/taps in the contextual
// lane. No scrollIntoView, wheel, or programmatic scroll writes can mask traps.
async function nativeContextJourneys(){
 const seeds=structuredClone(seedWorlds);
 const local=createGameServer({seeds,dist:process.env.QUEST_AREA_DIST||new URL('../dist',import.meta.url).pathname}),address=await local.listen(0);
 const cases=JSON.parse(process.env.QUEST_AREA_NATIVE_CASES||'[["root200","right"],["computed2x","left"]]');
 try{for(const [mode,side]of cases){
  const label=`native-${mode}-${side}`,ctx=await browser.newContext({viewport:{width:550,height:375},hasTouch:true,isMobile:true,reducedMotion:'reduce'}),p=await ctx.newPage(),cdp=await ctx.newCDPSession(p);p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));
  const scale=async(selector='#app')=>{if(mode==='root200')await p.evaluate(()=>document.documentElement.style.fontSize='200%');else await p.evaluate(selector=>{const nodes=[...document.querySelectorAll(selector+' *')].filter(n=>!n.dataset.textStress&&[...n.childNodes].some(t=>t.nodeType===Node.TEXT_NODE&&t.textContent.trim())),sizes=nodes.map(n=>parseFloat(getComputedStyle(n).fontSize));nodes.forEach((n,i)=>{n.style.setProperty('font-size',`${sizes[i]*2}px`,'important');n.dataset.textStress='true';});},selector);await p.waitForTimeout(120);};
  async function detail(selector,line=null){return p.locator(selector).evaluate((n,line)=>{
   const nodeRect=n.getBoundingClientRect(),lines=()=>{const range=document.createRange();range.selectNodeContents(n);return [...range.getClientRects()].filter(r=>r.width&&r.height);},r=line===null?nodeRect:lines()[line];if(!r)return{full:false,missing:true};
   let v={left:Math.max(0,r.left),top:Math.max(0,r.top),right:Math.min(innerWidth,r.right),bottom:Math.min(innerHeight,r.bottom)};
   for(let a=n.parentElement;a&&a!==document.body&&a!==document.documentElement;a=a.parentElement)if(/auto|scroll|hidden|clip/.test(getComputedStyle(a).overflow)){const b=a.getBoundingClientRect();v={left:Math.max(v.left,b.left),top:Math.max(v.top,b.top),right:Math.min(v.right,b.right),bottom:Math.min(v.bottom,b.bottom)};}
   // A font-range box is not the ink bound of the decorative ×. Keep its
   // actual target/label/hit checks; full label text still uses strict ranges.
   const decorativeClose=n.matches('.area-banner-dismiss')&&n.getAttribute('aria-label')==='Dismiss area message'&&n.textContent.trim()==='×';
   const paintFits=decorativeClose||line!==null||n.tagName!=='BUTTON'||lines().every(p=>p.left>=v.left-.5&&p.right<=v.right+.5&&p.top>=v.top-.5&&p.bottom<=v.bottom+.5);
   const visibleHeight=Math.max(0,v.bottom-v.top),visibleWidth=Math.max(0,v.right-v.left),hit=n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)),region=document.querySelector('.quest-context').getBoundingClientRect();
   return{rect:r.toJSON(),visibleHeight,visibleWidth,full:visibleHeight>=r.height-.5&&visibleWidth>=r.width-.5&&paintFits&&hit,paintFits,hit,region:region.toJSON(),scroll:document.querySelector('.quest-context').scrollTop,scrollOwners:[...n.parentElement.closest('.quest-context').querySelectorAll('*')].filter(a=>/auto|scroll/.test(getComputedStyle(a).overflowY)&&a.scrollHeight>a.clientHeight+1).map(a=>a.id||a.className)};
  },line);}
  async function swipe(delta){
   const r=await p.locator('.quest-context').boundingBox();assert(r&&r.height>0,'Context lane exists');
   const initial=await p.locator('.quest-context').evaluate(n=>n.scrollTop),x=r.x+Math.min(70,r.width/2),y=r.y+r.height/2,warm=-Math.sign(delta||1)*48;
   await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x,y}]});
   for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x,y:y+warm*i/8}]});await p.waitForTimeout(18);}
   // Once the browser recognizes a pan, finish the same native drag toward
   // the observed target; tiny gestures must never become accidental taps.
   await p.waitForTimeout(80);const moved=await p.locator('.quest-context').evaluate(n=>n.scrollTop),remaining=Math.max(-120,Math.min(120,initial+delta-moved));
   for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x,y:y+warm-remaining*i/8}]});await p.waitForTimeout(18);}
   await p.waitForTimeout(100);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(160);
  }
  async function reveal(selector,line=null){await p.locator('.quest-context').waitFor({state:'visible'});await p.locator(selector).waitFor({state:'visible'});let d=await detail(selector,line);for(let i=0;i<12&&!d.full;i++){await swipe(d.rect.y+d.rect.height/2-d.region.y-d.region.height/2||30);d=await detail(selector,line);}assert(d.full,`${selector} cannot be fully exposed by native touch: ${JSON.stringify(d)}`);if(line===null&&await p.locator(selector).evaluate(n=>n.tagName==='BUTTON'))assert(d.rect.height>=48,'Action retains its 48px target');return d;}
  async function tap(selector){const d=await reveal(selector);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:2,x:d.rect.x+d.rect.width/2,y:d.rect.y+d.rect.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
  try{await p.addInitScript(()=>{window.captureAttempts=0;for(const m of ['getUserMedia','getDisplayMedia'])if(navigator.mediaDevices)Object.defineProperty(navigator.mediaDevices,m,{value:()=>{window.captureAttempts++;throw Error('Capture forbidden in native context test');}});});await check(label+' exposes whole welcome/area/quest actions through one native scroll surface',async()=>{
   await p.goto(`http://127.0.0.1:${address.port}`);await p.getByPlaceholder('Your name').fill('Native context reviewer');await p.locator('#join-button').click();await p.waitForFunction(()=>window.__universe?.getState().ready);await p.locator('.quest-invitation').waitFor({state:'visible'});await p.evaluate(()=>document.fonts.ready);await scale();if(side==='left')await p.locator('#movement-side-toggle').tap();
   await reveal('.quest-invitation [data-quest-key="options"]');await reveal('.quest-invitation [data-quest-key="decline"]');await reveal('.quest-area-toggle');console.log('NATIVE',label,'invitation actions and area chip exposed');await p.screenshot({path:`${output}/${label}-area-chip.png`});await tap('.quest-area-toggle');
   const lineCount=await p.locator('#area-message').evaluate(n=>{const r=document.createRange();r.selectNodeContents(n);return [...r.getClientRects()].filter(r=>r.width&&r.height).length;});for(let line=0;line<lineCount;line++)await reveal('#area-message',line);await tap('.quest-area-toggle');console.log('NATIVE',label,'all area message lines read');
   await tap('.quest-invitation [data-quest-key="options"]');const card=p.locator('.quest-card').filter({has:p.getByRole('heading',{name:'Explore The Commons',exact:true})});await card.getByRole('button',{name:'Accept quest',exact:true}).click();await card.getByRole('button',{name:'Show the way',exact:true}).click();await p.locator('.quest-tracker').waitFor({state:'visible'});await scale('.quest-tracker');
   const objectiveLines=await p.locator('.quest-tracker .quest-next-step').evaluate(n=>{const r=document.createRange();r.selectNodeContents(n);return [...r.getClientRects()].filter(r=>r.width&&r.height).length;});for(let line=0;line<objectiveLines;line++)await reveal('.quest-tracker .quest-next-step',line);
   const walk=await reveal('.quest-tracker [data-quest-key="tracker-walk"]');console.log('NATIVE',label,'objective and Walk action exposed');assert.deepEqual(walk.scrollOwners,[],'No nested contextual scroll owner');await p.screenshot({path:`${output}/${label}-walk-action.png`});
   await tap('.quest-tracker [data-quest-key="tracker"]');await p.getByRole('button',{name:'Close quests',exact:true}).click();await reveal('.quest-tracker [data-quest-key="tracker"]');await reveal('.area-banner-dismiss');assert.equal(await p.locator('.area-banner-dismiss').getAttribute('aria-label'),'Dismiss area message');assert.equal(await p.locator('.area-banner-dismiss').innerText(),'×');await p.screenshot({path:`${output}/${label}-dismiss-visible.png`});await tap('.area-banner-dismiss');assert.equal(await p.locator('#area-banner').isVisible(),false);
   await tap('.quest-tracker [data-quest-key="tracker-walk"]');await p.waitForFunction(()=>__universe.getPath().length>0||/Walk into The Commons/.test(document.querySelector('.quest-tracker .quest-next-step')?.textContent||''));
   assert.equal(await p.evaluate(()=>captureAttempts),0);
  });}finally{await p.screenshot({path:`${output}/${label}-final.png`}).catch(()=>{});await cdp.detach();await ctx.close();}
 }}finally{await local.close();}
}
async function focusedAreaResize(){
 const isolated=createGameServer({seeds:structuredClone(seedWorlds),dist:process.env.QUEST_AREA_DIST||new URL('../dist',import.meta.url).pathname}),address=await isolated.listen(0);
 const ctx=await browser.newContext({viewport:{width:320,height:568},reducedMotion:'reduce'}),p=await ctx.newPage(),localErrors=[];p.on('pageerror',e=>localErrors.push(e.message));
 try{await check('Focused fine-pointer area disclosure survives desktop reparenting and return',async()=>{
  await p.goto(`http://127.0.0.1:${address.port}`);await p.getByPlaceholder('Your name').fill('Focused area reviewer');await p.locator('#join-button').click();await p.waitForFunction(()=>window.__universe?.getState().ready);await p.locator('.quest-invitation').waitFor({state:'visible'});assert(await p.evaluate(()=>matchMedia('(pointer:fine)').matches));
  for(let i=0;i<3;i++){await p.locator('.quest-area-toggle').click();const expanded=await p.locator('.quest-area-toggle').getAttribute('aria-expanded');await p.setViewportSize({width:1440,height:950});await p.waitForFunction(()=>document.querySelector('#area-banner').parentElement.id==='app');assert.equal(await p.locator('#area-banner').count(),1);assert.equal(await p.locator('.area-banner-dismiss').evaluate(n=>document.activeElement===n),true,'Focus returns to a visible area control');await p.setViewportSize({width:320,height:568});await p.waitForFunction(()=>document.querySelector('#area-banner').parentElement.className==='quest-context');assert.equal(await p.locator('#area-banner').count(),1);assert.equal(await p.locator('.quest-area-toggle').getAttribute('aria-expanded'),expanded);}
  assert.deepEqual(localErrors,[]);await p.screenshot({path:output+'/focused-area-resize.png'});
 });}finally{errors.push(...localErrors);await ctx.close();await isolated.close();}
}
async function geometry(stage){for(const [width,height]of[[320,568],[390,844],[667,375],[844,390],[550,375]]){await page.setViewportSize({width,height});await page.waitForTimeout(200);for(const side of ['right','left']){if(await page.locator('#app').getAttribute('data-movement-side')!==side)await page.locator('#movement-side-toggle').click();await page.waitForTimeout(120);const area=await page.locator('#area-banner').boundingBox(),card=await page.locator(stage==='welcome'?'.quest-invitation':'.quest-tracker').boundingBox();const row={stage,width,height,side,area,card,overlapPixels:overlap(area,card)};measurements.push(row);await page.screenshot({path:`${output}/${stage}-${width}x${height}-${side}.png`});await check(`${stage} ${width}x${height} ${side}: area and quest cards do not cover each other`,()=>{assert(area&&card);assert.equal(row.overlapPixels,0,JSON.stringify(row));});await check(`${stage} ${width}x${height} ${side}: world controls remain hit-testable`,async()=>{for(const selector of ['#joystick','#jump-button','#movement-side-toggle','#zoom-in','#zoom-out','#camera-follow','#dock-more'])await reachable(page.locator(selector));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);});}}}
try{
 await nativeContextJourneys();await focusedAreaResize();
 if(!process.env.QUEST_AREA_NATIVE_ONLY){
 await page.goto(`http://127.0.0.1:${port}`);await page.getByPlaceholder('Your name').fill('Context layout reviewer');await page.locator('#join-button').click();await page.waitForFunction(()=>window.__universe?.getState().ready);await page.locator('.quest-invitation').waitFor({state:'visible'});await page.locator('#area-banner').waitFor({state:'visible'});
 await geometry('welcome');
 await page.setViewportSize({width:320,height:568});await page.locator('.quest-invitation').getByRole('button',{name:'Show me the options',exact:true}).click();const quest=page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Explore The Commons',exact:true})});await quest.getByRole('button',{name:'Accept quest',exact:true}).click();await quest.getByRole('button',{name:'Show the way',exact:true}).click();await page.locator('.quest-tracker').waitFor({state:'visible'});await geometry('active');
 await check('Both area text and current objective are independently retrievable without covering each other',async()=>{
  await page.setViewportSize({width:320,height:568});const toggle=page.locator('.quest-area-toggle');assert.equal(await toggle.count(),1,'Area info expand/collapse control is available');await reachable(toggle);await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'true');await reachable(page.locator('#area-message'));assert.match(await page.locator('#area-message').innerText(),/Welcome to your Universe/);assert.equal(overlap(await page.locator('#area-banner').boundingBox(),await page.locator('.quest-tracker').boundingBox()),0);await page.screenshot({path:output+'/area-expanded-320.png'});await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'false');await reachable(page.locator('.quest-tracker .quest-next-step'));assert.match(await page.locator('.quest-tracker .quest-next-step').innerText(),/Step outside The Commons first/);
 });
 await check('Short-landscape 200% text keeps area retrieval bounded above every dock icon',async()=>{
  await page.setViewportSize({width:550,height:375});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.waitForTimeout(250);await reachable(page.locator('.quest-area-toggle'));await page.locator('.quest-area-toggle').click();await reachable(page.locator('#area-message'));await page.locator('.quest-area-toggle').click();for(const side of ['right','left']){if(await page.locator('#app').getAttribute('data-movement-side')!==side)await page.locator('#movement-side-toggle').click();for(const selector of ['#joystick','#jump-button','#movement-side-toggle','#dock button:not([hidden])']){const controls=page.locator(selector);for(let i=0;i<await controls.count();i++)if(await controls.nth(i).isVisible())await reachable(controls.nth(i));}const geometry=await page.evaluate(()=>{const clip=node=>{let r=node.getBoundingClientRect();r={x:r.x,y:r.y,width:r.width,height:r.height};for(let p=node.parentElement;p;p=p.parentElement){const css=getComputedStyle(p);if(/auto|scroll|hidden|clip/.test(css.overflow)){const a=p.getBoundingClientRect(),right=Math.min(r.x+r.width,a.right),bottom=Math.min(r.y+r.height,a.bottom);r.x=Math.max(r.x,a.x);r.y=Math.max(r.y,a.y);r.width=Math.max(0,right-r.x);r.height=Math.max(0,bottom-r.y);}}return r;};return{area:clip(document.querySelector('#area-banner')),quest:clip(document.querySelector('.quest-tracker')),dock:document.querySelector('#dock').getBoundingClientRect().toJSON()};});assert.equal(overlap(geometry.area,geometry.dock),0,JSON.stringify(geometry));assert.equal(overlap(geometry.quest,geometry.dock),0,JSON.stringify(geometry));}await page.screenshot({path:output+'/short-landscape-area-200-percent.png'});await page.evaluate(()=>document.documentElement.style.fontSize='');await page.setViewportSize({width:320,height:568});
 });
 await page.evaluate(()=>document.documentElement.style.fontSize='');await page.setViewportSize({width:320,height:568});if(await page.locator('.quest-area-toggle').getAttribute('aria-expanded')==='true')await page.locator('.quest-area-toggle').click();
 await check('Repeated quest-log open/close preserves progress, dismissal and focus',async()=>{
  for(let i=0;i<2;i++){await page.locator('.quest-tracker').getByRole('button',{name:'Quest log',exact:true}).click();await page.getByRole('button',{name:'Close quests',exact:true}).click();await page.locator('.quest-tracker').waitFor({state:'visible'});await reachable(page.locator('.quest-tracker').getByRole('button',{name:'Quest log',exact:true}));}
  assert.equal(await page.evaluate(async()=>(await(await fetch('/api/quests')).json()).stampCount),0);await page.locator('#area-banner').getByRole('button',{name:'Dismiss area message',exact:true}).click();assert.equal(await page.locator('#area-banner').isVisible(),false);await reachable(page.locator('.quest-tracker .quest-next-step'));await page.locator('.quest-tracker').getByRole('button',{name:'Quest log',exact:true}).click();await page.getByRole('button',{name:'Close quests',exact:true}).click();assert.equal(await page.locator('#area-banner').isVisible(),false);
 });
 await check('A real saved-room receipt is readable below the current objective and cannot intercept controls',async()=>{
  await page.locator('#dock-build').click();await page.getByRole('button',{name:'Terrain',exact:true}).click();await page.getByRole('button',{name:'Paint soil',exact:true}).click();await page.getByRole('button',{name:'Close terrain palette',exact:true}).click();await page.locator('#game').focus();await page.keyboard.press('Space');await page.keyboard.press('Control+s');await page.waitForFunction(()=>!__universe.getEditor().dirty);await page.locator('#dock-build').click();await page.locator('.quest-tracker').waitFor({state:'visible'});await page.locator('#toast').waitFor({state:'visible'});await page.waitForTimeout(150);assert.equal(overlap(await painted(page.locator('#toast')),await painted(page.locator('.quest-tracker'))),0);assert.equal(await page.locator('#toast').evaluate(n=>getComputedStyle(n).pointerEvents),'none');for(const id of ['joystick','jump-button','dock-more'])await reachable(page.locator('#'+id));await page.screenshot({path:output+'/save-receipt-and-objective.png'});await page.locator('#toast').waitFor({state:'hidden'});
 });
 await check('Root 200% really enlarges quest copy and leaves actions and controls reachable',async()=>{
  const instruction=page.locator('.quest-tracker .quest-next-step'),before=await instruction.evaluate(n=>parseFloat(getComputedStyle(n).fontSize));await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.waitForTimeout(250);assert(await instruction.evaluate(n=>parseFloat(getComputedStyle(n).fontSize))>=before*1.9);await reachable(instruction);for(const selector of ['.quest-tracker [data-quest-key="tracker-walk"]','#joystick','#jump-button','#movement-side-toggle','#dock-more'])await reachable(page.locator(selector));await page.screenshot({path:output+'/quest-text-200-percent.png'});await page.evaluate(()=>document.documentElement.style.fontSize='');
 });
 }
 await check('No browser runtime errors or media capture',async()=>{assert.deepEqual(errors,[]);if(!process.env.QUEST_AREA_NATIVE_ONLY)assert.equal(await page.evaluate(()=>window.captureAttempts),0);});
}catch(error){console.error(error);checks.push({name:'Actual game journey',status:'failed',error:error.stack});process.exitCode=1;await page.screenshot({path:output+'/failure.png'}).catch(()=>{});}
finally{await writeFile(output+'/results.json',JSON.stringify({checks,measurements,errors,decorativeIconLimit:'The aria-labelled × is checked for full target visibility, hit testing, unchanged label and glyph, and screenshot-reviewed ink. Its font-range box is not treated as an ink bound; actual text labels retain strict range checks.',scope:'Actual built application with in-memory local server and synthetic profile; Chromium SwiftShader touch/text emulation, not physical device certification'},null,2));await context.close();await browser.close();await app.close();}
