import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';

const touch=process.env.QUEST_POINTER!=='fine';
const output=touch?'evidence/quests-guidance':'evidence/quests-guidance-fine';await mkdir(output,{recursive:true});
const scene={version:1,theme:'garden',bounds:{width:20,depth:20},spawn:{x:0,z:0},objects:[],areas:[{id:'welcome-garden',name:'Welcome garden',x:0,z:0,width:6,depth:6,action:'welcome',message:''}]};
const app=createGameServer({seeds:[{id:'world',name:'Quest test world',rooms:[{id:'commons',name:'Quest test room',scene}]}],dist:process.env.QUEST_TEST_DIST||new URL('../dist',import.meta.url).pathname});
const {port}=await app.listen(0),browser=await launch(),checks=[],errors=[];
const context=await browser.newContext({viewport:{width:1440,height:960},hasTouch:touch}),page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push(error.message));
await page.addInitScript(()=>{window.captureCalls=0;if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=()=>{window.captureCalls++;throw Error('Quest test must not request media capture');};});
const pass=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
const snapshot=()=>page.evaluate(async()=>{const response=await fetch('/api/quests');if(!response.ok)throw Error('Quest state unavailable');return response.json();});
const until=async(check,label)=>{const end=Date.now()+25000;while(Date.now()<end){if(await check())return;await page.waitForTimeout(150);}assert.fail('Timed out: '+label);};
const overlaps=(a,b)=>a&&b&&a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
async function checkControls(){
 const tracker=await page.locator('.quest-tracker').boundingBox();assert.ok(tracker&&tracker.x>=0&&tracker.y>=0&&tracker.x+tracker.width<=page.viewportSize().width);
 for(const selector of ['#joystick','#jump-button','#movement-side-toggle','#dock']){const control=page.locator(selector);if(await control.isVisible())assert.equal(overlaps(tracker,await control.boundingBox()),false,`Quest card must not cover ${selector}`);}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),page.viewportSize().width);
}
try{
 await page.goto(`http://127.0.0.1:${port}`);await page.getByPlaceholder('Your name').fill('Guided explorer');await page.getByRole('button',{name:'Enter Universe'}).click();await page.waitForFunction(()=>window.__universe?.getState().ready);
 await page.keyboard.press('j');const quest=page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Explore Welcome garden',exact:true})});await quest.getByRole('button',{name:'Accept quest',exact:true}).click();await quest.getByText('Next: Step outside Welcome garden first.',{exact:true}).waitFor();
 const beforeGuide=await page.evaluate(()=>window.__universe.getStats().meshes);await quest.getByRole('button',{name:'Show the way',exact:true}).click();await page.locator('.quest-tracker .quest-next-step').getByText('Step outside Welcome garden first.',{exact:true}).waitFor();
 assert.equal((await snapshot()).stampCount,0);await page.waitForTimeout(8300);assert.equal(await page.evaluate(()=>window.__universe.getStats().meshes),beforeGuide+1);assert.equal(await page.getByRole('button',{name:'Hide marker',exact:true}).isVisible(),true);pass('Accepted-inside quest shows an outside first step and a persistent real scene marker without awarding a stamp');
 await page.screenshot({path:output+'/desktop-current-objective.png'});
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);await checkControls();await page.screenshot({path:output+'/mobile-current-objective.png'});pass(`390px ${touch?'touch':'mouse'} objective text and actions fit beside movement controls and above the dock`);
 const swap=page.locator('#movement-side-toggle');if(await swap.isVisible()){await swap.click();await checkControls();assert.equal(await page.locator('#app').getAttribute('data-movement-side'),'left');await page.screenshot({path:output+'/mobile-left-controls.png'});await swap.click();pass('Quest card mirrors away from the left-handed movement controls');}
 await page.setViewportSize({width:320,height:680});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await checkControls();const walk=page.getByRole('button',{name:'Walk outside',exact:true});await walk.scrollIntoViewIfNeeded();assert.equal(await walk.isVisible(),true);await page.screenshot({path:output+'/mobile-320-large-text.png'});pass('320px at 200% text keeps next action reachable in a scrollable card without page overflow');
 await page.getByRole('button',{name:'Quest log',exact:true}).click();await page.locator('.quest-sheet').waitFor({state:'visible'});await writeFile(output+'/large-log-layout.json',JSON.stringify(await page.evaluate(()=>({width:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(n=>{const r=n.getBoundingClientRect();return r.width&&r.height&&(r.right>innerWidth+.5||r.left<-.5)&&getComputedStyle(n).display!=='none';}).map(n=>({tag:n.tagName,id:n.id,cls:typeof n.className==='string'?n.className:'',bounds:n.getBoundingClientRect().toJSON(),text:n.textContent.slice(0,80)}))})),null,2));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),320);await page.getByRole('button',{name:'Close quests',exact:true}).click();pass('Large-text quest log remains within the 320px viewport');
 await page.evaluate(()=>document.documentElement.style.fontSize='');await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Walk outside',exact:true}).click();await until(async()=>(await snapshot()).tracked?.guidance?.phase==='enter-area','outside movement');await until(async()=>/Walk into Welcome garden/.test(await page.locator('.quest-tracker .quest-next-step').innerText()),'next step refresh');
 assert.equal((await snapshot()).stampCount,0);await page.waitForTimeout(400);assert.equal((await page.evaluate(()=>window.__universe.getPath())).length,0);assert.equal(await page.getByRole('button',{name:'Cancel walk',exact:true}).count(),0);pass('Real Walk outside ends outside with zero rewards and waits for explicit return action');
 await page.getByRole('button',{name:'Walk there',exact:true}).click();await until(async()=>(await snapshot()).stampCount===1,'real return entry');await page.locator('.quest-tracker').waitFor({state:'hidden'});assert.equal((await snapshot()).attempts[0].status,'completed');pass('Explicit return walk completes the server entry condition exactly once');
 await page.keyboard.press('j');const build=page.locator('.quest-card').filter({has:page.getByRole('heading',{name:'Try building',exact:true})});await build.getByRole('button',{name:'Accept quest',exact:true}).click();await build.getByRole('button',{name:'Open Build',exact:true}).click();await page.locator('#editor .quest-build-hint').waitFor({state:'visible'});await page.waitForTimeout(1000);assert.match(await page.locator('.quest-build-hint').innerText(),/new object.*Save room/);assert.equal(await page.locator('.quest-build-hint').evaluate(node=>{const r=node.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===node;}),true);assert.equal(await page.locator('.quest-tracker').isVisible(),false);await writeFile(output+'/build-hint-layout.json',JSON.stringify(await page.locator('.quest-build-hint').evaluate(node=>({text:node.textContent,parent:node.parentElement.className,bounds:node.getBoundingClientRect().toJSON(),css:{fontSize:getComputedStyle(node).fontSize,display:getComputedStyle(node).display,color:getComputedStyle(node).color}})),null,2));await page.screenshot({path:output+'/mobile-build-instruction.png'});pass('Build keeps its exact new-object-and-save instruction inside the editor without a floating tracker');
 await page.locator('#dock-build').click();await page.setViewportSize({width:1440,height:960});if(await page.locator('#quest-open').isVisible())await page.locator('#quest-open').click();else{await page.locator('#dock-more').click();await page.locator('#shell-more').getByRole('button',{name:'Quests',exact:true}).click();}await page.locator('.quest-sheet').waitFor({state:'visible'});await page.setViewportSize({width:320,height:680});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),320);await page.screenshot({path:output+'/resized-log.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('.quest-sheet').isVisible(),false);const returned=await page.evaluate(()=>({id:document.activeElement?.id,visible:!!document.activeElement?.getClientRects().length}));assert(returned.visible);assert((touch?['game','dock-more']:['dock-more']).includes(returned.id),JSON.stringify(returned));pass('Resizing a wide-opened log to320px/200% keeps page bounded and Escape returns focus to a visible world control');
 assert.equal(await page.evaluate(()=>window.captureCalls),0);assert.deepEqual(errors,[]);pass('No media permission requests or browser runtime errors');
}catch(error){console.error(error);checks.push({name:'Quest guidance journey',status:'failed',error:error.stack});await page.screenshot({path:output+'/failure.png'}).catch(()=>{});process.exitCode=1;}
finally{await writeFile(output+'/checks.json',JSON.stringify({checks,errors,input:touch?'touch':'fine pointer',scope:'Synthetic local accounts on actual game/server in cloud Chromium; pointer and large-text emulation, not physical iPhone validation'},null,2));await context.close();await browser.close();await app.close();}
