// GPU-free component tests. Synthetic receipt adapter only; no model service.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright-core';
import embedded from '@sparticuz/chromium';
const checks=[],errors=[];const server=createServer(async(req,res)=>{if(req.url==='/resident-test.js'){res.setHeader('Content-Type','text/javascript');return res.end(await readFile(new URL('../src/resident-test.js',import.meta.url)));}res.setHeader('Content-Type','text/html');res.end(`<!doctype html><body><main></main><script type="module">
import {createResidentTestPanel} from '/resident-test.js';
window.calls=[];window.providerCalls=0;window.sequence=0;window.context={actorId:'alice',roomId:'commons',botId:'resident',revision:4,saved:true,enabled:true,respondToPlayers:true,dirty:false,busy:false,canManage:true,available:true,limits:{maxInputChars:2000}};
window.mode='complete';window.pendingCount=0;window.stored=null;window.held=[];
const receipt=(body,status='completed')=>({operationId:body.clientOperationId,roomId:'commons',botId:'resident',revision:body.revision,status,result:status==='completed'?{status,text:'<img src=x onerror=alert(1)> fixture reply',textTrust:'untrusted-provider-output',toolResults:[{name:'pause',status:'accepted'}]}:null,duplicate:false,cancelRequested:false});
const api=async(path,options={})=>{calls.push({path,method:options.method||'GET',body:options.body?structuredClone(options.body):null});
 if(path.endsWith('/cancel')){stored={...stored,status:'pending',cancelRequested:true};return structuredClone(stored);}
 if(options.method==='POST'){
  if(!stored){providerCalls++;stored=receipt(options.body,mode==='pending'||mode==='held'?'pending':'completed');}
  if(mode==='lost'){mode='complete';throw Error('Fixture lost acknowledgement');}
  if(mode==='held')return new Promise(resolve=>held.push(resolve));
  return structuredClone(stored);
 }
 if(stored?.cancelRequested){stored={...stored,status:'cancelled',result:{status:'cancelled',text:''}};return structuredClone(stored);}
 if(mode==='pending')return structuredClone(stored);
 return structuredClone(stored);
};
window.panel=createResidentTestPanel({request:api,getContext:()=>context,uuid:()=>('fixture-'+(++sequence)),pollMs:20,pollLimitMs:100,requestTimeoutMs:120});document.querySelector('main').append(panel.element);
window.patch=data=>{Object.assign(context,data);panel.update();};window.ready=true;</script>`);});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;let browser;
try{browser=await chromium.launch({executablePath:await embedded.executablePath(),headless:true,args:['--no-sandbox','--no-zygote','--disable-gpu']});const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));const reset=async()=>{await page.goto(base);await page.waitForFunction(()=>window.ready);};
 await reset();await page.evaluate(()=>patch({available:false}));assert(await page.getByRole('button',{name:'Test saved resident',exact:true}).isDisabled());assert.match(await page.getByRole('status').textContent(),/No provider/);await page.evaluate(()=>patch({available:true,dirty:true}));assert(await page.getByRole('button',{name:'Test saved resident',exact:true}).isDisabled());await page.evaluate(()=>patch({dirty:false,saved:false,botId:null}));assert(await page.locator('[data-resident-test]').isHidden());assert.equal(await page.evaluate(()=>calls.length),0);checks.push('Unavailable, unsaved and dirty drafts cannot dispatch tests');
 await reset();await page.getByLabel('Private test message').fill('A deliberate message');await page.getByRole('button',{name:'Test saved resident',exact:true}).focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[aria-label="Private test reply"]').textContent.includes('fixture reply'));assert.equal(await page.locator('img').count(),0);assert.equal(await page.evaluate(()=>providerCalls),1);assert.match(await page.locator('.resident-test-tools').textContent(),/accepted, not an arrival guarantee/);checks.push('Native Enter creates one test and renders provider text literally with accepted-tool wording');
 await reset();await page.evaluate(()=>mode='lost');await page.getByLabel('Private test message').fill('Keep exact body');await page.getByRole('button',{name:'Test saved resident',exact:true}).click();await page.getByRole('button',{name:'Retry same test',exact:true}).waitFor();assert(await page.getByLabel('Private test message').isDisabled());await page.getByRole('button',{name:'Retry same test',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="Private test reply"]').textContent.includes('fixture reply'));const posts=await page.evaluate(()=>calls.filter(x=>x.method==='POST'));assert.equal(posts.length,2);assert.deepEqual(posts[0].body,posts[1].body);assert.equal(await page.evaluate(()=>providerCalls),1);checks.push('Lost acknowledgement exposes explicit retry with exactly the original id/body; no automatic POST retry');
 await reset();await page.evaluate(()=>mode='pending');await page.getByLabel('Private test message').fill('Cancel intentionally');await page.getByRole('button',{name:'Test saved resident',exact:true}).click();await page.getByRole('button',{name:'Cancel test',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[role="status"]').textContent.startsWith('Cancelled'));const cancellation=await page.evaluate(()=>calls.find(x=>x.path.endsWith('/cancel')));assert.deepEqual(cancellation.body,{});assert.equal(await page.evaluate(()=>calls.filter(x=>x.method==='POST'&&!x.path.endsWith('/cancel')).length),1);checks.push('Cancellation uses its own endpoint and only reports cancelled after a terminal receipt');
 await reset();await page.evaluate(()=>mode='held');await page.getByLabel('Private test message').fill('Late private reply');await page.getByRole('button',{name:'Test saved resident',exact:true}).click();await page.waitForFunction(()=>held.length===1);await page.evaluate(()=>{patch({actorId:'bob'});held.shift()({...stored,status:'completed',result:{text:'old private reply'}});});await page.waitForTimeout(40);assert.equal(await page.getByLabel('Private test reply').textContent(),'');assert.equal(await page.getByLabel('Private test message').inputValue(),'');checks.push('Account change clears private text and rejects late prior-account responses');
 await reset();await page.evaluate(()=>mode='held');await page.getByLabel('Private test message').fill('Adapter ignores abort');await page.getByRole('button',{name:'Test saved resident',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[role="status"]').textContent.includes('outcome is unknown'));assert.equal(await page.evaluate(()=>calls.length),1);assert(await page.getByRole('button',{name:'Retry same test',exact:true}).isEnabled());checks.push('Ignored abort is bounded by a request deadline with no automatic retry');
 await reset();await page.evaluate(()=>mode='pending');await page.getByLabel('Private test message').fill('Bound status reads');await page.getByRole('button',{name:'Test saved resident',exact:true}).click();await page.waitForTimeout(220);const count=await page.evaluate(()=>calls.length);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>calls.length),count);assert(count>=2&&count<=7);assert.match(await page.getByRole('status').textContent(),/Check receipt/);await page.evaluate(()=>patch({canManage:false}));assert.equal(await page.getByLabel('Private test reply').textContent(),'');assert(await page.getByRole('button',{name:'Test saved resident',exact:true}).isDisabled());checks.push('Read-only polling is bounded, and permission revocation clears the private operation');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors,limits:['Synthetic component receipts only; no server authorization or model effect claim','GPU disabled; real keyboard/click DOM interaction only']}));
}catch(error){console.error(error);checks.push({failed:error.stack});process.exitCode=1;}finally{await mkdir('evidence',{recursive:true});await writeFile('evidence/resident-test-ui.json',JSON.stringify({checks,errors},null,2));await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
