import {build} from 'esbuild';
import {launch} from '../scripts/browser.mjs';
import {source} from './bot-editor-fixture.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const output=await build({stdin:{contents:source,resolveDir:process.cwd()},bundle:true,format:'iife',write:false,outfile:'/tmp/resident-ux.js'});
const browser=await launch(),page=await browser.newPage({viewport:{width:1280,height:920}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
const pass=name=>{checks.push(name);console.log('PASS',name);};
const field=p=>page.locator(`[data-bot-field="${p}"]`);
const draft=()=>page.evaluate(()=>editor.getDraft());
const writes=()=>page.evaluate(()=>logs.requests.filter(r=>r.args.method).length);
await mkdir('evidence',{recursive:true});
try{
 await page.route('https://resident-ux.test/',r=>r.fulfill({contentType:'text/html',body:'<style>:root{--u-surface-raised:#251d32;--u-primary:#765394;--u-secondary:#3a2a48;--u-secondary-border:#735480;--u-text-soft:#fff;--u-text-muted:#c9b7d7;--u-selected:#53375e}body{margin:0;background:linear-gradient(140deg,#4c5e53,#293f41);height:100vh}</style>'}));
 await page.goto('https://resident-ux.test/');await page.addStyleTag({content:output.outputFiles.find(f=>f.path.endsWith('.css')).text});await page.addScriptTag({content:output.outputFiles.find(f=>f.path.endsWith('.js')).text});await page.evaluate(()=>document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!event.defaultPrevented)editor.handleEscape();}));
 await page.getByRole('button',{name:'Edit Moss',exact:true}).click();
 assert.equal(await page.getByTestId('bot-move-resident').isVisible(),true);assert.equal(await page.getByTestId('bot-route-world').isVisible(),true);
 assert.equal(await field('spawn.x').isVisible(),false);await page.screenshot({path:'evidence/resident-editing-simple.png'});
 const initial=await draft();await page.getByTestId('bot-move-resident').click();assert.equal(await page.getByTestId('bot-map-toolbar').isVisible(),true);
 assert.equal(await page.evaluate(()=>editor.placeMapPoint({x:2,z:1})),true);assert.deepEqual((await draft()).spawn,{x:2,z:1});assert.equal(await writes(),0);
 await page.getByTestId('bot-map-undo').click();assert.deepEqual((await draft()).spawn,initial.spawn);
 await page.evaluate(()=>editor.placeMapPoint({x:3,z:1}));await page.keyboard.press('Escape');assert.deepEqual((await draft()).spawn,initial.spawn);assert.equal(await page.getByTestId('bot-editor').isVisible(),true);assert.equal(await writes(),0);
 pass('Edit is discoverable; Move opens compact preview, Undo and Escape restore without saving');
 await page.getByTestId('bot-route-world').click();await page.evaluate(()=>editor.placeMapPoint({x:7,z:0}));await page.evaluate(()=>editor.placeMapPoint({x:7,z:2}));
 assert.equal((await draft()).behavior,'patrol');assert.deepEqual((await draft()).waypoints,[{x:7,z:0},{x:7,z:2}]);assert.ok((await draft()).radius>=Math.hypot(7,2));
 await page.getByRole('button',{name:'Select waypoint 1',exact:true}).click();await page.evaluate(()=>editor.placeMapPoint({x:6,z:1}));
 await page.getByTestId('bot-map-remove').click();assert.deepEqual((await draft()).waypoints,[{x:7,z:2}]);await page.getByTestId('bot-map-undo').click();assert.deepEqual((await draft()).waypoints,[{x:6,z:1},{x:7,z:2}]);
 await page.screenshot({path:'evidence/resident-editing-route.png'});await page.getByTestId('bot-map-done').click();assert.equal(await writes(),0);
 await page.getByTestId('bot-save').click();await page.waitForFunction(()=>!editor.isSaving());assert.equal(await writes(),1);assert.equal(await page.evaluate(()=>database.alpha[0].waypoints.length),2);
 pass('Route mode adds, moves, removes and undoes ordered points, fits radius, and persists only on explicit Save');
 const saved=await draft();await page.getByTestId('bot-move-resident').click();assert.equal(await page.evaluate(()=>editor.placeMapPoint({x:30,z:0})),false);assert.deepEqual((await draft()).spawn,saved.spawn);await page.getByTestId('bot-map-cancel').click();assert.deepEqual(await draft(),saved);
 await page.evaluate(()=>{currentRoom.scene.objects=[{id:'wall',type:'wall',x:3,z:0,width:2,depth:2}];return editor.setRoom(currentRoom)});
 await page.getByTestId('bot-move-resident').click();assert.equal(await page.evaluate(()=>editor.placeMapPoint({x:3,z:0})),false);await page.getByTestId('bot-map-cancel').click();
 pass('Blocked and outside-room positions are rejected; Cancel restores the entire placement draft');
 await field('name').fill('Unsaved name');await page.keyboard.press('Escape');assert.equal(await writes(),1);assert.equal(await page.getByTestId('bot-confirm-discard').isVisible(),true);await page.getByTestId('bot-confirm-discard').click();await page.getByTestId('bot-editor').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>database.alpha[0].name),'Moss');
 pass('Escape on a dirty saved resident asks Save/Discard/Keep editing and never silently persists');
 await page.evaluate(()=>editor.open());await page.getByRole('button',{name:'Edit Moss',exact:true}).click();await page.getByText('Room plan & exact coordinates',{exact:true}).click();
 const before=(await draft()).spawn,home=page.locator('[data-plan-handle="spawn"]');await home.scrollIntoViewIfNeeded();const box=await home.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+20,box.y+box.height/2-20);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual((await draft()).spawn,before);
 pass('Escape cancels a room-plan drag; releasing afterward does not place a point');
 await page.setViewportSize({width:390,height:844});await page.getByTestId('bot-route-world').click();const bounds=await page.locator('.resident-panel').boundingBox();assert.ok(bounds.height<844*.44);assert.ok(bounds.width<=390);assert.equal(await page.getByTestId('bot-map-done').isVisible(),true);await page.screenshot({path:'evidence/resident-editing-mobile.png'});await page.getByTestId('bot-map-cancel').click();
 pass('Mobile placement leaves most of the world uncovered with Done and Cancel visible');
 await page.evaluate(()=>setup());await page.getByRole('button',{name:'Edit Moss',exact:true}).click();await field('name').fill('Ambiguous saved name');await page.evaluate(()=>{uncertainNext=true;});await page.getByTestId('bot-save').click();await page.waitForFunction(()=>!editor.isSaving());await field('name').fill('Moss');assert.equal(await page.getByTestId('bot-save').isEnabled(),true);await page.getByTestId('bot-save').click();await page.waitForFunction(()=>!editor.isSaving());assert.equal(await page.evaluate(()=>database.alpha[0].name),'Moss');assert.equal(await page.evaluate(()=>editor.isDirty()),false);
 pass('An ambiguous saved operation remains retryable even when the visible draft is changed back to its baseline');
 assert.deepEqual(errors,[]);
}finally{await writeFile('evidence/resident-editing-ux.json',JSON.stringify({checks,errors,scope:'Synthetic DOM/protocol fixture; native pointer integration checked separately'},null,2));await page.close();await browser.close();}
