// Real game UI + file-backed service, with an explicitly synthetic loopback provider.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds,emptyScene} from '../src/worlds.js';
const out='evidence/resident-turn-full';await mkdir(out,{recursive:true});const dir=await mkdtemp(join(tmpdir(),'resident-ui-')),calls=[],checks=[],errors=[],posts=[];
const provider=createServer(async(req,res)=>{let raw='';for await(const part of req)raw+=part;const body=JSON.parse(raw);calls.push(body);res.setHeader('Content-Type','application/json');const used=body.messages.some(m=>m.role==='tool');res.end(JSON.stringify({choices:[{index:0,message:!used&&body.tools?.length?{role:'assistant',content:null,tool_calls:[{id:'pause-fixture',type:'function',function:{name:'pause',arguments:'{}'}}]}:{role:'assistant',content:'Synthetic private protocol reply'},finish_reason:!used&&body.tools?.length?'tool_calls':'stop'}],usage:{prompt_tokens:12,completion_tokens:4,total_tokens:16}}));});
await new Promise(resolve=>provider.listen(0,'127.0.0.1',resolve));const seeds=structuredClone(seedWorlds);seeds[0].rooms[0].scene={...emptyScene(),bounds:{width:20,depth:20},spawn:{x:0,z:4},objects:[],areas:[]};
const app=createGameServer({database:join(dir,'host.sqlite'),seeds,dist:new URL('../dist',import.meta.url).pathname,residentTurnOptions:{initializeJournal:true,provider:{endpoint:`http://127.0.0.1:${provider.address().port}/v1/chat/completions`,model:'synthetic-fixture'},toolMask:{pause:true,resume:false,return:false}}}),address=await app.listen(0),base=`http://127.0.0.1:${address.port}`,browser=await launch(),page=await browser.newPage({viewport:{width:1360,height:900}});page.setDefaultTimeout(60000);page.on('pageerror',e=>errors.push(e.message));let loseResponse=false;
await page.route('**/api/rooms/*/bots/*/turns',async route=>{if(route.request().method()==='POST'){posts.push(route.request().postDataJSON());if(loseResponse){loseResponse=false;await route.fetch();await route.abort();return;}}await route.continue();});
// Hold the first Create acknowledgement after its real SSE announcement. This
// deterministically exercises the CI ordering where Test does not exist yet.
let holdCreate=true,releaseCreateResponse=null,markCreateHeld;
const createHeld=new Promise(resolve=>{markCreateHeld=resolve;});
async function waitForHeldCreate(){let timer;try{await Promise.race([createHeld,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Create acknowledgement was not held within60 seconds')),60000);})]);}finally{clearTimeout(timer);}}
await page.route('**/api/rooms/*/bots',async route=>{
 if(route.request().method()!=='POST'||!holdCreate)return route.continue();
 holdCreate=false;const response=await route.fetch();
 await new Promise(resolve=>{releaseCreateResponse=resolve;markCreateHeld();});
 await route.fulfill({response});
});
const field=name=>page.locator(`[data-bot-field="${name}"]`),button=name=>page.getByRole('button',{name,exact:true});
async function ready(){await page.waitForFunction(()=>window.__universe?.getState().ready);}
async function waitForTestReady({saved=false}={}) {
 // SSE can announce the resident before the Save response attaches its controls.
 // Wait for the actual visible/enabled button; absence is not readiness or an error.
 await button('Test saved resident').waitFor({state:'visible'});
 await page.waitForFunction(requireSaved=>{
  const control=document.querySelector('[data-resident-test] button');
  const status=document.querySelector('.resident-save-status');
  return !!control && !control.disabled && control.getClientRects().length>0 &&
   (!requireSaved || !!status?.textContent.includes('Resident saved'));
 },saved);
}
try{
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByPlaceholder('Your name').fill('Private test owner');await page.locator('#join-button').click();await ready();await page.locator('#manage-bots').click();await page.getByTestId('bot-create').click();await field('name').fill('Protocol fixture resident');assert.equal(await page.locator('[data-resident-test]:visible').count(),0);await button('Close residents').click();await page.getByTestId('bot-editor').waitFor({state:'hidden'});assert.equal(app.store.get('SELECT COUNT(*) n FROM room_bots').n,0);assert.equal(calls.length,0);checks.push('New draft and Close never create a resident or call the provider');
 await page.locator('#manage-bots').click();await field('name').waitFor({state:'visible'});assert.equal(await field('name').inputValue(),'Protocol fixture resident','Reopening restores the unsaved draft without another Create');await field('modelPermissions.pause').check();await page.getByTestId('bot-save').click();await page.waitForFunction(()=>__universe.getState().bots.some(b=>b.name==='Protocol fixture resident'));const id=await page.evaluate(()=>__universe.getState().bots.find(b=>b.name==='Protocol fixture resident').id);await waitForHeldCreate();assert.equal(await button('Test saved resident').count(),0,'SSE precedes attachment of saved controls');let readiness='waiting',readinessError;const readyControl=waitForTestReady().then(()=>{readiness='ready';},error=>{readiness='rejected';readinessError=error;});await page.waitForTimeout(75);assert.equal(readiness,'waiting','Absent controls must never count as ready');releaseCreateResponse();await readyControl;if(readinessError)throw readinessError;assert.equal(readiness,'ready');await page.getByLabel('Private test message').fill('Run the private protocol fixture');await button('Test saved resident').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[aria-label="Private test reply"]')?.textContent==='Synthetic private protocol reply');assert.match(await page.locator('.resident-test-tools').textContent(),/accepted/);assert.equal(calls.length,2);assert.equal(app.store.get('SELECT COUNT(*) n FROM messages').n,0);await page.waitForFunction(id=>__universe.getState().bots.some(b=>b.id===id&&b.status==='paused'),id);await page.screenshot({path:out+'/completed-private-test.png'});checks.push('Actual saved permission, keyboard Test, real HTTP tool command and private reply work without room-chat output');
 await button('New test').click();await page.getByLabel('Private test message').fill('Retain exact retry identity');loseResponse=true;await button('Test saved resident').click();await button('Retry same test').waitFor();for(let i=0;i<200&&app.store.get("SELECT COUNT(*) n FROM resident_turn_journal_v1 WHERE state='terminal'").n<2;i++)await new Promise(r=>setTimeout(r,10));assert.equal(app.store.get("SELECT COUNT(*) n FROM resident_turn_journal_v1 WHERE state='terminal'").n,2);const before=calls.length;await button('Retry same test').click();await page.waitForFunction(()=>document.querySelector('[aria-label="Private test reply"]')?.textContent==='Synthetic private protocol reply');assert.equal(calls.length,before);assert.equal(calls.length,4);assert.deepEqual(posts.at(-1),posts.at(-2));checks.push('Lost POST acknowledgement retries the exact operation and returns its durable receipt without new provider calls');
 await button('Close residents').click();await page.reload({waitUntil:'domcontentloaded'});await ready();await page.locator('#manage-bots').click();await page.locator(`[data-bot-id="${id}"]`).click();assert(await field('modelPermissions.pause').isChecked());assert.equal(await page.getByLabel('Private test message').inputValue(),'');assert.equal(await page.getByLabel('Private test reply').textContent(),'');assert.equal(calls.length,4);await page.getByLabel('Private test message').fill('Still typing');await page.getByLabel('Private test message').evaluate(n=>n.setSelectionRange(5,5));const permissions=page.waitForResponse(r=>r.url().endsWith('/bot-permissions'));const changedRoom=await page.request.patch(base+'/api/rooms/commons',{data:{description:'External room update fixture'}});assert.equal(changedRoom.status(),200);await permissions;await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Private test message'&&document.activeElement.selectionStart===5);checks.push('A real catalog/permission refresh preserves private test input focus and cursor');await field('name').fill('Changed saved configuration');assert(await button('Test saved resident').isDisabled());assert.equal(calls.length,4);checks.push('Reload keeps saved permissions, clears private text, and unsaved edits block new tests');await page.getByTestId('bot-save').click();await waitForTestReady({saved:true});const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true});await page.setViewportSize({width:320,height:700});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.getByLabel('Private test message').fill('Narrow touch fixture');await button('Test saved resident').scrollIntoViewIfNeeded();const target=await button('Test saved resident').boundingBox(),panel=await page.locator('.resident-panel').boundingBox();assert(target.height>=44);assert(target.x>=panel.x&&target.x+target.width<=panel.x+panel.width+1);assert(target.y>=0&&target.y+target.height<=700);assert.equal(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.closest('button')?.textContent,{x:target.x+target.width/2,y:target.y+target.height/2}),'Test saved resident');assert(await button('Test saved resident').isEnabled());await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:target.x+target.width/2,y:target.y+target.height/2,radiusX:2,radiusY:2,force:1,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>document.querySelector('[aria-label="Private test reply"]')?.textContent==='Synthetic private protocol reply');await page.screenshot({path:out+'/narrow-touch-test.png'});assert.equal(calls.length,6);checks.push('At320px and200% root text, Test remains44px and native touch completes the private protocol');assert.deepEqual(errors,[]);console.log(JSON.stringify({checks,errors,calls:calls.length}));
}catch(error){console.error(error);checks.push({failed:error.stack});await page.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}
finally{releaseCreateResponse?.();await writeFile(out+'/results.json',JSON.stringify({bundleSha256:createHash('sha256').update(await readFile('dist/main.js')).digest('hex'),checks,errors,limits:['Local file-backed service and synthetic loopback protocol only','No real AI provider, external MCP, credential or deployment test','Actual Chromium software-WebGL keyboard/click UI; no physical-device claim']},null,2));await browser.close();await app.close();provider.closeAllConnections();await new Promise(resolve=>provider.close(resolve));await rm(dir,{recursive:true,force:true});}
