// Actual world movement and UI policy; device capture is explicitly prohibited.
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds,emptyScene} from '../src/worlds.js';
const out='evidence/silent-full';await mkdir(out,{recursive:true});
const seeds=structuredClone(seedWorlds);seeds[0].rooms[0].scene={...emptyScene(),bounds:{width:16,depth:16},spawn:{x:0,z:5},objects:[],areas:[{id:'meeting-fixture',name:'Meeting first',x:2,z:0,width:4,depth:4,action:'meeting'},{id:'silent-fixture',name:'Silent fixture',x:2,z:0,width:4,depth:4,action:'silent',message:'Old incorrect see and hear copy'}]};
const app=createGameServer({seeds,dist:new URL('../dist',import.meta.url).pathname}),address=await app.listen(0),base=`http://127.0.0.1:${address.port}`,browser=await launch(),page=await browser.newPage({viewport:{width:1200,height:850}});page.setDefaultTimeout(60000);
const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.captureAttempts=0;for(const name of ['getUserMedia','getDisplayMedia'])if(navigator.mediaDevices?.[name])Object.defineProperty(navigator.mediaDevices,name,{configurable:true,value:()=>{captureAttempts++;throw Error('Capture prohibited in Silent world test');}});});
async function move(x,z){await page.waitForFunction(()=>{const c=window.__universe.getCamera(),p=window.__universe.getState().position;return Math.hypot(c.target.x-p.x,c.target.z-p.z)<.08;});const p=await page.evaluate(p=>window.__universe.getScreenPoint(p.x,p.z),{x,z});assert(p?.visible);assert.equal(await page.evaluate(p=>document.elementFromPoint(p.x,p.y)?.id,p),'game');await page.mouse.click(p.x,p.y);await page.waitForFunction(p=>{const q=window.__universe.getState().position;return Math.hypot(p.x-q.x,p.z-q.z)<.35;},{x,z});}
try{await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByPlaceholder('Your name').fill('Silent world fixture');await page.locator('#join-button').click();await page.waitForFunction(()=>window.__universe?.getState().ready);await move(2,0);await page.waitForFunction(()=>document.querySelector('#area-name')?.textContent==='Silent fixture · No calls');assert.match(await page.locator('#area-message').textContent(),/No calls here.*microphone, camera and screen sharing are off.*incoming calls are blocked/);assert.doesNotMatch(await page.locator('#area-message').textContent(),/Old incorrect/);assert.equal((await(await page.request.get(base+'/api/media')).json()).context.kind,'silent');checks.push('Native click-to-walk enters overlap; Silent wins both actual banner and server policy');
await page.locator('#dock-media').click();await page.locator('.media-context-detail').getByText('No calls here.',{exact:false}).waitFor().catch(async()=>{await page.waitForFunction(()=>document.querySelector('.media-context-detail')?.textContent.startsWith('No calls here.'));});assert(await page.locator('.media-join').isDisabled());for(const kind of ['microphone','camera','screen'])assert(await page.locator(`[data-media="${kind}"]`).isDisabled());await page.screenshot({path:out+'/inside-silent.png'});checks.push('Real Connect controls are disabled inside Silent and old custom copy cannot replace the policy');
await page.locator('#dock-media').click();await move(0,5);await page.waitForFunction(()=>document.querySelector('#area-banner').hidden);await page.locator('#dock-media').click();await page.waitForFunction(()=>!document.querySelector('.media-join')?.disabled);assert.equal(await page.locator('.media-join').textContent(),'Join audio');assert.doesNotMatch(await page.locator('.media-context-detail').textContent(),/No calls here/);assert.equal(await page.evaluate(()=>captureAttempts),0);checks.push('Walking out restores Join availability with no automatic capture or implicit join');assert.deepEqual(errors,[]);await page.screenshot({path:out+'/after-exit.png'});console.log(JSON.stringify({checks,errors}));}
catch(error){console.error(error);checks.push({failed:error.stack});await page.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}finally{await writeFile(out+'/results.json',JSON.stringify({bundleSha256:createHash('sha256').update(await readFile('dist/main.js')).digest('hex'),checks,errors,limits:['Actual 3D world/native pointer UI; generated local fixture area only','Capture prohibited; no physical devices, peer packets, SFU/TURN or external providers']},null,2));await browser.close();await app.close();}
