/** Native bundled-game terrain authoring. Mutations use actual pointer/keyboard
 * gestures except the explicitly labeled concurrent-save fixture. */
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds,canStand} from '../src/worlds.js';
import {launch} from '../scripts/browser.mjs';
const seeds=structuredClone(seedWorlds);const room=seeds[0].rooms[0];room.scene.objects=[{id:'terrain-table',type:'table',name:'Garden table',x:-5,z:-2,rotation:0},{id:'terrain-bench',type:'bench',name:'Garden bench',x:-5,z:-4,rotation:0}];room.scene.areas=[];
const app=createGameServer({database:':memory:',seeds,dist:new URL('../dist',import.meta.url).pathname}),{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;
const browser=await launch(),contexts=[],checks=[],errors=[];let alice,bob,phase='startup';const out='evidence/terrain-full';await mkdir(out,{recursive:true});
const state=p=>p.evaluate(()=>__universe.getState()),editor=p=>p.evaluate(()=>__universe.getEditor());
const scene=p=>p.evaluate(()=>__universe.getState().scene);
async function enter(name,options={}){const ctx=await browser.newContext({viewport:{width:1440,height:960},...options});contexts.push(ctx);const p=await ctx.newPage();p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));await p.bringToFront();await p.goto(base,{waitUntil:'domcontentloaded'});if(!options.storageState){await p.locator('#display-name').fill(name);await p.locator('#join-button').click();}await p.waitForFunction(()=>window.__universe?.getState().ready,null,{timeout:90000});return p;}
async function projected(p,x,z,y=0){await p.waitForFunction(()=>{const f=__universe.getCamera().framing;return f.status==='manual'||!f.targetOffset||Math.hypot(f.offset.x-f.targetOffset.x,f.offset.y-f.targetOffset.y)<1;});const q=await p.evaluate(({x,z,y})=>__universe.getScreenPoint(x,z,y),{x,z,y});assert(q.visible,'World point is visible: '+JSON.stringify({x,z,q}));assert.equal(await p.evaluate(q=>document.elementFromPoint(q.x,q.y)?.id,q),'game','Actual world gesture must target unobscured canvas');return q;}
async function build(p){await p.bringToFront();if(await p.locator('#editor').isHidden())await p.locator('#dock-build').click();}
async function terrain(p,material){await build(p);if(await p.getByRole('region',{name:'Terrain tools',exact:true}).isHidden())await p.getByRole('button',{name:'Terrain',exact:true}).click();if(material){const choice=p.getByRole('button',{name:'Paint '+material,exact:true});await choice.click();assert.equal(await choice.getAttribute('aria-pressed'),'true','The native material selection is active');}}
async function drag(p,from,to,{cancel=false}={}){const a=await projected(p,...from),b=await projected(p,...to);const before=await scene(p);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:8});assert.deepEqual(await scene(p),before,'Live drag is preview only');const preview=(await editor(p)).preview;assert(preview?.valid,preview?.reason);if(cancel)await p.keyboard.press('Escape');await p.mouse.up();return{before,preview};}
async function save(p){await p.getByRole('button',{name:'Save room',exact:true}).click();await p.waitForFunction(()=>!__universe.getEditor().saving);assert.equal((await editor(p)).dirty,false,await p.locator('.builder-recovery').textContent());return scene(p);}
async function closeBuild(p){if(await p.locator('#editor').isVisible()){await p.getByRole('button',{name:'Close editor',exact:true}).click();await p.waitForFunction(()=>history.state?.surface!=='build');}}
async function walk(p,x,z){await p.bringToFront();const q=await projected(p,x,z);await p.mouse.click(q.x,q.y);await p.waitForFunction(({x,z})=>{const s=__universe.getState();return Math.hypot(s.position.x-x,s.position.z-z)<.35&&!__universe.getPath().length;},{x,z},{timeout:30000});}
async function pass(name,fn){phase=name;await fn();checks.push({name,status:'passed'});console.log('PASS',name);}
try{
 alice=await enter('Garden maker');bob=await enter('Garden visitor');assert.notEqual((await state(alice)).user.id,(await state(bob)).user.id);
 await pass('Native rectangle has exact snapped preview and one undo/redo transaction',async()=>{
  await terrain(alice,'stone');const {before,preview}=await drag(alice,[-5.2,4.2],[-1.2,5.2]);assert.equal(preview.width,5);assert.equal(preview.depth,2);assert.equal((await scene(alice)).terrain.cells.length,10);const painted=await scene(alice);await alice.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual(await scene(alice),before);await alice.getByRole('button',{name:'Redo',exact:true}).click();assert.deepEqual(await scene(alice),painted);await save(alice);await bob.waitForFunction(()=>__universe.getState().scene.terrain?.cells.length===10);
 });
 await pass('Occupied water save is rejected atomically, retains the draft, and succeeds after the visitor moves',async()=>{
  await walk(bob,4.5,3.5);await terrain(alice,'water');await drag(alice,[3.2,2.2],[5.2,4.2]);const draft=await scene(alice);assert.equal(draft.terrain.cells.filter(c=>c[2]==='water').length,9);await alice.getByRole('button',{name:'Save room',exact:true}).click();await alice.waitForFunction(()=>!__universe.getEditor().saving);assert.equal((await editor(alice)).dirty,true);assert.deepEqual(await scene(alice),draft);assert.equal((await scene(bob)).terrain.cells.length,10);await alice.locator('.builder-recovery').waitFor({state:'visible'});assert.match(await alice.locator('.builder-recovery').textContent(),/players standing here/);assert.equal(await alice.getByRole('button',{name:'Load server version',exact:true}).isVisible(),false);await walk(bob,7.5,3.5);await alice.bringToFront();await save(alice);await bob.waitForFunction(()=>__universe.getState().scene.terrain?.cells.length===19);
 });
 await pass('Native fast walk stops at the pond and click path walks around its shared geometry',async()=>{
  await bob.bringToFront();await bob.locator('#game').focus();await bob.keyboard.press('Home');await bob.waitForFunction(()=>Math.abs(__universe.getCamera().yaw-Math.PI/4)<.001);const before=(await state(bob)).position;const orbit=await projected(bob,before.x,before.z);await bob.mouse.move(orbit.x,orbit.y);await bob.mouse.down({button:'right'});await bob.mouse.move(orbit.x+(Math.PI/4)/.006,orbit.y,{steps:12});await bob.mouse.up({button:'right'});const yaw=await bob.evaluate(()=>__universe.getCamera().yaw);assert(Math.min(Math.abs(yaw),Math.abs(yaw-Math.PI*2))<.03,'Native orbit aligns one movement key with the pond boundary');await bob.locator('#game').focus();await bob.keyboard.down('Shift');await bob.keyboard.down('w');await bob.waitForTimeout(1100);await bob.keyboard.up('w');await bob.keyboard.up('Shift');const after=(await state(bob)).position;console.log('COLLISION DIAGNOSTIC',JSON.stringify({before,after,camera:await bob.evaluate(()=>__universe.getCamera()),water:(await scene(bob)).terrain.cells.filter(c=>c[2]==='water')}));assert(after.x<before.x-.5,'Movement precondition');assert(after.z>2.3&&after.z<4.7,'Movement stayed aligned with the pond rather than walking around its edge');assert(after.x>=6.29,'Pond blocks walking');assert(canStand(await scene(bob),after.x,after.z));await walk(bob,4.5,6.5);const q=await projected(bob,4.5,1.5);await bob.mouse.click(q.x,q.y);const path=await bob.evaluate(()=>__universe.getPath());assert(path.length>0);const committed=await scene(bob);assert(path.every(p=>canStand(committed,p.x,p.z)));assert(path.some(p=>p.x<2.7||p.x>6.3),'Path detours around water');await bob.waitForFunction(()=>Math.hypot(__universe.getState().position.x-4.5,__universe.getState().position.z-1.5)<.35&&!__universe.getPath().length,null,{timeout:30000});
 });
 await pass('Wall stroke remains an ordinary selectable, rotatable and movable object',async()=>{
  await terrain(alice);await alice.getByRole('button',{name:'Draw wall',exact:true}).click();const before=(await scene(alice)).objects.length;await drag(alice,[-7.2,2.2],[-3.2,2.2]);let wall=(await scene(alice)).objects.at(-1);assert.equal(wall.type,'wall');assert.equal((await scene(alice)).objects.length,before+1);await alice.getByRole('button',{name:'↖ Select',exact:true}).click();const q=await projected(alice,wall.x,wall.z,1);await alice.mouse.click(q.x,q.y);assert.equal((await editor(alice)).selected,wall.id);await alice.locator('#game').focus();await alice.keyboard.press('r');const rotated=(await scene(alice)).objects.find(o=>o.id===wall.id);assert.equal((rotated.rotation-wall.rotation+360)%360,90);await alice.keyboard.press('Control+z');wall=(await scene(alice)).objects.find(o=>o.id===wall.id);const a=await projected(alice,wall.x,wall.z,1),b=await projected(alice,wall.x,wall.z-1);await alice.mouse.move(a.x,a.y);await alice.mouse.down();await alice.mouse.move(b.x,b.y,{steps:6});await alice.mouse.up();assert.notDeepEqual((await scene(alice)).objects.find(o=>o.id===wall.id),wall);await save(alice);
 });
 await pass('Erase restores base, cancel leaves no paint, keyboard sizing commits once and saved terrain reloads',async()=>{
  await terrain(alice,'wood');const original=await scene(alice);await drag(alice,[-4.2,6.2],[-2.2,6.2],{cancel:true});assert.deepEqual(await scene(alice),original);await terrain(alice);await alice.getByRole('button',{name:'Restore base',exact:true}).click();await drag(alice,[-5.2,4.2],[-1.2,5.2]);assert.equal((await scene(alice)).terrain.cells.filter(c=>c[2]==='stone').length,0);await alice.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual(await scene(alice),original);await terrain(alice,'soil');const q=await projected(alice,-2.5,-1.5);await alice.mouse.move(q.x,q.y);await alice.locator('#game').focus();await alice.keyboard.press('Shift+ArrowRight');await alice.keyboard.press('Shift+ArrowDown');const preview=(await editor(alice)).preview;assert(preview.width*preview.depth>1);const before=(await scene(alice)).terrain.cells.length;await alice.keyboard.press('Enter');assert((await scene(alice)).terrain.cells.length>before);assert.equal(await alice.locator('#editor').isVisible(),true,'Build retains its native Enter action');assert.equal(await alice.locator('.express-tray').isVisible(),false,'Build Enter cannot also open Express on keyup');const saved=await save(alice);await closeBuild(alice);await alice.screenshot({path:out+'/authored-garden-desktop.png',timeout:60000});await alice.reload({waitUntil:'domcontentloaded'});await alice.waitForFunction(()=>window.__universe?.getState().ready);assert.deepEqual(await scene(alice),saved);
 });
 await pass('A real concurrent save preserves the losing terrain draft through existing CAS recovery',async()=>{
  await terrain(alice,'wood');await alice.getByRole('button',{name:'Close terrain palette',exact:true}).click();await drag(alice,[7.2,5.2],[8.2,5.2]);const draft=await scene(alice);const current=(await(await alice.request.get(base+'/api/rooms/commons')).json()).room;current.scene.theme='studio';assert.equal((await alice.request.put(base+'/api/rooms/commons/scene',{data:{revision:current.revision,scene:current.scene}})).status(),200);await alice.getByRole('button',{name:'Save room',exact:true}).click();await alice.waitForFunction(()=>!__universe.getEditor().saving);assert.deepEqual(await scene(alice),draft);await alice.getByRole('button',{name:'Load server version',exact:true}).click();assert.equal((await editor(alice)).dirty,false);
 });
 await pass('390px native touch separates camera cancellation from subsequent terrain placement',async()=>{
  const storageState=await alice.context().storageState();await alice.context().close();await bob.context().close();const mobile=await enter('',{storageState,viewport:{width:390,height:844},isMobile:true,hasTouch:true});alice=mobile;bob=null;await terrain(mobile,'grass');await mobile.getByRole('button',{name:'Close terrain palette',exact:true}).tap();const q=await projected(mobile,2.5,6.5),before=await scene(mobile),cdp=await mobile.context().newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:q.x,y:q.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:q.x,y:q.y},{id:2,x:q.x+40,y:q.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:q.x-12,y:q.y-8},{id:2,x:q.x+65,y:q.y+8}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.deepEqual(await scene(mobile),before);await mobile.locator('#home-camera').tap();const target=await projected(mobile,2.5,6.5);await mobile.touchscreen.tap(target.x,target.y);assert.notDeepEqual(await scene(mobile),before);await mobile.getByRole('button',{name:'Save room',exact:true}).scrollIntoViewIfNeeded();await save(mobile);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth),390);await mobile.screenshot({path:out+'/terrain-touch-390.png',timeout:60000});
 });
 assert.deepEqual(errors,[]);
}catch(error){checks.push({name:phase,status:'failed',error:error.stack});process.exitCode=1;console.error(error);for(const [name,p] of [['owner',alice],['visitor',bob]])if(p&&!p.isClosed())console.error(name,await p.evaluate(()=>({position:__universe.getState().position,terrain:__universe.getState().scene.terrain,camera:__universe.getCamera(),editor:__universe.getEditor(),toast:document.querySelector('#toast')?.textContent})).catch(e=>e.message));if(alice&&!alice.isClosed())await alice.screenshot({path:out+'/failure.png',timeout:60000}).catch(()=>{});
}finally{const hash=async file=>createHash('sha256').update(await readFile(new URL('../dist/'+file,import.meta.url))).digest('hex');await writeFile(out+'/results.json',JSON.stringify({checks,errors,bundle:{js:await hash('main.js'),css:await hash('main.css')},limits:['Isolated local accounts and fixture room; no live service changes','Native pointer/keyboard/CDP touch with read-only application diagnostics','Software WebGL and touch emulation; no physical-phone or production-capacity claim']},null,2));for(const ctx of contexts)await ctx.close().catch(()=>{});await browser.close();await app.close();}
