import {build} from 'esbuild';
import {mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {launch} from '../scripts/browser.mjs';
import {seedWorlds} from '../src/worlds.js';
import {createGameServer} from '../server/app.mjs';
await mkdir('evidence',{recursive:true});
await build({stdin:{contents:`import{EngineStore}from'@babylonjs/core/Engines/engineStore.js';import{createRenderer}from'./src/renderer.js';import{seedWorlds}from'./src/worlds.js';const r=await createRenderer(document.querySelector('canvas'),document.querySelector('#labels'));window.settle=async()=>{await EngineStore.LastCreatedScene.whenReadyAsync();r.render(.016);r.render(.016);};window.base=structuredClone(seedWorlds[0].rooms[0].scene);window.paint=(source=base)=>{const next=structuredClone(source),cells=new Map();function rect(x0,z0,x1,z1,material,blocked=false){for(let z=z0;z<=z1;z++)for(let x=x0;x<=x1;x++)cells.set(x+','+z,[x,z,material,blocked]);}rect(4,2,10,9,'stone');rect(5,3,9,7,'water',true);rect(-9,3,-3,6,'wood');rect(-10,3,-10,7,'soil');rect(-9,7,-3,7,'grass');next.terrain={version:1,cells:[...cells.values()]};return next;};r.sync(base);r.setFollow(false);r.setTarget(0,2);window.snapshot=()=>{const s=EngineStore.LastCreatedScene;return {meshes:s.meshes.length,nodes:s.transformNodes.length,materials:s.materials.length,textures:s.textures.length,terrain:s.meshes.filter(m=>m.metadata?.type==='terrain'||m.metadata?.ranges?.some(a=>a.metadata?.type==='terrain')).map(m=>({name:m.name,pickable:m.isPickable,vertices:m.getTotalVertices()})),ghost:s.getTransformNodeByName('build-preview')?.getChildMeshes().map(m=>({id:m.uniqueId,name:m.name,pickable:m.isPickable})),water:s.materials.filter(m=>m.name.startsWith('water')).map(m=>({alpha:m.alpha,specular:m.specularPower,offset:m.diffuseTexture?.vOffset}))};};let last=0;function loop(t){r.render(Math.min(.05,(t-last)/1000||.016));last=t;requestAnimationFrame(loop);}requestAnimationFrame(loop);await r.ready;window.r=r;`,resolveDir:process.cwd()},bundle:true,format:'esm',minify:true,outfile:'evidence/terrain-harness.js'});
const app=createGameServer({seeds:seedWorlds,dist:new URL('../dist',import.meta.url).pathname}),address=await app.listen(0),browser=await launch(),page=await browser.newPage({viewport:{width:1280,height:900},deviceScaleFactor:2}),errors=[],checks=[];
page.on('pageerror',error=>errors.push(error.message));const check=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
await page.route('**/terrain-harness.js',async route=>route.fulfill({contentType:'text/javascript',body:await readFile('evidence/terrain-harness.js')}));
await page.route('**/terrain-harness',route=>route.fulfill({contentType:'text/html',body:'<html><head><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#14121e}canvas{width:100%;height:100%;display:block}#labels{position:absolute;inset:0;pointer-events:none}.world-label{position:absolute;left:0;top:0;color:#ede8f3;font:12px sans-serif;white-space:nowrap;text-shadow:0 1px 4px #14121e}</style></head><body><canvas></canvas><div id="labels"></div><script type="module" src="/terrain-harness.js"></script></body></html>'}));
let stats;
try{
 await page.goto(`http://127.0.0.1:${address.port}/terrain-harness`);await page.waitForFunction(()=>!!window.r);await page.evaluate(()=>settle());const baseline=await page.evaluate(()=>snapshot());
 await page.evaluate(()=>r.sync(paint()));await page.evaluate(()=>settle());const painted=await page.evaluate(()=>snapshot());assert(painted.terrain.length>0&&painted.terrain.length<=5);assert(painted.terrain.every(m=>!m.pickable));assert.equal(painted.water.length,1);assert.equal(painted.water[0].alpha,1);assert.equal(painted.water[0].specular,80);check('five authored materials render in pooled nonpickable batches with opaque rippled water');
 const waterPixel=await page.evaluate(()=>{r.render(.016);const canvas=document.querySelector('canvas'),probe=document.createElement('canvas');probe.width=canvas.width;probe.height=canvas.height;const ctx=probe.getContext('2d');ctx.drawImage(canvas,0,0);const p=r.screenPoint(7.5,5.5,.024);return [...ctx.getImageData(p.x*canvas.width/canvas.clientWidth,p.y*canvas.height/canvas.clientHeight,1,1).data];});assert(waterPixel[0]<waterPixel[1]*.85&&waterPixel[0]<waterPixel[2]*.85,'visible pond pixel is blue-green, not exposed base paving');check('water surface is visibly rendered above its cut-away base');await page.screenshot({path:'evidence/terrain-authored-desktop.png'});
 for(const [x,z]of [[7,5],[-5,4],[-9.5,5]]){const picked=await page.evaluate(([x,z])=>{const p=r.screenPoint(x,z);return r.pick(p.x,p.y);},[x,z]);assert(Math.abs(picked.point.x-x)<.015);assert(Math.abs(picked.point.z-z)<.015);assert.notEqual(picked.type,'terrain');}check('DPR2 ground ray remains exact over water, wood and soil');
 const moving=await page.evaluate(()=>{r.setGhost({type:'terrain',kind:'terrain',x:6,z:4,width:4,depth:3,material:'water',blocked:true,valid:true});const first=snapshot();r.setGhost({type:'terrain',kind:'terrain',x:7,z:5,width:4,depth:3,material:'water',blocked:true,valid:true});return {first,second:snapshot()};});assert.deepEqual(moving.first.ghost,moving.second.ghost);assert(moving.second.ghost.every(m=>!m.pickable));assert(moving.second.ghost.some(m=>m.name==='terrain-preview-fill'));assert(moving.second.ghost.some(m=>m.name==='terrain-preview-cells'));check('terrain ghost moves without rebuilding meshes and never captures picking');await page.waitForTimeout(100);await page.screenshot({path:'evidence/terrain-blocked-ghost.png'});
 const objectPick=await page.evaluate(()=>{r.setGhost({type:'terrain',x:-6,z:-2,width:4,depth:3,material:'stone',blocked:false,valid:true});const p=r.screenPoint(-6,-2,1);return r.pick(p.x,p.y);});assert.equal(objectPick.id,'commons-table');check('terrain preview preserves merged object face selection');
 const repeated=await page.evaluate(()=>{for(let i=0;i<30;i++){r.setGhost({type:'terrain',x:i%4,z:4,width:2+i%5,depth:1+i%4,material:'water',blocked:i%2===0,erase:i%3===0,valid:i%5!==0});r.setGhost(null);}r.sync(paint());const before=snapshot();for(let i=0;i<6;i++){r.sync(base);r.sync(paint());}return {before,after:snapshot()};});for(const key of ['meshes','nodes','materials','textures'])assert.equal(repeated.before[key],repeated.after[key],key);check('repeated preview, commit and erase cycles do not accumulate render resources');
 const animation=await page.evaluate(()=>{const a=snapshot().water[0].offset;r.render(.05);return {a,b:snapshot().water[0].offset};});assert.notEqual(animation.a,animation.b);check('water motion updates a shared texture without rebuilding geometry');
 await page.evaluate(()=>r.sync(base));const restored=await page.evaluate(()=>snapshot());assert.equal(restored.meshes,baseline.meshes);assert.equal(restored.nodes,baseline.nodes);assert.equal(restored.terrain.length,0);check('erasure restores the original environment mesh and node composition');
 const max=await page.evaluate(()=>{const next=structuredClone(base);next.bounds={width:64,depth:64};next.objects=[];next.areas=[];const materials=['grass','soil','stone','wood','water'];next.terrain={version:1,cells:[]};for(let z=-32;z<32;z++)for(let x=-32;x<32;x++)next.terrain.cells.push([x,z,materials[((x+z)%5+5)%5],false]);const start=performance.now();r.sync(next);return {...snapshot(),syncMs:performance.now()-start};});await page.evaluate(()=>settle());stats=await page.evaluate(()=>r.getStats());assert.equal(max.terrain.length,5);assert(max.meshes<20);assert(stats.drawCalls<25);check('4096-cell checkerboard remains five surface batches and fewer than 25 draw calls');
 await page.evaluate(()=>{r.sync(paint());r.setTarget(4,4);r.zoom(-5);});await page.setViewportSize({width:700,height:900});await page.evaluate(()=>settle());await page.screenshot({path:'evidence/terrain-authored-narrow.png'});
 assert.deepEqual(errors,[]);await writeFile('evidence/terrain-renderer-results.json',JSON.stringify({checks,baseline,painted,max,stats,errors},null,2));
}catch(error){console.error(error);await page.screenshot({path:'evidence/terrain-renderer-failure.png'}).catch(()=>{});await writeFile('evidence/terrain-renderer-results.json',JSON.stringify({checks,errors,failure:error.stack},null,2));process.exitCode=1;}finally{await browser.close();await app.close();await rm('evidence/terrain-harness.js',{force:true});}
