import {build} from 'esbuild';
import {launch} from '../scripts/browser.mjs';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';

// Actual editor + world-input pointer arbitration; only ground projection and API are fixtures.
const source=`import {mountEditor} from './src/editor.js';import {mountWorldInput} from './src/world-input.js';import {emptyScene,contains,collisionBox} from './src/worlds.js';
const fresh=()=>emptyScene(),scene=fresh();window.state={scene,room:{id:'terrain-fixture',role:'owner',revision:1,scene:structuredClone(scene)},position:{x:0,z:7}};window.logs={commits:0,orbits:0,toasts:[],closed:0,requests:[]};let rejectNext=false;
window.toScreen=(x,z)=>({x:innerWidth/2+x*20,y:innerHeight*.32+z*20});
const pick=(x,y)=>{const point={x:(x-innerWidth/2)/20,z:(y-innerHeight*.32)/20};return {point,id:state.scene.objects.find(o=>contains(collisionBox(o,state.scene),point.x,point.z,.12))?.id};};
const renderer={pick,setGhost:()=>{},orbit:()=>logs.orbits++,pan:()=>logs.orbits++,zoom:()=>{},getCameraState:()=>({distance:25})};
window.editor=mountEditor({root:document.querySelector('#editor'),getState:()=>state,onScene:s=>{state.scene=s;logs.commits++},onSelect:()=>{},toast:t=>logs.toasts.push(t),onGhost:()=>{},onClose:()=>logs.closed++,getCameraAngle:()=>Math.PI/2,editPolicy:()=>({canEdit:true,canEditItem:()=>true,validateChange:()=>null}),api:async(url,args)=>{logs.requests.push({url,args});if(rejectNext==='occupied'){rejectNext=false;throw Object.assign(Error('Move this terrain away from another person before saving.'),{status:409,data:{code:'TERRAIN_BLOCKS_PLAYER',error:'TERRAIN_BLOCKS_PLAYER',message:'Move this terrain away from another person before saving.'}});}if(rejectNext){rejectNext=false;throw Object.assign(Error('Stale room'),{status:409,data:{code:'REVISION_CONFLICT',room:{...state.room,revision:9,scene:{...fresh(),theme:'studio'}}}});}return {room:{...state.room,revision:state.room.revision+1,scene:structuredClone(args.body.scene)}};}});
window.input=mountWorldInput({canvas:document.querySelector('#game'),joystickRoot:document.querySelector('#joystick'),joystickThumb:document.querySelector('#thumb'),getContext:()=>({ready:true,building:true,modalOpen:false}),getRenderer:()=>renderer,getEditor:()=>editor,onWalkTo:()=>{},onInteract:()=>{},onJoystick:()=>{}});
window.replaceRoom=()=>{state.scene=fresh();state.room={id:'room-'+crypto.randomUUID(),role:'owner',revision:1,scene:structuredClone(state.scene)};editor.attachRoom();};window.revoke=()=>{state.room.role='member';state.room.capabilities={canEditScene:false};editor.receiveScene({...state.room});};window.restore=()=>{state.room.role='owner';state.room.capabilities={canEditScene:true};editor.receiveScene({...state.room});};window.rejectSave=(reason=true)=>{rejectNext=reason};editor.attachRoom();editor.setBuild(true);`;
const bundle=await build({stdin:{contents:source,resolveDir:process.cwd(),sourcefile:'terrain-editor-fixture.js'},bundle:true,format:'iife',write:false});
const css=(await Promise.all(['public/universe-tokens.css','public/style.css','src/editor.css'].map(p=>readFile(p,'utf8')))).join('\n');
const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}\nhtml,body{margin:0;width:100%;height:100%;overflow:hidden}#game{position:absolute;inset:0;width:100%;height:100%;touch-action:none;background:#537263}#joystick{display:none}[hidden]{display:none!important}</style><canvas id="game" tabindex="0"></canvas><aside id="editor"></aside><div id="joystick"><div id="thumb"></div></div>`;
const browser=await launch(),ctx=await browser.newContext({viewport:{width:1440,height:960}}),page=await ctx.newPage(),checks=[],errors=[];
page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
const report=name=>{checks.push({name,status:'passed'});console.log('PASS',name);};
const start=async p=>{await p.route('https://terrain.test/',route=>route.fulfill({status:200,contentType:'text/html',body:html}));await p.goto('https://terrain.test/');await p.addScriptTag({content:bundle.outputFiles[0].text});};
const screen=(p,x,z)=>p.evaluate(([x,z])=>toScreen(x,z),[x,z]);
const move=async(p,x,z)=>{const q=await screen(p,x,z);await p.mouse.move(q.x,q.y,{steps:6});};
const dragStart=async(p,x,z,tx,tz)=>{await move(p,x,z);await p.mouse.down();await move(p,tx,tz);};
const click=async(p,x,z)=>{const q=await screen(p,x,z);await p.mouse.click(q.x,q.y);};
const snapshot=p=>p.evaluate(()=>structuredClone(state.scene));
const choose=async(p,name)=>{if(!await p.getByRole('region',{name:'Terrain tools'}).isVisible())await p.getByRole('button',{name:'Terrain',exact:true}).click();await p.getByRole('button',{name:'Paint '+name,exact:true}).click();};
try{
 await mkdir('evidence',{recursive:true});await start(page);await page.locator('#game').focus();for(let i=0;i<30&&await page.evaluate(()=>document.activeElement.getAttribute('aria-label'))!=='Terrain';i++)await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Terrain');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>editor.getInteractionState().tool),'terrain');for(let i=0;i<40&&await page.evaluate(()=>document.activeElement.getAttribute('aria-label'))!=='Paint stone';i++)await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Paint stone');await page.keyboard.press('Enter');report('Tab and native Enter reach Terrain and its material palette without a mouse');
 await dragStart(page,-3.8,-2.8,-1.8,-.8);assert.equal(await page.evaluate(()=>logs.commits),0);assert.equal(await page.evaluate(()=>editor.getInteractionState().preview.width),3);assert.equal(await page.evaluate(()=>editor.getInteractionState().preview.depth),3);await page.mouse.up();assert.equal(await page.evaluate(()=>logs.commits),1);assert.equal(await page.evaluate(()=>editor.getInteractionState().undo),1);assert.equal((await snapshot(page)).terrain.cells.length,9);const painted=await snapshot(page);report('Native mouse rectangle previews without mutation, then releases as one 9-cell transaction');
 await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal((await snapshot(page)).terrain,undefined);await page.getByRole('button',{name:'Redo',exact:true}).click();assert.deepEqual(await snapshot(page),painted);report('One native Undo and Redo restore the complete rectangle');
 await choose(page,'wood');await click(page,-2.8,-1.8);assert.equal((await snapshot(page)).terrain.cells.length,9);assert.equal((await snapshot(page)).terrain.cells.filter(c=>c[2]==='wood').length,1);await page.getByRole('button',{name:'Restore base',exact:true}).click();await dragStart(page,-3.8,-2.8,-1.8,-.8);await page.mouse.up();assert.deepEqual((await snapshot(page)).terrain.cells,[]);await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal((await snapshot(page)).terrain.cells.length,9);report('Click repaint and rectangular restore-base use the same reversible terrain transaction');
 await choose(page,'water');assert(await page.getByRole('checkbox',{name:'Blocks walking'}).isChecked());assert.match(await page.locator('.terrain-note').innerText(),/No swimming/);await page.getByRole('checkbox',{name:'Blocks walking'}).uncheck();assert.equal(await page.evaluate(()=>editor.getInteractionState().preview.blocked),false);await page.getByRole('checkbox',{name:'Blocks walking'}).check();assert.equal(await page.evaluate(()=>editor.getInteractionState().preview.blocked),true);const beforeReject=await snapshot(page);await click(page,.2,7.2);assert.deepEqual(await snapshot(page),beforeReject);assert.match(await page.locator('.builder-hint').innerText(),/arrival/);await click(page,2.2,-1.8);assert.deepEqual((await snapshot(page)).terrain.cells.find(c=>c[0]===2&&c[1]===-2),[2,-2,'water',true]);report('Water defaults blocking, labels no swimming and rejects arrival coverage');
 await choose(page,'soil');const beforeCancel=await snapshot(page);await dragStart(page,4.2,-2.8,6.2,-.8);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual(await snapshot(page),beforeCancel);await dragStart(page,4.2,-2.8,6.2,-.8);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.mouse.up();assert.deepEqual(await snapshot(page),beforeCancel);await dragStart(page,4.2,-2.8,6.2,-.8);await page.locator('#game').dispatchEvent('pointercancel',{pointerId:1,pointerType:'mouse'});await page.mouse.up();assert.deepEqual(await snapshot(page),beforeCancel);report('Escape, native pointercancel and window blur discard pending paint');
 await move(page,4.2,-2.8);await page.mouse.down({button:'right'});await move(page,6.2,-.8);await page.mouse.up({button:'right'});assert.deepEqual(await snapshot(page),beforeCancel);assert(await page.evaluate(()=>logs.orbits>0));report('Right-drag reaches camera arbitration without leaking terrain');
 await page.getByRole('button',{name:'Paint grass',exact:true}).focus();await page.keyboard.press('Enter');await page.keyboard.press('Shift+ArrowLeft');await page.keyboard.press('Shift+ArrowLeft');const sized=await page.evaluate(()=>editor.getInteractionState().preview);assert.equal(sized.width,3);assert.equal(sized.depth,1);await page.keyboard.press('r');assert.equal(await page.evaluate(()=>editor.getInteractionState().preview.depth),3);await page.keyboard.press('ArrowUp');const beforeKey=await page.evaluate(()=>editor.getInteractionState().undo);await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>editor.getInteractionState().undo),beforeKey+1);report('Native keyboard reaches material, resizes, rotates, moves and commits one rectangle with Enter');
 await page.evaluate(()=>replaceRoom());await page.getByRole('button',{name:'Terrain',exact:true}).click();await page.getByRole('button',{name:'Draw wall',exact:true}).click();await dragStart(page,-3,-2,1,-1.8);assert.equal((await snapshot(page)).objects.length,0);await page.mouse.up();const wall=(await snapshot(page)).objects[0];assert.equal(wall.type,'wall');assert.equal(wall.width,4);assert.equal(wall.rotation,0);await page.getByRole('button',{name:'↖ Select',exact:true}).click();await dragStart(page,-1,-2,1,-4);await page.mouse.up();const moved=(await snapshot(page)).objects[0];assert.equal(moved.id,wall.id);assert.notEqual(moved.x,wall.x);await page.keyboard.press('r');assert.equal((await snapshot(page)).objects[0].rotation,90);await page.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual((await snapshot(page)).objects[0],moved);report('Draw wall creates one ordinary wall; native Select drag, R and Undo preserve its identity');
 await choose(page,'stone');await dragStart(page,4.2,-2.8,6.2,-.8);const beforeRevoke=await snapshot(page);await page.evaluate(()=>revoke());await page.mouse.up();assert.deepEqual(await snapshot(page),beforeRevoke);assert(await page.getByRole('button',{name:'Terrain',exact:true}).isDisabled());assert.equal(await page.evaluate(()=>editor.setTool('terrain')),false);assert.equal(await page.evaluate(()=>editor.setTool('terrain-erase')),false);report('Mid-stroke revocation cancels paint and denies terrain even with permissive personal-space policy');
 await page.evaluate(()=>restore());await choose(page,'stone');await dragStart(page,4.2,-2.8,6.2,-.8);await page.evaluate(()=>replaceRoom());await page.mouse.up();assert.equal((await snapshot(page)).terrain,undefined);assert.equal(await page.evaluate(()=>editor.getInteractionState().undo),0);report('Room replacement discards pending stroke and resets terrain history');
 await choose(page,'water');await click(page,3.2,-2.8);const occupiedDraft=await snapshot(page),occupiedHistory=await page.evaluate(()=>editor.getInteractionState().undo),occupiedRevision=await page.evaluate(()=>state.room.revision);await page.evaluate(()=>rejectSave('occupied'));await page.getByRole('button',{name:'Save room',exact:true}).click();await page.waitForFunction(()=>!editor.isSaving());assert.deepEqual(await snapshot(page),occupiedDraft);assert.equal(await page.evaluate(()=>state.room.revision),occupiedRevision);assert.equal(await page.evaluate(()=>editor.getInteractionState().undo),occupiedHistory);assert.equal(await page.evaluate(()=>editor.isDirty()),true);assert.match(await page.locator('.builder-recovery').innerText(),/Move this terrain away from another person before saving/);assert.doesNotMatch(await page.locator('.builder-recovery').innerText(),/newer|Load server/);assert.equal(await page.getByRole('button',{name:'Load server version',exact:true}).count(),0);assert(await page.getByRole('button',{name:'Save room',exact:true}).isEnabled());await page.getByRole('button',{name:'Save room',exact:true}).click();await page.waitForFunction(()=>!editor.isSaving());assert.deepEqual(await snapshot(page),occupiedDraft);assert.equal(await page.evaluate(()=>editor.isDirty()),false);assert.equal(await page.evaluate(()=>state.room.revision),occupiedRevision+1);assert.deepEqual(await page.evaluate(()=>logs.requests.at(-1).args.body.scene),occupiedDraft);assert(await page.locator('.builder-recovery').isHidden());report('Occupied-terrain 409 shows its actual reason, retains exact draft and history, and successfully retries without false CAS recovery');
 await choose(page,'wood');await click(page,3.2,-2.8);const draft=await snapshot(page);await page.evaluate(()=>rejectSave());await page.getByRole('button',{name:'Save room',exact:true}).click();await page.waitForFunction(()=>!editor.isSaving());assert.deepEqual(await snapshot(page),draft);assert(await page.getByRole('button',{name:'Load server version',exact:true}).isVisible());await page.getByRole('button',{name:'Load server version',exact:true}).click();assert.equal((await snapshot(page)).theme,'studio');assert.equal((await snapshot(page)).terrain,undefined);report('Terrain save conflict retains the exact draft; explicit recovery loads server ground');
 await choose(page,'stone');await page.screenshot({path:'evidence/terrain-workbench-desktop.png'});
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await start(m);await choose(m,'stone');await m.getByRole('button',{name:'Close terrain palette',exact:true}).tap();assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth),390);const cdp=await mobile.newCDPSession(m),a=await screen(m,-3.8,-1.8),b=await screen(m,-1.8,.2);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...b,id:1}]});assert.equal((await snapshot(m)).terrain,undefined);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal((await snapshot(m)).terrain.cells.length,9);const touched=await snapshot(m);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...a,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...b,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...b,id:2},{x:b.x+35,y:b.y,id:3}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+10,y:b.y,id:2},{x:b.x+50,y:b.y+10,id:3}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.deepEqual(await snapshot(m),touched);assert(await m.evaluate(()=>logs.orbits>0));await m.getByRole('button',{name:'More build tools',exact:true}).tap();await m.getByRole('button',{name:'Undo',exact:true}).tap();assert.equal((await snapshot(m)).terrain,undefined);await m.screenshot({path:'evidence/terrain-workbench-mobile.png'});report('390px native touch drag commits once; adding a second finger cancels pending paint; touch Undo restores ground');await mobile.close();assert.deepEqual(errors,[]);
}catch(error){checks.push({name:'failure',status:'failed',error:error.stack});console.error(error);await page.screenshot({path:'evidence/terrain-workbench-failure.png'}).catch(()=>{});process.exitCode=1;}
finally{await writeFile('evidence/terrain-editor-checks.json',JSON.stringify({checks,errors,limits:['Actual editor and world-input with native Chromium mouse, keyboard and touch; deterministic ground projection and save API fixtures','WebGL appearance, real server authority and full-shell room propagation are tested by integration owner']},null,2));await ctx.close();await browser.close();}
