/** Full-renderer personal-area acceptance, ordinary local user workflows only.
 * Registered fixture accounts are created via authenticated local API setup.
 * Area creation, claims, transfers, bounded edits and manager actions use the UI.
 */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
const dist=process.env.UNIVERSE_TRANCHE_DIST||new URL('../dist',import.meta.url).pathname;
const buildSha256=createHash('sha256').update(await readFile(join(dist,'main.js'))).digest('hex');
const scene={version:1,theme:'garden',bounds:{width:32,depth:32},spawn:{x:0,z:8},objects:[],areas:[]};
const app=createGameServer({seeds:[{id:'personal-world',name:'Personal fixture world',rooms:[{id:'personal-room',name:'Personal acceptance room',scene}]}],dist,questsEnabled:false});
const {port}=await app.listen(0),base=`http://127.0.0.1:${port}`,browser=await launch();
const checks=[],errors=[],failures=[],consoleErrors=[],operations=[],contexts=[];let p,current;
const pass=(name,details={})=>{checks.push({name,status:'passed',...details});console.log('PASS',name)};
async function fixtureAccount(name,username){let cookie='';const call=async(path,method='GET',body)=>{const res=await fetch(base+path,{method,headers:{Cookie:cookie,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];const data=await res.json();assert(res.ok,JSON.stringify({path,status:res.status,data}));return data};await call('/api/session','POST',{name});await call('/api/account','POST',{username,password:'Local acceptance fixture only'});const user=(await call('/api/session')).user;await call('/api/rooms/personal-room/join','POST',{});return{user,cookie:()=>cookie,call}}
const manager=await fixtureAccount('Local manager','tranche_manager'),alice=await fixtureAccount('Local Alice','tranche_alice'),bob=await fixtureAccount('Local Bob','tranche_bob');
async function pageFor(account,options={}){if(current)await current.close();current=await browser.newContext({viewport:{width:1440,height:950},reducedMotion:'reduce',...options});contexts.push(current);await current.addCookies([{name:'universe_session',value:account.cookie().split('=')[1],url:base}]);p=await current.newPage();p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});p.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/personal-areas/'))operations.push({url:new URL(r.url()).pathname,body:r.postDataJSON()})});await p.goto(base+'/?room=personal-room',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe?.getState().ready);await p.waitForFunction(()=>!!__universe.getStats());return p}
const read=()=>p.evaluate(()=>__universe.getState());const ed=()=>p.evaluate(()=>__universe.getEditor());const key=name=>p.locator(`[data-focus-key="${name}"]`);const btn=name=>p.locator(`[data-personal-key="${name}"]`);
async function fill(name,value){await key(name).fill(String(value));await key(name).press('Tab')}
async function shot(name){await p.screenshot({path:`evidence/tranche-personal-${name}.png`})}
async function save(name='Save room'){await p.getByRole('button',{name,exact:true}).click();await p.waitForFunction(()=>!__universe.getEditor().saving&&!__universe.getEditor().dirty)}
async function personal(id){await p.locator('#game').focus();await p.keyboard.press('l');await btn('close').waitFor();await p.waitForFunction(()=>!document.querySelector('.personal-area-sheet')?.textContent.includes('Checking current room…'));if(id){if(!await btn('area-'+id).count()&&await btn('back').count())await btn('back').click();await btn('area-'+id).click()}}
async function closePersonal(){await btn('close').click();await p.locator('.personal-area-sheet').waitFor({state:'hidden'});await p.waitForFunction(()=>history.state?.surface!=='personal')}
async function walk(x,z,{desk=false}={}){await p.locator('#game').focus();if(desk)await p.keyboard.press('Control+d');else{const pt=await p.evaluate(({x,z})=>__universe.getScreenPoint(x,z),{x,z});assert(pt.x>=0&&pt.x<1440&&pt.y>=0&&pt.y<950,JSON.stringify(pt));await p.mouse.click(pt.x,pt.y)}const samples=[];const start=Date.now();while(Date.now()-start<60000){const s=await p.evaluate(()=>({position:__universe.getState().position,motion:__universe.getMotion(),path:__universe.getPath()}));samples.push(s.motion);if(Math.hypot(s.position.x-x,s.position.z-z)<.35&&!s.path.length)return{maxSpeed:Math.max(...samples.map(s=>s.speed)),running:samples.some(s=>s.running),samples:samples.length};await p.waitForTimeout(40)}throw Error('Actual world walk did not reach '+x+','+z+'; '+JSON.stringify((await read()).position))}
async function createArea(name,x,z,mode){await p.getByRole('button',{name:'▱ Area',exact:true}).click();await p.keyboard.press('Space');const id=(await ed()).selected;assert(id);await fill('Name',name);await fill('X',x);await fill('Z',z);await fill('Width',6);await fill('Depth',6);await p.locator('[data-section="personal-area"] summary').click();await key('Personal space mode').selectOption(mode);assert.equal((await read()).scene.areas.find(a=>a.id===id).personalArea.mode,mode);return id}
async function selectItem(name){if(!await p.locator('.builder-tray').isVisible())await p.getByRole('button',{name:'＋ Furniture',exact:true}).click();await p.getByRole('searchbox',{name:'Search room items'}).fill(name);await p.locator('.editor-search-results').getByRole('button',{name,exact:true}).click()}
try{
 await mkdir('evidence',{recursive:true});await pageFor(manager);await p.locator('#dock-build').click();const a=await createArea('Claimable west desk',-6,0,'dynamic'),b=await createArea('Claimable east desk',6,0,'dynamic'),s=await createArea('Assigned studio desk',0,-8,'static');await save();await shot('area-authoring');await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe?.getState().ready);assert.deepEqual((await read()).scene.areas.map(a=>a.personalArea.mode),['dynamic','dynamic','static']);pass('Manager creates/configures dynamic and static areas in real builder, saves and reloads');
 await pageFor(alice);assert.equal((await read()).user.account,true);assert.equal((await read()).room.capabilities.canEditScene,false);const normal=await walk(-6,0);await btn('invite-decline').waitFor();await btn('invite-decline').click();await p.waitForFunction(id=>__universe.getState().room.personalAreas.find(a=>a.areaId===id).declined,a);await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe?.getState().ready);await walk(-6,0);assert.equal(await p.locator('.personal-area-invitation').isVisible(),false);await personal(a);await btn('claim').click();await p.waitForFunction(id=>__universe.getState().room.personalAreas.find(a=>a.areaId===id).isOwner,a);await shot('claimed');pass('Registered account decline survives reload; Personal spaces entry reopens manual claim and grants bounded build rights');
 await btn('build').click();await p.locator('#editor').waitFor({state:'visible'});assert.equal(await p.getByRole('button',{name:'⚙ Room',exact:true}).isDisabled(),true);assert.equal(await p.getByRole('button',{name:'▱ Area',exact:true}).isDisabled(),true);await p.locator('[data-tool="chair"]').click();const cp=await p.evaluate(()=>__universe.getScreenPoint(-7,0));await p.mouse.click(cp.x,cp.y);await p.locator('#game').focus();await p.keyboard.press('v');await p.keyboard.press(']');assert.equal((await read()).scene.objects.length,1);await fill('Name','Alice personal chair');const chair=(await read()).scene.objects[0];assert.equal(chair.x,-7);await fill('X',0);assert.equal((await read()).scene.objects[0].x,-7);assert.match(await p.locator('#toast').innerText(),/inside a personal area/i);pass('Claim owner receives actual builder controls; room/area settings stay disabled and out-of-area position edit is rejected');
 // A local503 leaves the outcome unknown; deliberate Retry keeps its exact operation identity.
 let interrupted=true;const saveAttempts=[];await p.route('**/api/rooms/personal-room/scene**',route=>{const path=new URL(route.request().url()).pathname,method=route.request().method();if(path==='/api/rooms/personal-room/scene'&&method==='PUT'||path==='/api/rooms/personal-room/scene/operations'&&method==='POST'){saveAttempts.push({path,method,body:route.request().postDataJSON()});if(interrupted){interrupted=false;return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Local acceptance interrupted save'})})}}return route.continue()});await p.getByRole('button',{name:'Save room',exact:true}).click();await p.waitForFunction(()=>!__universe.getEditor().saving);assert.equal((await ed()).dirty,true);assert.equal((await read()).scene.objects[0].name,'Alice personal chair');await p.locator('.builder-recovery').waitFor({state:'visible'});await shot('draft-recovery');await save('Retry save');assert.equal(saveAttempts.length,2);assert.deepEqual(saveAttempts[1],saveAttempts[0]);assert.equal((await read()).room.scene.objects[0].name,'Alice personal chair');await p.getByRole('button',{name:'Close editor',exact:true}).click();await p.waitForFunction(()=>history.state?.surface!=='build');pass('Interrupted save keeps the scoped draft; explicit retry preserves the exact operation and commits it');
 await walk(6,0);await personal(b);await btn('claim').click();await btn('confirm-transfer').waitFor();const beforeCancel=operations.length;await btn('cancel').click();assert.equal(operations.length,beforeCancel);assert.equal((await read()).room.personalAreas.find(x=>x.areaId===a).isOwner,true);await btn('claim').click();await btn('confirm-transfer').waitFor();await shot('transfer-confirmation');await btn('confirm-transfer').click();await p.waitForFunction(id=>__universe.getState().room.personalAreas.find(a=>a.areaId===id).isOwner,b);assert.equal((await read()).room.personalAreas.find(x=>x.areaId===a).ownerId,null);assert.equal((await read()).scene.objects[0].name,'Alice personal chair');await closePersonal();pass('Transfer warns, Cancel sends no mutation, confirmed transfer releases prior area and retains its furniture');
 await walk(-6,5);const desk=await walk(6,0,{desk:true});assert(normal.maxSpeed>5.5&&normal.maxSpeed<5.7,JSON.stringify(normal));assert(desk.maxSpeed>13.8&&desk.maxSpeed<14.2,JSON.stringify(desk));assert(Math.abs(desk.maxSpeed/normal.maxSpeed-2.5)<.03);assert.equal(desk.running,true);await shot('desk-arrival');pass('Ctrl+D performs current-room scripted desk travel at source-grounded 2.5× normal peak speed',{normal,desk,ratio:desk.maxSpeed/normal.maxSpeed});
 await pageFor(manager);await personal(s);await btn('account-query').fill('Local Bob');await p.getByRole('button',{name:'Local Bob · @tranche_bob',exact:true}).click();await btn('assign').click();await p.waitForFunction(id=>__universe.getState().room.personalAreas.find(a=>a.areaId===id).owner?.name==='Local Bob',s);await shot('static-assignment');await btn('revoke').click();await btn('revoke-keep').waitFor();await btn('revoke-remove').waitFor();const beforeRevokeCancel=operations.length;await btn('cancel').click();assert.equal(operations.length,beforeRevokeCancel);await btn('revoke').click();await btn('revoke-keep').click();await p.waitForFunction(id=>!__universe.getState().room.personalAreas.find(a=>a.areaId===id).ownerId,s);assert.equal((await read()).scene.objects[0].name,'Alice personal chair');await shot('static-revoked');await closePersonal();pass('Manager account picker assigns the registered local recipient; revoke Cancel is inert and Keep all objects revokes visibly');
 await pageFor(alice,{viewport:{width:390,height:844},isMobile:true,hasTouch:true});await p.locator('#quick-actions').tap();await p.getByRole('combobox',{name:'Search actions, people and places'}).fill('Personal spaces');await p.getByRole('option').filter({hasText:'Personal spaces'}).tap();await btn('area-'+b).tap();await btn('desk').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),390);const closeBox=await btn('close').boundingBox();assert(closeBox.width>=44&&closeBox.height>=44);await shot('mobile-personal');await btn('close').tap();await p.locator('.personal-area-sheet').waitFor({state:'hidden'});pass('390px touch quick action opens owned Personal spaces with visible desk control and reachable close');
 assert.deepEqual(errors,[]);pass('No uncaught browser runtime exceptions');
}catch(error){failures.push({name:'combined personal flow',error:error.stack});console.error(error);await shot('failure').catch(()=>{});process.exitCode=1}
finally{await writeFile('evidence/tranche-personal.json',JSON.stringify({buildSha256,checks,failures,errors,consoleErrors,operations,fixtureSetup:'Registered local manager, Alice and Bob accounts created via local authenticated API; no live-host accounts or credentials',limitations:['Headless Chromium/SwiftShader and emulated touch only','Normal positive/interrupted/repeated workflows; authority threat cases covered separately','Read-only __universe diagnostics; no injected scene/runtime mutation helpers']},null,2));for(const c of contexts)await c.close().catch(()=>{});await browser.close();await app.close()}
