/** Combined app acceptance. Browser UI performs authoring and activation.
 * Local in-memory server + locally intercepted HTTPS fixture bytes only.
 * __universe diagnostics are read-only: no scene/runtime mutation helpers.
 */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';

const dist=process.env.UNIVERSE_TRANCHE_DIST||new URL('../dist',import.meta.url).pathname;
const buildSha256=createHash('sha256').update(await readFile(join(dist,'main.js'))).digest('hex');
const scene={version:1,theme:'garden',bounds:{width:32,depth:26},spawn:{x:0,z:0},objects:[],areas:[]};
const app=createGameServer({seeds:[{id:'actions-world',name:'Actions fixture world',rooms:[{id:'actions-room',name:'Actions acceptance room',scene},{id:'actions-other',name:'Actions second room',scene}]}],dist,questsEnabled:false});
const {port}=await app.listen(0),base=`http://127.0.0.1:${port}`;
const browser=await launch(),context=await browser.newContext({viewport:{width:1440,height:950},reducedMotion:'reduce'}),p=await context.newPage();
p.setDefaultTimeout(60000);
const checks=[],errors=[],consoleErrors=[],requests=[],mediaEvents=[],failures=[];
p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
const cdp=await context.newCDPSession(p);await cdp.send('Media.enable');
for(const event of ['playerEventsAdded','playerErrorsRaised','playerPropertiesChanged'])cdp.on('Media.'+event,data=>mediaEvents.push({event,...data}));
const pass=(name,details={})=>{checks.push({name,status:'passed',...details});console.log('PASS',name)};
const read=()=>p.evaluate(()=>window.__universe.getState());
const editor=()=>p.evaluate(()=>window.__universe.getEditor());
const key=name=>p.locator(`[data-focus-key="${name}"]`);
async function fill(name,value){await key(name).fill(String(value));await key(name).press('Tab')}
async function screenshot(name){await p.screenshot({path:`evidence/tranche-actions-${name}.png`})}
// Read-only native media inspection through DevTools; no Audio constructor replacement.
async function nativeAudio(){const prototype=await cdp.send('Runtime.evaluate',{expression:'HTMLAudioElement.prototype'});const objects=await cdp.send('Runtime.queryObjects',{prototypeObjectId:prototype.result.objectId});try{const result=await cdp.send('Runtime.callFunctionOn',{objectId:objects.objects.objectId,functionDeclaration:'function(){return this.map(a=>({src:a.src,volume:a.volume,paused:a.paused,loop:a.loop,error:a.error?.code||null})).filter(a=>a.src.includes("/fixtures/tranche-tone.wav"))}',returnByValue:true});return result.result.value;}finally{await cdp.send('Runtime.releaseObject',{objectId:objects.objects.objectId});await cdp.send('Runtime.releaseObject',{objectId:prototype.result.objectId});}}
async function world(x,z,y=0){const pt=await p.evaluate(({x,z,y})=>__universe.getScreenPoint(x,z,y),{x,z,y});assert(pt&&Number.isFinite(pt.x)&&Number.isFinite(pt.y));await p.mouse.click(pt.x,pt.y)}
async function save(){await p.getByRole('button',{name:'Save room',exact:true}).click();await p.waitForFunction(()=>!__universe.getEditor().saving&&!__universe.getEditor().dirty)}
async function openItem(){await p.locator('#interact').waitFor({state:'visible'});await p.locator('#interact').click();await p.locator('#dialog').waitFor({state:'visible'})}
async function activate(name){await openItem();await p.locator('#dialog-actions').getByRole('button',{name,exact:true}).click()}
async function choose(type){if(!await p.locator('.builder-tray').isVisible())await p.getByRole('button',{name:'＋ Furniture',exact:true}).click();await p.locator(`[data-tool="${type}"]`).click()}
async function selectItem(name){if(!await p.locator('.builder-tray').isVisible())await p.getByRole('button',{name:'＋ Furniture',exact:true}).click();await p.getByRole('searchbox',{name:'Search room items'}).fill(name);await p.locator('.editor-search-results').getByRole('button',{name,exact:true}).click()}
function wave(){const rate=8000,n=rate*8,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(Math.sin(2*Math.PI*220*i/rate)*1800),44+i*2);return b}
const audioBytes=wave();let failAudioOnce=true;
await context.route('**/fixtures/tranche-tone.wav',async route=>{requests.push({kind:'native-audio',url:route.request().url(),failed:failAudioOnce});if(failAudioOnce){failAudioOnce=false;await route.fulfill({status:503,contentType:'text/plain',body:'Local interrupted-audio fixture'});}else await route.fulfill({status:200,contentType:'audio/wav',headers:{'Access-Control-Allow-Origin':'*','Cache-Control':'no-store'},body:audioBytes})});
await context.route('https://tranche-fixture.invalid/**',async route=>{const denied=route.request().url().includes('/deny');requests.push({kind:denied?'denied-frame':'local-https-fixture',url:route.request().url(),navigation:route.request().isNavigationRequest()});await route.fulfill({status:200,contentType:'text/html',headers:denied?{'X-Frame-Options':'DENY','Content-Security-Policy':"frame-ancestors 'none'"}:{},body:'<!doctype html><title>Local HTTPS fixture</title><h1>'+ (denied?'Denied frame fixture':'Allowed frame fixture')+'</h1><p>These bytes were intercepted in the local browser test. No provider connection occurred.</p>'})});
try{
 await mkdir('evidence',{recursive:true});await p.goto(base+'/?room=actions-room',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!!window.__universe);await p.getByPlaceholder('Your name').fill('Actions UI owner');await p.getByRole('button',{name:'Enter Universe'}).click();await p.waitForFunction(()=>__universe.getState().ready);await p.waitForFunction(()=>!!__universe.getStats());
 await p.locator('#dock-build').click();await choose('board');await world(0,-2);await p.locator('#game').focus();await p.keyboard.press('v');await p.keyboard.press(']');assert.equal((await read()).scene.objects.length,1);await fill('Name','Actions acceptance board');await p.locator('[data-section="item-actions"] summary').click();
 // Deliberately add in a different order, then reorder using the real controls.
 for(const type of ['link','message','audio','link','teleport'])await key('add:'+type).click();
 let item=(await read()).scene.objects[0];const [link,message,audio,denied,travel]=item.actions.map(a=>a.id);
 await fill(message+':name','Read the welcome');await fill(message+':message','Saved ordered message from the combined app');
 await fill(audio+':name','Play room tone');await fill(audio+':url','/fixtures/tranche-tone.wav');await fill(audio+':label','Native local tone');await fill(audio+':volume','.4');await key(audio+':loop').selectOption('true');
 await fill(link+':name','Open fixture panel');await fill(link+':url','https://tranche-fixture.invalid/allowed');await fill(link+':label','Allowed local fixture');await key(link+':mode').selectOption('embed');await fill(link+':width','40');await key(link+':closable').selectOption('true');
 await fill(denied+':name','Open denied fixture');await fill(denied+':url','https://tranche-fixture.invalid/deny');await fill(denied+':label','Denied local fixture');await key(denied+':mode').selectOption('embed');await fill(denied+':width','40');await key(denied+':closable').selectOption('false');
 await fill(travel+':name','Travel to second room');await key(travel+':target').selectOption('actions-other');await key(message+':move:-1').click();await key(audio+':move:-1').focus();await p.keyboard.press('Space');
 const ids=[message,audio,link,denied,travel];assert.deepEqual((await read()).scene.objects[0].actions.map(a=>a.id),ids);await screenshot('ordered-editor');await save();const saved=(await read()).scene;
 await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe?.getState().ready);assert.deepEqual((await read()).scene,saved);await openItem();assert.deepEqual(await p.locator('#dialog-actions button').allTextContents(),['Read the welcome','Play room tone','Open fixture panel','Open denied fixture','Travel to second room']);pass('Real item action authoring, keyboard reorder, save and reload retain stable IDs and menu order');
 await p.locator('#dialog-actions').getByRole('button',{name:'Read the welcome',exact:true}).click();await p.getByText('Saved ordered message from the combined app',{exact:true}).waitFor();await screenshot('message');await p.locator('#dialog-close').click();pass('Saved message resolves and renders through the actual item menu');
 await activate('Play room tone');await p.locator('.world-audio-row button').filter({hasText:'Retry'}).waitFor();const beforeRetry=requests.filter(r=>r.kind==='native-audio').length;await p.getByRole('button',{name:'Play Native local tone',exact:true}).click();
 try{await p.getByRole('button',{name:'Pause Native local tone',exact:true}).waitFor({timeout:12000});assert(requests.filter(r=>r.kind==='native-audio').length>beforeRetry,'Retry must request the recovered native audio fixture');pass('Native Audio failure exposes Retry and recovers after the fixture is available');}
 catch(error){failures.push({name:'Native Audio Retry after interrupted load',error:error.message,requests:requests.filter(r=>r.kind==='native-audio')});console.error('DEFECT native audio retry',error.message);await screenshot('audio-retry-failure');await p.getByRole('button',{name:'Stop Native local tone',exact:true}).click();await activate('Play room tone');await p.getByRole('button',{name:'Pause Native local tone',exact:true}).waitFor();}
 await p.getByRole('button',{name:'Pause Native local tone',exact:true}).click();await p.getByRole('button',{name:'Play Native local tone',exact:true}).waitFor();await p.getByRole('button',{name:'Play Native local tone',exact:true}).click();await p.getByRole('button',{name:'Pause Native local tone',exact:true}).waitFor();
 assert.deepEqual((await nativeAudio()).map(a=>({volume:a.volume,loop:a.loop,paused:a.paused})),[{volume:.4,loop:true,paused:false}]);await p.getByRole('slider',{name:'World sound volume'}).focus();await p.keyboard.press('Home');for(let i=0;i<5;i++)await p.keyboard.press('ArrowRight');assert.equal(await p.getByRole('slider',{name:'World sound volume'}).inputValue(),'0.25');assert.equal(await p.evaluate(()=>localStorage.getItem('universe-world-volume')),'0.25');assert.equal((await nativeAudio())[0].volume,.25);await p.getByRole('button',{name:'Mute',exact:true}).click();assert.equal((await nativeAudio())[0].volume,0);await p.getByRole('button',{name:'Unmute',exact:true}).click();assert.equal((await nativeAudio())[0].volume,.25);await screenshot('native-audio');pass('Native Audio supports pause/resume, configured volume cap, keyboard user volume, persistent preference and mute/unmute');
 await activate('Open fixture panel');await p.frameLocator('iframe.embedded-frame').getByRole('heading',{name:'Allowed frame fixture'}).waitFor();assert.equal(await p.getByRole('button',{name:'Open in new tab ↗',exact:true}).isVisible(),true);assert.match(await p.locator('iframe.embedded-frame').getAttribute('sandbox'),/allow-scripts/);await screenshot('allowed-frame');await p.getByRole('button',{name:'Reload frame',exact:true}).click();await p.frameLocator('iframe.embedded-frame').getByRole('heading',{name:'Allowed frame fixture'}).waitFor();await p.getByRole('button',{name:'Close this panel',exact:true}).click();assert.equal(await p.locator('iframe.embedded-frame').count(),0);pass('HTTPS fixture panel loads locally intercepted bytes, reloads, and disposes its iframe on close');
 await activate('Open denied fixture');await p.locator('iframe.embedded-frame').waitFor();await p.waitForTimeout(350);assert.equal(await p.getByRole('button',{name:'Open in new tab ↗',exact:true}).isVisible(),true);assert.equal(await p.getByRole('button',{name:'Close this panel',exact:true}).isVisible(),false);assert.match(await p.locator('.embedded-status').innerText(),/blank|blocked|refus|loading/i);await screenshot('denied-frame-fallback');
 const popupPromise=context.waitForEvent('page');await p.getByRole('button',{name:'Open in new tab ↗',exact:true}).click();const popup=await popupPromise;await popup.waitForURL('https://tranche-fixture.invalid/deny');await popup.getByRole('heading',{name:'Denied frame fixture'}).waitFor();await popup.close();await p.getByRole('button',{name:'Return to world',exact:true}).click();assert.equal(await p.locator('iframe.embedded-frame').count(),0);pass('Deny-header frame keeps an always-visible new-tab fallback; fallback and Return to world work without a provider claim');
 // Delete the sounding item through normal builder controls; runtime must stop it.
 await p.locator('#dock-build').click();await selectItem('Actions acceptance board');await p.getByRole('button',{name:'Delete',exact:true}).click();await p.waitForFunction(()=>document.querySelectorAll('.world-audio-row').length===0);await save();await p.getByRole('button',{name:'Close editor',exact:true}).click();pass('Deleting the sounding item through the builder cleans up its native audio controls');
 // Undo preserves the authored item, then its travel action exercises room cleanup.
 await p.locator('#dock-build').click();await p.getByRole('button',{name:'Undo',exact:true}).click();await save();await p.getByRole('button',{name:'Close editor',exact:true}).click();await activate('Play room tone');await p.getByRole('button',{name:'Pause Native local tone',exact:true}).waitFor();await activate('Open fixture panel');await p.frameLocator('iframe.embedded-frame').getByRole('heading',{name:'Allowed frame fixture'}).waitFor();await p.locator('#game').focus();await openItem();await p.locator('#dialog-actions').getByRole('button',{name:'Travel to second room',exact:true}).click();await p.waitForFunction(()=>__universe.getState().room.id==='actions-other');assert.equal(await p.locator('iframe.embedded-frame').count(),0);assert.equal(await p.locator('.world-audio-row').count(),0);await screenshot('room-cleanup');pass('Actual travel action clears sound and iframe resources from the old room');
 assert.deepEqual(errors,[]);pass('No uncaught browser runtime exceptions');assert.deepEqual(failures,[],'All acceptance checks must pass');
}catch(error){if(!failures.some(f=>error.message.includes('All acceptance checks')))failures.push({name:'combined actions flow',error:error.stack});console.error(error);await screenshot('failure').catch(()=>{});process.exitCode=1;}
finally{await writeFile('evidence/tranche-actions.json',JSON.stringify({buildSha256,checks,failures,errors,consoleErrors,requests,mediaEvents,limitations:['Local standalone authority only; no live-host or security testing','HTTPS fixture response bytes intercepted locally; no real provider embedding or authentication claim','Native Chromium Audio, not physical-device/Safari/Firefox certification','Read-only __universe diagnostics; all scene authoring and activation through actual UI']},null,2));await context.close();await browser.close();await app.close()}
