/** Normal full-world 3D resident-handle acceptance. No scene mutation helpers. */
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
const dist=process.env.UNIVERSE_TRANCHE_DIST||new URL('../dist',import.meta.url).pathname,buildSha256=createHash('sha256').update(await readFile(join(dist,'main.js'))).digest('hex');
const scene={version:1,theme:'garden',bounds:{width:32,depth:26},spawn:{x:0,z:0},objects:[],areas:[]};
const app=createGameServer({dist,seeds:[{id:'bot-handle-world',name:'Resident handle fixture world',rooms:[{id:'bot-handle-room',name:'Resident 3D handle room',scene}]}],questsEnabled:false});
const {port}=await app.listen(0),base=`http://127.0.0.1:${port}`,browser=await launch(),ctx=await browser.newContext({viewport:{width:1440,height:950},reducedMotion:'reduce'}),p=await ctx.newPage();p.setDefaultTimeout(60000);
const checks=[],failures=[],errors=[],consoleErrors=[],drags=[],createRequests=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
p.on('request',request=>{if(request.method()==='POST'&&new URL(request.url()).pathname==='/api/rooms/bot-handle-room/bots')createRequests.push({method:request.method(),path:new URL(request.url()).pathname});});
const pass=(name,details={})=>{checks.push({name,status:'passed',...details});console.log('PASS',name)};
const field=name=>p.locator(`[data-bot-field="${name}"]`);
const home=async()=>({x:Number(await field('spawn.x').inputValue()),z:Number(await field('spawn.z').inputValue())});
const waypoint=async i=>({x:Number(await field(`waypoints.${i}.x`).inputValue()),z:Number(await field(`waypoints.${i}.z`).inputValue())});
async function catalog(){const response=await p.request.get(base+'/api/rooms/bot-handle-room/bots');assert.equal(response.status(),200);return(await response.json()).bots;}
async function shot(name){await p.screenshot({path:`evidence/tranche-bots-${name}.png`})}
async function point(x,z,y=0){const q=await p.evaluate(({x,z,y})=>__universe.getScreenPoint(x,z,y),{x,z,y}),panel=await p.locator('.resident-panel').boundingBox();assert(q&&q.x>130&&q.x<panel.x-5&&q.y>100&&q.y<850,'3D handle must stay on visible world ground: '+JSON.stringify({q,panel}));return q}
async function beginDrag(start,end,y){const from=await point(start.x,start.z,y),to=await point(end.x,end.z);drags.push({start,end,from,to});await p.mouse.move(from.x,from.y);await p.mouse.down();await p.mouse.move(to.x,to.y,{steps:8})}
try{
 await mkdir('evidence',{recursive:true});await p.goto(base+'/?room=bot-handle-room',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe);await p.getByPlaceholder('Your name').fill('Resident UI owner');await p.getByRole('button',{name:'Enter Universe'}).click();await p.waitForFunction(()=>__universe.getState().ready);await p.locator('#manage-bots').click();await p.getByTestId('bot-create').click();await field('name').fill('Pointer patrol guide');await field('name').press('Tab');await p.waitForFunction(()=>__universe.getCamera().viewportWidth===1&&__universe.getCamera().framing.status==='framed'&&Math.abs(__universe.getCamera().framing.offset.x-__universe.getCamera().framing.targetOffset.x)<1);await p.waitForTimeout(350);await shot('new-preview');
 const initial=await home(),target={x:initial.x+1,z:initial.z+1};await beginDrag(initial,target,1.1);assert.deepEqual(await home(),initial,'Home fields must not change while pointer is held');await shot('home-drag-preview');await p.mouse.up();await p.waitForFunction(expected=>{const value=n=>Number(document.querySelector(`[data-bot-field="${n}"]`).value);return value('spawn.x')===expected.x&&value('spawn.z')===expected.z},target);pass('Actual 3D home drag previews without field mutation, then commits only on pointer release',{initial,target});
 assert.deepEqual(await catalog(),[]);assert.deepEqual(await p.evaluate(()=>__universe.getState().bots),[]);assert.equal(createRequests.length,0);assert.equal(await p.getByRole('button',{name:'Close residents',exact:true}).isVisible(),true);await p.getByRole('button',{name:'Close residents',exact:true}).click();await p.getByTestId('bot-editor').waitFor({state:'hidden'});await p.waitForFunction(()=>history.state?.surface!=='bots');assert.deepEqual(await catalog(),[],'Closing a new local draft must not create a server resident');assert.deepEqual(await p.evaluate(()=>__universe.getState().bots),[],'World must still have no residents');assert.equal(await p.locator('[data-bot-id]').count(),0);assert.equal(createRequests.length,0,'Normal Close must never send a create request');await shot('closed-local-draft');pass('Closing the named, moved new draft sends no Create and leaves server catalog and world empty');
 await p.locator('#manage-bots').click();await field('name').waitFor();assert.equal(await field('name').inputValue(),'Pointer patrol guide');assert.deepEqual(await home(),target);assert.equal(await p.getByTestId('bot-save').innerText(),'Create resident');assert.equal(await p.getByTestId('bot-save').isEnabled(),true);assert.deepEqual(await catalog(),[]);assert.equal(createRequests.length,0);await p.waitForFunction(()=>__universe.getCamera().viewportWidth===1&&__universe.getCamera().framing.status==='framed'&&Math.abs(__universe.getCamera().framing.offset.x-__universe.getCamera().framing.targetOffset.x)<1);await shot('recovered-local-draft');pass('Reopening the same room restores the exact unsaved name and home without creating a resident');

 await field('behavior').selectOption('patrol');await p.getByTestId('bot-add-waypoint').click();await field('waypoints.0.x').fill(String(target.x+2));await field('waypoints.0.z').fill(String(target.z+1));await p.getByTestId('bot-add-waypoint').click();await field('waypoints.1.x').fill(String(target.x));await field('waypoints.1.z').fill(String(target.z+2));await field('pauseMs').fill('200');await field('pauseMs').press('Tab');const wp=await waypoint(0),wpTarget={x:wp.x-.5,z:wp.z+1};
 await beginDrag(wp,wpTarget,.25);assert.deepEqual(await waypoint(0),wp,'Waypoint fields must remain unchanged during native preview');await p.keyboard.press('Escape');await p.mouse.up();assert.deepEqual(await waypoint(0),wp);assert.equal(await p.getByTestId('bot-editor').isVisible(),true);await shot('cancelled-waypoint-drag');pass('Escape cancels an in-progress native waypoint drag without closing or modifying the resident draft');
 await beginDrag(wp,wpTarget,.25);assert.deepEqual(await waypoint(0),wp);await p.mouse.up();await p.waitForFunction(expected=>{const value=n=>Number(document.querySelector(`[data-bot-field="${n}"]`).value);return value('waypoints.0.x')===expected.x&&value('waypoints.0.z')===expected.z},wpTarget);const route=[await waypoint(0),await waypoint(1)];await shot('committed-route');pass('Native 3D waypoint handle commits snapped coordinates only at release',{route});
 const panStart=await point(target.x,target.z,1.1);await p.mouse.move(panStart.x,panStart.y);await p.mouse.down({button:'middle'});await p.mouse.move(panStart.x+25,panStart.y+10,{steps:5});await p.mouse.up({button:'middle'});const manualBeforeSave=await p.evaluate(()=>__universe.getCamera());assert.equal(manualBeforeSave.framingMode,'manual');
 await p.getByTestId('bot-save').click();await p.waitForFunction(()=>__universe.getState().bots.some(b=>b.name==='Pointer patrol guide'));const manualAfterSave=await p.evaluate(()=>__universe.getCamera());assert.equal(manualAfterSave.framingMode,'manual');assert.deepEqual(manualAfterSave.target,manualBeforeSave.target);assert.deepEqual(manualAfterSave.framing.offset,manualBeforeSave.framing.offset);pass('Committing a new resident identity does not steal native manual pan or frozen projection framing');await p.waitForFunction(()=>document.querySelector('[data-testid="bot-save"]').disabled);const id=await p.evaluate(()=>__universe.getState().bots.find(b=>b.name==='Pointer patrol guide').id);const createdCatalog=await catalog();assert.equal(createdCatalog.length,1);assert.equal(createdCatalog[0].id,id);assert.equal(createRequests.length,1,'Explicit Create must persist exactly once');assert.equal(await p.evaluate(()=>__universe.getState().bots.length),1);pass('Explicit Create persists exactly one resident after local draft recovery',{id,createRequests:createRequests.length});const saved=await p.request.get(base+'/api/rooms/bot-handle-room/bots/'+id);assert.equal(saved.status(),200);const record=(await saved.json()).bot;assert.deepEqual(record.spawn,target);assert.deepEqual(record.waypoints,route);assert.equal(record.behavior,'patrol');assert.equal(await p.evaluate(()=>__universe.getState().people.some(b=>b.name==='Pointer patrol guide')),false);await p.getByRole('button',{name:'Save and close residents',exact:true}).click();await p.getByTestId('bot-editor').waitFor({state:'hidden'});await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.__universe?.getState().ready);await p.locator('#manage-bots').click();await p.locator(`[data-bot-id="${id}"]`).click();assert.deepEqual(await home(),target);assert.deepEqual([await waypoint(0),await waypoint(1)],route);assert.equal(await field('behavior').inputValue(),'patrol');assert.equal((await catalog()).length,1);assert.equal(createRequests.length,1,'Saved close and reload must not create a duplicate');await shot('saved-reloaded-route');pass('Saved native home and ordered route survive real reload and reopen, with resident separate from human presence',{id});
 assert.deepEqual(errors,[]);pass('No uncaught browser errors in native-handle acceptance');
}catch(error){failures.push({name:'native bot handle flow',error:error.stack});console.error(error);await shot('failure').catch(()=>{});process.exitCode=1}
finally{await writeFile('evidence/tranche-bots.json',JSON.stringify({buildSha256,checks,failures,errors,consoleErrors,drags,createRequests,limitations:['Local native3D renderer and local authority only','Real pointer drags on the world canvas, not mini-plan or injected scene helpers','Headless Chromium/SwiftShader; no physical-device or production/provider claim']},null,2));await ctx.close();await browser.close();await app.close()}
