/** Real server, synthetic owner/editor, real SSE and deliberate response ordering. */
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {emptyScene} from '../src/worlds.js';
import {clientProtocolHeaders} from '../src/client-protocol.js';
const out='evidence/workshop-collaboration';await mkdir(out,{recursive:true});
const app=createGameServer({seeds:[{id:'universe',name:'Workshop test',rooms:[{id:'commons',name:'Collaboration studio',scene:emptyScene()}]}],dist:new URL('../dist',import.meta.url).pathname}),{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;
let ownerCookie='',browser,page;const checks=[],errors=[];const check=name=>{checks.push(name);console.log('PASS',name);};
async function owner(path,method='GET',body){const response=await fetch(base+path,{method,headers:clientProtocolHeaders({Cookie:ownerCookie,...(body?{'Content-Type':'application/json'}:{})}),body:body?JSON.stringify(body):undefined});if(response.headers.get('set-cookie'))ownerCookie=response.headers.get('set-cookie').split(';')[0];const data=await response.json();assert(response.ok,JSON.stringify({path,status:response.status,data}));return data;}
try{
 await owner('/api/session','POST',{name:'Workshop owner fixture'});await owner('/api/rooms/commons/join','POST',{});
 browser=await launch();const context=await browser.newContext({viewport:{width:1280,height:900}});await context.route('**/*',route=>route.request().url().startsWith(base+'/')||route.request().url().startsWith('data:')?route.continue():route.abort());page=await context.newPage();page.setDefaultTimeout(35000);page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByPlaceholder('Your name').fill('Workshop editor fixture');await page.locator('#join-button').click();await page.waitForFunction(()=>window.__universe?.getState().ready);const editorId=await page.evaluate(()=>__universe.getState().user.id);await owner('/api/rooms/commons/members/'+editorId,'PUT',{role:'editor'});await page.locator('#dock-build').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('#dock-build').disabled);
 await page.locator('#dock-build').click();await page.getByRole('button',{name:'Furniture workshop',exact:true}).click();const root=page.locator('#furniture-workshop');await root.waitFor({state:'visible'});await root.getByRole('button',{name:'Start a chair',exact:true}).click();await root.getByRole('button',{name:'Save furniture',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.workshop-save-state').textContent.includes('Saved in this room'));
 const original=(await owner('/api/rooms/commons/furniture')).assets[0];await root.getByLabel('Furniture name',{exact:true}).fill('My concurrent draft');await root.getByLabel('Furniture name',{exact:true}).press('Tab');
 let release,captured;const blocked=new Promise(resolve=>captured=resolve),ready=new Promise(resolve=>release=resolve);let delayed=false;await page.route('**/api/rooms/commons/furniture',async route=>{if(route.request().method()==='GET'&&!delayed){delayed=true;const response=await route.fetch();captured();await ready;await route.fulfill({response});}else await route.continue();});
 await root.getByRole('button',{name:'Refresh furniture',exact:true}).click();await blocked;const definition=structuredClone(original.definition);definition.asset.name='Peer revised chair';await owner('/api/rooms/commons/furniture/'+original.assetId,'PUT',{definition,revision:1,operationId:crypto.randomUUID()});await page.waitForTimeout(250);release();await root.getByRole('button',{name:'Open Peer revised chair',exact:true}).waitFor();await page.unroute('**/api/rooms/commons/furniture');assert.equal(await root.getByLabel('Furniture name',{exact:true}).inputValue(),'My concurrent draft');check('Remote revision event queues a fresh catalog read behind an older response without replacing dirty edits');
 await root.getByRole('button',{name:'Save furniture',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.workshop-status').textContent.includes('Furniture changed'));assert.equal(await root.getByLabel('Furniture name',{exact:true}).inputValue(),'My concurrent draft');assert.equal((await owner('/api/rooms/commons/furniture')).assets[0].revision,2);check('Stale source save is rejected by CAS and keeps the editor draft intact');
 await root.getByRole('button',{name:'Save as new copy',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.workshop-save-state').textContent.includes('Saved in this room'));assert.equal((await owner('/api/rooms/commons/furniture')).assets.length,2);check('Save as new copy resolves a source conflict with separate authoritative identity');
 await root.getByLabel('Furniture name',{exact:true}).fill('Keep after permission change');await root.getByLabel('Furniture name',{exact:true}).press('Tab');const local=await page.evaluate(()=>__universe.getWorkshopPreview().document);
 await owner('/api/rooms/commons/members/'+editorId,'DELETE');await page.waitForFunction(()=>document.querySelector('#furniture-workshop button.primary').disabled);assert.deepEqual(await page.evaluate(()=>__universe.getWorkshopPreview().document),local);assert.equal(await root.isVisible(),true);check('Role revocation disables publishing immediately and retains exportable local geometry');
 const downloadReady=page.waitForEvent('download');await root.getByRole('button',{name:'Save JSON',exact:true}).click();const downloaded=await downloadReady;assert.deepEqual(JSON.parse(await readFile(await downloaded.path(),'utf8')),local);
 await owner('/api/rooms/commons','PATCH',{public:false});await page.waitForFunction(()=>!__universe.getState().ready);await root.waitFor({state:'hidden'});const recovered=page.waitForEvent('download');await page.getByRole('button',{name:'Export furniture draft',exact:true}).click();assert.deepEqual(JSON.parse(await readFile(await(await recovered).path(),'utf8')),local);check('Full room access loss disposes the preview and offers the exact draft in recovery');
 assert.deepEqual(errors,[]);check('No browser exceptions during collaboration, stale-response and permission-loss flows');
}catch(error){console.error(error);errors.push(error.stack);process.exitCode=1;await page?.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});}
finally{await writeFile(out+'/results.json',JSON.stringify({checks,errors},null,2));await browser?.close();await app.close();}
