/** Actual game and native browser touch events with a synthetic account. */
import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {launch} from '../scripts/browser.mjs';
import {createGameServer} from '../server/app.mjs';
import {emptyScene} from '../src/worlds.js';
const out='evidence/workshop-touch';await mkdir(out,{recursive:true});
const app=createGameServer({seeds:[{id:'universe',name:'Workshop test',rooms:[{id:'commons',name:'Touch studio',scene:emptyScene()}]}],dist:new URL('../dist',import.meta.url).pathname}),{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;
let browser,page;const errors=[],checks=[];const check=name=>{checks.push(name);console.log('PASS',name);};
try{
 browser=await launch();const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});await context.route('**/*',route=>route.request().url().startsWith(base+'/')||route.request().url().startsWith('data:')?route.continue():route.abort());page=await context.newPage();page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByPlaceholder('Your name').fill('Touch fixture maker');await page.locator('#join-button').click();await page.waitForFunction(()=>window.__universe?.getState().ready&&__universe.getStats().presentation.drawnFrames>2);
 async function open(){await page.locator('#dock-build').click();if(!await page.getByRole('button',{name:'Furniture workshop',exact:true}).isVisible())await page.getByRole('button',{name:'More build tools',exact:true}).click();await page.getByRole('button',{name:'Furniture workshop',exact:true}).click();await page.locator('#furniture-workshop').waitFor({state:'visible'});}
 await open();const root=page.locator('#furniture-workshop'),canvas=root.locator('canvas'),cdp=await context.newCDPSession(page);
 const count=()=>root.getAttribute('data-parts');
 async function touch(type,touches){await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:touches.map(([x,y,id=1])=>({x,y,id,radiusX:5,radiusY:5,force:1}))});}
 async function center(){await canvas.scrollIntoViewIfNeeded();const r=await canvas.boundingBox();return{x:r.x+r.width*.5,y:r.y+r.height*.5};}
 await root.getByRole('button',{name:'Box',exact:true}).click();let p=await center();await touch('touchStart',[[p.x,p.y]]);assert.equal(await count(),'0');await touch('touchCancel',[]);assert.equal(await count(),'0');check('Native touch preview waits for release and cancellation adds no part');
 await root.getByRole('button',{name:'Box',exact:true}).click();p=await center();await touch('touchStart',[[p.x,p.y]]);await touch('touchEnd',[]);await page.waitForFunction(()=>document.querySelector('#furniture-workshop').dataset.parts==='1');check('Native DPR2 touch release places a real box');
 await root.getByLabel('Position Y',{exact:true}).fill('0.77');await root.getByLabel('Position Y',{exact:true}).press('Tab');await root.getByRole('button',{name:'X +',exact:true}).click();assert.equal(await root.getByLabel('Position Y',{exact:true}).inputValue(),'0.77');await root.getByRole('button',{name:'Undo',exact:true}).click();await root.getByRole('button',{name:'Redo',exact:true}).click();assert.equal(await root.getByLabel('Position Y',{exact:true}).inputValue(),'0.77');check('Touch nudge and undo/redo preserve off-grid height');
 await root.getByRole('button',{name:'Sphere',exact:true}).click();p=await center();await touch('touchStart',[[p.x,p.y,1]]);await touch('touchStart',[[p.x,p.y,1],[p.x+40,p.y+30,2]]);await touch('touchEnd',[]);assert.equal(await count(),'1');check('A second finger cancels pending Edit placement');
 await root.getByRole('button',{name:'Camera',exact:true}).click();const before=await root.getAttribute('data-dirty');p=await center();await touch('touchStart',[[p.x-30,p.y,1],[p.x+30,p.y,2]]);await touch('touchMove',[[p.x-65,p.y-10,1],[p.x+65,p.y+10,2]]);await touch('touchEnd',[]);assert.equal(await count(),'1');assert.equal(await root.getAttribute('data-dirty'),before);check('Native two-finger Camera pinch never edits parts');
 await root.getByRole('button',{name:'Edit',exact:true}).click();await canvas.scrollIntoViewIfNeeded();await page.waitForTimeout(100);const initialDrag=await page.evaluate(()=>__universe.getWorkshopPreview());let picked=initialDrag.parts[0];await touch('touchStart',[[picked.x,picked.y]]);await touch('touchMove',[[picked.x+35,picked.y+15]]);await touch('touchCancel',[]);assert.deepEqual((await page.evaluate(()=>__universe.getWorkshopPreview())).document,initialDrag.document);check('Native mesh drag cancellation restores every component transform');picked=(await page.evaluate(()=>__universe.getWorkshopPreview())).parts[0];await touch('touchStart',[[picked.x,picked.y]]);await touch('touchMove',[[picked.x+25,picked.y+8]]);await touch('touchMove',[[picked.x+45,picked.y+18]]);await touch('touchEnd',[]);const committedDrag=await page.evaluate(()=>__universe.getWorkshopPreview());assert.notDeepEqual(committedDrag.document.components[0].position,initialDrag.document.components[0].position);assert.equal(committedDrag.document.components[0].position[1],.77);assert.equal(committedDrag.undo,initialDrag.undo+1);await root.getByRole('button',{name:'Undo',exact:true}).click();assert.deepEqual((await page.evaluate(()=>__universe.getWorkshopPreview())).document,initialDrag.document);check('A native multipart drag commits exactly one undo operation and preserves height');
 for(const [width,height]of [[320,700],[390,844],[844,390],[1024,768]]){await page.setViewportSize({width,height});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const small=await root.locator('button').evaluateAll(nodes=>nodes.filter(n=>!n.hidden&&n.getClientRects().length).filter(n=>{const r=n.getBoundingClientRect();return r.width<47.9||r.height<47.9;}).map(n=>({text:n.textContent,w:n.offsetWidth,h:n.offsetHeight})));assert.deepEqual(small,[]);await page.screenshot({path:`${out}/${width}x${height}.png`,fullPage:true});}check('320/390/844/1024 layouts have no horizontal overflow and coarse controls are at least 48px');
 await page.setViewportSize({width:390,height:844});const downloaded=page.waitForEvent('download');await root.getByRole('button',{name:'Save JSON',exact:true}).click();const download=await downloaded,text=await readFile(await download.path(),'utf8'),doc=JSON.parse(text);assert.equal(doc.components.length,1);assert.equal(doc.components[0].position[1],.77);await writeFile(out+'/touch-composition.json',text);
 await root.locator('input[type=file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"bad":true}')});assert.equal(await count(),'1');assert.match(await root.locator('.workshop-status').textContent(),/missing|unknown|format|Composition/i);check('Malformed import leaves the existing editable composition intact');
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__universe?.getState().ready);await open();await root.locator('input[type=file]').setInputFiles({name:'saved.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.waitForFunction(()=>document.querySelector('#furniture-workshop').dataset.parts==='1');const again=page.waitForEvent('download');await root.getByRole('button',{name:'Save JSON',exact:true}).click();const restored=JSON.parse(await readFile(await(await again).path(),'utf8'));assert.deepEqual(restored,doc);check('Downloaded JSON survives full reload and exact editable reimport');
 await root.getByRole('button',{name:'Close workshop',exact:true}).click();await root.waitFor({state:'hidden'});await page.goForward();await root.waitFor({state:'visible'});await root.getByRole('button',{name:'Close workshop',exact:true}).click();await root.waitFor({state:'hidden'});check('Repeated history reopen/close disposes and recreates the preview without losing same-room draft');
 assert.deepEqual(errors,[]);check('No browser exceptions across native touch and recovery journeys');
}catch(error){console.error(error);errors.push(error.stack);process.exitCode=1;await page?.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});}
finally{await writeFile(out+'/results.json',JSON.stringify({checks,errors},null,2));await browser?.close();await app.close();}
