/** Real game, synthetic users, loopback-only network; no live account data. */
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createGameServer} from '../server/app.mjs';
import {seedWorlds} from '../src/worlds.js';
import {launch} from '../scripts/browser.mjs';
const out='evidence/workshop';await mkdir(out,{recursive:true});
const app=createGameServer({seeds:seedWorlds,dist:new URL('../dist',import.meta.url).pathname}),{port}=await app.listen(0),base=`http://127.0.0.1:${port}`;
const errors=[],checks=[];let browser,page;
const check=name=>{checks.push(name);console.log('PASS',name);};
try{
 browser=await launch();const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',route=>route.request().url().startsWith(base+'/')||route.request().url().startsWith('data:')?route.continue():route.abort());
 page=await context.newPage();page.setDefaultTimeout(45000);page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.getByPlaceholder('Your name').fill('Workshop fixture maker');await page.locator('#join-button').click();
 await page.waitForFunction(()=>window.__universe?.getState().ready&&__universe.getStats().presentation.drawnFrames>2);
 await page.locator('#dock-build').click();await page.getByRole('button',{name:'Furniture workshop',exact:true}).click();
 const root=page.locator('#furniture-workshop');await root.waitFor({state:'visible'});await page.getByRole('button',{name:'Start a chair',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#furniture-workshop').dataset.parts==='8');await page.screenshot({path:out+'/01-chair-desktop.png'});assert.equal(await root.locator('canvas').isVisible(),true);assert.equal((await page.evaluate(()=>__universe.getStats())).presentation.suspended,true);check('Actual workshop opens over suspended world and builds an editable eight-part chair');
 await root.getByRole('button',{name:'Ungroup parts',exact:true}).click();const first=root.locator('[data-part-id]').first();await first.click();await root.getByLabel('Part name',{exact:true}).fill('Custom chair seat');await root.getByLabel('Part name',{exact:true}).press('Tab');await root.getByLabel('Size X',{exact:true}).fill('1.4');await root.getByLabel('Size X',{exact:true}).press('Tab');check('Part list selects real chair components and numeric fields edit them');
 await root.getByLabel('Furniture name',{exact:true}).fill('Workshop test chair');await root.getByLabel('Furniture name',{exact:true}).press('Tab');
 let dropped=false;await page.route('**/api/rooms/*/furniture',async route=>{if(route.request().method()==='POST'&&!dropped){dropped=true;await route.fetch();await route.abort('failed');}else await route.continue();});await root.getByRole('button',{name:'Save furniture',exact:true}).click();await root.getByRole('button',{name:'Retry save',exact:true}).waitFor();assert.equal(await root.getByLabel('Furniture name',{exact:true}).isDisabled(),true);await root.getByRole('button',{name:'Retry save',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.workshop-save-state').textContent.includes('Saved in this room'));await page.unroute('**/api/rooms/*/furniture');assert.equal(await root.locator('.workshop-library-card').count(),1);check('Lost save acknowledgement retries the same committed definition exactly once');
 await root.getByRole('button',{name:'Place in room',exact:true}).click();await root.waitFor({state:'hidden'});await page.waitForFunction(()=>__universe.getEditor().tool==='composition'&&!__universe.getStats().presentation.suspended&&!__universe.getStats().presentation.resumePending);
 // Place with keyboard from the genuine editor preview; choose a clear floor location.
 const canvas=page.locator('#game');await canvas.focus();
 await page.waitForTimeout(800);const point=await page.evaluate(()=>__universe.getScreenPoint(2,4,0));await page.mouse.move(point.x,point.y);await page.mouse.click(point.x,point.y);await page.waitForFunction(()=>__universe.getState().scene.objects.some(o=>o.type==='composition'));
 await page.getByRole('button',{name:'Save room',exact:true}).click();await page.waitForFunction(()=>!__universe.getEditor().dirty&&!__universe.getEditor().saving);const firstPlaced=await page.evaluate(()=>__universe.getState().scene.objects.find(o=>o.type==='composition'));assert.equal(firstPlaced.assetRef.revision,1);assert.equal((await page.evaluate(()=>__universe.getStats())).compositions.instances,1);check('Saved chair placed through room editor and rendered as native multipart furniture');
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__universe?.getState().ready&&__universe.getStats().compositions.instances===1);const restored=await page.evaluate(()=>__universe.getState().scene.objects.find(o=>o.type==='composition'));assert.deepEqual(restored,firstPlaced);check('Placed chair and pinned revision survive full page reload');
 await page.locator('#dock-build').click();if(!await page.getByLabel('Search room items',{exact:true}).isVisible())await page.getByRole('button',{name:'＋ Furniture',exact:true}).click();await page.getByLabel('Search room items',{exact:true}).fill('Workshop test chair');await page.locator('.editor-search-results').getByRole('button',{name:'Workshop test chair',exact:true}).click();await page.waitForFunction(id=>__universe.getEditor().selected===id,restored.id);await page.getByRole('button',{name:'Edit furniture source',exact:true}).click();await root.waitFor({state:'visible'});await root.locator('[data-part-id]').first().click();await root.getByLabel('Size X',{exact:true}).fill('1.6');await root.getByLabel('Size X',{exact:true}).press('Tab');await root.getByRole('button',{name:'Save furniture',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.workshop-save-state').textContent.includes('Revision 2')&&document.querySelector('.workshop-save-state').textContent.includes('Saved'));assert.equal((await page.evaluate(()=>__universe.getState().scene.objects.find(o=>o.type==='composition'))).assetRef.revision,1);check('Editing the saved source creates revision 2 without silently changing the placed revision 1');await root.getByRole('button',{name:'Update placed copy',exact:true}).click();await root.waitFor({state:'hidden'});await page.getByRole('button',{name:'Save room',exact:true}).click();await page.waitForFunction(()=>!__universe.getEditor().dirty&&!__universe.getEditor().saving);assert.equal((await page.evaluate(()=>__universe.getState().scene.objects.find(o=>o.type==='composition'))).assetRef.revision,2);check('Explicitly replacing the placed copy saves the new pinned revision');
 await page.getByRole('button',{name:'Furniture workshop',exact:true}).click();await root.waitFor({state:'visible'});await root.getByRole('button',{name:'Start a table',exact:true}).click();await root.getByLabel('Furniture name',{exact:true}).fill('Workshop test table');await root.getByLabel('Furniture name',{exact:true}).press('Tab');await root.getByRole('button',{name:'Save furniture',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.workshop-save-state').textContent.includes('Saved in this room'));check('Table starter saves as a separate five-part composition');
 await page.screenshot({path:out+'/02-table-desktop.png'});
 await root.getByRole('button',{name:'Place in room',exact:true}).click();await root.waitFor({state:'hidden'});await page.waitForTimeout(800);const tablePoint=await page.evaluate(()=>__universe.getScreenPoint(-4,4,0));await page.mouse.click(tablePoint.x,tablePoint.y);await page.waitForFunction(()=>__universe.getState().scene.objects.filter(o=>o.type==='composition').length===2);await page.getByRole('button',{name:'Undo',exact:true}).click();await page.waitForFunction(()=>__universe.getState().scene.objects.filter(o=>o.type==='composition').length===1);await page.getByRole('button',{name:'Redo',exact:true}).click();await page.getByRole('button',{name:'Save room',exact:true}).click();await page.waitForFunction(()=>!__universe.getEditor().dirty&&!__universe.getEditor().saving);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__universe?.getState().ready&&__universe.getStats().compositions.instances===2);check('Table placement supports undo/redo and both chair and table reload with exact revision pins');await page.screenshot({path:out+'/03-world-furniture.png'});
 await page.locator('#dock-build').click();await page.getByRole('button',{name:'Furniture workshop',exact:true}).click();await root.waitFor({state:'visible'});

 await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/04-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);check('390px layout keeps authoring controls within the viewport');
 assert.deepEqual(errors,[]);check('No browser page errors during actual game journeys');
}catch(error){console.error(error);errors.push(error.stack);console.error(await page?.evaluate(()=>({editor:__universe?.getEditor(),toast:document.querySelector('#toast')?.textContent,workshop:document.querySelector('.workshop-status')?.textContent})).catch(()=>null));process.exitCode=1;await page?.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});}
finally{await writeFile(out+'/results.json',JSON.stringify({checks,errors},null,2));await browser?.close();await app.close();}
