/** The expanded Build More sheet owns its hit region above ambient area actions. */
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createGameServer} from '../server/app.mjs';
import {launch} from '../scripts/browser.mjs';
const out='evidence/workshop-hud';await mkdir(out,{recursive:true});
const scene={version:1,theme:'garden',bounds:{width:32,depth:26},spawn:{x:0,z:0},objects:[],areas:[{id:'content',name:'Content',action:'welcome',x:0,z:0,width:20,depth:20,actions:[{id:'open',type:'link',label:'Open content fixture',url:'https://workshop-hud.invalid/',mode:'embed',width:60,closable:true},{id:'wide',type:'link',label:'Open wide content',url:'https://workshop-hud.invalid/wide',mode:'embed',width:90,closable:true},{id:'message',type:'message',label:'Read local message',message:'Local message'}]}]};
const app=createGameServer({seeds:[{id:'hud-world',name:'HUD',rooms:[{id:'hud-room',name:'HUD room',scene}]}],dist:new URL('../dist',import.meta.url).pathname,questsEnabled:false}),{port}=await app.listen(0);let browser,page;const errors=[],checks=[];
const pass=name=>{checks.push(name);console.log('PASS',name);};
async function reachable(locator){await locator.scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const result=await locator.evaluate(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{label:el.getAttribute('aria-label')||el.textContent,hit:el===hit||el.contains(hit),target:hit?.outerHTML.slice(0,250),rect:r.toJSON(),width:innerWidth,height:innerHeight};});assert(result.hit&&result.rect.left>=0&&result.rect.right<=result.width&&result.rect.top>=0&&result.rect.bottom<=result.height,JSON.stringify(result));}
try{
 browser=await launch();page=await browser.newPage({viewport:{width:1440,height:950},deviceScaleFactor:2});page.setDefaultTimeout(30000);page.on('pageerror',error=>errors.push(error.message));await page.route('https://workshop-hud.invalid/**',route=>route.fulfill({contentType:'text/html',body:'<h1>Local fixture</h1>'}));await page.goto(`http://127.0.0.1:${port}/?room=hud-room`,{waitUntil:'domcontentloaded'});await page.getByPlaceholder('Your name').fill('Workshop HUD fixture');await page.locator('#join-button').click();await page.waitForFunction(()=>window.__universe?.getState().ready);
 await page.addStyleTag({content:'#app button,#app input,#app textarea {font-size:24px !important}'});await page.getByRole('button',{name:'Open content fixture',exact:true}).click();await page.locator('.embedded-panel').waitFor();await page.locator('#dock-build').click();await page.waitForFunction(()=>document.querySelector('#editor').dataset.compact==='true');await page.getByRole('button',{name:'More build tools',exact:true}).click();
 for(const name of ['Furniture workshop','Custom images','Undo','Redo','⌫ Erase'])await reachable(page.getByRole('button',{name,exact:true}));await page.screenshot({path:out+'/enlarged-more.png'});pass('Workshop and existing More actions are native hit targets with enlarged text and embedded content');
 await page.getByRole('button',{name:'Close more build tools',exact:true}).click();for(const name of ['Open content fixture','Open wide content','Read local message','Return to world'])await reachable(page.getByRole('button',{name,exact:true}));pass('Closing More restores native ambient content actions without disabling them');assert.deepEqual(errors,[]);
}catch(error){console.error(error);errors.push(error.stack);process.exitCode=1;await page?.screenshot({path:out+'/failure.png'}).catch(()=>{});}
finally{await writeFile(out+'/results.json',JSON.stringify({checks,errors},null,2));await browser?.close();await app.close();}
