import test from 'node:test';import assert from 'node:assert/strict';import {seedWorlds,emptyScene,movePlayer,canStand,findPath,nearestWalkable,contains,collisionBox,pathDirection} from '../src/worlds.js';
test('MOVE-01: seeded arrivals are walkable and distinct rooms retain identity',()=>{const ids=new Set;for(const w of seedWorlds)for(const r of w.rooms){assert(!ids.has(r.id));ids.add(r.id);assert(canStand(r.scene,r.scene.spawn.x,r.scene.spawn.z));}});
test('MOVE-02: collision prevents tunneling and permits sliding',()=>{const s=emptyScene();s.objects=[{id:'wall',type:'wall',x:0,z:0,width:8,depth:.3,rotation:0}];const p=movePlayer(s,{x:0,z:3},0,-20);assert(p.z>.4);const slide=movePlayer(s,{x:0,z:1},3,-3);assert(slide.x>2);assert(slide.z>.4);});
test('MOVE-03: rotated furniture uses rotated collision footprint',()=>{const b=collisionBox({type:'table',x:0,z:0,rotation:90});assert.equal(b.width,1.3);assert.equal(b.depth,2.4);});
test('MOVE-04: room boundary blocks repeated walking',()=>{const s=emptyScene();const p=movePlayer(s,{x:0,z:0},100,-100);assert(p.x<=15.7);assert(p.z>=-12.7);});
test('MOVE-05: bounded A* finds navigable path around solid items',()=>{const s=emptyScene();s.objects=[{id:'wall',type:'wall',x:0,z:0,width:8,depth:.3,rotation:0}];const path=findPath(s,{x:0,z:3},{x:0,z:-3});assert(path.length>10);for(const p of path)assert(canStand(s,p.x,p.z));assert.deepEqual(path.at(-1),{x:0,z:-3});assert.deepEqual(findPath(s,{x:0,z:3},{x:0,z:0}),[]);});
test('EDIT-13: moved boundary reconciles stationary inside predicate',()=>{const a={x:0,z:0,width:4,depth:4};assert(contains(a,1,1));a.x=10;assert(!contains(a,1,1));});
test('MOVE-06: blocked arrival finds safe nearby landing',()=>{const s=emptyScene();s.objects=[{id:'table',type:'table',x:0,z:0}];const p=nearestWalkable(s,{x:0,z:0});assert(canStand(s,p.x,p.z));});

test('MOVE-07: full click path advances through every waypoint around furniture',()=>{const scene=seedWorlds[0].rooms[0].scene;let position={x:0,z:7};const path=findPath(scene,position,{x:-10,z:-6});assert(path.length>20);for(let i=0;i<2000&&path.length;i++){const d=pathDirection(position,path);position=movePlayer(scene,position,d.x*3.9*.016,d.z*3.9*.016);}assert.equal(path.length,0);assert(Math.hypot(position.x+10,position.z+6)<.14);});
