import {randomUUID} from 'node:crypto';
import * as v from './validation.mjs';
import {slugify} from './hierarchy-store.mjs';
import {validatePersonalScene} from './personal-area-store.mjs';
const ROLES=['member','editor','admin'];
const ID='([A-Za-z0-9_-]+)';
export function createHierarchyService({store,now,body,send,changed,emitUser}){
  const deny=()=>v.fail(404,'PLACE_NOT_FOUND','Place is unavailable');
  function activeUniverse(id,userId,manage=false){const u=store.universeRow(id);if(u.archived_at||!store.canSeeUniverse(u,userId))deny();if(manage&&u.owner_id!==userId)v.fail(403,'UNIVERSE_OWNER_REQUIRED','Only the universe owner can change this place');return u;}
  function activeWorld(id,userId,manage=false){const w=store.worldRow(id);if(!store.canSeeWorld(w,userId))deny();if(manage&&!['owner','admin'].includes(store.worldRole(w,userId)))v.fail(403,'WORLD_ADMIN_REQUIRED','Only a universe owner or world admin can manage members');return w;}
  function immutable(b,extra=[]){for(const field of ['ownerId','owner_id','featured','id','role','tags','archivedAt',...extra])if(Object.hasOwn(b,field))v.fail(400,'IMMUTABLE_FIELD',`${field} cannot be set here`);}
  function fields(b,old=null){immutable(b);const name=b.name===undefined&&old?old.name:v.text(b.name,'name',120);const slug=b.slug===undefined?(old?.slug||slugify(name)):v.text(b.slug,'slug',64);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))v.fail(400,'INVALID_SLUG','Use lowercase letters, numbers and single hyphens');const description=b.description===undefined?(old?.description||''):typeof b.description==='string'&&b.description.length<=3000?b.description.trim():v.fail(400,'INVALID_DESCRIPTION','Description must be text of at most 3000 characters');let thumbnail=b.thumbnail===undefined?(old?.thumbnail||''):b.thumbnail??'';if(typeof thumbnail!=='string'||thumbnail.length>2000||thumbnail&&!(thumbnail.startsWith('/assets/')&&!thumbnail.includes('..')&&!thumbnail.includes('\\')||/^https:\/\//.test(thumbnail)))v.fail(400,'INVALID_THUMBNAIL','Use an HTTPS image URL or a built-in /assets path');if(thumbnail){try{const u=new URL(thumbnail,'https://local.invalid');if(u.username||u.password)v.fail(400,'INVALID_THUMBNAIL');}catch(e){if(e.status)throw e;v.fail(400,'INVALID_THUMBNAIL');}}const isPublic=b.public===undefined?(old?!!old.public:true):v.boolean(b.public,'public');return{name,slug,description,thumbnail,public:+isPublic};}
  function roleTags(b){const role=b.role===undefined?'member':v.oneOf(b.role,ROLES,'role');const tags=b.tags===undefined?[]:b.tags;if(!Array.isArray(tags)||tags.length>30)v.fail(400,'INVALID_TAGS','Use up to 30 world-local custom tags');const clean=[...new Set(tags.map(x=>v.text(x,'tag',40)))].sort();if(clean.some(t=>['owner','admin','editor','moderator','member','guest'].includes(t.toLowerCase())))v.fail(400,'RESERVED_TAG','Set permission roles with the role field, not custom tags');return{role,tags:JSON.stringify(clean)};}
  function cas(b,row,current){if(b.metadataRevision!==undefined){v.integer(b.metadataRevision,'metadataRevision');if(b.metadataRevision!==row.metadata_revision)v.fail(409,'METADATA_CONFLICT','This place changed. Refresh before saving.',{current});}}
  function unique(table,slug,parent,id=null){const parentField=table==='worlds'?'universe_id':table==='rooms'?'world_id':null;const found=parentField?store.get(`SELECT id FROM ${table} WHERE ${parentField}=? AND slug=?`,parent,slug):store.get(`SELECT id FROM ${table} WHERE slug=?`,slug);if(found&&found.id!==id)v.fail(409,'SLUG_TAKEN','This slug is already used in this place, including archived places');}
  function retry(userId,scope,b,payload){if(b.clientOperationId===undefined)return null;const op=v.id(b.clientOperationId,'clientOperationId');const prior=store.get('SELECT * FROM place_operations WHERE user_id=? AND scope=? AND operation_id=?',userId,scope,op);if(prior&&prior.payload!==JSON.stringify(payload))v.fail(409,'OPERATION_REUSED','This operation ID was already used for different content');return prior;}
  function remember(userId,scope,b,payload,id){if(b.clientOperationId!==undefined)store.run('INSERT INTO place_operations(user_id,scope,operation_id,payload,result_id) VALUES(?,?,?,?,?)',userId,scope,v.id(b.clientOperationId),JSON.stringify(payload),id);}
  function protectMember(w,m,nextRole=null){if(m.user_id===w.universe_owner&&nextRole!=='admin')v.fail(409,'PROTECTED_OWNER','The universe owner must remain a world admin');if(m.role==='admin'&&nextRole!=='admin'&&store.get("SELECT COUNT(*) AS n FROM world_members WHERE world_id=? AND role='admin'",w.id).n<=1)v.fail(409,'LAST_MANAGER','Keep at least one world admin');}
  function expire(){store.run("UPDATE world_invitations SET status='expired',updated_at=? WHERE status='pending' AND expires_at<=?",now(),now());}
  function invitation(row){const w=store.worldRow(row.world_id);const publicUser=id=>{const u=store.user(id);return{id:u.id,name:u.name,username:u.username};};return{id:row.id,worldId:row.world_id,worldName:w.name,universeId:w.universe_id,userId:row.user_id,recipient:publicUser(row.user_id),inviter:publicUser(row.inviter_id),role:row.role,tags:JSON.parse(row.tags),status:row.status,createdAt:row.created_at,expiresAt:row.expires_at,updatedAt:row.updated_at};}
  function inviteEvent(row){for(const id of new Set([row.user_id,row.inviter_id]))emitUser(id,'invitation',{invitationId:row.id,worldId:row.world_id,status:row.status});}
  const optionalBody=async req=>Number(req.headers['content-length']||0)>0||req.headers['transfer-encoding']?body(req):{};
  return{async handle({req,res,path,method,userId,url}){
    const respond=(status,data)=>{send(res,status,data);return true;};
    if(path==='/api/accounts'&&method==='GET'){const worldId=v.id(url.searchParams.get('worldId'),'worldId');activeWorld(worldId,userId,true);const q=(url.searchParams.get('query')||'').trim().toLowerCase().slice(0,80);if(q.length<2)v.fail(400,'SEARCH_REQUIRED','Enter at least two characters to find a local account');const users=store.all('SELECT u.id,u.name,a.username FROM accounts a JOIN users u ON u.id=a.user_id ORDER BY a.username').filter(u=>u.username.includes(q)||u.name.toLowerCase().includes(q)).slice(0,50);return respond(200,{users});}
    if(path==='/api/universes'&&method==='GET')return respond(200,{universes:store.universes(userId,{includeArchived:url.searchParams.get('includeArchived')==='1',scope:url.searchParams.get('scope')})});
    if(path==='/api/universes'&&method==='POST'){
      const b=await body(req);immutable(b,['universeId','worldId']);const f=fields(b),scope='universe';let duplicate=false;const id=store.transaction(()=>{const prior=retry(userId,scope,b,f);if(prior){duplicate=true;return prior.result_id;}unique('universes',f.slug);const id=randomUUID();store.run('INSERT INTO universes(id,name,slug,description,thumbnail,owner_id,public,created_at) VALUES(?,?,?,?,?,?,?,?)',id,f.name,f.slug,f.description,f.thumbnail,userId,f.public,now());remember(userId,scope,b,f,id);return id;});changed('universe-created');return respond(duplicate?200:201,{universe:store.universe(id,userId),duplicate});
    }
    let m=path.match(new RegExp(`^/api/universes/${ID}(?:/(restore))?$`));
    if(m&&['GET','PATCH','DELETE','POST'].includes(method)){
      const id=m[1],restore=m[2];if(method==='GET'&&!restore){activeUniverse(id,userId);return respond(200,{universe:store.universe(id,userId,{includeArchived:url.searchParams.get('includeArchived')==='1'})});}
      if(!['PATCH','DELETE'].includes(method)&&!(restore&&method==='POST'))return false;
      const b=await optionalBody(req);immutable(b,['universeId','worldId']);store.transaction(()=>{const u=store.universeRow(id);if(u.owner_id!==userId){if(!store.canSeeUniverse(u,userId))deny();v.fail(403,'UNIVERSE_OWNER_REQUIRED');}cas(b,u,store.universe(u,userId,{includeArchived:true}));if(method==='PATCH'){if(u.archived_at)deny();const f=fields(b,u);unique('universes',f.slug,null,id);store.run('UPDATE universes SET name=?,slug=?,description=?,thumbnail=?,public=?,metadata_revision=metadata_revision+1 WHERE id=?',f.name,f.slug,f.description,f.thumbnail,f.public,id);}else{store.run('UPDATE universes SET archived_at=?,metadata_revision=metadata_revision+1 WHERE id=?',restore?null:u.archived_at??now(),id);if(!restore)store.run("UPDATE world_invitations SET status='cancelled',updated_at=? WHERE status='pending' AND world_id IN(SELECT id FROM worlds WHERE universe_id=?)",now(),id);}});changed(restore?'universe-restored':method==='DELETE'?'universe-archived':'universe-updated');return respond(200,{universe:store.universe(id,userId,{includeArchived:true}),ok:true});
    }
    if(path==='/api/worlds'&&method==='GET')return respond(200,{worlds:store.worlds(userId,{includeArchived:url.searchParams.get('includeArchived')==='1',universeId:url.searchParams.get('universeId')})});
    if(path==='/api/worlds'&&method==='POST'){
      const b=await body(req);immutable(b,['worldId']);const universeId=b.universeId===undefined?store.get('SELECT id FROM universes WHERE owner_id=? AND archived_at IS NULL ORDER BY created_at,id LIMIT 1',userId)?.id:v.id(b.universeId);if(!universeId)v.fail(400,'UNIVERSE_REQUIRED','Create or choose your universe first');const f=fields(b),payload={...f,universeId},scope='world';let duplicate=false;const id=store.transaction(()=>{activeUniverse(universeId,userId,true);const prior=retry(userId,scope,b,payload);if(prior){duplicate=true;return prior.result_id;}unique('worlds',f.slug,universeId);const id=randomUUID();store.run('INSERT INTO worlds(id,universe_id,name,slug,description,thumbnail,owner_id,public,created_at) VALUES(?,?,?,?,?,?,?,?,?)',id,universeId,f.name,f.slug,f.description,f.thumbnail,userId,f.public,now());store.run("INSERT INTO world_members(world_id,user_id,role,tags,created_at) VALUES(?,?,'admin','[]',?)",id,userId,now());remember(userId,scope,b,payload,id);return id;});changed('world-created');return respond(duplicate?200:201,{world:store.world(id,userId),duplicate});
    }
    m=path.match(new RegExp(`^/api/worlds/${ID}(?:/(restore))?$`));
    if(m&&['GET','PATCH','DELETE','POST'].includes(method)){
      const id=m[1],restore=m[2];if(method==='GET'&&!restore){activeWorld(id,userId);return respond(200,{world:store.world(id,userId,{includeArchived:url.searchParams.get('includeArchived')==='1'})});}if(!['PATCH','DELETE'].includes(method)&&!(restore&&method==='POST'))return false;
      const b=await optionalBody(req);immutable(b,['universeId','worldId']);store.transaction(()=>{const w=store.worldRow(id);if(w.universe_owner!==userId){if(!store.canSeeWorld(w,userId))deny();v.fail(403,'UNIVERSE_OWNER_REQUIRED');}cas(b,w,store.world(w,userId,{includeArchived:true}));if(method==='PATCH'){activeWorld(id,userId);const f=fields(b,w);unique('worlds',f.slug,w.universe_id,id);store.run('UPDATE worlds SET name=?,slug=?,description=?,thumbnail=?,public=?,metadata_revision=metadata_revision+1 WHERE id=?',f.name,f.slug,f.description,f.thumbnail,f.public,id);}else{store.run('UPDATE worlds SET archived_at=?,metadata_revision=metadata_revision+1 WHERE id=?',restore?null:w.archived_at??now(),id);if(!restore)store.run("UPDATE world_invitations SET status='cancelled',updated_at=? WHERE status='pending' AND world_id=?",now(),id);}});changed(restore?'world-restored':method==='DELETE'?'world-archived':'world-updated');return respond(200,{world:store.world(id,userId,{includeArchived:true}),ok:true});
    }
    if(path==='/api/rooms'&&method==='POST'){
      const b=await body(req);immutable(b,['universeId']);const worldId=v.id(b.worldId),f=fields(b),scene=v.scene(b.scene??{version:1,theme:'garden',bounds:{width:32,depth:26},spawn:{x:0,z:0},objects:[],areas:[]});validatePersonalScene(JSON.parse(scene));if(b.mapUrl!==undefined||b.templateId!==undefined)v.fail(400,'UNSUPPORTED_PROVISIONING','This 3D room uses a local scene, not an external 2D map or template');const payload={...f,worldId,scene},scope='room';let duplicate=false;const id=store.transaction(()=>{activeWorld(worldId,userId,true);const prior=retry(userId,scope,b,payload);if(prior){duplicate=true;return prior.result_id;}unique('rooms',f.slug,worldId);const id=randomUUID();store.run('INSERT INTO rooms(id,world_id,name,slug,description,thumbnail,owner_id,public,scene,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',id,worldId,f.name,f.slug,f.description,f.thumbnail,userId,f.public,scene,now());store.syncPersonalAreas(id,null,JSON.parse(scene));remember(userId,scope,b,payload,id);return id;});changed('room-created');return respond(duplicate?200:201,{room:store.room(id,userId),duplicate});
    }
    m=path.match(new RegExp(`^/api/rooms/${ID}(?:/(restore))?$`));
    if(m&&(['PATCH','DELETE'].includes(method)||(m[2]==='restore'&&method==='POST'))){
      const id=m[1],restore=m[2],b=await optionalBody(req);immutable(b,['universeId','worldId']);store.transaction(()=>{const r=store.roomRow(id);if(restore){if(!store.roomCapabilities(r,userId).canRestore){if(!store.canSeeWorld(store.worldRow(r.world_id),userId))deny();v.fail(403,'ROOM_FORBIDDEN');}}else store.authorize(id,userId,['owner','admin','editor']);cas(b,r,store.room(r,userId));if(method==='PATCH'){const f=fields(b,r);unique('rooms',f.slug,r.world_id,id);store.run('UPDATE rooms SET name=?,slug=?,description=?,thumbnail=?,public=?,metadata_revision=metadata_revision+1 WHERE id=?',f.name,f.slug,f.description,f.thumbnail,f.public,id);}else store.run('UPDATE rooms SET archived_at=?,metadata_revision=metadata_revision+1 WHERE id=?',restore?null:r.archived_at??now(),id);});changed(restore?'room-restored':method==='DELETE'?'room-archived':'room-updated');return respond(200,{room:store.room(id,userId),ok:true});
    }
    m=path.match(new RegExp(`^/api/worlds/${ID}/legacy-grants$`));
    if(m&&method==='GET'){activeWorld(m[1],userId,true);const grants=store.all('SELECT m.*,r.name AS room_name FROM members m JOIN rooms r ON r.id=m.room_id WHERE r.world_id=? AND m.needs_review=1 ORDER BY r.name,m.user_id',m[1]).map(g=>({roomId:g.room_id,roomName:g.room_name,userId:g.user_id,name:store.user(g.user_id)?.name,username:store.user(g.user_id)?.username,role:g.role,reason:'private-parent-review'}));return respond(200,{grants});}
    m=path.match(new RegExp(`^/api/worlds/${ID}/members(?:/${ID})?$`));
    if(m){const worldId=m[1],target=m[2];if(method==='GET'&&!target){activeWorld(worldId,userId,true);return respond(200,{members:store.all('SELECT * FROM world_members WHERE world_id=? ORDER BY created_at,user_id',worldId).map(r=>store.worldMember(r))});}if(!target||!['PUT','DELETE'].includes(method))return false;const b=await optionalBody(req);if(b.worldId!==undefined&&b.worldId!==worldId)v.fail(400,'WORLD_MISMATCH');if(b.userId!==undefined&&b.userId!==target)v.fail(400,'USER_MISMATCH');let membership;store.transaction(()=>{const w=activeWorld(worldId,userId,true);if(!store.user(target))v.fail(404,'USER_NOT_FOUND');const existing=store.worldMembership(worldId,target);if(method==='DELETE'){if(!existing)v.fail(404,'MEMBERSHIP_NOT_FOUND');protectMember(w,existing);store.run('DELETE FROM world_members WHERE world_id=? AND user_id=?',worldId,target);store.run('UPDATE members SET granted=0,role=? WHERE user_id=? AND room_id IN(SELECT id FROM rooms WHERE world_id=?)','member',target,worldId);}else{const data=roleTags({...b,role:b.role??existing?.role??'member',tags:b.tags??JSON.parse(existing?.tags||'[]')});if(existing)protectMember(w,existing,data.role);store.run('INSERT INTO world_members(world_id,user_id,role,tags,created_at) VALUES(?,?,?,?,?) ON CONFLICT(world_id,user_id) DO UPDATE SET role=excluded.role,tags=excluded.tags',worldId,target,data.role,data.tags,now());store.run('UPDATE members SET needs_review=0 WHERE user_id=? AND room_id IN(SELECT id FROM rooms WHERE world_id=?)',target,worldId);membership=store.worldMember(store.worldMembership(worldId,target));}});changed('membership-changed',method==='DELETE'?{worldId,userId:target}:{});emitUser(target,'membership',{worldId,userId:target,reason:method==='DELETE'?'removed':'updated'});return respond(200,{ok:true,membership,members:store.all('SELECT * FROM world_members WHERE world_id=?',worldId).map(r=>store.worldMember(r))});}
    if(path==='/api/memberships'&&method==='GET')return respond(200,{memberships:store.all('SELECT * FROM world_members WHERE user_id=? ORDER BY created_at,world_id',userId).map(r=>store.worldMember(r))});
    m=path.match(new RegExp(`^/api/worlds/${ID}/leave$`));
    if(m&&method==='POST'){const worldId=m[1],b=await optionalBody(req);if(b.userId!==undefined)v.fail(400,'SELF_ONLY','Leaving always applies to your own membership');store.transaction(()=>{const w=store.worldRow(worldId),membership=store.worldMembership(worldId,userId);if(!membership)v.fail(404,'MEMBERSHIP_NOT_FOUND');protectMember(w,membership);store.run('DELETE FROM world_members WHERE world_id=? AND user_id=?',worldId,userId);store.run('UPDATE members SET granted=0,role=? WHERE user_id=? AND room_id IN(SELECT id FROM rooms WHERE world_id=?)','member',userId,worldId);});changed('membership-left',{worldId,userId});emitUser(userId,'membership',{worldId,userId,reason:'left'});return respond(200,{ok:true});}
    m=path.match(new RegExp(`^/api/worlds/${ID}/invitations$`));
    if(m&&['GET','POST'].includes(method)){const worldId=m[1];if(method==='GET'){activeWorld(worldId,userId,true);expire();return respond(200,{invitations:store.all('SELECT * FROM world_invitations WHERE world_id=? ORDER BY created_at DESC,id',worldId).map(invitation)});}const b=await body(req),target=v.id(b.userId,'userId'),data=roleTags(b),days=b.expiresInDays===undefined?7:v.integer(b.expiresInDays,'expiresInDays',1,30),payload={worldId,userId:target,...data,days};let duplicate=false;expire();const row=store.transaction(()=>{activeWorld(worldId,userId,true);if(!store.user(target)?.account)v.fail(400,'LOCAL_ACCOUNT_REQUIRED','Choose an existing registered local account');if(target===userId)v.fail(400,'INVITE_SELF','You cannot invite yourself');const prior=retry(userId,'invitation',b,payload);if(prior){duplicate=true;return store.get('SELECT * FROM world_invitations WHERE id=?',prior.result_id);}const pending=store.get("SELECT * FROM world_invitations WHERE world_id=? AND user_id=? AND status='pending'",worldId,target);if(pending){if(pending.role===data.role&&pending.tags===data.tags){duplicate=true;remember(userId,'invitation',b,payload,pending.id);return pending;}v.fail(409,'INVITATION_PENDING','A pending invitation already exists; cancel it before changing the intended role');}const id=randomUUID();store.run("INSERT INTO world_invitations(id,world_id,user_id,inviter_id,role,tags,status,created_at,expires_at,updated_at) VALUES(?,?,?,?,?,?,'pending',?,?,?)",id,worldId,target,userId,data.role,data.tags,now(),now()+days*86400000,now());remember(userId,'invitation',b,payload,id);return store.get('SELECT * FROM world_invitations WHERE id=?',id);});inviteEvent(row);return respond(duplicate?200:201,{invitation:invitation(row),duplicate});}
    if(path==='/api/invitations'&&method==='GET'){expire();return respond(200,{invitations:store.all('SELECT * FROM world_invitations WHERE user_id=? ORDER BY created_at DESC,id',userId).map(invitation)});}
    m=path.match(new RegExp(`^/api/invitations/${ID}/(accept|reject|cancel)$`));
    if(m&&method==='POST'){await optionalBody(req);expire();let membership;const row=store.transaction(()=>{const i=store.get('SELECT * FROM world_invitations WHERE id=?',m[1]);if(!i)v.fail(404,'INVITATION_NOT_FOUND');if(m[2]==='cancel')activeWorld(i.world_id,userId,true);else if(i.user_id!==userId)v.fail(404,'INVITATION_NOT_FOUND');if(i.status!=='pending')v.fail(409,'INVITATION_NOT_PENDING','This invitation has already reached an outcome',{status:i.status,invitation:invitation(i)});const w=store.worldRow(i.world_id);if(w.archived_at||w.universe_archived)deny();if(m[2]==='accept'){if(!['owner','admin'].includes(store.worldRole(w,i.inviter_id)))v.fail(409,'INVITER_REVOKED','The inviter no longer manages this world');store.run('INSERT OR IGNORE INTO world_members(world_id,user_id,role,tags,created_at) VALUES(?,?,?,?,?)',i.world_id,userId,i.role,i.tags,now());store.run('UPDATE members SET needs_review=0 WHERE user_id=? AND room_id IN(SELECT id FROM rooms WHERE world_id=?)',userId,i.world_id);membership=store.worldMember(store.worldMembership(i.world_id,userId));}store.run('UPDATE world_invitations SET status=?,updated_at=? WHERE id=? AND status=?',m[2]==='accept'?'accepted':m[2]==='reject'?'rejected':'cancelled',now(),i.id,'pending');return store.get('SELECT * FROM world_invitations WHERE id=?',i.id);});inviteEvent(row);changed('invitation-resolved');if(membership)emitUser(userId,'membership',{worldId:row.world_id,userId,reason:'added'});return respond(200,{invitation:invitation(row),...(membership?{membership}:{})});}
    if(path==='/api/discover'&&method==='GET'){const universeId=url.searchParams.get('universeId'),q=(url.searchParams.get('q')||'').toLowerCase().slice(0,120),universes=store.universes(userId).filter(u=>!universeId||u.id===universeId);const matches=p=>!q||[p.name,p.slug,p.description].some(s=>s.toLowerCase().includes(q));const worlds=universes.flatMap(u=>u.worlds),rooms=worlds.flatMap(w=>w.rooms);const offset=Math.max(0,Number(url.searchParams.get('offset'))||0),limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit'))||100));return respond(200,{universes:universes.filter(matches).map(({worlds,...u})=>u).slice(offset,offset+limit),worlds:worlds.filter(matches).map(({rooms,...w})=>w).slice(offset,offset+limit),rooms:rooms.filter(matches).slice(offset,offset+limit),hasMore:rooms.filter(matches).length>offset+limit});}
    if(path==='/api/stars'&&method==='GET'){return respond(200,{rooms:store.all('SELECT room_id FROM stars WHERE user_id=? ORDER BY created_at DESC',userId).map(s=>store.roomRow(s.room_id)).filter(r=>store.canSeeRoom(r,userId)).map(r=>store.room(r,userId,false))});}
    m=path.match(new RegExp(`^/api/rooms/${ID}/star$`));if(m&&['PUT','DELETE'].includes(method)){store.authorize(m[1],userId);if(method==='PUT')store.run('INSERT OR IGNORE INTO stars(user_id,room_id,created_at) VALUES(?,?,?)',userId,m[1],now());else store.run('DELETE FROM stars WHERE user_id=? AND room_id=?',userId,m[1]);return respond(200,{starred:method==='PUT',roomId:m[1]});}
    if(/^\/api\/rooms\/[A-Za-z0-9_-]+\/invites$/.test(path)||/^\/api\/invites\/[A-Za-z0-9_-]+\/join$/.test(path))v.fail(410,'TARGETED_INVITATION_REQUIRED','Use the world member panel to invite a registered local account');
    return false;
  }};
}
