import {sessionPrincipals} from './public-guests.mjs';
import {SCENE_OPERATION_FIELDS} from '../src/scene-operations.js';
import {randomUUID} from 'node:crypto';
import {fail} from './validation.mjs';
const ADMIN=['owner','admin'];
const EDIT=['owner','admin','editor'];
export const slugify=value=>String(value).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64)||'place';

export function migrateHierarchy(store){
  const add=(table,column,type)=>{if(!store.all(`PRAGMA table_info(${table})`).some(c=>c.name===column))store.db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${type}`);};
  store.db.exec(`CREATE TABLE IF NOT EXISTS universes(id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '',thumbnail TEXT NOT NULL DEFAULT '',owner_id TEXT REFERENCES users(id),public INTEGER NOT NULL DEFAULT 1,archived_at INTEGER,metadata_revision INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
  CREATE TABLE IF NOT EXISTS world_members(world_id TEXT NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN ('member','editor','admin')),tags TEXT NOT NULL DEFAULT '[]',created_at INTEGER NOT NULL,PRIMARY KEY(world_id,user_id));
  CREATE TABLE IF NOT EXISTS world_invitations(id TEXT PRIMARY KEY,world_id TEXT NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id),inviter_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN ('member','editor','admin')),tags TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL CHECK(status IN ('pending','accepted','rejected','cancelled','expired')),created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
  CREATE UNIQUE INDEX IF NOT EXISTS one_pending_world_invitation ON world_invitations(world_id,user_id) WHERE status='pending';
  CREATE TABLE IF NOT EXISTS place_operations(user_id TEXT NOT NULL REFERENCES users(id),scope TEXT NOT NULL,operation_id TEXT NOT NULL,payload TEXT NOT NULL,result_id TEXT NOT NULL,PRIMARY KEY(user_id,scope,operation_id));
  CREATE TABLE IF NOT EXISTS stars(user_id TEXT NOT NULL REFERENCES users(id),room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,created_at INTEGER NOT NULL,PRIMARY KEY(user_id,room_id));`);
  for(const table of ['worlds','rooms'])for(const[c,t]of[['slug',"TEXT NOT NULL DEFAULT ''"],['description',"TEXT NOT NULL DEFAULT ''"],['thumbnail',"TEXT NOT NULL DEFAULT ''"],['archived_at','INTEGER'],['metadata_revision','INTEGER NOT NULL DEFAULT 0']])add(table,c,t);
  add('worlds','universe_id','TEXT REFERENCES universes(id)');add('members','granted','INTEGER NOT NULL DEFAULT 1');add('members','needs_review','INTEGER NOT NULL DEFAULT 0');
  if(!store.get("SELECT value FROM metadata WHERE key='hierarchy-v3'"))store.transaction(()=>{
    // Existing world owners retain their authority: each distinct owner gets a
    // universe. Fresh seeds share one unclaimed universe, claimed by first guest.
    store.run("UPDATE members SET granted=0 WHERE role='member' AND room_id IN(SELECT r.id FROM rooms r JOIN worlds w ON w.id=r.world_id WHERE r.public=1 AND w.public=1)");
    const byOwner=new Map();for(const w of store.all('SELECT * FROM worlds ORDER BY created_at,id')){
      const key=w.owner_id||'unclaimed';let uid=byOwner.get(key);
      if(!uid){uid=byOwner.size===0?'universe-main':randomUUID();const slug=byOwner.size===0?'universe':`universe-${byOwner.size+1}`;store.run('INSERT INTO universes(id,name,slug,owner_id,created_at) VALUES(?,?,?,?,?)',uid,byOwner.size===0?'Universe':`${store.user(w.owner_id)?.name||'Explorer'}’s Universe`,slug,w.owner_id,w.created_at);byOwner.set(key,uid);}
      let slug=slugify(w.name);if(store.get('SELECT 1 FROM worlds WHERE universe_id=? AND slug=?',uid,slug))slug=`${slug.slice(0,45)}-${w.id.slice(0,12)}`;
      store.run('UPDATE worlds SET universe_id=?,slug=? WHERE id=?',uid,slug,w.id);
      if(w.owner_id)store.run("INSERT OR IGNORE INTO world_members(world_id,user_id,role,tags,created_at) VALUES(?,?,'admin','[]',?)",w.id,w.owner_id,w.created_at);
      // v0.2 room-only grants cannot safely become world-wide membership.
      // Preserve their records for manager review, but private ancestors require
      // explicit v0.3 world admission. This deliberately tightens legacy access.
      if(!w.public)store.run('UPDATE members SET needs_review=1 WHERE room_id IN(SELECT id FROM rooms WHERE world_id=?) AND user_id!=COALESCE(?,?)',w.id,w.owner_id,'');
      for(const r of store.all('SELECT id,name FROM rooms WHERE world_id=? ORDER BY created_at,id',w.id)){let rs=slugify(r.name);if(store.get('SELECT 1 FROM rooms WHERE world_id=? AND slug=?',w.id,rs))rs=`${rs.slice(0,45)}-${r.id.slice(0,12)}`;store.run('UPDATE rooms SET slug=? WHERE id=?',rs,r.id);}
    }
    if(!byOwner.size)store.run('INSERT INTO universes(id,name,slug,created_at) VALUES(?,?,?,?)','universe-main','Universe','universe',store.now());
    store.run("INSERT INTO metadata(key,value) VALUES('hierarchy-v3','1')");
  });
  store.db.exec('CREATE UNIQUE INDEX IF NOT EXISTS world_slug_scope ON worlds(universe_id,slug); CREATE UNIQUE INDEX IF NOT EXISTS room_slug_scope ON rooms(world_id,slug);');
}

export const hierarchyMethods={
  claimUnowned(userId){this.run('UPDATE universes SET owner_id=? WHERE owner_id IS NULL',userId);for(const w of this.all('SELECT id FROM worlds WHERE owner_id=?',userId))this.run("INSERT OR IGNORE INTO world_members(world_id,user_id,role,tags,created_at) VALUES(?,?,'admin','[]',?)",w.id,userId,this.now());},
  universeRow(id){const row=this.get('SELECT * FROM universes WHERE id=?',id);if(!row)fail(404,'PLACE_NOT_FOUND','Place is unavailable');return row;},
  worldRow(id){const row=this.get('SELECT w.*,u.owner_id AS universe_owner,u.public AS universe_public,u.archived_at AS universe_archived,u.name AS universe_name,u.slug AS universe_slug FROM worlds w JOIN universes u ON u.id=w.universe_id WHERE w.id=?',id);if(!row)fail(404,'PLACE_NOT_FOUND','Place is unavailable');return row;},
  roomRow(id){const row=this.get('SELECT r.*,w.owner_id AS world_owner,w.public AS world_public,w.archived_at AS world_archived,w.universe_id,u.owner_id AS universe_owner,u.public AS universe_public,u.archived_at AS universe_archived FROM rooms r JOIN worlds w ON w.id=r.world_id JOIN universes u ON u.id=w.universe_id WHERE r.id=?',id);if(!row)fail(404,'PLACE_NOT_FOUND','Place is unavailable');return row;},
  worldMembership(worldId,userId){return this.get('SELECT * FROM world_members WHERE world_id=? AND user_id=?',worldId,userId);},
  worldRole(world,userId){if(this.isPublicGuest(userId))return 'guest';return world.universe_owner===userId?'owner':this.worldMembership(world.id,userId)?.role||'guest';},
  canSeeUniverse(u,userId){if(this.isPublicGuest(userId))return !u.archived_at&&!!u.public;return !u.archived_at&&(!!u.public||u.owner_id===userId||!!this.get('SELECT 1 FROM world_members m JOIN worlds w ON w.id=m.world_id WHERE w.universe_id=? AND m.user_id=? AND w.archived_at IS NULL',u.id,userId));},
  canSeeWorld(w,userId){if(this.isPublicGuest(userId))return !w.archived_at&&!w.universe_archived&&!!w.public&&!!w.universe_public;return !w.archived_at&&!w.universe_archived&&(w.universe_owner===userId||!!this.worldMembership(w.id,userId)||!!(w.public&&w.universe_public));},
  canSeeRoom(r,userId){const m=this.membership(r.id,userId);if(m?.banned||r.archived_at||r.world_archived||r.universe_archived)return false;if(this.isPublicGuest(userId))return !!(r.universe_public&&r.world_public&&r.public);if(r.universe_owner===userId)return true;const wm=this.worldMembership(r.world_id,userId);if(wm)return true;return !!(r.universe_public&&r.world_public&&(r.public||m?.granted));},
  role(r,userId){const m=this.membership(r.id,userId);if(m?.banned)return'banned';if(!this.canSeeRoom(r,userId))return null;if(this.isPublicGuest(userId))return'guest';if(r.universe_owner===userId)return'owner';const wm=this.worldMembership(r.world_id,userId);if(wm?.role==='admin')return'admin';if(wm?.role==='editor')return'editor';return m?.granted?m.role:wm?'member':'guest';},
  authorize(roomId,userId,roles=null){const row=this.roomRow(roomId);if(!this.canSeeRoom(row,userId))fail(404,'PLACE_NOT_FOUND','Place is unavailable');const role=this.role(row,userId);if(roles&&!roles.includes(role))fail(403,'ROOM_FORBIDDEN','You do not have permission for this room');return{row,role,member:this.membership(roomId,userId)};},
  roomCapabilities(r,userId){const role=this.role(r,userId),wm=this.worldRole(this.worldRow(r.world_id),userId),edit=EDIT.includes(role),active=!r.archived_at&&!r.world_archived&&!r.universe_archived,manage=ADMIN.includes(wm)&&active,m=this.membership(r.id,userId),recover=EDIT.includes(wm)||(r.universe_public&&r.world_public&&!r.world_archived&&!r.universe_archived&&!!m?.granted&&m.role==='editor');const personal=this.personalAreas(r,userId),areaEdit=personal.some(a=>a.canEditObjects);return{canBuild:edit||areaEdit,canEditObjects:edit||areaEdit,canManagePersonalAreas:edit,editableAreaIds:personal.filter(a=>a.canEditObjects).map(a=>a.areaId),canEdit:edit,canEditScene:edit,canEditMetadata:edit,canArchive:edit,canRestore:!!recover,canModerate:['owner','admin','moderator'].includes(role),canManageMembers:manage,canInvite:manage};},
  room(rowOrId,userId,includeScene=true){const r=typeof rowOrId==='string'?this.roomRow(rowOrId):this.roomRow(rowOrId.id);return{id:r.id,worldId:r.world_id,universeId:r.universe_id,name:r.name,slug:r.slug,description:r.description,thumbnail:r.thumbnail,ownerId:r.owner_id,public:!!r.public,archivedAt:r.archived_at,metadataRevision:r.metadata_revision,revision:r.revision,sceneOperations:{version:1},sceneOperationsV2:{version:2,sceneFields:[...SCENE_OPERATION_FIELDS]},role:this.role(r,userId),tags:JSON.parse(this.worldMembership(r.world_id,userId)?.tags||'[]'),capabilities:this.roomCapabilities(r,userId),personalAreas:this.personalAreas(r,userId),...(includeScene?{scene:JSON.parse(r.scene)}:{})};},
  world(wOrId,userId,{includeArchived=false}={}){const w=typeof wOrId==='string'?this.worldRow(wOrId):this.worldRow(wOrId.id);const role=this.worldRole(w,userId),owned=role==='owner',admin=ADMIN.includes(role);return{id:w.id,universeId:w.universe_id,name:w.name,slug:w.slug,description:w.description,thumbnail:w.thumbnail,ownerId:w.owner_id,public:!!w.public,archivedAt:w.archived_at,metadataRevision:w.metadata_revision,role,tags:JSON.parse(this.worldMembership(w.id,userId)?.tags||'[]'),capabilities:{canEdit:owned&&!w.archived_at&&!w.universe_archived,canArchive:owned&&!w.archived_at&&!w.universe_archived,canRestore:owned,canCreateRoom:admin&&!w.archived_at&&!w.universe_archived,canManageMembers:admin&&!w.archived_at&&!w.universe_archived,canInvite:admin&&!w.archived_at&&!w.universe_archived},rooms:this.all('SELECT id FROM rooms WHERE world_id=? ORDER BY created_at,id',w.id).map(r=>this.roomRow(r.id)).filter(r=>this.canSeeRoom(r,userId)||(includeArchived&&(r.archived_at||r.world_archived||r.universe_archived)&&this.roomCapabilities(r,userId).canRestore)).map(r=>this.room(r,userId,false))};},
  worlds(userId,options={}){return this.all('SELECT id FROM worlds ORDER BY created_at,id').map(w=>this.worldRow(w.id)).filter(w=>this.canSeeWorld(w,userId)||(options.includeArchived&&(w.archived_at||w.universe_archived)&&EDIT.includes(this.worldRole(w,userId)))).filter(w=>!options.universeId||w.universe_id===options.universeId).map(w=>this.world(w,userId,options));},
  universe(uOrId,userId,options={}){const u=typeof uOrId==='string'?this.universeRow(uOrId):uOrId;const owned=u.owner_id===userId;return{id:u.id,name:u.name,slug:u.slug,description:u.description,thumbnail:u.thumbnail,ownerId:u.owner_id,public:!!u.public,archivedAt:u.archived_at,metadataRevision:u.metadata_revision,capabilities:{canEdit:owned&&!u.archived_at,canArchive:owned&&!u.archived_at,canRestore:owned,canCreateWorld:owned&&!u.archived_at},worlds:this.worlds(userId,{...options,universeId:u.id})};},
  universes(userId,options={}){return this.all('SELECT * FROM universes ORDER BY created_at,id').filter(u=>this.canSeeUniverse(u,userId)||(options.includeArchived&&u.owner_id===userId)).filter(u=>options.scope!=='owned'||u.owner_id===userId).map(u=>this.universe(u,userId,options));},
  worldMember(row){const w=this.worldRow(row.world_id),user=this.user(row.user_id),protectedMember=w.universe_owner===row.user_id;return{id:row.user_id,userId:row.user_id,worldId:row.world_id,worldName:w.name,universeId:w.universe_id,name:user.name,username:user.username,role:row.role,tags:JSON.parse(row.tags),createdAt:row.created_at,protected:protectedMember,canLeave:!protectedMember&&!(row.role==='admin'&&this.get("SELECT COUNT(*) AS n FROM world_members WHERE world_id=? AND role='admin'",w.id).n<=1)};},
  members(roomId){const r=this.roomRow(roomId);const ids=new Set(this.all('SELECT user_id FROM members WHERE room_id=? AND banned=0 AND granted=1',roomId).map(x=>x.user_id));for(const m of this.all('SELECT user_id FROM world_members WHERE world_id=?',r.world_id))ids.add(m.user_id);for(const s of sessionPrincipals(this,{roomId}))ids.add(s.user_id);if(r.universe_owner)ids.add(r.universe_owner);return[...ids].filter(id=>this.canSeeRoom(r,id)).map(id=>({...this.user(id),role:this.role(r,id),tags:JSON.parse(this.worldMembership(r.world_id,id)?.tags||'[]'),mutedUntil:this.membership(roomId,id)?.muted_until||0}));},
};
