import {roomAllows} from './permissions.js';
import {attachRoomFile,listRoomFiles,FILE_ACCEPT} from './files.js';
import {CATALOG,clone,dimensions} from './worlds.js';
const el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const uid=()=>crypto.randomUUID();
export function mountEditor({root,getState,onScene,onSelect,api,toast,onClose}){
 let tool='select',selected=null,history=[],future=[],dirty=false,saving=false,base=null,roomId=null,conflictRoom=null;
 const header=el('div','panel-header');header.append(el('div','','Build your world'));const close=el('button','icon-btn','×');close.ariaLabel='Close editor';close.onclick=onClose;header.append(close);root.append(header);
 const status=el('div','editor-status','Changes are stored in this room');root.append(status);
 const tools=el('div','editor-actions');root.append(tools);
 function button(label,action,title=label){const b=el('button','small-btn',label);b.title=title;b.onclick=action;return b;}
 const undo=button('↶',()=>undoScene(),'Undo last change (Ctrl+Z)'),redo=button('↷',()=>redoScene(),'Redo last change'),save=button('Save room',()=>saveScene()),discard=button('Revert',()=>revert());save.classList.add('primary');tools.append(undo,redo,discard,save);
 const tip=el('p','panel-hint','Choose an item, then click the ground. Select an item to move or edit it.');root.append(tip);
 const searchBox=el('div','editor-search');const search=el('input');search.type='search';search.placeholder='Find an item or area…';search.ariaLabel='Search room items';const results=el('div','editor-search-results');searchBox.append(search,results);root.append(searchBox);search.oninput=()=>renderSearch();
 const catalog=el('div','catalog');root.append(catalog);
 const selectBtn=button('↖ Select',()=>setTool('select')),areaBtn=button('▱ Area',()=>setTool('area'));catalog.append(selectBtn,areaBtn);
 for(const [type,def]of Object.entries(CATALOG)){const b=button(def.icon+' '+def.name,()=>setTool(type));b.dataset.tool=type;catalog.append(b);}
 const inspector=el('div','inspector');root.append(inspector);
 const foot=el('div','editor-footer');const exportBtn=button('Export room',()=>exportScene()),importBtn=button('Import JSON',()=>file.click());const file=el('input');file.type='file';file.accept='.json,application/json';file.hidden=true;file.onchange=()=>importScene(file.files[0]);foot.append(exportBtn,importBtn,file);root.append(foot);
 const getScene=()=>getState().scene;
 const permission=()=>roomAllows(getState().room,'canEditScene');
 function attachRoom(){const state=getState();if(roomId!==state.room?.id){roomId=state.room?.id;base=clone(state.scene);history=[];future=[];selected=null;dirty=false;tool='select';conflictRoom=null;}update();}
 function changed(before){history.push(before);if(history.length>60)history.shift();future=[];dirty=true;onScene(getScene());update();}
 function mutate(fn){if(!permission()){toast('Only room owners and editors can build');return;}const before=clone(getScene());fn(getScene());changed(before);}
 function setTool(t){tool=t;selected=null;onSelect(null);update();}
 function renderSearch(){results.replaceChildren();const query=search.value.trim().toLowerCase();if(!query)return;const matches=[...(getScene()?.objects||[]),...(getScene()?.areas||[])].filter(o=>(o.name+' '+(o.type||'area')+' '+(o.text||'')).toLowerCase().includes(query)).slice(0,20);if(!matches.length)results.append(el('p','panel-hint','No matching items'));for(const item of matches)results.append(button(item.name,()=>select(item.id)));}
 function update(){renderSearch();discard.textContent=conflictRoom?'Use server version':'Revert';status.textContent=conflictRoom?'Newer server version found · export or reload':saving?'Saving to server…':dirty?'Unsaved changes · save to keep this room':'All changes saved';status.classList.toggle('dirty',dirty);undo.disabled=!history.length||saving;redo.disabled=!future.length||saving;save.disabled=!dirty||saving||!permission();discard.disabled=!dirty||saving;for(const b of catalog.querySelectorAll('button'))b.classList.toggle('active',(b.dataset.tool||'')===tool);selectBtn.classList.toggle('active',tool==='select');areaBtn.classList.toggle('active',tool==='area');renderInspector();window.dispatchEvent(new CustomEvent('editor-status',{detail:{dirty,saving}}));}
 function field(label,value,onChange,{type='text',min,max,step,options}={}){const wrap=el('label','field');wrap.append(el('span','',label));const input=el(options?'select':type==='textarea'?'textarea':'input');if(!options){if(type!=='textarea')input.type=type;input.value=value??'';if(min!=null)input.min=min;if(max!=null)input.max=max;if(step!=null)input.step=step;}else{for(const [val,name]of options){const op=el('option','',name);op.value=val;input.append(op);}input.value=value??'';}input.onchange=()=>onChange(type==='number'?Number(input.value):input.value);wrap.append(input);return wrap;}
 function renderInspector(){inspector.replaceChildren();const scene=getScene();if(!scene)return;const o=scene.objects.find(o=>o.id===selected),a=scene.areas.find(a=>a.id===selected),v=o||a;
 if(!v){inspector.append(el('h3','',tool==='select'?'Room settings':tool==='area'?'Create an area':'Place '+(CATALOG[tool]?.name||'item')));inspector.append(el('p','panel-hint',tool==='area'?'Click the ground to place a 4 × 4 area. Then choose what happens inside it.':tool==='select'?'Click any furniture item, or select an area below.':'Each click adds an item. Switch back to Select when you’re finished.'));
 inspector.append(field('Environment',scene.theme,v=>mutate(s=>s.theme=v),{options:[['garden','Garden'],['studio','Studio'],['assembly','Assembly']]}));
 const areas=el('div','area-list');for(const a of scene.areas){const b=button('▱ '+a.name,()=>select(a.id));areas.append(b);}inspector.append(areas);const spawn=button('Set arrival at my position',()=>mutate(s=>s.spawn={...getState().position}));inspector.append(spawn);return;}
 inspector.append(el('h3','',a?'Area properties':'Item properties'));const patch=(k,val)=>mutate(s=>{const item=[...s.objects,...s.areas].find(i=>i.id===selected);if(item)item[k]=val;});
 inspector.append(field('Name',v.name,val=>patch('name',val)));
 const row=el('div','field-row');row.append(field('X',v.x,val=>patch('x',Math.max(-scene.bounds.width/2,Math.min(scene.bounds.width/2,val))),{type:'number',step:.5}),field('Z',v.z,val=>patch('z',Math.max(-scene.bounds.depth/2,Math.min(scene.bounds.depth/2,val))),{type:'number',step:.5}));inspector.append(row);
 if(a){const size=el('div','field-row');size.append(field('Width',a.width,val=>patch('width',Math.max(1,Math.min(32,val))),{type:'number',min:1,max:32,step:.5}),field('Depth',a.depth,val=>patch('depth',Math.max(1,Math.min(26,val))),{type:'number',min:1,max:26,step:.5}));inspector.append(size);
 inspector.append(field('On entry',a.action,val=>patch('action',val),{options:[['welcome','Show a message'],['silent','Quiet / no proximity'],['meeting','Meeting room'],['stage','Broadcast stage'],['audience','Broadcast audience'],['teleport','Teleport to room'],['link','Open a website prompt']]}));
 if(['meeting','stage','audience'].includes(a.action))inspector.append(field('Shared meeting name',a.meetingName||a.name,val=>patch('meetingName',val)));
 if(a.action==='teleport')inspector.append(field('Destination room ID',a.target||'',val=>patch('target',val)));
 if(a.action==='link')inspector.append(field('Website URL',a.url||'',val=>patch('url',val),{type:'url'}));
 inspector.append(field('Area message',a.message||'',val=>patch('message',val),{type:'textarea'}));
 inspector.append(el('h3','','Additional actions'));
 inspector.append(el('p','panel-hint','An area can show several links, messages, and opt-in sounds together.'));
 for(const action of a.actions||[]){const card=el('div','action-card');card.append(el('strong','',action.type==='link'?'Website / document':action.type==='audio'?'Room sound':action.type==='teleport'?'Room travel':'Message'));const change=(key,value)=>mutate(s=>{const item=s.areas.find(v=>v.id===selected)?.actions?.find(v=>v.id===action.id);if(item)item[key]=value;});
 if(action.type==='message')card.append(field('Text',action.message||'',v=>change('message',v),{type:'textarea'}));
 if(action.type==='link'||action.type==='audio')card.append(field('URL',action.url||'',v=>change('url',v),{type:'url'}));
 if(action.type==='link')card.append(field('Link label',action.label||'',v=>change('label',v)));
 if(action.type==='audio'){card.append(field('Volume',action.volume??.5,v=>change('volume',v),{type:'number',min:0,max:1,step:.1}));card.append(field('Playback',String(action.loop??true),v=>change('loop',v==='true'),{options:[['true','Loop in this area'],['false','Play once']]}));}
 if(action.type==='teleport')card.append(field('Destination room ID',action.target||'',v=>change('target',v)));
 card.append(button('Remove action',()=>mutate(s=>{const area=s.areas.find(v=>v.id===selected);area.actions=area.actions.filter(v=>v.id!==action.id);})));inspector.append(card);}
 const add=el('div','editor-actions');for(const[type,label]of [['message','+ Message'],['link','+ Link'],['audio','+ Sound'],['teleport','+ Travel']])add.append(button(label,()=>mutate(s=>{const area=s.areas.find(v=>v.id===selected);area.actions??=[];const item={id:uid(),type};if(type==='message')item.message='A new message';if(type==='link'){item.url='https://example.com';item.label='Open website';}if(type==='audio'){item.url='/assets/chime.wav';item.volume=.5;item.loop=true;}if(type==='teleport')item.target='commons';area.actions.push(item);})));inspector.append(add);
 }else{inspector.append(field('Rotation',v.rotation||0,val=>patch('rotation',Number(val)),{options:[[0,'0°'],[90,'90°'],[180,'180°'],[270,'270°']]}));inspector.append(field('Description',v.text||'',val=>patch('text',val),{type:'textarea'}));inspector.append(field('Open URL on interaction',v.url||'',val=>patch('url',val),{type:'url'}));if(v.type==='portal')inspector.append(field('Destination room ID',v.target||'',val=>patch('target',val)));inspector.append(field('Color',v.color||CATALOG[v.type].color,val=>patch('color',val),{type:'color'}));
 const docs=el('div','document-tools');docs.append(el('h3','','Room documents'));const uploadInput=el('input');uploadInput.type='file';uploadInput.accept=FILE_ACCEPT;uploadInput.hidden=true;const capturedRoom=roomId,capturedItem=v.id;const upload=button('Upload a document',()=>uploadInput.click());uploadInput.onchange=async()=>{const file=uploadInput.files[0];if(!file)return;upload.disabled=true;upload.textContent='Uploading…';try{const saved=await attachRoomFile({roomId:capturedRoom,file});if(roomId!==capturedRoom||!getScene().objects.some(o=>o.id===capturedItem)){toast('Uploaded to the original room. Select an item there to attach it.');return;}mutate(s=>{const item=s.objects.find(o=>o.id===capturedItem);item.url=saved.url;item.name=saved.name.slice(0,120);item.document={id:saved.id,name:saved.name,size:saved.size,contentType:saved.contentType};});toast('Document attached to this draft. Save the room to keep it.');}catch(e){toast(e.message);}finally{upload.disabled=false;upload.textContent='Upload a document';uploadInput.value='';}};docs.append(upload,uploadInput);const savedList=el('select');savedList.ariaLabel='Saved room document';const placeholder=el('option','','Choose an uploaded document');placeholder.value='';savedList.append(placeholder);docs.append(savedList);savedList.onchange=()=>{const item=savedList._files?.find(f=>f.id===savedList.value);if(!item)return;mutate(s=>{const o=s.objects.find(o=>o.id===capturedItem);if(o){o.url=item.url;o.name=item.name.slice(0,120);o.document={id:item.id,name:item.name,size:item.size,contentType:item.contentType};}});};listRoomFiles(capturedRoom).then(result=>{if(!docs.isConnected)return;savedList._files=result.files||[];for(const file of savedList._files){const option=el('option','',file.name);option.value=file.id;savedList.append(option);}}).catch(()=>{});if(v.document)docs.append(el('p','panel-hint','Attached: '+v.document.name+' · '+Math.ceil(v.document.size/1024)+' KB'));inspector.append(docs);}

 const actions=el('div','editor-actions');actions.append(button('Move here',()=>{tool='move';tip.textContent='Click the ground to move this item'}),button('Duplicate',()=>duplicate()),button('Delete',()=>remove()));inspector.append(actions);}
 function select(id){tool='select';selected=id;onSelect(id);update();}
 function pick(hit){if(saving)return;if(tool==='select'){if(hit.id)select(hit.id);else{selected=null;onSelect(null);update();}return;}if(!hit.point)return;const x=Math.round(hit.point.x*2)/2,z=Math.round(hit.point.z*2)/2;
 if(tool==='move'){mutate(s=>{const item=[...s.objects,...s.areas].find(o=>o.id===selected);if(item){item.x=x;item.z=z;}});tool='select';tip.textContent='Choose an item, then click the ground.';onSelect(selected);return;}
 if(tool==='area'){const id='area-'+uid();mutate(s=>s.areas.push({id,name:'New area',x,z,width:4,depth:4,action:'welcome',message:'Welcome to this area'}));select(id);return;}
 if(CATALOG[tool]){const id=tool+'-'+uid();mutate(s=>s.objects.push({id,type:tool,name:CATALOG[tool].name,x,z,rotation:0}));selected=id;onSelect(id);}}
 function duplicate(){if(!selected)return;const id=uid();mutate(s=>{const o=s.objects.find(o=>o.id===selected),a=s.areas.find(a=>a.id===selected);const copy={...clone(o||a),id,x:(o||a).x+1,z:(o||a).z+1};(o?s.objects:s.areas).push(copy);});select(id);}
 function remove(){if(!selected)return;mutate(s=>{s.objects=s.objects.filter(o=>o.id!==selected);s.areas=s.areas.filter(o=>o.id!==selected);});selected=null;onSelect(null);update();}
 function undoScene(){if(!history.length||saving)return;future.push(clone(getScene()));const prev=history.pop();onScene(prev);dirty=true;selected=null;onSelect(null);update();}
 function redoScene(){if(!future.length||saving)return;history.push(clone(getScene()));onScene(future.pop());dirty=true;selected=null;onSelect(null);update();}
 function revert(){if(conflictRoom){base=clone(conflictRoom.scene);getState().room.revision=conflictRoom.revision;getState().room.scene=clone(conflictRoom.scene);conflictRoom=null;}if(!base)return;onScene(clone(base));history=[];future=[];selected=null;dirty=false;onSelect(null);update();}
 async function saveScene(){if(saving||!dirty)return;const savingRoom=roomId,revision=getState().room.revision,scene=clone(getScene());saving=true;update();try{const result=await api('/api/rooms/'+savingRoom+'/scene',{method:'PUT',body:{revision,scene}});if(getState().room.id!==savingRoom)return;const room=result.room||result;getState().room.revision=room.revision;base=clone(room.scene||getScene());getState().room.scene=clone(base);onScene(clone(base));dirty=false;toast('Room saved');}catch(e){if(e.status===409){conflictRoom=e.data?.room||null;toast('Someone saved a newer version. Export your edits, then reload the room to resolve the conflict.');}else toast(e.message||'Save failed. Your edits are still here.');}finally{saving=false;update();}}
 function receiveScene(room){if(room.id!==roomId)return;if(saving)return;if(dirty){toast('This room changed on the server. Your draft is kept; save will check for a conflict.');return;}base=clone(room.scene);history=[];future=[];getState().room.revision=room.revision;getState().room.scene=clone(room.scene);onScene(clone(room.scene));update();}
 function exportScene(){const data=JSON.stringify({format:'universe-room',version:1,name:getState().room.name,scene:getScene()},null,2);const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=el('a');a.href=url;a.download=getState().room.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importScene(file){if(!file)return;try{if(file.size>512000)throw new Error('Room file is too large (500 KB maximum)');const doc=JSON.parse(await file.text()),s=doc.scene||doc;if(!Array.isArray(s.objects)||!Array.isArray(s.areas)||!s.bounds||s.objects.length>1000||s.areas.length>100)throw new Error('This is not a supported room file');for(const o of s.objects)if(!CATALOG[o.type]||!Number.isFinite(o.x)||!Number.isFinite(o.z))throw new Error('Invalid object in room file');const before=clone(getScene());onScene(clone(s));changed(before);toast('Imported into your draft. Save to apply.');}catch(e){toast(e.message);}file.value='';}
 function key(e){if(root.hidden||/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redoScene():undoScene();}if(e.key==='Delete'||e.key==='Backspace')remove();if(e.key.toLowerCase()==='r'&&selected)mutate(s=>{const o=s.objects.find(o=>o.id===selected);if(o)o.rotation=((o.rotation||0)+90)%360;});}
 window.addEventListener('keydown',key);
 return {attachRoom,pick,select,save:saveScene,receiveScene,isDirty:()=>dirty,isSaving:()=>saving,getSelected:()=>selected,getTool:()=>tool,revert,exportScene,destroy(){window.removeEventListener('keydown',key);}};
}
