import {seedWorlds,clone,findPath,movePlayer,canStand,nearestWalkable,contains,pathDirection} from './worlds.js';
import {createRenderer} from './renderer.js';
import {createAreaActionController} from './actions.js';
import {roomAllows} from './permissions.js';
import {mountEditor} from './editor.js';
import {mountSocial} from './social.js';
import './social.css';
import {mountPlaces} from './places.js';
import './places.css';
import {mountQuests} from './quests.js';
import {mountMedia} from './media.js';
import './media.css';
const $=id=>document.getElementById(id);
const activeSounds=new Map();let areaActions;

const state={user:null,worlds:[],universes:[],room:null,scene:clone(seedWorlds[0].rooms[0].scene),people:[],position:{x:0,z:7},direction:0,moving:false,ready:false,online:false};
let navigation=Promise.resolve(),navigating=false,surfaceBackPending=false,pendingSurface=null;
let renderer=null,editor=null,social=null,media=null,quests=null,places=null,events=null,keys=new Set(),path=[],joystick={x:0,z:0},building=false,presenceAt=0,presenceBusy=false,emote='',emoteUntil=0,nearby=null,currentAreas=new Set(),joinEpoch=0,lastTime=0,toastTimer=0,selectedWoka=0,unread=0,dragStart=null;
async function api(url,{method='GET',body}={}){const res=await fetch(url,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let data;try{data=await res.json();}catch{data={message:'The server returned an unreadable response'};}if(!res.ok){const err=new Error(data.message||data.error||'Request failed');err.status=res.status;err.data=data;throw err;}return data;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4300);}
function normalizePeople(people){return (people||[]).map(p=>({...p,id:p.id||p.userId,name:p.name||p.displayName||'Guest',woka:Number(p.woka)||0}));}
function renderPeople(){if(!state.user)return;if(!state.ready){renderer?.syncPeople([]);return;}const others=state.people.filter(p=>p.id!==state.user.id);renderer?.syncPeople([...others,{...state.user,...state.position,self:true,moving:state.moving,direction:state.direction,emote:emoteUntil>Date.now()?emote:''}]);$('people-count').textContent=String(others.length+1);}
function setScene(scene){state.scene=scene;renderer?.sync(scene);if(building&&editor?.getSelected())renderer?.select(editor.getSelected());updateAreas(true);}
function setOnline(ok){state.online=ok;$('connection').textContent='';const dot=document.createElement('i');$('connection').append(dot,document.createTextNode(ok?'Live room':'Reconnecting'));$('connection').className=ok?'live':'offline';}
function updateTitle(){if(!state.room){$('room-name').textContent='Find your place';$('world-name').textContent='UNIVERSE';$('room-subtitle').textContent='Choose a room or create a world';$('dock-build').disabled=true;return;}$('room-name').textContent=state.room.name;$('world-name').textContent=state.worlds.find(w=>w.id===state.room.worldId)?.name||'OUR UNIVERSE';$('room-subtitle').textContent=building?'A little imagination goes a long way':'A place to be together';$('dock-build').disabled=!renderer||!roomAllows(state.room,'canEditScene');$('dock-build').title=!renderer?'Building needs the 3D view':$('dock-build').disabled?'Ask the owner for editor access':'Build and edit this room';document.title=state.room.name+' · Universe';}
function getState(){return state;}
function joinRoom(id,options={}){if(editor?.isSaving()){const error=new Error('Wait for this room to finish saving before travelling');toast(error.message);return Promise.reject(error);}const run=()=>performJoin(id,options);navigation=navigation.then(run,run);return navigation;}
async function performJoin(id,{historyMode='push',invite}={}){if(editor?.isDirty()&&!window.confirm('You have unsaved room edits. Leave without saving?'))return;const epoch=++joinEpoch;navigating=true;path=[];keys.clear();try{const result=await api(invite?'/api/invites/'+encodeURIComponent(invite)+'/join':'/api/rooms/'+encodeURIComponent(id)+'/join',{method:'POST',body:{}});if(epoch!==joinEpoch)return;building=false;$('editor').hidden=true;$('dock-build').classList.remove('active');state.room=result.room;state.scene=clone(result.room.scene);state.people=normalizePeople(result.presence);for(const member of result.members||[]){const person=state.people.find(p=>p.id===member.id);if(person)Object.assign(person,{role:member.role,tags:member.tags||[],mutedUntil:member.mutedUntil});}{let arrival=clone(state.scene.spawn);const occupied=state.people.filter(p=>p.id!==state.user.id);for(let i=0;i<32&&occupied.some(p=>Math.hypot(p.x-arrival.x,p.z-arrival.z)<1);i++){const angle=i*Math.PI/4,r=1.3+Math.floor(i/8)*.7;arrival=nearestWalkable(state.scene,{x:state.scene.spawn.x+Math.cos(angle)*r,z:state.scene.spawn.z+Math.sin(angle)*r});}state.position=nearestWalkable(state.scene,arrival);}currentAreas.clear();areaActions?.clear();renderer?.sync(state.scene);renderer?.setBuild(false);editor.attachRoom();updateTitle();renderPeople();social.render();media.update();state.ready=true;quests?.refresh();setOnline(true);$('welcome').hidden=true;const u=new URL(location.href);u.searchParams.set('room',state.room.id);u.searchParams.delete('invite');history[historyMode==='replace'?'replaceState':'pushState']({room:state.room.id},'',u);updateAreas(true);sendPresence(true);$('game').focus();}catch(e){toast(e.message);throw e;}finally{navigating=false;}}
async function loadSession(session){state.user=session.user;state.worlds=session.worlds||[];state.universes=session.universes||[];if(!state.worlds.length){const res=await api('/api/worlds');state.worlds=res.worlds;}
 const desired=new URL(location.href).searchParams;const invite=desired.get('invite');const room=desired.get('room')||session.currentRoomId||'commons';
 connectEvents();let admitted=false;try{await joinRoom(room,{historyMode:'replace',invite});admitted=state.ready;}catch{if(room!=='commons')try{await joinRoom('commons',{historyMode:'replace'});admitted=state.ready;}catch{}}if(!admitted){state.ready=false;state.room=null;state.people=[];$('welcome').hidden=true;renderer?.syncPeople([]);const url=new URL(location.href);url.searchParams.delete('room');url.searchParams.delete('invite');history.replaceState({room:null},'',url);updateTitle();places?.open(invite?'invitations':'explore');} }
function connectEvents(){events?.close();events=new EventSource('/api/events');events.onopen=()=>{setOnline(true);if(state.room){api('/api/rooms/'+state.room.id).then(data=>{if(data.room.id!==state.room?.id)return;state.people=normalizePeople(data.presence);if(!editor.isDirty())editor.receiveScene(data.room);renderPeople();social.render();}).catch(()=>{});}};events.onerror=()=>setOnline(false);
 for(const type of ['hello','presence','scene','message','dm','members','role','room','moderation','media-policy','media-signal','quest','catalog','access-revoked','membership','invitation'])events.addEventListener(type,event=>{let data;try{data=JSON.parse(event.data);}catch{return;}handleEvent({type,data});});}
async function refreshCatalog(){if(!state.user)return;try{const data=await api('/api/worlds');state.worlds=data.worlds||[];if(data.universes)state.universes=data.universes;updateTitle();social.render();places?.refresh();}catch(error){if(error.status!==401)toast('The place directory could not refresh. Try again.');}}
function handleEvent(event){const {type,data}=event;const thisRoom=!data.roomId||data.roomId===state.room?.id;if(type==='presence'&&thisRoom){state.people=normalizePeople(data.presence);renderPeople();}
 if(type==='catalog')refreshCatalog();if(type==='invitation'&&!places?.isOpen()){$('places-alert').hidden=false;}
 if(type==='access-revoked'&&thisRoom){state.ready=false;keys.clear();path=[];joystick={x:0,z:0};areaActions?.clear();quests?.cancelWalk();if(state.room){state.room.role='guest';state.room.capabilities={canEditScene:false,canEditMetadata:false,canModerate:false,canManageMembers:false,canInvite:false};}if(building)toggleBuild(false,{record:false});renderer?.syncPeople([]);media.update();quests?.refresh();updateTitle();const actions=[];if(editor.isDirty())actions.push({label:'Export my unsaved draft',run:()=>editor.exportScene()});actions.push({label:'Browse accessible places',run:()=>places?.open('explore')});showDialog({eyebrow:'ROOM ACCESS CHANGED',title:'You’ve left this room',text:data.reason||'Your permission to visit this room changed. Your draft is kept so you can save a copy.',actions});}
 if(type==='scene'&&thisRoom){editor.receiveScene(data.room);}
 if(type==='members'&&thisRoom){for(const member of data.members||[]){const person=state.people.find(p=>p.id===(member.id||member.userId));if(person)Object.assign(person,{role:member.role,mutedUntil:member.mutedUntil});}}
 if(type==='role'&&thisRoom){state.room.role=data.role;state.room.capabilities=data.capabilities||data.room?.capabilities;if(building&&!roomAllows(state.room,'canEditScene')){toggleBuild(false,{record:false});if(editor.isDirty())showDialog({eyebrow:'EDITOR ACCESS CHANGED',title:'Keep a copy of your work',text:'Your editor access was removed. You can export the unsaved draft before leaving this room.',actions:[{label:'Export my draft',run:()=>editor.exportScene()}]});else toast('Your editor access changed');}updateTitle();}
 if(type==='room'&&thisRoom&&data.room){state.room={...state.room,...data.room};updateTitle();}
 if(type==='moderation'&&thisRoom&&['kick','ban','deleted'].includes(data.action)&&(data.userId===state.user?.id||data.action==='deleted')){state.ready=false;path=[];state.people=[];renderer?.syncPeople([]);toast('You left this room: '+data.action);social.setTab('explore');}
 if((type==='message'&&thisRoom||type==='dm')&&data.message?.author?.id!==state.user?.id&&$('social').hidden){unread++;$('unread').textContent=unread;$('unread').hidden=false;}
 social.onEvent(event);media.onEvent(event);quests?.onEvent(event);places?.onEvent(event);}
function rememberSurface(surface){if(!state.user)return;if(surfaceBackPending){pendingSurface=surface;return;}const current=history.state||{};if(current.room===(state.room?.id||null)&&current.surface===surface)return;const next={room:state.room?.id||null,surface};history[current.surface?'replaceState':'pushState'](next,'',location.href);}
function dismissSurface(surface){if(history.state?.surface===surface&&!surfaceBackPending){surfaceBackPending=true;history.back();}}
function togglePanel(tab){if(!state.user)return;if(tab==='explore'){if(places?.isOpen())places.close();else places?.open('explore');return;}const same=$('social').dataset.tab===tab&&!$('social').hidden;if(same){$('social').hidden=true;clearActive();dismissSurface(tab);return;}if(building)toggleBuild(false,{record:false});if(places?.isOpen())places.close();$('social').hidden=false;social.setTab(tab);rememberSurface(tab);clearActive();$('dock-'+tab)?.classList.add('active');if(tab==='chat'){unread=0;$('unread').hidden=true;}}
function clearActive(){for(const b of document.querySelectorAll('#dock [data-panel]'))b.classList.remove('active');}
function toggleBuild(force,{record=true}={}){if(force!==false&&(!state.room||!roomAllows(state.room,'canEditScene'))){toast('The room owner can grant you editor access');return;}building=force??!building;if(record){if(building)rememberSurface('build');else dismissSurface('build');}$('editor').hidden=!building;$('dock-build').classList.toggle('active',building);$('room-subtitle').textContent=building?'A little imagination goes a long way':'A place to be together';if(building){if(places?.isOpen())places.close();$('social').hidden=true;clearActive();path=[];keys.clear();editor.attachRoom();}renderer?.setBuild(building);if(building&&editor.getSelected())renderer?.select(editor.getSelected());}
function showDialog({eyebrow,title,text,actions=[]}){rememberSurface('dialog');$('dialog-eyebrow').textContent=eyebrow||'UNIVERSE';$('dialog-title').textContent=title;$('dialog-content').textContent=text||'';$('dialog-actions').replaceChildren();for(const action of actions){const b=document.createElement('button');b.className='primary';b.textContent=action.label;b.onclick=()=>{closeDialog(false);history.replaceState({room:state.room.id},'',location.href);action.run();};$('dialog-actions').append(b);}$('dialog').hidden=false;keys.clear();path=[];$('dialog-close').focus();}
function closeDialog(record=true){$('dialog').hidden=true;if(record)dismissSurface('dialog');$('game').focus();}
function openUrl(url){try{const u=new URL(url,location.origin);if(!['https:','http:'].includes(u.protocol))throw Error();window.open(u.href,'_blank','noopener,noreferrer');}catch{toast('This item needs a valid http or https address');}}
function interact(o=nearby){if(!o)return;if(o.target){joinRoom(o.target).catch(()=>{});return;}const actions=o.url?[{label:o.document?'Download document ↓':'Open website ↗',run:()=>{if(o.document){const link=document.createElement('a');link.href=o.url;link.download=o.document.name;link.click();}else openUrl(o.url);}}]:[];showDialog({eyebrow:o.document?'ROOM DOCUMENT':o.type==='screen'?'ROOM SCREEN':'ROOM ITEM',title:o.name,text:o.text||(o.document?o.document.name+' · '+Math.ceil(o.document.size/1024)+' KB · protected room download':o.url?'Open this linked content in a new browser tab.':'This '+o.type+' was placed by the room’s creators.'),actions});}
function updateAreas(force=false){if(!state.scene||!state.user)return;const active=state.scene.areas.filter(a=>contains(a,state.position.x,state.position.z));const next=new Set(active.map(a=>a.id));for(const a of active){if(!currentAreas.has(a.id)&&!building&&!navigating){if(a.action==='teleport'&&a.target){joinRoom(a.target).catch(()=>{});return;}if(a.action==='link'&&a.url)showDialog({eyebrow:'AREA LINK',title:a.name,text:a.message||'This area links to external content.',actions:[{label:'Open website ↗',run:()=>openUrl(a.url)}]});}}
 areaActions?.update(state.room?.id,state.scene,state.position,{suppressed:building||!state.ready});currentAreas=next;const area=active.find(a=>['silent','meeting','stage','audience'].includes(a.action))||active[0];$('area-banner').hidden=!area||building;if(area){$('area-name').textContent=area.name;const defaults={silent:'Quiet garden · proximity is paused',meeting:'Meeting area · connect when you’re ready',stage:'Stage · authorized speakers can broadcast',audience:'Audience · listen to the stage'};$('area-message').textContent=area.message||defaults[area.action]||'';}
 const useable=state.scene.objects.filter(o=>o.target||o.url||o.text||['screen','board','portal'].includes(o.type));nearby=useable.filter(o=>Math.hypot(o.x-state.position.x,o.z-state.position.z)<2.4).sort((a,b)=>Math.hypot(a.x-state.position.x,a.z-state.position.z)-Math.hypot(b.x-state.position.x,b.z-state.position.z))[0];$('interaction').hidden=!nearby||building||!$('dialog').hidden;if(nearby){$('interaction-label').textContent=nearby.name;$('interact').textContent=nearby.target?'E · Travel':'E · Open';}}
async function sendPresence(force=false){if(!state.ready||presenceBusy||!state.user||!state.room)return;const now=performance.now();if(!force&&now-presenceAt<(state.moving?140:1500))return;presenceAt=now;presenceBusy=true;try{await api('/api/presence',{method:'POST',body:{roomId:state.room.id,...state.position,moving:state.moving,direction:state.direction,emote:emoteUntil>Date.now()?emote:null}});}catch(e){if(e.status===401){state.ready=false;$('welcome').hidden=false;}else if(e.status!==429)setOnline(false);}finally{presenceBusy=false;}}
function isTyping(){return /INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName)||document.activeElement?.isContentEditable;}
function update(dt,actualDt=dt){quests?.setSuppressed(places?.isOpen()||building||!$('social').hidden||!$('media').hidden||!$('dialog').hidden||isTyping());if(renderer&&state.ready&&!navigating&&!building&&!quests?.isOpen()&&!places?.isOpen()&&!isTyping()&&$('dialog').hidden&&$('welcome').hidden){let sx=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0)+joystick.x,sy=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0)+joystick.z;const manual=Math.hypot(sx,sy)>.05;let dx=0,dz=0;if(manual){if(quests?.isWalking?.())quests.cancelWalk();path=[];const len=Math.max(1,Math.hypot(sx,sy));sx/=len;sy/=len;const a=renderer?.getCameraAngle()??Math.PI/4;dx=(-Math.sin(a)*sx+Math.cos(a)*sy);dz=(Math.cos(a)*sx+Math.sin(a)*sy);}else if(path.length){const direction=pathDirection(state.position,path);dx=direction.x;dz=direction.z;}
 const speed=keys.has('Shift')?5.4:3.9;const old=state.position;state.position=movePlayer(state.scene,old,dx*speed*dt,dz*speed*dt);state.moving=Math.hypot(state.position.x-old.x,state.position.z-old.z)>.0001;if(state.moving){state.direction=Math.abs(dx)>Math.abs(dz)?(dx>0?2:1):(dz>0?0:3);}else if(path.length&&!manual&&Math.hypot(dx,dz)>.01)path=[];updateAreas();}else state.moving=false;
 renderPeople();renderer?.setTarget(state.position.x,state.position.z);renderer?.render(dt,actualDt);sendPresence();$('coords').textContent=state.position.x.toFixed(1)+' / '+state.position.z.toFixed(1);}
function loop(time){const actualDt=(time-lastTime)/1000||.016,dt=Math.min(.05,actualDt);lastTime=time;update(dt,actualDt);requestAnimationFrame(loop);}
function setupControls(){for(const b of document.querySelectorAll('#dock [data-panel]'))b.onclick=()=>togglePanel(b.dataset.panel);$('dock-build').onclick=()=>toggleBuild();$('dock-media').onclick=()=>{$('media').hidden=!$('media').hidden;$('dock-media').classList.toggle('active',!$('media').hidden);};$('dock-emote').onclick=()=>$('emotes').hidden=!$('emotes').hidden;for(const b of document.querySelectorAll('[data-emote]'))b.onclick=()=>{emote=b.dataset.emote;emoteUntil=Date.now()+4500;$('emotes').hidden=true;api('/api/rooms/'+state.room.id+'/emote',{method:'POST',body:{emoji:emote}}).catch(e=>toast(e.message));sendPresence(true);};
 $('manage-place').onclick=()=>places?.open('manage');$('places-alert').onclick=()=>{$('places-alert').hidden=true;places?.open('invitations');};$('quest-open').onclick=()=>quests?.open();$('zoom-in').onclick=()=>renderer?.zoom(-2);$('zoom-out').onclick=()=>renderer?.zoom(2);$('rotate-camera').onclick=()=>renderer?.rotate(Math.PI/2);$('home-camera').onclick=()=>{state.position=nearestWalkable(state.scene,state.scene.spawn);path=[];sendPresence(true);};$('interact').onclick=()=>interact();$('dialog-close').onclick=()=>closeDialog();$('dialog').onclick=e=>{if(e.target===$('dialog'))closeDialog();};$('invite').onclick=async()=>{if(!state.room){places?.open('explore');return;}const url=new URL(location.href);url.searchParams.set('room',state.room.id);try{await navigator.clipboard.writeText(url.href);toast('Room link copied. This shares the location; private access still needs membership.');}catch{showDialog({title:'Invite someone in',text:url.href});}};
 window.addEventListener('session-ended',()=>{editor.revert();location.reload();});window.addEventListener('social-close',()=>{clearActive();const surface=history.state?.surface;if(['chat','people','explore','settings'].includes(surface))dismissSurface(surface);});window.addEventListener('profile-updated',()=>{renderPeople();sendPresence(true);});window.addEventListener('avatar-emote',e=>{emote=e.detail.emoji;emoteUntil=Date.now()+4500;renderPeople();sendPresence(true);});document.addEventListener('focusin',()=>{if(isTyping()){keys.clear();path=[];joystick={x:0,z:0};}});window.addEventListener('editor-status',e=>{$('dirty-dot').hidden=!e.detail.dirty;});
 window.addEventListener('keydown',e=>{if(isTyping()||!$('welcome').hidden||quests?.isOpen()||places?.isOpen())return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(k)){e.preventDefault();keys.add(k);}else if(k==='Shift')keys.add(k);else if(k==='b')toggleBuild();else if(k==='e'&&!building)interact();else if(k==='Escape'){keys.clear();path=[];closeDialog();$('social').hidden=true;clearActive();$('emotes').hidden=true;if(building)toggleBuild(false);}else if(k==='Enter'&&$('dialog').hidden)togglePanel('chat');});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{keys.clear();joystick={x:0,z:0};});document.addEventListener('visibilitychange',()=>{keys.clear();if(!document.hidden)sendPresence(true);});
 $('game').addEventListener('pointerdown',e=>{dragStart={x:e.clientX,y:e.clientY};});$('game').addEventListener('pointerup',e=>{if(!state.ready||places?.isOpen()||quests?.isOpen()||!renderer||!dragStart||Math.hypot(e.clientX-dragStart.x,e.clientY-dragStart.y)>10)return;dragStart=null;const hit=renderer.pick(e.clientX,e.clientY);if(building){editor.pick(hit);return;}if(hit.id){const o=state.scene.objects.find(o=>o.id===hit.id);if(o&&(o.target||o.url||o.text)){if(Math.hypot(o.x-state.position.x,o.z-state.position.z)<2.7){interact(o);return;}let goal=nearestWalkable(state.scene,{x:o.x,z:o.z+1.6});path=findPath(state.scene,state.position,goal);toast('Walk closer to '+o.name);return;}}if(hit.point)path=findPath(state.scene,state.position,hit.point);$('game').focus();});
 $('game').addEventListener('wheel',e=>{e.preventDefault();renderer?.zoom(Math.sign(e.deltaY)*.8);},{passive:false});
 let touchId=null;$('joystick').addEventListener('pointerdown',e=>{touchId=e.pointerId;$('joystick').setPointerCapture(e.pointerId);moveStick(e);});$('joystick').addEventListener('pointermove',e=>{if(touchId===e.pointerId)moveStick(e);});const stopStick=()=>{touchId=null;joystick={x:0,z:0};$('joystick-thumb').style.transform='';};$('joystick').addEventListener('pointerup',stopStick);$('joystick').addEventListener('pointercancel',stopStick);function moveStick(e){const r=$('joystick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.max(32,Math.hypot(dx,dy));joystick={x:dx/d,z:dy/d};$('joystick-thumb').style.transform=`translate(${joystick.x*27}px,${joystick.z*27}px)`;}
 window.addEventListener('popstate',()=>{surfaceBackPending=false;if(pendingSurface){const pending=pendingSurface;pendingSurface=null;rememberSurface(pending);}const room=new URL(location.href).searchParams.get('room');if(room&&room!==state.room?.id){joinRoom(room,{historyMode:'replace'}).catch(()=>{});return;}const surface=history.state?.surface==='explore'?'places':history.state?.surface;if(history.state?.surface==='explore')history.replaceState({...history.state,surface:'places'},'',location.href);if(!['chat','people','settings'].includes(surface)){$('social').hidden=true;clearActive();}else{social.setTab(surface);clearActive();$('dock-'+surface)?.classList.add('active');}if(surface==='places'&&!places?.isOpen())places?.open('explore');else if(surface!=='places'&&places?.isOpen())places.close();if(surface==='quests'&&!quests?.isOpen())quests?.open();else if(surface!=='quests'&&quests?.isOpen())quests.close();if(surface!=='dialog')$('dialog').hidden=true;else $('dialog').hidden=false;if(surface==='build'&&!building)toggleBuild(true,{record:false});if(surface!=='build'&&building){building=false;$('editor').hidden=true;$('dock-build').classList.remove('active');renderer?.setBuild(false);updateTitle();}});window.addEventListener('beforeunload',e=>{if(editor.isDirty()){e.preventDefault();e.returnValue='';}});}
async function boot(){areaActions=createAreaActionController({enter:({area,action,key})=>{const holder=document.createElement('div');holder.className='area-action-control';const button=document.createElement('button');holder.append(button);$('area-sounds').append(holder);const entry={holder,audio:null};activeSounds.set(key,entry);
if(action.type==='message'){button.textContent='ⓘ '+area.name;button.onclick=()=>showDialog({eyebrow:'AREA MESSAGE',title:area.name,text:action.message});toast(action.message);}
if(action.type==='link'){button.textContent='↗ '+(action.label||'Open website');button.onclick=()=>showDialog({eyebrow:area.name,title:action.label||'Explore this link',text:action.url,actions:[{label:'Open website ↗',run:()=>openUrl(action.url)}]});}
if(action.type==='teleport'){button.textContent='→ Travel to '+action.target;button.onclick=()=>joinRoom(action.target).catch(()=>{});}
if(action.type==='audio'){button.textContent='♫ Listen · '+area.name;button.onclick=async()=>{if(!activeSounds.has(key))return;if(entry.audio){entry.audio.pause();entry.audio=null;button.textContent='♫ Listen · '+area.name;return;}const audio=new Audio(action.url);audio.loop=!!action.loop;audio.volume=action.volume??.5;entry.audio=audio;try{await audio.play();button.textContent='■ Stop room sound';}catch{entry.audio=null;toast('This sound could not play. Check its URL and browser permissions.');}};}},leave:({key})=>{const entry=activeSounds.get(key);if(entry){entry.audio?.pause();entry.holder.remove();activeSounds.delete(key);}}});for(let i=0;i<6;i++){const b=document.createElement('button');b.type='button';b.className='woka-option'+(i===0?' selected':'');b.ariaLabel='Choose Woka '+(i+1);b.ariaPressed=String(i===0);const s=document.createElement('span');s.className='woka-sprite';s.style.backgroundImage=`url('/assets/woka-${i}.png')`;b.append(s);b.onclick=()=>{selectedWoka=i;for(const [n,b]of [...$('woka-options').children].entries()){b.classList.toggle('selected',n===i);b.ariaPressed=String(n===i);}};$('woka-options').append(b);}
 editor=mountEditor({root:$('editor'),getState,onScene:setScene,onSelect:id=>renderer?.select(id),api,toast,onClose:()=>toggleBuild(false)});social=mountSocial({root:$('social'),api,getState,onNavigate:id=>joinRoom(id).catch(()=>{}),onExplore:()=>places?.open('explore'),onManage:()=>places?.open('manage'),toast});media=mountMedia({root:$('media'),api,getState,toast});quests=mountQuests({root:$('quests'),api,getContext:()=>({user:state.user,room:state.room,ready:state.ready,busy:places?.isOpen()||building||!$('social').hidden||!$('media').hidden||!$('dialog').hidden}),onGuide:target=>renderer?.setGuide(target?.roomId===state.room?.id?target:null),onWalk:async target=>{if(target.roomId!==state.room?.id)await joinRoom(target.roomId);const landing=nearestWalkable(state.scene,{x:target.x,z:target.z});path=findPath(state.scene,state.position,landing);renderer?.setGuide(target);},onCancelWalk:()=>{path=[];},onOpenEditor:()=>toggleBuild(true),onRegister:()=>togglePanel('settings'),onOpenChange:open=>{keys.clear();path=[];joystick={x:0,z:0};if(open){rememberSurface('quests');if(building)toggleBuild(false,{record:false});$('social').hidden=true;clearActive();}else dismissSurface('quests');}});places=mountPlaces({root:$('places'),api,getState,onNavigate:id=>joinRoom(id),onChanged:()=>refreshCatalog(),toast,onOpenChange:open=>{keys.clear();path=[];joystick={x:0,z:0};if(open){rememberSurface('places');if(building)toggleBuild(false,{record:false});if(quests?.isOpen())quests.close();$('social').hidden=true;clearActive();$('dock-explore').classList.add('active');}else{dismissSurface('places');$('dock-explore').classList.remove('active');}}});setupControls();
 try{renderer=await createRenderer($('game'),$('labels'));renderer.sync(state.scene);renderer.syncPeople([{id:'welcome',name:'Your story starts here',woka:0,x:0,z:7,self:true}]);await renderer.ready;}catch(e){console.error('3D renderer unavailable',e);$('joystick').hidden=true;$('view-controls').hidden=true;$('controls-hint').hidden=true;$('fallback-message').textContent='The 3D view could not start in this browser. You can still use room chat, people, and navigation. Try a WebGL-capable browser for movement and building.';$('fallback-enter').onclick=()=>{$('fallback').hidden=true;togglePanel('chat');};}
 requestAnimationFrame(loop);$('show-login').onclick=()=>{const login=$('login-form').hidden;$('login-form').hidden=!login;$('join-form').hidden=login;$('show-login').textContent=login?'Start with a new guest profile':'Already have a local account?';if(login)$('login-username').focus();};$('login-form').onsubmit=async e=>{e.preventDefault();$('login-button').disabled=true;$('login-error').textContent='';try{const session=await api('/api/login',{method:'POST',body:{username:$('login-username').value.trim(),password:$('login-password').value}});$('login-password').value='';await loadSession(session);}catch(error){$('login-error').textContent=error.message;}finally{$('login-button').disabled=false;}};$('join-form').onsubmit=async e=>{e.preventDefault();$('join-button').disabled=true;$('join-error').textContent='';try{await loadSession(await api('/api/session',{method:'POST',body:{name:$('display-name').value.trim(),woka:selectedWoka}}));if(!renderer)$('fallback').hidden=false;}catch(e){$('join-error').textContent=e.message;}finally{$('join-button').disabled=false;}};
 try{const session=await api('/api/session');await loadSession(session);if(!renderer)$('fallback').hidden=false;}catch(e){if(e.status!==401)$('join-error').textContent='The server is not ready. Please retry in a moment.';}
 window.__universe={getState:()=>clone({...state,scene:state.scene}),getStats:()=>renderer?.getStats(),getScreenPoint:(x,z,y=0)=>renderer?.screenPoint(x,z,y),getEditor:()=>({dirty:editor.isDirty(),selected:editor.getSelected(),tool:editor.getTool()}),getPath:()=>clone(path)};
}
boot().catch(e=>{console.error(e);toast('Could not open Universe: '+e.message);});
