import {Workshop,createDocument,createFurniture,validate,parse,serialize,LIMITS} from '../modules/asset-workshop/model.js';
import {createView} from '../modules/asset-workshop/view.js';
import {bindCompositionDefinitions,compositionDefinitions} from './composition-context.js';
import './workshop.css';
const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node;};
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const typing=target=>!!target?.closest('input,select,textarea,[contenteditable]');
const uid=()=>crypto.randomUUID();

export function mountWorkshop({root,getState,api,onChoose,onUpdate=()=>false,onOpenChange=()=>{},onDefinitions=()=>{},toast=()=>{}}){
 let editor=new Workshop(),view=null,opened=false,mode='edit',snap=.25,multi=false,pending=null,gesture=null,blockedTouches=false;
 let savedText=serialize(editor.doc),source=null,assets=[],loading=false,refreshAgain=false,saving=false,epoch=0,context=null,returnFocus=null,operation=null,editingInstance=null,draftGeneration=0,openRequest=0,importRequest=0,requestController=null;
 const pointers=new Set();
 root.className='furniture-workshop';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.ariaLabel='Furniture workshop';
 const shell=el('div','workshop-shell'),header=el('header','workshop-header'),brand=el('div','workshop-brand');
 const logo=el('img','workshop-logo');logo.src='/assets/bawes-universe-logo.png';logo.alt='BAWES Universe';const brandCopy=el('div');brandCopy.append(el('span','workshop-eyebrow','CREATE SOMETHING YOURS'),el('h2','','Furniture workshop'));brand.append(logo,brandCopy);
 function button(label,fn,{primary=false}={}){const b=el('button',primary?'primary':'',label);b.type='button';b.onclick=()=>run(fn);return b;}
 const closeButton=button('Close workshop',()=>close());header.append(brand,closeButton);
 const intro=el('p','workshop-intro','Make something that belongs here. Shape a chair, build a table, or start with one small part.');
 const identity=el('div','workshop-identity'),name=el('input');name.ariaLabel='Furniture name';name.maxLength=80;
 name.onchange=()=>run(()=>{const doc=validate(editor.doc);doc.asset.name=name.value;editor.load(doc);changed();});
 const stateLabel=el('span','workshop-save-state');identity.append(name,stateLabel);
 const actions=el('div','workshop-actions');const save=button('Save furniture',()=>publish(),{primary:true}),place=button('Place in room',()=>choose(),{primary:true});
 const undo=button('Undo',()=>{cancel();editor.undo();changed();}),redo=button('Redo',()=>{cancel();editor.redo();changed();});
 const updatePlaced=button('Update placed copy',()=>updatePlacement(),{primary:true});updatePlaced.hidden=true;
 actions.append(save,place,updatePlaced,button('Save as new copy',()=>{if(locked())throw Error('Resolve the pending save before making a copy');source=null;operation=null;return publish();}),undo,redo,button('Save JSON',download),button('Open JSON',()=>input.click()));
 const nav=el('nav','workshop-section-nav');for(const [id,label]of [['shapes','Shapes'],['canvas','Canvas'],['parts','Parts'],['library','Saved']]){const link=el('a','',label);link.href='#workshop-'+id;nav.append(link);}
 const work=el('div','workshop-workbench'),shapes=el('section','workshop-shapes');shapes.id='workshop-shapes';shapes.append(el('h3','','Start making'));
 const starters=el('div','workshop-starters');starters.append(button('Start a chair',()=>start('chair')),button('Start a table',()=>start('table')),button('Empty composition',()=>start()));shapes.append(starters,el('h3','','Add a part'));
 const palette=el('div','workshop-primitives');for(const [shape,label,glyph]of [['box','Box','▰'],['cylinder','Cylinder','▥'],['sphere','Sphere','●'],['wedge','Wedge','◭']]){const b=button(label,()=>preview(shape));b.ariaLabel=label;const shapeIcon=el('span','workshop-shape-icon',glyph);shapeIcon.setAttribute('aria-hidden','true');b.prepend(shapeIcon);palette.append(b);}shapes.append(palette);
 const snapLabel=el('label','','Snap'),snapInput=el('select');snapInput.ariaLabel='Workshop snap';for(const [value,label]of [['0','Off'],['0.1','0.1 m'],['0.25','0.25 m'],['0.5','0.5 m'],['1','1 m']]){const option=el('option','',label);option.value=value;snapInput.append(option);}snapInput.value=String(snap);snapInput.onchange=()=>{cancel();snap=Number(snapInput.value);};snapLabel.append(snapInput);shapes.append(snapLabel);
 const multiLabel=el('label','workshop-check'),multiInput=el('input');multiInput.type='checkbox';multiInput.ariaLabel='Multi-select parts';multiInput.onchange=()=>{multi=multiInput.checked;};multiLabel.append(multiInput,document.createTextNode('Multi-select'));shapes.append(multiLabel);
 const stage=el('section','workshop-stage');stage.id='workshop-canvas';const cameraTools=el('div','workshop-camera-tools');
 const editButton=button('Edit',()=>setMode('edit')),cameraButton=button('Camera',()=>setMode('camera'));
 cameraTools.append(editButton,cameraButton,button('Frame asset',()=>view?.focus(editor.doc)),button('Orbit left',()=>view?.orbit(-.2)),button('Orbit right',()=>view?.orbit(.2)),button('Zoom in',()=>view?.zoom(-.6)),button('Zoom out',()=>view?.zoom(.6)));
 const canvas=el('canvas','workshop-canvas');canvas.tabIndex=0;canvas.ariaLabel='Furniture preview: select and drag parts in Edit mode';
 const previewTools=el('div','workshop-preview-tools'),placePart=button('Place at preview',commitPreview),cancelPart=button('Cancel preview',()=>{cancel();changed('Preview cancelled');});previewTools.append(placePart,cancelPart);
 stage.append(cameraTools,canvas,previewTools);
 const parts=el('section','workshop-parts');parts.id='workshop-parts';const count=el('span','workshop-count');parts.append(el('h3','','Your parts'),count);
 const list=el('div','workshop-part-list');list.setAttribute('role','group');list.ariaLabel='Composition parts';parts.append(list);
 const selectionTools=el('div','workshop-selection-tools');selectionTools.append(button('Duplicate parts',()=>mutate(()=>editor.duplicate())),button('Delete parts',()=>mutate(()=>editor.delete())),button('Group parts',()=>mutate(()=>editor.group())),button('Ungroup parts',()=>mutate(()=>editor.ungroup())));parts.append(selectionTools);
 const inspector=el('div','workshop-inspector');parts.append(inspector);
 work.append(shapes,stage,parts);
 const status=el('p','workshop-status','Choose a starter or add your first part.');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const library=el('section','workshop-library');library.id='workshop-library';const libraryHead=el('div','workshop-library-heading');libraryHead.append(el('h3','','Made for this room'),button('Refresh furniture',refresh));const libraryList=el('div','workshop-library-list');library.append(libraryHead,libraryList);
 const help=el('details','workshop-help');help.append(el('summary','','Keyboard & touch controls'),el('p','','Edit: drag on the ground plane, with height preserved. Select a part or enable Multi-select. Arrows move X/Z; Shift+Up/Down moves Y. R rotates, D duplicates, Delete removes. Enter places the preview. Ctrl/Cmd+Z undoes; Shift+Z redoes. Camera mode: drag to orbit, pinch to zoom. A second finger cancels an Edit gesture. Numeric values are exact; snap applies to ground placement and dragging. Saved revisions stay pinned in the room until you explicitly replace a placement.'));
 const input=el('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.onchange=async()=>{const file=input.files?.[0];input.value='';if(!file||locked())return;const token=epoch,request=++importRequest,generation=draftGeneration;if(file.size>LIMITS.bytes)return say('Furniture JSON is limited to 256 KiB');try{const text=await file.text();if(!current(token)||request!==importRequest||generation!==draftGeneration||locked())return;const doc=parse(text);cancel();editor.load(doc);source=null;operation=null;changed('Opened an editable composition');view?.focus(editor.doc);}catch(error){if(current(token))say(error.message);}};
 shell.append(header,intro,identity,actions,nav,work,status,library,help,input);root.append(shell);
 function say(message){status.textContent=message;}
 function run(fn){try{const result=fn();if(result?.catch)result.catch(error=>say(error.message));}catch(error){say(error.message);}}
 function locked(){return saving||operation?.unknown===true;}
 function dirty(){return serialize(editor.doc)!==savedText;}
 function authority(){const s=getState();return !!(s.ready&&s.room?.id===context?.roomId&&s.user?.id===context?.userId&&s.room?.capabilities?.canEditScene);}
 function current(token){const s=getState();return opened&&epoch===token&&s.room?.id===context?.roomId&&s.user?.id===context?.userId;}
 function render(){
  name.value=editor.doc.asset.name;root.dataset.parts=String(editor.doc.components.length);root.dataset.dirty=String(dirty());root.dataset.mode=mode;
  stateLabel.textContent=saving?'Saving…':operation?.unknown?'Save result unknown · Retry the same save':source?'Revision '+source.revision+(dirty()?' · Unsaved edits':' · Saved in this room'):'Not saved to this room';
  save.textContent=operation?.unknown?'Retry save':'Save furniture';work.inert=locked();save.disabled=saving||!authority()||!editor.doc.components.length;place.disabled=saving||!source||source.status!=='active'||dirty()||!getState().ready;updatePlaced.hidden=!editingInstance;updatePlaced.disabled=place.disabled;
  undo.disabled=!editor.canUndo||locked();redo.disabled=!editor.canRedo||locked();name.disabled=locked();
  placePart.disabled=!pending;cancelPart.disabled=!pending&&!gesture;editButton.setAttribute('aria-pressed',String(mode==='edit'));cameraButton.setAttribute('aria-pressed',String(mode==='camera'));
  count.textContent=editor.doc.components.length+' / 128 parts';list.replaceChildren();
  for(const part of editor.doc.components){const b=button(part.name,()=>{cancel();editor.select(part.id,{additive:multi,toggle:multi});render();});b.dataset.partId=part.id;b.setAttribute('aria-pressed',String(editor.selection.has(part.id)));b.append(el('small','',part.shape+(part.groupId?' · grouped':'')));list.append(b);}
  inspect();view?.update(editor.doc,editor.selection,pending);
 }
 function changed(message){draftGeneration++;operation=null;render();if(message)say(message);}
 function mutate(fn){if(locked())return;cancel();fn();changed();}
 function field(label,value,change,{type='number',step='.05',options}={}){const wrap=el('label','',label),i=el(options?'select':'input');i.ariaLabel=label;if(options)for(const [v,text]of options){const o=el('option','',text);o.value=v;i.append(o);}else{i.type=type;if(type==='number')i.step=step;}i.value=String(value);i.disabled=saving;i.onchange=()=>run(()=>{change(options||type!=='number'?i.value:Number(i.value));changed();});wrap.append(i);return wrap;}
 function inspect(){
  inspector.replaceChildren();const selected=editor.selected;if(!selected.length){inspector.append(el('p','','Select a part to shape it.'));return;}
  inspector.append(el('h3','',selected.length===1?'Shape this part':selected.length+' parts selected'));
  if(selected.length===1){const p=selected[0];inspector.append(field('Part name',p.name,v=>editor.patch({name:v}),{type:'text'}));for(const [i,axis]of ['X','Y','Z'].entries()){inspector.append(field('Position '+axis,p.position[i],v=>{const position=[...p.position];position[i]=v;editor.patch({position});}),field('Size '+axis,p.size[i],v=>{const size=[...p.size];size[i]=v;editor.patch({size});}));}inspector.append(field('Material',p.materialId,v=>editor.patch({materialId:v}),{options:editor.doc.materials.map(m=>[m.id,m.name])}),field('Collision',p.collision,v=>editor.patch({collision:v}),{options:[['box','Solid (conservative box)'],['none','Decorative (no collision)']]}));}
  if(selected.length===1){const p=selected[0],material=editor.doc.materials.find(m=>m.id===p.materialId);const editMaterial=changes=>{const doc=validate(editor.doc);Object.assign(doc.materials.find(m=>m.id===p.materialId),changes);editor.load(doc);editor.select(p.id);};inspector.append(field('Material color (shared)',material.color,value=>editMaterial({color:value}),{type:'color'}),field('Roughness (shared)',material.roughness,value=>editMaterial({roughness:value}),{step:'.05'}),button('Separate material',()=>mutate(()=>{const doc=validate(editor.doc),id=uid();doc.materials.push({...material,id,name:'Custom material'});doc.components.find(c=>c.id===p.id).materialId=id;editor.load(doc);editor.select(p.id);})));}
  const moves=el('div','workshop-axis-tools');for(const [index,axis]of ['X','Y','Z'].entries())for(const direction of [-1,1])moves.append(button(axis+(direction>0?' +':' −'),()=>mutate(()=>{const delta=[0,0,0];delta[index]=direction*(snap||.1);editor.move(delta);})));inspector.append(moves);
  const rotates=el('div','workshop-axis-tools');for(const axis of ['X','Y','Z'])rotates.append(button('Rotate '+axis,()=>mutate(()=>editor.rotate(axis.toLowerCase(),15))));inspector.append(rotates);
  const scale=el('div','workshop-axis-tools');scale.append(button('Smaller',()=>mutate(()=>editor.scale(.9))),button('Larger',()=>mutate(()=>editor.scale(1.1))));inspector.append(scale);
  if(selected.length>1){const align=el('div','workshop-axis-tools');for(const axis of ['X','Y','Z'])align.append(button('Align '+axis,()=>mutate(()=>editor.align(axis.toLowerCase(),'center'))));inspector.append(align);}
 }
 function cancel(){if(gesture)editor.cancel();gesture=null;pending=null;for(const id of pointers)try{canvas.releasePointerCapture(id);}catch{}pointers.clear();blockedTouches=false;view?.update(editor.doc,editor.selection);}
 function setMode(next){cancel();mode=next;view?.cameraMode(mode==='camera');render();say(mode==='camera'?'Drag to orbit; pinch or use the zoom buttons.':'Select a part or choose a shape to add.');}
 function start(kind){if(locked())return;if(dirty()&&!window.confirm('Discard unsaved furniture changes and start again?'))return;cancel();editor.load(kind?createFurniture(kind):createDocument());if(kind)editor.select(editor.doc.components.map(p=>p.id));source=null;operation=null;changed(kind?'A '+kind+' made from editable parts. Make it yours.':'An empty composition, ready for your idea.');view?.focus(editor.doc);}
 function preview(shape){if(locked())return;cancel();mode='edit';view?.cameraMode(false);pending={id:'part-preview',name:shape,shape,position:[0,.5,0],rotation:[0,0,0,1],size:[1,1,1],materialId:editor.doc.materials[0].id,groupId:null,collision:'box',valid:true};render();say('Move over the grid, then release to place your '+shape+'.');canvas.focus();}
 function snapFloor(point){return point&&[snap?Math.round(point[0]/snap)*snap:point[0],.5,snap?Math.round(point[2]/snap)*snap:point[2]];}
 function movePreview(point){if(!pending||!point)return;pending.position=snapFloor(point);try{const probe=new Workshop(editor.doc);probe.add(pending.shape,pending.position);pending.valid=true;}catch{pending.valid=false;}view?.update(editor.doc,editor.selection,pending);}
 function commitPreview(){if(!pending)return;if(!pending.valid)throw Error('Keep the new part inside the workshop bounds');const {shape,position}=pending;editor.add(shape,position);pending=null;changed('Part added. Drag it or use the exact controls.');}
 canvas.addEventListener('pointerdown',event=>{
  if(mode!=='edit'||saving||event.button!==0)return;pointers.add(event.pointerId);
  if(pointers.size>1){if(gesture)editor.cancel();gesture=null;pending=null;blockedTouches=true;render();say('Second touch cancelled the edit. Use Camera mode to pinch.');return;}
  event.preventDefault();canvas.focus();canvas.setPointerCapture(event.pointerId);if(blockedTouches)return;
  const point=view?.floor(event.clientX,event.clientY);if(pending){movePreview(point);gesture={kind:'place',pointer:event.pointerId};return;}
  const id=view?.pick(event.clientX,event.clientY);if(!id){editor.select([]);render();return;}
  if(!editor.selection.has(id)||multi)editor.select(id,{additive:multi,toggle:multi});
  if(editor.selection.size&&point){editor.begin();gesture={kind:'move',pointer:event.pointerId,start:point};}render();
 });
 canvas.addEventListener('pointermove',event=>{
  if(mode!=='edit'||blockedTouches||saving)return;const point=view?.floor(event.clientX,event.clientY);if(pending){movePreview(point);return;}
  if(gesture?.kind==='move'&&gesture.pointer===event.pointerId&&point){try{editor.previewMove([point[0]-gesture.start[0],0,point[2]-gesture.start[2]],{snap});view?.update(editor.doc,editor.selection);}catch(error){say(error.message);}}
 });
 canvas.addEventListener('pointerup',event=>{pointers.delete(event.pointerId);if(blockedTouches){if(!pointers.size)blockedTouches=false;return;}if(gesture?.pointer!==event.pointerId)return;const kind=gesture.kind;gesture=null;try{canvas.releasePointerCapture(event.pointerId);}catch{}run(()=>{if(kind==='place')commitPreview();else{editor.commit();changed('Part moved');}});});
 const interrupt=()=>{if(gesture||pending){cancel();render();say('Edit cancelled');}};canvas.addEventListener('pointercancel',interrupt);canvas.addEventListener('lostpointercapture',()=>{if(gesture)interrupt();});window.addEventListener('blur',interrupt);const visibilityHandler=()=>{if(document.hidden)interrupt();};document.addEventListener('visibilitychange',visibilityHandler);
 function download(){const url=URL.createObjectURL(new Blob([serialize(editor.doc)],{type:'application/json'})),a=el('a');a.href=url;a.download=editor.doc.asset.name.replace(/[^a-z0-9_-]/gi,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Editable furniture JSON downloaded');}
 function installDefinition(asset){const s=getState();if(s.room?.id!==asset.roomId)return;const key=asset.assetId+':'+asset.revision;s.room.compositionDefinitions={...s.room.compositionDefinitions,[key]:asset.definition};bindCompositionDefinitions(s.scene,{...compositionDefinitions(s.scene),...s.room.compositionDefinitions},s.room.id);if(s.room.scene)bindCompositionDefinitions(s.room.scene,s.room.compositionDefinitions,s.room.id);onDefinitions();}
 async function refresh(){if(!opened)return;if(loading){refreshAgain=true;return;}const token=epoch;loading=true;try{const result=await api('/api/rooms/'+encodeURIComponent(context.roomId)+'/furniture');if(!current(token))return;assets=result.assets;if(source){const latest=assets.find(a=>a.assetId===source.assetId);if(latest?.status==='archived')source={...source,status:'archived'};}renderLibrary();render();}catch(error){if(current(token))say(error.message);}finally{if(current(token)){loading=false;if(refreshAgain){refreshAgain=false;await refresh();}}}}

 function renderLibrary(){libraryList.replaceChildren();if(!assets.length)libraryList.append(el('p','','Your first saved piece will live here.'));for(const asset of assets){const card=el('article','workshop-library-card');card.append(el('strong','',asset.definition.asset.name),el('span','','Revision '+asset.revision+' · '+asset.definition.components.length+' parts'+(asset.status==='archived'?' · Archived':'')),button('Open '+asset.definition.asset.name,()=>loadAsset(asset)));if(asset.status==='active'&&authority())card.append(button('Archive '+asset.definition.asset.name,()=>archive(asset)));libraryList.append(card);}}
 function loadAsset(asset){if(locked())return;if(dirty()&&!window.confirm('Discard unsaved furniture changes and open this saved piece?'))return;cancel();editor=new Workshop(asset.definition);draftGeneration++;source=asset;operation=null;savedText=serialize(editor.doc);installDefinition(asset);render();view?.focus(editor.doc);say('Opened revision '+asset.revision+'. Saving changes creates a new revision.');}
 async function publish(){if(!authority())throw Error('Room editor access is required to save furniture');if(saving)return;cancel();const token=epoch,definition=validate(editor.doc);if(!definition.components.length)throw Error('Add at least one part before saving');
  if(!operation)operation={path:'/api/rooms/'+encodeURIComponent(context.roomId)+'/furniture'+(source?'/'+encodeURIComponent(source.assetId):''),method:source?'PUT':'POST',body:{definition,operationId:uid(),...(source?{revision:source.revision}:{})}};
  saving=true;requestController=new AbortController();const controller=requestController,timer=setTimeout(()=>controller.abort(),20000);render();try{const result=await api(operation.path,{method:operation.method,body:operation.body,signal:controller.signal});if(!current(token))return;source=result.asset;editor=new Workshop(source.definition);savedText=serialize(editor.doc);operation=null;installDefinition(source);say('Saved revision '+source.revision+'. Place it in the room when you’re ready.');await refresh();}catch(error){if(current(token)){if(error.status&&error.status<500)operation=null;else if(operation)operation.unknown=true;say((operation?.unknown?'The save result is unknown. Retry save checks the same operation without creating a duplicate.':error.message)+(error.status===409?' Open the latest saved piece or save this draft as a copy.':' You can export your JSON at any time.'));} }finally{clearTimeout(timer);if(requestController===controller)requestController=null;if(current(token)){saving=false;render();}}
 }
 async function archive(asset){if(!authority()||saving)return;if(!window.confirm('Archive '+asset.definition.asset.name+'? Existing room placements keep their saved revision.'))return;const token=epoch;saving=true;render();try{await api('/api/rooms/'+context.roomId+'/furniture/'+asset.assetId+'/archive',{method:'POST',body:{revision:asset.revision,operationId:uid()}});if(current(token)){if(source?.assetId===asset.assetId){source=null;operation=null;}await refresh();say('Archived. Existing placements are unchanged.');}}finally{if(current(token)){saving=false;render();}}}
 function updatePlacement(){if(!source||dirty()||!editingInstance||saving)throw Error('Save the edited furniture first');installDefinition(source);if(onUpdate(editingInstance,{assetId:source.assetId,revision:source.revision},source.definition.asset.name)!==false){close({force:true});toast('Placed copy updated in your draft. Save room to apply.');}}
 function choose(){if(!source||dirty()||saving)throw Error('Save this furniture before placing it');if(source.status!=='active')throw Error('Archived furniture cannot be placed');const asset=source;installDefinition(asset);if(onChoose({assetId:asset.assetId,revision:asset.revision},asset.definition.asset.name)!==false)close({force:true});}
 async function open({assetRef,instanceId,record=true,trigger=document.activeElement}={}){
  const request=++openRequest;
  if(opened){const token=epoch;editingInstance=instanceId||null;render();if(assetRef){await refresh();if(!current(token)||request!==openRequest)return false;const asset=assets.find(a=>a.assetId===assetRef.assetId);if(asset)loadAsset(asset);}return true;}
  const s=getState();if(!s.ready||!s.room)return false;
  if(context&&(context.roomId!==s.room.id||context.userId!==s.user.id)){editor=new Workshop();source=null;assets=[];savedText=serialize(editor.doc);operation=null;draftGeneration++;}
  context={roomId:s.room.id,userId:s.user.id};editingInstance=instanceId||null;const token=++epoch;returnFocus=trigger;opened=true;root.hidden=false;onOpenChange(true,{record});
  try{const created=createView(canvas);view=created;render();created.focus(editor.doc);await created.ready;if(!current(token)||request!==openRequest||view!==created)return false;canvas.focus();await refresh();if(!current(token)||request!==openRequest||view!==created)return false;if(assetRef){const asset=assets.find(a=>a.assetId===assetRef.assetId);if(asset)loadAsset(asset);else say('That furniture is unavailable in this room.');}}catch(error){if(current(token))say('The 3D preview could not start: '+error.message);}return true;
 }
 function close({force=false,record=true,restore=true}={}){if(!opened)return true;if(saving&&!force){say('Wait for this save to finish before closing');return false;}if(dirty()&&!force&&!window.confirm('Close the workshop? Your unsaved draft stays here until you leave this room.'))return false;if(saving&&operation)operation.unknown=true;cancel();opened=false;root.hidden=true;epoch++;openRequest++;importRequest++;loading=false;refreshAgain=false;saving=false;requestController?.abort();requestController=null;view?.dispose();view=null;onOpenChange(false,{record});if(restore)(returnFocus?.isConnected?returnFocus:document.getElementById('game'))?.focus({preventScroll:true});return true;}
 function syncAuthority(){if(!opened)return;const s=getState();if(s.user?.id!==context.userId||s.room&&s.room.id!==context.roomId){close({force:true,record:false});editor=new Workshop();source=null;savedText=serialize(editor.doc);assets=[];operation=null;draftGeneration++;return;}if(!s.ready||!s.room){requestController?.abort();saving=false;render();say('Room access changed. Export your local draft to keep a copy. Saving and placement are disabled.');return;}render();renderLibrary();if(!authority())say('Editor access changed. Your local draft can still be exported, but saving is disabled.');}
 function key(event){if(!opened)return;if(locked()&&event.key!=='Escape'&&event.key!=='Tab'&&!((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'))return;if(event.key==='Tab'){const controls=[...root.querySelectorAll('button,input,select,summary,a,canvas')].filter(n=>!n.disabled&&n.getClientRects().length),first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}return;}
  if(event.isComposing||event.keyCode===229)return;const k=event.key.toLowerCase();if(k==='escape'){event.preventDefault();event.stopImmediatePropagation();if(pending||gesture){cancel();changed('Preview cancelled');}else close();return;}
  if((event.ctrlKey||event.metaKey)&&k==='s'){event.preventDefault();event.stopImmediatePropagation();run(publish);return;}if(typing(event.target))return;
  if((event.ctrlKey||event.metaKey)&&k==='z'){event.preventDefault();event.stopImmediatePropagation();run(()=>{cancel();event.shiftKey?editor.redo():editor.undo();changed();});return;}
  if(event.target!==canvas||event.ctrlKey||event.metaKey||event.altKey)return;
  if(['arrowleft','arrowright','arrowup','arrowdown','r','d','delete','backspace','enter',' ','+','-'].includes(k)){event.preventDefault();event.stopImmediatePropagation();run(()=>{if(mode==='camera'){if(k.startsWith('arrow'))view?.orbit(k==='arrowleft'?-.15:k==='arrowright'?.15:0,k==='arrowup'?-.1:k==='arrowdown'?.1:0);if(k==='+'||k==='-')view?.zoom(k==='+'?-.5:.5);return;}if(k==='enter'||k===' '){commitPreview();return;}if(k.startsWith('arrow')){const delta=[k==='arrowleft'?-(snap||.1):k==='arrowright'?(snap||.1):0,event.shiftKey?(k==='arrowup'?(snap||.1):k==='arrowdown'?-(snap||.1):0):0,event.shiftKey?0:k==='arrowup'?-(snap||.1):k==='arrowdown'?(snap||.1):0];if(pending){pending.position=pending.position.map((v,i)=>v+delta[i]);view?.update(editor.doc,editor.selection,pending);}else mutate(()=>editor.move(delta));}else if(k==='r')mutate(()=>editor.rotate('y',15));else if(k==='d')mutate(()=>editor.duplicate());else if(k==='delete'||k==='backspace')mutate(()=>editor.delete());});}
 }
 root.addEventListener('keydown',key);
 return{open,close,getRecoverySnapshot:()=>context?.userId===getState().user?.id&&dirty()?serialize(editor.doc):null,getPreviewState:()=>({active:opened,document:validate(editor.doc),selection:[...editor.selection],undo:editor.history.length,redo:editor.future.length,...(view?.diagnostics()||{frames:0,meshes:0,materials:0,parts:[]})}),isOpen:()=>opened,hasFocus:target=>opened&&root.contains(target||document.activeElement),syncAuthority,refresh,isDirty:dirty,prepareRoom(room){if(room?.scene)bindCompositionDefinitions(room.scene,room.compositionDefinitions||{},room.id);},dispose(){close({force:true,record:false});window.removeEventListener('blur',interrupt);document.removeEventListener('visibilitychange',visibilityHandler);root.remove();}};
}
