/** Pointer intent arbitration: camera drags never fall through into walk or placement. */
export function mountWorldInput({canvas,joystickRoot,joystickThumb,getContext,getRenderer,getEditor,onWalkTo,onInteract,onJoystick,onCameraChange=()=>{}}){
 const pointers=new Map();let cameraGesture=null,touchMetric=null,panMode=false;const consumed=new Set();
 const blocked=()=>{const c=getContext();return !c.ready||c.modalOpen||!getRenderer();};
 function metrics(){const p=[...pointers.values()].filter(p=>p.type==='touch');if(p.length<2)return null;return{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2,distance:Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),count:p.length};}
 function beginCamera(kind,id){getEditor()?.cancelGesture();getRenderer()?.setGhost(null);cameraGesture={kind,id};for(const key of pointers.keys())consumed.add(key);canvas.classList.add('camera-dragging');onCameraChange(kind);}
 function down(e){if(blocked())return;if(![0,1,2].includes(e.button))return;const p={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,button:e.button,type:e.pointerType};pointers.set(e.pointerId,p);try{canvas.setPointerCapture(e.pointerId);}catch{}const m=metrics();if(m){beginCamera('touch',e.pointerId);touchMetric=m;e.preventDefault();return;}if(e.button===1||e.button===2||e.altKey||panMode){beginCamera(e.button===1||e.shiftKey||panMode?'pan':'orbit',e.pointerId);e.preventDefault();return;}if(getContext().building)getEditor()?.pointerDown(getRenderer().pick(e.clientX,e.clientY),e);canvas.focus({preventScroll:true});}
 function move(e){if(blocked())return;const p=pointers.get(e.pointerId);if(!p){if(getContext().building&&!cameraGesture)getEditor()?.pointerMove(getRenderer().pick(e.clientX,e.clientY),e);return;}if(consumed.has(e.pointerId)&&!cameraGesture)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;p.x=e.clientX;p.y=e.clientY;const m=metrics();if(m){if(!cameraGesture)beginCamera('touch',e.pointerId);if(touchMetric){const r=getRenderer(),distance=r.getCameraState?.().distance||25;if(m.distance>1&&touchMetric.distance>1)r.zoom(distance*(touchMetric.distance/m.distance-1));if(m.count>=3||panMode)r.pan(m.x-touchMetric.x,m.y-touchMetric.y);else r.orbit(m.x-touchMetric.x,m.y-touchMetric.y);}touchMetric=m;e.preventDefault();return;}
  if(cameraGesture){if(cameraGesture.kind==='pan')getRenderer().pan(dx,dy);else if(cameraGesture.kind==='orbit')getRenderer().orbit(dx,dy);e.preventDefault();return;}
  if(!getContext().building&&Math.hypot(p.x-p.startX,p.y-p.startY)>7){beginCamera('orbit',e.pointerId);getRenderer().orbit(dx,dy);e.preventDefault();return;}
  if(getContext().building)getEditor()?.pointerMove(getRenderer().pick(e.clientX,e.clientY),e);
 }
 function up(e){const p=pointers.get(e.pointerId);if(!p)return;const wasCamera=consumed.has(e.pointerId)||!!cameraGesture;pointers.delete(e.pointerId);consumed.delete(e.pointerId);try{canvas.releasePointerCapture(e.pointerId);}catch{}if(wasCamera){/* Finger removal changes the pinch pair and its center; rebase before the next move. */touchMetric=metrics();if(pointers.size===0){cameraGesture=null;touchMetric=null;consumed.clear();canvas.classList.remove('camera-dragging');onCameraChange(null);}return;}if(blocked()||e.button!==0)return;const hit=getRenderer().pick(e.clientX,e.clientY);if(getContext().building){getEditor()?.pointerUp(hit,e);return;}if(Math.hypot(e.clientX-p.startX,e.clientY-p.startY)>7)return;if(hit.id&&onInteract(hit))return;if(hit.point)onWalkTo(hit.point);}
 function cancelWorld(){for(const id of pointers.keys())try{canvas.releasePointerCapture(id);}catch{}pointers.clear();consumed.clear();cameraGesture=null;touchMetric=null;getEditor()?.cancelGesture();canvas.classList.remove('camera-dragging');onCameraChange(null);}
 function cancel(){cancelWorld();if(stickId!==null)try{joystickRoot.releasePointerCapture(stickId);}catch{}stickId=null;onJoystick({x:0,z:0});joystickThumb.style.transform='';}
 // Escape consumes the entire held pointer gesture. Its later move/up cannot
 // recreate a one-cell preview or place at the original anchor.
 const escape=e=>{if(e.key==='Escape'&&getContext().building)for(const id of pointers.keys())consumed.add(id);};
 window.addEventListener('keydown',escape,true);
 const wheel=e=>{if(blocked())return;e.preventDefault();getRenderer().zoom(Math.sign(e.deltaY)*Math.min(2,Math.abs(e.deltaY)*.012+.35));};const context=e=>e.preventDefault();
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancelWorld);canvas.addEventListener('contextmenu',context);canvas.addEventListener('wheel',wheel,{passive:false});
 let stickId=null;const stickMove=e=>{if(blocked()||getContext().building)return;const r=joystickRoot.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,z=e.clientY-r.top-r.height/2,d=Math.max(32,Math.hypot(x,z));const value={x:x/d,z:z/d};onJoystick(value);joystickThumb.style.transform=`translate(${value.x*27}px,${value.z*27}px)`;};const stickDown=e=>{if(blocked()||getContext().building||stickId!==null)return;stickId=e.pointerId;joystickRoot.setPointerCapture(e.pointerId);stickMove(e);e.preventDefault();};const stickDrag=e=>{if(e.pointerId===stickId)stickMove(e);};const stickUp=e=>{if(e&&e.pointerId!==undefined&&e.pointerId!==stickId)return;stickId=null;onJoystick({x:0,z:0});joystickThumb.style.transform='';};
 joystickRoot.addEventListener('pointerdown',stickDown);joystickRoot.addEventListener('pointermove',stickDrag);joystickRoot.addEventListener('pointerup',stickUp);joystickRoot.addEventListener('pointercancel',stickUp);window.addEventListener('blur',cancel);
 return{cancel,setPanMode(value){panMode=!!value;canvas.classList.toggle('camera-pan-mode',panMode);cancel();},getPanMode:()=>panMode,isCameraGesture:()=>!!cameraGesture,destroy(){cancel();window.removeEventListener('keydown',escape,true);canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancelWorld);canvas.removeEventListener('contextmenu',context);canvas.removeEventListener('wheel',wheel);joystickRoot.removeEventListener('pointerdown',stickDown);joystickRoot.removeEventListener('pointermove',stickDrag);joystickRoot.removeEventListener('pointerup',stickUp);joystickRoot.removeEventListener('pointercancel',stickUp);window.removeEventListener('blur',cancel);}};
}
